### ISSUE TITLE
GVim 9.0 on Windows does not recognize the right Alt key

### ISSUE THREAD

**Issue by k-euser** [vim/vim#10826] opened 2022-07-31 19:22 UTC
### Steps to reproduce

1. Start GVim on Windows.
2. Type any Alt-key combination (other than a menu bar accelerator) using the right Alt key.  For example, `RightAlt-i` works to demonstrate the problem.

### Expected behaviour

If you hit `RightAlt-i`, Vim should invoke any mapping that exists for `<m-i>` or beep if no such mapping exists.  Instead, it acts as if you simply typed `i`.
<br>
More detailed description of the problem:

GVim 9.0 on Windows does not recognize the right Alt key; if you hit `RightAlt-Somekey`, it acts as if you just hit `Somekey` alone.

The one exception to this is that the menu bar accelerators work:  if you hit `RightAlt-f`, for example, it _does_ invoke the File menu.

I'm using a US keyboard, so the right Alt key is not an AltGr key, in case that matters.

The left Alt key works fine.

Both Alt keys work in the text-mode version of Vim; only GVim is affected.

Both Alt keys work in GVim 8.2.

I've confirmed that the problem exists when starting GVim via `gvim --clean` so it's not a settings issue.

I've confirmed that the problem exists on two different computers, one running Windows 8.1 and one running Windows 10.

I've confirmed that the problem exists in the most recent stable version listed for download on vim.org (https://github.com/vim/vim-win32-installer/releases/download/v9.0.0000/gvim_9.0.0000_x86_signed.exe) and in a recent nightly (https://github.com/vim/vim-win32-installer/releases/download/v9.0.0117/gvim_9.0.0117_x64.exe).

### Version of Vim

9.0 and 9.0.0117

### Environment

Microsoft Windows 8.1 (64-bit) and Microsoft Windows 10 (64-bit)

**Comment by brammool** [comment] 2022-08-01 10:02
@LemonBoy  @ant0sha

**Comment by salsifis** [comment] 2022-08-01 12:34
Hello, this seems to be a duplicate of issue #10753.
@k-euser Could you try this build: https://github.com/vim/vim-win32-installer/releases/tag/v9.0.0124

**Comment by k-euser** [comment] 2022-08-01 16:32
That's not precisely a duplicate, although it might be related; https://github.com/vim/vim/issues/10753 is about `AltGr-Space` not working whereas this is about `RightAlt-anything` not working, on a keyboard layout where RightAlt is not AltGr.

In any case, I've just tried [v9.0.0124](https://github.com/vim/vim-win32-installer/releases/download/v9.0.0124/gvim_9.0.0124_x86.exe) and the problem is still there.

Please reopen.

**Comment by ant0sha** [comment] 2022-08-03 19:37
> @LemonBoy @ant0sha

Recently tried to create test case for this bug using new ```test_gui_w32_sendevent``` low level key press simulation mechanism, but it fails: internally whatever key code i simulate gui_w32.c logic judges it as "left alt", thus performing all tests without revealing bug reported here. Only manually operating the keyboard i can reproduce the problem. Still have some hope, will try to extend logic in ```test_gui_w32_sendevent``` to use scan_code instead of wVk. Seems will not come to it very soon, have some busy weeks now.

**Comment by georgd** [comment] 2022-08-19 12:45
> That's not precisely a duplicate, although it might be related; #10753 is about `AltGr-Space` not working whereas this is about `RightAlt-anything` not working, on a keyboard layout where RightAlt is not AltGr.
> 
> In any case, I've just tried [v9.0.0124](https://github.com/vim/vim-win32-installer/releases/download/v9.0.0124/gvim_9.0.0124_x86.exe) and the problem is still there.

I can confirm the issue for this keyboard layout: https://www.europatastatur.de/e1

**Comment by zoumi** [comment] 2022-10-05 00:36
Is there any plan to fix this?

**Comment by brammool** [comment] 2022-10-05 11:58
It requires someone with this keyboard to figure out what happens and come up with a solution (that doesn't break things for other keyboards).

**Comment by k-euser** [comment] 2022-10-05 18:22
You don't need a physical keyboard with one of the affected layouts to reproduce the problem.  You can reproduce it just fine using the "On-Screen Keyboard" included with Windows after setting the keyboard layout in Windows' Language settings.

(Actually, I suspect simply changing the keyboard layout would be sufficient to reproduce it on essentially any physical keyboard as well, but I don't have any way of checking that as I don't have a non-US keyboard available.)

**Comment by zoumi** [comment] 2022-10-06 00:37
RAlt
```
VK  SC	Type	Up/Dn	Elapsed	Key	
-------------------------------------------------------------------------------------------------------------
A5  138	 	d	12.45	RAlt
A5  138	 	u	0.17	RAlt    
```
LAlt
```
VK  SC	Type	Up/Dn	Elapsed	Key	
-------------------------------------------------------------------------------------------------------------       	
A4  038	 	d	24.81	LAlt           	
A4  038	 	u	0.09	LAlt         
```
RAlt +p
```
VK  SC	Type	Up/Dn	Elapsed	Key	
-------------------------------------------------------------------------------------------------------------
A5  138	 	d	8.06	RAlt 
50  019	 	d	0.20	p              	
50  019	 	u	0.19	p              	
A5  138	 	u	0.06	RAlt     
```

**Comment by brammool** [comment] 2022-10-06 11:40
Can you try out #11294 ?

**Comment by ant0sha** [comment] 2022-10-06 19:29
> Can you try out #11294 ?

No need any more ((( , just checked myself - it breaks AltGr handling completely (but US RightAlt starts to work though).

**Comment by ant0sha** [comment] 2022-10-10 07:33
should it be not closed since https://github.com/vim/vim/commit/8d8b9758ced52b6303af95ad7e28ae9c5636cdf8 ?

**Comment by chrisbra** [comment] 2022-10-10 11:43
closing then again :)

**Closed as completed by chrisbra** 2022-10-10 11:43 UTC
Labels: bug

**Comment by zoumi** [comment] 2022-10-10 11:45
Yes,it works now.Thank you!
