### ISSUE TITLE
Copy (ctrl+c. ctrl+shift+c) does not work in Vim or ignored (windows 11)

### ISSUE THREAD

**Issue by kyxap** [vim/vim#14930] opened 2024-06-06 12:08 UTC
### Steps to reproduce

- choco install vim
- open file with vim
- select text and try to copy (ctrl+c. ctrl+shift+c)
- try to past (ctrl-v)

### Expected behaviour

Copied text is past

Actual: old clipboard is used and just copied is ignored, also seems like old clipboard is corrupted when pasted

### Version of Vim

v9.1.466

### Environment

windows 11
tested on: PowerShell 7, PowerShell 5, git-bash 2.45.2, nushell  0.94.1 (same behavior)

### Screenshots

![ctrl+c](https://github.com/nushell/nushell/assets/3080529/890efa8e-96ca-4d25-9574-263ba3a704eb)

**Comment by chrisbra** [comment] 2024-06-06 12:19
If you want typical Windows shortcuts, you need to explicitly source `$VIMRUNTIME/mswin.vim`. I would however rather recomment to learn Vim shortcuts instead. See `:h mswin.vim`

Closing as not a bug. Please ask user questions at appropriat forums instead.

**Closed as not planned by chrisbra** 2024-06-06 12:19 UTC
