### ISSUE TITLE
User local script causes SIGILL and crash

### ISSUE THREAD

**Issue by geeknik** [vim/vim#9278] opened 2021-12-04 16:48 UTC
### Steps to reproduce

1. Compile vim with Clang12 + UBSan
2. `echo "LSaw" | base64 -d > /tmp/script.fuzz`
3. `vim -u NONE -X -Z -e -s -S /tmp/script.fuzz -c ":qa!"`

### Expected behaviour

No crash.

### Operating system

Ubuntu 20.04.3 LTS

### Version of Vim

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Dec  4 2021 14:54:54) Included patches: 1-3719

### Logs and stack traces

```shell
#0  0x0000000000501658 in get_address (eap=<optimized out>, ptr=0x7fffffffa620,
    addr_type=ADDR_LINES, skip=<optimized out>, silent=<optimized out>,
    to_other_file=<optimized out>, address_count=<optimized out>) at ex_docmd.c:4447
#1  0x00000000004f481d in parse_cmd_address (eap=0x7fffffffa610,
    errormsg=0x7fffffffa5f8, silent=0) at ex_docmd.c:3241
#2  0x00000000004e0399 in do_one_cmd (cmdlinep=<optimized out>,
    flags=<optimized out>, cstack=<optimized out>, fgetline=<optimized out>,
    cookie=<optimized out>) at ex_docmd.c:1951
#3  0x00000000004dad00 in do_cmdline (cmdline=<optimized out>,
    fgetline=<optimized out>, cookie=<optimized out>, flags=7) at ex_docmd.c:1000
#4  0x00000000009ee774 in do_source (fname=<optimized out>,
    check_other=<optimized out>, is_vimrc=0, ret_sid=<optimized out>)
    at scriptfile.c:1420
#5  0x00000000009f77a1 in ex_source (eap=<optimized out>) at scriptfile.c:985
#6  0x00000000004e5fce in do_one_cmd (cmdlinep=<optimized out>,
    flags=<optimized out>, cstack=<optimized out>, fgetline=<optimized out>,
    cookie=<optimized out>) at ex_docmd.c:2578
#7  0x00000000004dad00 in do_cmdline (cmdline=<optimized out>,
    fgetline=<optimized out>, cookie=<optimized out>, flags=11) at ex_docmd.c:1000
#8  0x0000000000da3996 in do_cmdline_cmd (cmd=0x1155e73 "") at ex_docmd.c:594
#9  exe_commands (parmp=<optimized out>) at main.c:3080
#10 vim_main2 () at main.c:774
#11 0x0000000000d9459b in main (argc=<optimized out>, argv=<optimized out>)
    at main.c:426
```

**Comment by brammool** [comment] 2021-12-04 18:54
I cannot reproduce the problem...

**Comment by dpelle** [comment] 2021-12-04 20:13
I also cannot reproduce it with 8.2.3738 on xubuntu-18.04.6.

To @geeknik :  how did you configure vim?  Consider posting the output  of `:version` and try with the latest (your version is quite recent though).

**Comment by lacygoill** [comment] 2021-12-11 11:27
I can't reproduce either.  Neither on master, nor on the reported version (v8.2.3719).  Same OS as the OP: Ubuntu 20.04.

**Comment by brammool** [comment] 2021-12-11 13:01
Since we haven't received more information in a week I'm closing this.

**Closed as completed by brammool** 2021-12-11 13:01 UTC
