### ISSUE TITLE
[vim9script] Unexpected error using `+=` to modify a `final` list

### ISSUE THREAD

**Issue by errael** [vim/vim#13745] opened 2023-12-20 19:14 UTC
### Steps to reproduce

The error
```
E46: Cannot change read-only variable "ll2"
```
is produced by the script
```
vim9script

# Note both ll2 and ll2x are the same list; the list can be modified.

final ll2: list<string> = []
var ll2x = ll2

ll2->add('b')
echo 'same:' ll2 is ll2x

# Note the following modifies the list, is does not modify either variable.
ll2x += ['cx']
echo 'same:' ll2 is ll2x

ll2 += ['d']
```

### Expected behaviour

No error. When `+=` is used on a `list`, the variable is not modifed. Only the referenced list is modifed.

### Version of Vim

9.0.2181

### Environment

ubuntu/gtk3/gnome

**Comment by yegappan** [comment] 2023-12-20 21:38
This is the expected behavior.  A final variable cannot be reassigned to some other value but the value itself can be changed.

The statement `ll2 += ['d']` is actually `ll2 = ll2 + ['d']`.  This takes the value of the List `ll2` and adds 'd' to it and
then assigns the resulting List to ll2.  As ll2 is a final variable, it cannot be changed.  The statement using ll2x works
because ll2x is not a final variable.

**Comment by errael** [comment] 2023-12-20 22:58
> This is the expected behavior. A final variable cannot be reassigned to some other value but the value itself can be changed.
> 
> The statement `ll2 += ['d']` is a shortcut for the statement `ll2 = ll2 + ['d']`. 

That's not how it works for lists; for lists it seems to mean `add()`. Notice that
```
# Note the following modifies the list, is does not modify either variable.
ll2x += ['cx']
echo 'after "+=" same:' ll2 is ll2x

# Note that in following ll2x is changed
ll2x = ll2x + ['cx']
echo 'after "v +" same:' ll2 is ll2x
```
The variable is only modified in the 2nd case
```
after "+=" same: true
after "v +" same: false
```

> This takes the current value of the List variable `ll2` and adds 'd' to it and then assigns the resulting List to ll2. As ll2 is a final variable, it cannot be changed (resulting in the error).
> 
> The statement using the ll2x variable works because ll2x is not a final variable.

**Comment by qeatzy** [comment] 2024-02-01 16:34
I think it's indeed intended behavior.
For list, 
- `+` is  concat, `lst + other` roughly equivalent to `copy(lst)->add(other) ` , that's why in your code it outputs `false`.
- `+=` is roughly equivalent to `lst = lst->add(other) ` , though for assignment the rhs is same object as lhs.
In final effect `+=` achieve same side effect as `add()`, but technically different.
With final variable, the assignment will fail, even though you are assigning to same object.
Also, it's unrelated to vim9. It's same in legacy vim.

```
let lst = [1,2,3]
let l2 = lst + [3,4,5]
let l3 = lst->add([3,4,5])
echo [lst is l2, lst]
echo [lst is l3, lst]
```

**Comment by qeatzy** [comment] 2024-02-01 16:44
I think it's indeed intended behavior.
For list,
- `+` is  concat, `lst + other` roughly equivalent to `copy(lst)->extend(other) ` , that's why in your code it outputs `false`.
- `+=` is roughly equivalent to `lst = lst->extend(other) ` , though for assignment the rhs is same object as lhs.
In final effect `+=` achieve same side effect as `extend()`, but technically different.
With final variable, the assignment will fail, even though you are assigning to same object.
Though for language spec/implementation, it might mandate the assignment being ignored.

**Comment by qeatzy** [comment] 2024-02-02 02:31
> The statement ll2 += ['d'] is a shortcut for the statement ll2 = ll2 + ['d']. This takes the current value of the List variable ll2 and adds 'd' to it and then assigns the resulting List to ll2. As ll2 is a final variable, it cannot be changed (resulting in the error).

As @yegappan already tells the basic stuff, though that's 100% percent accurate. (more on this later)
That's perhaps where you confusion come from.

> += is roughly equivalent to lst = lst->extend(other)  , though for assignment the rhs is same object as lhs.
> In final effect += achieve same side effect as extend(), but technically different.
> With final variable, the assignment will fail, even though you are assigning to same object.

Seems you don't read or react to these words.

> lst2 is changed by lst1 += ['a'].

That's because it's intended to.
You are missing **lvalue** & **rvalue** here.
lvalue lst1 and lst2 are two disjoint entity, and both evaluate to same rvalue, aka the list literal `[]` .
You apply binary operator `=+` with lhs `ls1` and rhs `['a']`. The end result is extend `['a']` to the `[]` and returning it, then reassign it to lvalue `ls1`. lst2 of course will be changed, since they are pointing to same rvalue.

**Comment by errael** [comment] 2024-02-02 03:55
> > The statement ll2 += ['d'] is a shortcut for the statement ll2 = ll2 + ['d']. This takes the current value of the List variable ll2 and adds 'd' to it and then assigns the resulting List to ll2. As ll2 is a final variable, it cannot be changed (resulting in the error).
> 
> As @yegappan already tells the basic stuff, though that's 100% percent accurate. (more on this later) That's perhaps where you confusion come from.

The problem is that the explanation is **not** "100% accurate". `l1 += l2` and `l1 = l1 + l2` are not semantically equivalent for lists; one is not a shortcut for the other. Perhaps they are supposed to be the same, but they are not; the quirk is already in the language.

As the `:help` indicates, `+=` should not modify the list in place; but it does. That's where my confusion comes from.

(Bringing `extend()` into the conversation didn't help clarify the issue, at least for me)

**Comment by qeatzy** [comment] 2024-02-02 03:59
There is no quick in the language, it's the explanations not 100% accurate. We are human, not machine, and here is not web standard committee. [😂]

**Comment by qeatzy** [comment] 2024-02-02 04:25
> That's not how it works for lists; for lists it seems to mean add(). Notice that

> (Bringing extend() into the conversation didn't help clarify the issue, at least for me)

You are mixing things up. 😂

`add()` is for adding single item to list, and completely unrelated here.
in vimscript, concat is `extend()`. The difference demonstrated by code block 3 .
`[1, 2, 3, [4, 5, 6]]` vs `[1, 2, 3, 4, 5, 6]`
code block 1 and code block 2 is equivalent. Same in vim9script.

```
" block 1
let lst = [1, 2, 3]
let lst += [4, 5, 6]

" block 2
let lst = [1, 2, 3]
let lst = extend(lst, [4, 5, 6])

" block 3
echo add([1,2,3], [4,5,6])
echo extend([1,2,3], [4,5,6])
```

To summarize, for list a and b
`a + b` equivalent to `copy(a)->extend(b)`. which is reentrant.
`a += b` equivalent to 
```
tmp = extend(a, b)
a = tmp
```
which is not reentrant.

You encounter the error not due to concat, but due to assignment.

**Comment by qeatzy** [comment] 2024-02-02 04:40
> As the :help indicates, += should not modify the list in place; but it does. That's where my confusion comes from.

`lst += other` modify the rvalue lst in place, but it also re-assign the returned value to lvalue lst.
It's in place in the sense of modifying rvalue lst in place, and not in place in the sense of modify lvalue lst via re-assignment.
Here we enter the tricky part of lvalue and rvalue, rememeber C++ terminology here, cough cough, 

`extend(lst, other)` modify the rvalue lst in place, and is completely inplace.

I do agree the doc may be not perfect here, and un-friendly to those being strictly rigorous.
And in common meaning `+=` do modify list in place. But I believe this is quite obvious. Though a clearer documentation will be better.

**Comment by chrisbra** [comment] 2024-02-02 07:37
> As the :help indicates, += should not modify the list in place; but it does. That's where my confusion comes from.

It's however mentioned briefly at [:h list-identity](https://vimhelp.org/eval.txt.html#list-identity) that you may change the same list. It does not mention `+=` in particular  but uses `add()` but the principle is explained there.

**Comment by errael** [comment] 2024-02-02 14:51
> > As the :help indicates, += should not modify the list in place; but it does. That's where my confusion comes from.
> 
> It's however mentioned briefly at [:h list-identity](https://vimhelp.org/eval.txt.html#list-identity) that you may change the same list. It does not mention `+=` in particular but uses `add()` but the principle is explained there.

- `:help list-concatenation` shows the use of `+=` as a shortcut for list concatenation
   and says "to change a list in-place, refer to list-modification"
- `:help list-identity` says that multiple variables can refer to the same list. (I celebrate that)
- `:help-list-modification` says "_Adding and removing items from a list is done with functions_"
   after showing the specialized list syntax for modifying a list in-place.

I understand that vim's `+=` behaves like in python with a mutable list (and vim's definition of `+=` on a list can't be changed, nor would I want it to be). Vim's `+=` is not documented to act like `add()`/`extend()`, quite the opposite. But this whole thing about the documentation is a side issue. The fact is that `+=` on a list has nothing to do with an assignment; `l1 = l1 + l2` is very different.

Do we all agree that `+=` is like `add()`/`extend()`? Except that it isn't. `:help final` says
```
`:final` is used for making only the variable a constant, the value can be changed.
```
So if `+=` is like `add()`/`extend()` then it could be used on a final variable (which is what this issue is about). BTW, I'm OK with closing this as "won't fix".

Just to add some color...
- I don't know how modern strongly type languages handle this.
  Is `a.plusAssign(b)` implemented by default for kotlin lists `a` and `b`?
- There's also confusion in the python community about `+=` on a list.

**Comment by qeatzy** [comment] 2024-02-04 10:23
Let me try to consolidate the related points without introducing additional confusions.

Some prerequisite/terminology:
- `lhs` and `rhs` stands for left hand operand and right hand operand.
- `reentrant`, if an expression evaluated multiple times and always evaluate to same result.
- `lvalue` and `rvalue`, refer to c++ terminology. l for left, r for right. usually `lvalue` mean the reference/pointer itself, `rvalue` mean the object it pointing to.


Points that are known for sure (both in implementation, in doc, and common sense)

1. `+` on list is concat, and must **not** modify either lhs or rhs, and is reentrant
2. `+=` on list is also concat, and must be in place, and is **not** reentrant. (P.S. doc is vague)
3. `extend()` is the function for concat to list.
4. `add(lst, 'a')` is equivalent to `extend(lst,, ['a'])`, but `add()` *is* technically unrelated to list concatenation.
5. `add()` and `extend()` do not change identity of any it's args, they both modify first argument in place.
6. `final` disallow change `lvalue` itself but *allow* change `rvalue` it pointing to.
7. `lst = lst` is disallowed if `lst` is declared `final`.
8. `+=` is assignment too. The `final` constraint applies too. Though an exception could be made in the language spec level. 

Workarounds for similar error for `fina`l list `lst`
1. replace `lst += ['a']` with either `add(lst, 'a')` or `extend(lst, ['a'])`
2. replace `lst += ['a', 'b', 'c']` with `extend(lst, ['a', 'b', 'c'])`

Based on point 1 and 2, for list a and b, `a += b` and `a = a + b` **cannot** be equivalent since they are fundamentally different (inplace + reentrant).
Thus saying `a += b` is shortcut `a = a + b` is not accurate (technically wrong), even though both are list concat.

A minor nitpicking about interpretation & logic of doc at `list-concatenation` and inplace-ness of `+=`

> As the :help indicates, += should not modify the list in place; but it does. That's where my confusion comes from.
> 
> > :help list-concatenation shows the use of += as a shortcut for list concatenation
> > and says "to change a list in-place, refer to list-modification"

Here "to change a list in-place, refer to list-modification" is similar to an announcer saying "please refer to Elon Musk as for representative of those who's income is over ten thousand per month". Both says nothing about *itself*. Though it could be *implied*.

My suggestion/view for document change is do not add too much to not intimidate new users.
Some points should be clear from the doc
- for list `+=` is concat in place.

I prefer not adding below (at least not at `list-conatenation`)
- `+=` is assignment, and thus will fail on final variable, use `add()/extend()` instead in this case.
- more complex explanation about the reason and technical details.

At last, as for point 8 (and the error these issues encounter)
I'm against to make a hole to `+=` and `final`, which create a quirk in the language for no benefit. Where the alternative is well defined. (just use `add()/extend()` in this case. Perhaps mention at doc describing `final`.

**Closed as completed** 2024-02-06 10:07 UTC
Labels: bug
