### ISSUE TITLE
Clarify docs around :set< for unsetting the local value of a global-local option

### ISSUE THREAD

**Issue by ddickstein** [vim/vim#12594] opened 2023-06-25 21:01 UTC
### Problem

https://github.com/vim/vim/blob/8154e642aa476e1a5d3de66c34e8289845b2b797/runtime/doc/options.txt#L362-L373
My reading of this snippet is:
* To unset the local value of number and boolean options, use `:setlocal name<`. The behavior of `:set name<` is not defined.
* To unset the local value of string options, use `:set name<` (or `:setlocal name=`). `:setlocal name<` will instead copy the global value.

This reading is different from these docs:
https://github.com/vim/vim/blob/8154e642aa476e1a5d3de66c34e8289845b2b797/runtime/doc/options.txt#L320-L324

Here's a table that shows the differences:
|||First reading implication|Second reading implication
|---|---|---|---|
|`:set name<`|`number`/`boolean`|undefined|unset local value
|`:set name<`|`string`|unset local value|unset local value
|`:setlocal name<`|`number`/`boolean`|unset local value|copy global value
|`:setlocal name<`|`string`|copy global value|copy global value

### Expected behaviour

The docs on unsetting local values for global-local options should be consistent.

### Version of Vim

9.0.1664

### Environment

Linux

**Comment by chrisbra** [comment] 2023-06-26 07:27
May be I am missing something, but I don't understand where it is contractionary. Can you please explain in more detail what you mean?

**Comment by ddickstein** [comment] 2023-06-26 10:02
I've added a table to highlight the differences I see

**Comment by brammool** [comment] 2023-06-27 16:44
In the third row of the table ":setlocal name<", third column "First reading implication" you have "unset local value".
That is incorrect, since the text says: " Note that for non-boolean and non-number options using "<" copies the global 
 value to the local value, it doesn't switch back to using the global value ".  It should say the same as in the fourth column: "copy global value".

I know that the text is hard to read.  That is caused by keeping the :set command backwards compatible while adding the local value.  If you have a suggestion to phrase it better, please let us know.

**Comment by ddickstein** [comment] 2023-06-27 17:55
The third row of the table is for `number`/`boolean` options. That line applies to non-boolean and non-number options.

**Comment by brammool** [comment] 2023-06-27 20:36
Yeah, that part of the sentence "for non-boolean and non-number options" is misplaced.  The code does copy the global value to the local value, except for a few options that are reset (usually using the value -1) to use the global option value.  Let me also do this for 'scrolloff' and 'sidescrolloff' for consistency.

**Comment by chrisbra** [comment] 2023-06-27 20:36
I checked in the source:

https://github.com/vim/vim/blob/19e6c4fd2d262075d39cb802ea5b85f5ec92f153/src/option.c#L2067-L2082

Note the comment at the beginning:


> ":set opt<": reset to global value 

|cmd|option scope|meaning
|---|---|---|
|`:setlocal name<`|`number`/`boolean`|use *global* option-value

**Comment by chrisbra** [comment] 2023-06-27 20:45
I have updated my answer with what I think is the answer (hopefully) for the two contradictory lines (1 and 3)

**Closed as completed** 2023-06-27 20:51 UTC
Labels: documentation, bug
