### ISSUE TITLE
Pixel perfect box-drawing characters in GVim

### ISSUE THREAD

**Issue by noscript** [vim/vim#11477] opened 2022-10-31 17:43 UTC
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**

GVim delegates drawing [box-drawing characters](https://en.wikipedia.org/wiki/Box-drawing_character) to a font-rendering engine. This makes the characters overlap, blurry and never align property. Most terminals draw those characters by themself.

```
Box drawing alignment tests:                                          █
                                                                      ▉
  ╔══╦══╗  ┌──┬──┐  ╭──┬──╮  ╭──┬──╮  ┏━━┳━━┓  ┎┒┏┑   ╷  ╻ ┏┯┓ ┌┰┐    ▊ ╱╲╱╲╳╳╳
  ║┌─╨─┐║  │╔═╧═╗│  │╒═╪═╕│  │╓─╁─╖│  ┃┌─╂─┐┃  ┗╃╄┙  ╶┼╴╺╋╸┠┼┨ ┝╋┥    ▋ ╲╱╲╱╳╳╳
  ║│╲ ╱│║  │║   ║│  ││ │ ││  │║ ┃ ║│  ┃│ ╿ │┃  ┍╅╆┓   ╵  ╹ ┗┷┛ └┸┘    ▌ ╱╲╱╲╳╳╳
  ╠╡ ╳ ╞╣  ├╢   ╟┤  ├┼─┼─┼┤  ├╫─╂─╫┤  ┣┿╾┼╼┿┫  ┕┛┖┚     ┌┄┄┐ ╎ ┏┅┅┓ ┋ ▍ ╲╱╲╱╳╳╳
  ║│╱ ╲│║  │║   ║│  ││ │ ││  │║ ┃ ║│  ┃│ ╽ │┃  ░░▒▒▓▓██ ┊  ┆ ╎ ╏  ┇ ┋ ▎
  ║└─╥─┘║  │╚═╤═╝│  │╘═╪═╛│  │╙─╀─╜│  ┃└─╂─┘┃  ░░▒▒▓▓██ ┊  ┆ ╎ ╏  ┇ ┋ ▏
  ╚══╩══╝  └──┴──┘  ╰──┴──╯  ╰──┴──╯  ┗━━┻━━┛  ▗▄▖▛▀▜   └╌╌┘ ╎ ┗╍╍┛ ┋  ▁▂▃▄▅▆▇█
                                               ▝▀▘▙▄▟
```

libvte-based terminal:

![image](https://user-images.githubusercontent.com/717109/199122316-f53b0ddd-542a-416d-beb7-0cb99fecc4b8.png)

GVim (GTK3):

![image](https://user-images.githubusercontent.com/717109/199122562-cb1d765f-980c-4a9a-93ef-59d3eecf0bb2.png)

**Describe the solution you'd like**
Don't use font-rendering engine to draw box-drawing characters.

**Describe alternatives you've considered**
Borrow the code from libvte.

**Comment by bfrg** [comment] 2022-10-31 22:15
There's also another issue that occurs when drawing popup borders, see https://github.com/vim/vim/issues/6043. Can you reproduce this?

**Comment by jlittlenz** [comment] 2022-10-31 22:30
The images are good, but it would be helpful to get the text to put into vim.

**Comment by noscript** [comment] 2022-10-31 22:34
> There's also another issue that occurs when drawing popup borders, see #6043. Can you reproduce this?

Yes, it is the same problem.

**Comment by ychin** [comment] 2022-11-01 22:13
Is this always desired? I was curious and looked around, and seems like on iTerm at least there was an issue complaining about the native box drawing (iTerm does do custom box drawing) taking control away from the font which may have the box drawing glyphs fit their style more. The solution there was they added an advanced option to revert back to the font's glyphs: https://gitlab.com/gnachman/iterm2/-/issues/6151

I wonder if another solution would be to stretch the glyph to line up better, but it depends on the font rendering engine, and for the grayscale boxes (e.g. U+2591 "░") that wouldn't work.

**Comment by jlittlenz** [comment] 2022-11-01 22:53
FWIW, the kate editor in KDE plasma 5.24, and geany, look like gvim.

**Comment by noscript** [comment] 2022-11-01 22:59
>Is this always desired?

Probably not. I guess it is not too big of an issue on HiDPI displays.

**Comment by ychin** [comment] 2022-11-01 23:13
I wasn't trying to say this is not useful btw, as the gaps do seem annoying. Just trying to understand if there will be some users who may prefer to use the font's rendering instead (probably applies more to the borders and lines than the blocks).

**Comment by bfrg** [comment] 2022-11-01 23:29
The `alacritty` terminal also has an option [`font.builtin_box_drawing`](https://github.com/alacritty/alacritty/blob/578e08486dfcdee0b2cd0e7a66752ff50edc46b8/alacritty.yml#L177-L182) that can be set to either `true` or `false`. Wouldn't something like this be the best approach so that users can decide themselves?

**Comment by chrisbra** [comment] 2022-11-02 10:31
I suppose you may also want to configure anit-aliasing settings? E.g. on Windows enable ClearType and set the the 'renderoptions' setting.

**Comment by noscript** [comment] 2022-11-02 10:46
Configuring anti-alialiasing will affect the look of all the glyphs, not only box-drawing characters. I like how anti-aliasing is applied to my font overall.

**Comment by brammool** [comment] 2022-11-05 22:43
Isn't this just a GTK3 bug?

The GUI libraries we use must be able to draw characters properly.
Working around bugs in those by adding code in Vim sounds like a really bad idea.
Only if there are some rendering parameters we could use those perhaps.
But then why would we need to inspect characters to decide how to best draw them?
That's also a task of the rendering engine, not of Vim.  Especially since we use fixed cell sizes, it should just work.

**Comment by noscript** [comment] 2022-11-07 14:42
Both libvte and GTK projects are under Gnome umbrella, however they decided to address this issue inside libvte.

I haven't looked how GVim draws the characters, but if Vim already depends on libvte I wonder if it would be feasible to reuse its drawing routine.

**Comment by brammool** [comment] 2022-11-08 00:31
> Both libvte and GTK projects are under Gnome umbrella, however they
> decided to address this issue inside libvte.
> 
> I haven't looked how GVim draws the characters, but if Vim already
> depends on libvte I wonder if it would be feasible to reuse its
> drawing routine.

It is a bit disappointing that you report an issue without even looking
around for more information....

Vim intentionally miminizes dependencies on libraries.  It appears
libvte is a terminal widget, not something you would use inside an
editor.  Well, we have libvterm, which is included as source code to
avoid dragging in a dependency (where versioning is very difficult to
handle, and the code actually required fixing).  I don't know how libvte
and libvterm are related, if at all.

Anyway, if libvte has some example code, that could perhaps be used
inside Vim.  But I very much doubt it actually is something we want to
do.  If someone wants to spend time on making this work perfectly, and
after review it is considered a good improvement, without introducing a
new maintenance burden, there is a chance for it.  I can't estimate how
big that chance is.

-- 
Apparently, 1 in 5 people in the world are Chinese.  And there are 5
people in my family, so it must be one of them.  It's either my mum
or my dad.  Or my older brother Colin.  Or my younger brother
Ho-Cha-Chu.  But I think it's Colin.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by noscript** [comment] 2022-11-08 00:52
I'm sorry. I saw many mentions of libvterm in Vim discussions and I confused it with libvte. Those are totally separate projects, with similar goals however.

As for example code, this is how libvte is doing it https://github.com/GNOME/vte/blob/master/src/minifont.cc

**Comment by ychin** [comment] 2022-11-08 01:55
> Isn't this just a GTK3 bug?
> 
> The GUI libraries we use must be able to draw characters properly. Working around bugs in those by adding code in Vim sounds like a really bad idea. Only if there are some rendering parameters we could use those perhaps. But then why would we need to inspect characters to decide how to best draw them? That's also a task of the rendering engine, not of Vim. Especially since we use fixed cell sizes, it should just work.

I think part of the issue here is that some fonts don't have perfectly stitched border, and also if you have non-standard line-heights, it would be impossible for the fonts to match up perfectly at the border. You also can't get perfectly grayscaled boxes and instead get a dithered shading instead. So not a bug in GTK3 per se, but it does seem like some fonts could have addressed this by fixing their glyphs better. But it's ultimately a nice-to-have but optional feature. Looking at Alacritty's threads seems like there were quite a bit of back and forth:

Original issue proposal which was shot down (filed by the same author as this issue): https://github.com/alacritty/alacritty/issues/3262
Another issue to propose the same thing, where the maintainers eventually decided to implement this reluctantly: https://github.com/alacritty/alacritty/issues/5485
More issues that came out after it was implemented since Alacritty now didn't respect the original font's glyphs: https://github.com/alacritty/alacritty/issues/5809

From the last one, it does seem like this is the kind of thing that will lead to more people complaining about why things work certain ways and not drawn another way, so it's definitely the kind of feature that would require a little bit of upkeep post-commit to keep people happy (since people who want this usually have very particular way they want their boxes drawn).

**Comment by ychin** [comment] 2022-11-08 01:57
Also, I would imagine if this is implemented we should do this at least for GTK and Windows so Vim isn't so platform dependent (and for MacVim as well). I think the implementation part is not hard anyway (therefore we shouldn't use a library to do it), but rather it's the deciding what to do and what options to expose etc (all of which would be Vim specific) that's the annoying part.

**Comment by chrisbra** [comment] 2022-11-08 22:18
This sounds like it's not worth the effort and we may get complaints for whatever behaviour we will settle on. So I vote for closing it. It's not like there are not enough issues to spend time on :)

**Comment by brammool** [comment] 2022-11-09 01:08
> This sounds like it's not worth the effort and we may get complaints
> for whatever behaviour we will settle on. So I vote for closing it.
> It's not like there are not enough issues to spend time on :) 

Right, the problem stems from the idea that you can use a font to draw
boxes and lines, while that is not something a font renderer was really
made for (they are optimized to draw text very well, sharp and smooth,
to make it pleasant to read, which is what we do all the time thus it is
very important to optimize for it).  Then you get into an impossible choice
between making a font renderer that can draw things well that it wasn't
made for and working around it by not using a font renderer for some
selection of characters but hard coding what the glyph must look like
for them.  Basically drawing pixels directly instead of using a font,
and ignoring all information about the properties of the currently
selected font.

Of course there is more history, in the past when characters were used
to draw graphics because characters were the only things you could draw
anyway.  In MS-DOS times whole menu systems were made that way.  Some
installers still rely on that mechanism being available.  But I don't
see much use for it when editing text files with Vim.

So let's settle on it being possible to draw boxes and lines with
characters if you really want to, but accept that they won't look all
that pretty.  Not something that Vim needs to spend time on making
better.  Just using the existing font renderer should be good enough.


-- 
Q. What happens to programmers when they die?
A: MS-Windows programmers are reinstalled.  C++ programmers become undefined,
   anyone who refers to them will die as well. Java programmers reincarnate
   after being garbage collected, unless they are in permgen, in which case
   they become zombies.  Zimbu programmers leave a stack trace that tells us
   exactly where they died and how they got there.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment] 2022-11-15 11:56
closing then

**Closed as completed by chrisbra** 2022-11-15 11:56 UTC
Labels: enhancement
