### ISSUE TITLE
Patchmode does not use backupdir

### ISSUE THREAD

**Issue by cwfoo** [vim/vim#8085] opened 2021-04-07 21:37 UTC
**Describe the bug**
When the `patchmode` option is non-empty, patchmode files are not placed into the directory specified by the `backupdir` option.

With `set backup`, `set backupdir=~/.vim/backups`, and `set patchmode=.orig`, patchmode files are not created in the backupdir, but in the directory of the files edited.

**To Reproduce**
1. `mkdir -p ~/.vim/backups`
1. `cd ~ && echo 'Hello' > hello.txt`
2. `vim --clean hello.txt`
3. `:set backup backupdir=~/.vim/backups patchmode=.orig`
4. Insert some text.
5. Save and exit (`:wq`)
6. Observation: the patchmode file gets created in the directory of the edited file: `~` (`~/hello.txt.orig`).

**Expected behavior**
The patchmode file should have been placed in the `backupdir` instead (`~/.vim/backups/hello.txt.orig`).

**Environment**
 - Vim version: 8.1.2269
 - OS: Ubuntu 20.04
 - Terminal: GNOME Terminal

**Additional context**

If this is not a bug, then this is a feature request: add a `patchmodedir` option.

Relevant mailing list threads from many years ago:

* [Can I set directory for 'patchmode' ?](https://groups.google.com/g/vim_use/c/5qFPNtOiAM8/m/HqXyRC5hnsQJ) (2011)
* [patchmode directory](https://groups.google.com/g/vim_use/c/DiaFG_3oe-E/m/7v5VP2288SAJ) (2008)
* 'patchmode' vs 'backupdir' (2004; not present in the Google Groups archive).

**Comment by chrisbra** [comment] 2021-06-01 09:23
I think this is a duplicate of #5791 (more or less). Note this part in the documentation ([:h 'patchmode'](https://vimhelp.org/options.txt.html#%27patchmode%27)):

> (Detail: The backup file is renamed to the patchmode file after the new file has been successfully written, that's why it must be possible to write a backup file)

**Comment by chrisbra** [comment] 2021-06-22 17:43
closing as being a duplicate.

**Closed as completed** 2021-06-24 14:28 UTC
Labels: duplicate
