### ISSUE TITLE
Cname for vim.org to point to www.vim.org

### ISSUE THREAD

**Issue by ghost** [vim/vim#1062] opened 2016-09-12 21:09 UTC
Not a code issue per se, but noticed that vim.org has no A/AAAA records or a cname pointer to www.vim.org.

As per the old discussion on https://groups.google.com/forum/?_escaped_fragment_=topic/vim_dev/Lq40ieh4D-8#!topic/vim_dev/Lq40ieh4D-8, it looks it never got solved as www.vim.org is still on sourceforge and vim.org remained as is.

Reporting this based on:

```
Feel free to report even the smallest problem, also typos in the documentation.
```

**Comment by vim-ml** [comment] 2016-09-12 21:26
Some browsers, including by default Firefox and SeaMonkey, will look
up www.something.tld if something.tld isn't found. This feature can be
disabled by means of a preference, however, so it may or may not be a
problem for you. For me it isn't.

Best regards,
Tony.

**Comment by chrisbra** [comment] 2016-09-13 19:49
duplicate of #899

**Closed as completed by chrisbra** 2016-09-13 19:49 UTC
