### ISSUE TITLE
After 8.2.765, Ctrl-BSlash mapping does not work in motif GUI

### ISSUE THREAD

**Issue by puremourning** [vim/vim#6150] opened 2020-05-27 10:01 UTC
**Describe the bug**

A mapping for `<C-Bslash>` does not trigger in motif GUI afterr patch 0765 (https://github.com/vim/vim/commit/fd615a3c901f59abddca27c6a09940be552c0f4d#diff-053b22f1b0fa16b318823c1ff6536546)

**To Reproduce**

1. Build with `--with-gui=motif`
1. Run `vim -gfNu NONE`
2. Run `:map <C-Bslash> :echom "Hello"<CR>`
3. Type `Ctrl` and `\`

**Expected behavior**

"Hello" is echo'd

**Actual Behaviour**

Nothing is echoed. Mapping is not triggered.

**Environment (please complete the following information):**
 - Vim version 8.2.0830 with motif GUI
 - OS: Linux RHEL 7
 - Terminal: GUI (motif)

**Additional context**

Similar to these?

* https://github.com/vim/vim/issues/6092
* https://github.com/vim/vim/issues/6147
* https://github.com/vim/vim/issues/6110

**Comment by brammool** [comment] 2020-05-27 19:52
Doesn't work with GTK either

**Comment by puremourning** [comment] 2020-05-28 12:56
Sorry, Bram, still not working with latest patch.

Interestingly, when enabling `showcmd`, it displays `^\` as the command, just the mapping does not trigger.

![Screenshot 2020-05-28 at 13 55 38](https://user-images.githubusercontent.com/10584846/83144197-f287d100-a0ea-11ea-916b-75477930c8e4.png)

**Comment by brammool** [comment] 2020-05-28 13:58
Ben Jackson wrote:

> Sorry, Bram, still not working with latest patch.
> 
> Interestingly, when enabling `showcmd`, it displays `^\` as the command, just the mapping does not trigger.
> 
> ![Screenshot 2020-05-28 at 13 55 38](https://user-images.githubusercontent.com/10584846/83144197-f287d100-a0ea-11ea-916b-75477930c8e4.png)

Yes, the thing is that because of modifyOtherKeys the mapping gets added
twice, with and without modifier.  Once Vim has seen that the terminal
supports modifyOtherKeys, it will only use the mapping with modifier,
the one for just the single backspace character will not be used.

Please find out what causes the problem, since I cannot reproduce now.
Do you execute a shell command perhaps?  Please start with "gvim
--clean" to rule out plugins.

-- 
Some of the well known MS-Windows errors:
	EMEMORY		Memory error caused by..., eh...
	ELICENSE	Your license has expired, give us more money!
	EMOUSE		Mouse moved, reinstall Windows
	EILLEGAL	Illegal error, you are not allowed to see this
	EVIRUS		Undetectable virus found

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by puremourning** [comment] 2020-05-28 14:05
OK thanks for the pointer. I'm running `vim -fgNu NONE` but it repros with `gvim --clean` here too. Steps are as above `gvim --clean` and `:nmap <C-Bslash> :echom "Test"<CR>`.

I'll post the full vim --version output in case that's helpful and some more info and i'll test starting gvim from a couple of different terms. I'll also step through the initilaisations sequence in the debugger, see if that shows anything up. Seems strange that vim's querying the terminal support even though it's starting as `gvim` ? Is that usual?

**Comment by puremourning** [comment] 2020-05-28 14:15
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled May 28 2020 12:04:57)
Included patches: 1-834
Compiled by jenkins-slave@ukfd-emma33l
Huge version with X11-Motif GUI.  Features included (+) or not (-):
+acl               -farsi             +mouse_sgr         +tag_binary
+arabic            +file_in_path      -mouse_sysmouse    -tag_old_static
+autocmd           +find_in_path      +mouse_urxvt       -tag_any_white
+autochdir         +float             +mouse_xterm       -tcl
-autoservername    +folding           +multi_byte        +termguicolors
+balloon_eval      -footer            +multi_lang        +terminal
+balloon_eval_term +fork()            -mzscheme          +terminfo
+browse            +gettext           +netbeans_intg     +termresponse
++builtin_terms    -hangul_input      +num64             +textobjects
+byte_offset       +iconv             +packages          +textprop
+channel           +insert_expand     +path_extra        +timers
+cindent           +ipv6              -perl              +title
+clientserver      +job               +persistent_undo   +toolbar
+clipboard         +jumplist          +popupwin          +user_commands
+cmdline_compl     +keymap            +postscript        +vartabs
+cmdline_hist      +lambda            +printer           +vertsplit
+cmdline_info      +langmap           +profile           +virtualedit
+comments          +libcall           +python/dyn        +visual
+conceal           +linebreak         +python3/dyn       +visualextra
+cryptv            +lispindent        +quickfix          +viminfo
+cscope            +listcmds          +reltime           +vreplace
+cursorbind        +localmap          +rightleft         +wildignore
+cursorshape       -lua               +ruby/dyn          +wildmenu
+dialog_con_gui    +menu              +scrollbind        +windows
+diff              +mksession         +signs             +writebackup
+digraphs          +modify_fname      +smartindent       +X11
-dnd               +mouse             -sound             +xfontset
-ebcdic            +mouseshape        +spell             +xim
+emacs_tags        +mouse_dec         +startuptime       +xpm
+eval              -mouse_gpm         +statusline        +xsmp_interact
+ex_extra          -mouse_jsbterm     -sun_workshop      +xterm_clipboard
+extra_search      +mouse_netterm     +syntax            -xterm_save
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "
/eems/eems/jenkins/opt/RHEL7-Stable/pkg-home/vim-motif/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MOTIF     -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L. -Wl,-z,relro -fstack-protector-strong -rdynamic -Wl,-export-dynamic  -L/usr/local/lib -Wl,--as-needed -o vim  -lXp -lXmu -lXext -lXm -lXt -lSM -lICE -lXpm -lXt -lX11 -lSM -lICE -ldl  -lm -ltinfo -lelf  -lselinux   -ldl

$ echo $TERM
screen-256color

```

Sorry for not posting that before. It's inside my "work" box so harder to extract.

* `v:termresponse` is empty (in both the gui and terminal).
* `t_TI` and `t_TE` are both empty in both GUI and terminal

In both terminal and GUI `CTRL-SHIFT-V CTRL-V` print `^V` so it suggests `modifyOtherKeys` is off.

Anyway, i'll do some digging this evening.

**Comment by puremourning** [comment] 2020-05-28 14:18
Actually, it turns out no mappings with control work with `gvim --clean`. (e.g. `:nmap <C-K> :echo 'test'<CR>` does not trigger either). Probably the same underlying issue.

**Comment by brammool** [comment] 2020-05-28 17:53
OK, apparently I only checked with GTK, for which it is fixed now, but I can reproduce the problem with Motif.  Let's see if I can find the problem by debugging...

**Closed as completed** 2020-05-28 19:04 UTC

**Comment by puremourning** [comment] 2020-05-28 19:29
Thanks again, confirmed working :)
