### ISSUE TITLE
Maximized screen border

### ISSUE THREAD

**Issue by jbarrantes** [vim/vim#4319] opened 2019-04-30 17:29 UTC
There is a border on the bottom and right sides of the window when GVim is maximized. This is especially noticeable with dark themes and is annoying for presentations given the bright spot on a dark environment.

A possible solution could be to set the background color of this area to match the current theme background or at least set it to black if ```background=dark```

**Comment by k-takata** [comment] 2019-05-03 22:43
Same as #349?

**Comment by chrisbra** [comment] 2019-05-06 06:06
closing as duplicate of #349

**Closed as completed by chrisbra** 2019-05-06 06:06 UTC
Labels: duplicate, enhancement
