### ISSUE TITLE
Version 8.1 (Included patches: 1-2234) breaks support for long paths

### ISSUE THREAD

**Issue by AmaruCoder** [vim/vim#5609] opened 2020-02-10 05:10 UTC
**Describe the bug**
When the path for the file being opened is longer than 66 characters, MacVim shows "Press ENTER or type command to continue." This is something that did not happen in previous versions. This does not happen in the terminal.

**Environment (please complete the following information):**
 - Vim version:
VIM - Vi IMproved 8.1 (2018 May 18, compiled Oct 30 2019 11:57:56)
macOS version
Included patches: 1-2234
 - OS: macOS Sierra (10.12.16)

**Comment by k-takata** [comment] 2020-02-10 05:15
Does it occur with `vim --clean`?
Can you bisect which patch causes it?

**Comment by AmaruCoder** [comment] 2020-02-11 05:20
It happens with `vim --clean` too. This behavior did not happen prior to patch 1-2234. If you change the `set columns=` to a number wider than the length of the path, there is no "Press ENTER" message.

**Comment by dpelle** [comment] 2020-02-11 06:43
What are the exact steps to reproduce?
Ideally give a single command line to that reproduces it using `vim --clean …` so we can just copy/paste it.

**Comment by adudek16** [comment] 2020-02-11 15:30
I think if we test/verify against MacVim Snapshot 160 (Vim patch 8.1.2224) then we have an idea that it was introduced between patches 8.1.2224 - 8.1.2234. That is only 10 patches.

**Comment by adudek16** [comment] 2020-02-11 15:34
Looking at the Readme, I wonder if `8.1.2234  get_short_pathname() fails depending on encoding`
is a potential suspect

**Comment by k-takata** [comment] 2020-02-11 16:14
8.1.2234 is Windows specific.

**Comment by AmaruCoder** [comment] 2020-02-16 00:49
Just to follow up, one workaround is to add the following to `.vimrc`:

`set shortmess+=aF`

An easy way to recreate the error is to issue a `cd: <path>`, with a path longer that the `columns` value.

**Comment by chrisbra** [comment] 2020-02-26 08:05
I tried to reproduce in a terminal with 80 Columns:

			chrisbra@debian ~ % cd /tmp
			chrisbra@debian /tmp % mkdir `printf 'a%.0s' {1..100}`
			chrisbra@debian /tmp % echo test > ./aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/testfile
			chrisbra@debian /tmp % vim --clean
			:cd /tmp/aaaa<tab>
			:e testfile
			:w
			:q


I did only see a `Press enter command to continue` after the `:cd` command, but I think this is expected, as the command line was longer than $COLUMNS

So I am still missing, what the exact steps are to see the bug. 

@AmaruCoder please give exact steps. You mention, this does not happen in the terminal. So is this perhaps a MacVim bug then?

This was with 8.2.139

**Comment by AmaruCoder** [comment] 2020-02-28 00:52
The steps to replicate the problem are:

1. Open Vim
2. Navigate to a folder whose complete path is longer than 66 characters
3. Open a file within that folder

**Comment by k-takata** [comment] 2020-02-28 01:48
It seems that you are using MacVim. Does it occur with Vim (not MacVim)?

**Comment by k-takata** [comment] 2020-02-28 02:13
> 1. Open Vim

What is the exact command?

> 2. Navigate to a folder whose complete path is longer than 66 characters

What is the exact command?

> 3. Open a file within that folder

What is the exact command?

**Comment by chrisbra** [comment] 2020-02-28 06:27
Please also show the :version output and mention when exactly you see the message

**Comment by AmaruCoder** [comment] 2020-03-02 05:09
1. `vim`
2. `:cd ` to a folder with a path longer than 66
3. `:e ` any file within that folder.

**Comment by AmaruCoder** [comment] 2020-03-02 05:12
Version info:

VIM - Vi IMproved 8.1 (2018 May 18, compiled Oct 30 2019 11:57:56)
macOS version
Included patches: 1-2234
Compiled by travis@Traviss-Mac.local

**Comment by k-takata** [comment] 2020-03-02 05:26
Please answer the questions:

> Does it occur with Vim (not MacVim)?

> mention when exactly you see the message

**Comment by k-takata** [comment] 2020-03-02 07:07
Okay, it looks that you are using this version of MacVim: https://github.com/macvim-dev/macvim/releases/tag/snapshot-161.

I suspect that this is a plugin issue or you're misunderstanding the behavior.
I asked some people to reproduce the issue with the same version of MacVim, but they couldn't reproduce it. They only see the message after `:cd` like @chrisbra's comment.
Closing this for now.

If you still have the issue, please show the **exact steps** like https://github.com/vim/vim/issues/5609#issuecomment-591292629 using Vim with `--clean` option, so that other people can copy/paste them. ([Your comment](https://github.com/vim/vim/issues/5609#issuecomment-593221963) is not enough.)
Also don't forget to mention **when exactly** you see the message.

**Closed as completed by k-takata** 2020-03-02 07:07 UTC
Labels: invalid, needs feedback

**Comment by AmaruCoder** [comment] 2020-03-05 04:34
Thank you for the followup. The issue also happened in `vim` (`which vim` in the terminal gave `/usr/bin/vim`. However the new version (8.2 patches 1-319) has fixed the problem. Thank you again.
