### ISSUE TITLE
resolve() works incorrectly under windows

### ISSUE THREAD

**Issue by zdm** [vim/vim#4661] opened 2019-07-12 18:57 UTC
**Describe the bug**
I have directory ```D:\work```, that is symbolic link to the directory ```D:\gdrive```.
I start vim in ```D:\work``` and open some file from this dir, for example, ```:e TODO.txt```.
If I exec ```:echo resolve(expand('%:p'))``` it returns ```C:\gdrive\TODO.txt```.
This is incorrect, because it should return ```D:\gdrive\TODO.txt```.

**To Reproduce**
mkdir d:\111
mklink /D "d:\222" "d:\111" (need to run from Administrator)
cd /D "d:\222"
touch 1.txt (or create d:\222\1.txt somehow, if you don't have touch command)
vim 1.txt
:echo resolve(expand('%:p'))

**Expected behavior**
It should return ```d:\111\1.txt```, but it returns ```c:\111\1.txt```. Drive letter is incorrect.

**Environment (please complete the following information):**
 - Vim version 8.1.1670;
 - OS: Windows 10;
 - GUI;

**Comment by chrisbra** [comment] 2019-07-14 12:15
Just for reference: according to https://github.com/mhinz/vim-signify/issues/299, this was caused by patch [v8.1.1417](https://github.com/vim/vim/commit/1bbebab5255b5300d727c9b3f1b308205847dafd)

**Comment by k-takata** [comment] 2019-07-17 00:30
Couldn't reproduce on Windows 10 1803. It returns `D:\111\1.txt`.
@mattn Any comments?

**Comment by mattn** [comment] 2019-07-17 01:02
I could not reproduce this on Windows 7.

**Comment by chrisbra** [comment] 2019-07-17 03:33
> Couldn't reproduce on Windows 10 1803. It returns D:\111\1.txt

Same for me using Win 10 1803 and vim_8.1.1705_x64

**Comment by zdm** [comment] 2019-07-17 04:11
Hmm, for me it works incorrectly.
My vimrc is located on c:, maybe this cause the problem?
I will try.

**Comment by k-takata** [comment] 2019-07-17 04:20
Ah, when I assign a drive letter to a directory with the `subst` command, `resolve()` also resolves the subst drive.

```
C:\>md 000
C:\>subst f: 000
C:\>f:
F:\>md tmp
F:\>mklink /j link tmp
F:\>vim
:echo resolve('link')
C:\000\tmp          " Doesn't return F:\tmp
```

Not sure if this is the same case with you. Is your D: drive something special?

**Comment by zdm** [comment] 2019-07-17 07:25
No, just a standard partition.

**Comment by zdm** [comment] 2019-07-17 07:41
I just tested with the empty vimrc - still not working, so the problem not in the configuration.
My C: and D: drives - simple partitions.

**Comment by chrisbra** [comment] 2019-07-17 07:42
so what windows version is this?

**Comment by zdm** [comment] 2019-07-17 08:02
latest windows 10 Pro 1903 x64 with the all updates installed.

**Comment by mattn** [comment] 2019-07-17 09:16
Could you please show me BEFORE and AFTER?

```
:echo expand('%:p')
:echo resolve(expand('%:p'))
```

**Comment by zdm** [comment] 2019-07-17 09:22
before: d:\222\1.txt
after: C:\111\1.txt

**Comment by zdm** [comment] 2019-07-17 09:42
windows resolves link correctly:
```
dir /A

01.07.2019  11:21    <DIR>          $RECYCLE.BIN
17.07.2019  12:23    <DIR>          111
17.07.2019  12:20    <SYMLINKD>     222 [d:\111]
....
```

**Comment by mattn** [comment] 2019-07-17 13:19
I tried this on Windows 10 too. But could not reproduce.

**Comment by zdm** [comment] 2019-07-17 14:42
I am building vim manually under msys2 environment. Can this be a build issue?
Could someone provide latest vim exe for test on my side?

**Comment by zdm** [comment] 2019-07-17 14:49
Ok, I already tested with the vim from here https://github.com/vim/vim-win32-installer/releases
Issue still present

**Comment by zdm** [comment] 2019-07-22 04:23
Is it possible to debug it on my computer?

**Comment by chrisbra** [comment] 2019-07-22 06:40
you possible need to compile your own version and debug the issue using a debugger (depends on how you compile your version).

**Comment by zdm** [comment] 2019-07-22 07:58
I don;t have required skills to debug binary code.

**Comment by zdm** [comment] 2019-07-22 08:10
Maybe it is possible to create custom build, that will write debug log?

**Comment by k-takata** [comment] 2019-07-22 08:49
[listvol.zip](https://github.com/vim/vim/files/3416426/listvol.zip)

Could you execute `listvol.exe` from the Command Prompt, and paste the result here?

**Comment by zdm** [comment] 2019-07-22 10:38
I have no such command.
```
'listvol' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by k-takata** [comment] 2019-07-22 11:44
Download the zip file from my previous comment.

**Comment by zdm** [comment] 2019-07-22 11:48
```
d:\downloads>.\listvol.exe
\\?\Volume{8ab503a4-7948-4481-bf50-64fdd2961ce7}\: : 0xa0e61476
\\?\Volume{1341d48d-37fd-4a18-9842-9de6bfb44134}\: C:\: 0x12345678
\\?\Volume{1981d456-a904-4e52-a2a4-29dec5b9a494}\: D:\: 0x12345678
\\?\Volume{346c1185-010e-4c74-81b1-b15d4cc6b2a9}\: : 0xd2e76bef
\\?\Volume{025af2ff-b9a3-11e8-b667-34415dcc2aaa}\: S:\: 0x12345678

```

**Comment by k-takata** [comment] 2019-07-22 11:58
Hmm, it's very strange that C:, D: and S: drives have the same volume serial number 0x12345678.

**Comment by zdm** [comment] 2019-07-22 12:01
I set it manually, it was required by some software.

**Comment by zdm** [comment] 2019-07-22 12:06
How is basInterval calculated?

**Comment by k-takata** [comment] 2019-07-22 12:07
That's the reason why `resolve()` returns the incorrect drive. `resolve()`'s processing depends on the volume serial numbers.

**Comment by zdm** [comment] 2019-07-22 12:10
hmm, it shouldn't depend on serial numbers, they means nothing and windows don't guarantee, that they will be different.

**Comment by k-takata** [comment] 2019-07-22 12:24
disagree

**Comment by zdm** [comment] 2019-07-22 12:29
Duplicate Volume Serial Numbers
Since volume serial numbers are not generated at random and without knowledge of the volume serial numbers on other drives in the computer, there's a chance that two drives on the same computer could end up having the same volume serial number.

**Comment by chrisbra** [comment] 2019-07-22 12:43
Well yes, but https://www.lifewire.com/volume-serial-number-2626046 mentions those should be unique. Also it explicitly says:

> While the probability of two drives in a single computer getting the same volume serial number is 
> technically possible, the chance is infinitesimally small and isn't usually a concern.

Not saying it shouldn't be fixed (if we can), but this is a useful information you should have given us earlier.

**Comment by zdm** [comment] 2019-07-22 12:52
VSN can be changed by user or by the third party software, like in my case, so it is bad point for using in resolve(). From this point of view - volume letter, for example, is much better, because it is 100% unique under windows.

**Comment by k-takata** [comment] 2019-07-23 03:03
How about this patch?
https://gist.github.com/k-takata/52d0a677ca9a27bdbaed21d77533244e

This uses `GetFinalPathNameByHandleW` instead of `GetFileInformationByHandleEx`, `GetVolumeInformationByHandleW` and other volume APIs. This makes the implementation simpler. Now, this doesn't use volume serial numbers to retrieve the drive name. (However, it might fail if it uses volume serial numbers internally.)

**Comment by k-takata** [comment] 2019-07-23 08:47
I noticed that the current implementation doesn't resolve a symlink to a network path. (E.g. link to `\\server\share\foo.txt`
My above patch also fixes this problem.

**Comment by k-takata** [comment] 2019-07-26 00:55
@zdm Have you tried the above [patch](https://gist.github.com/k-takata/52d0a677ca9a27bdbaed21d77533244e)?
Can you compile Vim by yourself?

@mattn Could you also check if this works on Windows 7?

**Comment by zdm** [comment] 2019-07-26 05:22
I tested patch, it works.
Not tested with the links to network path.

**Comment by mattn** [comment] 2019-07-26 06:38
@k-takata I will check this in monday.

**Comment by mattn** [comment] 2019-07-30 00:53
I checked this on Windows7. Seems works fine for me. (Sorry, I can not check with same volume serial number)

**Comment by k-takata** [comment] 2019-07-30 01:30
Thank you.

@brammool 
I think that [my patch](https://gist.github.com/k-takata/52d0a677ca9a27bdbaed21d77533244e) is ready to be merged.

**Closed as completed** 2019-08-01 11:56 UTC
Labels: patch, platform-windows
