### ISSUE TITLE
E117: Unknown function: strptime

### ISSUE THREAD

**Issue by VimWei** [vim/vim#14599] opened 2024-04-20 02:56 UTC
### Steps to reproduce

1. Restart gVim 9.1 
2. `:echo strptime("%Y %b %d %X", "1997 Apr 27 11:49:23")`

This is the first example in `:help strptime()`

Result: `E117: Unknown function: strptime`

### Expected behaviour

echo message: 862156163

### Version of Vim

9.1.0309

### Environment

- Windows Pro 22H2
- gvim_9.1.0309_x64_signed.exe

**Comment by VimWei** [comment] 2024-04-20 02:59
https://github.com/vim/vim/issues/6573

**Comment by VimWei** [comment] 2024-04-20 03:25
I noticed that lervag has already solved this issue in wiki.vim. Could this solution be integrated into Vim?

https://github.com/lervag/wiki.vim/issues/254

**Comment by chrisbra** [comment] 2024-04-20 07:16
duplicate of #6573 

If your underlying C runtime does not provide `strptime()` function there is nothing that Vim can do against it. The solution from the mentioned vim plugin is simply testing whether `strptime()` exists. That is basically what everybody should do, before using `strptime()`

**Closed as not planned by chrisbra** 2024-04-20 07:16 UTC
Labels: duplicate, platform-windows, bug

**Comment by VimWei** [comment] 2024-04-20 08:20
> The solution from the mentioned vim plugin is simply testing whether `strptime()` exists.

Not only testing for the existence of strptime() but also recreating its functionality.

https://github.com/lervag/wiki.vim/blob/master/autoload/wiki/date/strptime.vim

**Comment by chrisbra** [comment] 2024-04-20 08:34
Yes, that's largely what a plugin can do. I don't plan to add `strptime()` or `strftime()` alternative inside Vims code. That would be way out of an editors business. It's a best effort approach currently and that's why you should always use `exists()` before using those functions.
