### ISSUE TITLE
After upgrade I get: Error detected while processing BufWinEnter Autocommands for "*"..function

### ISSUE THREAD

**Issue by sandrodz** [vim/vim#10128] opened 2022-04-09 06:46 UTC
### Steps to reproduce

On MacOS after upgrading vim from 8.2.4450 to  8.2.4700

I get following error on opening vim:

```Error detected while processing BufWinEnter Autocommands for "*"..function <SNR>65_Setup[6]..<SNR>65_IndentLinesEnable[10]..<SNR>65_SetConcealOption```

Downgrading to 8.2.4450 fixes issue:

`curl https://raw.githubusercontent.com/Homebrew/homebrew-core/29d97c4ea6b9e71604abf27285dc1ab809b45f3b/Formula/vim.rb > $(find $(brew --repository) -name vim.rb) && brew reinstall vim`

### Expected behaviour

no error :)

### Version of Vim

8.2.4700

### Environment

MacOS 12.3

**Comment by lacygoill** [comment] 2022-04-09 08:21
Is there an error message given after the call stack?
Which plugin(s) do you use?
Can you provide a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)?
Can you bisect the exact commit which introduces this regression?

**Comment by sandrodz** [comment] 2022-04-09 08:27
> Is there an error message given after the call stack?
> Which plugin(s) do you use?
> Can you provide a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)?
> Can you bisect the exact commit which introduces this regression?

I can provide my `.vimrc`: https://github.com/wearede/DevCeption/blob/master/provisioning/roles/vim/files/.vimrc

**Comment by chrisbra** [comment] 2022-04-09 08:31
Please show the complete message. And mention what plugin defines `<SNR>65_SetConcealOption` (check the output of :scriptnames for the 65 entry). Currently, this issue report gives us no clue and we cannot try to debug your vimrc with several plugins.

**Comment by chrisbra** [comment] 2022-04-09 08:47
My guess is: https://github.com/Yggdroot/indentLine 

Can you please also show the full `:version` output? Are you possibly missing conceal mode?

**Comment by sandrodz** [comment] 2022-04-09 10:40
> My guess is: https://github.com/Yggdroot/indentLine
> 
> Can you please also show the full `:version` output? Are you possibly missing conceal mode?

yep, disabling indentLine error disappears.

+conceal is present

`VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr 06 2022 16:59:21)
macOS version - arm64
Included patches: 1-4700
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl               +file_in_path      +mouse_urxvt       -tag_any_white
+arabic            +find_in_path      +mouse_xterm       -tcl
+autocmd           +float             +multi_byte        +termguicolors
+autochdir         +folding           +multi_lang        +terminal
-autoservername    -footer            -mzscheme          +terminfo
-balloon_eval      +fork()            +netbeans_intg     +termresponse
+balloon_eval_term +gettext           +num64             +textobjects
-browse            -hangul_input      +packages          +textprop
++builtin_terms    +iconv             +path_extra        +timers
+byte_offset       +insert_expand     +perl              +title
+channel           +ipv6              +persistent_undo   -toolbar
+cindent           +job               +popupwin          +user_commands
-clientserver      +jumplist          +postscript        +vartabs
+clipboard         +keymap            +printer           +vertsplit
+cmdline_compl     +lambda            +profile           +vim9script
+cmdline_hist      +langmap           -python            +viminfo
+cmdline_info      +libcall           +python3           +virtualedit
+comments          +linebreak         +quickfix          +visual
+conceal           +lispindent        +reltime           +visualextra
+cryptv            +listcmds          +rightleft         +vreplace
+cscope            +localmap          +ruby              +wildignore
+cursorbind        +lua               +scrollbind        +wildmenu
+cursorshape       +menu              +signs             +windows
+dialog_con        +mksession         +smartindent       +writebackup
+diff              +modify_fname      -sodium            -X11
+digraphs          +mouse             -sound             -xfontset
-dnd               -mouseshape        +spell             -xim
-ebcdic            +mouse_dec         +startuptime       -xpm
+emacs_tags        -mouse_gpm         +statusline        -xsmp
+eval              -mouse_jsbterm     -sun_workshop      -xterm_clipboard
+ex_extra          +mouse_netterm     +syntax            -xterm_save
+extra_search      +mouse_sgr         +tag_binary
-farsi             -mouse_sysmouse    -tag_old_static
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/opt/homebrew/share/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H -DMACOS_X -DMACOS_X_DARWIN -g -O2 -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: clang -L. -fstack-protector-strong -L/opt/homebrew/lib -L/opt/homebrew/opt/libyaml/lib -L/opt/homebrew/opt/openssl@1.1/lib -L/opt/homebrew/opt/readline/lib -o vim -lm -lncurses -liconv -lintl -framework AppKit -L/opt/homebrew/opt/lua/lib -llua5.4 -mmacosx-version-min=12.0 -fstack-protector-strong -L/opt/homebrew/Cellar/perl/5.34.0/lib/perl5/5.34.0/darwin-thread-multi-2level/CORE -lperl -L/opt/homebrew/opt/python@3.10/Frameworks/Python.framework/Versions/3.10/lib/python3.10/config-3.10-darwin -lpython3.10 -framework CoreFoundation -lruby.3.1 -L/opt/homebrew/Cellar/ruby/3.1.1/lib`

**Comment by lacygoill** [comment] 2022-04-09 10:45
I tried the indent plugin immediately, and could not reproduce the issue, which is why I asked:

   > Can you provide a minimal reproducible example?

As well as:

   > Is there an error message given after the call stack?

**Comment by chrisbra** [comment] 2022-04-09 11:27
okay, please: Show the complete error stack. It looks like it comes from the `SetConcealOption` function. That function looks quite innocent to me: 

https://github.com/Yggdroot/indentLine/blob/7753505f3c500ec88d11e9373d05250f49c1d900/after/plugin/indentLine.vim#L96-L107

So I tried with this simplified example:

```concealtest.vim
  let g:indentLine_setConceal = 1

  function! SetConcealOption()
      if !g:indentLine_setConceal
          return
      endif
      if !(exists("b:indentLine_ConcealOptionSet") && b:indentLine_ConcealOptionSet)
          let b:indentLine_ConcealOptionSet = 1
          let b:indentLine_original_concealcursor = &l:concealcursor
          let b:indentLine_original_conceallevel = &l:conceallevel
          let &l:concealcursor = exists("g:indentLine_concealcursor") ? g:indentLine_concealcursor : "inc"
          let &l:conceallevel = exists("g:indentLine_conceallevel") ? g:indentLine_conceallevel : "2"
      endif
  endfunction

  call SetConcealOption()
```

Does that throw an error for you?

**Comment by chrisbra** [comment] 2022-04-09 11:36
Ah found it.

This errors out for you

```
let g:indentLine_concealcursor = 0
let g:indentLine_setConceal = 1

function! SetConcealOption()
    if !g:indentLine_setConceal
        return
    endif
    if !(exists("b:indentLine_ConcealOptionSet") && b:indentLine_ConcealOptionSet)
        let b:indentLine_ConcealOptionSet = 1
        let b:indentLine_original_concealcursor = &l:concealcursor
        let b:indentLine_original_conceallevel = &l:conceallevel
        let &l:concealcursor = exists("g:indentLine_concealcursor") ? g:indentLine_concealcursor : "inc"
        let &l:conceallevel = exists("g:indentLine_conceallevel") ? g:indentLine_conceallevel : "2"
    endif
endfunction

call SetConcealOption()
```

You are setting `g:indentLine_concealcursor` in your .vimrc to an invalid option.
`g:indentLine_concealcursor` must be set to a valid option value for 'concealcursor', see `:h 'concealcursor'

This was changed in 8ccbbeb620dcc73154de29c51100fe815, before that Vim wouldn't complain about using an invalid option.

Please adjust your configuration.

I am closing as invalid.

**Closed as completed by chrisbra** 2022-04-09 11:36 UTC

**Comment by sandrodz** [comment] 2022-04-09 15:38
It is the first time I reported problem to vim repo - And level of competence and involvement is just wow. Thank you guys.
