### ISSUE TITLE
Inconsistency with vimL highlighting parts of `.vimrc` when using vim-plug

### ISSUE THREAD

**Issue by paniash** [vim/vim#8482] opened 2021-06-30 13:00 UTC
**Describe the bug**
(Issues related to the runtime files should be reported to their maintainer, check the file header.)

I've noticed an inconsistency with highlighting parts of `.vimrc`(or `init.vim` in my case) in current and past versions of vim. Specifically, the highlighting of enclosed text when using [vim-plug](https://github.com/junegunn/vim-plug). For example,

```vim
call plug@begin('~/.config/nvim/plugged')
Plug 'tpope/vim-commentary'
```

In past versions of vim (not sure when it changed), the text `tpope/vim-commentary` would be highlighted whereas in the current stable version `v8.2.2891`, the same text is not syntax highlighted at all.

This is possible because of an updated syntax file perhaps.

See [here](https://github.com/neovim/neovim/issues/14940#issuecomment-871234359) for more context.

**Expected behavior**

Syntax highlighting should preferably exist for text enclosed within quotes.

**Screenshots**
If applicable, copy/paste the text or add screenshots to help explain your problem.

**With syntax highlighting (earlier versions)**

![pic-selected-210630-1307-06](https://user-images.githubusercontent.com/59497618/123964452-0b8b4180-d9d1-11eb-8073-a94fc001c03d.png)

**With latest stable version**

![pic-selected-210630-1314-08](https://user-images.githubusercontent.com/59497618/123964485-15ad4000-d9d1-11eb-9498-de0dcd2d18f2.png)

**Environment (please complete the following information):**
 - Vim version: 8.2.2891
 - OS: Artix linux
 - Terminal:  st-256color

**Comment by lacygoill** [comment] 2021-06-30 13:22
Duplicate of https://github.com/vim/vim/issues/6587

---

Update your Vim; it's fixed since 8.2.2914.

**Comment by chrisbra** [comment] 2021-06-30 13:23
closing then.

**Closed as completed by chrisbra** 2021-06-30 13:23 UTC
Labels: duplicate

**Comment by paniash** [comment] 2021-06-30 14:04
Thanks a lot!
