### ISSUE TITLE
Termguicolors uses cterm instead of gui

### ISSUE THREAD

**Issue by gerardbm** [vim/vim#1740] opened 2017-06-02 16:21 UTC
Issue: the setting `termguicolors` is using **cterm** instead of **gui** on the typography emphasis (bold, italic, underline...). It works well on **guibg** and **guifg**, though.

Way to reproduce it:
1. `$ vim -N -u NORC test.md` (include a title `# title`).
2. `:set termguicolors`
3. `:syntax enable`
4. `:hi markdownH1 gui=bold` (now title should be bold).
5. `:hi markdownH1 cterm=bold` (now title is bold).

As it works well on **guibg** and **guifg**, it would be more coherent if it worked on **gui** as well.

Some color schemes (i.e., molokai) use this syntax:

```viml
hi MatchParen      guifg=#000000 guibg=#FD971F gui=NONE ctermfg=000 ctermbg=208 cterm=NONE
```
Other color schemes use conditionals to decide when it is **gui** and when it is **cterm**: 
```viml 
if (has('termguicolors') && &termguicolors) || has('gui_running') 
```
Converting this:
```viml
hi MatchParen      guifg=#000000 guibg=#FD971F gui=NONE 
```
To this:
```viml
hi MatchParen      ctermfg=000 ctermbg=208 cterm=NONE
```

Vim version 8.0, and patches 1-586. (It works well on nvim).

**Comment by purpleP** [comment] 2017-08-25 21:44
I also have problems with `termguicolors` while nvim works fine.
`ModeMsg` is bold for some reason, selection doesn't change background, while error messages aren't bold (as they should be in my theme). I use slightly customized solarized [theme](https://github.com/purpleP/vim-colors-solarized/blob/master/colors/solarized.vim). It supports termguicolors and adds `CursorLineNr`  and `SignColumn` support.

**Comment by dpelle** [comment] 2020-07-31 10:37
Bug is reported against vim-8.0.586 which is old.  It would be good if bug reported tried with the latest vim (vim-8.2.1328 at the time I write this.

The duplicate issue #6580 was using vim-8.0 which is also a bit old.

I see several patches related to `termguicolor`:
```
patch 8.2.0906: when setting 'termguicolors' SpellBad is no longer red
patch 8.2.0890: no color in terminal window when 'termguicolor' is set
patch 8.1.0997: using GUI colors in vim.exe when 'termguicolors' is off
patch 8.0.1600: crash when setting t_Co to zero when 'termguicolors' is set
```

**Comment by Opencode-foss** [comment] 2020-07-31 12:51
Issue #6580 was tested on vim-8.2.

**Comment by dpelle** [comment] 2020-08-02 07:02
In the duplicate issue #6580, bug reporter indicated in comment there, that his issue is fixed with a more recent version of vim (the version was not given unfortunately). This issue #1740 is probably also fixed with a more recent version of vim.

To bug submitter @gerardbm : can you confirm that bug is fixed in latest vim? (vim-8.2.1352 as the time I write this).

**Comment by lacygoill** [comment] 2020-08-02 07:48
FWIW, I can still reproduce the issue on 8.2.1352.  That being said, I doubt it will be fixed because changing the semantics of `gui`, `cterm` and similar arguments this late would be [backwards incompatible](https://github.com/vim/vim/pull/1773#issuecomment-535963889):

> I'm closing this, since there hasn't been enough request for the change to justify the backwards-incompatibility. It would be possible to add a new argument for attributes used both by the gui and cterm+termguicolors, but that's a bit complicated.

**Comment by purpleP** [comment] 2020-08-02 07:55
> FWIW, I can still reproduce the issue on 8.2.1352. That being said, I doubt it will be fixed because changing the semantics of `gui`, `cterm` and similar arguments this late would be [backwards incompatible](https://github.com/vim/vim/pull/1773#issuecomment-535963889):
> 
> > I'm closing this, since there hasn't been enough request for the change to justify the backwards-incompatibility. It would be possible to add a new argument for attributes used both by the gui and cterm+termguicolors, but that's a bit complicated.

Exactly the reason I switch to neovim completely a long time ago. Sorry, I don't have vim installed anymore to test this.

**Comment by gerardbm** [comment] 2020-08-02 09:28
> In the duplicate issue #6580, bug reporter indicated in comment there, that his issue is fixed with a more recent version of vim (the version was not given unfortunately). This issue #1740 is probably also fixed with a more recent version of vim.
> 
> To bug submitter @gerardbm : can you confirm that bug is fixed in latest vim? (vim-8.2.1352 as the time I write this).

I can't test this at this moment, because I'm using Debian 9 with an older version of Vim. If someone uses Arch and can reproduce the steps mentioned above, that would be fine and helpful. If not, during holidays I would try to install Arch in a virtual machine.

However, the pull-request 1773 was closed by Bram. A fix would be a casuality, I think...

**Comment by brammool** [comment] 2020-08-02 14:39
I would call this a bug in Neovim: Even though 'termguicolors' clearly implies that this is about colors and nothing else, they apparently (based on comments above) also made it switch attributes.  Whether that is good or not depends on the terminal (does it support italic?) and the color scheme.  It appears the reports mention "this works fine in nvim" which to me means that they use highlighting created for nvim and try to use it in Vim.  Because of the bug introduced by Neovim this then causes problems.

As already mentioned in #1773 making a backwards incompatible change at this time is a bad idea.  And like I said above, 'termguicolors' is about colors, not attributes, changing the behavior also goes against user expectations.

To get out of this, perhaps we should introduce the 'termguiattr' option.  It's not nice to add yet-another-option, but I can't think of another solution.

**Comment by purpleP** [comment] 2020-08-02 14:50
I don't know all the details, but I don't think it's a bug. The idea is that all modern terminals support almost everything that GUI vim supported. So I can only have configuration for gui in my colorscheme and then just `set termguicolors` in config.

**Comment by brammool** [comment] 2020-08-02 15:09
If the terminal supports the gui attributes, then why weren't the cterm attributes set to it?  So no, in general terminals don't support the same attributes as the GUI, or they don't look so good.  That's the whole reason there are separate attributes.
Again, 'termguicolors' is about the colors, those will work if the terminal supports RGB colors.  You can't just say "works for most" and then assume it works for everybody (which means they can't use 'termguicolors' because of the side effects).

**Comment by purpleP** [comment] 2020-08-02 16:16
Again, I've never looked into it deeply, but it seems to me that because tui attributes are subset of gui attributes It's easier to maintain (for a user) just one set of attributes in his config and then vim can decide which attributes it can actually support in particular environment. And I think that that's was a motivation for neovim to introduce `termguicolors`, but I'm not sure.

Here's help for this setting.
```
'termguicolors' 'tgc'	boolean (default off)
			global
	Enables 24-bit RGB color in the |TUI|.  Uses "gui" |:highlight|
	attributes instead of "cterm" attributes. |highlight-guifg|
	Requires an ISO-8613-3 compatible terminal.
```

**Comment by lifepillar** [comment] 2020-09-05 10:02
I am with Bram about this: his argument makes perfect sense to me. I don't think that a “termguiattr” is necessary, but only confusing. Perhaps, it might be useful to stress that `cterm/gui` depend only on GUI vs terminal and not on `termguicolors`—maybe just an additional note or a reference to `'termguicolors'` under `'highlight-gui'` and `'highlight-cterm'`.

I would like to notice, though, that `synIDattr()` returns the value “for the currently active highlighting […] (GUI, cterm, or term)” when mode is omitted (`:h synIDattr()`). I think that it would be more coherent if `synIDattr()` returned the values that are used in the current environment (not highlighting) instead.

To appreciate the difference, consider this definition:

```vim
hi Statement gui=italic cterm=NONE
```

There are at least three modes/environments (ignoring `term`) to consider:
| Environment    |Attr |synIDattr(hlID('Statement'), 'italic')|  OK? |
|----------------|-----|:------------------------------------:|:----:|
| GUI Vim        |gui  |  '1'                                 | Yes! |
| notermguicolors|cterm|  (empty)                             | Yes! |
| termguicolors  |cterm|  '1'                                 | No   |

The last line shows that `synIDattr()` is inconsistent with how the attributes are used in the active mode.

**Comment by bfredl** [comment] 2020-10-29 19:04
> I would call this a bug in Neovim: Even though 'termguicolors' clearly implies that this is about colors and nothing else, they apparently (based on comments above) also made it switch attributes.

Fake news. vim defines both colors and attributes in a `:colors` file.

**Comment by brammool** [comment] 2020-10-29 20:47
There are two ways to look at it, there is no solution that will please all users.  Therefore it's best to just leave it as it is now, avoiding that those who found a good working setup will have to change there setup (again).

**Closed as completed by brammool** 2020-10-29 20:47 UTC

**Comment by rwxe** [comment] 2023-09-23 11:32
I did a workaround about this, you can put this into `.vimrc`,  or use the [plugin](https://github.com/rwxe/termguiattrhook) I wrote.
```
command SetTermGuiAttr call TermGuiAttrHook() 
"Override cterm attributes with gui attributes
function! TermGuiAttrHook()
    for group in getcompletion('', 'highlight')
        let group_config = execute('hi ' . group)
        let gui_match = matchlist(group_config, 'gui\s*=\s*\zs\S\+\ze')
        let gui_values = filter(gui_match, 'v:val != ""')
        if !empty(gui_values)
            let gui_value = gui_values[0]
            execute 'hi ' . group . ' cterm=' . gui_value
        endif
    endfor
endfunction
```
