### ISSUE TITLE
[Centos8.2]checking for tgetent()... configure: error: NOT FOUND! 

### ISSUE THREAD

**Issue by muse117** [vim/vim#7449] opened 2020-12-10 07:46 UTC
I'm compiling and running configure on the master branch, I have just received an error checking for tgetent()...configure: error: NOT FOUND!, but I have installed ncurses and ncurses-devel.
![微信截图_20201210154049](https://user-images.githubusercontent.com/9733486/101736737-d683d400-3afe-11eb-8e6e-d5c63381acb0.png)

**Comment by k-takata** [comment] 2020-12-10 08:34
Please check `src/auto/config.log`.
Please fill the issue template when you report an issue.

**Comment by muse117** [comment] 2020-12-10 09:27
> Please check `src/auto/config.log`.
> Please fill the issue template when you report an issue.

configure:11910: checking --with-tlib argument
configure:11919: result: ncurses
configure:11922: checking for linking with ncurses library
configure:11935: gcc -o conftest -g -O2  -L. -Wl,-z,relro  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -fstack-protector-strong -rdynamic -Wl,-export-dynamic  -L/usr/local/lib conftest.c -lelf  -lselinux  -lncurses >&5
configure:11935: $? = 0
configure:11936: result: OK
configure:12039: checking for tgetent()
configure:12052: gcc -o conftest -g -O2  -L. -Wl,-z,relro  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -fstack-protector-strong -rdynamic -Wl,-export-dynamic  -L/usr/local/lib conftest.c -lelf  -lselinux  -lncurses >&5
/usr/bin/ld: /tmp/cckPksFC.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
configure:12052: $? = 1
configure: failed program was

| /* end confdefs.h.  */
| int tgetent(char *, const char *);
| int
| main ()
| {
| char s[10000]; int res = tgetent(s, "thisterminaldoesnotexist");
|   ;
|   return 0;
| }
configure:12056: error: NOT FOUND!
      You need to install a terminal library; for example ncurses.
      Or specify the name of the library with --with-tlib.

**Comment by muse117** [comment] 2020-12-10 09:34
> Please check `src/auto/config.log`.
> Please fill the issue template when you report an issue.

add CFLAGS=-fPIC, it is ok.

**Comment by k-takata** [comment] 2020-12-10 09:35
It looks that this is the same as #4047.
It fixed the issue on RHEL/Fedora, but it should be also applied to CentOS.

**Comment by chrisbra** [comment] 2020-12-10 13:37
closing for being a duplicate of #4047.

**Closed as completed by chrisbra** 2020-12-10 13:37 UTC
