### ISSUE TITLE
Not work parameter mouse="" in /etc/vim/vimrc

### ISSUE THREAD

**Issue by stm32repo** [vim/vim#9506] opened 2022-01-11 08:59 UTC
Changes to /etc/vim/vimrc don't work. If I change the parameter in /usr/share/vim/vim82/defaults.vim then it is removed after vim update. The only solution is to add parameters to ~ /.vimrc for each user. It blows my mind.

```
:scriptnames
  1: /usr/share/vim/vimrc
  2: /usr/share/vim/vim82/syntax/syntax.vim
  3: /usr/share/vim/vim82/syntax/synload.vim
  4: /usr/share/vim/vim82/syntax/syncolor.vim
  5: /usr/share/vim/vim82/filetype.vim
  6: /usr/share/vim/vim82/colors/desert.vim
  7: /etc/vim/vimrc.local
  8: /usr/share/vim/vim82/syntax/nosyntax.vim
  9: /usr/share/vim/vim82/defaults.vim
 10: /usr/share/vim/vim82/ftplugin.vim
 11: /usr/share/vim/vim82/indent.vim
 12: /usr/share/vim/vim82/plugin/getscriptPlugin.vim
 13: /usr/share/vim/vim82/plugin/gzip.vim
 14: /usr/share/vim/vim82/plugin/logiPat.vim
 15: /usr/share/vim/vim82/plugin/manpager.vim
 16: /usr/share/vim/vim82/plugin/matchparen.vim
 17: /usr/share/vim/vim82/plugin/netrwPlugin.vim
 18: /usr/share/vim/vim82/plugin/rrhelper.vim
 19: /usr/share/vim/vim82/plugin/spellfile.vim
 20: /usr/share/vim/vim82/plugin/tarPlugin.vim
 21: /usr/share/vim/vim82/plugin/tohtml.vim
 22: /usr/share/vim/vim82/plugin/vimballPlugin.vim
 23: /usr/share/vim/vim82/plugin/zipPlugin.vim
```

**Comment by chrisbra** [comment] 2022-01-11 09:23
what problem are you trying to solve? And why can't you use ~/.vimrc? Depending on your distribution, it might be possible. Debian e.g. uses `/etc/vim/vimrc.local`. 

Also possible duplicate of #2042 #2841 #1188 and #1326

**Comment by lacygoill** [comment] 2022-01-11 09:32
> Changes to /etc/vim/vimrc don't work. If I change the parameter in /usr/share/vim/vim82/defaults.vim then it is removed after vim update. The only solution is to add parameters to ~ /.vimrc for each user. It blows my mind.

It's not a Vim bug.  There is nothing at [`:help initialization`](https://vimhelp.org/starting.txt.html#initialization) which suggests that `/etc/vim/vimrc` should be read.  [Google](https://unix.stackexchange.com/questions/571320/difference-beetwen-default-vim-and-etc-vim-vimrc) tells me that this file can be used by package maintainers:

   > /etc/vim/vimrc is a system-wide default Vim configuration added by the corresponding package maintainers (e.g. the Debian folks for the vim-common APT package). It represents the opinion of the distribution's maintainers about good (and secure) defaults.

The devs have no control over how Vim is packaged on each OS (thank you for providing this information BTW).

The closest file I can think of is the one documented at [`:help system-vimrc`](https://vimhelp.org/starting.txt.html#system-vimrc).  On your system, it could be `/usr/share/vim/vimrc`; that's the 1st line in the output of `:scriptnames` that you posted.  Or maybe try `/etc/vim/vimrc.local`; that's the 7th line.

**Comment by jamessan** [comment] 2022-01-11 15:18
> On your system, it could be `/usr/share/vim/vimrc`;

This is a symlink to `/etc/vim/vimrc`, since /usr/share files aren't supposed to be edited.

The problem is the unintuitive behavior of defautls.vim, as described in the issues Christian already mentioned.

The system-vimrc is where sysadmins expect to put things that apply to all users.  However, defaults.vim is loaded after that (only if the user doesn't have a `~/.vimrc`) and overrides their choices.

The solution, @stm32repo, which is suggested in `/etc/vim/vimrc` if you're on a Debian-based system, is to source defaults.vim in the system vimrc (or vimrc.local) and _then_ override the settings you dislike from defaults.vim.

**Comment by brammool** [comment] 2022-01-11 17:55
Generally, sys admins should not force their own opinion upon their users.  Just give them the Vim defaults and don't confuse them with undocumented defaults.
If you are stubborn and want to do it anyway, the solution from James McCoy works.  So nothing to change in Vim.

**Closed as completed by brammool** 2022-01-11 17:55 UTC
