### ISSUE TITLE
support searching for vimrc in ~/.config or XDG_CONFIG_HOME

### ISSUE THREAD

**Issue by mvdan** [vim/vim#4275] opened 2019-04-17 12:24 UTC
**Is your feature request related something that is currently hard to do? Please describe.**

For some context, see https://wiki.archlinux.org/index.php/XDG_Base_Directory. Having config files in `~/.config` is useful for multiple reasons, such as not polluting `$HOME`, and having all of these dirs/files under one directory.

Vim can now read from `~/.vim/vimrc`, which is certainly an improvement, but still means I must have that extra directory in my home directory.

**Describe the solution you'd like**

Right now, the list of paths to search for the user's `vimrc` on Linux is:

```
~/.vimrc
~/.vim/vimrc
```

I propose that we extend it to:

```
~/.vimrc
~/.vim/vimrc
$XDG_CONFIG_DIR/vim/vimrc (if the env var is unset, its default is ~/.config)
```

**Describe alternatives you've considered**

It's possible to symlink from `~/.config/vim` to `~/.vim`, but this still requires cluttering my home directory.

I could also use a line like `export VIMINIT=":source $XDG_CONFIG_HOME"/vim/vimrc` in my `~/.profile` file, but needing to do that seems unfortunate, given that this is such a widespread and common default for config files.

**Additional context**

For some further reading on not cluttering $HOME:

https://web.archive.org/web/20190202170417/https://plus.google.com/+RobPikeTheHuman/posts/R58WgWwN9jp
https://ploum.net/207-modify-your-application-to-use-xdg-folders/

**Comment by chrisbra** [comment] 2019-04-17 12:37
duplicate of #2034

**Closed as completed by chrisbra** 2019-04-17 12:37 UTC
Labels: enhancement

**Comment by mvdan** [comment] 2019-04-17 12:41
Damn, thanks - I didn't spot that. Sad to see that there's been zero development in two years, for what would probably be a fairly simple patch.
