### ISSUE TITLE
normal mode search command "/" with special offset ";" breaks parantheses

### ISSUE THREAD

**Issue by Anton-Wessel** [vim/vim#11245] opened 2022-09-28 16:18 UTC
### Steps to reproduce

command /l/;/a/
works correctly, i.e. first searches"l", then makes new search for *"a".
now this command is to be inclosed in parantheses, like
command \( /l/;/a/ \)
this gives error message:
E54: Unmatched \(

Regards

Anton_Wessel@t-online.de

### Expected behaviour

Error message is not justified. I suppose the reason is that vim takes the ";" es end of command.

### Version of Vim

vim version 8.2 (2019 Dec 12, Compiled Jan 31 2021 04:47:07)

### Environment

KNOPPIX 9.1

**Comment by Anton-Wessel** [comment] 2022-09-28 16:24
my bachslashes before parantheses your form had removed.
code has to be \\( /l/;/a/ \\)
with one backslash before (
and one backslash before )

Regards

**Comment by lacygoill** [comment] 2022-09-28 16:27
\( /l/;/a/ \)

What is this pattern supposed to match exactly in a given text?

---

   > vim version 8.2 (2019 Dec 12, Compiled Jan 31 2021 04:47:07)

This is 3 years old.  Try to reproduce on master.

**Comment by habamax** [comment] 2022-09-28 17:38
@Anton-Wessel please provide exact steps of what you are doing and what you expect to have.

Currently what I can deduce from your message is that you try to specify a range for a command:

```
:/l/;/a/
```
which is a range given by two searches, separated by `;`.

This range could be used with some command, for example `:p` (print):
```
:/l/;/a/p
```
It would print all lines in a range between 2 searches.

Now the *unclear* part is what you try to achieve with `\( /l/;/a/ \)`? What is the context? It is clearly not a range now...

**Comment by chrisbra** [comment] 2022-09-28 18:50
This does not look like  a bug here. So please clarify and answer @habamax  questions.

**Comment by Anton-Wessel** [comment] 2022-09-29 09:44
Dear Mr.Braband,

thank you for your Email of 28.08.2022 20:51

1.

The link, you gave me, i.e. @habamax, I have used and spent a very long 
time. But there I have nothing found what could be relevant to the item I 
reported.

2.

The link "view it on github" contains questions to me.

+++++
\( /l/;/a/ \)


What is this pattern supposed to match exactly in a given text?

-----

Answer:

The aim is to search for the letter "l". Then after "l" is found, in the 
same command to make a follow search and search the letter "a".

When "a" is found, at that location, I have to make editing by hand.

In a very long file there are very many such locations to be edited by hand.

To find each location, one by one, this pattern is used.

After half an hour of such work a wish for more autonatization came up.

e.g., to swich from one location to the next, the usual method, typing "N", 
should work. This is not the case whith the special offset ";" to make a 
follow-up search.

Instead, typing "N" causes to find the next "a" but not to apply the whole 
search command.This case and other automatization trials needs to group and 
enclose the whole command into parantheses.

Please do not try to convince me not to make such a work.

Why is reporting an issue so time consuming ?

Regards

***@***.***


=====

Am 28. September 2022 20:51:18 schrieb Christian Brabandt 
***@***.***>:

**Comment by chrisbra** [comment] 2022-09-29 09:56
so instead of trying to using 2 patterns, maybe you want to make this one single pattern instead:

```
/l\_.\{-\}a
```

Or if you want to further automate it, you may want to use a `:g` command:
something like:

```
:g/l/;/a/p
```
to print the range (not sure it will do exactly what you need so)

> Why is reporting an issue so time consuming ?

You can also use the vim-dev or vim-use mailinglist (as you have done in the past, I believe).

**Comment by Anton-Wessel** [comment] 2022-09-29 09:57
thanks,

please read my email of 29.09.2022 11:45

which I am sending you as an attachmenr.


=====

Am 28. September 2022 19:38:35 schrieb Maxim Kim ***@***.***>:
> @Anton-Wessel please provide exact steps of what you are doing and what you 
> expect to have.
>
> Currently what I can deduce from your message is that you try to specify a 
> range for a command:
>
> :/l/;/a/
>
>
> which is a range given by two searches, separated by ;.
>
> This range could be used with some command, for example :p (print):
>
> :/l/;/a/p
>
>
> It would print all lines in a range between 2 searches.
>
> Now the unclear part is what you try to achieve with \( /l/;/a/ \)? What is 
> the context? It is clearly not a range now...
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.


﻿Re: [vim/vim] normal mode search command "/" with special offset ";" breaks parantheses (Issue #11245)
Von: Anton Wessel ***@***.***
An: vim/vim ***@***.***
Donnerstag, 29. September 2022, 11:45

Dear Mr.Braband,

thank you for your Email of 28.08.2022 20:51

1.

The link, you gave me, i.e. @habamax, I have used and spent a very long time. But there I have nothing found what could be relevant to the item I reported.

2.

The link "view it on github" contains questions to me.

+++++
\( /l/;/a/ \)


What is this pattern supposed to match exactly in a given text?

-----

Answer:

The aim is to search for the letter "l". Then after "l" is found, in the same command to make a follow search and search the letter "a".

When "a" is found, at that location, I have to make editing by hand.

In a very long file there are very many such locations to be edited by hand.

To find each location, one by one, this pattern is used.

After half an hour of such work a wish for more autonatization came up.

e.g., to swich from one location to the next, the usual method, typing "N", should work. This is not the case whith the special offset ";" to make a follow-up search.

Instead, typing "N" causes to find the next "a" but not to apply the whole search command.This case and other automatization trials needs to group and enclose the whole command into parantheses.

Please do not try to convince me not to make such a work.

Why is reporting an issue so time consuming ?

Regards

***@***.***


=====

Am 28. September 2022 20:51:18 schrieb Christian Brabandt ***@***.***>:

**Comment by chrisbra** [comment] 2022-09-29 10:44
> please read my email of 29.09.2022 11:45

I did. Did you not read my comment?

> which I am sending you as an attachmenr.

on a side note: it does not make sense to add attachments to mails that are directed to github issues. It makes reading the issue more confusing.

**Comment by chrisbra** [comment] 2022-09-29 10:59
and maybe I should comment some more.

the `;` is used to separate two addresses, that form a range. You cannot add `()` around those two addresses and therefore you receive the error message.

So you can either try to translate your search command to a single one, that's what my `/l\_.\{-\}a` pattern tried to match. Not sure if this will always match exactly what you need (may depend on corner cases like overlapping matches, etc and you may need to add the end offset `/e` to have the cursor move to the end of your match). 

Or you can use your range command, but then the `n` will not repeat this, because it is not a normal search command. 

But you can then define your own command that does this, by using e.g. 

```
:command JumpNext /l/;/a/
```
(untested, so you may need to fiddle with this a bit)

So then use the `:JumpNext` command to jump to your next interesting location.

**Comment by chrisbra** [comment] 2022-09-29 16:39
> Dear Mr.Brabandt,
You can call me Chris :) 

> My code allows to specify an offset, e.g.
> 
>     /l/;/a/e-2
> 

Yes and `n` will only repeat the *last* search command. I see where you are coming from. Anyhow, would a custom command not work for you? Which you can then map to a custom key and use that.

**Comment by Anton-Wessel** [comment] 2022-10-02 16:24
Dear Mr.Brabandt,

my last email to our former item was of 29.09.2022 18:49

Now I wold like to try to begin a new discussion with you.

I have your email address, and I am glad to have it. But I don't know if 
this email address is approropriate for my next item.

You are the only living Linux-Man, the only person I know in the moment, 
not a machine like stackexchange etc.

I am working on a good linux tool, .on a bash script named

we_find__in_find_its_path_ARG1__find_its_posix_extended_regex_to_search_ARG2__grep_its_PCRE_regex_to_search_contents_ARG3

I would like to post this my tool. And I have many reasons to do this:

a.

As an ammendment to a post if mine and to my comment therein to one of the 
replies.

b.

to additionally show what I expect from a "good" Linux tool.

c.

to offer this tool to be used by somebody else.

I would like to ask you if you are willing to help me with this intention.

I yes, then many emails would follow:

the reasons in detail,

comments, remarks to my code,

the code itself.

On the last, the question is, how to deliver my code.

I cannot bother with the forms of e.g. stackexchenge.

I can only send it as an attachment to an email.

All beyond would stay as task of you. You have the proficiency.


Regards

Anton Wessel

**Comment by chrisbra** [comment] 2022-10-05 12:34
you can contact me offline if you want. Not sure if I am able to help with whatever you are trying to achieve.

**Comment by chrisbra** [comment] 2022-10-05 12:34
anyhow, it looks like there is no issue here, so let me close this issue.

**Closed as completed by chrisbra** 2022-10-05 12:34 UTC
Labels: bug

**Comment by Anton-Wessel** [comment] 2022-10-05 19:39
Thank you for your email of today, 05.10.2022 14:34

But I do not understand what you mean by

> you can contact me offline if you want.

An email cannot go offline. And I can only communicate via email.

Its at all not urgent. In the development of my script I have a lot to do.

And since I am yet on the way to restore what aptitude and we-get had 
removed thousends of packages, my computer makes problems. commands I have 
used since tens of years, e.g.

xargs /bin/bash  zc '...'

do not work in the moment.

Regards

Anton Wessel



=====


Am 5. Oktober 2022 14:34:24 schrieb Christian Brabandt 
***@***.***>:

**Comment by chrisbra** [comment] 2022-10-06 07:33
by offline I mean outside of this forum here.

**Comment by Anton-Wessel** [comment] 2022-10-11 06:56
thanks,

please read my email of 29.09.2022 11:45

which I am sending you as an attachmenr.


=====

Am 28. September 2022 18:27:51 schrieb lacygoill ***@***.***>:
> \( /l/;/a/ \)
>
>
> What is this pattern supposed to match exactly in a given text?
>
> vim version 8.2 (2019 Dec 12, Compiled Jan 31 2021 04:47:07)
>
> This is 3 years old. Try to reproduce on master.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.


﻿Re: [vim/vim] normal mode search command "/" with special offset ";" breaks parantheses (Issue #11245)
Von: Anton Wessel ***@***.***
An: vim/vim ***@***.***
Donnerstag, 29. September 2022, 11:45

Dear Mr.Braband,

thank you for your Email of 28.08.2022 20:51

1.

The link, you gave me, i.e. @habamax, I have used and spent a very long time. But there I have nothing found what could be relevant to the item I reported.

2.

The link "view it on github" contains questions to me.

+++++
\( /l/;/a/ \)


What is this pattern supposed to match exactly in a given text?

-----

Answer:

The aim is to search for the letter "l". Then after "l" is found, in the same command to make a follow search and search the letter "a".

When "a" is found, at that location, I have to make editing by hand.

In a very long file there are very many such locations to be edited by hand.

To find each location, one by one, this pattern is used.

After half an hour of such work a wish for more autonatization came up.

e.g., to swich from one location to the next, the usual method, typing "N", should work. This is not the case whith the special offset ";" to make a follow-up search.

Instead, typing "N" causes to find the next "a" but not to apply the whole search command.This case and other automatization trials needs to group and enclose the whole command into parantheses.

Please do not try to convince me not to make such a work.

Why is reporting an issue so time consuming ?

Regards

***@***.***


=====

Am 28. September 2022 20:51:18 schrieb Christian Brabandt ***@***.***>:

**Comment by Anton-Wessel** [comment] 2022-10-11 08:42
Dear Mr.Brabandt,

thank you for your Email of 29.09.2022 12:59

Now we have it.

The one part is an item of designation.

In the vim-help one can read:

++++-
a very special offset is ";".
is like executing two search commands, except that:
- can be used as a single motion command.
- the direction for a following "n" or "N" command comes from the first 
command.
-----

It is not written that the object used by the following "n" or "N" command 
is the pattern of   o n l y   the second comnand.

Thus this is natural to be anderstood as  "? can be used as a single search 
command ?".

The other part is that vim -- on closer inspection -- use grouping of 
commands only for autocomnands, but not for commands in general (as, e.g. 
sed does).

Yet this behavior of vim cannot be called a bug, you call it

> You cannot add () around those two

You give a very, very fine solution to this item of grouping:
> But you can then define your own command that does this, by using e.g.
>
> :command JumpNext /l/;/a/
This possibility I have overlooked.
Thank you very much.


But trying to use this, another imperfection occurs:

In the search history my code with the two seaches is correct, and I can 
recall it by "/", and can execute it by RET.

But looking into the register "/" yiels only a fragnent of my code, only 
the beginning / and something of the end.

I would like to bring the contents of the search register into the Ex 
cmdline as usual.

Is not possible.

When I type my code by hand, the definition of the User Command is going 
perfectly. I can list the User Commands, and all is ok.

But the execution of this defined user command is not possible:

Gives allways this error message:

E481: No range allowed.

But I do not specify a range, I type:

:Wevimcmd01

Regards

Anton Wessel


=====



Am 29. September 2022 12:59:53 schrieb Christian Brabandt 
***@***.***>:
