### ISSUE TITLE
Terminal window does not differentiate between CTRL-J and CTRL-M

### ISSUE THREAD

**Issue by junegunn** [vim/vim#2031] opened 2017-08-29 01:13 UTC
### Affected version: 

```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Aug 29 2017 10:06:43)
MacOS X (unix) version
Included patches: 1-1010
```

### Test environment

- macOS Sierra
- Both with iTerm2 and macOS terminal

### Steps to reproduce:

- Start terminal (`:terminal`)
- Run `ruby -rio/console -e '2.times { p IO.console.getch }'`
- Press CTRL-J and CTRL-M

Terminal prints `"\n"` twice instead of `"\n"` and `"\r"`.

**Comment by tonymec** [comment] 2017-08-29 02:40
I think this is intentional, see `:help i_CTRL-J` and immediately below it, `:help i_CTRL-M`. Whether an end-of-line is represented by a carriage return (CR, ^M, 0x0D), a line feed (LF, ^J, 0x0A) or both (CR+LF, ^M^J, 0x0D 0x0A, but not the opposite sequence) is defined by the `'fileformat'` option. Those ends-of-line are not shown in the window displayed by Vim, but they are understood when reading and added when writing. Using

    :setlocal ff=dos

will accept either a LF not preceded by CR, or a CR+LF pair, as an end-of-line when reading, and write a CR+LF pair when writing. OTOH,

    :setlocal ff=unix

accepts only a LF as an end-of-line, and displays any CR as ^M, even if it immediately precedes a LF.
Note that the opposite sequence (LF followed by CR) is never treated as a single end-of-line. The third value (`mac`) should be used only for files from Mac OS 9 or earlier, where the end-of-line was a CR alone.

**Comment by junegunn** [comment] 2017-08-29 03:24
@tonymec Hi Tony, I renamed the issue to avoid further confusion. I'm reporting an issue on the new `:terminal` window.

**Comment by chrisbra** [comment] 2017-08-29 05:28
duplicate of #1998

**Closed as completed by chrisbra** 2017-08-29 05:28 UTC
