### ISSUE TITLE
`b:changedtick` incremented twice on buffer reload

### ISSUE THREAD

**Issue by noscript** [vim/vim#12234] opened 2023-04-06 12:55 UTC
### Steps to reproduce

1. Create `~/changedtick.vim`:
```vim
vim9script
echom 'start' b:changedtick
autocmd BufReadPost * {
  echom 'autocmd' b:changedtick
  timer_start(0, (_) => execute("echom 'timer' b:changedtick", ""))
}
```
2. Run Vim:
`vim -g -f --clean +'so ~/changedtick.vim' README.txt`
3. Reload the file:
`:e`
4. Print messages:
`:mes`
outputs:
```
Messages maintainer: Bram Moolenaar <Bram@vim.org>
"README.txt" 133L, 4908B
start 3
"README.txt" 133L, 4908B
autocmd 4
timer 5
```

### Expected behaviour

```
Messages maintainer: Bram Moolenaar <Bram@vim.org>
"README.txt" 133L, 4908B
start 3
"README.txt" 133L, 4908B
autocmd 4
timer 4
```

### Version of Vim

9.0.1439

### Environment

OS: Debian 12
Terminal: GUI

**Comment by brammool** [comment] 2023-04-15 12:16
> ### Steps to reproduce
> 
> 1. Create `~/changedtick.vim`:
> ```vim
> vim9script
> echom 'start' b:changedtick
> autocmd BufReadPost * {
>   echom 'autocmd' b:changedtick
>   timer_start(0, (_) => execute("echom 'timer' b:changedtick", ""))
> }
> ```
> 2. Run Vim:
> `vim -g -f --clean +'so ~/changedtick.vim' README.txt`
> 3. Reload the file:
> `:e`
> 4. Print messages:
> `:mes`
> outputs:
> ```
> Messages maintainer: Bram Moolenaar ***@***.***>
> "README.txt" 133L, 4908B
> start 3
> "README.txt" 133L, 4908B
> autocmd 4
> timer 5
> ```
> 
> 
> ### Expected behaviour
> 
> ```
> Messages maintainer: Bram Moolenaar ***@***.***>
> "README.txt" 133L, 4908B
> start 3
> "README.txt" 133L, 4908B
> autocmd 4
> timer 4
> ```

b:changedtick is incremented for every change to the buffer.
Sometimes it is incremented for a change that doesn't actually change
the buffer text, because Vim doesn't compare the text before and after
(for the ":e" command it would have to compare all lines in the buffer,
which would be quite a bit of overhead).

Is this really a problem?  Or just unexpected?

-- 
Dreams are free, but there's a small charge for alterations.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment] 2023-04-15 15:41
Hm, this seems to come from the fact, that `do_ecmd` reloads the same file and calls [buf_clear_file()](https://github.com/vim/vim/blob/master/src/ex_cmds.c#L3006), which then increments the changetick var in `unchanged()` and then later calls `open_buffer()` which eventually calls [unchanged()](https://github.com/vim/vim/blob/master/src/change.c#L907) again which increments the changetick variabls one more time. 

I guess this patch would fix this:
```patch
diff --git a/src/buffer.c b/src/buffer.c
index 6d4c4359f..4adb117a3 100644
--- a/src/buffer.c
+++ b/src/buffer.c
@@ -782,7 +782,7 @@ aucmd_abort:
            // Init the options when loaded again.
            buf->b_p_initialized = FALSE;
        }
-       buf_clear_file(buf);
+       buf_clear_file(buf, TRUE);
        if (del_buf)
            buf->b_p_bl = FALSE;
     }
@@ -794,10 +794,10 @@ aucmd_abort:
  * Make buffer not contain a file.
  */
     void
-buf_clear_file(buf_T *buf)
+buf_clear_file(buf_T *buf, int increment_changedtick)
 {
     buf->b_ml.ml_line_count = 1;
-    unchanged(buf, TRUE, TRUE);
+    unchanged(buf, TRUE, increment_changedtick);
     buf->b_shortname = FALSE;
     buf->b_p_eof = FALSE;
     buf->b_start_eof = FALSE;
@@ -812,6 +812,7 @@ buf_clear_file(buf_T *buf)
 #endif
 }

+
 /*
  * buf_freeall() - free all things allocated for a buffer that are related to
  * the file.  Careful: get here with "curwin" NULL when exiting.
@@ -2292,7 +2293,7 @@ buflist_new(
     buf->b_flags = BF_CHECK_RO | BF_NEVERLOADED;
     if (flags & BLN_DUMMY)
        buf->b_flags |= BF_DUMMY;
-    buf_clear_file(buf);
+    buf_clear_file(buf, TRUE);
     clrallmarks(buf);                  // clear marks
     fmarks_check_names(buf);           // check file marks for this file
     buf->b_p_bl = (flags & BLN_LISTED) ? TRUE : FALSE; // init 'buflisted'
diff --git a/src/ex_cmds.c b/src/ex_cmds.c
index 3ccb29ab3..45c4cb115 100644
--- a/src/ex_cmds.c
+++ b/src/ex_cmds.c
@@ -3003,7 +3003,7 @@ do_ecmd(
        if (aborting())     // autocmds may abort script processing
            goto theend;
 #endif
-       buf_clear_file(curbuf);
+       buf_clear_file(curbuf, FALSE);  // changedtick will be incremented later in open_buffer()
        curbuf->b_op_start.lnum = 0;    // clear '[ and '] marks
        curbuf->b_op_end.lnum = 0;
     }
diff --git a/src/proto/buffer.pro b/src/proto/buffer.pro
index 3a6102789..c7cac0260 100644
--- a/src/proto/buffer.pro
+++ b/src/proto/buffer.pro
@@ -6,7 +6,7 @@ void set_bufref(bufref_T *bufref, buf_T *buf);
 int bufref_valid(bufref_T *bufref);
 int buf_valid(buf_T *buf);
 int close_buffer(win_T *win, buf_T *buf, int action, int abort_if_last, int ignore_abort);
-void buf_clear_file(buf_T *buf);
+void buf_clear_file(buf_T *buf, int increment_changedtick);
 void buf_freeall(buf_T *buf, int flags);
 void free_wininfo(wininfo_T *wip);
 void goto_buffer(exarg_T *eap, int start, int dir, int count);
```

not sure if this is worth it...

**Comment by noscript** [comment] 2023-04-15 16:41
>Is this really a problem?  Or just unexpected?

Yes, the problem is that the second increment happens asynchronously.

When I change the buffer content or reload it, I save the current changedtick and report the changes to LSP server and request semantic highlighting from LSP server. Once I receive the response from LSP, I compare changedtick to see if something has changed in between, and if so, I invalidate the response. So then I have to do another request. Basically I need to do two same requests when reloading the buffer.

This is not critical, because I can track my own changedtick via `listener_add()`.

**Comment by brammool** [comment] 2023-04-15 20:12
> Hm, this seems to come from the fact, that `do_ecmd` reloads the same
> file and calls
> [buf_clear_file()](https://github.com/vim/vim/blob/master/src/ex_cmds.c#L3006),
> which then increments the changetick var in `unchanged()` and then
> later calls `open_buffer()` which eventually calls
> [unchanged()](https://github.com/vim/vim/blob/master/src/change.c#L907)
> again which increments the changetick variabls one more time. 
> 
> I guess this patch would fix this:

Well, except that when something fails b:changedtick is not incremented
even though the buffer was changed.  Handling different kinds of errors
is going to be a bit complicated.

I also think that it's fine to consider this to be two changes: making
the buffer empty and reading the file.  This behavior doesn't really
need to be changed.

Considering the other remark: Your main problem appears to be that
b:changedtick is incremented after triggering the BufReadPost event.
This happens because BufReadPost is triggered in readfile(), while
unchanged() is called in open_buffer() after calling readfile().
Changing this is going to be tricky, since there are quite a few calls
to both functions.

For keeping track of changes the listener functionality is certainly the
way to go, that's what it was intended for.

-- 
ROBIN:  (warily) And if you get a question wrong?
ARTHUR: You are cast into the Gorge of Eternal Peril.
ROBIN:  Oh ... wacho!
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment] 2023-04-16 07:25
then let's close it.

**Closed as not planned by chrisbra** 2023-04-16 07:25 UTC
Labels: bug
