### ISSUE TITLE
GVim: <c-x><c-k> not working when there is an insert-mode <c-k> mapping

### ISSUE THREAD

**Issue by dstein64** [vim/vim#9889] opened 2022-03-03 19:40 UTC
### Steps to reproduce

```vim
gvim --clean
set dictionary=/usr/share/dict/words
inoremap <c-k> <cmd>echom 'hello'<cr>
```
In insert mode, type "a", then enter `<c-x><c-k>` for dictionary completion.

### Expected behaviour

Expected: A popup would show that displays completion items, matching the behavior of command-line Vim.

Actual: No popup shows, and the `<c-k>` mapping executes.

### Version of Vim

8.2.4500

### Environment

Kubuntu 21.10
Terminal Konsole 21.08.1
Value of $TERM: xterm-256color
Shell: bash

**Comment by brammool** [comment] 2022-03-03 21:54
This appears to be specific for the GUI.  In a terminal it works OK.

**Comment by lacygoill** [comment] 2022-03-04 03:27
Duplicate of #8799.

Regression introduced in patch [8.2.0851](https://github.com/vim/vim/releases/tag/v8.2.0851).

**Comment by lacygoill** [comment] 2022-03-04 03:30
> Regression introduced in patch 8.2.0851.

This patch is also responsible for https://github.com/vim/vim/issues/8792.

**Comment by brammool** [comment] 2022-03-04 14:52
> > Regression introduced in patch 8.2.0851.
> 
> This patch is also responsible for https://github.com/vim/vim/issues/8792.

Does the patch for this issue also fix that one?

-- 
hundred-and-one symptoms of being an internet addict:
161. You get up before the sun rises to check your e-mail, and you
     find yourself in the very same chair long after the sun has set.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Closed as completed** 2022-03-04 14:51 UTC

**Comment by lacygoill** [comment] 2022-03-04 15:00
> Does the patch for this issue also fix that one?

Unfortunately, it does not.  However, it does fix https://github.com/vim/vim/issues/8799 .
