### ISSUE TITLE
Make :syn-containedin restrictive

### ISSUE THREAD

**Issue by matveyt** [vim/vim#7199] opened 2020-10-25 08:34 UTC
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**

`:syntax` command accepts a number of arguments (`:h :syn-arguments`). But none of them is restrictive enough to make sure that one group is only contained inside another. Consider this,

        syntax match A /.../ contains=ALL
        syntax match B /.../
        syntax match C /.../ contained containedin=B

At first it may look as if C is contained in B only, but currently this is just an equivalent of

        syntax match A /.../ contains=ALL
        syntax match B /.../ contains=C
        syntax match C /.../ contained

And therefore group C is contained in both A and B. I'm not aware of any way to prevent C from being contained in A.

However, as mentioned in `:h syn-containedin`, the "containedin" argument "is useful when adding a syntax item afterwards". So it could be more logical (and possibly faster)  if it had precedence over unrestrictive groups with "contains=ALL" or "contains=ALLBUT".

**Describe the solution you'd like**

Make command "syntax match C /.../ containedin=B" to work in such a way that C is only contained in B, or groups with explicit "contains=C", but not "contains=ALL", "contains=ALLBUT", "contains=TOP" or "contains=CONTAINED".

Of course, this could have many consequences for existsing syntax files and needs testing. But potentially syntax performance could only benefit from this.

**Comment by bfrg** [comment] 2020-10-25 09:33
Duplicate of https://github.com/vim/vim/issues/1265 and https://github.com/vim/vim/issues/6426

**Comment by brammool** [comment] 2020-10-25 12:33
Using "contains=ALL" is really "all".  If that's not wanted, then don't use it.
There are several tactics of defining the syntax, some are more for simple syntax files, others for complicated ones.
A generic one that could replace the "contains=ALL" is to create a cluster "Toplevel" for all toplevel items,
then us "contains=@Toplevel" for items that can contain other toplevel items.
This is more complicated, since you need to create this cluster and make sure it contains the right items.
The "contains=ALL" way is a lot simpler, but it can't always be used.

**Comment by matveyt** [comment] 2020-10-25 12:57
@brammool  The problem is that existing syntax files never follow this logic. It looks like every (standard!) syntax file out there has

        syn region MyParen start="(" end=")"  contains=ALLBUT,X,Y,Z

End even if _some_ of them have

        syn region MyParen start="(" end=")"  contains=ALLBUT,@MyParenGroup

it's almost impossible to extend a dozen of such syntaxes in a general manner.

**Closed as completed** 2021-02-25 15:09 UTC
Labels: enhancement
