### ISSUE TITLE
VimResized not triggering

### ISSUE THREAD

**Issue by TheFantasticWarrior** [vim/vim#12154] opened 2023-03-15 05:01 UTC
### Steps to reproduce

starting vim in i3(tested on urxvt and kitty)
start a new terminal(splits the screen)

### Expected behaviour

I have a `autocmd VimResized * exe "normal!  \<C-l>"` that doesn't trigger when window is resized
`doautocmd VimResized` works

### Version of Vim

VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Feb 21 2023 18:10:20) Included patches: 1-1337 Compiled by Arch Linux

### Environment

archlinux-keyring-20230225-1
kitty-shell-integration-0.27.1-1 
kitty-terminfo-0.27.1-1
i3-wm-4.22-3
kitty-0.27.1-1

**Comment by chrisbra** [comment] 2023-03-15 08:06
can you please verify with a different wm? I think we had similar issues with this particular WM

**Comment by TheFantasticWarrior** [comment] 2023-03-16 08:01
Haven't tried other wm but apparently no issue with ST terminal+i3, even without the autocmd, maybe it's certain combinations?

**Comment by brammool** [comment] 2023-03-31 19:18
The VimResized event is triggered when the Vim window is changed, that is when the 'lines' and/or 'columns option changes value.  It does not trigger when a window inside Vim changes size or when a new window is opened.

You mention "when window is resized", what do you mean exactly?

**Comment by TheFantasticWarrior** [comment] 2023-04-01 02:16
Like when in i3 a full screen vim is opened, then open a new window splitting the window in half, then close the new window making vim window back to full screen size, but the text will still be half the screen

**Comment by khodedawsh** [comment] 2024-03-15 15:07
I'm encountering the same problem on a similar setup(i3+kitty+arch).
basically resizing the kitty window/tab in any way breaks vim, however if I run in the following ways it works correctly:
```
$ env TERM=kitty vim
$ vim -T kitty
```
TERM is by default set to xterm-kitty by kitty, other programs(like htop) detect both `kitty` and `xterm-kitty` and work OK.
vim however only detects `kitty`

**Comment by chrisbra** [comment] 2024-03-15 15:34
try to compare `:set termcap` values for both TERMINAL modes, perhaps this gives an indication. The help also has a short section on xterm-kitty vs kitty I believe.

**Comment by khodedawsh** [comment] 2024-03-15 19:14
> The help also has a short section on xterm-kitty vs kitty I believe.

Well I see there's a section suggesting the variable name should have been kitty, which isn't by default.
The only difference I see is `t_XM`; It's empty for xterm-kitty but not for kitty.

**Comment by chrisbra** [comment] 2024-03-16 14:47
`t_XM` is mouse reporting capability. In any case the help suggests, that setting `kitty` as $TERM is the right thing to do. So you should be using that.

**Comment by khodedawsh** [comment] 2024-03-16 22:23
The mouse is working fine in both cases.
well why isn't vim resized when $TERM is xterm-kitty? why shouldn't it?

I just noticed there is a problem with $TERM=kitty and htop also, lol.

**Comment by chrisbra** [comment] 2024-03-17 08:51
> I just noticed there is a problem with $TERM=kitty and htop also, lol.

Well, please give precise instructions. That is not what I would call a good bug report :/

**Comment by khodedawsh** [comment] 2024-03-17 15:35
### Steps to reproduce
1. start kitty
2. make sure $TERM is set to xterm-kitty (default value)
3. run vim
4. resize the kitty window in any way you'd prefer

### Behaviour
the screen breaks in case you make the terminal window smaller, and it doesn't change size if you make the window larger
![image](https://github.com/vim/vim/assets/156741006/c5029c8b-be69-4c06-931b-fa57d9fed7e5)

### Expected behaviour
vim should re-render the terminal screen.

### Version of Vim
VIM - Vi IMproved 9.1 (2024 Jan 02, compiled Mar 05 2024 22:43:21)
Included patches: 1-151
Compiled by Arch Linux

### Environment
kitty{,-shell-integration,-terminfo}-0.33.0-1 
i3-wm-4.23-1
no ~/.vimrc is created
tested both with and without --clean option.
tested on three different archlinux+i3 setups, all belonging to different people + a fourth one which is mine.
tested using both bash and fish.

## Some experiments with the environment
strangely after creating the `~/.vimrc` file the issue is fixed to some extent, although I noticed other issues. and this doesn't work out of the box obviously.
on the other hand `vim --clean` ensures the same result is produced 
using `TERM=kitty` completely fixes the problem in vim. however it causes problems with htop and possibly other tools.


### Logs and stack traces
I would provide logs but I didn't find out how I could gather it for this context.

**Comment by khodedawsh** [comment] 2024-03-17 15:38
> Well, please give precise instructions. That is not what I would call a good bug report :/

the problem with htop is that when I bring my cursor inside the kitty window with htop open,
it resorts the processes in the reverse order.
like from ascending to descending order.
this only happens when $TERM is set to kitty

**Comment by chrisbra** [comment] 2024-03-17 19:19
how did you resize the window? Is this specific to i3?

**Comment by khodedawsh** [comment] 2024-03-17 21:06
> how did you resize the window?

it doesn't matter/ you could make the window floating and change its size or make it fullscreen or...

> Is this specific to i3?

I don't think it is. even though the only environment I ran this on was arch+i3.
I'll ask around and see if I could test this on ubuntu or debian.

but if you know any way I could find more details or a log I'd be happy to do it. 
perhaps the problem could be from archlinux patches on vim or even kitty.

**Comment by khodedawsh** [comment] 2024-03-20 23:45
This isn't specific to i3.
successfully reproduced on kde plasma.

**Comment by mmdchnar** [comment] 2024-03-21 00:04
i check it in kde plasma with kitty and konsole and with them test in tmux too
and the result is everything is fixed in konsole
but when manually resize the kitty
the bug happened
in kitty with tmux but it is fixed and resize is ok
so when tmux handle the resizing it is ok!

as my result i think the issue is about kitty, not the vim

**Comment by khodedawsh** [comment] 2024-03-21 01:21
> I can also reproduce this. Adding this line to vimrc fixes the issue for me:
> 
> ```viml
> set ttymouse=sgr
> ```
> 
> Can you guys confirm?

as I said adding nothing to .vimrc fixes this for me.
remove that line but don't delete your .vimrc and try again.

**Comment by julio-b** [comment] 2024-04-03 18:13
If anyone still has this problem, please test PR #14401.

**Comment by chrisbra** [comment] 2024-04-03 20:04
I suppose #14401 only fixes it if one uses `+mouse_gpm`? Is that what you have @khodedawsh @TheFantasticWarrior ?

**Comment by khodedawsh** [comment] 2024-04-03 22:18
Yes `mouse_gpm` is included; I think we have the same environment, will try the PR though asap.
Thanks @julio-b

**Closed as completed** 2024-04-04 19:56 UTC
Labels: bug
