### ISSUE TITLE
Termdebug display wrong file name in the GDB prompt buffer

### ISSUE THREAD

**Issue by skywind3000** [vim/vim#12550] opened 2023-06-16 09:40 UTC
### Steps to reproduce

```viml
:packadd termdebug
:Termdebug xxx
```

and type "run" in the gdb prompt window

### Expected behaviour

display the correct file name, not this:

![图片](https://github.com/vim/vim/assets/3035071/8c756421-58d6-436d-b436-a74690e70bbe)

The full path of the executable is `E:\Lab\workshop\scratch\scratch\test_gdb.exe`

gdb displays it as an escaped C string: `E:\\Lab\\workshop\\scratch\\scratch\\test_gdb.exe`

But in the last segment of the path, the `\\test` has been replaced as a backslash and a tab character 
(the tab character is visible as the bar character according to my listchar option).

This only happens on Windows. 

Definitely a minor display error, but it would be nice to get fixed, since termdebug is the 
only gdb front-end that can work on MS Windows (excluding vscode).

I want to give it a go, and wish it could be polished on Windows.

### Version of Vim

9.0.1627

### Environment

OS: Windows 10
Terminal: None (GVim)

**Comment by skywind3000** [comment] 2023-06-16 09:58
the display error happens in the command line as well:

![图片](https://github.com/vim/vim/assets/3035071/56989a3b-114f-4eb3-aeac-38a9ab1ffdce)

see the `^I` in the right side of the command line.

**Comment by chrisbra** [comment] 2023-06-16 11:13
Can you try if `:set shellslash` fixes the issue?

**Comment by skywind3000** [comment] 2023-06-16 14:07
same, after `:set shellslash` :

![图片](https://github.com/vim/vim/assets/3035071/f67a2d89-b867-48ee-9bbc-04efefd59ab3)

and

![图片](https://github.com/vim/vim/assets/3035071/bde4b92d-7b12-4712-bd28-de836cb5255e)

**Comment by skywind3000** [comment] 2023-06-16 14:13
and I found that the breakpointer in the signcolumn is not displayed on Windows (I have disabled vim-signify and vim-signature for potential conflict).

The current line highlighting is invisible too.

I'm not sure is it related to the same issue (file name can't be correctly read) ?

**Comment by chrisbra** [comment] 2023-06-19 16:24
this seems to be a duplicate of #12560

**Closed as completed** 2023-06-24 19:02 UTC
Labels: bug
