### ISSUE TITLE
vim9class: problem compiling object method call as function call argument

### ISSUE THREAD

**Issue by errael** [vim/vim#12081] opened 2023-02-27 22:32 UTC
### Steps to reproduce

Source 
```
vim9script

class Elem
endclass

class ElemContainer
    def Current(): Elem
        return Elem.new()
    enddef
endclass

var elems = ElemContainer.new()

def F()
    []->index(elems.Current())
enddef
F()
```

Observe
```
Error detected while compiling command line..script /home/err/bugs/vim/parse-object-method-arg/a.vim
[17]..function <SNR>31_F:
line    1:
E1013: Argument 1: type mismatch, expected list<any> but got object<ElemContainer>
```

### Expected behaviour

No error
Notice that the following works OK.
```
def G()
    var cur = elems.Current()
    echo []->index(cur)
enddef
G()
```

### Version of Vim

9.0.1362

### Environment

ubuntu

**Comment by qeatzy** [comment] 2023-05-18 11:15
Recently encountering 3 cases where cannot treat method as ordinary value that cause troubles.

1. result of `F(args)` as argument to `G()`. 
    - workaroud, create tmp variable from `F(args)` then pass to `G()`. 
    - Same as op's case. code exmaple below. Another one at https://github.com/vim/vim/issues/12324

2. object `c: C` that has `this.Cbs: list<func>`, `def AddCb(Cb: func)`. you want to use a method from `b: B` as `Cb`.
    -  workaroud, create a funcref, eg, via a lambda expression.
    - say your `Cb` of type `func(number, string): bool`, b's method name is `Key`, 
    - `c.AddCb(b.Key)` not work. `c.AddCb((id, key) => b.Key(id, key))` works.
    - another post https://github.com/vim/vim/issues/11981
    - This one is quite common as long you lean to functional programming style and/or prefer composition over inheritance. Almost all well-known programming support it, you can pass golang method around and no difference from function, so is python, java are all method, not to mention javascript/typescript which has functional origin from the start, or other languages with known fame of feature complete/complex (rust/c++/scala/etc).
3. when using `call()` to unpack variable argument but first argument is a method.
    - seems no workaround available yet.
    - (for detailed example see issues/11865.](https://github.com/vim/vim/issues/11865#issuecomment-1552837824)

An example for case 1: result of F(args) as argument to G().
```
vim9script

class KeyStates
    def Key(id: number, key: string): bool
        if key =~ '^[jk]$'
            this.Normal(id, this.CntPrefix(key))
        endif
        return 1
    enddef
    def CntPrefix(key: string): string
        return key
        # var x = this.ttl >= 0 ? str2nr(this.prefix) : 0
        # return x >= 0 ? x .. key : key
    enddef
    def Normal(id: number, key: string)
        call win_execute(id, 'norm!' .. key)
    enddef
endclass

var ks = KeyStates.new()
ks.Key(1001, 'j')
```

error messages
```
Error detected while compiling ..function Key:
line    2:
E1013: Argument 1: type mismatch, expected number but got object<KeyStates>
```
workaround, create tmp variable. change from
```
            this.Normal(id, this.CntPrefix(key))
```
to
```
            const tmp = this.CntPrefix(key)
            this.Normal(id, tmp)
```

**Comment by brammool** [comment] 2023-05-18 15:42
> Recently encountering 3 cases where cannot treat method as ordinary value that cause troubles.
> 
> 1. result of `F(args)` as argument to `G()`. 
>     - workaroud, create tmp variable from `F(args)` then pass to `G()`. 
>     - Same as op's case. code exmaple below. Another one at https://github.com/vim/vim/issues/12324

So this is probably the same issue as #12324 ?

> 2. object `c: C` that has `this.Cbs: list<func>`, `def AddCb(Cb: func)`. you want to use a method from `b: B` as `Cb`.
>     -  workaroud, create a funcref, eg, via a lambda expression.
>     - say your `Cb` of type `func(number, string): bool`, b's method name is `Key`, 
>     - `c.AddCb(b.Key)` not work. `c.AddCb((id, key) => b.Key(id, key))` works.
>     - another post https://github.com/vim/vim/issues/11981
>     - This one is quite common as long you lean to functional
>     programming style and/or prefer composition over inheritance.
>     Almost all well-known programming support it, you can pass golang
>     method around and no difference from function, so is python, java
>     are all method, not to mention javascript/typescript which has
>     functional origin from the start, or other languages with known
>     fame of feature complete/complex (rust/c++/scala/etc).

Can you give example code?  Preferably in a way it can be used in a
test.

> 3. when using `call()` to unpack variable argument but first argument
> is a method.
>     - seems no workaround available yet.
>     - (for detailed example see issues/11865.](https://github.com/vim/vim/issues/11865#issuecomment-1552837824)

If the issue is described there, why mention it again here?  It is
strongly recommended to have one issue for each individual problem.
That is the only way we can keep track of individual issues, avoid that
issues are closed when only part of it has been fixed.


-- 
Everybody lies, but it doesn't matter since nobody listens.
                                -- Lieberman's Law

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by qeatzy** [comment] 2023-05-19 02:22
> > Recently encountering 3 cases where cannot treat method as ordinary value that cause troubles.
> > 
> > 1. result of `F(args)` as argument to `G()`.
> >    
> >    * workaroud, create tmp variable from `F(args)` then pass to `G()`.
> 
> So this is probably the same issue as [#12324](https://github.com/vim/vim/issues/12324) ?
> 
Yes. They are the same issue which occurs on a daily basis.

> > 2. object `c: C` that has `this.Cbs: list<func>`, `def AddCb(Cb: func)`. you want to use a method from `b: B` as `Cb`.
> >    
> >    * workaroud, create a funcref, eg, via a lambda expression.
> >    * say your `Cb` of type `func(number, string): bool`, b's method name is `Key`,
> >    * `c.AddCb(b.Key)` not work. `c.AddCb((id, key) => b.Key(id, key))` works.
> >    * another post [[vim9script] Cannot pass (instance or static) method to function #11981](https://github.com/vim/vim/issues/11981)
> >    * This one is quite common as long you lean to functional programming style and/or prefer composition over inheritance. Almost all well-known programming support it, you can pass golang method around and no difference from function, so is python, java are all method, not to mention javascript/typescript which has functional origin from the start, or other languages with known fame of feature complete/complex (rust/c++/scala/etc).
> 
> Can you give example code?  Preferably in a way it can be used in a
> test.

Here is an testable example code for case 2, the commented line is workaround via lambda.
Also note if you move the reporting error method to a plain function. it works without error.

```
vim9script

export class KeyStates
    this.winid: number
    this.filters: list<func(number, string): bool>
    this.watcher: func
    def AddFilter(...fs: list<func(number, string): bool>)
        this.filters->extend(fs)
    enddef
endclass

class FileSearcher
    this.ks = KeyStates.new()
    def Key(id: number, key: string): bool
        if key =~ '[jkG]'
            call win_execute(id, 'norm!' .. key)
        endif
        return 1
    enddef
    def new()
        # this.ks.AddFilter((id, key) => this.Key(id, key))
        this.ks.AddFilter(this.Key)
    enddef
endclass

var f = FileSearcher.new()
```

> > 3. when using `call()` to unpack variable argument but first argument is a method.
> >    
> >    * seems no workaround available yet.
> >    * (for detailed example see issues/11865.]([[vim9] Pass a list to a function with variable arguments #11865 (comment)](https://github.com/vim/vim/issues/11865#issuecomment-1552837824))
> 
> If the issue is described there, why mention it again here?  It is
> strongly recommended to have one issue for each individual problem.
> That is the only way we can keep track of individual issues, avoid that
> issues are closed when only part of it has been fixed.

Mention here because.
  - that issue is already closed. which request for ability to unpack variable arguments, which is solved by good old `call()`, probably not worth introducing new syntax.
  - the true problem in this case is *not ability to unpack variable arguments*, but rather **cannot treat method as ordinary value thus cannot pass as argument**
  - thus this is essentially same issue as case 2, but with a different use case and no workaround.
  
Treating method/function as plain value is essential in common programming language.
Python distinguish bound method and unbound methods (or a plain function object in python3).
In golang, method are function with receiver, which is its way of specifying *this* manually with the name you want.
```
//     `(f *File)` is called receiver in golang, serves same role as this/self in other language
//      you can give any name you like, what matters are receiver's type
func (f *File) Write(b []byte) (n int, err error) {
        // ...
	return n, err
}
```
But disregarding how it is implemented, almost all well-known language support use method/function as plain value. In vim9script currently there is inconsistency in this regard, you can pass a function as argument, but cannot pass a method as argument.

> An example for case 1: result of F(args) as argument to G().
> 
> ```
> vim9script
> 
> class KeyStates
>     def Key(id: number, key: string): bool
>         if key =~ '^[jk]$'
>             this.Normal(id, this.CntPrefix(key))
>         endif
>         return 1
>     enddef
>     def CntPrefix(key: string): string
>         return key
>         # var x = this.ttl >= 0 ? str2nr(this.prefix) : 0
>         # return x >= 0 ? x .. key : key
>     enddef
>     def Normal(id: number, key: string)
>         call win_execute(id, 'norm!' .. key)
>     enddef
> endclass
> 
> var ks = KeyStates.new()
> ks.Key(1001, 'j')
> ```
> 
> error messages
> 
> ```
> Error detected while compiling ..function Key:
> line    2:
> E1013: Argument 1: type mismatch, expected number but got object<KeyStates>
> ```
> 
> workaround, create tmp variable. change from
> 
> ```
>             this.Normal(id, this.CntPrefix(key))
> ```
> 
> to
> 
> ```
>             const tmp = this.CntPrefix(key)
>             this.Normal(id, tmp)
> ```

**Comment by errael** [comment] 2023-05-19 03:33
> cannot treat method as ordinary value thus cannot pass as argument
> ... and no workaround.

Doesn't passing something like (with args as needed)
```
(obj: MyType) => obj.MethodName()
```
achieve what you're looking for?

**Comment by qeatzy** [comment] 2023-05-19 04:54
> > cannot treat method as ordinary value thus cannot pass as argument
> > ... and no workaround.
> 
> Doesn't passing something like (with args as needed)
> 
> ```
> (obj: MyType) => obj.MethodName()
> ```
> 
> achieve what you're looking for?

Thank you. Didn't aware of variable argument lambda. 

For completeness, I copy test code of case 3 from https://github.com/vim/vim/issues/11865#issuecomment-1552837824, and added the workaround with variable argument lambda in comments.
```
vim9script

export class FWin # popup window, float window
    this.winid: number
    def Echo(...vals: list<any>)
        const x = len(vals) == 1 ? string(vals[0]) : string(vals)
        echo x
    enddef
endclass

var g_echoer = FWin.new()
def Echo(...vals: list<any>)
    call(g_echoer.Echo, vals)
    # call((...x) => g_echoer.Echo(x), vals)
enddef

Echo(1, 2, 3, "hello")
```

**Comment by qeatzy** [comment] 2023-05-19 05:23
> 



> > cannot treat method as ordinary value thus cannot pass as argument
> > ... and no workaround.
> 
> Doesn't passing something like (with args as needed)
> 
> ```
> (obj: MyType) => obj.MethodName()
> ```
> 
> achieve what you're looking for?

@errael My bad. I thought it works, but it's not. The behavior using variable argument lambda is different.

Here is the code showing the difference

```
vim9script

export class FWin # popup window, float window
    this.winid: number
    def Echo(...vals: list<any>)
        echo vals
    enddef
endclass

var g_echoer = FWin.new()
def Echo(...vals: list<any>)
    # call(g_echoer.Echo, vals) # original one trigger error
    call((...x) => g_echoer.Echo(x), vals) # lambada workaround, but incorrect
enddef

Echo(1, 2, 3, "hello")
var x = FWin.new()
x.Echo(1, 2, 3, "hello")
```

It ouputs
```
[[1, 2, 3, 'hello']] # this is clearly wrong, only one argument passed
[1, 2, 3, 'hello']
```

Looks like an A/B problem, introducing lambda suppress compilation error E1123, but didn't help to delegate variable argument to another variable argument function.

Look a little deeper in the code, `(...x) => g_echoer.Echo(x)` is insufficient, we need delegate in lambda too, something like `(...x) => g_echoer.Echo(x...)`.

**Comment by errael** [comment] 2023-05-19 07:26
I see. Until the bug, using a method call as a function, is fixed. There's
```
vim9script

export class FWin # popup window, float window
    this.winid: number
    def Echo(...vals: list<any>)
        this.EchoX(vals)
    enddef
    def EchoX(vals: list<any>)
        echo vals
    enddef
endclass

var g_echoer = FWin.new()
def Echo(...vals: list<any>)
    # call(g_echoer.Echo, vals) # original one trigger error
    g_echoer.EchoX(vals)
enddef

Echo(1, 2, 3, "hello")
var x = FWin.new()
x.Echo(1, 2, 3, "hello")
```

**Comment by brammool** [comment] 2023-05-19 13:05
> > Can you give example code?  Preferably in a way it can be used in a
> > test.
> 
> Here is an testable example code for case 2, the commented line is
> workaround via lambda.
> Also note if you move the reporting error method to a plain function.
> it works without error.

Thanks.  I'll look at it later when I get back to work on the class
implementation.

> But disregarding how it is implemented, almost all well-known language
> support use method/function as plain value. In vim9script currently
> there is inconsistency in this regard, you can pass a function as
> argument, but cannot pass a method as argument.

A method is different from a function reference, as with the method the
object it's bound to also needs to be passed.  It can probably be
implemented, in legacy script a dictionary could be used in a similar
way.

Passing a method without an object is a whole different thing, I don't
think we want to support that, because it gets complicated and requires
runtime type checking.  While it is hardly every useful.

-- 
Microsoft is to software what McDonalds is to gourmet cooking

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by qeatzy** [comment] 2023-05-20 11:19
> > But disregarding how it is implemented, almost all well-known language
> >  support use method/function as plain value. In vim9script currently
> >  there is inconsistency in this regard, you can pass a function as
> >  argument, but cannot pass a method as argument.
>
> A method is different from a function reference, as with the method the
> object it's bound to also needs to be passed.  It can probably be
> implemented, in legacy script a dictionary could be used in a similar
> way.

Yes, method *is different* from function, that's why python has bound method, golang has receiver. However, for language user encountering a value of callable type, it shouldn't matter it's a function or method or a member of callable type, nor should it care it's plain dot access or result of some expression (eg, return value of a func or get dict entry), nor should it care how the value being used (calling it or passed as argument).
> Passing a method without an object is a whole different thing, I don't
> think we want to support that, because it gets complicated and requires
> runtime type checking.  While it is hardly every useful.

Unless intend to support meta-programming of defining class dynamically, I don't see any urgent reason to support value of unbound method. I suppose it's ok to not allow it.

**Comment by brammool** [comment] 2023-05-20 12:00
> > > But disregarding how it is implemented, almost all well-known language
> > >  support use method/function as plain value. In vim9script currently
> > >  there is inconsistency in this regard, you can pass a function as
> > >  argument, but cannot pass a method as argument.
> >
> > A method is different from a function reference, as with the method the
> > object it's bound to also needs to be passed.  It can probably be
> > implemented, in legacy script a dictionary could be used in a similar
> > way.
> 
> Yes, method *is different* from function, that's why python has bound
> method, golang has receiver. However, for language user encountering a
> value of callable type, it shouldn't matter it's a function or method
> or a member of callable type, nor should it care it's plain dot access
> or result of some expression (eg, return value of a func or get dict
> entry), nor should it care how the value being used (calling it or
> passed as argument).

I don't think both things you say here can be true at the same time.
A class method can only be used in the context of that class, it cannot
be called the same way as a regular function.
Implementation of classes is only somewhere halfway, I currently just
want to get the basics done and work consistently.  Maybe later we can
look into some more flexibility, but I don't want to add much
complexity.  Go is not a good language to use as an example, it does not
support classes.

> > Passing a method without an object is a whole different thing, I don't
> > think we want to support that, because it gets complicated and requires
> > runtime type checking.  While it is hardly every useful.
> 
> Unless intend to support meta-programming of defining class
> dynamically, I don't see any urgent reason to support value of unbound
> method. I suppose it's ok to not allow it.

As I mentioned, I intend to avoid complexity.  Just basic classes and a
few things that most other languages do.  Let's keep it simple.

-- 
hundred-and-one symptoms of being an internet addict:
47. You are so familiar with the WWW that you find the search engines useless.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by qeatzy** [comment] 2023-05-20 17:15
> > Yes, method *is different* from function, that's why python has bound
> >  method, golang has receiver. However, for language user encountering a
> >  value of callable type, it shouldn't matter it's a function or method
> >  or a member of callable type, nor should it care it's plain dot access
> >  or result of some expression (eg, return value of a func or get dict
> >  entry), nor should it care how the value being used (calling it or
> >  passed as argument).
> > 
> 
> I don't think both things you say here can be true at the same time.
> A class method can only be used in the context of that class, it cannot
> be called the same way as a regular function.
> Implementation of classes is only somewhere halfway, I currently just
> want to get the basics done and work consistently.  Maybe later we can
> look into some more flexibility, but I don't want to add much
> complexity.  Go is not a good language to use as an example, it does not
> support classes.

So you do agree it should work with object method? I think static method behave same as regular function, at least in typescript and python.

Golang might be the only one of those new languages that gain wider adoption, its some choices are unconventional but did do many thing right. Go do support class, though it didn't use class keyword and method defined outside of struct block, which is unconventional, so is its choice of interface being implicit. But it's out of topic. Let's stop here.

As for class/static method, it's more akin to plain function than object method, with the class acting as kind of namespace or scope. let's using java/typescript/python/c++ as exmaple. And think some questions.
- is it possible to store/pass-around static method, similar to plain function?
- how can static method being accessed. `ClassName.M` is obvious choice, or just `M`, should `this.M` being valid?

For question 2, different language has different choices. But for question 1, I didn't see anything that prevent static method being used outside, IMO that's the role of private keyword. I think the answer for question 1 is yes for almost all language, though not 100% sure. Since plain function can already being store/pass around, it don't see any reason why static method cannot.

As for language feature, pure OOP is insufficient, some kind of functional programming support is a must for a successful language. Let's learn from the lesson of java in this regard, it only add lambda and functional interface in java 8, and syntax being kind of clumsy due to its language constraints. Vimscript support lambda and `function()`, `map()`, `filter()`, which already support many functional programming construct. Value semantic of function/method/static method, is essential for functional programming, otherwise it will behave similar to java 8, possible but clumsy. Typescript is quite good in this regard. We probably won't need the flexibility of python.

Below illustrate some of above point in typescript/python.

```
// hello.ts
class Hello {
    Hello(s: string): void {
        console.log('hello', s)
    }
    static HelloStatic(s: string): void {
        console.log('hello', s)
    }
}

function wrapper(how: number): (s: string) => void {
    return how == 1 ? Hello.HelloStatic : (new Hello()).Hello
}

let x = new Hello()
x.Hello("world")
let f = x.Hello
f("f")
let g = Hello.HelloStatic
// g = x.HelloStatic
// let h = Hello.Hello
g("g")
wrapper(0)("f")
wrapper(1)("g")
```

```
# hello.py
class Hello:
    @staticmethod
    def HelloStatic(s):
        print("hello ", s)
    def Hello(self, s):
        print("hello ", s)

x = Hello()
x.HelloStatic("world")
f = x.HelloStatic
g = Hello.HelloStatic
f("f")
g("g")

x = Hello()
x.Hello("world")
f = x.Hello
g = Hello.Hello
f("f")
g(x, "g")
```

Python is more lenient, permitting access static method through instance, and value of unbound method and manually bind it. Both of which is invalid in typescript.

**Comment by errael** [comment] 2023-05-20 19:33
I'm having trouble understanding what this thread is about anymore.

I thought the question was about begin able to do something like
```
var F: func = obj.classMethod
var G: func = obj.classStatic
F(arg)
G(arg)
```
And IIUC, something like that is on the radar. Of course sh*t happens, but I'm optimistic. (This is a divergence from the original issue, but in a similar vein)

If implemented, I hope this works as shown without needing to introduce a new type, and so remains an implementation detail.

The thread has evolved to other issues, but I'm not sure if anything's been requested that can't already be done. (except of course a method call as a func doesn't work yet.)

A method name *can* be passed around; it's cumbersome. The following currently works.

```
var bounce_obj: any = null_object
def BounceMethod(obj: any, methodName: string, ...args: list<any>)
    bounce_obj = obj
    execute "bounce_obj." .. methodName .. '(' .. args->join(', ') .. ')'
enddef
```
other implementations are possible depending on how you want to deal with args.

IIRC, there was a comment/question about dynamically creating functions. In a few situations I've created tailored/optimized functions/lambdas out of strings.

Is there something else?

**Comment by brammool** [comment] 2023-05-20 21:25
> I'm having trouble understanding what this thread is about anymore.

Yeah, this drifted off in a direction unrelated to the actual issue
reported.  Let's move unrelated discussions elsewhere.  I'll try to
summarize.  This issue should just be for the error in the example
given, which is not about choices but an implementation bug

> I thought the question was about begin able to do something like
> ```
> var F: func = obj.classMethod
> var G: func = obj.classStatic
> F(arg)
> G(arg)
> ```
> And IIUC, something like that is on the radar. Of course sh*t happens,
> but I'm optimistic. (This is a divergence from the original issue, but
> in a similar vein)

There are two things:
1. Binding an object with an object method, like a dictionary is bound
   to a function on a dictionary.  "obj.classMethod" in the example.
2. Referring to a staic (class) function.  No binding needed, but the
   function name is scoped to the class namespace.  "obj.classStatic" is
   confusing, but that's a separate discussion.

> If implemented, I hope this works as shown without needing to
> introduce a new type, and so remains an implementation detail.

This applies to 1: It will be a new type, as the bound object is
included, which differs from a function that is not bound.

For 2: it's a function reference like others.  That it has access to
local (and even private) class members doesn't matter for the type.

> A method name *can* be passed around; it's cumbersome. The following
> currently works.

We try to avoid passing around function names, as this is inefficient,
it requires runtime type checking.

> IIRC, there was a comment/question about dynamically creating
> functions. In a few situations I've created tailored/optimized
> functions/lambdas out of strings.

That seems unrelated to classes.  Except that in a closure an object
might be used, referred to with "this".  That's an implementation issue.

-- 
There is a difference between "should work" and "does work",
it's called testing.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by qeatzy** [comment] 2023-05-21 11:36
> > If implemented, I hope this works as shown without needing to
> >  introduce a new type, and so remains an implementation detail.
> > 
> This applies to 1: It will be a new type, as the bound object is
> included, which differs from a function that is not bound.

In python `print(type(x.Hello), type(Hello.HelloStatic))` prints `<class 'method'> <class 'function'>`
in typescript `console.log(typeof x.Hello, typeof Hello.HelloStatic)` prints `function function`

I like @errael's idea of not introducing new type and prefer a typescript-like approach of treating method/function in same way, thus the code checking type of callback wouldn't need to change. But either way is ok, as the difference is small.

**Comment by errael** [comment] 2023-08-19 18:57
Still fails with 9.0.1754

This shows up a lot and has generated a lot of discussion. But there's an obvious/simple workaround.

**Comment by mg979** [comment] 2023-08-27 01:18
Copy-pasting from #12525 for additional context.

this works
```vim
vim9script

class Test
	this._name = ""

	def new(this._name)
	enddef

	def GetName(): string
		return this._name
	enddef
endclass

var t = Test.new("testname")
setreg('"', t.GetName())
```

this doesn't (same `E1013` error)
```vim
vim9script

class Test
	this._name = ""

	def new(this._name)
	enddef

	def GetName(): string
		return this._name
	enddef
endclass

var t = Test.new("testname")

def Setreg()
	setreg('"', t.GetName())
enddef

Setreg()
```

This works again:
```vim
vim9script

class Test
	this._name = ""

	def new(this._name)
	enddef

	def GetName(): string
		return this._name
	enddef
endclass

var t = Test.new("testname")

def Setreg()
	var n = t.GetName()
	setreg('"', n)
enddef

Setreg()
```

So it's not possible to invoke a class method in functions, directly as arguments in function calls, but it works if you assign it to a variable and then pass the variable.

Also this works:
```vim
vim9script

class Test
	this._name = ""

	def new(this._name)
	enddef

	def GetName(): string
		return this._name
	enddef
endclass

var t = Test.new("testname")

def SetReg(v: string, reg: string)
	setreg(reg, v)
enddef

def SetRegCaller()
	SetReg(t.GetName(), '"')
enddef

SetRegCaller()
```

So the problem only exists for arguments after the first, it might have to do with argument parsing.

**Comment by yegappan** [comment] 2023-08-27 05:17
I have created PR https://github.com/vim/vim/pull/12929 to support passing the result of a object/method call
as an argument.  Let me know if you see any additional issues.

**Comment by mg979** [comment] 2023-08-27 11:58
@yegappan good work!

These all seem to work fine now:
```vim
vim9script

class Obj
	this._name = 'objname'

	def GetName(): string
		return this._name
	enddef
endclass

class Test
	this._name = ""

	def new(this._name)
	enddef

	def GetName(): string
		return this._name
	enddef

	def GetObjName(o: Obj): string
		return o.GetName()
	enddef
endclass

var t = Test.new("testname")

setreg('a', t.GetName())
echom @a

def SetReg1(v: string, reg: string, r2: string)
	echom 'arg3:' r2
	setreg(reg, v)
	echom @a
enddef

def SetReg2(reg: string, v: string)
	setreg(reg, v)
	echom @a
enddef

def SetReg3(v: string)
	setreg('a', v)
	echom @a
enddef

def SetRegCaller()
	@a = ''
	SetReg1(t.GetName(), 'a', t.GetName())
	@a = ''
	SetReg2('a', t.GetName())
	@a = ''
	SetReg3(t.GetName())
	@a = ''
	SetReg2('a', t.GetObjName(Obj.new()))
enddef

SetRegCaller()
```

output:
```
testname
arg3: testname
testname
testname
testname
objname
```

**Closed as completed** 2023-08-27 17:26 UTC
Labels: bug
