### ISSUE TITLE
Vim 8.2.3550, zip plugin (v31) is not capable of showing internal files content at Mac OS

### ISSUE THREAD

**Issue by aadral** [vim/vim#9108] opened 2021-11-08 16:13 UTC
### Steps to reproduce

```bash
echo "hi" > test.txt
zip test.zip test.txt
vim test.zip
```
then try to open test.txt

### Expected behaviour

You can list the content of zip files, but you cannot see the content of any internal file. You see the empty content for any internal file.

### Operating system

Mac OS Big Sur 11.6.1

### Version of Vim

 8.2.3550

### Logs and stack traces

```shell
vim --version
    VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Oct 21 2021 10:39:53)
    macOS version - x86_64
    Included patches: 1-3550
    Compiled by Homebrew
    Huge version without GUI.  Features included (+) or not (-):
    +acl               +file_in_path      +mouse_urxvt       -tag_any_white
    +arabic            +find_in_path      +mouse_xterm       -tcl
    +autocmd           +float             +multi_byte        +termguicolors
    +autochdir         +folding           +multi_lang        +terminal
    -autoservername    -footer            -mzscheme          +terminfo
    -balloon_eval      +fork()            +netbeans_intg     +termresponse
    +balloon_eval_term +gettext           +num64             +textobjects
    -browse            -hangul_input      +packages          +textprop
    ++builtin_terms    +iconv             +path_extra        +timers
    +byte_offset       +insert_expand     +perl              +title
    +channel           +ipv6              +persistent_undo   -toolbar
    +cindent           +job               +popupwin          +user_commands
    -clientserver      +jumplist          +postscript        +vartabs
    +clipboard         +keymap            +printer           +vertsplit
    +cmdline_compl     +lambda            +profile           +virtualedit
    +cmdline_hist      +langmap           -python            +visual
    +cmdline_info      +libcall           +python3           +visualextra
    +comments          +linebreak         +quickfix          +viminfo
    +conceal           +lispindent        +reltime           +vreplace
    +cryptv            +listcmds          +rightleft         +wildignore
    +cscope            +localmap          +ruby              +wildmenu
    +cursorbind        +lua               +scrollbind        +windows
    +cursorshape       +menu              +signs             +writebackup
    +dialog_con        +mksession         +smartindent       -X11
    +diff              +modify_fname      -sodium            -xfontset
    +digraphs          +mouse             -sound             -xim
    -dnd               -mouseshape        +spell             -xpm
    -ebcdic            +mouse_dec         +startuptime       -xsmp
    +emacs_tags        -mouse_gpm         +statusline        -xterm_clipboard
    +eval              -mouse_jsbterm     -sun_workshop      -xterm_save
    +ex_extra          +mouse_netterm     +syntax
    +extra_search      +mouse_sgr         +tag_binary
    -farsi             -mouse_sysmouse    -tag_old_static
       system vimrc file: "$VIM/vimrc"
         user vimrc file: "$HOME/.vimrc"
     2nd user vimrc file: "~/.vim/vimrc"
          user exrc file: "$HOME/.exrc"
           defaults file: "$VIMRUNTIME/defaults.vim"
      fall-back for $VIM: "/usr/local/share/vim"
    Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H -DMACOS_X -DMACOS_X_DARWIN -g -O2 -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
    Linking: clang -L. -fstack-protector-strong -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl@1.1/lib -L/usr/local/opt/readline/lib -L/usr/local/lib -o vim -lm -lncurses -liconv -lintl -framework AppKit -L/usr/local/opt/lua/lib -llua5.4 -mmacosx-version-min=11.3 -fstack-protector-strong -L/usr/local/lib -L/usr/local/Cellar/perl/5.34.0/lib/perl5/5.34.0/darwin-thread-multi-2level/CORE -lperl -L/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/config-3.9-darwin -lpython3.9 -framework CoreFoundation -lruby.3.0 -L/usr/local/Cellar/ruby/3.0.2_1/lib
```

**Comment by aadral** [comment] 2021-11-08 16:14
might be useful: https://vi.stackexchange.com/questions/34924/zip-plugin-is-not-capable-of-showing-internal-files-content-after-upgrade

**Comment by chrisbra** [comment] 2021-11-08 16:54
duplicate of #8974?

**Comment by lacygoill** [comment] 2021-11-08 17:00
> duplicate of #8974?

Yes, I think so.

**Closed as completed** 2021-11-08 17:15 UTC
Labels: duplicate, runtime

**Comment by lacygoill** [comment] 2021-11-08 18:20
To the OP:  on [this page](http://www.drchip.org/astronaut/vim/), you can find a [more recent version](http://www.drchip.org/astronaut/vim/vbafiles/zip.vba.gz) of the zip plugin (`v32c` at the time of writing).  It might fix your issue.

**Comment by aadral** [comment] 2021-11-08 21:46
> To the OP: on [this page](http://www.drchip.org/astronaut/vim/), you can find a [more recent version](http://www.drchip.org/astronaut/vim/vbafiles/zip.vba.gz) of the zip plugin (`v32c` at the time of writing). It might fix your issue.

just for clarity: what is the meaning of "OP" ?

**Comment by lacygoill** [comment] 2021-11-08 21:48
> just for clarity: what is the meaning of "OP" ?

[Original Poster](https://www.urbandictionary.com/define.php?term=OP)
