### ISSUE TITLE
Error: 'warning: "_FORTIFY_SOURCE" redefined' when I attempt to enable the Perl interpretter

### ISSUE THREAD

**Issue by scottchiefbaker** [vim/vim#2068] opened 2017-09-06 18:13 UTC
Using master on Fedora 26 results in a compile time error if `--enable-perlinterp` is used. If that option is left out Vim compiles just fine. Here is an appropriate section of output from the compiliation:

```
gcc -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        -o objects/move.o move.c
gcc -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        -o objects/mbyte.o mbyte.c
gcc -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        -o objects/normal.o normal.c
gcc -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        -o objects/ops.o ops.c
gcc -c -I.  -D_REENTRANT -D_GNU_SOURCE -O2 -g  -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -fwrapv  -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64  -I/usr/lib64/perl5/CORE      -Iproto -DHAVE_CONFIG_H     -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        -o objects/option.o option.c
cc1: error: -Wformat-security ignored without -Wformat [-Werror=format-security]
<command-line>:0:0: warning: "_FORTIFY_SOURCE" redefined
<command-line>:0:0: note: this is the location of the previous definition
gcc -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        -o objects/os_unix.o os_unix.c
gcc -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        -o objects/pathdef.o auto/pathdef.c
gcc -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        -o objects/popupmnu.o popupmnu.c
gcc -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        -o objects/pty.o pty.c
gcc -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        -o objects/quickfix.o quickfix.c
gcc -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        -o objects/regexp.o regexp.c
cc1: some warnings being treated as errors
make[1]: *** [Makefile:3209: objects/option.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/home/bakers/github/vim/src'
make: *** [Makefile:29: first] Error 2
```

For reference here is my configure/make command:
```
make distclean && ./configure --prefix=/home/bakers/vim/ --enable-perlinterp --enable-python3interp && make -j3
```

**Comment by chrisbra** [comment] 2017-09-06 20:30
In the file auto/config.mk in the src directory check the definition of PERL_CFLAGS and remove the `-Wp,-D_FORTIFY_SOURCE=2` Not sure, where this comes from.

**Comment by chrisbra** [comment] 2017-09-06 20:45
perhaps we need this patch:
```patch
diff --git a/src/configure.ac b/src/configure.ac
index 918c36c1d..745e4f322 100644
--- a/src/configure.ac
+++ b/src/configure.ac
@@ -1007,7 +1007,7 @@ if test "$enable_perlinterp" = "yes" -o "$enable_perlinterp" = "dynamic"; then
       dnl Remove "-fdebug-prefix-map", it isn't supported by clang.
       perlcppflags=`$vi_cv_path_perl -Mlib=$srcdir -MExtUtils::Embed \
              -e 'ccflags;perl_inc;print"\n"' | sed -e 's/-fno[[^ ]]*//' \
-                       -e 's/-fdebug-prefix-map[[^ ]]*//g'`
+                       -e 's/-fdebug-prefix-map[[^ ]]*//g' -e 's/\(-Wp,\)\?-D_FORTIFY_SOURCE=.//g`
       dnl Remove "-lc", it breaks on FreeBSD when using "-pthread".
       perllibs=`cd $srcdir; $vi_cv_path_perl -MExtUtils::Embed -e 'ldopts' | \
                sed -e '/Warning/d' -e '/Note (probably harmless)/d' \
```

**Comment by scottchiefbaker** [comment] 2017-09-06 20:47
I don't see `FORTIFY_SOURCE` anywhere in my `auto/config.mk`.

**Comment by scottchiefbaker** [comment] 2017-09-06 21:00
I took `-Wp,-D_FORTIFY_SOURCE=2` out of my config.mk and I'm still getting a (different) compile error:

```
gcc -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        -o objects/mbyte.o mbyte.c
gcc -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        -o objects/normal.o normal.c
gcc -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        -o objects/ops.o ops.c
gcc -c -I.  -D_REENTRANT -D_GNU_SOURCE -O2 -g  -Werror=format-security  -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -fwrapv  -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64  -I/usr/lib64/perl5/CORE      -Iproto -DHAVE_CONFIG_H     -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        -o objects/option.o option.c
cc1: error: -Wformat-security ignored without -Wformat [-Werror=format-security]
gcc -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        -o objects/os_unix.o os_unix.c
creating auto/pathdef.c
gcc -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        -o objects/popupmnu.o popupmnu.c
gcc -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        -o objects/pty.o pty.c
```

**Comment by chrisbra** [comment] 2017-09-07 11:35
Does the `-Werror=format-security` also come from `PERL_CFLAGS`?

**Comment by scottchiefbaker** [comment] 2017-09-07 15:56
Looks like it:

```
PERL_CFLAGS     =  -D_REENTRANT -D_GNU_SOURCE -O2 -g  -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -fwrapv  -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64  -I/usr/lib64/perl5/CORE
```

If I remove `-Werror=format-security` and `-Wp,-D_FORTIFY_SOURCE=2` it compiles

**Comment by scottchiefbaker** [comment] 2017-09-14 16:26
Any updates on this issue?

**Comment by nuko8** [comment] 2017-09-14 19:58
FWIW, as the first half of the error message in your first post indicates, without `-Wformat`, `-Werror=format-security` won't work.  You need to specify the both on the command line simultaneously to get the latter to work properly.

As for the error message in your second post, when `-Wp` is used, the argument `-D_FORTIFY_SOURCE=2` is directly passed through to the preprocessor, bypassing the compiler driver.  This prevents the compiler driver from merging the argument into Vim's own command line options `-U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1` to compute the net result.  Also, `gcc(1)` says
> The preprocessor's direct interface is undocumented and subject to change, so whenever possible you should avoid using -Wp and let the driver handle the options instead.

So, I would say the real issue is: `perlembed` forgets to add `-Wformat` and uses `-Wp` without any good reason.  Looks like a bug of it.  I'm wondering why it passes those options to clients that way; if PERL_CFLAGS were something like
```
PERL_CFLAGS = ... -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 ...
```
instead of
```
PERL_CFLAGS = ... -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 ...
```
then Vim would compile.

N.B.  The options `-Werror=format-security` and `-Wp,-W_FORTIFY_SOURCE=2` come from
```
$ perl -MExtUtils::Embed -e 'ccflags;perl_inc;print'
```
and Vim's build system respects the return value.

**Comment by scottchiefbaker** [comment] 2017-09-15 15:28
Sorry @brammool I'm still getting a compile error:

```
gcc -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        -o objects/mbyte.o mbyte.c
gcc -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        -o objects/normal.o normal.c
gcc -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        -o objects/ops.o ops.c
gcc -c -I.  -D_REENTRANT -D_GNU_SOURCE -O2 -g  -Werror=format-security  -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -fwrapv  -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64  -I/usr/lib64/perl5/CORE      -Iproto -DHAVE_CONFIG_H     -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        -o objects/option.o option.c
cc1: error: -Wformat-security ignored without -Wformat [-Werror=format-security]
gcc -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        -o objects/os_unix.o os_unix.c
gcc -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        -o objects/pathdef.o auto/pathdef.c
gcc -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        -o objects/popupmnu.o popupmnu.c
```

**Comment by chrisbra** [comment] 2017-09-15 15:33
as nuko8 [explains](https://github.com/vim/vim/issues/2068#issuecomment-329592074) this is most likely a bug from your perl, because  you are treating warnings as errors, but at the same time you get noticed (**warned**, that you are missing the `-Wformat` switch). As said before, you might have to hand edited auto/config.mk and fix `PERL_CFLAGS` manually.

And you should probably open a bug report at your distributor, why the perl command gives you the compile flag `-Werror=format-security` without the corresponding `-Wformat`

**Comment by scottchiefbaker** [comment] 2017-09-15 15:42
I can look at filing an upstream bug report for sure. What Perl command is used to generate that line in the `config.mk`?

**Comment by chrisbra** [comment] 2017-09-15 16:05
this is defined in [configure.ac](https://github.com/vim/vim/blob/master/src/configure.ac#L1009-L1012)
use perl for $vi_cv_path_perl and src for $srcdir (assuimg you are running this from the toplevel root command) (I am actually not sure anymore, if $srcdir is actually set).

**Comment by scottchiefbaker** [comment] 2017-09-19 22:13
```
:perl -Mlib=src/ -MExtUtils::Embed -e 'ccflags;perl_inc;print"\n"'
 -D_REENTRANT -D_GNU_SOURCE -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -fwrapv -fno-strict-aliasing -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64  -I/usr/lib64/perl5/CORE
```

It is indeed missing a `-Wformat`. Is that a distro bug, or a `ExtUtils::Embed` bug?

**Comment by scottchiefbaker** [comment] 2017-09-26 20:57
It was brought to my attention that [here](https://github.com/vim/vim/blob/master/src/configure.ac#L1041) an attempt was made to remove `-W*` arguments from Perl cflags, but without a `/g` in that regexp it only removes the **first** one. I believe the intent was to remove all `-W` flags? If so we'll want to add `/g` to that regexp to strip them all.

**Comment by chrisbra** [comment] 2017-09-27 05:42
but `-Wformat` was missing even before that sed call, wasn't it?

**Comment by jplesnik** [comment] 2017-09-27 07:36
It seems that sed removes -Wall which turns on many warning flags including -Wformat

**Comment by chrisbra** [comment] 2017-09-27 07:39
so if you add the `g` flag to the mentioned sed statement, does it fix it for you?

**Comment by chrisbra** [comment] 2017-09-27 09:36
I find it confusing, that perlcppflags is changed twice. So how about the following patch?
```patch
diff --git a/src/configure.ac b/src/configure.ac
index 1183ab44b..3ae8d55a4 100644
--- a/src/configure.ac
+++ b/src/configure.ac
@@ -1006,10 +1006,12 @@ if test "$enable_perlinterp" = "yes" -o "$enable_perlinterp" = "dynamic"; then
       dnl Remove "-fno-something", it breaks using cproto.
       dnl Remove "-fdebug-prefix-map", it isn't supported by clang.
       dnl Remove "FORTIFY_SOURCE", it will be defined twice.
+      dnl Remove -pipe and -Wxxx, it confuses cproto
       perlcppflags=`$vi_cv_path_perl -Mlib=$srcdir -MExtUtils::Embed \
                -e 'ccflags;perl_inc;print"\n"' | sed -e 's/-fno[[^ ]]*//' \
                -e 's/-fdebug-prefix-map[[^ ]]*//g' \
-               -e 's/\(-Wp,\)\?-D_FORTIFY_SOURCE=.//g'`
+               -e 's/-pipe //' -e 's/-W[[^ ]]*//g' \
+               -e 's/-D_FORTIFY_SOURCE=.//g'`
       dnl Remove "-lc", it breaks on FreeBSD when using "-pthread".
       perllibs=`cd $srcdir; $vi_cv_path_perl -MExtUtils::Embed -e 'ldopts' | \
                sed -e '/Warning/d' -e '/Note (probably harmless)/d' \
@@ -1037,8 +1039,7 @@ if test "$enable_perlinterp" = "yes" -o "$enable_perlinterp" = "dynamic"; then
       LDFLAGS=$ldflags_save
       if test $perl_ok = yes; then
        if test "X$perlcppflags" != "X"; then
-         dnl remove -pipe and -Wxxx, it confuses cproto
-         PERL_CFLAGS=`echo "$perlcppflags" | sed -e 's/-pipe //' -e 's/-W[[^ ]]*//'`
+         PERL_CFLAGS=$perlcppflags
        fi
        if test "X$perlldflags" != "X"; then
          if test "X`echo \"$LDFLAGS\" | $FGREP -e \"$perlldflags\"`" = "X"; then
```

**Comment by chrisbra** [comment] 2017-09-27 09:37
make sure to run `make autoconf` after that patch.

**Comment by scottchiefbaker** [comment] 2017-09-27 15:27
```
bakers@yellow(~/github/vim)
:make autoconf
make: *** No rule to make target 'autoconf'.  Stop.
```

Oh wait... do I need to run that in the `src/` directory? Looks like the command works in there.

**Comment by scottchiefbaker** [comment] 2017-09-27 15:32
Your patch above fixes the problem, as does **just** adding `g` to the end of that original sed command.

**Comment by nuko8** [comment] 2017-09-27 16:31
What @jplesnik said seems to be opposite to the current direction.  My interpretation of it is that she rather suggested restoring `-Wall` by removing `-e 's/-W[[^ ]]*//'`,  by which the error caused by `-Wformat-security` is suppressed since `-Wall` implies `-Wformat`.   So, if `-Wall` were included in `$CPPFLAGS` from the beginning, the suggestion would lead to a correct solution.

Based on the idea, I think adding `-e 's/\(-Wformat-secutiry\)/-Wformat \1/` to the `sed` command is better than the "adding g" solution since the latter is only useful to look away all possible troubles at runtime, though i still think it's perl's responsibility, not Vim's.

**Comment by scottchiefbaker** [comment] 2017-09-27 16:32
Looking at this a little further... the error is complaining about a missing `-Wformat` command. That sed command is removing the FIRST `-W` command, which happens to be `-Wall`, which in turn triggers this error (`-Wall` includes `-Wformat`).

So two things seem appropriate here:

1. Add `g` to the sed regexp to it removes ALL of the `-W` flags
1. Don't muck around with the `-W` flags at all, which would leave `-Wall` in place

I just did a test trying #2 where I remove the `-e 's/-W[[^ ]]*//g'` sed call entirely, which leaves all of the `-W` options in place and I compile just fine now. My `PERL_CFLAGS` is now: 

`PERL_CFLAGS     =  -D_REENTRANT -D_GNU_SOURCE -O2 -g -Wall -Werror=format-security  -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -fwrapv  -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64  -I/usr/lib64/perl5/CORE`

And it works fine. I'm not sure what we were trying to solve by removing the `-W` flags, perhaps some other issue? I would be in favor of leaving `-Wall` in place if we can, it may catch something else.

**Comment by chrisbra** [comment] 2017-09-27 18:06
>  So, if -Wall were included in $CPPFLAGS from the beginning, the suggestion would lead to a correct solution.

I did it that way because of this comment in configure.ac: 
https://github.com/vim/vim/blob/b5e79ef5a9e85f5bb70eb4cc6e12cbeec2a820ca/src/configure.ac#L1040-L1041

On the other hand, this comes from commit https://github.com/vim/vim/commit/d7afed3753242ace4190f1d75 which is from 2007 so perhaps this is no problem any longer.

**Comment by scottchiefbaker** [comment] 2017-09-27 18:24
I'm fine with either solution, but I think leaving `-W` is better long term for catching other potential errors.

**Comment by brammool** [comment] 2017-09-27 19:42
Christian Brabandt wrote:

> I find it confusing, that perlcppflags is changed twice. So how about the following patch?
> ```patch
> diff --git a/src/configure.ac b/src/configure.ac
> index 1183ab44b..3ae8d55a4 100644
> --- a/src/configure.ac
> +++ b/src/configure.ac
> @@ -1006,10 +1006,12 @@ if test "$enable_perlinterp" = "yes" -o "$enable_perlinterp" = "dynamic"; then
>        dnl Remove "-fno-something", it breaks using cproto.
>        dnl Remove "-fdebug-prefix-map", it isn't supported by clang.
>        dnl Remove "FORTIFY_SOURCE", it will be defined twice.
> +      dnl Remove -pipe and -Wxxx, it confuses cproto
>        perlcppflags=`$vi_cv_path_perl -Mlib=$srcdir -MExtUtils::Embed \
>                 -e 'ccflags;perl_inc;print"\n"' | sed -e 's/-fno[[^ ]]*//' \
>                 -e 's/-fdebug-prefix-map[[^ ]]*//g' \
> -               -e 's/\(-Wp,\)\?-D_FORTIFY_SOURCE=.//g'`
> +               -e 's/-pipe //' -e 's/-W[[^ ]]*//g' \
> +               -e 's/-D_FORTIFY_SOURCE=.//g'`
>        dnl Remove "-lc", it breaks on FreeBSD when using "-pthread".
>        perllibs=`cd $srcdir; $vi_cv_path_perl -MExtUtils::Embed -e 'ldopts' | \
>                 sed -e '/Warning/d' -e '/Note (probably harmless)/d' \
> @@ -1037,8 +1039,7 @@ if test "$enable_perlinterp" = "yes" -o "$enable_perlinterp" = "dynamic"; then
>        LDFLAGS=$ldflags_save
>        if test $perl_ok = yes; then
>         if test "X$perlcppflags" != "X"; then
> -         dnl remove -pipe and -Wxxx, it confuses cproto
> -         PERL_CFLAGS=`echo "$perlcppflags" | sed -e 's/-pipe //' -e 's/-W[[^ ]]*//'`
> +         PERL_CFLAGS=$perlcppflags
>         fi
>         if test "X$perlldflags" != "X"; then
>           if test "X`echo \"$LDFLAGS\" | $FGREP -e \"$perlldflags\"`" = "X"; then
> ```

Thanks.  I think this is the best solution.  When building Vim other -W
flags will be used just like for the other files.  I see no reason to
use more -W flags when building some of the files.

The result is still tricky, for me it adds "-D_LARGEFILE_SOURCE
-D_FILE_OFFSET_BITS=64" and using those only for some of the .c files
might cause trouble.  Using the Perl flags for all files might cause
other problems.  Not sure which one is the least bad.

-- 
hundred-and-one symptoms of being an internet addict:
210. When you get a divorce, you don't care about who gets the children,
     but discuss endlessly who can use the email address.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment] 2017-09-27 20:08
closed by https://github.com/vim/vim/releases/tag/v8.0.1156

**Closed as completed by chrisbra** 2017-09-27 20:08 UTC
