### ISSUE TITLE
Line completion popup is in a wrong position

### ISSUE THREAD

**Issue by mihaicristiantanase** [vim/vim#2681] opened 2018-02-27 18:10 UTC
Use vim version:
>> VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Feb 13 2018 12:01:25)
>> macOS version
>> Included patches: 1-1500
>> Compiled by Homebrew

Use test files:
[test-file1.txt](https://github.com/vim/vim/files/1764137/test-file1.txt)
[test-file2.txt](https://github.com/vim/vim/files/1764138/test-file2.txt)
[test-vim-script.txt](https://github.com/vim/vim/files/1764142/test-vim-script.txt)

Run (in a terminal emulator):
>> vim -u NONE --noplugins -s test-vim-script.txt

Press (in VIM, to get line completion):
>> o^X^L

Expected:
>> the popup should be displayed in the correct position.

Result:
>> the popup is displayed somewhere in the left window.
<img width="600" alt="line-completion-popup" src="https://user-images.githubusercontent.com/7289591/36745838-6dc04948-1bf9-11e8-8a86-3b087a010d63.png">

**Comment by k-takata** [comment] 2018-02-28 00:04
I think this is a duplicate of #2661 and fixed by 8.0.1540.

**Comment by mihaicristiantanase** [comment] 2018-02-28 09:46
You're right, I've checked 8.0.1553 and the issue does not show up.
Thanks!

**Closed as completed** 2018-02-28 09:46 UTC
Labels: duplicate
