### ISSUE TITLE
Status line renders incorrectly when :set termguicolor

### ISSUE THREAD

**Issue by nowox** [vim/vim#1157] opened 2016-10-11 14:24 UTC
This https://github.com/vim-airline/vim-airline/issues/1244 on vim-airline seems to be a vim issue. 

The issue can be reproduced with the following: 

```
set nocompatible
filetype off
set runtimepath +=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'vim-airline/vim-airline'                        
let g:airline#extensions#tabline#enabled = 1
call vundle#end()
filetype plugin indent on 
set laststatus=2
set termguicolors
filetype plugin on
filetype indent on
syntax on
```

The problem is with the characters `>>` visible in `NORMAL >> [No Name]`. They are improperly colored  no matter the selected theme, the color of these chars is white on black.

**Comment by chrisbra** [comment] 2016-10-12 17:25
I think this is a duplicate of #993

**Closed as completed by chrisbra** 2016-10-12 17:25 UTC
