### ISSUE TITLE
Patch 8.0.0754 (commit eeac677) breaks bold colours on xterm t_Co=8

### ISSUE THREAD

**Issue by koitsu** [vim/vim#1901] opened 2017-07-31 01:13 UTC
Potentially involved commits:

https://github.com/vim/vim/commit/eeac67788677a9ea81bcab69f81b4fc22c2adc00 (8.0.0754)
https://github.com/vim/vim/commit/b41bf8e6b45a773456031954bca1bc4212cbffbe (8.0.0791)

I recent upgraded my FreeBSD 10.3 vim-lite package from 8.0.0742 to 8.0.0809 and was surprised to find that colours looked incorrect -- specifically, they were darker (i.e. bold bit no longer being set on terminal output).

FreeBSD's TERM=xterm uses t_Co=8 and has for decades.  The terminal truly only supports 8 colours, but in the terminal emulator (PuTTY), bold being set causes the colours to be brighter.  This behaviour is "ANSI-like" (where bold means "brighter colour" rather than a bolded font) and is extremely common.

I do not use t_Co=256 because the colours look weird to me ("washed out", purely an aesthetic dislike), and I do not use TERM=xterm-color (which uses t_Co=256 anyway) because not all *IX software works correctly with xterm-color.

Attached are screenshots of FreeBSD 10.3 vim-lite 8.0.0809 vs. FreeBSD 9.3 vim-lite 8.0.0134.  There are irrelevant termcap differences (I reviewed them), but visually you can see the difference I'm referring to (re: lack of bold).  FreeBSD binary package updates do not have have a native way to revert to a previous package, so I cannot roll back to 8.0.0742.

Crummy workaround, which may or not be accurate (can't tell if 0754 or 0791 is responsible):

```
if has("patch-8.0.0754") && &term =~ "xterm"
  set t_Co=16
endif
```
![with_patch](https://user-images.githubusercontent.com/8430773/28759464-8d0e87e0-7552-11e7-9dc5-cbeb0d1f4f4d.png)
![without_patch](https://user-images.githubusercontent.com/8430773/28759466-9583145e-7552-11e7-93bf-a31c7be375f0.png)

**Comment by sdt** [comment] 2017-08-01 02:15
I noticed this problem as well and bisected it to 8.0.0791 (b41bf8e6b)

Before 791:
![screen shot 2017-08-01 at 12 08 40 pm](https://user-images.githubusercontent.com/615293/28806298-8e42a284-76b2-11e7-81b3-e97b41ca3833.png)

After 791:
![screen shot 2017-08-01 at 12 07 40 pm](https://user-images.githubusercontent.com/615293/28806275-65a5efde-76b2-11e7-9b41-29dc74c8ab4a.png)

Manually setting `set t_Co=16` as per @koitsu's workaround fixes the colours 

Running iTerm2 on macos with tmux and TERM=screen

**Comment by koitsu** [comment] 2017-08-01 03:25
@sdt Thanks so much for confirming it's b41bf8e that causes the problem!

**Comment by sdt** [comment] 2017-08-01 04:20
I see the problem, but I'm not sure on what the solution might be.

In the old code, we have `i` which is the color table index, 

https://github.com/vim/vim/blob/fa228f716a4b63bf508887a49ce56bf4c07364d3/src/syntax.c#L7795

and `idx` which is an offset into `HL_TABLE`

https://github.com/vim/vim/blob/fa228f716a4b63bf508887a49ce56bf4c07364d3/src/syntax.c#L7803

In the new version, that code has been lifted out to become `lookup_color`, with `i` being renamed to `idx`. The original `idx` is clobbered.

The original `idx` could be passed as a parameter easily enough from `do_highlight`, but this may not make sense for all the new calls to `lookup_color` in `color2index`.

**Comment by nuko8** [comment] 2017-08-01 05:15
@sdt 

I can't reproduce the issue on my macOS, but following your investigation, we have
```diff
diff --git a/src/proto/syntax.pro b/src/proto/syntax.pro
index 33b8b80f5..f1efde71d 100644
--- a/src/proto/syntax.pro
+++ b/src/proto/syntax.pro
@@ -23,7 +23,7 @@ void ex_syntime(exarg_T *eap);
 char_u *get_syntime_arg(expand_T *xp, int idx);
 void init_highlight(int both, int reset);
 int load_colors(char_u *name);
-int lookup_color(int idx, int foreground);
+int lookup_color(int hl_idx, int idx, int foreground);
 void do_highlight(char_u *line, int forceit, int init);
 void free_highlight(void);
 void restore_cterm_colors(void);
diff --git a/src/syntax.c b/src/syntax.c
index e026c4400..8e8a760b0 100644
--- a/src/syntax.c
+++ b/src/syntax.c
@@ -7278,7 +7278,7 @@ static int color_numbers_8[28] = {0, 4, 2, 6,
  * color_names[].
  */
     int
-lookup_color(int idx, int foreground)
+lookup_color(int hl_idx, int idx, int foreground)
 {
     int		color = color_numbers_16[idx];
     char_u	*p;
@@ -7301,11 +7301,11 @@ lookup_color(int idx, int foreground)
 	     * colors (on some terminals, e.g. "linux") */
 	    if (color & 8)
 	    {
-		HL_TABLE()[idx].sg_cterm |= HL_BOLD;
-		HL_TABLE()[idx].sg_cterm_bold = TRUE;
+		HL_TABLE()[hl_idx].sg_cterm |= HL_BOLD;
+		HL_TABLE()[hl_idx].sg_cterm_bold = TRUE;
 	    }
 	    else
-		HL_TABLE()[idx].sg_cterm &= ~HL_BOLD;
+		HL_TABLE()[hl_idx].sg_cterm &= ~HL_BOLD;
 	}
 	color &= 7;	/* truncate to 8 colors */
     }
@@ -7857,7 +7857,7 @@ do_highlight(
 		    break;
 		}
 
-		color = lookup_color(i, key[5] == 'F');
+		color = lookup_color(idx, i, key[5] == 'F');
 	    }
 
 	    /* Add one to the argument, to avoid zero.  Zero is used for
```
Will you try this patch to see if it fixes the issue for you?  Note that the patch was made against HEAD.

**Comment by nuko8** [comment] 2017-08-01 05:56
@sdt 
> The original idx could be passed as a parameter easily enough from do_highlight, but this may not make sense for all the new calls to lookup_color in color2index.

Ah,  I missed it.  Let me take back the patch.  That's wrong.  Sorry for the noise.

**Comment by sdt** [comment] 2017-08-01 08:10
@nuko8 I tried a similar patch locally, but changing 

`if (foreground)` to `if (foreground && (hl_idx >= 0))`

and for the other calls, passing `-1` for `hl_idx`.

That fixes the issue for me, but  I have no idea what is valid for a real `hl_idx`.

**Comment by nuko8** [comment] 2017-08-01 08:18
@sdt 

Interesting.  I was just about sending the following when I got your message.  Somehow, we are working with the same idea :)

----
Since `color2index()` only needs to know the index of a given color, it is unnecessary for it to access to `HL_TABLE()`.   So, when `lookup_color()` is called from `color2index()`, there's no need to refer to the index of `HL_TABLE()` at all. 

So, using -1 as a means to skip access to `HL_TABLE()`, a possible quick fix would be [this](https://gist.github.com/nuko8/e25ef6ba0135450bce97b33ca052e0e8).

----

I'd like to hear your opinion on that.

**Comment by sdt** [comment] 2017-08-01 09:25
That's more or less what I was experimenting with.

I don't have a working build machine available until tomorrow, so I won't be able to actually test that, but it's the same logic I had. I'll test it for real in the morning.

Thanks for looking into this @nuko8 !

**Comment by nuko8** [comment] 2017-08-01 11:18
@sdt 

Thanks to you, we now know the cause of the trouble.  Also, it seems that you are familiar with the code base.  So if you get a better solution, or find anything to fix or improve in the patch, please consider sending us your own patch.   I'm wondering why you didn't do so ;-)

**Comment by brammool** [comment] 2017-08-01 16:04
Stephen Thirlwall wrote:

> I see the problem, but I'm not sure on what the solution might be.
> 
> In the old code, we have `i` which is the color table index, 
> 
> https://github.com/vim/vim/blob/fa228f716a4b63bf508887a49ce56bf4c07364d3/src/syntax.c#L7795
> 
> and `idx` which is an offset into `HL_TABLE`
> 
> https://github.com/vim/vim/blob/fa228f716a4b63bf508887a49ce56bf4c07364d3/src/syntax.c#L7803
> 
> In the new version, that code has been lifted out to become
> `lookup_color`, with `i` being renamed to `idx`. The original `idx` is
> clobbered.
> 
> The original `idx` could be passed as a parameter easily enough from
> `do_highlight`, but this may not make sense for all the new calls to
> `lookup_color` in `color2index`.

Thanks for pinpointing the problem.  The terminal code didn't use the
bold flag, that should be fixed as well.

-- 
GUARD #1:  What -- a swallow carrying a coconut?
ARTHUR:    It could grip it by the husk!
GUARD #1:  It's not a question of where he grips it!  It's a simple question
           of weight ratios!  A five ounce bird could not carry a 1 pound
           coconut.
                                  The Quest for the Holy Grail (Monty Python)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Closed as completed** 2017-08-01 16:04 UTC

**Comment by sdt** [comment] 2017-08-02 00:00
@brammool - I can confirm 12d853f works for me. Thanks!

@nuko8 - I'm actually 100% unfamiliar with the code base - I just got lucky with git bisect. It took a bit of staring at that diff to work out what had actually changed.

**Comment by koitsu** [comment] 2017-08-06 09:31
FreeBSD just pushed out vim/vim-lite 8.0.0867 packages, and I can now confirm the problem is gone with the introduction of 12d853f / 8.0.0831. Thanks everyone!
