### ISSUE TITLE
Can't build 8.0.1050 and later if system has libvterm installed

### ISSUE THREAD

**Issue by cglogic** [vim/vim#2080] opened 2017-09-12 04:58 UTC
After patch 8.0.1050 build fail with installed libvterm in system. Version 8.0.1049 builds fine.

```cc -c -I. -Iproto -DHAVE_CONFIG_H   -DLIBICONV_PLUG -I/usr/local/include  -O2 -pipe  -DLIBICONV_PLUG -fstack-protector -fno-strict-aliasing -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        -Ilibvterm/include -DINLINE=""  -DVSNPRINTF=vim_vsnprintf  -DIS_COMBINING_FUNCTION=utf_iscomposing_uint  -DWCWIDTH_FUNCTION=utf_uint2cells -o objects/term_mouse.o libvterm/src/mouse.c
libvterm/src/mouse.c:73:6: error: conflicting types for 'vterm_mouse_button'
void vterm_mouse_button(VTerm *vt, int button, int pressed, VTermModifier mod)
     ^
/usr/local/include/vterm.h:154:6: note: previous declaration is here
void vterm_mouse_button(VTerm *vt, int button, bool pressed, VTermModifier mod);
     ^
1 error generated.
*** Error code 1
```

**Comment by mattn** [comment] 2017-09-12 05:04
It seems header path conflicting. You have /usr/local/include/vterm.h and -I/usr/local/include is prefered that -Ilibvterm/include. So configure should be fixed.

**Comment by cglogic** [comment] 2017-09-12 05:35
I just do the following:
```
git clone
./configure
make
```
And have this error. This issue with my environment or vim itself?

**Comment by k-takata** [comment] 2017-09-12 05:45
How about this patch?

```diff
--- a/src/Makefile
+++ b/src/Makefile
@@ -3299,7 +3299,7 @@ objects/channel.o: channel.c
 Makefile:
 	@echo The name of the makefile MUST be "Makefile" (with capital M)!!!!
 
-CCCTERM = $(CCC) -Ilibvterm/include -DINLINE="" \
+CCCTERM = $(CCC_NF) -Ilibvterm/include $(ALL_CFLAGS) -DINLINE="" \
 	  -DVSNPRINTF=vim_vsnprintf \
 	  -DIS_COMBINING_FUNCTION=utf_iscomposing_uint \
 	  -DWCWIDTH_FUNCTION=utf_uint2cells
```

**Comment by mattn** [comment] 2017-09-12 05:53
>This issue with my environment or vim itself?

No No. This is caused by configure script of vim.

**Comment by cglogic** [comment] 2017-09-12 06:07
Thanks @k-takata! Patch fixes this issue.

**Closed as completed** 2017-09-12 21:00 UTC
