### ISSUE TITLE
Failing mapping makes command-line ignored

### ISSUE THREAD

**Issue by ZyX-I** [vim/vim#1846] opened 2017-07-17 00:13 UTC
Consider the following script:

```Shell
vim -u NONE -i NONE --cmd "cnoremap <expr> x execute('bwipeout!')[-1].'x'" -s <(echo -n $':%s/tw/tox') <(echo 'Here is two')
```

After executing it Vim ends with the following screen:

![Screen with error message and :s/tw/tox](http://img-fotki.yandex.ru/get/232875/9151298.7/0_c644f_aa84c3a8_orig.png)

Putting the fact that `x` was drawn on the error message as well aside, as you see it looks like you may continue to type text after the event, and you indeed may. Let’s type `/g` for example:

![Screen with error message and :s/tw/tox/g](http://img-fotki.yandex.ru/get/769660/9151298.7/0_c6450_da191a35_orig.png)

Now press `<CR>`. Given that I was able to still type text I would expect this command to work. But this is not the case, buffer still shows text “Here is two” and not “Here is toxo” which you would see if substitution run successfully. Command text is still saved in typed commands history and `:` register, so it may be redone easily.

Using vim-8.0.725.

**Comment by ZyX-I** [comment] 2017-07-17 01:18
Some clarification: I expect one of two possible resolutions:

1. After the error command-line is still editable and pressing `<CR>` will make command run.
2. Error cancels the input. It may still be somehow\* accessible, but still it should be obvious that current Ex command will not be run, cancelling the input is the most obvious and easiest choice.

\*  E.g. via history, but, for example, zsh holds one last command separately from history for purposes like “user typed a command starting with a space (i.e. the one not put into history with certain settings) with error, need to make it easier for the user to correct it”.

**Comment by lacygoill** [comment] 2021-02-04 21:38
Duplicate of https://github.com/vim/vim/issues/983

**Closed as completed** 2021-02-05 07:23 UTC
Labels: duplicate
