### ISSUE TITLE
Buffer tab-completion doesn't work when buffer name contains backslash

### ISSUE THREAD

**Issue by markonm** [vim/vim#2201] opened 2017-10-11 19:39 UTC
Vim: v8.0.1184 x64
Os: Windows 10 x64

Steps to reproduce
1. `mkdir test`
2. `vim --clean`
3. `:e test\foobar`
4. `:b test\fo<tab>`
5. completions are not provided

If backslash is replaced with forward slash, completions also don't show up. On linux completions are always provided when forward slash in present inside buffer name.

**Comment by idbrii** [comment] 2017-11-15 19:23
Dupe of #1274.

**Comment by chrisbra** [comment] 2017-11-16 07:09
closing then.

**Closed as completed by chrisbra** 2017-11-16 07:09 UTC
