### ISSUE TITLE
Typing <C-Insert> (Break) inputs ^\ on Cygwin build

### ISSUE THREAD

**Issue by AvianY** [vim/vim#7601] opened 2021-01-02 10:21 UTC
**Describe the bug**
as the title says

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run `vim --clean` (or `gvim --clean`, etc.)
2. Edit `filename`
3. Type 'ctrl - insert'
4. Vim inserts ^\ (in insert mode only after the next key is pressed).

**Expected behavior**
Vim inserts break. In insert mode, that should make vim return to normal mode.

**Environment (please complete the following information):**
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Mar 30 2020 21:58:19)
Included patches: 1-486
Modified by <cygwin@cygwin.com>
Compiled by <cygwin@cygwin.com>
 - OS: Windows 10; Cygwin
 - Terminal: mintty

**Additional context**
This is in relation to the other bug where Break on Cygwin doesn't interrupt a command.

**Comment by chrisbra** [comment] 2021-01-02 12:07
Looks like mintty sends quite some other keycodes than xterms modifyOther Keys. See https://github.com/mintty/mintty/wiki/CtrlSeqs

I think the best would be to disable modifyOtherKeys for mintty for the moment.

**Comment by brammool** [comment] 2021-01-02 17:46
We do accept most of these Escape sequences ending in "u", see handle_key_with_modifier() in term.c.
Can we attempt to make them work?  Last time I looked into this there appears that there are two camps
in producing these Escape sequences with modifiers.  We can try to support both.
I don't have mintty myself.

**Comment by chrisbra** [comment] 2021-01-02 18:33
I'll have a look

**Comment by chrisbra** [comment] 2021-01-02 18:35
@AvianY  can you please run `vim -u NONE -N --cmd "call ch_logfile('cygwin.log', 'w')"` then enter insert mode and press `Ctrl-Insert`, then quit and please paste the cygwin.log file afterwards. Thanks!

**Comment by AvianY** [comment] 2021-01-02 18:39
[cygwin.log](https://github.com/vim/vim/files/5760714/cygwin.log)

**Comment by chrisbra** [comment] 2021-01-02 18:49
Ah, sorry, You have only 8.2.486, but for the `ch_logfile()` to be useful, we need 8.2.1582.

**Comment by AvianY** [comment] 2021-01-02 18:51
well.... what should I do? Compile vim for cygwin myself and try again?

**Comment by chrisbra** [comment] 2021-01-02 18:54
hm, okay, try this (assuming modifyOtherKeys is enabled [check `:set t_TI` and `:set t_TE`, both shouldn't be empty]):

Enter insert mode, type `Ctrl-Shift-V` followed by `Ctrl-Insert`, note: The `Shift` is important. Show the keycode that is genearated, should be something like `^[[<num>;5u` 

I tried on my version, but apparently my laptop keyboard does not generate any key event.

**Comment by AvianY** [comment] 2021-01-02 19:35
I cannot do as you said. A soon as I press ```ctrl-shift-v```, it inserts ```<96>``` and doesn't wait for the next key.  It acts differently than in gVim, where it waits for the next key to be pressed.

**Comment by chrisbra** [comment] 2021-01-02 19:38
okay thanks, no worries.

I'll have a closer looks later. This is probably caused by the not quite compatible way of xterm modifyOtherKeys in mintty

**Comment by chrisbra** [comment] 2021-01-02 23:35
Hm, I did some tests. Is `Ctrl-Break` actually supported on Cygwin? It looks like Ctrl-Break is only defined for the windows source. 

So on Cygwin it behaves like in a Unix environment, and on my test system, `Ctrl-Break` doesn't work in xterm or the gui (on linux) and it doesn't even seem to be recognized as separate key. But on cygwin, mintty, seems to send decimal 28, which seems to be correct `^\`.

**Comment by chrisbra** [comment] 2021-01-05 08:02
I am closing this, as I think this is not a bug.

**Closed as completed by chrisbra** 2021-01-05 08:02 UTC
