### ISSUE TITLE
Unexpected position of the cursor after pressing `g^`

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#3625] opened 2018-11-19 19:59 UTC
- `vim --version`:      VIM - Vi IMproved 8.1  Included patches: 1-526
 - Operating system:     Ubuntu 16.04.5 LTS
 - Terminal emulator:    rxvt-unicode v9.22
 - Terminal multiplexer: tmux next-2.9
 - `$TERM`:              tmux-256color
 - Shell:                zsh 5.6.2-dev-1 (x86_64-pc-linux-gnu)

Consider this shell command:

    $ echo '    hello' | vim +'set cole=1 cocu=n' +'norm! $' -R -Nu NONE -

It writes 4 spaces and the word `hello` on a line, then moves the cursor at the end of the line.

If you press `g^`, the cursor moves on the `h` character, which is expected because it's the first non-whitespace on the line. But if you press `g^` again, the cursor moves on the first space on the line. I would expect the cursor not to move. If you press `l`, the cursor then moves on the `e` character, which seems to suggest that Vim considers that the cursor was still on the `h`, even though it was displayed on the first space.

The issue seems to be linked to the `'conceallevel'` and `'concealcursor'` options.
If you remove the value `n` from `'concealcursor'`, or if you give the value `0` to `'conceallevel'`, pressing `g^` twice doesn't make the cursor be visible on the first space.

**Comment by h-east** [comment] 2018-11-20 09:40
Hi,

Could you confirm with the following patch?

```patch
diff --git a/src/normal.c b/src/normal.c
index a0683b207..855ce13d3 100644
--- a/src/normal.c
+++ b/src/normal.c
@@ -8143,6 +8143,7 @@ nv_g_cmd(cmdarg_T *cap)
 	    do
 		i = gchar_cursor();
 	    while (VIM_ISWHITE(i) && oneright() == OK);
+	    curwin->w_valid &= ~VALID_VIRTCOL;
 	}
 	curwin->w_set_curswant = TRUE;
 	break;
```

--
Best regards,
Hirohito Higashi (h_east)

**Comment by lacygoill** [comment] 2018-11-20 10:06
Hello and thank you for the answer. I've just applied the patch and recompiled twice, but unfortunately it didn't seem to fix the issue (maybe I made an error though).

**Comment by chrisbra** [comment] 2018-11-20 11:06
I see the problem. After `nv_g_cmd()`, it will run into `validate_cursor()` in `main_loop`. However, since 
https://github.com/vim/vim/blob/5958f95a40a4a44bd9e7f3b7ec6554a6ef3e42ca/src/move.c#L654-L659

w_valid did not change, `curs_columns()` won't be changed.

Later, Vim runs into `update_single_line()` 
https://github.com/vim/vim/blob/5958f95a40a4a44bd9e7f3b7ec6554a6ef3e42ca/src/main.c#L1287-L1301

and from there it will finally hit where curwin->w_wcol will be reset in `win_line()`
https://github.com/vim/vim/blob/5958f95a40a4a44bd9e7f3b7ec6554a6ef3e42ca/src/screen.c#L5258-L5275

Note, it resets `wp->w_col` to `col - boguscols` and since `did_wcol` will be set to `TRUE` it won't set it again to the cursor position. That actually looks strange, that even if there is no concealing happening, the curwin->w_col will be set to zero (the first time the big loop hits this condition). I think it should also check for the cursor position, but not sure how to convert the cursor position into the screen column in the current screen line. So I cannot suggest a patch here. Also, the concealing code inside `win_line()` is extremely fragile and tends to break in subtile ways (although we have a couple of tests for that).

Now back to the first code snippet. I think @h-east patch is almost correct, it should just be `VALID_WCOL` instead of `VALID_VIRTCOL`. 

```patch
diff --git a/src/normal.c b/src/normal.c
index 9dc8aaddc..0f6f45b5e 100644
--- a/src/normal.c
+++ b/src/normal.c
@@ -8161,6 +8161,7 @@ nv_g_cmd(cmdarg_T *cap)
            do
                i = gchar_cursor();
            while (VIM_ISWHITE(i) && oneright() == OK);
+           curwin->w_valid &= ~VALID_WCOL;
        }
        curwin->w_set_curswant = TRUE;
        break;
```

**Comment by lacygoill** [comment] 2018-11-20 11:17
I can confirm that the patch fixes the issue once `VALID_VIRTCOL` is replaced with `VALID_WCOL`. Thank you very much @h-east, @chrisbra.

**Comment by h-east** [comment] 2018-11-20 12:06
> I can confirm that the patch fixes the issue once VALID_VIRTCOL is replaced with VALID_WCOL.

Hmm, Strange. My patch will also do the corrct behavior, right?

**Comment by h-east** [comment] 2018-11-20 12:17
Ah..
I confirmed Okay by the following cmd.
```
$ vim --clean +"set cocu=n cole=1" +"call setline(1, '    Hello')" +"norm! $"
g^g^
```

But, my patch behavior is not correct @lacygoill 's cmd.
```
$ echo '    hello' | vim +'set cole=1 cocu=n' +'norm! $' -R -Nu NONE -
g^g^
```

So, only @chrisbra 's patch is right:+1:
Sorry for the confusion.

**Comment by chrisbra** [comment] 2018-11-22 08:37
fixed by https://github.com/vim/vim/releases/tag/v8.1.0542 (despite the patch description about vartab feature, this patch was also included there).

**Closed as completed by chrisbra** 2018-11-22 08:37 UTC
