### ISSUE TITLE
Vim hangs when showmatch and cpoptions-m are enabled and paste a block containing parens

### ISSUE THREAD

**Issue by jorhett** [vim/vim#3146] opened 2018-07-03 16:35 UTC
Starting with simple .vimrc

```
set nocompatible " get out of vi-compatible mode
set showmatch " show matching brackets
set cpoptions=m " When a new match is created (showmatch) pause for .5
```

Copy a string with parens to your buffer. The following is sufficient for me:
```
output = dump(data, Dumper=Dumper)
```

What happens on Mac (installed via HomeBrew):

1. The string is pasted
1. The string has &lt;b0&gt; appended to the end of it
1. The editor will no longer leave input mode (escape is ignored)
1. The editor must be killed from the CLI to get out

Pretty bad, right? Nope, gets worse: If you hit CTRL-C this is repeated endlessly until you kill the editor with `kill -9`

This problem was not visible when building vim fresh from Github on a CentOS 7.4 box (plain "make" with no options) so it might be somewhere in the compile options enabled by HomeBrew.

**Comment by andymass** [comment] 2018-07-25 18:57
I was able to reproduce this but it doesn't really have to do with showmatch or cpoptions=m.  When using bracketed paste, it's going slow for some reason (e.g., pasting a big block with heavy load or the showmatch delay happens), and you press CTRL-C to cancel, you get stuck in a state where vim will not respond to key presses.  Presumably, it's waiting eternally for the bracketed paste terminator.

**Comment by chrisbra** [comment] 2018-07-25 20:38
Looks like we need a patch like this:
```patch
diff --git a/src/edit.c b/src/edit.c
index 657bd2c86..d5f0d66ef 100644
--- a/src/edit.c
+++ b/src/edit.c
@@ -9708,7 +9708,7 @@ bracketed_paste(paste_mode_T mode, int drop, garray_T *gap)
 #endif
            buf[idx++] = c;
        buf[idx] = NUL;
-       if (end != NULL && STRNCMP(buf, end, idx) == 0)
+       if ((end != NULL && STRNCMP(buf, end, idx) == 0) || got_int)
        {
            if (end[idx] == NUL)
                break; /* Found the end of paste code. */
```

While testing pasting using bracketed paste ( I usually don't use it, since my terminal does not support it), it looks like `Ctrl-C` is dropped from the input.

**Comment by chrisbra** [comment] 2018-07-26 07:33
Oh, I just checked again. Setting `:set showmatch cpo+=m` before pasting is awefully slow (try pasting evalfunc.c into a new buffer.) Plus you cannot abort pasting using `<ctrl-c>` since this will leave Vim still in bracketed paste mode.

So here is a better patch, that should correctly handle options related to paste mode.
```patch
diff --git a/src/edit.c b/src/edit.c
index 657bd2c86..b64707926 100644
--- a/src/edit.c
+++ b/src/edit.c
@@ -9692,7 +9692,7 @@ bracketed_paste(paste_mode_T mode, int drop, garray_T *gap)
        end = NULL;
     ++no_mapping;
     allow_keys = 0;
-    p_paste = TRUE;
+    set_option_value((char_u *)"paste", TRUE, NULL, 0);
     curbuf->b_p_ai = FALSE;

     for (;;)
@@ -9708,7 +9708,7 @@ bracketed_paste(paste_mode_T mode, int drop, garray_T *gap)
 #endif
            buf[idx++] = c;
        buf[idx] = NUL;
-       if (end != NULL && STRNCMP(buf, end, idx) == 0)
+       if ((end != NULL && STRNCMP(buf, end, idx) == 0) || got_int)
        {
            if (end[idx] == NUL)
                break; /* Found the end of paste code. */
@@ -9763,7 +9763,7 @@ bracketed_paste(paste_mode_T mode, int drop, garray_T *gap)

     --no_mapping;
     allow_keys = save_allow_keys;
-    p_paste = save_paste;
+    set_option_value((char_u *)"paste", save_paste, NULL, 0);
     curbuf->b_p_ai = save_ai;

     return ret_char;
```

**Comment by chrisbra** [comment] 2018-07-26 07:41
or slightly better:
```patch
diff --git a/src/edit.c b/src/edit.c
index 657bd2c86..360e83a3d 100644
--- a/src/edit.c
+++ b/src/edit.c
@@ -9692,7 +9692,7 @@ bracketed_paste(paste_mode_T mode, int drop, garray_T *gap)
        end = NULL;
     ++no_mapping;
     allow_keys = 0;
-    p_paste = TRUE;
+    set_option_value((char_u *)"paste", TRUE, NULL, 0);
     curbuf->b_p_ai = FALSE;
 
     for (;;)
@@ -9714,6 +9714,8 @@ bracketed_paste(paste_mode_T mode, int drop, garray_T *gap)
                break; /* Found the end of paste code. */
            continue;
        }
+       else if (got_int)
+           break; /* aborted pasting */
        if (!drop)
        {
            switch (mode)
@@ -9763,7 +9765,7 @@ bracketed_paste(paste_mode_T mode, int drop, garray_T *gap)
 
     --no_mapping;
     allow_keys = save_allow_keys;
-    p_paste = save_paste;
+    set_option_value((char_u *)"paste", save_paste, NULL, 0);
     curbuf->b_p_ai = save_ai;
 
     return ret_char;
```patch

**Comment by brammool** [comment] 2018-07-28 21:12
Christian wrote:

> Looks like we need a patch like this:
> ```patch
> diff --git a/src/edit.c b/src/edit.c
> index 657bd2c86..d5f0d66ef 100644
> --- a/src/edit.c
> +++ b/src/edit.c
> @@ -9708,7 +9708,7 @@ bracketed_paste(paste_mode_T mode, int drop, garray_T *gap)
>  #endif
>             buf[idx++] = c;
>         buf[idx] = NUL;
> -       if (end != NULL && STRNCMP(buf, end, idx) == 0)
> +       if ((end != NULL && STRNCMP(buf, end, idx) == 0) || got_int)
>         {
>             if (end[idx] == NUL)
>                 break; /* Found the end of paste code. */
> ```
> 
> While testing pasting using bracketed paste ( I usually don't use it,
> since my terminal does not support it), it looks like `Ctrl-C` is
> dropped from the input.

I think we should also call vgetc() directly, to avoid waiting for the
user to type a character.  In bracketed paste mode everything should be
in typeahead.

I'll make a patch and tentatively close the issue. Please re-open if you
still notice the problem.

-- 
This is the polymorph virus!  Follow these instructions carefully:
1. Send this message to everybody you know.
2. Format your harddisk.
Thank you for your cooperation in spreading the most powerful virus ever!

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Closed as completed by brammool** 2018-07-28 21:12 UTC
