### ISSUE TITLE
Line comments in dictionaries not highlighted

### ISSUE THREAD

**Issue by noscript** [vim/vim#7355] opened 2020-11-23 16:58 UTC
**Describe the bug**

A comment in between dictionary declaration is not highlighted. 

**To Reproduce**
1. Create script `~/comment_syntax.vim`:

```vim
let array = [
    "\ first entry comment
    \ 'first',
    "\ second entry comment
    \ 'second',
    \ ]
echo 'array ' . string(array)

let dict = {
    "\ first entry comment
    \ 'first': 'a',
    "\ second entry comment
    \ 'second': 'b',
    \ }
echo 'dict ' . string(dict)
```

2. Run VIM as:
 ```sh
vim -g -u NONE ~/comment_syntax.vim +'syntax on'
```

3. Comments in between lines not highlighted.

![image](https://user-images.githubusercontent.com/717109/99990449-7b42a980-2dbc-11eb-83b0-b10fa4bdc10a.png)

**Expected behavior**
All comments highlighted.

**Environment:**
 - Vim version: 8.2.2019
 - OS:  Ubuntu 20.04
 - Terminal: GUI

**Workaround**
```diff
diff --git runtime/syntax/vim.vim runtime/syntax/vim.vim
index 675c79503..98eae9c19 100644
--- runtime/syntax/vim.vim
+++ runtime/syntax/vim.vim
@@ -223,7 +223,7 @@ syn keyword vimAugroupKey contained aug[roup]

 " Operators: {{{2
 " =========
-syn cluster    vimOperGroup    contains=vimEnvvar,vimFunc,vimFuncVar,vimOper,vimOperParen,vimNumber,vimString,vimRegister,vimContinue,vim9Comment
+syn cluster    vimOperGroup    contains=vimEnvvar,vimFunc,vimFuncVar,vimOper,vimOperParen,vimNumber,vimString,vimRegister,vimContinue,vim9Comment,vimLineComment
 syn match      vimOper "\%#=1\(==\|!=\|>=\|<=\|=\~\|!\~\|>\|<\|=\)[?#]\{0,2}"  skipwhite nextgroup=vimString,vimSpecFile
 syn match      vimOper "\(\<is\|\<isnot\)[?#]\{0,2}\>"                 skipwhite nextgroup=vimString,vimSpecFile
 syn match      vimOper "||\|&&\|[-+.!]"                                skipwhite nextgroup=vimString,vimSpecFile
```

**Comment by brammool** [comment] 2020-11-23 19:53
@cecamp

**Comment by lacygoill** [comment] 2020-11-23 22:27
Duplicate of https://github.com/vim/vim/issues/6592

**Comment by k-takata** [comment] 2020-11-23 23:28
Closing then.

**Closed as completed by k-takata** 2020-11-23 23:28 UTC
Labels: duplicate, runtime
