### ISSUE TITLE
runtime/syntax/go: correct goPredefinedIdentifiers

### ISSUE THREAD

**Issue by i1v** [vim/vim#11996] opened 2023-02-14 23:35 UTC
currently `goPredefinedIdentifiers` are linked to `goBoolean`, which is in turn linked to `Boolean`:

https://github.com/vim/vim/blob/fdbd14e89207dca95549f298ee468793da852086/runtime/syntax/go.vim#L136-L140

I think this is a mistake. Identifiers are not booleans. Even in the context of highlighting, I think its a mistake as well. Vim already has two builtins for Identifiers, one for dark and light:

https://github.com/vim/vim/blob/fdbd14e89207dca95549f298ee468793da852086/runtime/syntax/syncolor.vim#L37

https://github.com/vim/vim/blob/fdbd14e89207dca95549f298ee468793da852086/runtime/syntax/syncolor.vim#L48

so perhaps improved code would look like this:

~~~vim
hi def link goPredefinedIdentifiers Identifier
~~~

**Comment by brammool** [comment] 2023-02-15 21:00
@bhcleek

**Comment by bhcleek** [comment] 2023-02-15 21:20
`goBoolean` and `Boolean` are both linked to `Constant`. `true`, `false`, `nil,` and `iota` are all constants in vim-go declared in the universe block in Go. Yes, they're identifiers, but they're constant identifiers.

The way it is now was decided long ago after input from multiple maintainers and contributors after a pull request there made it as this issue is asking for (see fatih/vim-go#1030).

This is also a duplicate of fatih/vim-go#3517.

**Comment by i1v** [comment] 2023-02-15 22:06
> `goBoolean` and `Boolean` are both linked to `Constant`.

I would say thats a mistake as well. The `true` and `false` values might be constants, but the `bool` type is not.

> The way it is now was decided long ago after input from multiple maintainers and contributors after a pull request there made it as this issue is asking for (see [fatih/vim-go#1030](https://github.com/fatih/vim-go/pull/1030)).

"thats the way its always been done" is not a good reason to keep doing something. So pointing to an link without further justification is not a good argument.

> This is also a duplicate of [fatih/vim-go#3517](https://github.com/fatih/vim-go/issues/3517).

I posted an issue upstream, but I was under the impression that was the correct action. Once that idea was countered (by you):

https://github.com/fatih/vim-go/issues/3516#issuecomment-1429157861

I posted to the correct location. If you didn't want me to do that, you could have specified that at the time of your original comment.

**Comment by brammool** [comment] 2023-02-17 22:29
> > `goBoolean` and `Boolean` are both linked to `Constant`.
> 
> I would say thats a mistake as well. The `true` and `false` values
> might be constants, but the `bool` type is not.

The help for highlight mentions "Boolean" as a kind of Constant.  "true"
and "false" are the most common names.

I don't get why you mention the bool type here.  The word "bool" is
recognized as "goType".


These lines looks strange:

    syn keyword     goPredefinedIdentifiers    nil iota

    hi def link     goPredefinedIdentifiers    goBoolean

"nil" is not a boolean.  I would think this should be:

    hi def link     goPredefinedIdentifiers    Constant

Although "iota" is not really a constant, "Keyword" is probably better.
But that's a tiny detail.

-- 
hundred-and-one symptoms of being an internet addict:
137. You decide to stay in college for an additional year or two,
     just so you can have the free Internet access.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by bhcleek** [comment] 2023-02-17 22:36
> Although "iota" is not really a constant, "Keyword" is probably better.

@brammool `iota` is a constant in Go. It comes from the `builtin` package: https://pkg.go.dev/builtin#pkg-constants. Note that it's not one of Go's keywords.

**Comment by i1v** [comment] 2023-02-17 22:38
I agree with @brammool . regardless of the resulting change, I think *some change* should be made. Regardless of some peoples confidence in this thread to the current code, I think everyone else can agree that the current code is not ideal, and that it would be simple to rectify that. Why a certain user is wholly resistant to any change on these lines, or even to admit that the code is not perfect, is beyond me.

**Comment by bhcleek** [comment] 2023-02-17 22:43
I guess I'm "a certain user." I've explained my reasons. Clearly, not everyone agrees. I do not care to keep repeating myself, but I'll do it one last time. The changes asked for here were effectively done in fatih/vim-go#1030 and then changed in fatih/vim-go#1049 to be the way they are now so that the `nil`, `iota`, `false` and `true` are all colored the same by default and users have an easy means to vary `iota` and `nil` from `false` and `true` highlights if the user wants to.

No code is perfect. I find your solution to also be imperfect, as did multiple maintainers after fatih/vim-go#1030 was merged.

**Comment by bhcleek** [comment] 2023-02-17 22:48
> The help for highlight mentions "Boolean" as a kind of Constant. 
> I would think this should be:
>    hi def link     goPredefinedIdentifiers    Constant

I can get behind that. It would preserve the current same coloring for `goBool` and `goPredefinedIdentifiers` that #1049 introduced along with the separation that #1030 introduced.

**Comment by brammool** [comment] 2023-02-18 11:31
> > Although "iota" is not really a constant, "Keyword" is probably better.
> 
> @brammool `iota` is a constant in Go. It comes from the `builtin`
> package: https://pkg.go.dev/builtin#pkg-constants. Note that it's not
> one of Go's keywords.

The value of "iota" increments every time it is used.  That is why I
would not call it a constant.  It would be OK to call it a  keyword,
identifier, reserved word, etc.

"iota" is part of the language: https://go.dev/ref/spec#Iota
It's called a "predeclared identifier" there, whatever that means.
Probably what is called "reserved words" in other languages.

But this page: https://go.dev/ref/spec#Predeclared_identifiers
says iota is a Constant, while nil is a "Zero value".  These names
appear to be personal choices of whoever wrote this.

I don't know why they made this language so confusing.

-- 
Amazing but true: If all the salmon caught in Canada in one year were laid
end to end across the Sahara Desert, the smell would be absolutely awful.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment] 2023-02-20 20:35
I have included PR #12026, which changes this.

**Closed by brammool** 2023-02-20 20:35 UTC
Labels: runtime
