### ISSUE TITLE
Switching buffers alters changelist

### ISSUE THREAD

**Issue by sosmo** [vim/vim#6196] opened 2020-06-03 21:18 UTC
**Describe the bug**
If I'm not mistaken, the changelist should be buffer-local. But when you do a bunch of changes, then switch to another buffer, the changelist position of the original buffer seems to change - it reverts back to the start. Does this happen to anybody else?

**To Reproduce**

`vim --clean`

Do:

	:set hidden<cr>
	i1<esc>     # initial content to allow :enew
	:enew<cr>   # second buffer
	:bn<cr>     # back to first buffer
	o2<esc>     # make sequential changes
	o3<esc>
	o4<esc>
	:bn<cr>     # second buffer
	ifoo<esc>   # make a change
	:bn<cr>     # first buffer
	g;          # try to move back in changelist - vim moves to the start of buffer, instead of stepping through the previous edits
	g;          # "at start of changelist"
	g,          # moves towards the end of changelist normally

**Environment (please complete the following information):**

VIM - Vi IMproved 8.1 (2018 May 18, compiled Mar 19 2020 13:12:18)
Included patches: 1-875, 878, 884, 948, 1046, 1365-1368, 1382, 1401

**Comment by lacygoill** [comment] 2020-06-03 21:28
Possible duplicate of https://github.com/vim/vim/issues/2173.

FWIW, I agree, it's a bug.  [Relevant item](https://github.com/vim/vim/blob/14681627f39421cce289345d4ec9927c10fa3b1c/runtime/doc/todo.txt#L1118-L1119) from the todo list:

> The change list index is local to a buffer, but it doesn't make sense using it
> for another buffer.  (lacygoll) Copy w_changelistidx to wininfo_S and back.

**Comment by lacygoill** [comment] 2020-06-03 21:32
As a workaround, I use [something](https://github.com/lacygoill/vim-window/blob/a20262d8eaa549471d123ef90db792847c6d4686/plugin/window.vim#L36-L41) similar to this:

    augroup preserve_pos_in_changelist | au!
        au BufWinLeave * if !s:is_special() | call s:save_change_position() | endif
        au BufWinEnter * if !s:is_special() | call s:restore_change_position() | endif
    augroup END

    fu s:is_special() abort
        return &l:pvw
          \ || &l:diff
          \ || &ft is# 'gitcommit'
          \ || &bt =~# '^\%(quickfix\|terminal\)$'
    endfu

    fu s:save_change_position() abort
        let changelist = get(getchangelist('%'), 0, [])
        let b:my_change_position = get(getchangelist('%'), 1, -1)
        if b:my_change_position == -1
            let b:my_change_position = 100
        endif
    endfu

    fu s:restore_change_position() abort
        if !exists('b:my_change_position')
            if !empty(get(getchangelist(0), 0, []))
                sil! norm! 99g,
            endif
            return
        endif
        sil! exe 'norm! 99g;'
        \ ..(b:my_change_position == 1 ? 'g,' : (b:my_change_position - 1).'g,')
    endfu

**Comment by sosmo** [comment] 2020-06-04 09:26
@lacygoill Yes it does seem like a duplicate! Anybody feel free to close this issue or leave it up. E: In fact, since Bram already noted he's accepting fix requests, I'll just close this one.

The workaround seems to pretty much fix the issue, so thanks for sharing! Of course it would be good to have it fixed on the official side too.

**Closed as completed** 2020-06-04 09:28 UTC
Labels: duplicate
