### ISSUE TITLE
completion info popup not cleaned in cmdline

### ISSUE THREAD

**Issue by Song-Tianxiang** [vim/vim#14212] opened 2024-03-16 14:52 UTC
### Steps to reproduce

1. create file
``` omni.vim
vim9script

def MyOmnifunc(findstart: number, base: string): any 
  if findstart
    return col('.')
  endif

  var match = {
    word: '1st match',
    info: "complete info popup\ncomplete info popup\ncomplete info popup\ncomplete info popup\ncomplete info popup\ncomplete info popup\ncomplete info popup\ncomplete info popup\ncomplete info popup\ncomplete info popup\ncomplete info popup\ncomplete info popup\ncomplete info popup\ncomplete info popup\ncomplete info popup\ncomplete info popup\ncomplete info popup\ncomplete info popup\ncomplete info popup\ncomplete info popup\ncomplete info popup\ncomplete info popup\ncomplete info popup\ncomplete info popup\ncomplete info popup\ncomplete info popup\ncomplete info popup\ncomplete info popup\ncomplete info popup\ncomplete info popup\ncomplete info popup\ncomplete info popup\ncomplete info popup\ncomplete info popup\ncomplete info popup\ncomplete info popup\ncomplete info popup\ncomplete info popup\ncomplete info popup\ncomplete info popup\ncomplete info popup\ncomplete info popup\ncomplete info popup\ncomplete info popup\ncomplete info popup\ncomplete info popup\ncomplete info popup\ncomplete info popup\ncomplete info popup\ncomplete info popup\ncomplete info popup\ncomplete info popup\ncomplete info popup\ncomplete info popup\ncomplete info popup\ncomplete info popup\ncomplete info popup\ncomplete info popup\ncomplete info popup\ncomplete info popup\ncomplete info popup\ncomplete info popup\n",
  }

  return {words: [ match, "2nd match", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24" ]} 
enddef

setlocal omnifunc=MyOmnifunc

setlocal completeopt=popup,menuone
setlocal completepopup=border:off

```
2. source file and use omnifunc to complete, when `<c-y>` select the first match, you will found popup info not cleaned in cmdline.(notice the downright corner of info popup)
3. 
![Kapture 2024-03-16 at 22 38 49](https://github.com/vim/vim/assets/149415622/a3b70c27-8de6-4d7a-97a3-e995d03bb595)

### Expected behaviour

completion `popup info` was cleaned on cmdline or popup info will like `popup menu` respect `cmdheight` and not cover cmdline.

It's not a big deal, but I think I'd better to report.

### Version of Vim

9.1.150

### Environment

macOS 13.6.1

**Comment by Shane-XB-Qian** [comment] 2024-03-23 11:10
not sure why you closed it, maybe it's a real problem.
// and @dpelle maybe related to https://github.com/vim/vim/issues/13955

**Comment by Song-Tianxiang** [comment] 2024-03-23 11:29
Sorry, I mistakenly thought no one was interested in this little question and I'll open it now.

**Comment by chrisbra** [comment] 2024-09-03 09:42
closing as duplicate of #15608

**Closed as not planned by chrisbra** 2024-09-03 09:42 UTC
Labels: bug
