### ISSUE TITLE
On XFCE, the gvim main window opens without having focus

### ISSUE THREAD

**Issue by cajuntechie** [vim/vim#689] opened 2016-03-14 19:45 UTC
OS:                  Xubuntu 14.04
DESKTOP:       4.10
Vim Version:   7.4

When gVim starts, the main window does not have focus and must be clicked in order to begin using it.

**Comment by nuko8** [comment] 2016-03-14 20:49
Though I'm not 100% sure, I'm afraid this is an issue on usage of the window manager.

Would you take a look at [this part of the xfce manual](http://docs.xfce.org/xfce/xfwm4/preferences#focus) and follow the instructions there?  Perhaps, after you check off the box at "New window focus", gvim will get focus.

In case it doesn't work for you, try "Activate focus stealing prevention" at [another dialog box](http://docs.xfce.org/xfce/xfwm4/wmtweaks#focus) also.

**Comment by vim-ml** [comment] 2016-03-15 00:15
On Tuesday, March 15, 2016 at 8:46:16 AM UTC+13, Anthony Papillion wrote:

> When gVim starts, the main window does not have focus and must be clicked in order to begin using it.

I struck this problem with xterm some years ago. 

https://www.kubuntuforums.net/showthread.php?57403-xterm-kde-gtk-focus-glitch&highlight=xterm

The cause was an environment variable called DESKTOP_STARTUP_ID, and the terminal programme (xterm) should unset it, according to the "Desktop Entry Specification".  I corresponded with the maintainer of xterm and he agreed that it should be unset.  Maybe the fix didn't get to XFCE by 14.04, or you are using something else.  Anyway, you could check if DESKTOP_STARTUP_ID is set, and unset it in your .profile or .bashrc.

Regards, John Little

**Comment by chrisbra** [comment] 2016-03-15 07:50
I think this is an issue of the windowmanager and not gvims fault. Closing.

**Closed as completed by chrisbra** 2016-03-15 07:50 UTC
