### ISSUE TITLE
Terminal vim flickers in tmux on VimEnter if colorscheme doesn't set Normal color group

### ISSUE THREAD

**Issue by mtglsk** [vim/vim#739] opened 2016-04-08 16:05 UTC
Simple to test, try the default colorscheme - when entering vim there is a very short flicker (some syntax clearing maybe?).

Now add the following line to vimrc:

```
hi Normal       ctermbg=16       ctermfg=15  <or some else matching terminal background>
```

Vim no longer flickers when launching. The flicker still happens outside of tmux (even with t_ti, t_te being unset). Less for example doesn't flicker.

**Comment by lacygoill** [comment] 2020-06-11 15:10
I can't reproduce on master.

I checked with:

    vim --clean ~/.vim/vimrc

In xterm and gnome-terminal.  Outside and inside tmux:

    tmux -Lx -f/dev/null
    vim --clean ~/.vim/vimrc

I can't see any flicker when Vim starts; nor afterward when scrolling the file.

Maybe something in your config triggers the issue.  Try to reproduce without config.

Read this [faq entry](https://github.com/chrisbra/vim_faq/blob/de424bd8e08bcf0e6b1e0563ee49514dfed926ae/vim_faq.txt#L1153-L1228) to find a [minimal working example](https://en.wikipedia.org/wiki/Minimal_working_example).

**Comment by chrisbra** [comment] 2020-06-11 16:48
closing then.

**Closed as completed by chrisbra** 2020-06-11 16:48 UTC
