### ISSUE TITLE
Only half of some emojis is displayed

### ISSUE THREAD

**Issue by lkintact** [vim/vim#15149] opened 2024-07-04 21:09 UTC
### Steps to reproduce

Copy these emojis into a Vim buffer: `⛷️ ⛹ 🌶`. You should see something like this:
![emojis](https://github.com/vim/vim/assets/24726299/97b81b3a-7dca-4100-b063-96e74b67bc54)
Notice that only the first halves of the emojis are displayed.

FWIW, this only happens to some emojis, most of them are displayed correctly.

### Expected behaviour

The emojis should be displayed fully.

### Version of Vim

9.1.505

### Environment

OS: Arch Linux
Terminal: UXterm
$TERM: xterm-256color
Shell: bash 5.2.26
Font used: Deja Vu Sans Mono.

**Comment by chrisbra** [comment] 2024-07-04 21:33
Duplicate of #10544?

**Comment by lkintact** [comment] 2024-07-04 23:36
> Duplicate of [#10544](https://github.com/vim/vim/issues/10544)?

I don't know, but FWIW I tried adding this line into my vimrc: `call setcellwidths([[0x80, 0x7fffffff, 2]])`, and it didn't change anything.

**Comment by zeertzjq** [comment] 2024-07-05 01:05
Is this really a Vim bug? The same seems to happen when outputting these character in XTerm using `cat`.

**Comment by habamax** [comment] 2024-07-05 03:57
I believe that is not a vim "bug", but terminal capability to draw emoji. Here it looks ok in windows terminal:

![image](https://github.com/vim/vim/assets/234774/3d9e63d1-b157-4fe6-abe0-1f54768936b4)

**Comment by chrisbra** [comment] 2024-07-05 07:50
Yeah, terminal Vim is complicated for unicode display, since this not only involves Vims unicode libraries, but also the underlying unicode libraries for the terminal and the system of course. This can lead to strange artifacts, if some of those disagree on eg the width. Closing as not a Vim bug then.

**Closed as not planned by chrisbra** 2024-07-05 07:50 UTC
Labels: bug

**Comment by lkintact** [comment] 2024-07-05 20:54
Thank you, guys, I tried another terminal - gnome-console - and it displays the emojis correctly. So it's indeed an UXTerm's issue, not Vim's.
