### ISSUE TITLE
`set background` destroys additional highlighting

### ISSUE THREAD

**Issue by GoogleCodeExporter** [vim/vim#262] opened 2015-08-18 21:08 UTC
```
What steps will reproduce the problem?
1. Use a plug-in that does highlighting but not by filetype. Ex `vim-bling` or 
`vim-css-color`
2. set background=light
3. Voila. Filetype highlighting remains, but other types of highlighting is 
destroyed

I expect that `set background` is non-obtrusive. That it only loads the 
highlighting-scheme
of choice.

I'm on:
VIM - Vi IMproved 7.4 (20
MacOS X (unix) version 10.9.5
Included patches: 1-444
Compiled by Homebrew
Huge version without GUI.

There's a great plug-in called vim-holylight that I'd like to use, but this 
`set background`-bug
is too annoying. Hope this can be resolved.
If I knew the vim-source I'd give it a shot myself.

```

Original issue reported on code.google.com by `hkj...@me.com` on 1 Oct 2014 at 6:56

**Comment by lacygoill** [comment] 2021-02-27 23:45
> I do not understand correctly what the problem is. Could you please describe
> in more detail, what you expect and what changes? I am not sure, I understand
> what you mean by "destroys" background. Please be more precise and also mention
> what colorscheme you use and perhapse provide a sample file that shows the
> behaviour. (BTW: It is always good to start from vim -u NONE -N)

I agree.  I have no clue what the bug is.  There is no minimal example.  No explicit url pointing to the plugin repositories.  No explanation of what "Filetype highlighting" and "other types of highlighting" are.  No info about the color scheme used.

According to `:h 'bg'`, when the `'background'` option is set, Vim adjusts the default color groups for the new value.  That is the groups listed at `:h highlight-groups`.  Also, the color scheme is reloaded.  Maybe the color scheme used by the OP doesn't reset the default highlight groups, which would explain why they perceive some color change when their plugin reset `'background'`.  But since the OP didn't mention which color scheme they used, and after more than 5 years they didn't find the time to answer the questions they were asked:

   > I do not understand correctly what the problem is. Could you please describe
   > in more detail, what you expect and what changes? I am not sure, I understand
   > what you mean by "destroys" background. Please be more precise and also mention
   > what colorscheme you use and perhapse provide a sample file that shows the
   > behaviour. (BTW: It is always good to start from vim -u NONE -N)

we'll probably never know.

**Comment by lacygoill** [comment] 2021-02-28 00:07
> after more than 5 years they didn't find the time to answer the questions they were asked

s/more than 5 years/more than 6 years/

At least, there are no more answers on the [original google discussion](https://groups.google.com/g/vim_dev/c/svucKZMDTlc/m/4DhgXFTZnRoJ).

**Comment by chrisbra** [comment] 2021-03-02 09:10
so let's close it down.

**Closed as completed by chrisbra** 2021-03-02 09:10 UTC
Labels: Priority-Medium, defect, auto-migrated
