### ISSUE TITLE
A serious bug making cpu load too high

### ISSUE THREAD

**Issue by 24pawa** [vim/vim#12379] opened 2023-05-11 10:04 UTC
### Steps to reproduce

I want to replace \n and \s in text file with vim. But when I execute the command in blew , the cpu load is over 80 in my virtual pc with 2 cpu & 4 memory and lead to the mariadb was restarted.

1. open the text file with vim
[binlog.test.zip](https://github.com/vim/vim/files/11450819/binlog.test.zip)

2. input the command below:

:%s/\n\|\s//g

3. execute it

### Expected behaviour

replace the \n and \s

### Version of Vim

9.0.1539

### Environment

CentOS 7.9.2009
Kernel: Linux ser232 3.10.0-1160.45.1.el7.x86_64
Terminal: Mobaxterm
Shell: Vim 9.0.1539

**Comment by chrisbra** [comment] 2023-05-11 11:22
I suppose you rather want to replace `\n` followed by any number of spaces? so:
```
:%s/\n\s\+//g
```
Else you would lose all your sql commands, because the spaces would also be lost?

**Comment by chrisbra** [comment] 2023-05-11 11:26
also, in case you want to get rid of `\n`, it is more efficient to use the `:%join` command.

**Comment by Shane-XB-Qian** [comment] 2023-05-11 12:09
1, what is `2 cpu & 4 memory` ? how that measure?
2, recently i noticed cpufreq service looks a flaw, but not sure if you had same.

**Comment by Shane-XB-Qian** [comment] 2023-05-11 12:19
3, some in vim e.g ':g//' to yank truly is slow and is a knew case,  perhaps should avoid.

// anyway, looks this is un-reproduceable as per the ticket description, more like just a 'question'.

**Comment by xvim64** [comment] 2023-05-11 12:52
vim does not handle large single-line files well.

This is especially true if you replace \n with any character other than \n in a large file. This creates a large single-line file that vim can't handle well.

To replace \n with other characters in a text file, you can write a simple Python conversion script that uses less memory and is faster than vim.

**Comment by ant0sha** [comment] 2023-05-16 21:36
```
# sorry for OT but ))))
# on any unix can be solved with sed one-liner
# 1{} block clears hold buffer /* ugly but works for me */
# every single line is appended to hold buffer with 'H'
# anchored to last line only (${} block) the 'x' to get the hold buffer to pattern space, run 's///' on it and 'p'rint it
cat binlog.test.sql  | sed -n -e '1{x;d;x}; H; ${x;s/[\n\t ]\+/ /g;p}' > logbin.test.sql
```

**Comment by chrisbra** [comment] 2023-05-17 06:23
Actually, I'd like the OP to clarify what exactly he wants to do. I don't think it was his intention to remove all whitespace, but if so, the following would be even faster:
```
 tr -d ' \t\n' < binlog.test.sql
```
But I doubt that was his intention anyway.

**Comment by chrisbra** [comment] 2023-05-30 06:45
I am closing this for missing feedback.

**Closed as completed by chrisbra** 2023-05-30 06:45 UTC
Labels: bug
