### ISSUE TITLE
256/truecolor support for :terminal?

### ISSUE THREAD

**Issue by LunarLambda** [vim/vim#3427] opened 2018-09-13 15:19 UTC
-> Should be off by default
-> Enable it with a togglable option
-> (Set t_XX codes if needed, not needed in gvim?)

It would (probably) slow down performance, hence why I'm suggesting it as an optional eyecandy feature

**Comment by andymass** [comment] 2018-09-13 20:12
Can you explain what you mean?  What aspect of 256 or truecolor doesn't already work?

**Comment by LunarLambda** [comment] 2018-09-13 20:29
The :terminal command only supports 16 colors. Vim could use capture the appropriate escape sequences (as controlled by the t_xx options) to display 256/truecolor in a gui / terminal with proper color support. As I've said, this is very much optional eyecandy.
![image](https://user-images.githubusercontent.com/38919842/45513933-51d17080-b7a4-11e8-943b-235c9ae32456.png)

**Comment by chdiza** [comment] 2018-09-13 20:37
> The :terminal command only supports 16 colors

I don't think that's true.

**Comment by LunarLambda** [comment] 2018-09-13 20:42
> 
> 
> > The :terminal command only supports 16 colors
> 
> I don't think that's true.

I don't see the helpfiles stating otherwise, and on my Windows machine both Terminal and GUI Vim (from the vim-win32-installer project, latest release) only show 16 colors (in particular, 256/truecolor codes are mapped to the 16 color palette provided by the colorscheme, as seen in the above screenshot)
Perhaps it is a Windows only issue, but I doubt that somewhat.

**Comment by andymass** [comment] 2018-09-13 20:44
Your example appears to work fine for me (both in terminal and gvim), but then I'm on linux.

![image](https://user-images.githubusercontent.com/6655373/45514454-63e6eb00-b773-11e8-90be-b72070e3e9f6.png)

**Comment by LunarLambda** [comment] 2018-09-13 20:46
Oh Bummer! I guess it's a Windows only issue then.

**Comment by chdiza** [comment] 2018-09-13 20:46
When I use `:terminal` on macOS, the resulting custom bash prompt exhibits truecolors.  If I then run `vim` inside of `vim`, the second `vim` has truecolors.

**Comment by LunarLambda** [comment] 2018-09-13 20:49
As said. Appears to be a windows only issue. Dunno if this fixable, if not this can he closed, else please rename it appropriately (And I apologise for assuming this was across all systems without testing beforehand, despite having a working Linux system.)

EDIT: Works on my Linux install.

**Comment by k-takata** [comment] 2018-09-14 02:26
> I guess it's a Windows only issue then.

Yes. Current version of Windows doesn't provide a way to capture 256 or full colors.
Next version of Windows (1810) will provide new [ConPTY API](https://blogs.msdn.microsoft.com/commandline/2018/08/02/windows-command-line-introducing-the-windows-pseudo-console-conpty/). If Vim or winpty supports the new API, 256 or full colors might be enabled. Currently @ntak is working on it.

**Comment by k-takata** [comment] 2018-09-27 01:31
Link: #3474

**Comment by k-takata** [comment] 2019-02-01 03:01
Link: #3794

**Comment by k-takata** [comment] 2019-02-04 02:47
This should be fixed in [8.1.0870](https://github.com/vim/vim/commit/aa5df7e3127dff6b7336df0903f5c569a40eb174).

**Closed as completed by k-takata** 2019-02-04 02:47 UTC
Labels: platform-windows

**Comment by k-takata** [comment] 2019-02-14 00:48
The ConPTY support was disabled by default in [8.1.0909](https://github.com/vim/vim/commit/d9ef1b8d77f304c83241f807c17ffa26c9033778), because ConPTY in Win10 1809 is considered still unstable.
To use ConPTY, set `'termwintype'` to "conpty" or remove `winpty(32/64).dll` from the `PATH`.

**Comment by DHowett** [comment] 2019-06-29 21:51
> ConPTY in Win10 1809 is considered still unstable

well, it's not considered unstable by us (Microsoft).

Should we re-enable it by default for 1903 (build number 10.0.18362.0)? It's improved quite a bit since 1809.

**Comment by k-takata** [comment] 2019-06-30 01:03
https://github.com/microsoft/terminal/issues/370 is not fixed yet.

**Comment by DHowett** [comment] 2019-06-30 01:14
That doesn’t necessarily mean it's _unstable_, just that it doesn’t work
100% as expected for 100% of inputs. It’s a different set of trade-offs:
winpty has some issues with fidelity and color reproduction and
performance, and conpty has some lingering issues with character sizing.
Does that mean winpty is unstable? Of course not!

**Comment by k-takata** [comment] 2019-06-30 14:36
The main reason why we disable conpty by default is that issue.
It is a critical problem for CJK users.

**Comment by blayz3r** [comment] 2019-10-04 19:30
This might be off topic but I notice that when I am using a python REPL Gvim only shows colors in Normal mode. 

**Insert mode:**
![Insert Mode](https://user-images.githubusercontent.com/12205650/66234445-bd41f500-e6bb-11e9-9f49-fcc644bd846d.PNG)

**Normal mode:**
![Normal Mode](https://user-images.githubusercontent.com/12205650/66234496-d9459680-e6bb-11e9-802b-c244ee4f3eee.PNG)
