### ISSUE TITLE
Fortran: two double quotes are not recognized as an empty string

### ISSUE THREAD

**Issue by ysdtkm** [vim/vim#5148] opened 2019-10-30 12:51 UTC
**Describe the bug**
In Fortran code, an empty string represented by two consecutive double quotes seems to be recognized as a beginning of a multi-line string.

**To Reproduce**
Save the following lines as `my_module.f90` and open it. The empty string assigned to `b` is wrongly recognized (see the screenshot below).
```Fortran
module my_module
  a = "a"
  b = ""
  c = "c"
end module my_module
```

**Screenshot**
![Screenshot from 2019-10-25 09-59-14](https://user-images.githubusercontent.com/35924685/67858985-daa09c80-fb5d-11e9-837f-652fb00710fe.png)

**Environment:**
 - GVim version 8.0.586
 - Windows 10
(Also reproduced with Vim 7.4 + Ubuntu 18.04 + Gnome terminal)

**Possible modification**
The following line is suspicious because the problem doesn't happen when I comment it out:
https://github.com/vim/vim/blob/3f39697b73f661d6900c7cf5430d967a129660d7/runtime/syntax/fortran.vim#L378

Although I am not familiar with vim script, here is an example patch to solve the problem:
```diff
- syn region	cIncluded	contained start=+"[^(]+ skip=+\\\\\|\\"+ end=+"+ contains=fortranLeftMargin,fortranContinueMark,fortranSerialNumber
+ syn region	cIncluded	contained start=+"[^("]+ skip=+\\\\\|\\"+ end=+"+ contains=fortranLeftMargin,fortranContinueMark,fortranSerialNumber
```

**Comment by chrisbra** [comment] 2019-10-30 12:58
Have you contacted the syntax file maintainer (see the top of the syntax script)?

**Comment by ysdtkm** [comment] 2019-10-30 13:10
Thanks, I've just sent him a link to this GitHub issue.

**Comment by lacygoill** [comment] 2020-06-22 19:11
The change you suggested here:

> Although I am not familiar with vim script, here is an example patch to solve the problem:
>
>     - syn region	cIncluded	contained start=+"[^(]+ skip=+\\\\\|\\"+ end=+"+ contains=fortranLeftMargin,fortranContinueMark,fortranSerialNumber
>     + syn region	cIncluded	contained start=+"[^("]+ skip=+\\\\\|\\"+ end=+"+ contains=fortranLeftMargin,fortranContinueMark,fortranSerialNumber

has been merged by https://github.com/vim/vim/commit/0c0734d527a132edfb4089be48486586424b3f41.

So, I guess the issue is fixed.

**Closed as completed** 2020-06-22 19:21 UTC
Labels: runtime
