### ISSUE TITLE
highlight commands don't work well with a colorscheme set

### ISSUE THREAD

**Issue by Cavig01** [vim/vim#13852] opened 2024-01-13 11:07 UTC
### Steps to reproduce

1. Make sure that there is no colorscheme set manually in config files.
2. Open file `~/.vimrc` with vim in terminal. Add these commands:
```
highlight SimpleTest ctermfg=red
match SimpleTest /\a/
```
to the end of the file.

3. Save and quit, and open the file with vim in terminal again. You can see all alphabet characters are red as expected.
4. Add this command:
```
colorscheme retrobox
```
just before the commands added in step two.

5. Save and quit, and open the file with vim in terminal again. You'll see that the alphabet characters are no longer red.
6. Type `:source ~/.vimrc<CR>`, the alphabet characters are red again.

### Expected behaviour

The alphabet characters should still be red, without sourcing it manually in command mode, because the colorscheme command is before the highlight command.

### Version of Vim

9.1

### Environment

OS: Arch (proot container in Termux)
terminal: Termux //idk?
$TERM: xterm-256color
shell: bash 5.2.21(1)

**Comment by chrisbra** [comment] 2024-01-16 16:41
I cannot reproduce with the following vimrc:
```
set nocp
set bg=dark
colorscheme retrobox
highlight SimpleTest ctermfg=red
match SimpleTest /\a/
```
and starting with `vim --clean -u vimrc vimrc`

![grafik](https://github.com/vim/vim/assets/244927/29efbed9-95bf-477b-a082-0a8f02841e82)

**Comment by habamax** [comment] 2024-01-26 03:32
can't reproduce it.

**Comment by chrisbra** [comment] 2024-01-26 07:30
no feedback, not reproducible. Closing

**Closed as not planned by chrisbra** 2024-01-26 07:30 UTC
Labels: needs feedback, bug

**Comment by Cavig01** [comment] 2024-05-01 07:12
Oh, I'm so sorry that I didin't follow up and feedback. I think I didn't emphasize that I was using Termux. Do you mind try reproduce this on Termux?

**Comment by Cavig01** [comment] 2024-05-01 07:16
@chrisbra Oh, I'm so sorry. I appologize for that I didin't follow up and feedback. I think I didn't emphasize that I was using Termux. Would you mind try reproducing this on Termux?
