### ISSUE TITLE
7.4.979 duplication file in autocomplete wildmenu

### ISSUE THREAD

**Issue by JulienPivard** [vim/vim#539] opened 2015-12-26 16:11 UTC
I started Vim start with `vim -u NONE` (to be sure it's a bug, and not caused by my config) and `set nocompatible`, `set wildmenu`

When press tab after typed `:!/` suggestion are duplicate like this :
![decoupeduplic](https://cloud.githubusercontent.com/assets/16414723/12007046/89afac3a-abf2-11e5-869e-a971ab0fa099.png)
and this :
![decoupeduplicfic](https://cloud.githubusercontent.com/assets/16414723/12007047/9ef9e2b8-abf2-11e5-87d3-b595bd1eb0a5.png)

But no probleme in insert mode with `<CTRL-X><CTRL-F>`
![duplicmenuedition](https://cloud.githubusercontent.com/assets/16414723/12007050/cf0f416e-abf2-11e5-9e63-e2db5d73ac46.png)

**Comment by vim-ml** [comment] 2015-12-26 20:06
On Sat, Dec 26, 2015 at 5:11 PM, Julien Pivard
vim-dev-github@256bit.org wrote:

> I started Vim start with vim -u NONE (to be sure it's a bug, and not caused by my config) and set nocompatible, set wildmenu
> 
> When press tab after typed :!/ suggestion are duplicate like this :
> 
> and this :
> 
> But no probleme in insert mode with <CTRL-X><CTRL-F>

I confirm the duplication. Here on Vim for Linux64, I see the
following on the wildmenu line:

:/<Tab>
bin/ boot/ dev/ etc/ home/ lib/ lib64/ lost+found/ mnt/ opt/ proc/
root/ run/ sbin/ selinux/ srv/ sys/ tmp/ usr/ var/ bin/ boot/ dev/
etc/ home/ lib/ lib64/ lost+found/ mnt/ opt/ proc/ root/ run/ sbin/
selinux/ srv/ sys/ tmp/ usr/ var/

The default 'wildmode' in 'nocompatible' mode is full.

With my usual vimrc which sets 'wildmode' to longest:full,full I see the same.

In another case I see only partial duplication:

:!sea<Tab>
seamonkey seahorse seahorse-demon seahorse-tool seahorse
seahorse-demon seahorse-tool

while in another case I even see triplication:
:!fir<Tab>
firefox firefox firefox

I think I have the explanation:

On this system, most programs live in /usr/bin for which /usr/bin/X11
is a symlink; both of these directories are in the $PATH.
SeaMonkey is installed only in /usr/local/bin which is not duplicated
in the $PATH
For Firefox I have both the Mozilla Nightly version in /usr/local/bin
and the openSUSE Leap version in /usr/bin

IOW, Vim does completion for the :! command by means of the $PATH and
if a single program name exists at several different places in the
$PATH it is listed as many times as it is found.

I think it's normal.

Best regards,
Tony.

**Comment by lifepillar** [comment] 2016-01-23 12:57
I have exactly the same problem as the OP, using Vim 7.4.1147 on OS X and Vim 7.4.1046 on Ubuntu, but _not_ with Vim 7.4.52 (on Ubuntu) or NeoVim v0.1.2-300-gee0e214. It looks like a regression to me. Completion for commands like `:edit` works as expected, but for `!` and user-defined commands duplicated entries appear.

**Comment by lifepillar** [comment] 2016-01-24 10:23
This is the commit that introduces this regression: b5971141dff0c69355fd64196fcc0d0d071d4c82.

**Comment by vim-ml** [comment] 2016-01-29 09:38
On Sa, 26 Dez 2015, Julien Pivard wrote:

> I started Vim start with `vim -u NONE` (to be sure it's a bug, and not caused by my config) and `set nocompatible`, `set wildmenu`
> 
> When press tab after typed `:!/` suggestion are duplicate like this :
> ![decoupeduplic](https://cloudgithubusercontentcom/assets/16414723/12007046/89afac3a-abf2-11e5-869e-a971ab0fa099png)
> and this :
> ![decoupeduplicfic](https://cloudgithubusercontentcom/assets/16414723/12007047/9ef9e2b8-abf2-11e5-87d3-b595bd1eb0a5png)
> 
> But no probleme in insert mode with `<CTRL-X><CTRL-F>`
> ![duplicmenuedition](https://cloudgithubusercontentcom/assets/16414723/12007050/cf0f416e-abf2-11e5-9e63-e2db5d73ac46png)

Here is a patch, including a test.

Best,

## Christian

Man spricht und dichtet viel eher von der Leerheit und Nichtigkeit des
Lebens, als man sie kennt; man spricht ungern oder nicht freudig
davon, wenn man sie kennt.
        -- Jean Paul

**Comment by vim-ml** [comment] 2016-01-29 20:09
Christian Brabandt wrote:

> On Sa, 26 Dez 2015, Julien Pivard wrote:
> 
> > I started Vim start with `vim -u NONE` (to be sure it's a bug, and not caused by my config) and `set nocompatible`, `set wildmenu`
> > 
> > When press tab after typed `:!/` suggestion are duplicate like this :
> > ![decoupeduplic](https://cloudgithubusercontentcom/assets/16414723/12007046/89afac3a-abf2-11e5-869e-a971ab0fa099png)
> > and this :
> > ![decoupeduplicfic](https://cloudgithubusercontentcom/assets/16414723/12007047/9ef9e2b8-abf2-11e5-87d3-b595bd1eb0a5png)
> > 
> > But no probleme in insert mode with `<CTRL-X><CTRL-F>`
> > ![duplicmenuedition](https://cloudgithubusercontentcom/assets/16414723/12007050/cf0f416e-abf2-11e5-9e63-e2db5d73ac46png)
> 
> Here is a patch, including a test.

Thanks!

## 

hundred-and-one symptoms of being an internet addict:
71. You wonder how people walk

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment] 2018-03-21 05:29
should be fixed with #2733

**Closed as completed** 2018-05-22 14:59 UTC
Labels: patch
