### ISSUE TITLE
Incorrect display of non-latin characters in the names of files inside ZIP archives

### ISSUE THREAD

**Issue by lkintact** [vim/vim#15741] opened 2024-09-25 00:47 UTC
### Steps to reproduce

Execute `gvim.exe arc.zip` ([arc.zip](https://github.com/user-attachments/files/17122565/arc.zip)). gVim opens the archive and lists its contents, the only file, `файл file.txt`, which is shown as `д ©« file.txt`. Pressing <kbd>Enter</kbd> on the file opens an empty buffer.

### Expected behaviour

gVim should show the file as `файл file.txt` and open it on pressing <kbd>Enter</kbd>.

### Version of Vim

9.1.740

### Environment

OS: Windows 10 Home
Terminal: GUI

**Comment by k-takata** [comment] 2024-09-25 02:19
It looks like the file name is encoded in cp866:
```
$ xxd arc.zip
00000000: 504b 0304 0a00 0000 0000 a81c 3959 e44e  PK..........9Y.N
00000010: aa0f 0600 0000 0600 0000 0d00 1a00 e4a0  ................
00000020: a9ab 2066 696c 652e 7478 7475 7016 0001  .. file.txtup...
```
If the byte array `e4 a0 a9 ab` is decoded as cp1251, it is shown as `д ©«`.

It seems that unzip 6.00 has options to specify the encoding:
```
$ unzip
UnZip 6.00 of 20 April 2009, by Info-ZIP.  Maintained by C. Spieler.  Send
    ...
  -O CHARSET  specify a character encoding for DOS, Windows and OS/2 archives
  -I CHARSET  specify a character encoding for UNIX and other archives
```

**Comment by chrisbra** [comment] 2024-09-25 11:35
And the issue is we should try to detect the used encoding inside a zip file?  I don't even understand, why one needs to different parameters to specify the file-encoding, depending on the system?

**Comment by k-takata** [comment] 2024-09-25 12:34
Historically, the file name in a zip file was encoded in the current code page. Nowadays, some tools use UTF-8, but some other tools still use the current code page. So, 

> And the issue is we should try to detect the used encoding inside a zip file?

Yes.

> why one needs to different parameters to specify the file-encoding, depending on the system?

I don't understand why `-O` and `-I` are needed.

**Comment by chrisbra** [comment] 2024-09-29 15:53
It works on Linux. On Windows, it seems to use the OEM codepage. In addition, neither my Linux nor Windows unzip does not seem to know the `-I` or `-O` argument switches. 

For Windows: you can also check in a terminal on Windows (cmd.com) and see what `unzip -l` shows. For me it showes garbled encoding as well. 

So it seems there is nothing to fix here for Vim. Let's close it then.

**Closed as not planned by chrisbra** 2024-09-29 15:53 UTC
Labels: runtime, bug

**Comment by k-takata** [comment] 2024-10-01 02:18
FYI, the unzip command coming with Cygwin has the `-I` and `-O` options. (I wasn't aware that this was a Cygwin-specific feature.)
