### ISSUE TITLE
Tab size depends on window width with "above" virtual text

### ISSUE THREAD

**Issue by zeertzjq** [vim/vim#12600] opened 2023-06-26 08:46 UTC
### Steps to reproduce

1. Run `vim --clean`
2. Source the following file:
```vim
set noequalalways
50vnew
28vsplit
call setline(1, "foo\tbar")
call prop_type_add('theprop', #{highlight: 'Special'})
call prop_add(1, 0, {'type': 'theprop', 'text': '12345', 'text_align': 'above'})
```
3. Tab size differs in the first and the second vsplit

### Expected behaviour

Tab size is the same in the first and the second vsplit

### Version of Vim

9.0.1628

### Environment

Operating system: Arch Linux
Terminal: kitty
Value of $TERM: xterm-kitty
Shell: fish

**Comment by berggeist** [comment] 2023-06-28 17:32
See also / possibly duplicate of #12232 
Only / always the first tab within a line is affected.

**Closed as completed** 2023-06-28 22:14 UTC
Labels: duplicate, bug
