### ISSUE TITLE
Suggestions for the Windows installer

### ISSUE THREAD

**Issue by scootergrisen** [vim/vim#3149] opened 2018-07-03 19:30 UTC
During gVim 8.1 installation on Windows 7 i get command prompt dialogs popping up quickly and closing so its like a flash when the install starts and dialogs that stays in the back of the install/uninstall window.

I would prefer if these dialogs could be avoiding.

Maybe use an argument like --quiet i think some programs use something like that to run commands without having dialogs popping up.

Also during uninstall i get 3 questions about do i want to delete this and that.
I suggest to have a check box in the uninstall window like "keep/save/delete user settings" as seen in other software so the user can make the choce before clicking the uninstall button.
And then when the user clicks the uninstall button the program just gets uninstalled without all kinds dialogs popping up and having to answer questions.

**Comment by k-takata** [comment] 2018-07-04 09:45
Related: #279, #751, etc.

See also the todo.txt:
https://github.com/vim/vim/blob/f0447e89a52885630947510f2d1b55f665a1a20e/runtime/doc/todo.txt#L203-L214

**Comment by chrisbra** [comment] 2018-07-13 21:22
closing as duplicate of #751

**Closed as completed by chrisbra** 2018-07-13 21:22 UTC
Labels: platform-windows, installer
