### ISSUE TITLE
vim.org is down

### ISSUE THREAD

**Issue by tobireif** [vim/vim#916] opened 2016-07-12 19:46 UTC
Chrome says "This site can’t be reached" "The connection was reset."

**Comment by allonhadaya** [comment] 2016-07-12 20:10
dig reveals no A record. Perhaps ns.42.org is misconfigured at the moment?

``````
> dig -t ANY vim.org.

; <<>> DiG 9.9.5-3ubuntu0.8-Ubuntu <<>> -t ANY vim.org.
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 4381
;; flags: qr rd ra; QUERY: 1, ANSWER: 5, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;vim.org.            IN    ANY

;; ANSWER SECTION:
vim.org.        21599    IN    SOA    ns.42.org. sec.42.org. 2016061000 28800 3600 864000 57600
vim.org.        21599    IN    NS    ns.42.org.
vim.org.        21599    IN    NS    ns2.42.org.
vim.org.        21599    IN    NS    ns6.gandi.net.
vim.org.        21599    IN    MX    20 jail.42.org.

;; Query time: 123 msec
;; SERVER: 127.0.1.1#53(127.0.1.1)
;; WHEN: Tue Jul 12 15:58:51 EDT 2016
;; MSG SIZE  rcvd: 162```
``````

**Comment by brammool** [comment] 2016-07-12 21:15
> dig reveals no A record. Perhaps ns.42.org is misconfigured at the moment?

The problem is with SourceForge, vim.sf.net has the same problem.
Shell service is also down.

## 

Facepalm statement #5: "Petrol getting more expensive?  Not for me, I'm always
tanking for 20 dollars"

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by vim-ml** [comment] 2016-07-12 22:08
On Tue, Jul 12, 2016 at 11:15 PM, Bram Moolenaar
vim-dev-github@256bit.org wrote:

> > dig reveals no A record. Perhaps ns.42.org is misconfigured at the moment?
> 
> The problem is with SourceForge, vim.sf.net has the same problem.
> Shell service is also down.
> 
> ## 
> 
> Facepalm statement #5: "Petrol getting more expensive? Not for me, I'm always
> tanking for 20 dollars"
> 
> /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net \\
> /// sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
> \\ an exciting new programming language -- http://www.Zimbu.org ///
> \\ help me help AIDS victims -- http://ICCF-Holland.org ///

At the moment, and from here (Belgacom-Skynet-Proximus in Brussels,
Belgium), www.vim.org resolves to 216.34.181.97, which resolves back
to vhost.sourceforge.net

Unless the problem reappears, I think we can resolve the issue as FIXED.

Best regards,
Tony.

**Comment by allonhadaya** [comment] 2016-07-13 03:58
Ah! **www.**vim.org. is resolving to 216.34.181.97 here in NYC too.

Looks like the webserver is down (maybe a firewall or a dead process... who knows):

```
> curl -v http://www.vim.org/
*   Trying 216.34.181.97...
* Connected to www.vim.org (216.34.181.97) port 80 (#0)
> GET / HTTP/1.1
> Host: www.vim.org
> User-Agent: curl/7.47.0
> Accept: */*
> 
* Recv failure: Connection reset by peer
* Closing connection 0
curl: (56) Recv failure: Connection reset by peer
```

P.S. vim.org. still doesn't seem to resolve anywhere which may be okay.

**Comment by tobireif** [comment] 2016-07-13 08:17
vim.org is still down, after 12 hours or more. The host seems quite unreliable. Perhaps the content of the site could be moved to a more reliable host?

**Comment by brammool** [comment] 2016-07-13 10:39
Tobi Reif wrote:

> vim.org is still down, after 12 hours or more. The host seems quite
> unreliable. Perhaps the content of the site could be moved to a more
> reliable host?

Yes, SourceForge appears to be going down hill again.  There was hope
with the last takeover, but in vain.

## 

Facepalm statement #7: "Last week I almost got pregnant!"

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by tobireif** [comment] 2016-07-13 10:43
Finding a great hosting company is not easy, but it seems any popular & decent option would be much better than SourceForge.

**Comment by vim-ml** [comment] 2016-07-13 15:04
On Wednesday, July 13, 2016 at 5:39:28 AM UTC-5, Bram Moolenaar wrote:

> Tobi Reif wrote:
> 
> > vim.org is still down, after 12 hours or more. The host seems quite
> > 
> > unreliable. Perhaps the content of the site could be moved to a more
> > 
> > reliable host?
> 
> Yes, SourceForge appears to be going down hill again.  There was hope
> 
> with the last takeover, but in vain.

Well, at the moment pretty much all of SourceForge is down. The only thing I can access is their front page. So it's not too surprising the vim.org page they host is also down.

**Comment by tobireif** [comment] 2016-07-13 15:19
> Well, at the moment pretty much all of SourceForge is down. The only thing I can access is their
> front page. So it's not too surprising the vim.org page they host is also down.

vim.org is down since at least 20 hours. The fact that SourceForge itself is down as well doesn't help in any way :|

I'd sure start looking for a new host.

**Comment by brammool** [comment] 2016-07-13 18:33
It's back up.

**Closed as completed by brammool** 2016-07-13 18:33 UTC

**Comment by tobireif** [comment] 2016-07-14 07:43
Please reopen. The site is down as of July 14 09:44 Berlin time.

![screenshot](https://cloud.githubusercontent.com/assets/80411/16831839/725bca2a-49a7-11e6-97c8-57135e0b6dd5.png)

**Comment by tobireif** [comment] 2016-07-14 07:48
Now it works.

**Comment by SteveGZr** [comment] 2018-01-19 12:16
It's down again.

**Comment by tobireif** [comment] 2018-01-19 12:26
Yep, it's down.
