### ISSUE TITLE
Ctrl-A decrements numbers if 'octal' is removed from nrformats

### ISSUE THREAD

**Issue by catlee** [vim/vim#787] opened 2016-05-02 17:45 UTC
To reproduce:
:set nrformats-=octal

Using the text '1-2-3' as a sample. With the cursor over '1', Ctrl-A increments as expected. With the cursor over '2', Ctrl-A decrements, as with '3'.

**Comment by vim-ml** [comment] 2016-05-02 17:51
2016-05-02 20:45 GMT+03:00 Chris AtLee vim-dev-github@256bit.org:

> To reproduce:
> :set nrformats-=octal
> 
> Using the text '1-2-3' as a sample. With the cursor over '1', Ctrl-A
> increments as expected. With the cursor over '2', Ctrl-A decrements, as
> with '3'.

Octal is irrelevant, it does the same thing with or without it. It is also
not a bug, `(-2) + 1` is indeed `-1`.​ It does increment, just it does
increment a negative number.

**Comment by catlee** [comment] 2016-05-02 17:56
Ok, I see why I was confused then. The string I was actually testing was more like this:
1-06

I wanted to increment it to 1-07, then 1-08. However, because of the leading 0, vim treats it as octal and goes from 1-06 to 1-07 to 1-010. So I thought by removing octal from nrformats I could stop it treating these strings as octal.

**Comment by vim-ml** [comment] 2016-05-02 18:03
2016-05-02 20:56 GMT+03:00 Chris AtLee vim-dev-github@256bit.org:

> Ok, I see why I was confused then. The string I was actually testing was
> more like this:
> 1-06
> 
> I wanted to increment it to 1-07, then 1-08. However, because of the
> leading 0, vim treats it as octal and goes from 1-06 to 1-07 to 1-010. So I
> thought by removing octal from nrformats I could stop it treating these
> strings as octal.

​For some reason Vim accepts only decimal negative numbers. I do not know
why it was chosen to ignore minus sign near octal, hexadecimal and binary
numbers, but it is also intentional.​

**Comment by chrisbra** [comment] 2016-05-02 19:24
In recent Vim versions (high 7.4 patchlevel) you can alternatively visually select the interesting part and increment it then (so you can make vim ignore the leading '-')

I am closing however. If you have a usage question, please ask on vim-use ml. Thanks.

**Closed as completed by chrisbra** 2016-05-02 19:24 UTC

**Comment by vim-ml** [comment] 2016-10-19 17:14
Hello, 
I have to  show you  something  that I  can't understand, can you  tell  me what's that? Take a  look here  <http://perfect.datasciencetoolkit.org/e4jcwx>
Warmest, paul

**Comment by vim-ml** [comment] 2016-10-19 17:21
Dear friend! 

Look  at that stuff, I  like it so  much, I guess you're  gonna  like it too. Look at it  <http://stay.robertgreim.com/e4opik>

Looking forward, paul
