### ISSUE TITLE
characterwise ranges

### ISSUE THREAD

**Issue by teto** [vim/vim#6004] opened 2020-04-27 22:12 UTC
I would like to be able to specify columns in ranges to be able to create inline folds. One issue I have is in `put_folds` to create the view (to save/restore folds), I can't specify the columns for folds

It is already listed in the todo.txt
```
7   Substitute in a block of text.  Use {line}.{column} notation in an Ex
    range, e.g.: ":1.3,$.5s" means to substitute from line 1 column 3 to the
    last line column 5.
```
but I thought I would nudge here to show some interest.

**Comment by chrisbra** [comment] 2024-12-25 10:04
duplicate of #3292 so closing.

**Closed as not planned by chrisbra** 2024-12-25 10:04 UTC
Labels: enhancement
