### ISSUE TITLE
gvim user unable to input underscore "_" character in plugin ctrl-p's input prompt

### ISSUE THREAD

**Issue by kting28** [vim/vim#6243] opened 2020-06-11 21:39 UTC
**Describe the bug**
In the gvim 8.2, somewhere between patch 567 and patch 775+, something changed that broke ctrl-p's input prompt. User can type any character but underscore "_" somehow is ignored. The last known good one I tried is patch 566.

**To Reproduce**
Detailed steps to reproduce the behavior:
0. install ctrl-p 
1. Run `gvim` from patch `775+`
2. type ctrl + p 
3. Type any string of characters including underscore
4. underscore not echo'ed back

**Expected behavior**
All characters should be echo'ed back on the input line. vim in console mode has no such issue. All versions <= patch 566 are ok.

**Screenshots**
![image](https://user-images.githubusercontent.com/24449116/84441853-5cc36a00-abf1-11ea-88e8-c34444895ec2.png)
Here the underscore key moves the cursor up on the "==NO ENTRIES==" line

**Environment (please complete the following information):**
```
Included patches: 1-775
Huge version with GTK2 GUI.  Features 
```
 Ubuntu 16.04 

**Additional context**
Reported also here 
https://github.com/ctrlpvim/ctrlp.vim/issues/545

**Comment by lacygoill** [comment] 2020-06-12 03:17
I can't reproduce on Ubuntu 16.04 with GTK2 (`8.2.960`).

I tried like this:

    vim -Nu NORC -g --cmd 'set rtp^=/path/to/ctrlp.vim'
    " press:  C-p _
    " result: the underscore is correctly inserted on the plugin's prompt

I guess something else is needed to reproduce?  Maybe the plugin needs to be configured in a certain way?

**Comment by kting28** [comment] 2020-06-12 04:39
Thanks for the response, I tried the same command above and can still reproduce the problem.
are you using latest from "https://github.com/ctrlpvim/ctrlp.vim"  ? 
Let me try 960 first. I think the other report on this is on 940.

**Comment by lacygoill** [comment] 2020-06-12 04:47
Yes, I just cloned the plugin with this command in a temporary directory:

    $ git clone https://github.com/ctrlpvim/ctrlp.vim

Then I added the path to the plugin in my runtimepath.
The plugin works, because when I press `C-p`, the prompt is displayed.

![gif](https://user-images.githubusercontent.com/8505073/84465899-6e038980-ac78-11ea-804f-d3e49440a95e.gif)

**Comment by kting28** [comment] 2020-06-12 05:25
Just tried 960, no dice, same result with the command above. What I do notice this is that the issue is not just underscore. Basically somehow all chars like $ ^ are treated like the normal mode - i.e. if I type something in the input line and type "up arrow" to the result list, $ moves the cursor to the end and ^ to the beginning. 
Anyway, since you can't reproduce I will just wait to see if more people report this. Thanks again for your time.

**Comment by chrisbra** [comment] 2020-06-12 07:35
That was the gui version? Which one? Can you bisect and find the commit that caused this?

**Comment by lacygoill** [comment] 2020-06-12 08:03
FWIW, here are all the commits whose message contains "GUI", inside the range mentioned in the OP (i.e. from 567 up to 775):

   - [8.2.0622](https://github.com/vim/vim/releases/tag/v8.2.0622)  Haiku: GUI does not compile
   - [8.2.0630](https://github.com/vim/vim/releases/tag/v8.2.0630)  "make tags" does not cover Haiku GUI file
   - [8.2.0646](https://github.com/vim/vim/releases/tag/v8.2.0646)  t_Co uses the value of $COLORS in the GUI
   - [8.2.0763](https://github.com/vim/vim/releases/tag/v8.2.0763)  GUI test fails without the terminal feature
   - [8.2.0765](https://github.com/vim/vim/releases/tag/v8.2.0765)  In the GUI can't use all the modifiers.
   - [8.2.0770](https://github.com/vim/vim/releases/tag/v8.2.0770)  cannot map CTRL-B when using the GUI

If I could reproduce, the first commit I would check is [8.2.0765](https://github.com/vim/vim/releases/tag/v8.2.0765).

**Comment by mgedmin** [comment] 2020-06-12 09:31
I can reproduce with 8.2.957, GTK3 GUI, on Ubuntu 20.04 LTS. ctrlp.vim version 1.79.

**Comment by mgedmin** [comment] 2020-06-12 09:44
git bisect tells me fd615a3c901f59abddca27c6a09940be552c0f4d (7.0.0765) is the 1st bad commit.

It's probably relevant that `_`, `^` and `$` require me to hold down Shift.

(A few commits are so bad I can't launch ctrlp with Ctrl+P, I have to use :CtrlP.  Then Ctrl+P starts working, but `_` doesn't.)

**Comment by lacygoill** [comment] 2020-06-20 12:53
For those of you who can reproduce, can you check whether https://github.com/vim/vim/commit/ef6746f637adbdb6860b4fa0266c43c49fa498bc helped in any way?

**Comment by mgedmin** [comment] 2020-06-22 11:46
I haven't checked 8.2.1019 specifically, but the current git master (8.2.1034) works fine: I can enter `_` and `^` into the ctrlp.vim plugin after launching the GUI with `vim -g`.

**Comment by lacygoill** [comment] 2020-06-22 11:49
The only commits whose message contains "GUI" after 8.2.0960 are:

- [8.2.1019](https://github.com/vim/vim/releases/tag/v8.2.1019)  mapping &lt;M-S-a> does not work in the GUI
- [8.2.1020](https://github.com/vim/vim/releases/tag/v8.2.1020)  popupwin test fails in the GUI
- [8.2.1027](https://github.com/vim/vim/releases/tag/v8.2.1027)  GUI: multi-byte characters do not work in a terminal

So, if the issue is fixed, it's probably due to one of these.

**Comment by chrisbra** [comment] 2020-06-22 11:50
closing then.

**Closed as completed by chrisbra** 2020-06-22 11:50 UTC

**Comment by sanjaypatelic** [comment] 2020-07-30 18:28
I noticed that the issue can be fixed by setting g:ctrlp_key_loop=1 to enable multi byte characters.
However, it will take away g:ctrlp_lazy_update from you!!
