### ISSUE TITLE
:echo works incorrectly in gVim

### ISSUE THREAD

**Issue by lkintact** [vim/vim#14860] opened 2024-05-27 12:13 UTC
### Steps to reproduce

1. Create a file `vimrctest` with the theese contents:
```vim
echo "in vimrctest 1"
echo "in vimrctest 2"

``` 
2. Run `gvim.exe -u vimrctest`. A small window pops up showing this text:
```
in vimrctest
1
```

### Expected behaviour

The window should display this:
```
in vimrctest 1
in vimrctest 2
```

### Version of Vim

9.1.443

### Environment

OS: Windows 10 Home
Terminal: GUI

**Comment by chrisbra** [comment] 2024-05-27 13:36
echo during startup may not work, especially when starting up the GUI. You shouldn't rely on that.

**Comment by Jajauma** [comment] 2024-06-01 09:36
The call chain ends at `gui_mch_dialog()` with the correct text and I see no reason why this would not work. The `gui_mch_dialog()` function contains a few screenful of calculations of element sizes and positions and there is a possibility that the text is simply displayed incorrectly.

https://github.com/vim/vim/blob/bad9577b9ae7a6ab61ec636aaa1ed7d446ef5db9/src/gui_w32.c#L7185

![Screenshot 2024-06-01 122505](https://github.com/vim/vim/assets/11892063/777695f9-e9ab-4bca-9fed-4a7b7a54a3b8)

**Comment by chrisbra** [comment] 2024-06-01 19:07
I just checked it and I also cannot reproduce this.

**Comment by chrisbra** [comment] 2024-06-13 10:41
let's close it then.

**Closed as not planned by chrisbra** 2024-06-13 10:41 UTC
Labels: bug
