### ISSUE TITLE
Searching in visual block does not permit regular expressions

### ISSUE THREAD

**Issue by yashamon** [vim/vim#11685] opened 2022-12-09 22:23 UTC
### Steps to reproduce

write foo with f as first character in line.
visually highlight foo
starting in normal mode feed keys
:/\%V^f\%V<cr>

no match found. 

### Expected behaviour

the first character f should be found. I haven't gotten any regular expressions to work. 

If this is a feature how do I turn it off?

The same thing happens in neovim nightly. But if this is a bug it better be fixed in Vim first. 

### Version of Vim

8.2.2824

### Environment

Windows 
Windows Terminal

**Comment by yashamon** [comment] 2022-12-12 17:28
Sorry I forgot to write \%. I tested what you wrote and it works. But if you try a different regular expression then no.
For example suppose I am looking for a forward slash '/' in 
"foo/bar"
I am guessing it should be /\%V\/\%V this gives no match. Maybe something is wrong with my execution. I am visually highlighting the whole string then executing  /\%V\/\%V.

Incidentally, visual-select-multi plugin does this without issues. At the moment it is my workaround. But it is a big complicated plugin.

**Comment by chrisbra** [comment] 2022-12-12 19:30
Please provide a reproducible example, starting with `vim --clean`. It works for me using `/\%V\/\%V` if I have selected the whole line. Note, that if you end your visual selection at the `/`, then the following `\%V` won't match anymore, because it asserts a visual selection at the character after your `/`.

**Comment by chrisbra** [comment] 2022-12-12 20:09
Please provide exact reproduction steps. You talked previously about matching foo/bar now you are talking about // Thanks Am 12.12.2022 um 21:06 schrieb yashamon ***@***.***>:﻿
I just tried again, in vim --clean with that example the matched // will
not be highlighted, and the cursor does not move to the match, but it can
be reached via n operator. Is this what you experience? In that case it is
just a visual indication issue not the search issue.

**Comment by yashamon** [comment] 2022-12-12 20:29
I edited my comment. I am searching for  the character '/' in the visually selected string "foo/bar".

**Comment by yashamon** [comment] 2022-12-13 17:13
Oh sorry, I forgot to set hls after vim --clean.
This fixes one problem. However, the cursor still does not move to the
match. Instead it appears to move to the start of visual selection. The n
operator works however.

**Comment by chrisbra** [comment] 2022-12-13 17:17
I cannot reproduce. From my command given above, the cursor is moved exactly to the beginning of the match after the `/` command. So please give reproducible examples what is not working.

**Comment by chrisbra** [comment] 2022-12-15 12:35
I am closing this as un-reproducible.

**Closed as completed by chrisbra** 2022-12-15 12:35 UTC
Labels: bug

**Comment by yashamon** [comment] 2022-12-15 14:39
I don't know how to reproduce via a direct command -c.
But have you tried it after opening vim? Visually select a line containing
f search for  'f'  using :/\\%Vf\\%V the cursor does not jump to f.

**Comment by chrisbra** [comment] 2022-12-15 15:59
`:/\\%Vf\\%V` the cursor does not jump to f.

You are using an ex-command here. That will place you on a line that matches, with the cursor on the first column. This is not the same as using the normal mode command `/`.

I suggest, if you have usage questions, please check out the vim_use mailing list or head over to [vi.stackexchange.com](https://vi.stackexchange.com)

**Comment by yashamon** [comment] 2022-12-15 19:45
You are right, I was using the ex command only because it can be auto
completed. I had no idea the ex version of the command would behave
differently. (And why?)

**Comment by chrisbra** [comment] 2022-12-16 08:14
> You are right, I was using the ex command only because it can be auto
completed. I had no idea the ex version of the command would behave
differently. (And why?)

One more time: There is a difference between the normal search command (`/`) and your used ex (range) command. That is basically 
a way to specify on which lines to operate. Ex commands are always line-wise. So you can do things like:

```
:/searchpattern/,$d
``` 
to delete everything from the first line (after your cursor position) matching your search-pattern until the end of the file.
That's how basic vi and ex and ed and sed also works. So this is to be expected by a vi compatible editor.

Please, if you have questions on how certain things work, please ask your questions on the mentioned communities. This is a bug tracker here. We cannot provide individual support here.

Thanks.

**Comment by yashamon** [comment] 2022-12-16 16:54
I wasn't asking for additional support, I just said I was surprised about
the difference in functionality. Since ex commands can be auto-completed it
makes sense that any normal mode command sequence should have an exact ex
counterpart. (I guess it can be achieved with additional flags. But I don't
want to research now, since plugins  do what I need.)

Thank you for help!
