### ISSUE TITLE
nnoremap with arrow keys do not work like previous in CUI since v8.2.4503 if you have other <esc> mappings

### ISSUE THREAD

**Issue by thinca** [vim/vim#9903] opened 2022-03-07 04:06 UTC
### Steps to reproduce

This can reproduce after [Vim v8.2.4504](https://github.com/vim/vim/commit/196c3850dbe95247f7aa1b0000a5cae625a99ef2).

vimrc
```vim
nnoremap <Up> iHello<Esc>
nnoremap <Esc> <Nop>
nnoremap <Esc><Esc> <Nop>
```

1. Start Vim `vim -u vimrc -i NONE -N`
2. Vim starts in Replace mode.
3. Return to Normal mode(`<Esc>`) and type `<Up>`.
4. Entered to Insert mode with `O`, and `A` is input.

### Expected behaviour

- Vim starts in Normal mode.
- When type the `<Up>`, "Hello" is inserted.

### Version of Vim

v8.2.4504

### Environment

OS: Arch Linux
Terminal: Windows Terminal (with tmux 3.2a)
$TERM: screen-256color

**Comment by lacygoill** [comment] 2022-03-07 09:21
Mapping something to Escape is known to [cause issues](https://github.com/lacygoill/wiki/blob/master/vim/mapping.md#why-should-i-avoid-a-mapping-with-an-esc-in-its-lhs).

As a workaround/suggestion, you could try to delay the installation of the problematic mappings with a timer:
```vim
nnoremap <Up> iHello<Esc>

call timer_start(100, {-> s:EscapeMappings()})

function s:EscapeMappings() abort
    nnoremap <Esc> <Nop>
    nnoremap <Esc><Esc> <Nop>
endfunction
```

**Comment by thinca** [comment] 2022-03-07 10:49
This worked as expected before version v8.2.4503.

**Comment by lacygoill** [comment] 2022-03-07 11:56
It doesn't matter whether it worked at some point because there is no guarantee that it should work.

   > The only solution is: Don't map that.

[Source](https://github.com/vim/vim/issues/2581#issuecomment-639746235)

---

FWIW, I had a similar issue in https://github.com/vim/vim/issues/6206
The mapping worked fine before the patch 8.0.0973.

**Comment by lacygoill** [comment] 2022-03-07 12:04
Although, I'm not sure this pitfall is properly documented.

I only found this excerpt somewhere below [`:help t_CTRL-W_CTRL-C`](https://vimhelp.org/terminal.txt.html#t_CTRL-W_CTRL-C):

   > You can use Esc, but you need to make sure it won't cause other keys to
   > break (cursor keys start with an Esc, so they may break), this probably only
   > works in the GUI: >
   >    tnoremap <Esc> <C-W>N
   >    set notimeout ttimeout timeoutlen=100

**Comment by chrisbra** [comment] 2022-03-09 10:20
I guess we can close this then?

**Comment by mattn** [comment] 2022-03-12 03:36
This is side effect of this.

https://github.com/ctrlpvim/ctrlp.vim/issues/592

**Comment by systemmonkey42** [comment] 2022-03-12 04:29
A quick test shows that as soon as you map <kbd>Esc</kbd> to *anything*, existing terminal codes which include escape as a prefix are broken.

Normally vim can tell the difference betweek <kbd>Esc</kbd> and <kbd>Up</kbd>/<kbd>Down</kbd> based on `timeout` and `ttimeout`.

However `timeout` and `ttimeout` no longer have an impact.  Patch 8.2.4504 just breaks everything.

**Comment by Shougo** [comment] 2022-03-12 06:55
@systemmonkey42 It is not just breaking.

https://github.com/vim/vim/issues/9903#issuecomment-1060724305

Please see the comment.  It is the side effect of the fix.

**Comment by brammool** [comment] 2022-03-12 13:10
I had another look.  When I revert Patch 8.2.4504 it doesn't appear to make a difference.  What else matters?

**Comment by brammool** [comment] 2022-03-12 13:43
I found a solution.  I'll submit the patch, but please check for any side effects.

**Closed as completed** 2022-03-12 13:48 UTC

**Comment by thinca** [comment] 2022-03-12 14:13
Thank you very much, Bram!
At least I've confirmed that the problem I was encountering has been fixed.

**Comment by systemmonkey42** [comment] 2022-03-12 23:58
I can confirm this fixes any issues I have with the patch.

Many thanks.

**Comment by bfrg** [comment] 2022-03-18 12:39
I encountered a similar issue, and it's not related to `<Esc>` keys.

Before 8.2.4504, the `s<BS>` mapping worked fine:
```vim
nnoremap s <C-w>
nnoremap s<BS> <C-w><C-^>
```
Since 8.2.4504 it doesn't work anymore.

**Comment by systemmonkey42** [comment] 2022-03-18 14:46
It appears that some mapping which consists of another existing mapping as a prefix are broken.

This does not affect intrinsic (or built in) mappings, eg, after adding
```
nnoremap r<BS> x
```
Pressing r followed by any letter acts as a normal replace.
Pressing r followed by <BS> deletes the character under the cursor

But in @bfrg's example, the mapping for `s' is always executed, unless <kbd>BS</kbd> is replaced by a normal letter.
Eg,
```
nnoremap s <C-w>
nnoremap sl <C-w><C-^>
```
This will correctly add <kbd>s</kbd> as an alias for <kbd>C-w</kbd>, AND allow <kbd>s</kbd><kbd>l</kbd> to open the alternate file in a new split.

It seems that <kbd>BS</kbd> is receiving _very_ special handling in this case.

**Comment by brammool** [comment] 2022-03-18 15:34
This is very tricky.  We can't be sure the termcode is supposed to be replaced or not.  I think we can make a proper guess if the next part of a partly mapping is K_SPECIAL, then we should check for a termcode following right away. Otherwise not, or we would re-introduce the problem that 8.2.4504 was fixing.
