### ISSUE TITLE
Stuck in insert mode - ESC is printed as ^[

### ISSUE THREAD

**Issue by hugomelo** [vim/vim#2258] opened 2017-10-27 13:49 UTC
Hi,

A few weeks ago I've started to come across a Vim bug in which, when I paste a small piece of code in normal mode (not insert mode) it would paste normally the text, but stay stuck in insert mode and every command I use is translated to text in the document.

Esc         becomes ^[
Control-v becomes ^V 
Control-b becomes ^B

The text I've just pasted here is:
```
    height: 45px;
    width: calc( 100% - 40px );
    margin-left: 40px;
    border-bottom: 1px solid #d9dee3;
```
When I paste it again it shows the first line as:
`^[200~    height: 45px;`

Unfortunatelly, copying the text from the first whole snippet above doesn't reproduce the error. That's why I am showing the first line as it's shown in vim. I imagine some more text is coming from the browser inspector (where I am copying text from).
 
I can reproduce it in an empty file pasting the same content in the middle of other letters. When I paste it in an empty line it wouldn't happen.

**Comment by mattn** [comment] 2017-10-27 14:51
Do you reproduce this without plugins? Could you please try with `vim -clean` ?

**Comment by kafeltz** [comment] 2017-10-27 15:42
I had a simular behavior but in fact it was stuck for few seconds. What happened to me, was the LINTER was processing the file (syntastic plugin with eslint).

**Comment by hugomelo** [comment] 2017-10-27 16:14
I can reproduce with `vim -clean`, which I don't what is, but I think disables the plugins only, it loads the vimrc
But.. I can't reproduce removing the vimrc file / .vim directory
It's seems to be related to a code that enables insert or paste mode when we paste text into it.

My vim version is: vim-runtime 8.0.1176-1 on arch linux

**Comment by hugomelo** [comment] 2017-10-27 16:23
I've just noted it doesn't happen if I disable the code below which enables the paste mode during xterm paste.
```
function! XTermPasteBegin()
  set pastetoggle=<Esc>[201~
  set paste
  return ""
endfunction
inoremap <special> <expr> <Esc>[200~ XTermPasteBegin()
```

**Comment by k-takata** [comment] 2017-10-27 16:25
Actually `vim --clean` is correct, not `vim -clean`.

Your settings conflict with the built-in bracketed paste mode support.
See `:help xterm-bracketed-paste` for detail.

**Comment by hugomelo** [comment] 2017-10-27 16:42
@k-takata, are you talking about this patch?
https://groups.google.com/forum/#!topic/vim_dev/E0cG2cfKsQA

Also, I seem to implement a solution for it on tmux as described here:
https://ttssh2.osdn.jp/manual/en/usage/tips/vim.html

How could I achieve the same results of paste without ident (using both tmux or a direct term) so?

**Comment by k-takata** [comment] 2017-10-27 19:29
Not only that one. The support for bracketed paste mode was started from 8.0.0210, but it doesn't work as expected before 8.0.0238. That's the reason why the page you linked checks the Vim version by `if has("patch-8.0.0238")`.
So, if you will use only 8.0.0238 or later, you only need:

```vim
    if &term =~ "screen"
        let &t_BE = "\e[?2004h"
        let &t_BD = "\e[?2004l"
        exec "set t_PS=\e[200~"
        exec "set t_PE=\e[201~"
    endif
```

If you still use older Vim also, use the setting described in the page as it is (including the `else` clause of `if has("patch-8.0.0238")`).

**Comment by chrisbra** [comment] 2017-10-27 20:14
> I can reproduce with vim -clean, which I don't what is, but I think disables the plugins only, it loads the vimrc

`: h --clean`

Please ask user questions at vi.stackexchange.com or vim-use mailinglist. Closing, as this does not seem to be a bug.

**Closed as completed by chrisbra** 2017-10-27 20:14 UTC

**Comment by 1ak31sha** [comment] 2021-05-18 17:31
is there any way to get out of this wierd mode once youre in it without losing your work?

**Comment by 1ak31sha** [comment] 2021-05-18 17:42
> Not only that one. The support for bracketed paste mode was started from 8.0.0210, but it doesn't work as expected before 8.0.0238. That's the reason why the page you linked checks the Vim version by `if has("patch-8.0.0238")`.
> So, if you will use only 8.0.0238 or later, you only need:
> 
> ```viml
>     if &term =~ "screen"
>         let &t_BE = "\e[?2004h"
>         let &t_BD = "\e[?2004l"
>         exec "set t_PS=\e[200~"
>         exec "set t_PE=\e[201~"
>     endif
> ```
> 
> If you still use older Vim also, use the setting described in the page as it is (including the `else` clause of `if has("patch-8.0.0238")`).

im on nvim 0.4.4 (latest as of now) and this happens to me too. your fix didnt work for me unfortunately

**Comment by chrisbra** [comment] 2021-05-18 18:29
It sounds like you are stuck  in xterm bracketed paste mode, which I think is a known problem with neovim 0.4.4. So please report to neovim. It does not support this configuration.

**Comment by ccope** [comment] 2022-03-24 07:07
I've been able to get control back by pasting again from my desktop clipboard (ctrl + shift + V followed by escape).

I've had this happen to me twice recently while using neovim 0.6 inside tmux in an alacritty terminal emulator.  Posting this for my future self because this is the top google result.

**Comment by daviareias** [comment] 2022-10-29 10:52
> I've been able to get control back by pasting again from my desktop clipboard (ctrl + shift + V followed by escape).
> 
> I've had this happen to me twice recently while using neovim 0.6 inside tmux in an alacritty terminal emulator. Posting this for my future self because this is the top google result.

What worked for me was actually copying something else outside of Neovim and pasting it again inside Neovim, after that I could exit insert mode

**Comment by Deshdeepak1** [comment] 2025-04-14 15:33
Same issue I faced with neovim 0.11 in windows terminal, and recovered after pasting with Ctrl+Shift+v again
