### ISSUE TITLE
setting dictionary fails after upgrade to 8.0.101

### ISSUE THREAD

**Issue by mattmartini** [vim/vim#1284] opened 2016-11-25 19:17 UTC
**PROBLEM:** 
After upgrading to Vim 8.0.101 the folowing line in my .vimrc fails.  
`set dictionary+=/usr/share/dict/words
`
with this error message:
`E474: Invalid argument: dictionary+=/usr/share/dict/words
`
I also get this error message using '=' instead of '+=':
`set dictionary=/usr/share/dict/words
`

**OBSERVATIONS:** 
I get the same error if I manually run the command from inside vim.  This line has been in my .vimrc for over a decade.  On another computer with vim 8.0.94 I do not get this error with the same .vimrc

**ENVIORNMENT:**
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Nov 25 2016 13:24:53)
MacOS X (unix) version
Included patches: 1-101
Compiled by Homebrew

Mac OS X 10.10.5 
Homebrew 1.1.1

Note: /usr/share/dict/words is a reachable and readable text file

**Comment by jamessan** [comment] 2016-11-25 19:26
This is a duplicate of #1279 and has also been brought up on [vim_dev].

[vim_dev]: https://www.mail-archive.com/vim_dev@googlegroups.com/msg42837.html

**Closed as completed** 2016-11-25 20:39 UTC
