### ISSUE TITLE
when I create .vimrc in home path, I can not use backspace.

### ISSUE THREAD

**Issue by asmartboy** [vim/vim#10922] opened 2022-08-16 04:12 UTC
### Steps to reproduce

touch .vimrc in home path.
Can not use backspace

### Expected behaviour

Use backspace to change code.

### Version of Vim

9.0.217

### Environment

CentOS Linux release 7.9.2009 (Core)
MoberXterm

**Comment by habamax** [comment] 2022-08-16 04:29
`:h defaults.vim`.

```
							*defaults.vim* *E1187*
If Vim is started normally and no user vimrc file is found, the
$VIMRUNTIME/defaults.vim script is loaded.  This will set 'compatible' off,
switch on syntax highlighting and a few more things.  See the script for
details.  NOTE: this is done since Vim 8.0, not in Vim 7.4. (it was added in
patch 7.4.2111 to be exact).

This should work well for new Vim users.  If you create your own .vimrc, it is
recommended to add these lines somewhere near the top: >
	unlet! skip_defaults_vim
	source $VIMRUNTIME/defaults.vim
Then Vim works like before you had a .vimrc. Copying $VIMRUNTIME/vimrc_example
is way to do this.  Alternatively, you can copy defaults.vim to your .vimrc
and modify it (but then you won't get updates when it changes).
```

**Comment by chrisbra** [comment] 2022-08-16 06:35
This is not a bug of vim but intended behaviour. Please ask user questions on the vim_use mailinglist or use vi.stackexchange.com. This here is a bug tracker for problems with Vim. We cannot provide individual help here. Closing.

**Closed as completed by chrisbra** 2022-08-16 06:35 UTC
Labels: bug
