### ISSUE TITLE
glob() E944 Reverse range in character class

### ISSUE THREAD

**Issue by Julpikar** [vim/vim#15210] opened 2024-07-11 06:52 UTC
### Steps to reproduce

glob([a-z]) -- worked
glob(/[a-z]) -- worked
glob(\\[a-z]) -- worked
glob([z-a]) -- E944
glob(/[z-a]) -- E944
glob(\\[z-a]) -- worked

### Expected behaviour

A file name should be expanded. Instead E944 error is raised.

### Version of Vim

NVIM v0.11.0-dev-381+gfb6c059dc

### Environment

- Windows 10
- cmd
- wezterm

**Comment by chrisbra** [comment] 2024-07-11 07:05
Well, first of all, you would need to quote those arguments, right? 

Then:
```
glob('[z-a]') -- E944
glob('/[z-a]') -- E944
glob('\[z-a]') -- worked
```
Those are all correct. The last one escapes the `[`, so that's why you do not get `E944`. Instead it looks for a file matching literally `[z-a]` and not a glob pattern.

So you would need to use `glob('\\[z-a]')` if you want to match the directory separator and get `E944` again.

**Comment by Julpikar** [comment] 2024-07-11 07:40
maybe related to https://github.com/vim/vim/issues/2749.

**Comment by chrisbra** [comment] 2024-07-11 07:50
don't think so and it is not a bug here. So closing.

**Closed as not planned by chrisbra** 2024-07-11 07:50 UTC
Labels: bug
