### ISSUE TITLE
Bash Syntax HighLight error

### ISSUE THREAD

**Issue by A4-Tacks** [vim/vim#11969] opened 2023-02-10 23:13 UTC
### Steps to reproduce

a=$'\e'
echo "${a@Q}"
![Screenshot_20230211_070940](https://user-images.githubusercontent.com/102709083/218219499-26e9d553-d84b-460b-919f-9746d0a42255.jpg)

### Expected behaviour

"@Q" This section is not marked as an error, which is bash's allowed syntax, which you can find in its manual

### Version of Vim

8.2.4919

### Environment

Os: Ubuntu 22.04
Shell: Bash-5.1.16

**Comment by cecamp** [comment] 2023-02-11 00:12
I'm afraid that I haven't seen that syntax before and the bash manual is quite large. Please elucidate on what its supposed to do. When I ran your code snippet, I got `line 3: ${a@Q}: bad substitution` (I have a #! /bin/bash on top).

**Comment by errael** [comment] 2023-02-11 06:22
Under `Parameter Expansion`
```
       ${parameter@operator}
              Parameter transformation.  The expansion is either a transformation of the value of
              parameter or information about parameter itself, depending on the value  of  opera‐
              tor.  Each operator is a single letter:

              U      The  expansion is a string that is the value of parameter with lowercase al‐
                     phabetic characters converted to uppercase.
              u      The expansion is a string that is the value  of  parameter  with  the  first
                     character converted to uppercase, if it is alphabetic.
              L      The  expansion is a string that is the value of parameter with uppercase al‐
                     phabetic characters converted to lowercase.
              Q      The expansion is a string that is the value of parameter quoted in a  format
                     that can be reused as input.
              E      The  expansion is a string that is the value of parameter with backslash es‐
                     cape sequences expanded as with the $'...' quoting mechanism.
              P      The expansion is a string that is the result of expanding the value  of  pa‐
                     rameter as if it were a prompt string (see PROMPTING below).
              A      The  expansion is a string in the form of an assignment statement or declare
                     command that, if evaluated, will recreate parameter with its attributes  and
                     value.
              K      Produces a possibly-quoted version of the value of parameter, except that it
                     prints the values of indexed and associative arrays as a sequence of  quoted
                     key-value pairs (see Arrays above).
              a      The expansion is a string consisting of flag values representing parameter's
                     attributes.

              If parameter is @ or *, the operation is applied to each  positional  parameter  in
              turn,  and  the expansion is the resultant list.  If parameter is an array variable
              subscripted with @ or *, the operation is applied to each member of  the  array  in
              turn, and the expansion is the resultant list.

              The  result of the expansion is subject to word splitting and pathname expansion as
              described below.
```

**Comment by TAforever** [comment] 2023-02-13 10:10
> I'm afraid that I haven't seen that syntax before and the bash manual is quite large. Please elucidate on what its supposed to do. When I ran your code snippet, I got `line 3: ${a@Q}: bad substitution` (I have a #! /bin/bash on top).



![good](https://user-images.githubusercontent.com/52626363/218429915-233f5f53-5b79-4ea1-8b85-c0c82ca0e72f.png)
![bad](https://user-images.githubusercontent.com/52626363/218429947-90a1a3a9-289c-4df5-a52d-ec2bdf21ba47.png)
Syntax highlighting broke after updating to version 9.0.1302. Rolled back to version 9.0.1182 archlinux.

**Comment by k-takata** [comment] 2023-02-13 10:37
@TAforever I think it's another issue. See #11937.

**Comment by TAforever** [comment] 2023-02-13 10:52
> @TAforever I think it's another issue. See #11937.

@k-takata Thank you! problem solved

**Comment by scrawld** [comment] 2023-02-21 04:09
I also have the same problem
![image](https://user-images.githubusercontent.com/48232670/220245406-ed50c757-44d8-46bc-9e4a-5f48a35fc0a1.png)

**Comment by errael** [comment] 2023-02-21 04:30
> I also have the same problem

@scrawld Same problem as what? This issue is about `echo "${a@Q}"`, and fixed as indicated in #11937

**Comment by jwilk** [comment] 2023-03-06 10:14
Duplicate of #10551.

**Comment by chrisbra** [comment] 2023-03-06 10:29
this seems to be fixed by https://github.com/vim/vim/commit/dd60c365cd2630794be84d63c4fe287124a30b97#diff-650e28e4ad6a5c9241345580a7136ff18b5629f3b4910a5b5a455828bca5e517

**Closed as completed by chrisbra** 2023-03-06 10:29 UTC
Labels: runtime, bug
