### ISSUE TITLE
Termdebug taking 100% cpu

### ISSUE THREAD

**Issue by tomleb** [vim/vim#2179] opened 2017-10-01 12:41 UTC
Hi,

when I use :Termdebug to debug with gdb, my cpu hits 100%.
The only way to stop it is to exit completely or kill vim.

I am running vim 8.0 with included patch: 1-1159.

I tried both with my vimrc loaded and with `vim --clean`.

Simple to reproduce:

1. Open a C file
2. :packadd termdebug
3. :Termdebug <any executable>
4. Wait and see the cpu going to 100%.

(Also, I tried sending this issue on the vim_dev mailing list. I successfully subscribed to the mailing list and I sent my message, but it doesn't seem to appear on [this](https://groups.google.com/forum/#!forum/vim_dev) page (which I assume it should).

**Comment by brammool** [comment] 2017-10-01 14:10
tomleb wrote:

> when I use :Termdebug to debug with gdb, my cpu hits 100%.
> The only way to stop it is to exit completely or kill vim.
> 
> I am running vim 8.0 with included patch: 1-1159.
> 
> I tried both with my vimrc loaded and with `vim --clean`.
> 
> Simple to reproduce:
> 
> 1. Open a C file
> 2. :packadd termdebug
> 3. :Termdebug <any executable>
> 4. Wait and see the cpu going to 100%.

This is caused by select() returning immediately even though there is
nothing to read.  This is for the terminal window without a job.  I
suspect this is because select() considers it an error that the other
side is not connected.  That will happen only later, when "run" is used
in gdb and something is connected.  Although it's still at 100% when the
job has started, even though there is nothing to read.

The only workaround I can think of is to not listen on this fd and poll.
That would cause sluggish behavior though.

Perhaps there is some option for the pty to avoid this behavior?

Since I can't think of a better solution, I'll implement the polling.

> (Also, I tried sending this issue on the vim_dev mailing list. I
> successfully subscribed to the mailing list and I sent my message, but
> it doesn't seem to appear on
> [this](https://groups.google.com/forum/#!forum/vim_dev) page (which I
> assume it should).

First message is moderated.

-- 
Marriage isn't a word.  It's a sentence.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment] 2017-10-15 13:15
fixed by https://github.com/vim/vim/releases/tag/v8.0.1170

**Closed as completed by chrisbra** 2017-10-15 13:15 UTC
Labels: feature-terminal
