### ISSUE TITLE
Key mappings through 'langmap' don't respect mappings, if "from" key is not 7-bit ASCII

### ISSUE THREAD

**Issue by filbranden** [vim/vim#7458] opened 2020-12-11 17:37 UTC
**Describe the bug**
When using the `'langmap'` setting to map keys from non-English keyboard layouts into keys such as braces and brackets in Normal mode, if the "from" key in the mapping is an accented character such as `á`, `é` or `ø`, or an extended symbol such as `€`, the "to" is not used to expand mappings defined with that symbol. If the "from" character is a basic symbol such as `(`, `[` or `3`, it works as expected.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run `vim --clean`
2. Create a mapping to make `<` turn the text object uppercase: `nmap < gU`
3. Set a langmap with a special key mapping to `<`, for example `:set langmap=á<`
4. Type some contents into the buffer, preferrably lines with lowercase letters and with some indentation.
5. Use the `áj` command.

**Expected behavior**
I'd expect this to behave the same as `gUj`, meaning turn the current and following line to uppercase.

Instead, this ends up executing the original behavior of `<`, which is to unindent the current and following line.

The `'langremap'` setting doesn't seem to make a difference here. (As I understand it, it defines how the RHS of mappings work.)

Using a symbol in the 7-bit ASCII range seems to work fine, for example `:set langmap=[<` or `:set langmap=3<`.

**Environment (please complete the following information):**
 - Vim version 8.2.2127 (latest from GH), Vim 8.2.1885 (Fedora), (also DroidVim, version 8.2.1704)
 - OS: Linux (also Android for DroidVim)
 - Terminal: GNOME Terminal (DroidVim ships its own copy of the Android Terminal Emulator)

**Additional context**
Uncovered in [this question](https://vi.stackexchange.com/q/28376/18609) on the Vi & Vim Stack Exchange.

**Comment by habamax** [comment] 2020-12-11 17:40
related (or duplicate of) https://github.com/vim/vim/issues/3018

**Comment by filbranden** [comment] 2020-12-11 18:02
@tonymec I tried it with both `set langremap` and `set nolangremap` (or the equivalent `set langnoremap`), it doesn't make a difference.

It really looks like the issue @habamax mentioned is the source of this bug.

The discussion over there suggests that a proper fix needs a somewhat deep refactor (and the issue has been around for a while), so not sure how quick we'll get a solution for this one...

**Comment by chrisbra** [comment] 2020-12-14 07:44
yes, this is a duplicate of #3018. So closing. The thing is, this is a core function and I did not feel comfortable to make changes which might affect very many other things.

**Closed as completed by chrisbra** 2020-12-14 07:44 UTC
