### ISSUE TITLE
setline() will clear text property

### ISSUE THREAD

**Issue by Yggdroot** [vim/vim#15030] opened 2024-06-17 05:01 UTC
### Steps to reproduce

```help
setline({lnum}, {text}) 
                Set line {lnum} of the current buffer to {text}.  To insert
                lines use append(). To set lines in another buffer use
                setbufline().  **Any text properties in {lnum} are cleared.**
```

As the help says: Any text properties in {lnum} are cleared. 
If  a plugin uses `setline`, the text properties defined by other plugins will be removed. This is unexpected.

I think it is reasonable that `setline()` does not clear text property. 
The following operations have the same effect as `call setline(line('.'), '')`：
1. in normal mode
2. type `0` to go to the first column
3. type `D` 

This won't remove the text property.

Another reason, `setline()` won't clear extmarks set by `nvim_buf_set_extmark()` in neovim， where extmarks in neovim is equivalent to text property in vim.

### Expected behaviour

setline() does not clear text property.

### Version of Vim

all

### Environment

all

**Comment by chrisbra** [comment] 2024-06-17 06:36
Well, I can only say this is done intentionally since [v8.1.0690](https://github.com/vim/vim/releases/tag/v8.1.0690). The idea probably was that once you replace a line, all attached properties to it may no longer be valid, which I think makes sense.

**Comment by Yggdroot** [comment] 2024-06-17 07:24
Although it was intentional, I can not see the advantage of it, but lots of disadvantages. Because I can not prevent the text properties defined by my plugin from being removed by others which use `setline()`.

I don't think it make sense that the text property is removed after `call setline(line('.'), getline('.'))`, the text is not changed in the user's view.

What is more, as I said above, `Another reason, setline() won't clear extmarks set by nvim_buf_set_extmark() in neovim， where extmarks in neovim is equivalent to text property in vim.`

**Comment by Shane-XB-Qian** [comment] 2024-06-17 07:34
looks it make sense if the text was changed.
but I am curious you said the by D then it would be remained?

--
shane.xb.qian

**Comment by chrisbra** [comment] 2024-06-17 07:38
> What is more, as I said above, Another reason, setline() won't clear extmarks set by nvim_buf_set_extmark() in neovim， where extmarks in neovim is equivalent to text property in vim.

I don't see how this relates to Vim. We don't have this: `nvim_buf_set_extmark()`.

**Comment by Yggdroot** [comment] 2024-06-17 07:47
> looks it make sense if the text was changed. but I am curious you said the by D then it would be remained?
> […](#)
> -- shane.xb.qian

```vim
call prop_type_add('aaa', {'highlight': 'Number'})
call prop_add(line('.'), 0, {'type':'aaa', 'text': 'test'})

```

**Comment by Yggdroot** [comment] 2024-06-17 08:09
> > What is more, as I said above, Another reason, setline() won't clear extmarks set by nvim_buf_set_extmark() in neovim， where extmarks in neovim is equivalent to text property in vim.
> 
> I don't see how this relates to Vim. We don't have this: `nvim_buf_set_extmark()`.

I mean in neovim's point of view, `setline` should not remove text property just like `setline` does not remove extmarks.


Another reason current behavior is thought to be buggy is : `setline` also removes  zero-width text property.

https://github.com/vim/vim/blob/c52a8560792b47a19fd0686377f588ef25e5a7d4/runtime/doc/textprop.txt#L509-L517

 **However, a text property that was defined as zero-width will remain,  unless the whole line is deleted.**

**Comment by chrisbra** [comment] 2024-06-17 08:13
> However, a text property that was defined as zero-width will remain, unless the whole line is deleted.

I think this is essentially what setline does. It deletes the line and replaces it with a new one, even if it is empty.

**Comment by zeertzjq** [comment] 2024-06-17 08:16
Maybe this can be made configurable as a flag of text properties?

**Comment by Yggdroot** [comment] 2024-06-17 08:28
> > However, a text property that was defined as zero-width will remain, unless the whole line is deleted.
> 
> I think this is essentially what setline does. It deletes the line and replaces it with a new one, even if it is empty.

Is it not the same with :
norm! 0D
then append some text ?

**Comment by chrisbra** [comment] 2024-06-17 08:36
I rahter thought of making the behaviour of setline() configurable.

**Comment by habamax** [comment] 2024-06-17 08:57
> I rather thought of making the behaviour of setline() configurable.

How it would solve the issue then? There still will be `setline()` calls that would remove text properties:

> Because I can not prevent the text properties defined by my plugin from being removed by others which use setline().

I think removal of text properties as of current implementation is expected.

**Comment by chrisbra** [comment] 2024-06-17 09:34
> I think removal of text properties as of current implementation is expected.

Yes, that is also my expectation, see also: https://github.com/vim/vim/blob/c52a8560792b47a19fd0686377f588ef25e5a7d4/runtime/doc/textprop.txt#L534-L538

it looks like even `:move` drops the text properties.

> There still will be setline() calls that would remove text properties

Well, would you expect the text-property to be still there after doing
```
:5d
:4put ='foobar'
```
? Once you remove the line and add a new line, how would do you know the attached text-property attached to that line is still valid?

**Comment by Shane-XB-Qian** [comment] 2024-06-17 09:38
> > looks it make sense if the text was changed. but I am curious you said the by D then it would be remained?
> > […](#)
> > -- shane.xb.qian
> 
> ```vim
> call prop_type_add('aaa', {'highlight': 'Number'})
> call prop_add(line('.'), 0, {'type':'aaa', 'text': 'test'})
> ```

not sure why `D` was special..
// if delete by :delete, then it was removed too.

-- 
shane.xb.qian

**Comment by Yggdroot** [comment] 2024-06-17 09:42
> > looks it make sense if the text was changed. but I am curious you said the by D then it would be remained? > […](#) > -- shane.xb.qian ```vim call prop_type_add('aaa', {'highlight': 'Number'}) call prop_add(line('.'), 0, {'type':'aaa', 'text': 'test'}) ```
> not sure why `D` was special.. // if delete by :delete, then it was removed too.
> […](#)
> -- shane.xb.qian

It is different. 
:delete is the same as `dd`, not `D`

**Comment by Shane-XB-Qian** [comment] 2024-06-17 09:50
yes, it is different, but the answer maybe as @chrisbra commented above, to `D` maybe it was intended to make it happy with instant edit. :shrug:

**Comment by Yggdroot** [comment] 2024-06-17 09:56
> > I think removal of text properties as of current implementation is expected.
> 
> Yes, that is also my expectation, see also:
> 
> https://github.com/vim/vim/blob/c52a8560792b47a19fd0686377f588ef25e5a7d4/runtime/doc/textprop.txt#L534-L538
> 
> it looks like even `:move` drops the text properties.
> 
> > There still will be setline() calls that would remove text properties
> 
> Well, would you expect the text-property to be still there after doing
> 
> ```
> :5d
> :4put ='foobar'
> ```
> 
> ? Once you remove the line and add a new line, how would do you know the attached text-property attached to that line is still valid?

Actually, my expectation is : 
for example, 
```vim
call prop_type_add('aaa', {'highlight': 'Number'})
call prop_add(line('.'), 0, {'type':'aaa', 'text': 'test'})
```

`call setline(line('.'), '')` has the same effect as `norm! 0D`.

```vim
call prop_type_add('aaa', {'highlight': 'Number'})
call prop_add(line('.'), 1, {'type':'aaa', 'length': 0})
```
`call setline(line('.'), '')` has the same effect as `norm! 0D`. 

Because `However, a text property that was defined as zero-width will remain, unless the whole line is deleted.`
I think setline is not delete line 3 and insert a new line after line 2, it is replacing line 3 with new text. Am I right?

**Comment by Shane-XB-Qian** [comment] 2024-06-17 10:03
`unless the whole line is deleted` it is `D`

**Comment by Shane-XB-Qian** [comment] 2024-06-17 10:05
`unless the whole line is deleted` it was said for `D` :sweat_smile:

**Comment by Yggdroot** [comment] 2024-06-17 10:06
> `unless the whole line is deleted` it was said for `D` 😅

I think it's dd

**Comment by Shane-XB-Qian** [comment] 2024-06-17 10:07
i meant that statement was expressed why `D` was special.

**Comment by chrisbra** [comment] 2024-06-17 10:47
I posted the link to the documentation already. It's simply not possible to retain the text property, because how should Vim know where you added some text?
```
call setline(1, 'You are a hero!')
cal prop_type_add('Highlight', #{highlight: 'Search'})
call prop_add(1, 11, {'end_col': 15, 'type': 'Highlight'})
" doesn't work, but would add an off by one error
call getline(1)->substitute('\<a\>', 'my', 'g')->setline(1) 
```

**Comment by Yggdroot** [comment] 2024-06-17 12:00
Notice that my example is special, one is virtual text, the column is 0, another is 0-width.

```vim
call prop_type_add('aaa', {'highlight': 'Number'})
call prop_add(line('.'), 0, {'type':'aaa', 'text': 'test'})
```

```vim
call prop_type_add('aaa', {'highlight': 'Number'})
call prop_add(line('.'), 1, {'type':'aaa', 'length': 0})
```
`:call setline(line('.'), '')`  will remove the virtual text,  `:norm! 0D` won't.
Can we make their behavior the same?

**Comment by habamax** [comment] 2024-06-17 12:07
> :call setline(line('.'), '') will remove the virtual text, :norm! 0D won't.
> Can we make their behavior the same?

If properties wouldn't be removed, then *a lot* of things would need to be changed internally...
You have a text property, then you changed a line and now it is invalid.

![image](https://github.com/vim/vim/assets/234774/ffae535e-9ded-4341-a055-f949bd3ae77e)

**Comment by habamax** [comment] 2024-06-17 12:10
Now if the case is virtual text at the edges of the line -- it could be safe to preserve it, although I am not sure it worth the complexity it brings.

**Comment by Shane-XB-Qian** [comment] 2024-06-17 12:45
> Can we make their behavior the same?

the 'question' had been answered above.

--
shane.xb.qian

**Comment by Yggdroot** [comment] 2024-06-17 12:47
> Can we make their behavior the same?
> the 'question' had been answered above.
> […](#)
> -- shane.xb.qian

I don't think so.

**Comment by bfrg** [comment] 2024-06-17 21:10
I would also expect `setline()` and `setbufline()` to remove any text-properties.

I think what you want is something like `subbufline()` that substitutes text in a line while preserving text-properties in that line, similar to the `:substitute` command. There's already an open feature request for https://github.com/vim/vim/issues/5632. Bram wasn't opposed to this idea, it just needs to be implemented. :smile:

**Comment by Yggdroot** [comment] 2024-06-18 01:51
In my view, ` :call setline(line('.'), '')`  and  `:norm! 0D` do the same thing, why `:norm! 0D` don't remove the virtual-text  column starts from 0 and the 0-width text property?

**Comment by chrisbra** [comment] 2024-06-18 12:02
The effect might be the same, but it is not the same, it's essentially a `:d` followed by a `:put`. 
There is also `listener_add()` not sure, if one can use it to save and restore text-properties. 

The current behaviour is well documented, so let's close this as a duplicate of #5632 then.

**Closed as not planned by chrisbra** 2024-06-18 12:02 UTC
Labels: bug
