### ISSUE TITLE
Error detected while processing syntax/fortran.vim

### ISSUE THREAD

**Issue by interkosmos** [vim/vim#5433] opened 2020-01-03 16:26 UTC
**Describe the bug**
Error message occurs when starting Vim 8.2 with Fortran syntax highlighting enabled:

```
let fortran_free_source=1
let fortran_more_precise=1
let fortran_do_enddo=1
```
The following error is shown when a Fortran file (`*.f90`) is opened:
```
Error detected while processing /usr/local/share/vim/vim82/syntax/fortran.vim:
line  188:
E869: (NFA) Unknown operator '\@1'
E475: Invalid argument: fortranTarget^Idisplay^I"\(\<do\s\+\)\@<11=\d\+\>"
line  277:
E869: (NFA) Unknown operator '\@1'
E475: Invalid argument: fortranConstructName "\(\<end\s*forall\s\+\)\@<15=\a\w*\>"
```

**To Reproduce**
1. Enable Fortran syntax highlighting in `.vimrc`.
2. Open any Fortran source-code file.
3. Error is shown.

**Expected behavior**
No error to be shown.

**Screenshots**
–

**Environment (please complete the following information):**
 - Vim version: 8.2
 - OS: FreeBSD 12
 - Terminal: XTerm.

**Additional context**
–

**Comment by chrisbra** [comment] 2020-01-03 16:37
duplicate of #5350 

as mentioned there, please contact the maintainer of the file.

**Closed as completed by chrisbra** 2020-01-03 16:37 UTC
Labels: duplicate, runtime
