### ISSUE TITLE
PHP OmniComplete fails with E565

### ISSUE THREAD

**Issue by fancsali** [vim/vim#10047] opened 2022-03-30 16:03 UTC
### Steps to reproduce

1. Open ViM, exiting a PHP file: `vim --clean spam.php`
2. Confirm, the filetype is set: `set ft?` responds with `ft=php`
3. Start typing:
```
<?php
ech<C-X><X-O>
```
4. Observer error:
```
Error detected while processing function phpcomplete#CompletePHP[131]..function phpcomplete#CompletePHP[63]..phpcomplete#GetCurrentNameSpace:
line   30:
E565: Not allowed to change text or change window
Press ENTER or type command to continue
```

### Expected behaviour

OmniComplete works

### Version of Vim

8.2.2434

### Environment

Operating System: Raspberry Pi OS 11 (bullseye)

**Comment by chrisbra** [comment] 2022-03-30 20:00
I also can't reproduce. So closing assuming this is already fixed.

**Closed as completed by chrisbra** 2022-03-30 20:00 UTC

**Comment by fancsali** [comment] 2022-03-30 23:16
@lacygoill: Thanks, reported downstream to the Debian maintainers: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1008710.

**Comment by chrisbra** [comment] 2022-03-31 07:40
Note: you can always download the latest version from the vim repository to your `~/.vim/` directory and override the system version with this. So you do not need for Debian to fix this.

**Comment by lacygoill** [comment] 2022-03-31 13:10
Indeed, you might override the current php completion with a more recent one:

    $ mkdir -p ~/.vim/autoload/
    $ curl -s https://raw.githubusercontent.com/vim/vim/master/runtime/autoload/phpcomplete.vim > ~/.vim/autoload/phpcomplete.vim

**Comment by fancsali** [comment] 2022-04-01 09:15
@chrisbra & @lacygoill: That's exactly what I did; but thanks for the help and suggestions. Nevertheless I found, it's a nice thing to report it for the benefit of the community. ;)
