### ISSUE TITLE
Vim freezes consuming CPU when I edit a .php file

### ISSUE THREAD

**Issue by DiscipleOfShinku** [vim/vim#4562] opened 2019-06-19 08:34 UTC
**Describe the bug**
Vim freezes in the insert mode when I hit an Enter.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Create a file `t.php`:
``` php
<?php
$a = ", sd";
?>
```
2. Run `vim --clean t.php`
3. Place a cursor at the `,`.
4. Press an `a`.
5. Press an Enter.
6. Vim is freezed.

**Environment:**
 - Vim version: 8.1.1401
 - OS: Debian Buster (Linux 4.19.0-4-amd64 #1 SMP Debian 4.19.28-2 (2019-03-15) x86_64 GNU/Linux)
 - Terminal: xfce4-terminal

**Additional context**
Vim does not freeze if I name a file `t`.

**Comment by chrisbra** [comment] 2019-06-19 13:26
It's the [php indent](https://github.com/vim/vim/blob/master/runtime/indent/php.vim) that causes a endless loop, because `trylnum` will never be properly decremented.

I think this patch fixes it:
```patch
diff --git a/runtime/indent/php.vim b/runtime/indent/php.vim
index 5dee6c9f4..2b62f04d6 100644
--- a/runtime/indent/php.vim
+++ b/runtime/indent/php.vim
@@ -218,7 +218,7 @@ function! GetLastRealCodeLNum(startline) " {{{
                let trylnum = trylnum - 1
            endwhile

-           if trylnum == 1
+           if trylnum == 1 || trylnum == lnum
                break
            else
                if lastline =~ ';'.s:endline
@@ -227,7 +227,7 @@ function! GetLastRealCodeLNum(startline) " {{{
                    endwhile


-                   if trylnum == 1
+                   if trylnum == 1 || trylnu == lnum
                        break
                    end
                end
```

However, it should probably be reported at the upstream repository:

https://github.com/2072/PHP-Indenting-for-VIm

ping @2072 (since he is the upstream author).

**Comment by chrisbra** [comment] 2019-06-19 13:26
Note, I can reproduce the issue with the upstream repository as well.

**Comment by 2072** [comment] 2019-06-30 19:21
This is fixed in upstream, thanks for the patch but the problem was actually caused by the regex testing for the end of multi-lined strings declaration which, in this case is also matching the line where the string is opened, because of the comma... I added a syntax check.

**Closed as completed** 2019-07-14 16:11 UTC
