### ISSUE TITLE
Get wired string when open a file.

### ISSUE THREAD

**Issue by roachsinai** [vim/vim#5965] opened 2020-04-22 02:16 UTC
**Describe the bug**

I got a wierd string when use `gVim`(what I exactly using is run `vim` in konsole), the string is `^[[2;2R^[[> 0;115;0c^[]11;rgb:2323/2323/2323^G`.

**To Reproduce**

I can't reproduce it one hundred percent. Try several times maybe catch one.

![got_it](https://user-images.githubusercontent.com/9500049/80571186-bd765900-8a2e-11ea-866c-34d130d69dd1.gif)

And sometime the string changes:

![Screenshot_20200429_102311](https://user-images.githubusercontent.com/9500049/80571242-d8e16400-8a2e-11ea-9f31-e173b03876bf.png)

Failed to  catch it this time.

**Expected behavior**

No these string

**Environment:**
 - OS: [Manjaro 20.0 Lysia]
 - Terminal: [Konsole, yakuake]
 - Vim version:

```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr  4 2020 13:23:00)
包含补丁: 1-510
编译者 Arch Linux
巨型版本 with GTK3 GUI.  可使用(+)与不可使用(-)的功能:
+acl               -farsi             -mouse_sysmouse    -tag_old_static
+arabic            +file_in_path      +mouse_urxvt       -tag_any_white
+autocmd           +find_in_path      +mouse_xterm       +tcl/dyn
+autochdir         +float             +multi_byte        +termguicolors
-autoservername    +folding           +multi_lang        +terminal
+balloon_eval      -footer            -mzscheme          +terminfo
+balloon_eval_term +fork()            +netbeans_intg     +termresponse
+browse            +gettext           +num64             +textobjects
++builtin_terms    -hangul_input      +packages          +textprop
+byte_offset       +iconv             +path_extra        +timers
+channel           +insert_expand     +perl/dyn          +title
+cindent           +job               +persistent_undo   +toolbar
+clientserver      +jumplist          +popupwin          +user_commands
+clipboard         +keymap            +postscript        +vartabs
+cmdline_compl     +lambda            +printer           +vertsplit
+cmdline_hist      +langmap           +profile           +virtualedit
+cmdline_info      +libcall           +python/dyn        +visual
+comments          +linebreak         +python3/dyn       +visualextra
+conceal           +lispindent        +quickfix          +viminfo
+cryptv            +listcmds          +reltime           +vreplace
+cscope            +localmap          +rightleft         +wildignore
+cursorbind        +lua/dyn           +ruby/dyn          +wildmenu
+cursorshape       +menu              +scrollbind        +windows
+dialog_con_gui    +mksession         +signs             +writebackup
+diff              +modify_fname      +smartindent       +X11
+digraphs          +mouse             +sound             -xfontset
+dnd               +mouseshape        +spell             +xim
-ebcdic            +mouse_dec         +startuptime       -xpm
+emacs_tags        +mouse_gpm         +statusline        +xsmp_interact
+eval              -mouse_jsbterm     -sun_workshop      +xterm_clipboard
+ex_extra          +mouse_netterm     +syntax            -xterm_save
+extra_search      +mouse_sgr         +tag_binary        
     系统 vimrc 文件: "/etc/vimrc"
     用户 vimrc 文件: "$HOME/.vimrc"
 第二用户 vimrc 文件: "~/.vim/vimrc"
      用户 exrc 文件: "$HOME/.exrc"
    系统 gvimrc 文件: "/etc/gvimrc"
    用户 gvimrc 文件: "$HOME/.gvimrc"
第二用户 gvimrc 文件: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
        系统菜单文件: "$VIMRUNTIME/menu.vim"
         $VIM 预设值: "/usr/share/vim"
编译方式: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/lib/libffi-3.2.1/include -I/usr/include/harfbuzz -I/usr/include/fribidi -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/gio-unix-2.0 -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/at-spi-2.0 -pthread    -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -D_REENTRANT  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
链接方式: gcc   -L. -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fstack-protector-strong -rdynamic -Wl,-export-dynamic -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.30/core_perl/CORE  -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -L/usr/local/lib -Wl,--as-needed -o vim   -lgtk-3 -lgdk-3 -lz -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0  -lSM -lICE -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lelf -lnsl    -lcanberra  -lacl -lattr -lgpm -ldl   -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.30/core_perl/CORE -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/perl5/5.30/core_perl/CORE -lperl -lpthread -ldl -lm -lcrypt -lutil -lc   -L/usr/lib -ltclstub8.6 -ldl -lz -lpthread -lm     
```

**Additional context**

Any hints would be appreciated. Thanks in advanced!

**Comment by chrisbra** [comment] 2020-04-29 08:12
check your terminal configuration. In particular, the $TERM environment variable and perhaps you also need to disable the `termguicolors` setting.

**Comment by roachsinai** [comment] 2020-04-29 08:18
@chrisbra Thanks for the fast reply!

My termguicolors setting is:

```
if has("termguicolors")
    " fix true color not work under tmux
    let &t_8f = "ESC[38;2;%lu;%lu;%lum"
    let &t_8b = "ESC[48;2;%lu;%lu;%lum"
    " enable true color
    set termguicolors
endif
```

and `$TERM`:

```
hmank ~/c/G/dotfiles master » echo $TERM
xterm-256color
```

**Comment by roachsinai** [comment] 2020-04-29 08:41
What's more `$COLORTERM` shows truecolor.

```
hmank ~/c/G/dotfiles master » echo $COLORTERM
truecolor
```

**Comment by chrisbra** [comment] 2020-04-29 09:22
> ```
> if has("termguicolors")
>     " fix true color not work under tmux
>     let &t_8f = "ESC[38;2;%lu;%lu;%lum"
>     let &t_8b = "ESC[48;2;%lu;%lu;%lum"
>     " enable true color
>     set termguicolors
> endif
> ```
> 
> 
> and `$TERM`:
> 
> ```
> hmank ~/c/G/dotfiles master » echo $TERM
> xterm-256color
> ```

Are you sure this is actually correct for your terminal?

**Comment by chrisbra** [comment] 2020-04-29 09:25
especiall the literally "ESC" in your `t_8f` and `t_8b` settings look wrong and if you want to use the defaults (e.g. semi-colon delimited values, you do not need to specify `t_8f` and `t_8b`. BTW: this looks like a configuration problem and not a bug in Vim.

**Comment by roachsinai** [comment] 2020-04-29 10:23
> > ```
> > if has("termguicolors")
> >     " fix true color not work under tmux
> >     let &t_8f = "ESC[38;2;%lu;%lu;%lum"
> >     let &t_8b = "ESC[48;2;%lu;%lu;%lum"
> >     " enable true color
> >     set termguicolors
> > endif
> > ```
> > 
> > 
> > and `$TERM`:
> > ```
> > hmank ~/c/G/dotfiles master » echo $TERM
> > xterm-256color
> > ```
> 
> Are you sure this is actually correct for your terminal?

Well I runed `cat` to print my color setting to konsole. What exactly in my VIMRC is:

![image](https://user-images.githubusercontent.com/9500049/80585806-84e27980-8a46-11ea-973c-40079a842a91.png)

**Comment by roachsinai** [comment] 2020-04-29 10:32
> especiall the literally "ESC" in your `t_8f` and `t_8b` settings look wrong and if you want to use the defaults (e.g. semi-colon delimited values, you do not need to specify `t_8f` and `t_8b`. BTW: this looks like a configuration problem and not a bug in Vim.

Maybe! I confused several day about this. Failed to resolve it..

And remove the setting `t_8f` and `t_8b` still can't help it.

**Comment by chrisbra** [comment] 2020-04-29 12:25
as far as I can see, you are explicitly using the defaults for `t_8f` and `t_8b` (so you can leave that out). Are you sure, that the terminal is actually capable of using true color settings? Are you sure, $TERM=xterm-256color is correct for the terminal you are using? It sounds like it is not, since if your terminal is capable of truecolors, than `-256color` is definitely wrong (and it is definitely not a xterm). Does it work correctly, if you do not set termguicolors?

**Comment by roachsinai** [comment] 2020-04-29 13:38
I'v removed settings about truecolor:

```
if has("termguicolors")
    " fix true color not work under tmux
    let &t_8f = "ESC[38;2;%lu;%lu;%lum"
    let &t_8b = "ESC[48;2;%lu;%lu;%lum"
    " enable true color
    set termguicolors
endif
```

setting above was removed, still have this issue.

**Comment by chrisbra** [comment] 2020-04-29 13:51
please try with a minimal or start from `vim --clean`

**Comment by roachsinai** [comment] 2020-04-29 15:12
I'm sorry for now failed to find a minimal vimrc to reproduce the string one hundred percent shows like `^[[2;2R^[[> 0;115;0c^[]10;rgb:a9a9/b7b7/c6c6^G^[]11;rgb:2323/2323/2323^G`.

Found a old thread #183 which echo similar string but in message area.

**Comment by chrisbra** [comment] 2020-04-29 15:20
I don't know what causes this. I suspect a terminal incompatibility.

**Comment by roachsinai** [comment] 2020-04-29 15:44
Maybe, I'll check on xfce terminal later...

**Comment by roachsinai** [comment] 2020-04-30 14:45
Well it can be reproduce 100% on xfce-terminal and terminator! And maybe found the reason: 
```
Plug 'Valloric/YouCompleteMe'
" input method switching
Plug 'rlue/vim-barbaric'
```

YCM must ahead barbaric (when using vim-plug)!

**Comment by chrisbra** [comment] 2020-04-30 20:20
please always provide reproducible examples, starting from `vim --clean`. I suppose this is not Vims fault here. So closing.

**Closed as completed by chrisbra** 2020-04-30 20:20 UTC
Labels: question

**Comment by roachsinai** [comment] 2020-05-01 02:36
Sorry for my last comment.

I mean I installed two plugins: YouCompleteMe and vim-barbaric by vim-plug.

And seems in the block:

```
call plug#begin('~/.vim/plugged')

call plug#end()
```

YouCompleteMe must ahead vim-barbaric!

```
call plug#begin('~/.vim/plugged')
Plug 'rlue/vim-barbaric'
Plug 'Valloric/YouCompleteMe'
call plug#end()
```

Setting above will reproduce it on konsole(sometimes reproduce), on xfce-terminal and terminator(reproduce 100%).

And I agree it's not Vim's fault.
