### ISSUE TITLE
syntax/sh.vim: unmatched quotes

### ISSUE THREAD

**Issue by birkelund** [vim/vim#6416] opened 2020-07-07 06:31 UTC
**Describe the bug**
Since version v190 of `syntax/sh.vim` I am seeing quotes being unmatched in certain situations. 

**To Reproduce**
1. Run `vim --clean test.sh` (test file attached as [test.sh.txt](https://github.com/vim/vim/files/4882891/test.sh.txt))
2. See Screenshots.

**Expected behavior**
Quotes a matched as they were in v189 of `syntax/sh.vim`.

**Screenshots**
![quotes](https://user-images.githubusercontent.com/55311/86727452-bf125d80-c02b-11ea-9f22-201659eca33a.png)

**Environment (please complete the following information):**
 - Vim version: 8.2.0814
 - OS: Arch Linux
 - Terminal: st, xterm (tested both)

**Additional context**
I know this is a runtime bug, so I contacted the maintainer, but have received no reply.

**Comment by birkelund** [comment] 2020-07-07 06:33
Applying the following diff fixes the issue (reverting the addition of `matchgroup=shSpecial in line 361)

```diff
diff --git i/runtime/syntax/sh.vim w/runtime/syntax/sh.vim
index 3a2a6e7b0e4c..290087f6ef49 100644
--- i/runtime/syntax/sh.vim
+++ w/runtime/syntax/sh.vim
@@ -358,7 +358,7 @@ elseif !exists("g:sh_no_error")
 endif
 syn region  shSingleQuote      matchgroup=shQuote start=+'+ end=+'+            contains=@Spell nextgroup=shSpecialStart,shSpecialSQ
 syn region  shDoubleQuote      matchgroup=shQuote start=+\%(\%(\\\\\)*\\\)\@<!"+ skip=+\\.+ end=+"+    contains=@shDblQuoteList,shStringSpecial,@Spell nextgroup=shSpecialStart
-syn region  shDoubleQuote      matchgroup=shQuote start=+"+ matchgroup=shSpecial skip=+\\"+ end=+"+            contained       contains=@shDblQuoteList,shStringSpecial,@Spell nextgroup=shSpecialStart
+syn region  shDoubleQuote      matchgroup=shQuote start=+"+ skip=+\\"+ end=+"+         contained       contains=@shDblQuoteList,shStringSpecial,@Spell nextgroup=shSpecialStart
 syn match   shStringSpecial    "[^[:print:] \t]"                       contained
 syn match   shStringSpecial    "[^\\]\zs\%(\\\\\)*\\[\\"'`$()#]"                       nextgroup=shComment
 syn match   shSpecialSQ        "[^\\]\zs\%(\\\\\)*\\[\\"'`$()#]"               contained       nextgroup=shBkslshSnglQuote,@shNoZSList
```

**Comment by mlippert** [comment] 2020-07-27 16:00
I've been seeing the same shell script syntax highlighting behavior.
I also sent an email report to the maintainer, but haven't gotten a reply saying that they have been able to reproduce the problem and were going to look into it.

This is with this (g)vim version (on Linux Mint 18.3 KDE):
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jul 27 2020 10:52:11)
Included patches: 1-1303
Modified by jonathon.fernyhough@york.ac.uk
```

![image](https://user-images.githubusercontent.com/2589356/88562847-33bf3300-cfff-11ea-935e-f8f18efff0c9.png)
As you can see I may have found some additional cases that narrow when the closing double quote is highlighted incorrectly. (It may not add to what @birkelund found if these are just additional cases related to `shSpecial`)

It seems that quotes after `echo` and after parameter assignment, as well as all quoted strings in a function definition have this problem.

Note the double quoted string after a random command (I used the names `test` and `anycmd` above) that is not inside a function definition has the closing quote highlighted correctly.

I've been reverting version 190 back to version 189 after every update of vim. But it would be nice if this got fixed and I didn't have to do that.

**Comment by vim-ml** [comment] 2020-07-27 20:17
On 2020-07-27, Mike Lippert wrote:

> This is with this (g)vim version (on Linux Mint 18.3 KDE):

> I've been reverting version 190 back to version 189 after every
> update of vim.  But it would be nice if this got fixed and
> I didn't have to do that.

You can avoid doing that after every update by copying version 189
of sh.vim into ~/.vim/syntax.  Version 190 will see that the sh
syntax file has already been loaded and won't load itself, so you'll
get only version 189.

That is the recommended method of making any changes to the runtime
files that come with the Vim package because it avoids the problem
of your changes being overwritten by the next update.

Regards,
Gary

**Comment by benburrill** [comment] 2020-08-02 02:32
Alternatively, you can just put that one line from birkelund's comment into ~/.vim/after/syntax, as I've done [here](https://github.com/benburrill/.vim/blob/master/after/syntax/sh.vim).

**Comment by filbranden** [comment] 2020-08-29 16:00
This has been fixed on latest v193 on DrChip's website.

Can we please get an update to runtime to get this fixed on the version shipped with Vim?

More details here:
https://vi.stackexchange.com/a/27062/18609

**Comment by chrisbra** [comment] 2020-09-02 06:15
I am closing this here. I suppose @cecamp will send updates to @brammool whenever he thinks the version is ready to be included. For the time being, use the version from DrChip's website.

**Closed as completed by chrisbra** 2020-09-02 06:15 UTC
Labels: runtime

**Comment by filbranden** [comment] 2020-09-21 16:21
This is still an issue, the shipped version is currently bugged.

I don't see why this should be closed. I understand there's an external maintainer, but since the runtimes are shipped together with Vim, it doesn't make sense to close it here if the issue is still not closed...

There have been updates to runtimes lately (for example, 1d59aa1fdfb191d9872ff87eb94652acd374b293 yesterday) and this syntax file is still broken.

If fixing it is not an option, at least can we get it rolled back to v189 which was working correctly?

**Comment by inkarkat** [comment] 2020-09-21 18:40
I second @filbranden here. Rolling back to the last known good version (and waiting for a fix from DrChip) would have been trivial - that's what version control is for.

Though it's just a visual disruption, the _shell_ filetype is very common, and double-quoted strings appear in virtually all shell scripts somewhere. Many people (including me) edit a lot of shell scripts each day, and as IDEs typically focus on Java / C / Python / JavaScript, Vim is a predominant editor for them.

I've been close to implementing the mentioned fix in `~/.vim/after/syntax/sh.vim` several times, but always thought that an official fix would be just around the corner, and it's too easy to forget about undoing the fix in one's local config (especially as more and more time passes until it's fixed in upstream).

I know you're busy working on the Vim 9 language, but please don't forget the mundane maintenance of existing functionality!
