### ISSUE TITLE
compile error with lua 5.4

### ISSUE THREAD

**Issue by zhuzhzh** [vim/vim#6380] opened 2020-07-02 14:26 UTC
**Describe the bug**
with lua 5.4, the compile will error out at if_lua.c line 462

**To Reproduce**
Detailed steps to reproduce the behavior:
1. download lua 5.4
2. compile lua: make && make install
3. compile vim with 
--with-lua-prefix=<place to lua> \
--enable-luainterp=yes

**Expected behavior**
the compile should pass

**Screenshots**

**Environment (please complete the following information):**
- centos 6.8
- gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-4)

**Comment by chrisbra** [comment] 2020-07-02 14:42
lua 5.4 is almost like a new and different language. So this needs some adjustments in the source. I think it is a duplicate of #6358

**Closed as completed by chrisbra** 2020-07-02 14:42 UTC
Labels: if_lua
