### ISSUE TITLE
Inquiry: StatusLine highlight groups

### ISSUE THREAD

**Issue by dylnmc** [vim/vim#4143] opened 2019-03-21 15:24 UTC
Preface: this is less of a bug (I think) and more of an inquiry into how vim highlights user-defined highlight groups for the statusline.

---

If you put make this your vimrc, or comment out your statusline plugin and/or config and put this in there:

```vim
augroup StlStuff
	au!
	au VimEnter * hi StlBufnameRo      guifg=#f2777a ctermfg=1  guibg=#515151 ctermbg=8
	au VimEnter * hi StlBufnameNoma    guifg=#cc99cc ctermfg=5  guibg=#515151 ctermbg=8
	au VimEnter * hi StlBufnameMod     guifg=#6699cc ctermfg=4  guibg=#515151 ctermbg=8
	au VimEnter * hi StlBufnameDefault guifg=#99cc99 ctermfg=2  guibg=#515151 ctermbg=8
augroup end
set stl=%#StlBufname#%f%{PostStl()}
function! PostStl()
	exe 'hi! link StlBufname StlBufname'.(&ro ? 'Ro' : (!&ma ? 'Noma' : (&mod ? 'Mod' : 'Default')))
	return ''
endfunction
```

Then you will get a very simple statusline that changes the color of `%f` (the buffer's "file" name) to *red* if the buffer is *read-only* (`&ro`), *magenta* if the buffer is *non-modifiable* (`!&ma`), *blue* if the buffer is *modified* (`&mod`), or *green* if none of those are true.

Then, if you do something like `vim +vnew +setl\ ro +new +setl\ noma +wincmd\ t +new +setl\ mod`, you will see **4** different colors in each of the 4 windows even though they all use the same highlight group. (UPDATE) Indeed, if you navigate to each window and run `:hi StlBufname` in each of them, the highlights are different.

To be honest, I like how it works; I don't know how it works, but I like how it works. But I am wondering how and why it works, and if it is a stable "feature".

Thanks

### Update

I was messing around with `:hi-link`, and it seems to be window-specific, which differs from `:hi`. But this doesn't seem to be documented, and I am still a little confused.

---

Somewhat surprisingly, this works, as well.

```vim
let g:StlBufname = {
\	'Ro'      : 'guifg=#f2777a ctermfg=1  guibg=#515151 ctermbg=8',
\	'Noma'    : 'guifg=#cc99cc ctermfg=5  guibg=#515151 ctermbg=8',
\	'Mod'     : 'guifg=#6699cc ctermfg=4  guibg=#515151 ctermbg=8',
\	'Default' : 'guifg=#99cc99 ctermfg=2  guibg=#515151 ctermbg=8',
\}
set stl=%#StlBufname#%f%{PostStl()}
function! PostStl()
	exe 'hi StlBufname '.g:StlBufname[&ro ? 'Ro' : (!&ma ? 'Noma' : (&mod ? 'Mod' : 'Default'))]
	return ''
endfunction
```

(`:hi StlBufname` improperly reports the 4th window's highlight group, but it is corrected when you navigate to a different window.)

**Comment by chrisbra** [comment] 2019-05-06 09:08
so you want local highlighting groups? That is a duplicate of #3576

**Closed as completed by chrisbra** 2019-05-06 09:08 UTC
Labels: duplicate
