### ISSUE TITLE
Incompatibility between Python 2.7.11 and Vim 64 bits on Windows

### ISSUE THREAD

**Issue by micbou** [vim/vim#532] opened 2015-12-15 15:12 UTC
### Description

I am using my own built version of [Vim 64 bits for Windows with python2 support](https://bintray.com/micbou/generic/vim/view#) and I am getting the following error when running python2 inside Vim 

```
E887: Sorry, this command is disabled, the Python's site module could not be loaded.
```

with [python 2.7.11 64 bits](https://www.python.org/ftp/python/2.7.11/python-2.7.11.amd64.msi). I don't have this issue with the previous version (2.7.10) of Python.
### How to reproduce

Install [Vim 7.4.972 64 bits for Windows](https://bintray.com/artifact/download/micbou/generic/vim7.4.972-x64.exe) and [python 2.7.11 64 bits](https://www.python.org/ftp/python/2.7.11/python-2.7.11.amd64.msi) on Windows 7 64 bits.
Start Vim:

```
vim -N -u NONE
```

and run the command:

```
:py 1
```
### Configuration details

In a shell:

``` sh
$ python
Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

``` sh
$ vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Dec 13 2015 17:01:30)
MS-Windows 64-bit console version
Included patches: 1-972
Compiled by micbou <contact@micbou.com>
Huge version without GUI.  Features included (+) or not (-):
+acl             +eval            +mouse           +syntax
+arabic          +ex_extra        -mouseshape      +tag_binary
+autocmd         +extra_search    +multi_byte      +tag_old_static
-balloon_eval    +farsi           +multi_lang      -tag_any_white
-browse          +file_in_path    -mzscheme        -tcl
++builtin_terms  +find_in_path    -netbeans_intg   -tgetent
+byte_offset     +float           +path_extra      -termresponse
+cindent         +folding         -perl            +textobjects
+clientserver    -footer          +persistent_undo +title
+clipboard       +gettext/dyn     -postscript      -toolbar
+cmdline_compl   -hangul_input    +printer         +user_commands
+cmdline_hist    +iconv/dyn       +profile         +vertsplit
+cmdline_info    +insert_expand   +python/dyn      +virtualedit
+comments        +jumplist        +python3/dyn     +visual
+conceal         +keymap          +quickfix        +visualextra
+cryptv          +langmap         +reltime         +viminfo
+cscope          +libcall         +rightleft       +vreplace
+cursorbind      +linebreak       -ruby            +wildignore
+cursorshape     +lispindent      +scrollbind      +wildmenu
+dialog_con      +listcmds        +signs           +windows
+diff            +localmap        +smartindent     +writebackup
+digraphs        -lua             -sniff           -xfontset
-dnd             +menu            +startuptime     -xim
-ebcdic          +mksession       +statusline      -xterm_save
+emacs_tags      +modify_fname    -sun_workshop    -xpm_w32
   system vimrc file: "$VIM\vimrc"
     user vimrc file: "$HOME\_vimrc"
 2nd user vimrc file: "$HOME\vimfiles\vimrc"
 3rd user vimrc file: "$VIM\_vimrc"
      user exrc file: "$HOME\_exrc"
  2nd user exrc file: "$VIM\_exrc"
Compilation: cl -c /W3 /nologo  -I. -Iproto -DHAVE_PATHDEF -DWIN32   -DFEAT_CSCOPE       -DWINVER=0x0500 -D_WIN32_WINNT=0x0500  /Fo.\ObjCYHAMD64/ /Ox /GL -DNDEBUG  /Zl /MT -DFEAT_MBYTE -DDYNAMIC_ICONV -DDYNAMIC_GETTEXT -DFEAT_PYTHON -DDYNAMIC_PYTHON  -DDYNAMIC_PYTHON_DLL=\"python27.dll\" -DFEAT_PYTHON3 -DDYNAMIC_PYTHON3 -DDYNAMIC_PYTHON3_DLL=\"python34.dll\" -DFEAT_HUGE /Fd.\ObjCYHAMD64/ /Zi
Linking: link /RELEASE /nologo /subsystem:console /LTCG:STATUS oldnames.lib kernel32.lib advapi32.lib shell32.lib gdi32.lib  comdlg32.lib ole32.lib uuid.lib /machine:AMD64  /nodefaultlib libcmt.lib  user32.lib      /nodefaultlib:python27.lib /nodefaultlib:python34.lib      /PDB:vim.pdb -debug
```

In Vim:

```
:echo has('python')
1
```

**Comment by micbou** [comment] 2015-12-15 15:27
I can confirm that this is specific to the python 64 bits version. It works fine with Vim 32 bits and python 2.7.11 32 bits. Maybe it should be reported to the python folks?

**Comment by k-takata** [comment] 2015-12-15 17:25
Maybe same as #526?

**Comment by chrisbra** [comment] 2015-12-15 19:39
closing as duplicate of #526

**Closed as completed by chrisbra** 2015-12-15 19:39 UTC
