### ISSUE TITLE
Parsing error with heredoc that contains keywords such as change, append, insert, etc.

### ISSUE THREAD

**Issue by wookayin** [vim/vim#9074] opened 2021-10-31 22:33 UTC
### Steps to reproduce

```
$ vim -u NONE
:source foo.vim
```

foo.vim:
```
function RunLua() abort
lua<<EOF
local foo = {
    change = {},
    insert = {},
    append = {},
}
EOF
endfunction
```

### What happens:

(neovim nightly, vim 8.2.0000)
```
E126: Missing :endfunction
```

(or in recent versions, in my env: vim 8.2.3550)
```
E1145: Missing heredoc end marker: .
```

### Expected behaviour

The heredoc block should run without any errors -- even if the heredoc script contains a word like `change`, `append`, `insert`, etc. Those words are some kind of special directives (see `:lua-heredoc`) but they impact on parsing `function ... endfunction` blocks.

### Operating system

macOS

### Version of Vim

Vim 8.2 and Nightly (8.2.3550)

### Logs and stack traces

See https://github.com/neovim/neovim/issues/16136 for the downstream issue on Neovim. I believe this is a vim bug.

Implementation of parsing heredoc: https://github.com/vim/vim/blob/master/src/userfunc.c#L940

**Comment by vim-ml** [comment] 2021-11-06 01:26
Hi,

I am not able to reproduce this problem with the latest version of Vim
(with one minor modification
described below). Can you try to reproduce this problem with the latest
version of Vim?

On Sun, Oct 31, 2021 at 3:33 PM Jongwook Choi ***@***.***>
wrote:

> Steps to reproduce
>
> $ vim -u NONE
> :source foo.vim
>
> foo.vim:
>
> function RunLua() abort
> lua<<EOF
>
>
You should add a space around "<<".

- Yegappan


>
> local foo = {
>     change = {},
>     insert = {},
>     append = {},
> }
> EOF
> endfunction
>
> What happens:
>
> E126: Missing :endfunction
>
> Expected behaviour
>
> The heredoc block should run without any errors -- even if the heredoc
> script contains a word like change, append, insert, etc. Those words are
> some kind of special directives (see :lua-heredoc) but they impact on
> parsing function ... endfunction blocks.
> Operating system
>
> macOS
> Version of Vim
>
> Vim 8.2 and Nightly
> Logs and stack traces
>
> See https://github.com/neovim/neovim/issues/16136 for the downstream issue on Neovim. I believe this is a vim bug.
>
> Implementation of parsing heredoc: https://github.com/vim/vim/blob/master/src/userfunc.c#L940
>
>
>

**Comment by zeertzjq** [comment] 2021-11-06 02:31
Indeed, when `lua<<EOF` is changed to `lua <<EOF` the error can no longer be reproduced in either Vim or Nvim.

**Comment by zeertzjq** [comment] 2021-11-06 02:33
And this is also what the documentation says:
```
:[range]lua << [endmarker]
{script}
{endmarker}
```

**Comment by chrisbra** [comment] 2021-11-06 07:27
closing then.

**Closed as completed by chrisbra** 2021-11-06 07:27 UTC
