### ISSUE TITLE
syntax match does not work in terminal mode

### ISSUE THREAD

**Issue by antoinemadec** [vim/vim#6614] opened 2020-08-03 21:50 UTC
**Describe the bug**
In a terminal, **syntax match** does not have any effect in **terminal** mode, but it does in **normal** mode.

**To Reproduce**
1. `vim --clean`
2. `:terminal`
3. Type '\<C-\\>\<C-n>'
4. `:syntax match Comment /.*/` ; everything is correctly highlighted as Comment
5. press `i` to go back to terminal mode, all the highlights are gone

**Expected behavior**
We should see the same highlights in **terminal** model as in other modes in a terminal.

**Screenshots**
With my colorful PS1, after `syntax match Comment /.*/`:
- normal mode in terminal - highlights can be seen:
![highlight_term_normal](https://user-images.githubusercontent.com/10830594/89230456-2e7e5d00-d598-11ea-8e85-f35d13438172.png)
- terminal mode in terminal - highlights cannot be seen anymore:
![highlight_term_terminal](https://user-images.githubusercontent.com/10830594/89230466-30e0b700-d598-11ea-9eb3-9680b1fadbac.png)

**Environment (please complete the following information):**
 - Vim version
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Aug  3 2020 14:36:38)
Included patches: 1-1360
```
 - OS: debian testing
 - Terminal: alacritty, also true in GUI

**Comment by bfrg** [comment] 2020-08-03 22:29
Related #5327.

**Comment by chrisbra** [comment] 2020-08-04 06:41
seems to be a duplicate of #5327, so closing.

**Closed as completed by chrisbra** 2020-08-04 06:41 UTC
Labels: duplicate
