### ISSUE TITLE
Register "1 content changes also when another register was specified

### ISSUE THREAD

**Issue by ramele** [vim/vim#2346] opened 2017-11-18 04:18 UTC
Register 1 contains the last deleted text also when specifying another register ("xdd). This is not according to the help and yank behavior:

   "Numbered register 0 contains the text from the most recent yank command, unless the command specified another register with ["x].
   Numbered register 1 contains the text deleted by the most recent delete or change command, unless the command specified another register"

**Comment by vim-ml** [comment] 2017-11-18 04:28
On Sat, Nov 18, 2017 at 5:19 AM, ramele <vim-dev-github@256bit.org> wrote:
> Register 1 contains the last deleted text also when specifying another
> register ("xdd). This is not according to the help and yank behavior:
>
> "Numbered register 0 contains the text from the most recent yank command,
> unless the command specified another register with ["x].
> Numbered register 1 contains the text deleted by the most recent delete or
> change command, unless the command specified another register"

Do you have clear steps to reproduce?

Note that according to the help, movement commands %, (, ), `, /, ?,
n, N, { and } always use register 1, possibly _in addition_ to any
register explicitly specified — or that is how I understand the text;
it is admittedly not crystal-clear.

Best regards,
Tony.

**Comment by ramele** [comment] 2017-11-18 05:28
Steps to reproduce:

call setline(1, ['line1', 'line2'])
dd  "delete line1
"add  "delete line2
:reg 1a

--- Registers ---
"1   line2^J
"a   line2^J

Thanks,
Ramel

**Comment by chrisbra** [comment] 2017-11-18 15:54
isn't that expected behaviour?

**Comment by rlue** [comment] 2017-11-20 08:33
I don't think it strictly follows a careful reading of the documentation. I've copied the whole "numbered registers" section below for completeness, but apart from one phrase already copied by @ramele (marked in bold), the only relevant part is the last paragraph (also marked in bold):

> ### 2. Numbered registers "0 to "9
>
> Vim fills these registers with text from yank and delete commands.
>
> Numbered register 0 contains the text from the most recent yank command, unless the command specified another register with ["x].
>
> Numbered register 1 contains the text deleted by the most recent delete or change command, **unless the command specified another register** or the text is less than one line (the small delete register is used then).  An exception is made for the delete operator with these movement commands: `%`, `(`, `)`, `` ` ``, `/`, `?`, `n`, `N`, `{` and `}`.  Register "1 is always used then (this is Vi compatible).  The "- register is used as well if the delete is within a line. Note that these characters may be mapped.  E.g. `%` is mapped by the matchit plugin.
>
> **With each successive deletion or change, Vim shifts the previous contents of register 1 into register 2, 2 into 3, and so forth, losing the previous contents of register 9.**
>
> {Vi: numbered register contents are lost when changing files; register 0 does not exist}

In my own experimentation, it appears that the first bolded phrase and the behavior of vim are not consistent with one another.

**Comment by ramele** [comment] 2017-11-20 11:06
Thanks @rlue for clarifying this. Also, note that yank behavior does follow the documentation ("xyy does not override register "0) so there is inconsistency between yank and delete/change.

**Comment by csarath** [comment] 2019-03-06 21:16
Can I take this up? I'm new to contribution for open source. This looks to be good first issue.

**Comment by andymass** [comment] 2019-03-07 01:43
Evidently vi behaves the same as vim here, so if it were changed it would probably be put behind a `cpoptions` flag (maybe `cpo+=1`?).  I personally think this is OK, but @csarath be aware there is a fair chance your work doesn't get merged in this case due to resistance to changing old behavior or adding new options.  If you are still interested, you could create a PR and be sure to include tests.

**Closed as completed** 2019-03-10 19:03 UTC
