### ISSUE TITLE
`set cursorline` makes code syntax colors gone

### ISSUE THREAD

**Issue by NoahELE** [vim/vim#9617] opened 2022-01-24 08:12 UTC
### Steps to reproduce

1. open any file with syntax color highlightings
2. use `set cursorline`
3. that line is highlighted but the syntax colors are gone, and all words on that line are white.

### Expected behaviour

cursorline should only highlight the backgroud a little to inform user of the line that the cursor is on, and should not make the syntax colors gone.

### Version of Vim

8.2.4198

### Environment

Windows 11, windows terminal

**Comment by chrisbra** [comment] 2022-01-24 08:55
that sounds more like a problem with your colorscheme

**Comment by NoahELE** [comment] 2022-01-24 08:58
> that sounds more like a problem with your colorscheme

I thought it was a problem with vim as I also use neovim with the same config and curline worked fine on nvim.

**Comment by NoahELE** [comment] 2022-01-24 09:04
I test it and find something really weird.

default colorscheme does not have the problem

![image](https://user-images.githubusercontent.com/49080986/150752318-1b6cc996-7b49-4700-b61f-d56d7a3c0750.png)

but nearly all other colorscheme including the preinstalled ones like `desert` and `industry` do have the problem.

![image](https://user-images.githubusercontent.com/49080986/150752646-28620176-1bbb-49d9-9700-8bc5f6883dea.png)

**Comment by chrisbra** [comment] 2022-01-24 10:04
related discussion on vim-dev: https://groups.google.com/g/vim_dev/c/e6puIxRP2gI/m/Q4XUxSDpAgAJ?pli=1

**Comment by brammool** [comment] 2022-01-24 11:57
This must be a problem in your configuration.  I can set the cursorline background and the syntax highlighting is clearly visible.

**Comment by habamax** [comment] 2022-01-24 12:18
> This must be a problem in your configuration. I can set the cursorline background and the syntax highlighting is clearly visible.

It is actually not.

The issue is **windows** cmd.exe + `set termguicolors` + a colorscheme that defines a `Normal` highlight group.

It is easily reproducible as I mentioned in a vim_dev thread:

0. on a `cmd.exe` run `vim -Nu NONE`
1. `set termguicolors`
2. `colo industry` (or any other that defines `Normal` hl)
3. `set ft=vim`
4. `syntax on`
5. `iecho "hello world"`
6. `set cursorline`

industry

![image](https://user-images.githubusercontent.com/234774/150781042-b845a4ed-9f7d-49ef-bbe0-65535abbffde.png)

peachpuff

![image](https://user-images.githubusercontent.com/234774/150781553-58d43d18-7c3b-4bef-9743-81f7ae138b5a.png)

**Comment by habamax** [comment] 2022-01-24 12:46
Just to make it clear, I have never experienced this issue except 

1. windows command line (either cmd.exe, powershell.exe, new windows terminal) 
2. with `set termguicolors` 
3. and a colorscheme that defines `Normal` highlight group.

For me there is no issue for GVIM, OSX homebrewed vim, macvim, debian wsl vim.

**Comment by brammool** [comment] 2022-01-24 13:04
Hmm, so this is only a problem in the MS-Windows console?

**Comment by habamax** [comment] 2022-01-24 13:15
> Hmm, so this is only a problem in the MS-Windows console?

Yes, indeed!

**Comment by chrisbra** [comment] 2022-04-29 11:29
duplicate of #10241 let me close this one here.

**Closed as completed by chrisbra** 2022-04-29 11:29 UTC
Labels: platform-windows
