### ISSUE TITLE
JavaScript - comment inside string causing indentation problem inside switch statement

### ISSUE THREAD

**Issue by dylan-chong** [vim/vim#877] opened 2016-06-20 03:15 UTC
If you have a `/*` inside a string (in a JavaScript file) and then have a
switch statement somewhere below that string, the indenting will stuff up (when
using `gg=G`. See the two screenshots (string with `/*` is on line 12);

Code file with the bug: 
[gulpfile.js.zip](https://github.com/vim/vim/files/322681/gulpfile.js.zip)

Here, all is fine when I run the indent command.
<img width="771" alt="fine without star comment" src="https://cloud.githubusercontent.com/assets/17482349/16182365/5a68efee-36f9-11e6-8780-d9e6d364e546.png">

Now that there is a `/*` on line 12 inside the string, running the indent command will cause the switch statement to be indented crazily.
<img width="799" alt="bad with star comment caused by line 12" src="https://cloud.githubusercontent.com/assets/17482349/16182364/5a1df1c4-36f9-11e6-98c6-53dcbce8d429.png">

**Comment by chrisbra** [comment] 2016-06-20 09:22
I suppose you use the indent/javascript.vim file? please contact the indent script maintainer and discuss the issue with him.
Oh, the maintainer line looks weird. Also it seems to be an inssue with cindent, so perhaps it's not a runtime file issue but rather a bug? Don't know.

@brammool Do you know, who is the maintainer of that file?

**Comment by brammool** [comment] 2016-06-20 11:05
Dylan Chong wrote:

> If you have a `/*` inside a string (in a JavaScript file) and then
> have a switch statement somewhere below that string, the indenting
> will stuff up (when using `gg=G`. See the two screenshots (string with
> `/*` is on line 12);

Can you please include the text?  Preferably a short example.
Can't reproduce from a screenshot.

## 

hundred-and-one symptoms of being an internet addict:
117. You are more comfortable typing in html.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by dylan-chong** [comment] 2016-06-21 22:50
@brammool the file is linked in the original post [gulpfile.js.zip](https://github.com/vim/vim/files/322681/gulpfile.js.zip)

**Comment by dylan-chong** [comment] 2016-06-21 22:57
@chrisbra It seems I have a indent/javascript.vim under vim-polyglot. I will contact him when I get the chance

**Comment by chrisbra** [comment] 2016-06-22 06:54
closing then.

**Closed as completed by chrisbra** 2016-06-22 06:54 UTC

**Comment by dylan-chong** [comment] 2016-06-29 07:06
I have removed the plugin that had the javascript.vim file, now I get a
different indenting result. The the code will look like this:

```
    var x = '/*';
           function test() {
           switch (x) {
           case 0:
           break;
           case 1:
           break;
           default:
           break;
           }
```
