### ISSUE TITLE
"Ctrl+o u" in Insert mode is performed with about 4 seconds delay

### ISSUE THREAD

**Issue by AntonSamokat** [vim/vim#14947] opened 2024-06-09 13:51 UTC
### Steps to reproduce

Write something in Insert mode. Then try to undo with `Ctrl+o u`. Insert mode will be returned only after about 4 seconds delay.
Related closed bug report for `nvim`: ["Ctrl+o u" in Insert mode is performed with a delay if 'showmode' is on](https://github.com/vim/vim/issues/3125)

### Expected behaviour

Expected behavior is without such delay.

### Version of Vim

VIM - Vi IMproved 8.1 (2018 May 18, compiled Dec 07 2023 15:42:49)

### Environment

Ubuntu 20.04
bash
echo $TERM is xterm-256color

### Logs and stack traces

```shell
vim --version
VIM - Vi IMproved 8.1 (2018 May 18, compiled Dec 07 2023 15:42:49)
Included patches: 1-213, 1840, 214-579, 1969, 580-1848, 4975, 5023, 2110, 1849-1854, 1857, 1855-1857, 1331, 1858, 1858-1859, 1873, 1860-1969, 1992, 1970-1992, 2010, 1993-2068, 2106, 2069-2106, 2108, 2107-2109, 2109-2111, 2111-2112, 2112-2269, 3612, 3625, 3669, 3741, 1847
Modified by team+vim@tracker.debian.org
Compiled by team+vim@tracker.debian.org
Huge version with GTK3 GUI.  Features included (+) or not (-):
+acl               -farsi             -mouse_sysmouse    -tag_any_white
+arabic            +file_in_path      +mouse_urxvt       +tcl
+autocmd           +find_in_path      +mouse_xterm       +termguicolors
+autochdir         +float             +multi_byte        +terminal
-autoservername    +folding           +multi_lang        +terminfo
+balloon_eval      -footer            -mzscheme          +termresponse
+balloon_eval_term +fork()            +netbeans_intg     +textobjects
+browse            +gettext           +num64             +textprop
++builtin_terms    -hangul_input      +packages          +timers
+byte_offset       +iconv             +path_extra        +title
+channel           +insert_expand     +perl              +toolbar
+cindent           +job               +persistent_undo   +user_commands
+clientserver      +jumplist          +postscript        +vartabs
+clipboard         +keymap            +printer           +vertsplit
+cmdline_compl     +lambda            +profile           +virtualedit
+cmdline_hist      +langmap           -python            +visual
+cmdline_info      +libcall           +python3           +visualextra
+comments          +linebreak         +quickfix          +viminfo
+conceal           +lispindent        +reltime           +vreplace
+cryptv            +listcmds          +rightleft         +wildignore
+cscope            +localmap          -ruby              +wildmenu
+cursorbind        +lua               +scrollbind        +windows
+cursorshape       +menu              +signs             +writebackup
+dialog_con_gui    +mksession         +smartindent       +X11
+diff              +modify_fname      +sound             -xfontset
+digraphs          +mouse             +spell             +xim
+dnd               +mouseshape        +startuptime       +xpm
-ebcdic            +mouse_dec         +statusline        +xsmp_interact
+emacs_tags        +mouse_gpm         -sun_workshop      +xterm_clipboard
+eval              -mouse_jsbterm     +syntax            -xterm_save
+ex_extra          +mouse_netterm     +tag_binary        
+extra_search      +mouse_sgr         -tag_old_static    
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -Wdate-time  -g -O2 -fdebug-prefix-map=/build/vim-6X01Ez/vim-8.1.2269=. -fstack-protector-strong -Wformat -Werror=format-security -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -Wl,-E  -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim   -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lnsl  -lselinux  -lcanberra -lacl -lattr -lgpm -ldl  -L/usr/lib -llua5.2 -Wl,-E  -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/x86_64-linux-gnu/perl/5.30/CORE -lperl -ldl -lm -lpthread -lcrypt  -L/usr/lib/python3.8/config-3.8-x86_64-linux-gnu -lpython3.8 -lcrypt -lpthread -ldl -lutil -lm -lm -L/usr/lib/x86_64-linux-gnu -ltcl8.6 -ldl -lz -lpthread -lm
```

**Comment by zeertzjq** [comment] 2024-06-09 13:55
The version you are using is 6 years old

**Comment by AntonSamokat** [comment] 2024-06-09 13:57
@zeertzjq By now I have only this old version. Could you please check if this is reproducing on the new version?

**Comment by AntonSamokat** [comment] 2024-06-09 13:59
Related question and comments on `VI SE`: [Undo in insert mode - Vi and Vim Stack Exchange](https://vi.stackexchange.com/a/4558/48864)

**Comment by chrisbra** [comment] 2024-06-09 14:24
closing as unreproducible then.

**Closed as not planned by chrisbra** 2024-06-09 14:24 UTC
Labels: bug

**Comment by AntonSamokat** [comment] 2024-06-11 09:30
@zeertzjq Thanks, also is not reproducing on `Vim 9.0` (now this is latest version for Ubuntu 20.04 in unofficial PPA)
Vim can be updated with:
```
sudo add-apt-repository ppa:jonathonf/vim
sudo apt install vim
```
Source: [How to Install Latest Vim 9.0 on Ubuntu](https://itsfoss.com/install-latest-vim-ubuntu/)

**Comment by chrisbra** [comment] 2024-06-11 09:33
Note: this ppa is no longer updated, since the maintainer passed away. I wouldn't recommend to use it, since you won't get any security updates.

**Comment by AntonSamokat** [comment] 2024-06-11 09:38
@chrisbra Ok, thanks. May be you have some recommendations how to update Vim for Ubuntu 20.04 or more recent versions?

**Comment by chrisbra** [comment] 2024-06-11 09:45
compile your own? Use the vim-appimage? Upgrade your Ubuntu to 22.04 at least? find another ppa (I don't really know any updated and maintained ppas)?

**Comment by AntonSamokat** [comment] 2024-06-11 09:51
@chrisbra I see, thanks
