### ISSUE TITLE
Provide a way to get list of buffers in diff mode / (re)set diff mode

### ISSUE THREAD

**Issue by blueyed** [vim/vim#736] opened 2016-04-07 00:24 UTC
I am seeing the following error from time to time, although only two diff windows are visible:

> E101: More than two buffers in diff mode, don't know which one to use

This might happen when closing a window which had diff mode enabled, and there
appears no way to reset it easily?!

I've seen usage of `getbufvar` in that context, but the following returns all buffers when in a window with `diff` set, and is empty otherwise (although another window is in diff mode):

```
:echo filter(range(1, bufnr('$')), "getbufvar(v:val, '&diff')")
```

Is there a way to see for which buffers `diff` is set?
It could certainly be displayed with the `E101` error (since it can only be 4 (E96)).

It seems like `diffoff!` could provide a way to turn it off, but that appears
to handle windows (and their buffers) only:

```
:diffo[ff]! Switch off diff mode for the current window and in all windows
        in the current tab page where 'diff' is set.  Resetting
        related options only happens in a window that has 'diff' set,
        if the current window does not have 'diff' set then no options
        in it are changed.
```

**Comment by vim-ml** [comment] 2016-04-07 00:46
2016-04-07 3:24 GMT+03:00 Daniel Hahler vim-dev-github@256bit.org:

> I am seeing the following error from time to time, although only two diff
> windows are visible:
> 
> E101: More than two buffers in diff mode, don't know which one to use
> 
> This might happen when closing a window which had diff mode enabled, and
> there
> appears no way to reset it easily?!
> 
> I've seen usage of getbufvar in that context, but the following returns
> all buffers when in a window with diff set, and is empty otherwise
> (although another window is in diff mode):
> 
> :echo filter(range(1, bufnr('$')), "getbufvar(v:val, '&diff')")
> 
> Is there a way to see for which buffers diff is set?

​&diff is window-local option. Your question has no sense, it may not be
set for any buffer. You may get a list of windows in which this option is
set and transform this into a list of buffers displayed in those windows.​

`getbufvar()` is evaluated in the current window context, with different
buffer context. So, of course, your code does not work; but VimL is rather
permissive so it does not work, but as well does not throw any errors. If
you wrote

```
:python for buf in vim.buffers: print(buf.number, buf.options['diff'])
```

you would get KeyError because my python bindings are not that permissive:
you cannot use `options` attribute of `vim.Buffer` instance to get option
that is not buffer-local or buffer-local/global.

**Comment by vim-ml** [comment] 2016-04-07 06:14
On Wed, Apr 06, 2016 at 05:24:36PM -0700, Daniel Hahler wrote:

> I am seeing the following error from time to time, although only two diff windows are visible:
> 
> > E101: More than two buffers in diff mode, don't know which one to use
> 
> This might happen when closing a window which had diff mode enabled, and there
> appears no way to reset it easily?!

I'm convinced there's a bug in vim: sometimes when you switch away/close
a buffer with &diff enabled, vim still thinks there's an active diff for
it.

Internally vim maintains a list of diff-enabled buffers separately from
the buffer/window's own option structures, and these datasets sometimes
somehow get out of sync.  I spent hours trying to track it down with
gdb, but haven't succeeded.

I don't have a recipe for reproducing this -- when this happens, it
always happens unexpectedly in a long editing session when I diff things
and forget do :windo diffoff soon enough.  Luckily it happens rarely.

There's a workaround: you can open a new tab, close the old one, reopen
your windows as you like -- the diff state is reset because every tab
keeps its own diff state.

Regards,

## Marius Gedminas

If you are good, you will be assigned all the work.  If you are real
good, you will get out of it.

**Comment by blueyed** [comment] 2016-04-07 09:54
> Internally vim maintains a list of diff-enabled buffers separately from the buffer/window's own option structures, and these datasets sometimes somehow get out of sync.

Yes, that explains the main issue I'm having, and what I'm trying to get at from VimL.
Could the internal list of diff-enabled buffers be exposed, possibly only read-only?

> `getbufvar()` is evaluated in the current window context, with different buffer context.

Thanks for explaining this.
This means that `getbufvar(b, '&diff')` is the same as just `&diff`?

E.g. the following does not work as expected:
https://github.com/kopischke/vim-stay/blob/89e5a31fcdfd39774945e61144f0022977f13365/autoload/stay.vim#L27

**Comment by kopischke** [comment] 2016-04-07 11:38
@blueyed actually, I think it should be `getwinvar(<winnr>, '&diff')`, as the option is window-local (as is the next one in that function, `&previewwindow`). I’ll fix that in the next _stay_ release.

**Comment by blueyed** [comment] 2016-04-07 21:56
@kopischke 
But that seems to be impossible given that you only have the `bufnr` input there.
You could try to find that buffer in open windows (which is not trivial IIRC), but that still means in the end that you would rather like to have an interface to the internal buffer-is-in-diff-mode list.

**Comment by kopischke** [comment] 2016-04-07 22:24
@blueyed it’s easy for _stay_ as its operation is actually window based, but you are right as to the general usage case. I guess I was just trying to say your issue might be in part caused by the fact that you try to link `&diff` state to a **buffer** instead of a **window** and got sidetracked by the example taken from my plugin. Apologies for taking this OT, and I will leave further discussion to those more familiar with Vim’s diff mode than I am.

**Comment by Grueslayer** [comment] 2017-02-03 16:23
blueyed's question is born to have a workaround for that annoying diff problem. As written in the manual diffoff! runs for "windows" BUT the "buffers" are marked for diff. You can reproduce this like this:

a.txt
~~~
aaa
aaa
aaa
aaa
aaa
aaa
aaa
aaa
aaa
~~~

b.txt
~~~
aaa
aaa
aaa
bbb
bbb
bbb
aaa
aaa
aaa
~~~


c.txt
~~~
aaa
aaa
aaa
aaa
aaa
aaa
ccc
ccc
ccc
~~~

Open a new vim
~~~vim
:set hidden "dont delete buffers when closing windows
:%bd "kill all buffers
:e a.txt "open a.txt
:vert diffsplit b.txt "youll see the inner three lines as diff
:close "window closed, b.txt buffer still exists, diff in a.txt still shown
:diffoff! "window with a.txt no diff mode
:vert diffsplit c.txt "diff a.txt with c.txt --> you will see that a.txt + c.txt AND b.txt are diffed
~~~

So there is a flag on the hidden buffer for b, you can not get rid off with :diffoff!. Only solution so far is
~~~vim
:bufdo diffoff
~~~
But this sucks cause it loads (sofar unloaded buffers) from disc.

I can not imagine any situation where I want to turn off diff mode (using the exclamation mark) to buffers actual "visible" only, my intention is to turn off diff mode to all "available" buffers or maybe better to "all buffers the current buffer is diffed to". I think the current implementation is unusable.

**Closed as completed** 2017-02-03 22:16 UTC

**Comment by blueyed** [comment] 2017-02-03 22:35
Thanks!
