### ISSUE TITLE
Give credit to contributors.

### ISSUE THREAD

**Issue by trusktr** [vim/vim#7574] opened 2020-12-30 02:05 UTC
The contributor graph doesn't look good:

https://github.com/vim/vim/graphs/contributors

That would be the way!

**Comment by dkearns** [comment] 2020-12-30 06:12
Contributors are credited in commit messages.

**Comment by chrisbra** [comment] 2020-12-30 07:55
duplicate of  #1554 and #4518 This is a convention that came with git and the distributed development model. But it is just a convention, not a rule. and the current workflow is typical, if the development has been started by someone that pre-dates the git era. 

Note: that contribution is  always welcome and given in the commit message (and you can see that even if you do not have cloned the repository, but is also recorded in the help).

If you want to suggest a change to how the main contributor works (and possibly makes it harder for him), you may discuss this on the vim-dev mailinglist. But you should have more convincing arguments than to have nice graphs for contributors.

Closing, as this is clearly not a vim issue itself.

**Closed as completed by chrisbra** 2020-12-30 07:55 UTC
Labels: duplicate

**Comment by felipec** [comment] 2020-12-30 13:45
> Contributors are credited in commit messages.

Are they? List all my contributions.

**Comment by Shane-XB-Qian** [comment] 2021-01-05 14:08
https://github.com/vim/vim/issues/4518#issuecomment-754656370

**Comment by Shane-XB-Qian** [comment] 2021-01-05 15:37
https://github.com/vim/vim/issues/7624

**Comment by dstein64** [comment] 2021-06-19 03:58
I noticed that the [Contributors](https://github.com/vim/vim/graphs/contributors) list on GitHub now includes 21 contributors, up from 2 a few months ago.

It appears that the updated approach for merging contributions started with commit bb01a1e on April 26, 2021.
