### ISSUE TITLE
spellchecker is confused by curly apostrophes

### ISSUE THREAD

**Issue by mcepl** [vim/vim#4168] opened 2019-03-25 09:08 UTC
Spellchecker gets confused by using typographic apostrophe (U+2019) instead of incorrect ASCII minute character (U+0027).

Steps to reproduce:

  1. Open a document with phrases like "hasn’t" (where apostrophe is actually U+2019, not U+0027)
  2. Ensure spellchecker is on and `spelllang` is some dialect of English.

Observed:
    ![Snímek z 2019-03-25 08-01-24](https://user-images.githubusercontent.com/198999/54907126-164af800-4ee5-11e9-9477-00a517346e15.png)
The phrase "hasn’t" is marked as spelling error.

Expected:
    It is not a spelling error. vim should replace all curly characters(“ ” „ ‘ ’ ‚) with their pure ASCII equivalents to avoid confusing spellchecker, or something. Obviously change of dictionaries is not a proper solution, because spellchecking is done on many files where keeping the file plain ASCII is completely correct behaviour (programming source code).

This is another take on the problem described in #3747 and of course fixing finally #846 would be also a solution.

Of course, fixing #356 would help as well.

Originally, filed as https://github.com/neovim/neovim/issues/9784 but I got sent here because it is completely shared issue between vim and neovim.

**Comment by chrisbra** [comment] 2019-03-25 09:16
isn't this a duplicate of #3747? Also what's about #356?

**Comment by mcepl** [comment] 2019-03-25 12:33
Well, both of these ask for exactly what I don't think is a good idea: changing dictionaries to work with UTF-8. I think the answer is in smarter algorithm, not in fixing data. And of course, I think the right answer is to revive and finish my PR #2500, but that's probably a lost cause, because of NIH.

**Comment by chrisbra** [comment] 2019-03-25 12:49
Well, I think it depends on the language so it should be part of the dictionary I think. Also I think you are confusing #356 with neovim/neovim#356

I agree #2500 would have been nice.

**Comment by mcepl** [comment] 2019-03-25 13:51
> Well, I think it depends on the language so it should be part of the dictionary I think. Also I think you are confusing #356 with [neovim/neovim#356](https://github.com/neovim/neovim/issues/356)

Right, but that's even more complicated, because there is no unified API for remote plugins and there is actually nothing done about that (#2500 still exists).

And of course, the change of dictionaries (if any), should go other way around … all of them in UTF-8 (which is the only universal encoding universally supported really working in the real life) and able to work with ASCII characters (for legacy purposes and ASCII-only files).

**Comment by mcepl** [comment] 2019-03-25 13:56
> Well, I think it depends on the language so it should be part of the dictionary I think. Also I think you are confusing #356 with [neovim/neovim#356](https://github.com/neovim/neovim/issues/356)

Right, but that's even more complicated, because there is no unified API for remote plugins and there is actually nothing done about that (#2500 still exists).

And of course, the change of dictionaries (if any), should go other way around … all of them in UTF-8 (which is the only universal encoding universally supported really working in the real life) and able to work with ASCII characters (for legacy purposes and ASCII-only files).

https://github.com/vim/vim/issues/3747#issuecomment-476122276 is intriguing: does it mean that code is actually there?

**Comment by brammool** [comment] 2019-03-25 21:21
Matěj Cepl wrote:

> Spellchecker gets confused by using typographic apostrophe (U+2019)
> instead of incorrect ASCII minute character (U+0027).
> 
> Steps to reproduce:
> 
>   1. Open a document with phrases like "hasn’t" (where apostrophe is actually U+2019, not U+0027)
>   2. Ensure spellchecker is on and `spelllang` is some dialect of English.
> 
> Observed:
>     ![Snímek z 2019-03-25 08-01-24](https://user-images.githubusercontent.com/198999/54907126-164af800-4ee5-11e9-9477-00a517346e15.png)
> The phrase "hasn’t" is marked as spelling error.
> 
> Expected:
>     It is not a spelling error. vim should replace all curly characters(“ ” „ ‘ ’ ‚) with their pure ASCII equivalents to avoid confusing spellchecker, or something. Obviously change of dictionaries is not a proper solution, because spellchecking is done on many files where keeping the file plain ASCII is completely correct behaviour (programming source code).
> 
> This is another take on the problem described in #3747 and of course fixing finally #846 would be also a solution.
> 
> Of course, fixing #356 would help as well.

Unicode has a different code for this character, meaning that it is
different from the ASCII character.  There can be various subtle reasons
for this, usually it's because the character has a different meaning in
some language or encoding.

I don't think we should try to implement a generic solution, which no
doubt will be wrong in some cases and has to be fixed later.  Also, it
depends on what quotes the dictionary is using.

The solution is to add the alias to the affix file.  It should map
characters used in text to the character used in the spell file.
Unfortunately I don't know what hunspell uses for this.  Perhaps ICONV,
but I haven't been able to find a specification of what it actually
does or what the syntax is.

-- 
"A clear conscience is usually the sign of a bad memory."
                             -- Steven Wright

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment] 2019-05-06 11:09
closing this as duplicate of #3747

**Closed as completed by chrisbra** 2019-05-06 11:09 UTC
Labels: duplicate
