### ISSUE TITLE
`<amatch>` prepends working directory to file which results in different behavior from `<afile>`

### ISSUE THREAD

**Issue by chaoren** [vim/vim#9184] opened 2021-11-22 03:56 UTC
### Steps to reproduce

1. Open a zip file in Vim.
    ```
    $ echo foo > foo.txt
    $ zip foo.zip foo.txt
      adding: foo.txt (stored 0%)
    $ vim foo.zip
    ```
    This should open `foo.zip` with the bundled zip plugin (the bug here isn't with the zip plugin).
2. Press enter with the cursor on `foo.txt`.

### Expected behaviour

I expect to see the contents of `foo.txt`:
```
foo
```
but instead, I get an empty buffer.

If I edit `/usr/share/vim/vim82/plugin/zipPlugin.vim` (I actually copied it to `~/.vim/plugin/` first) and change
```vim
  au BufReadCmd   zipfile:*/*   call zip#Read(expand("<amatch>"), 1)
```
to
```vim
  au BufReadCmd   zipfile:*/*   call zip#Read(expand("<afile>"), 1)
```
then the plugin will behave as expected.

But according to documentation:
```
                                                        :<afile> <afile>
        <afile>    When executing autocommands, is replaced with the file name
                   of the buffer being manipulated, or the file for a read or
                   write.  E495
                                                        :<amatch> <amatch>
        <amatch>   When executing autocommands, is replaced with the match for
                   which this autocommand was executed.  E497
                   It differs from <afile> only when the file name isn't used
                   to match with (for FileType, Syntax and SpellFileMissing
                   events).
```
`<afile>` and `<amatch>` should behave exactly the same when the matching is done on the file name.

If I add these autocmds to `zipPlugin.vim`:
```vim
  au BufReadCmd   zipfile:*/*   echomsg "<amatch>" expand("<amatch>")
  au BufReadCmd   zipfile:*/*   echomsg "<afile>" expand("<afile>")
```
and try to open `foo.txt` in `foo.zip` again, I get these messages:
```
<amatch> /home/chaoren/zipfile:/home/chaoren/foo.zip::foo.txt
<afile> zipfile:/home/chaoren/foo.zip::foo.txt
```
It seems `<amatch>` is prepending the current working directory when it shouldn't.

I think either
1. the documentation on `<amatch>` should be updated and `zipPlugin.vim` should be changed to use `<afile>` instead of `<amatch>`, or
2. `<amatch>`'s behavior should be fixed.

### Operating system

Linux 5.15.3.arch1-1

### Version of Vim

```
$ vim --version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Nov 09 2021 19:35:34)
Included patches: 1-3582
```

### Logs and stack traces

*No response*

**Comment by brammool** [comment] 2021-11-22 11:41
I cannot reproduce, I do get a buffer with the contents of foo.txt.

**Comment by lacygoill** [comment] 2021-11-22 12:15
I can't reproduce either.  It might be a duplicate of https://github.com/vim/vim/issues/8974 and https://github.com/vim/vim/issues/9108 which were fixed a few days ago in an [update of the runtime files](https://github.com/vim/vim/commit/519cc559b08b800edc429688aece7ad6a00d41eb#diff-c3431e35dce9ef0098df28d227c4539fc744a55e32dca0291be3eeddab0fe245).  For reference, I think the latter happened right before 8.2.3605.

---

Although, maybe the help should document one difference between `<amatch>` and `<afile>`.  When the autocmd pattern is matched against a filename, `<amatch>` gives an absolute  path, by prepending the current working directory, while `<afile>` only gives a file name:
```vim
autocmd BufEnter * echomsg [expand('<amatch>'), expand('<afile>'), expand('<amatch>') ==# expand('<afile>')]
edit file
```
    ['/home/lgc/file', 'file', false]
```diff
diff --git a/runtime/doc/cmdline.txt b/runtime/doc/cmdline.txt
index bf6102487..d29270c6f 100644
--- a/runtime/doc/cmdline.txt
+++ b/runtime/doc/cmdline.txt
@@ -919,9 +919,11 @@ Note: these are typed literally, they are not special keys!
 							*:<amatch>* *<amatch>*
 	<amatch>   When executing autocommands, is replaced with the match for
 		   which this autocommand was executed.  *E497*
-		   It differs from <afile> only when the file name isn't used
-		   to match with (for FileType, Syntax and SpellFileMissing
-		   events).
+		   It differs from <afile> when the file name isn't used to
+		   match with (for example for FileType, Syntax and
+		   SpellFileMissing events).  When the autocmd pattern is
+		   matched against a file name, <amatch> prepends the current
+		   working directory, but not <afile>.
 							*:<sfile>* *<sfile>*
 	<sfile>    When executing a ":source" command, is replaced with the
 		   file name of the sourced file.  *E498*
```

**Comment by chaoren** [comment] 2021-12-04 12:51
Yes, it's the same as those previous issues. Sorry for the dupe. I'll leave this open if you still want to change the documentation.

**Comment by brammool** [comment] 2021-12-04 14:21
I'll add a note in the help.

**Closed as completed by brammool** 2021-12-04 14:21 UTC
