### ISSUE TITLE
Swap files that match the stored file should be automatically removed and replaced.

### ISSUE THREAD

**Issue by schveiguy** [vim/vim#4243] opened 2019-04-12 14:57 UTC
**Is your feature request related something that is currently hard to do? Please describe.**
Sometimes my computer crashes, and I have several vim windows open. This leaves my code base littered with .swp files. In order to remove them, I have to open each one, hit recover. The most often result is that the stored file matches the swap file contents. It suggests you "might want to delete the .swp file" or something. Cool, now I do that from the command line. But why can't vim take this action itself?

**Describe the solution you'd like**
If the swap file is determined to be identical to the stored file, do not bug me. Just delete the swap file, and recreate it anew. I believe all this can be figured out without any action from me.

**Describe alternatives you've considered**
Alternatives:
1. Still ask to recover, but delete the swap file for me when it's the same (or give me the option to) instead of making me delete it by hand.
2. A command line tool to remove all "trivial" swap files in a directory subtree.

**Additional context**
None, everyone is familiar with this feature who uses vim.

**Comment by chrisbra** [comment] 2019-04-15 08:44
duplicate of #1237

**Closed as completed by chrisbra** 2019-04-15 08:44 UTC
Labels: enhancement
