### ISSUE TITLE
:terminal command (without arguments) non-functional on FreeBSD 12

### ISSUE THREAD

**Issue by ov2k** [vim/vim#4290] opened 2019-04-21 22:13 UTC
This occurs on a fresh install of FreeBSD 12, installed with default settings wherever possible. It affects the vim-console package (8.1.985) and a source build (8.1.1198).

Invoking the `:terminal` command with no options or arguments seems to be non-functional.  A split is opened and the status line indicates `!/bin/sh [running]`.  However, no prompt is given and it is unresponsive to simple inputs.  Inputs intercepted by vim (e.g., `ctrl+w :`) seem to work as expected.  Checking `:!ps -U "$(id -u)" -l` shows a running `/bin/sh` process.

**Comment by brammool** [comment] 2019-04-23 17:08
This works for everybody, there must be something wrong in your setup.
It's most likely not a bug in Vim, therefore closing.

**Closed as completed by brammool** 2019-04-23 17:08 UTC

**Comment by ov2k** [comment] 2019-04-25 02:10
I've documented the (lack of) setup in #4289, which I now think is likely related.
