### ISSUE TITLE
Cannot apply autocmd BufNew for help file

### ISSUE THREAD

**Issue by hungpham3112** [vim/vim#9812] opened 2022-02-15 08:46 UTC
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled May  2 2021 18:02:30)
MS-Windows 32-bit console version
Included patches: 1-2824
Compiled by mool@tororo
Huge version without GUI.  Features included (+) or not (-):
+acl                +comments           +find_in_path       +listcmds           +popupwin           -sun_workshop       +vertsplit
+arabic             +conceal            +float              +localmap           -postscript         +syntax             +virtualedit
+autocmd            +cryptv             +folding            -lua                +printer            +tag_binary         +visual
+autochdir          +cscope             -footer             +menu               +profile            -tag_old_static     +visualextra
+autoservername     +cursorbind         +gettext/dyn        +mksession          -python             -tag_any_white      +viminfo
-balloon_eval       +cursorshape        -hangul_input       +modify_fname       -python3            -tcl                +vreplace
+balloon_eval_term  +dialog_con         +iconv/dyn          +mouse              +quickfix           +termguicolors      +vtp
-browse             +diff               +insert_expand      -mouseshape         +reltime            +terminal           +wildignore
++builtin_terms     +digraphs           +ipv6               +multi_byte_ime/dyn +rightleft          -termresponse       +wildmenu
+byte_offset        -dnd                +job                +multi_lang         -ruby               +textobjects        +windows
+channel            -ebcdic             +jumplist           -mzscheme           +scrollbind         +textprop           +writebackup
+cindent            +emacs_tags         +keymap             -netbeans_intg      +signs              -tgetent            -xfontset
+clientserver       +eval               +lambda             +num64              +smartindent        +timers             -xim
+clipboard          +ex_extra           +langmap            +packages           +sound              +title              -xpm_w32
+cmdline_compl      +extra_search       +libcall            +path_extra         +spell              -toolbar            -xterm_save
+cmdline_hist       -farsi              +linebreak          -perl               +startuptime        +user_commands      
+cmdline_info       +file_in_path       +lispindent         +persistent_undo    +statusline         +vartabs            
   system vimrc file: "$VIM\vimrc"
     user vimrc file: "$HOME\_vimrc"
 2nd user vimrc file: "$HOME\vimfiles\vimrc"
 3rd user vimrc file: "$VIM\_vimrc"
      user exrc file: "$HOME\_exrc"
  2nd user exrc file: "$VIM\_exrc"
       defaults file: "$VIMRUNTIME\defaults.vim"
Compilation: cl -c /W3 /GF /nologo  -I. -Iproto -DHAVE_PATHDEF -DWIN32  -DFEAT_CSCOPE -DFEAT_TERMINAL -DFEAT_SOUND  -DFEAT_JOB_CHANNEL -DFEAT_IPV6      -DWINVER=0x0501 -D_WIN32_WINNT=0x0501 /source-charset:utf-8 /MP -DHAVE_STDINT_H /Ox /GL -DNDEBUG /arch:IA32 /Zl /MT /D_CRT_SECURE_NO_DEPRECATE /D_CRT_NONSTDC_NO_DEPRECATE -DFEAT_MBYTE_IME -DDYNAMIC_IME -DDYNAMIC_ICONV -DDYNAMIC_GETTEXT -DFEAT_HUGE /Fd.\ObjCi386/ /Zi
Linking: link  /nologo /opt:ref /LTCG:STATUS oldnames.lib kernel32.lib advapi32.lib shell32.lib gdi32.lib  comdlg32.lib ole32.lib netapi32.lib uuid.lib /machine:i386   libcmt.lib  user32.lib          winmm.lib WSock32.lib Ws2_32.lib  /PDB:vim.pdb -debug

```

I'm using [vim-autoresize](https://github.com/kovetskiy/vim-autoresize) for resize focused buffer.

```
augroup autoresize
    autocmd!
    autocmd BufNew * call autoresize#resize()
augroup END
```

BufNew works fine for all buffer except help file. I don't know why I can't apply affect to help file. How to solve this problem?

**Comment by brammool** [comment] 2022-02-21 17:46
When I try this I can see the BufNew autocommand triggered also for help buffers.

**Comment by hungpham3112** [comment] 2022-02-22 03:56
Oh, I found the issue in here, because this line:

    autocmd BufWinEnter * if &buftype == 'help' | wincmd L | endif

I used it for opening vertical help file, but it incompatible with this plugin, I don't know how to mix my config with that, both are autocmd.

**Comment by chrisbra** [comment] 2022-02-22 07:14
so this is an issue with your configuration and those two configurations seem to contradict a bit. 

Please ask user questions on the vim_use mailinglist or use vi.stackexchange.com. This here is a bug tracker for problems with Vim. We cannot provide individual help here. Closing.

**Closed as completed by chrisbra** 2022-02-22 07:14 UTC
Labels: question

**Comment by hungpham3112** [comment] 2022-02-22 08:00
> so this is an issue with your configuration and those two configurations seem to contradict a bit.
> 
> Please ask user questions on the vim_use mailinglist or use vi.stackexchange.com. This here is a bug tracker for problems with Vim. We cannot provide individual help here. Closing.

I believe this is a bug cause by wincmd L because not only this plugin but also lens.vim is broken with 
`autocmd BufWinEnter * if &buftype == 'help' | wincmd L | endif`

You can try to reproduce this with minimal vimrc have autocmd like above and lens.vim. You will see.

**Comment by chrisbra** [comment] 2022-02-22 08:26
If you want to report a bug, please open a new issue and provide a minimal reproducible example and clearly state what is wrong and what you expect.  Don't just mention *it is brocken*

Thanks.

**Comment by hungpham3112** [comment] 2022-02-22 09:41
> If you want to report a bug, please open a new issue and provide a minimal reproducible example and clearly state what is wrong and what you expect. Don't just mention _it is brocken_
> 
> Thanks.

Sorry, I don't know how to say it right because my English is bad. 



> CTRL-W L	Move the current window to be at the far right, using the full
> 		height of the screen.  This works like closing the
> 		current window and then creating another one with
> 		`:vert botright split`, except that the current window
> 		contents is used for the new window.

Like the help file said, `wincmd L` moves the current window but also resize the window, it is unexpected behavior.

It should just move the current window to the left and respect the current width of window.

**Comment by lacygoill** [comment] 2022-02-23 17:15
> Not like the help file said, wincmd L moves the current window but it also resize the window -> unexpected behavior.

The fact that `:wincmd L` resizes the window is documented at [`:help CTRL-W_L`](https://vimhelp.org/windows.txt.html#CTRL-W_L):

                                                    *CTRL-W_L*
    CTRL-W L        Move the current window to be at the far right, using the full
                    height of the screen.  This works like closing the
                    current window and then creating another one with
                    `:vert botright split`, except that the current window
                    contents is used for the new window.

Notice the "using the full height of the screen" part.

> It should just move the current window to the left and respect the current width of window.

Not sure but have a look at the [vim-tradewinds](https://github.com/andymass/vim-tradewinds) plugin, or the [`win_splitmove()`](https://vimhelp.org/builtin.txt.html#win_splitmove%28%29) function.

If you decide to use the plugin, try to find the right sequence of keypresses to move the help window in the position and with the geometry that you want.  For the sake of the example, let's say it's `abcd`.  Then, replace this autocmd:

    autocmd BufWinEnter * if &buftype == 'help' | wincmd L | endif

With this one:

    autocmd BufWinEnter * if &buftype == 'help' | execute 'normal abcd' | endif

---

Just a suggestion, but since we sometimes have questions here, maybe we could open a [discussions forum](https://docs.github.com/en/discussions) on github.  It would allow us to transfer questions out of the issue tracker.

FWIW, the [fish shell](https://github.com/fish-shell/fish-shell/discussions) has opened one about 4 months ago, and the [kitty terminal](https://github.com/kovidgoyal/kitty/discussions) open theirs about a year ago.

**Comment by chrisbra** [comment] 2022-02-23 17:51
I am fine with enabling discussions.

Personally I just found them to be not so super helpful, because I still get them as notifications in my mail box and think those are issues and only later I notice it. But whatever.

**Comment by hungpham3112** [comment] 2022-02-24 00:25
> 



> > Not like the help file said, wincmd L moves the current window but it also resize the window -> unexpected behavior.
> 
> The fact that `:wincmd L` resizes the window is documented at [`:help CTRL-W_L`](https://vimhelp.org/windows.txt.html#CTRL-W_L):
> 
> ```
>                                                 *CTRL-W_L*
> CTRL-W L        Move the current window to be at the far right, using the full
>                 height of the screen.  This works like closing the
>                 current window and then creating another one with
>                 `:vert botright split`, except that the current window
>                 contents is used for the new window.
> ```
> 
> Notice the "using the full height of the screen" part.
> 
> > It should just move the current window to the left and respect the current width of window.
> 
> Not sure but have a look at the [vim-tradewinds](https://github.com/andymass/vim-tradewinds) plugin, or the [`win_splitmove()`](https://vimhelp.org/builtin.txt.html#win_splitmove%28%29) function.
> 
> If you decide to use the plugin, try to find the right sequence of keypresses to move the help window in the position and with the geometry that you want. For the sake of the example, let's say it's `abcd`. Then, replace this autocmd:
> 
> ```
> autocmd BufWinEnter * if &buftype == 'help' | wincmd L | endif
> ```
> 
> With this one:
> 
> ```
> autocmd BufWinEnter * if &buftype == 'help' | execute 'normal abcd' | endif
> ```
> 
> Just a suggestion, but since we sometimes have questions here, maybe we could open a [discussions forum](https://docs.github.com/en/discussions) on github. It would allow us to transfer questions out of the issue tracker.
> 
> FWIW, the [fish shell](https://github.com/fish-shell/fish-shell/discussions) has opened one about 4 months ago, and the [kitty terminal](https://github.com/kovidgoyal/kitty/discussions) open theirs about a year ago.

Thanks for your answer. I found solution for my issue. Simply:

`autocmd BufWinEnter * if &buftype == 'help' | wincmd L | execute 'vertical resize '. g:autoresize_width |endif`
