### ISSUE TITLE
markdown syntax does not sync correctly

### ISSUE THREAD

**Issue by SwuduSusuwu** [vim/vim#15406] opened 2024-07-31 14:15 UTC
### Steps to reproduce

```
fetch https://raw.githubusercontent.com/SwuduSusuwu/SubStack/8f171c87f868fa753c0879394acfc141fedcc12f/posts/VirusAnalysis.md
vim VirusAnalysis.md
/execves
```

### Expected behaviour

Normal C++ text shows

### Version of Vim

9.1 (June 2024 02)

### Environment

Operating System: Android OS 14
Terminal: Termux
Value of $TERM: xterm-256color
Shell: Bash

**Comment by SwuduSusuwu** [comment] 2024-07-31 14:21
![Termux Markdown C++](https://github.com/user-attachments/assets/1874ac73-667d-43c4-bb9c-9235eab9323a)

**Comment by SwuduSusuwu** [comment] 2024-07-31 14:23
```
cat << EOF > test.md
\```
class s {
    ~s();
}
\```
Example of vim Markdown strikethrough error
\```
class x {
    ~x();
}
\```
EOF
vim test.md
```
shows normal, thus _Vim_ must require huge files (such that `/` goes from top of file -- which does not have code blocks -- through the section with the code blocks) to trigger this.

**Comment by SwuduSusuwu** [comment] 2024-07-31 14:31
GitHub follows the reference Markdown implementation, such that if you browse to https://github.com/SwuduSusuwu/SubStack/blob/8f171c87f868fa753c0879394acfc141fedcc12f/posts/VirusAnalysis.md , press `<Ctrl>+f`, `execves`, `<enter>`, the browser shows this;
![Firefox Markdown C++](https://github.com/user-attachments/assets/4463d502-d93e-4430-ac95-a8ea932526a5)

**Comment by chrisbra** [comment] 2024-07-31 15:05
cannot reproduce. Does  `:syn sync fromstart` fix it?

**Comment by SwuduSusuwu** [comment] 2024-07-31 15:14
```
~ $ cat ~/.vimrc
set nomodeline
set hlsearch
set shiftwidth=2
set tabstop=2
set softtabstop=0 noexpandtab
set bs=indent,eol,start
set whichwrap=<,>,h,l,[,],b
runtime TabComplete "Import ~/.vim/TabComplete
inoremap <expr> <silent> <tab> TabComplete("forward")
inoremap <expr> <silent> <c-tab> TabComplete("backward") "TODO: <c-tab> support
inoremap <expr> <silent> <s-tab> TabComplete("tab")
~ $ cat ~/.vim/Tab complete
function! TabComplete(direction)
	let oldIsk=&isk
	set isk+=(,),,
	let col=col('.')-1
	if "tab" ==a:direction
		return "\<tab>"
	elseif !pumvisible() && (!col || getline('.')[col - 1] !~ '\k')
		return "\<tab>"
	elseif "backward" ==a:direction
		return "\<c-p>"
	elseif "forward" ==a:direction
		return "\<c-n>"
	elseif exists('&omnifunc') && &omnifunc != ''
		return "\<c-x>\<c-o>"
	endif
	set &isk=oldIsk
endfunction
```

**Comment by chrisbra** [comment] 2024-07-31 15:29
see :h ft-markdown-syntax and configure the `minlines` value to something more large.

**Comment by SwuduSusuwu** [comment] 2024-07-31 15:42
`echo "let g:markdown_minlines=200" >> ~/.vimrc` success.
But others who load the _Markdown_ with _Vim_ can have this problem.
Wish _Vim_ defaults to `g:markdown_minlines=200` or fixes the interpretor for use with the small default value.

**Comment by SwuduSusuwu** [comment] 2024-07-31 15:53
Lots have reproduced this, such as: https://vi.stackexchange.com/questions/37309/minlines-in-gvimrc
  https://stackoverflow.com/questions/23458517/vim-folds-out-of-sync-with-syntax-incorrectly-inserted
  https://stackoverflow.com/questions/5917760/vim-sync-syntax-from-beginning-of-file-on-command
  https://vi.stackexchange.com/questions/20989/syntax-highlighting-is-getting-screwed-when-loading-long-markdown-files-on-windo

For personal use, can use fixes. But project is open-source (wish to contribute)
Thus wish that _Vim_'s defaults fix this

**Comment by chrisbra** [comment] 2024-07-31 16:06
This needs to go to the Markdown upstream maintainer. Ping @tpope

**Comment by tpope** [comment] 2024-07-31 16:12
You can open an issue at https://github.com/tpope/vim-markdown. But `minlines` is always a tradeoff. There's no one default that can appease everybody.

**Comment by chrisbra** [comment] 2024-07-31 18:01
closing then. Please take it to the upstream repo then. Thanks!

**Closed as completed by chrisbra** 2024-07-31 18:01 UTC
Labels: bug

**Comment by SwuduSusuwu** [comment] 2024-07-31 18:20
If understood the StackExchange/StackOverflow questions, this does not just affect _Markdown_; unless you use `syn sync fromstart` (or huge `minlines`,) this affects all languages/syntaxes.

**Comment by chrisbra** [comment] 2024-07-31 19:47
That depends on the syntax script used.

**Comment by SwuduSusuwu** [comment] 2024-07-31 20:56
> But `minlines` is always a tradeoff. There's no one default that can appease everybody.

Proposed fix: do not parse Markdown across <backtick>s;
<backtick> (which begins or closes a code block) should have Markdown stop;
Thus <backtick> class s{~s();} <backtick> text <backtick> class x{~x();} <backtick> /
class s{~s();} <backtick> text <backtick> class x{~x();}
must both have the ~ ignored (as the ~ crosses <backtick>s).

The rest of `vim`'s languages/syntaxes should have such fixes.

**Comment by SwuduSusuwu** [comment] 2024-07-31 21:38
Proposed fix 2: post-`/`: `if(1 & context_symbols['<backtick>'].count) { execute("sin sync fromstart" /* or "let g:markdown_minlines 6666" */); }`

The rest of `vim`'s languages/syntaxes should have such fixes;
_Proposed fix 2_ is generalizable to: `for(auto symbol : context_symbols) {if(1 & symbol.count) { execute("sin sync fromstart" /* or "let g:markdown_minlines 6666" */); return; }}`
