### ISSUE TITLE
Mapping <Esc> to CTRL-\_CTRL-N makes terminal non-modifiable

### ISSUE THREAD

**Issue by manasthakur** [vim/vim#2216] opened 2017-10-18 11:00 UTC
As suggested in the docs, I added the following map in my vimrc:
```vim
tnoremap <Esc> <C-\><C-N>
```

The mapping works as said. However, now whenever I try to go up or down the history in the terminal buffer (using the arrow keys), an E21 is thrown. Disabling the map solves the issue.

**Comment by lacygoill** [comment] 2017-10-18 11:56
On my machine, `up` and `down` produce the sequence of keycodes `Esc O A` and `Esc O B`. So, when you press one of these arrows, maybe Vim expands `Esc` into `C-\ C-n`, which makes you enter Terminal-Normal mode, and from this other mode, it may interpret `O` as a command to open a new line above the current one, which is forbidden since the buffer is now non-modifiable.

I didn't think that the remapping of the Escape keycode could be possible when you press the arrow keys, because the keycodes they produce should be received by Vim in less than `&ttimeoutlen` ms (100 ms by default).

I noticed a similar issue. With the mapping you mentioned in your post, all the readline key bindings, using the `Alt` modifier, do not work as expected. This is probably because the first keycode they produce is Escape, like the arrow keys. For example, `M-b` should move the cursor one word backward, while staying in Terminal-Job mode. But with the mapping, it moves back one word and switch to Terminal-Normal mode.

Because of this, you can't navigate across the different words on the command-line with `M-b` and `M-f`, like you could in a terminal outside Vim, because as soon as you press `M-b`, you aren't in Terminal-Job mode anymore.

So far, I haven't found a solution, so I just use 2 Escape in the `lhs` of the mapping:

    tnoremap <esc><esc> <c-\><c-n>

With this mapping, the first Escape produced by the arrow keys and various readline key bindings won't be expanded into `C-\ C-n`. So, they will work as expected, but you will have to hit Escape twice in a terminal buffer, to go from Terminal-Job mode to Terminal-Normal mode.

Edit:

Another solution would be to create another mapping which begins with `Esc`:

    tnoremap <esc>  <c-\><c-n>
    tnoremap <esc>: <c-\><c-n>:

This way, when an arrow key sends an Escape keycode, it can't be immediately expanded into `C-\ C-n`, because there's an ambiguity between the 2 mappings. So, Vim must wait for possible other keycodes.
The arrow keys should work, and a single keypress on Escape should be enough, however, if you don't press anything after Escape, you'll have to wait for the timeout to occur (specifically `&timeoutlen` ms; 1s by default). Also, it doesn't seem to fix the issue with `M-b` and similar keys.

**Comment by manasthakur** [comment] 2017-10-18 12:38
Hi @lacygoill,

Thanks for the explanation. In fact, I like the mapping in your workaround (two `ESC`s) more than the previous one 👍

**Comment by brammool** [comment] 2017-10-19 13:02
Manas Thakur wrote:

> As suggested in the docs, I added the following map in my vimrc:
> ```vim
> tnoremap <Esc> <C-\><C-N>
> ```
> 
> The mapping works as said. However, now whenever I try to go up or
> down the history in the terminal buffer (using the arrow keys), an E21
> is thrown. Disabling the map solves the issue.

Works for me.  Check your settings, is 'timeout' set and otherwise
'ttimeout' set?

-- 
    [clop clop]
MORTICIAN:  Who's that then?
CUSTOMER:   I don't know.
MORTICIAN:  Must be a king.
CUSTOMER:   Why?
MORTICIAN:  He hasn't got shit all over him.
                                  The Quest for the Holy Grail (Monty Python)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by manasthakur** [comment] 2017-10-21 09:47
I have `ttimeoutlen` set to `50`.

**Comment by joshtriplett** [comment] 2018-09-10 01:57
I can confirm the same issue here. If I `:tnoremap <Esc> <C-\><C-N>`, then the arrow keys or any other key that sends an escape sequence starting with `<Esc>` no longer gets passed through to the terminal.

I have `ttimeoutlen=100`.

**Comment by chrisbra** [comment] 2018-09-10 08:14
So what terminal are you using?

**Comment by joshtriplett** [comment] 2018-09-10 12:30
GNOME Terminal 3.30.0 using VTE 0.54.0

**Comment by brammool** [comment] 2020-06-06 13:38
Mapping <Esc> is expected to cause problems.  It may work in some specific situations (e.g. in the GUI), but it if fails then just don't use it.  It's not something that can be fixed in Vim.

**Closed as completed by brammool** 2020-06-06 13:38 UTC

**Comment by ghomem** [comment] 2024-10-11 15:14
My experience with this is.

This workaround works for vim 8.x (Ubuntu 20.04 and 22.04):

```
tnoremap <esc>  <c-\><c-n>
tnoremap <esc>: <c-\><c-n>:
```

whereas this:

```
tnoremap <esc>  <c-\><c-n>
```

works without problems on vim 9.1 (Ubuntu 24.04).

The ability to map this key is ergonomically very interesting.

Thank you @lacygoill for posting this workaround!
