### ISSUE TITLE
Shell syntax highlighting broken in 9.0.1350 vs 9.0.981

### ISSUE THREAD

**Issue by ghost** [vim/vim#12127] opened 2023-03-08 23:32 UTC
### Steps to reproduce

1. Edit a shell script with 9.0.981 (e.g., MacOS). Observe highlighting.
2. Edit the same file with 9.0.1350 (e.g, Homebrew). Observe broken highlighting.

### Expected behaviour

The same highlighting.

### Version of Vim

9.0.1530 (homebrew)

### Environment

Operating System: Macintosh Ventura 13.2.1
Term: iTerm2
Value of $TERM: xterm-256color
Shell: /opt/homebrew

**Comment by k-takata** [comment] 2023-03-09 00:04
Please update to 9.0.1362 or later.
Duplicate of #11937. Closing.

**Closed as completed by k-takata** 2023-03-09 00:04 UTC
Labels: duplicate, runtime, bug
