### ISSUE TITLE
[critical] Timer breaks customized key combo in GVim 8.1.0712

### ISSUE THREAD

**Issue by skywind3000** [vim/vim#3799] opened 2019-01-14 09:31 UTC
Version: GVim 8.1.0712 (downloaded from [vim-win32-installer](https://github.com/vim/vim-win32-installer/releases) )
System: Windows 10 

## Description

the keymap below is used to display a message:

```VimL
let s:index = 0
function! MyFunction()
	echo "index: " . s:index
	let s:index += 1
endfunc
noremap <space><space> :call MyFunction()<cr>
```

It was expected to display a "index: N" message on command line every time you press `<space>` twice in a short time.

But after gvim 8.1.0712, the key combo can't be used in GVim if there is a timer running periodicly, terminal vim works fine.

## Reproduce

timer_bug.vim:

```VimL
set nocompatible
set ruler
set showcmd
set timeout
set timeoutlen=2000

let s:index = 0
function! MyFunction()
	echo "index: " . s:index
	let s:index += 1
endfunc
noremap <space><space> :call MyFunction()<cr>

function! MyTimer(args)
endfunc

if exists('s:timer')
	call timer_stop(s:timer)
endif

let s:timer = timer_start(100, 'MyTimer', {'repeat': -1})
```

step1: start gvim with the script above

```batch
gvim -u timer_bug.vim
```

step2: press `<space>` twice within two seconds, see if there is a message "index: N" displayed in command.

expected result:
gvim displays "index: N" in command line.

actual result:
the keymap is not triggerred in GVim 8.1.0712 but works fine in GVim 8.1.0707

## Demo

![timer_bug](https://user-images.githubusercontent.com/3035071/51104436-1cf02b80-1821-11e9-8eb0-812056c91307.png)

When you type the first `<space>` in GVim 8.1.0712, you can see there is a pending `<20>` command in the right bottom area. but it will disappear immediately when timer triggerred.

So, the first pending `<space>` will be cancelled and the `<space><space>` keymap breaks.

But in GVim 8.1.0707, the first pending `<20>` will last for 2 seconds (timeoutlen) and I have enough time to press another `<20>` and command `<space><space>` can be actived easily.

I have no idea where the bug is.

**Comment by brammool** [comment] 2019-01-14 19:44
This is probably a duplicate of #3417.
However, that was before patch 8.1.0710.

-- 
hundred-and-one symptoms of being an internet addict:
200. You really believe in the concept of a "paperless" office.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Closed as completed** 2019-01-17 13:12 UTC
