### ISSUE TITLE
FocusGained for vim (not only gvim)

### ISSUE THREAD

**Issue by jerome-diver** [vim/vim#5526] opened 2020-01-23 16:43 UTC
Read vim official manual about event FocusGained (:h autocmd and go down to event list) and see what you can hope to get back on focus vim.
In real life, FocusGained event is working fine only for gvim.

Please, make it works also for vim from terminal (tmux, termite, urxvt and other... from any unix/Linux), or maybe if not able to do that, correct the manual to reflect the reality.

**Comment by chrisbra** [comment] 2020-01-23 16:54
I believe this is a duplicate of #609

**Comment by chrisbra** [comment] 2020-01-23 16:58
and according to https://github.com/vim/vim/issues/4359 it seems to be possible by setting the `t_ti` and `t_te` options for some terminals).

**Comment by jerome-diver** [comment] 2020-01-23 18:29
hi @chrisbra and thank you for try to help me.
Do you try the solution at #4359 ? And specialy from insert or any visual mode ?
I try it but from insert or visual mode there is output inside edited text and no FocusGained working out of normal mode.

Also, i think it should be fantastic to get vim option/setting macro/module ready to go by a global vim variable to set for FocusGained / Losted - able (a variable like "terminal_focus_event = 0|1) where all the required code can be loaded.
The idea is to make vim script more comfortable to access this kind of useful event.

**Comment by chrisbra** [comment] 2020-01-24 07:57
IIRC, there was no general solution.

**Comment by jerome-diver** [comment] 2020-01-24 17:51
if there is some use case with no solution, so yes, it can not be a general solution. 
By the time, I read one solution (and also a plugin) who seems to works good for my use case. 
And then i think that if this increase the ability to provide any solution for vim (even if it is not a full general solution), i can not understand that it would not be adopted inside the official vim source code. Because this will decrease the use case with no solution. To do more is better (it is the idea for the logic concept).

**Comment by Konfekt** [comment] 2020-01-26 11:20
Regarding recognizing FocusGained in`urxvt` as mentioned in the opener, here are [instructions](https://artisan.karma-lab.net/creer-plugin-urxvt-sauvegarder-vim-automatiquement) for setting it up and an adaption for `tmux` at https://github.com/majutsushi/etc/commit/4aec766b490c7c522caf224cbc6f329b96ef4577

**Comment by jerome-diver** [comment] 2020-01-26 17:59
@Konfekt thank you very much for your help (i'm also french and the first link helped me a lot to understand).
I also find some great users provide some good solutions (all in vim script) and i'm thinking this solution should interest vim devs to increase vim ability.
[first solution](https://github.com/vim/vim/issues/4359)
[second solution plugin](https://github.com/tmux-plugins/vim-tmux-focus-events)

**Closed as completed** 2021-01-14 16:35 UTC
Labels: enhancement
