### ISSUE TITLE
Vim9: cannot use variables in map()

### ISSUE THREAD

**Issue by itchyny** [vim/vim#7329] opened 2020-11-18 22:08 UTC
**Describe the bug**
In Vim9 script, variables are not seen from map().

**To Reproduce**
Loading following Vim9 script does not work.
```
vim9script

var xs = 'test'
echo map([1], 'xs')   # works
echo map([1], {->xs}) # does not work

def F()
  var ys = 'test'
  echo map([1], 'ys')   # does not work
  echo map([1], {->ys}) # works
enddef
call F()
```

**Expected behavior**
All lines should be work and outputs
```
['test']
['test']
['test']
['test']
```

**Environment (please complete the following information):**
 - Vim version 8.2.2013
 - OS: macOS 10.15.7
 - Terminal: iTerm2

**Comment by lacygoill** [comment] 2020-11-18 23:01
Possible duplicate of https://github.com/vim/vim/issues/6401 and https://github.com/vim/vim/issues/6475 .

See the `Limitations` section at `:h fast-functions`.

---

The bottom line is that you should not use an eval string inside a `:def` function; instead use a lambda which is faster (because compiled).  In decreasing order of performance, you can use:

 - a lambda in a `:def` function
 - an eval string (in a `:def` function or at the script level)
 - a lambda at the script level

---

Besides, a lambda gives you other benefits:

 - the code is easier to read (the syntax highlighting is not shadowed by `vimString`) and write (especially if the expression contains a mix of quotes)

 - you can catch an error earlier (at compile time), if you use invalid types for the arguments

For the latter bullet point, you need the patch [8.2.1956](https://github.com/vim/vim/releases/tag/v8.2.1956).  For example, if you write this:
```vim
vim9script
def Func()
    var Ref = {x: number, y: number -> x + y}
    echo Ref(1, 'x')
enddef
defcompile
```
You'll get this error message:

    E1013: Argument 2: type mismatch, expected number but got string

Notice that the error message also includes the position of the argument whose type needs to be fixed.

**Comment by itchyny** [comment] 2020-11-19 01:57
Thank you, I understand the benefits for lambda. So the point is

- I propose to allow lambda at the script level
  - a code works in a function but not outside is confusing
- I propose to disallow evaluating string in Vim9 script completely, or report the limitation to inform this behavior is not a bug
  - making the type of 2nd arg of map to func is explicit for users.

**Comment by lacygoill** [comment] 2020-11-19 02:17
> I propose to allow lambda at the script level

Lambda already work at the script level, but you need to specify the script-local scope:
```vim
vim9script
var xs = 'test'
echo map([1], {-> xs})   # does not work
echo map([1], {-> s:xs}) # works
```
I think what you want is for Vim to look in the script-local namespace when a variable is not prefixed by an explicit scope and is used in a lambda outside a `:def` function.  I don't know whether there would be a downside, or whether it would bring some inconsistency, but I think it makes sense.  Besides, I always find it a bit weird to have to write `s:` in a Vim9 script, considering you almost never need it anymore.

---

> I propose to disallow evaluating string in Vim9 script completely, or report the limitation to inform this behavior is not a bug

If it is possible to report the limitation, then yes, a more explicit error message would be welcome.
However, I disagree with disallowing an eval string completely; an eval string is still faster at the script level.  Although, one could make the argument that we can always wrap a `map()` inside a `:def` function...

**Comment by lacygoill** [comment] 2020-11-19 02:31
> when a variable is not prefixed by an explicit scope and is used in a lambda outside a :def function

And when the variable is absent from the lambda's arguments.  Basically, you want the script-local namespace to be considered as the outer scope of the lambda, just like the function-local namespace is the outer scope when `map()` is invoked from a `:def` function.  From there, the lambda could automatically access script-level variables, without us having to write `s:`.  Again, I agree; it would be nice if it could work that way.

**Closed as completed** 2020-11-19 20:48 UTC
