### ISSUE TITLE
Openhab Syntax files

### ISSUE THREAD

**Issue by mueller-ma** [vim/vim#1678] opened 2017-05-04 05:17 UTC
The syntax files are under GPL and can be found here: https://github.com/cyberkov/openhab-vim

Can I just copy them and make a PR or do I have to preserve the commit history?

**Comment by chrisbra** [comment] 2017-05-04 06:03
are you the owner of the repository? The ftdetect script looks strange. Why does it set several different filetypes but all are of the same syntax? I think those should all set the filetype to openhub and then we would need an update to filetype.vim with those rules.

**Comment by mueller-ma** [comment] 2017-05-04 06:32
I'm contributer, but not owner.
I didn't create this structure, but I think the different filetypes are set, because all of them belong to openhab, but different syntax applies.

**Comment by chrisbra** [comment] 2017-05-04 07:27
oh I see and the syntax script does different things depending on the filetype. That is a bit unusual, also the filetype names are a bit generic. Can't we use somehting like `oh-items` or `ohitems`?

**Comment by mueller-ma** [comment] 2017-05-04 07:29
I can split them and make a PR, but I dont know if  it will be merged

**Comment by mueller-ma** [comment] 2017-05-04 08:55
https://github.com/cyberkov/openhab-vim/pull/11

**Comment by mueller-ma** [comment] 2017-05-04 09:03
Are non free dependencies a problem? openhab is under EPL, but they recommend Oracle Java instead of openjdk

**Comment by mueller-ma** [comment] 2017-05-04 09:27
I have renamed the filetypes

**Comment by brammool** [comment] 2017-05-06 15:48
muller-ma wrote:

> Are non free dependencies a problem? openhab is under EPL, but they
> recommend Oracle Java instead of openjdk

It is fine to support non-open languages.  What is included in Vim
preferably uses the Vim license.

-- 
It is illegal for anyone to give lighted cigars to dogs, cats, and other
domesticated animal kept as pets.
		[real standing law in Illinois, United States of America]

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by ThomDietrich** [comment] 2017-05-08 12:55
Please also pay attention to https://github.com/cyberkov/openhab-vim/issues/2
While filetype can be openHAB specific, the syntax should be Xtend. Maybe @chrisbra or @brammool have some best practice recommendation?

**Comment by chrisbra** [comment] 2017-05-08 13:40
@ThomDietrich I don't understand the problem. Why does it matter, what the syntax name is? I think if the syntax name is changed, the filetype name should also be changed, to make it easier for people to find the correct file.

I think in general this should be solved upstream (e.g. cyberkov/openhab-vim) and whatever the conclusion is can then be distributed with Vim.

**Comment by mueller-ma** [comment] 2017-05-08 14:33
@ThomDietrich Most Xtend elements are included in https://github.com/cyberkov/openhab-vim

**Comment by ThomDietrich** [comment] 2017-05-08 14:54
Correct. The problem is that GitHub's syntax highlighting engine Linguist will recognize "Xtend" as syntax but will not highlight "openhab" or a file without an explicit vim modeline. ([Example](https://github.com/openhab/openhab-distro/blob/master/features/distro-resources/src/main/resources/rules/demo.rules)). Hence it would be ideal to work with the "common divisor":
`// vim: syntax=Xtend`

**Comment by cyberkov** [comment] 2017-05-08 15:10
Hello!

@ThomDietrich why not extend Linguist with the openHab syntax?
We are speaking about a syntaxfile for vim here, not Github's own syntax highlighting.

If there are missing elements I would gladly add them (or have PR's of course :) ) or, if Xtend syntax will be in the default syntaxes as well, use `runtime! syntax/xtend.vim` as it is in https://github.com/vim/vim/blob/master/runtime/syntax/gitsendemail.vim#L11 for instance


Thank you @mueller-ma for pushing me ;-) I will try to prepare a proper pull request incorporating the changes needed to be a good vim citizen.

Cheers Hannes

**Comment by chrisbra** [comment] 2017-08-02 20:02
closing then.

**Closed as completed by chrisbra** 2017-08-02 20:02 UTC
