### ISSUE TITLE
Can't use object variable in mapnew

### ISSUE THREAD

**Issue by habamax** [vim/vim#14030] opened 2024-02-13 23:19 UTC
### Steps to reproduce

Run following vim9script

```
vim9script

class MyClass
    var somestring: string
endclass

var listOfClasses = []

listOfClasses->add(MyClass.new("hello"))

var newListOfClasses = listOfClasses->mapnew((_, v) => v.somestring)
```

### Expected behaviour

There should be no error.

Instead, there is `E715: Dictionary required`

### Version of Vim

9.1.105

### Environment

debian

**Comment by lifepillar** [comment] 2024-02-19 19:55
Possibly related: https://github.com/vim/vim/issues/12024 and https://github.com/vim/vim/issues/11822.

Generally speaking, `E715` often happens when Vim script is not able to infer the types by itself, so the best cure is to be more explicit with type annotations. If you add all type annotations, your script works:

```vim
vim9script

class MyClass
  var somestring: string
endclass

var listOfClasses: list<MyClass> = []

listOfClasses->add(MyClass.new("hello"))

var newListOfClasses: list<string> = listOfClasses->mapnew((_, v: MyClass): string => v.somestring)
```

In fact, often a minimal amount of explicit typing is needed. In your case, you certainly need to type `listOfClasses`, because the type of the list cannot be inferred from an empty list. As it turns out, you also need to type the argument of the lambda (note that the error refers to the lambda):

```vim
vim9script

class MyClass
  var somestring: string
endclass

var listOfClasses: list<MyClass> = []

listOfClasses->add(MyClass.new("hello"))

var newListOfClasses = listOfClasses->mapnew((_, v: MyClass) => v.somestring)
```

I am not sure whether this can be considered a bug. I would say that the type system is not smart enough *yet* to figure out the types automatically in some cases—especially when lambda are involved.

**Comment by errael** [comment] 2024-02-19 20:15
> the best cure is to be more explicit with type annotations

BTW, some tests I ran showed if the type annotations are used, the code executes faster. I guess there's less checking needed at runtime.

**Comment by yegappan** [comment] 2024-12-30 01:51
I am not able to reproduce this problem with the latest Vim (9.1.973).  Can you try to reproduce this issue with the latest Vim?

**Comment by lifepillar** [comment] 2024-12-30 10:58
Confirmed. The OP's script now compiles and runs without additional type hints. Great!

**Comment by chrisbra** [comment] 2024-12-30 11:13
Closing then

**Closed as not planned by chrisbra** 2024-12-30 11:13 UTC
Labels: bug, vim9class
