### ISSUE TITLE
The window scroll event

### ISSUE THREAD

**Issue by rickhowe** [vim/vim#5181] opened 2019-11-06 04:52 UTC
I have been looking for how to monitor the window scroll.
My plugin highlights some text contents using matchadd() but if the file is too big it takes much time to do whole lines and consumes memory.
I would like to highlight only within visible lines, range(line('w0'), line('w$')), and update them whenever the scroll happens.
But there is no specific event for the window scroll.

One workaround is to use CursorMoved, but it is not called without cursor moved (eg, CTRL-E, CTRL-Y, zb, zt).
Another one is to use '%{}' for statusline (and titlestring or so) option and check the scroll, but it might have some side effects.

Is it reasonable and possible to add the scroll event?

**Comment by chrisbra** [comment] 2019-11-06 07:17
looks like a duplicate of #3127

**Comment by brammool** [comment] 2019-11-06 12:59
> I have been looking for how to monitor the window scroll.
> My plugin highlights some text contents using matchadd() but if the
> file is too big it takes much time to do whole lines and consumes
> memory.
> I would like to highlight only within visible lines, range(line('w0'),
> line('w$')), and update them whenever the scroll happens.
> But there is no specific event for the window scroll.
> 
> One workaround is to use CursorMoved, but it is not called without
> cursor moved (eg, CTRL-E, CTRL-Y, zb, zt).
> Another one is to use '%{}' for statusline (and titlestring or so)
> option and check the scroll, but it might have some side effects.
> 
> Is it reasonable and possible to add the scroll event?

There was a request for a WindowScrolled event (can't find it now).
It would be a reasonable thing to add.
Question is when it would trigger.  Probably not for every small scroll,
but only from the main loop, otherwise scripts may get a bit slow.
Probably around the same moment CursorMoved is triggered.

-- 
hundred-and-one symptoms of being an internet addict:
35. Your husband tells you he's had that beard for 2 months.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by andymass** [comment] 2019-11-06 16:25
Maybe the real problem here is matchadd is apparently too slow?  What about text properties?

**Comment by rickhowe** [comment] 2019-11-07 06:12
> I have been looking for how to monitor the window scroll.
> My plugin highlights some text contents using matchadd() but if the file is too big it takes much time to do whole lines and consumes memory.
> I would like to highlight only within visible lines, range(line('w0'), line('w$')), and update them whenever the scroll happens.
> But there is no specific event for the window scroll.
> 
> One workaround is to use CursorMoved, but it is not called without cursor moved (eg, CTRL-E, CTRL-Y, zb, zt).
> Another one is to use '%{}' for statusline (and titlestring or so) option and check the scroll, but it might have some side effects.
> 
> Is it reasonable and possible to add the scroll event?

**Comment by rickhowe** [comment] 2019-11-07 06:17
> There was a request for a WindowScrolled event (can't find it now). It would be a reasonable thing to add. Question is when it would trigger. Probably not for every small scroll, but only from the main loop, otherwise scripts may get a bit slow. Probably around the same moment CursorMoved is triggered.

For example, [count]CTRL-F can trigger a single event, even if multiple lines are actually scrolled.
And it is nice to get an event if the scroll is completed after resizing the window and using the scroll bar.

**Comment by rickhowe** [comment] 2019-11-07 06:21
> Maybe the real problem here is matchadd is apparently too slow? What about text properties?

matchadd() is just an example, in my case. If  the event is available, it can be used, for example, to customize the scroll bind between several windows.

**Comment by romgrk** [comment] 2020-11-08 00:40
@brammool neovim added it as `WinScrolled` in master. Should have checked sooner but if you have different opinions on that name it could still be changed, we still have some work to do on it, though I based it on your comment above that mentioned `WindowScrolled`; `WinScrolled` felt more in line with the other existing events.

**Comment by rickhowe** [comment] 2020-11-08 04:28
That is a good news. `WinScrolled` is much better as it is consistent with the name of the existing events.

**Comment by brammool** [comment] 2020-11-08 15:51
Yeah, WinScrolled sounds good.  I don't have a specific preference, thus making it work like neovim will simplify things for plugin writers.  Is the amount of scrolling made available somehow?

**Comment by romgrk** [comment] 2020-11-09 00:49
It is not. What about it's made available through `v:event`? Something like `topscroll` and `leftscroll`?

Now that I think, it could also be interesting for neovim to add `topline`, `leftcol`, `width` and `height` on `v:event`. That avoids a roundtrip for our remote plugins. But it's not as useful in vim because plugins are all in-process. 

On the other hand, for the moment I haven't thought about a use-case where the amount of scrolling is required, all use-cases I've seen need to know the current viewport, but the amount of scrolling isn't that relevant. Example use-cases:
 - https://github.com/wellle/context.vim and https://github.com/romgrk/nvim-treesitter-context
 - https://github.com/Yggdroot/indentLine (Updating indent-lines for the viewport only)

Let me know what sounds good for you. We can also wait a bit before finalizing the spec, the event will surely be tested by people following master neovim and we might have more feedback then.

**Comment by brammool** [comment] 2020-11-09 10:29
I suppose the plugin could remember any state it needs, and get the current scroll position with existing functions.  Thus only the window ID is needed (it can differ from the current window).  Similar to `<abuf>` and `<afile>`.  `<awinid>` ?

**Comment by romgrk** [comment] 2020-11-09 11:04
> Similar to and . ?

Sorry I don't get that.

> I suppose the plugin could remember any state it needs, and get the current scroll position with existing functions.

Indeed. OTOH it's nice for plugins to have less work to do. My only worry about including those properties on `v:event` is performance. Haven't looked at anything in `typval.c` yet, but would there be a relevant performance penalty for attaching that data?

Update:

> `<awinid>` ?

Yes, that could also be nice. But if there's no performance penalty I'd go with the props.

**Comment by k-takata** [comment] 2020-11-09 11:07
> Similar to and . ?

I updated Bram's comment so that make this visible.

**Comment by brammool** [comment] 2020-11-09 18:24
> > Similar to and . ?
> 
> Sorry I don't get that.

Github tends to eat things that look like HTML.
Perhaps this works: &lt;awinid&gt;
But that will look bad for those reading the maillist.

> > I suppose the plugin could remember any state it needs, and get the
> > current scroll position with existing functions.
> 
> Indeed. OTOH it's nice for plugins to have less work to do. My only
> worry about including those properties on `v:event` is performance.
> Haven't looked at anything in `typval.c` yet, but would there be a
> relevant performance penalty for attaching that data?

v:event is a dictionary, and there is indeed some overhead (allocating
items, hash computation).  But compared to the whole autocommand
execution it is small.  It would be good to try avoid setting v:event
when there are no matching autocommands.

-- 
hundred-and-one symptoms of being an internet addict:
222. You send more than 20 personal e-mails a day.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by k-takata** [comment] 2020-11-09 23:51
> Github tends to eat things that look like HTML.

You can surround it with backquotes or escape with a backslash.

    `<abc>` will show <abc> as a code.
    \<abc> will show <abc> as a normal text.

And you can preview what it looks like by the "Preview" tab.
![image](https://user-images.githubusercontent.com/840186/98609960-e22e8000-2331-11eb-887c-4155f5b91374.png)

**Comment by chrisbra** [comment] 2020-11-10 07:40
> Github tends to eat things that look like HTML.

That's a property of markdown, to allow users to easily include html code.

**Comment by dstein64** [comment] 2022-04-12 00:54
A `WinScrolled` event was added in #10102.

**Closed as completed** 2022-04-12 09:56 UTC
Labels: enhancement
