### ISSUE TITLE
clientserver without X

### ISSUE THREAD

**Issue by kohnish** [vim/vim#9094] opened 2021-11-05 19:44 UTC
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**
In order to use clientserver feature, not only linking with X libraries but also X server is necessary on runtime.
To do something like `vim --servername VIM_SERVER --remote-tab test` , you need to start full x server or virtual x server. --remote-tab is very useful when you open from vim :sh or :terminal. On Mac, it's especially painful to link with xquartz and have it running. On SSH only server, you'd run Xvfb.

**Describe the solution you'd like** 
 Ideally vim directly supports or vim project can generate a tiny server binary, and vim can open remote tab through unix domain socket or tcp.

**Describe alternatives you've considered**
None. I cannot think of things other than socket for IPC for this.

**Additional context**
None

**Comment by bfrg** [comment] 2021-11-05 19:53
Duplicate of #3509.

**Closed as completed** 2021-11-05 21:39 UTC
Labels: enhancement
