### ISSUE TITLE
Buffer allocations too small

### ISSUE THREAD

**Issue by workbbraun** [vim/vim#1258] opened 2016-11-16 16:09 UTC
There's two places where the buffer allocated for vim_snprintf is too small, potentially resulting in truncation of the output string.  Fortunately, since vim_snprintf will always ensure nul termination, and will overwrite the last char of the buffer if it has to, this isn't and out of bounds access.  But can still result in the truncation of the last character of the buffer.

https://github.com/vim/vim/blob/master/src/ex_cmds2.c#L3656
and
https://github.com/vim/vim/blob/master/src/ex_cmds2.c#L3592

The len alloc'd should be +1 to include the terminating nul.

**Comment by brammool** [comment] 2016-11-17 13:48
workbbraun wrote:

> There's two places where the buffer allocated for vim_snprintf is too
> small, potentially resulting in truncation of the output string.
> Fortunately, since vim_snprintf will always ensure nul termination,
> and will overwrite the last char of the buffer if it has to, this
> isn't and out of bounds access.  But can still result in the
> truncation of the last character of the buffer.
> 
> https://github.com/vim/vim/blob/master/src/ex_cmds2.c#L3656
> and
> https://github.com/vim/vim/blob/master/src/ex_cmds2.c#L3592
> 
> The len alloc'd should be +1 to include the terminating nul.

The "%s" in the pattern is counted for the length, that should be
sufficient.  Can you reproduce the suspected problem?

## 

"Space is big.  Really big.  You just won't believe how vastly hugely mind-
bogglingly big it is.  I mean, you may think it's a long way down the
road to the chemist, but that's just peanuts to space."
        -- Douglas Adams, "The Hitchhiker's Guide to the Galaxy"

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by bwasim** [comment] 2017-02-06 21:23
I've verified @brammool 's comment to be correct. The buffer size is always sufficient because of the %s. This needs to be closed as Not a Bug. 

Cheers, 
Wasim

**Closed as completed** 2017-02-06 21:41 UTC
