### ISSUE TITLE
Stuttering cursorline in newer versions of vim

### ISSUE THREAD

**Issue by txtyash** [vim/vim#8908] opened 2021-09-23 17:22 UTC
**Description**
While scrolling through files with cursorline and cursorcolumn enabled, the cursorcolumn stutters when the lines it scrolls through are of variable length, i.e., the lines through which the cursor jumps rapidly back and forth while scrolling. This happens specifically when cursorcolumn and syntax is enabled. If the back and forth jumping isn't understood well then steps to reproduce will be of help.
_WHILE READING STEPS TO REPRODUCE, MAKE SURE 'k' IS HELD DOWN WHILE SCROLLING_

**Steps to Reproduce**
1. Run 'vim --clean'
2. Open this [sample file](https://github.com/zim0369/dotfiles/blob/main/public/vimrc) inside of the 'vim --clean' session.
3. Move to the bottom of the file and place your cursor on/underneath 't' in 'tokyonight'. 
4. 'set cursorline' and 'syntax on'
5. Now scroll upwards about 20-30 lines using 'k'. (All movements done using the keyboard)
6. No stutter is noticed.
7. Now place the cursor back underneath 't' in 'tokyonight' at the bottom of the file.
8. set cursorcolumn
9. Now scroll upwards about 20-30 lines using 'k'.
10. Stuttering of the cursorline is noticable. 
11. syntax off
12. Now place the cursor back underneath 't' in 'tokyonight' at the bottom of the file.
13. Now scroll upwards about 20-30 lines using 'k'.
14. No stutter is noticed.

**Expected behavior**
No stutter with cursorline enabled along with cursorcolumn & syntax together, when scrolling through a file with lines of variable length where the cursor jumps back and forth rapidly while scrolling due to the default behavior of vim to focus on words or can say to jump to specific words on every line while scrolling.

**Environment**
 - Vim version: VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Sep 15 2021 21:48:21)
 - OS: Archlinux
 - Terminal: urxvt and alacritty.
 - Terminal: urxvt and alacritty.
 - TERM: 'xterm-256color' 

**Additional context**
This stuttering of cursorline occurs when both the cursorcolumn and syntax are enabled.

**Comment by chrisbra** [comment] 2021-09-24 06:32
This is not very clear. Please start with `vim --clean` to reproduce and mention exactly how you scroll (mouse, keyboard, etc). Also please test the most recent vim version. It may also depend on what your $TERM is set to. There were some patches to make cursorline scrolling better, not sure why it did not help. It may also depend on you syntax scripts. so test with and without syntax highlighting please.

Second of all, this might depend on your system (e.g. graphics driver etc). So please give more details. And finally, it would probably need profiling to figure this out.

**Comment by zim0369** [comment] 2021-09-24 07:14
> This is not very clear. Please start with `vim --clean` to reproduce and mention exactly how you scroll (mouse, keyboard, etc). Also please test the most recent vim version. It may also depend on what your $TERM is set to. There were some patches to make cursorline scrolling better, not sure why it did not help. It may also depend on you syntax scripts. so test with and without syntax highlighting please.
> 
> Second of all, this might depend on your system (e.g. graphics driver etc). So please give more details. And finally, it would probably need profiling to figure this out.

Hey I've been able to trackdown the problem. The stutter during scroll occurs due to cursorcolumn. I'm sorry that I might not have been able to convey my problem in a report properly but [this post on reddit might help.](https://www.reddit.com/r/vim/comments/ptw7yp/is_slow_scroll_ever_going_to_be_fixed/)

**Comment by ychin** [comment] 2021-09-24 14:01
I played around and can see the issue too. In particular, if `cursorcolumn` and `syntax on` are both set, it seems to be really bad, regardless of whether `cursorline` is on (since I do remember there were some performance fixes regarding `cursorline` and `relativenumber` before).

I am using `let g:profstart=reltime() | for i in range(1,50) | exec "normal \<C-E>" | redraw | endfor | echo reltimestr(reltime(g:profstart)) . ' seconds'` to profile, and turning on `cursorcolumn` makes it 20x slower (From 0.02s to 0.40s) for me. I think maybe Vim is repainting the regions instead of issuing scroll commands but not sure. I was testing this on Apple Terminal which is not hardware accelerated. A hardware-accelerated terminal will probably be able to handle this better.

**Comment by dargor** [comment] 2021-09-26 13:14
Same here, I use mostly python files (`syntax on`, `cursorcolumn` and `cursorline`) and vim stutters with `cursorcolumn` but works fine with `nocursorcolumn` (no other changes, so this is _not_ a `cursorline` issue).

Vim version 8.2.3455, tried on multiple terminals (alacritty, rxvt-unicode, st, xterm and zutty).

**Comment by brammool** [comment] 2021-09-29 10:58
> > I played around and can see the issue too.
> I'm glad you noticed it. It was kinda' hard for me to explain. I mean it is pretty obvious to the eye but hard to convey in a textual format.
> > I was testing this on Apple Terminal which is not hardware accelerated. A hardware-accelerated terminal will probably be able to handle this better.
> No. I tried this on Alacritty but didn't work as expected. I still see the same amount of stuttering. And gvim must be suffering from an existential crisis.

To see whether Vim uses terminal commands to scroll text up or down or
redraws the text character by character, you can set the 'writedelay'
option.  Just setting it to one might already work, otherwise try larger
values.

-- 
hundred-and-one symptoms of being an internet addict:
78. You find yourself dialing IP numbers on the phone.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by zim0369** [comment] 2021-09-30 09:07
There's not much info about 'writedelay' in vim help, but 'set writedelay=1' forces the entire terminal window to refresh for every action I do. In simple words content of the terminal is drawn from top to the bottom after every action.

**Comment by chrisbra** [comment] 2021-09-30 09:13
Also for `gvim --clean`? For me (with 'cursorcolumn' set and) going down one line using `j` it just redraws the area under the cursor in the old current line and the new current line (if the column doesn't change). If the column changes, Vim redraws the up to until the new (or old column) (depending on which one is farther to the right).

Perhaps some options negatively effect it (like relativenumbering, concealing, cursorline and cursorcolumn).

**Comment by zim0369** [comment] 2021-09-30 12:06
> Also for `gvim --clean`? For me (with 'cursorcolumn' set and) going down one line using `j` it just redraws the area under the cursor in the old current line and the new current line (if the column doesn't change). If the column changes, Vim redraws the up to until the new (or old column) (depending on which one is farther to the right).

Yes, you're correct. Only the area under the cursorline gets refreshed. I started editing from the top most line, that's why the whole window was being refreshed from top to bottom. Now I tried it with more operations and I've noticed :
- No line gets refreshed when inserting text but just the area around cursor on that specific line. 
- When any operation makes the other lines move only then does the area below the cursorline gets refreshed/redrawn. 
- The cursorcolumn is redrawn very frequently as compared to the cursorline because moving the cursor sideways doesn't redraw the cursorline, similarly moving the cursor up/down shouldn't redraw the cursorcolumn but since the cursor doesn't stay in the same column, the cursorcolumn has to be redrawn.

The frequent redrawing of the cursorcolumn explains a little bit of the 'steps to recreate' I made. I mentioned that scrolling through files with lines of variable length so that the cursor frequently moves back and forth causing the cursorline to lag but whenever the cursor was static along the row, keeping the cursorcolumn static as well, did not cause the curosorline to lag. So I think it must be the frequently redrawn cursorcolumn that's causing the lag. 
Anyways, I don't know much about the technical stuff, so my assumptions could be terribly wrong.

**Comment by brammool** [comment] 2021-09-30 21:01
> > Also for `gvim --clean`? For me (with 'cursorcolumn' set and) going
> > down one line using `j` it just redraws the area under the cursor in
> > the old current line and the new current line (if the column doesn't
> > change). If the column changes, Vim redraws the up to until the new
> > (or old column) (depending on which one is farther to the right).
> 
> Yes, you're correct. Only the area under the cursorline gets
> refreshed. I started editing from the top most line, that's why the
> whole window was being refreshed from top to bottom. Now I tried it
> with more operations and I've noticed :
> - No line gets refreshed when inserting text but just the area around cursor on that specific line. 
> - When any operation makes the other lines move only then does the area below the cursorline gets refreshed/redrawn. 
> - The cursorcolumn is redrawn very frequently as compared to the cursorline because moving the cursor sideways doesn't redraw the cursorline, similarly moving the cursor up/down shouldn't redraw the cursorcolumn but since the cursor doesn't stay in the same column, the cursorcolumn has to be redrawn.
> 
> The frequent redrawing of the cursorcolumn explains a little bit of
> the 'steps to recreate' I made. I mentioned that scrolling through
> files with lines of variable length so that the cursor frequently
> moves back and forth causing the cursorline to lag but whenever the
> cursor was static along the row, keeping the cursorcolumn static as
> well, did not cause the curosorline to lag. So I think it must be the
> frequently redrawn cursorcolumn that's causing the lag. 
> Anyways, I don't know much about the technical stuff, so my
> assumptions could be terribly wrong.

Vim already does some optimization for redrawing the cursorline and
cursorcolumn, but at the same time the redrawing may require a full
redraw of lines when certain options are set, text is changed and syntax
highlighting is used, etc.  We can't optimize every situation.

If you find the slow redrawing annoying, you'll have to disable the
cursorcolumn.  Or find out what else matters, e.g. line numbering and
other options that change how text is displayed.

-- 
From "know your smileys":
¯\_(ツ)_/¯   Shrug

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by ychin** [comment] 2021-09-30 21:28
I can confirm that writedelay seems to suggest that Vim is correct only redrawing when necessary.

One weird thing I noticed was that `vim --clean` would not have the issue, but `vim -u NONE -U NONE` would. After mucking around a little, I think the `set scrolloff=5` line in `defaults.vim` is helping out a lot, and if you set `scrolloff` back to 0, then you would see the slowed down scrolling more. Haven't investigated enough but just thought I would put it out why `vim --clean` may feel fine.

**Comment by zim0369** [comment] 2021-10-01 13:07
> > Also for `gvim --clean`? For me (with 'cursorcolumn' set and) going > down one line using `j` it just redraws the area under the cursor in > the old current line and the new current line (if the column doesn't > change). If the column changes, Vim redraws the up to until the new > (or old column) (depending on which one is farther to the right). Yes, you're correct. Only the area under the cursorline gets refreshed. I started editing from the top most line, that's why the whole window was being refreshed from top to bottom. Now I tried it with more operations and I've noticed : - No line gets refreshed when inserting text but just the area around cursor on that specific line. - When any operation makes the other lines move only then does the area below the cursorline gets refreshed/redrawn. - The cursorcolumn is redrawn very frequently as compared to the cursorline because moving the cursor sideways doesn't redraw the cursorline, similarly moving the cursor up/down shouldn't redraw the cursorcolumn but since the cursor doesn't stay in the same column, the cursorcolumn has to be redrawn. The frequent redrawing of the cursorcolumn explains a little bit of the 'steps to recreate' I made. I mentioned that scrolling through files with lines of variable length so that the cursor frequently moves back and forth causing the cursorline to lag but whenever the cursor was static along the row, keeping the cursorcolumn static as well, did not cause the curosorline to lag. So I think it must be the frequently redrawn cursorcolumn that's causing the lag. Anyways, I don't know much about the technical stuff, so my assumptions could be terribly wrong.
> Vim already does some optimization for redrawing the cursorline and cursorcolumn, but at the same time the redrawing may require a full redraw of lines when certain options are set, text is changed and syntax highlighting is used, etc. We can't optimize every situation. If you find the slow redrawing annoying, you'll have to disable the cursorcolumn. Or find out what else matters, e.g. line numbering and other options that change how text is displayed.
> […](#)
> -- From "know your smileys": ¯\_(ツ)_/¯ Shrug /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net \\\ /// \\\ \\\ sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ /// \\\ help me help AIDS victims -- http://ICCF-Holland.org ///

Okay. Closing the issue.

**Closed as completed by zim0369** 2021-10-01 13:07 UTC
