### ISSUE TITLE
Starting vim session quickly leads to segfault 11

### ISSUE THREAD

**Issue by xave** [vim/vim#12214] opened 2023-03-31 18:21 UTC
### Steps to reproduce

1. Open vim and some files in the buffer. Organize them into splits. 2 rows, 3 columns. 
2. Save this to a session file with the default name in the directory of the files to be opened.
3. launch vim: `vim -S`
4. Scroll down with `j` key until page begins to scroll.
5. vim exits. Message: 
```
Vim: Caught deadly signal SEGV
Vim: Finished.
Segmentation fault: 11
```

This issue is consistent.

If one scrolls in the split that is active when session starts and then navigates to another split, the segfault does not seem to happen. If one opens `vim -S` and immediately jumps to another split and scrolls, the segfault happens every time.

### Expected behaviour

`vim -S` and then use vim like normal with no segfaults.

### Version of Vim

 version 9.0.1023

### Environment

OS: M1 Mac v 12.6.3
Terminal: iTerm2
$TERM: screen
Shell: bash (in tmux)

**Comment by errael** [comment] 2023-03-31 20:08
9.0.1429 is the current vim version.

**Comment by chrisbra** [comment] 2023-04-01 15:38
I cannot reproduce. Does it happen with `vim --clean`?

**Comment by brammool** [comment] 2023-04-02 18:02
I also cannot reproduce.  The description is vague, please state exactly:
- how to open Vim, preferably with "vim --clean".
- What files are edited.  E.g. go to the directory with the Vim help files $VIMRUNTIME  /doc
- List the commands literally how to split the windows
- I assume you create a session file with :mksession ?  Add a name if you can't write in the "doc" directory.

**Comment by chrisbra** [comment] 2023-04-20 06:18
Missing feedback, so closing

**Closed as not planned by chrisbra** 2023-04-20 06:18 UTC
Labels: bug
