### ISSUE TITLE
Setting an encoding in a buffer breaks spellcheck in another buffer.

### ISSUE THREAD

**Issue by alkim0** [vim/vim#10876] opened 2022-08-09 17:32 UTC
## Setup
My `.vimrc`:
```
set spell
```

In a directory, I have two text files called `apple.txt` and `pear.txt`.
The contents of `apple.txt` are:
```
aoweijfwoeifj
```
The contents of `pear.txt` are:
```
woeijfoewifj
```

## Steps
1. Go to directory that `apple.txt` and `pear.txt` are in.
2. . Open `apple.txt` with vim:
```
vim apple.txt
```
3. The word in `apple.txt` should be highlighted as a misspelled word
4. Run:
```
:vsplit pear.txt
```
5. In the newly opened buffer with `pear.txt`, run:
```
:let &encoding='utf-8'
```
6. The word in `apple.txt` is no longer highlighted. When changing back to the `apple.txt` over the misspelled word and running `z=`, I get the error: `E756: Spell checking is not possible`.

### Expected behaviour

After setting performing `:let &encoding='utf-8'`, I expect no changes to occur. The highlighted word in `apple.txt` should remain highlighted and `z=` should work as expected.

### Version of Vim

9.0.0000

### Environment

OS: ArchLinux
Terminal: alacritty
$TERM: alacritty
Shell: zsh

**Comment by brammool** [comment] 2022-08-09 18:20
What was the value of 'encoding' before you set it to "utf-8"?
If it was different, this has all kinds of side effects.  'encoding' is only supposed to be changed early during startup.
Maybe you intended to change 'fileencoding'?

**Comment by alkim0** [comment] 2022-08-09 18:52
It was `utf-8`. I ran across this problem because I use editorconfig and that sets the encoding every time a new file is opened (See linked issue for more details).

**Comment by brammool** [comment] 2022-08-09 21:06
> It was `utf-8`. I ran across this problem because I use editorconfig
> and that sets the encoding every time a new file is opened (See linked
> issue for more details).

That would reduce the side effects, but there still are some.
The internal wordlist is cleared, for example: ":help
internal-wordlist".  Also:
	When 'encoding' is set all the word lists are reloaded, thus you
	may notice a delay then too.

-- 
This is an airconditioned room, do not open Windows.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by alkim0** [comment] 2022-08-09 21:12
I see. So in a plugin such as editorconfig, which requires being able to set the encoding, "fileencoding" should be used instead?

**Comment by chrisbra** [comment] 2022-08-10 06:45
Yes, you should basically never ever change the encoding setting after vim initializes. I think this is a bug in your editorconfig plugin

**Comment by k-takata** [comment] 2022-08-10 07:28
Cf. https://github.com/editorconfig/editorconfig-vim/pull/186

Closing as this is not a bug of Vim.

**Closed as completed by k-takata** 2022-08-10 07:28 UTC

**Comment by alkim0** [comment] 2022-08-10 17:29
Thanks for all the help!
