### ISSUE TITLE
% movement does not jump to opening paren when followed by a '>' with ft=php

### ISSUE THREAD

**Issue by sdondley** [vim/vim#9825] opened 2022-02-22 16:17 UTC
### Steps to reproduce

Got this line:

add_post_meta($this->cmr_id, 'intro_paragraph', 'Hello');

With:
```
add_post_meta($this->cmr_id, 'intro_paragraph', 'Hello');
                                 ^ cursor here
```
Hitting '%' key jumps to opening paren as expected.

But with:
```
add_post_meta($this->cmr_id, 'intro_paragraph', 'Hello');
                 ^ cursor here
```
Nothing happens.

See https://vi.stackexchange.com/questions/36865/jumping-to-open-paren-with-doesnt-work-when-open-paren-followed-by-and-curs/36867#36867 for workround.

### Expected behaviour

Jumps to opne paren.

### Version of Vim

8.2.3489

### Environment

macos iterm

**Comment by chrisbra** [comment] 2022-02-22 16:36
I cannot reproduce. Have you tried with Vim --clean? Do you use matchit or not? Also, can you please try with latest master?

**Comment by sdondley** [comment] 2022-02-22 19:48
The matchit plugin is loaded and used by default on neovim.

I have a workaround in the link to stackoverflow in OP.

**Comment by chrisbra** [comment] 2022-02-22 20:06
well, this is vim here and I only see this behavious without the matchit plugin. Can you please check? 

> I have a workaround in the link to stackoverflow in OP.

Would have been nice to mention that here, oh well

**Comment by chrisbra** [comment] 2022-02-22 21:40
I have a preliminary patch here: https://github.com/chrisbra/vim/commit/5ae98be06b79293be946b5f5a4bf79438a4b3d10?w=1

@brammool what do you think?

**Comment by sdondley** [comment] 2022-02-23 03:13
> well, this is vim here and I only see this behavious without the matchit plugin. Can you please check?

I'm unclear what you're asking. You want me to check without the matchit plugin running? Or you want me to make sure it's running? It the latter, it's def running. I see it getting called in scriptnames.

> 
> > I have a workaround in the link to stackoverflow in OP.
> 
> Would have been nice to mention that here, oh well

In OP, I said "see <link> for the workaround."

**Comment by sdondley** [comment] 2022-02-23 03:18
As I recall, the html.vim script checks to see if matchit is running. Line 29:

```
if exists("loaded_matchit")
    let b:match_ignorecase = 1
    let b:match_words = '<:xx>,' . 
    \ '<\@<=[ou]l\>[^>]*\%(>\|$\):<\@<=li\>:<\@<=/[ou]l>,' .
    \ '<\@<=dl\>[^>]*\%(>\|$\):<\@<=d[td]\>:<\@<=/dl>,' .
    \ '<\@<=\([^/][^ \t>]*\)[^>]*\%(>\|$\):<\@<=/\1>'
endif
```

**Comment by chrisbra** [comment] 2024-11-09 11:01
it seems you got a reasonable work-around. So closing

**Closed as completed by chrisbra** 2024-11-09 11:01 UTC
