### ISSUE TITLE
joining a set of lines with some blank lines does not keep a space between joined lines

### ISSUE THREAD

**Issue by gblais** [vim/vim#5562] opened 2020-02-01 04:06 UTC
**Bug Description**
When joining multiple lines (J or v_J), normally the joined lines are separated by a space.
But in vim 8.2, if there is a blank line somewhere in the group of lines to be joined, the lines above and below this blank line will be concatenated without any space separating them.

**To Reproduce**
1. Run `vim --clean` (or `gvim --clean`, etc.)
2. Insert the following text (a on first line, then a blank line, then b on the third line):
```
a

b
```
3. Join the 3 lines.
i.e.  with the cursor on line 1 (gg), join the 3 lines (3J),
 or select all 3 lines with V, then type J  (ggVGJ)
You get lines 1 and 3 concatenated without any spaces in between
```
ab


```

**Expected behavior**
As in previous vim versions, the joined lines should have been separated by a space as follows:
```
a b


```

**Environment:**
- VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Dec 12 2019 13:19:27)
MS-Windows 32-bit console version
Compiled by mool@tororo
- OS: Windows 10 pro, 1909, build 18363.592
 - Terminal: GUI

**Comment by k-takata** [comment] 2020-02-01 04:24
I think this is fixed with [v8.2.0018](https://github.com/vim/vim/commit/91b65e49440e77222a65b6f868507453239f409b).

**Comment by chrisbra** [comment] 2020-02-01 11:38
Yes, cannot reproduce in 8.2.140. Therefore closing.

**Closed as completed by chrisbra** 2020-02-01 11:38 UTC
