### ISSUE TITLE
highlighted matches of `\%V` will not be cleared correctly

### ISSUE THREAD

**Issue by haolian9** [vim/vim#11694] opened 2022-12-11 23:22 UTC
### Steps to reproduce
case 1:
1. `$ seq 20 | vim -u NONE +'set hlsearch' -`
2. a) `:1`, `V2j<esc>`
3. `/\%V\d`
4. b) `:5`, `V2j<esc>`
5. c) `:10`, `v2j<esc>`

case 2:
1. `$ seq 100 | vim -u NONE +'set hlsearch' +'set incsearch' -`
2. `:vs`, `:50`, `zt`
3. `V2j` 
     4.1: `/%V` # now some lines in the another window are selected
     4.2: `/%V\d` # now the last line in the another window is selected, sometimes it will be the first line

### actual behavior:

case 1:
* now the a, b and c region will all be highlighted.
* when the line is scrolled out of the screen, the highlights will be cleared in my tests.

### Expected behaviour

case 1: only the previous visual region will be highlighted
case 2: &incsearch will not apply matching to the another window as it's not in the visual area of `\%V`

### Version of Vim

VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Nov 19 2022 14:37:14) Included patches: 1-910 Compiled by Arch Linux Huge version without GUI.

### Environment

os: archlinux
terminal: st 0.8.5
TERM: st-256color
shell: zsh 5.9

**Comment by brammool** [comment] 2022-12-12 14:21
I can reproduce it.
Unfortunately this is hard to fix, other than redrawing everything on any change, which is very inefficient.

**Comment by haolian9** [comment] 2022-12-12 15:12
thanks for taking time on this!

**Comment by chrisbra** [comment] 2022-12-12 19:27
If this bothers you, you can potentially make use of a *ModeChanged* autocommand:

    au ModeChanged [vV\x16]:* :redraw!

should work (with or without the `!` attribute), haven't tested it thoroughly.

**Comment by chrisbra** [comment] 2022-12-12 19:31
I am closing this, since there is a work-around to fix it (or you can always use `CTRL-L` to force a redraw, which I do not find too bad).

**Closed as completed by chrisbra** 2022-12-12 19:31 UTC
Labels: bug
