### ISSUE TITLE
German spell files are broken

### ISSUE THREAD

**Issue by AlxHnr** [vim/vim#4314] opened 2019-04-28 14:26 UTC
**Note**: It wasn't obvious to me who currently maintains the German vim spell files. I had no time to dive into mailing lists and google groups, so this is what you get.

# Environment

System: `Fedora 29`
Terminal: `rxvt-unicode v9.22`
$TERM: `rxvt-unicode-256color`
Output of `vim --version`:

```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Apr  8 2019 12:18:55)
Included patches: 1-1137
Modified by <bugzilla@redhat.com>
Compiled by <bugzilla@redhat.com>
Huge version without GUI.  Features included (+) or not (-):
+acl               +extra_search      +mouse_netterm     -tag_old_static
+arabic            -farsi             +mouse_sgr         -tag_any_white
+autocmd           +file_in_path      -mouse_sysmouse    -tcl
+autochdir         +find_in_path      +mouse_urxvt       +termguicolors
-autoservername    +float             +mouse_xterm       +terminal
-balloon_eval      +folding           +multi_byte        +terminfo
+balloon_eval_term -footer            +multi_lang        +termresponse
-browse            +fork()            -mzscheme          +textobjects
++builtin_terms    +gettext           +netbeans_intg     +textprop
+byte_offset       -hangul_input      +num64             +timers
+channel           +iconv             +packages          +title
+cindent           +insert_expand     +path_extra        -toolbar
-clientserver      +job               +perl/dyn          +user_commands
-clipboard         +jumplist          +persistent_undo   +vartabs
+cmdline_compl     +keymap            +postscript        +vertsplit
+cmdline_hist      +lambda            +printer           +virtualedit
+cmdline_info      +langmap           +profile           +visual
+comments          +libcall           +python/dyn        +visualextra
+conceal           +linebreak         +python3/dyn       +viminfo
+cryptv            +lispindent        +quickfix          +vreplace
+cscope            +listcmds          +reltime           +wildignore
+cursorbind        +localmap          +rightleft         +wildmenu
+cursorshape       +lua/dyn           +ruby/dyn          +windows
+dialog_con        +menu              +scrollbind        +writebackup
+diff              +mksession         +signs             -X11
+digraphs          +modify_fname      +smartindent       -xfontset
-dnd               +mouse             +startuptime       -xim
-ebcdic            -mouseshape        +statusline        -xpm
+emacs_tags        +mouse_dec         -sun_workshop      -xsmp
+eval              +mouse_gpm         +syntax            -xterm_clipboard
+ex_extra          -mouse_jsbterm     +tag_binary        -xterm_save
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/etc"
 f-b for $VIMRUNTIME: "/usr/share/vim/vim81"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -L. -Wl,-z,relro   -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,--enable-new-dtags -Wl,-z,relro -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld  -Wl,-z,relro   -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -L/usr/local/lib -Wl,--as-needed -o vim        -lm  -lselinux   -lncurses -lacl -lattr -lgpm -ldl   -Wl,--enable-new-dtags -Wl,-z,relro -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -Wl,-z,relro -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -fstack-protector-strong -L/usr/local/lib  -L/usr/lib64/perl5/CORE -lperl -lpthread -lresolv -ldl -lm -lcrypt -lutil -lc        
```

Output of `locale`, which don't seem to make any difference:

```
LANG=C.UTF-8
LC_CTYPE="C.UTF-8"
LC_NUMERIC="C.UTF-8"
LC_TIME="C.UTF-8"
LC_COLLATE="C.UTF-8"
LC_MONETARY="C.UTF-8"
LC_MESSAGES="C.UTF-8"
LC_PAPER="C.UTF-8"
LC_NAME="C.UTF-8"
LC_ADDRESS="C.UTF-8"
LC_TELEPHONE="C.UTF-8"
LC_MEASUREMENT="C.UTF-8"
LC_IDENTIFICATION="C.UTF-8"
LC_ALL=
```

# Problem

The current `de.utf-8.spl` and `de.utf-8.sug` files available on http://ftp.vim.org/pub/vim/runtime/spell/ don't recognize many words and autocorrect to gibberish. [Older](https://github.com/AlxHnr/vim-spell-files/tree/master/spell) versions of these files work like they are supposed to. English spell files do also work.

Example for the word `Rasenmäher`, which is flagged as a spelling mistake and autocorrected to garbage:

```vim
iRasenmäher<esc>
z=
```

Suggestions:

```
Change "Rasenmäher" to:
1 "-rasenmäher"
2 "Rasen0mäher"
3 "-rassenmäher"
4 "Rassen0mäher"
5 "-rasenhäher"
6 "Rasen0häher"
7 "Rasen0näher"
8 "-rasen-mäher"
9 "-arsenmäher"
10 "Arsen0mäher"
11 "Rast0mäher"
12 "-nasenmäher"
13 "-rasenmähen"
14 "-rosenmäher"
15 "Nasen0mäher"
16 "Rasen0mähen"
17 "Rosen0mäher"
18 "-hasenmäher"
19 "-rasennäher"
20 "Hasen0mäher"
...
```

# Expected behaviour

The word `Rasenmäher` is not marked as a mistake and valid suggestions pop up when typing `z=`. This can be reproduced using [older](https://github.com/AlxHnr/vim-spell-files/tree/master/spell) versions of the spell files, which give the following suggestions:

```
Change "Rasenmäher" to:
1 "Rasenmähern"
2 "Rasenmähers"
3 "Rasen Mäher"
4 "Rasen jäher"
5 "Rasen näher"
6 "Rasen zäher"
7 "Rase näher"
8 "Rasen mähre"
9 "Rasen Häher"
10 "Rassen Mäher"
11 "Rasenschere"
12 "Rasender"
13 "Rasen daher"
14 "Rasen mähen"
15 "Rasen mähe"
16 "Rauenscher"
17 "Randnäher"
...
```

# Steps to reproduce this bug

Usually Vim downloads spell files automatically. This feature is not available with `vim --clean`, so they have to be fetched manually. (Vims auto-download would fail on the .sug file anyways, so a manual download is unavoidable. I don't know why, but this is a separate issue).

Create a minimal runtime:

```sh
mkdir -p /tmp/vim-runtime/spell/
cd /tmp/vim-runtime/spell/
wget http://ftp.vim.org/pub/vim/runtime/spell/de.utf-8.spl
wget http://ftp.vim.org/pub/vim/runtime/spell/de.utf-8.sug
cd -
```

Start Vim and enter the following commands:

```vim
vim --clean
:set runtimepath+=/tmp/vim-runtime
:setlocal spell spelllang=de
iRasenmäher<esc>
z=
```

These issues also occur in Neovim v0.3.3.

# Recreating the broken spell files

I tried to build the .spl and .sug files myself, but ended up with the same results. Here is what I tried:

**Note**: The commands below have been tried with different env variables, locale settings, regenerating locales and installing my distributions German lang packs. All resulting in the same problem.

Output of `localectl status`:

```
   System Locale: LANG=de_DE.utf8
       VC Keymap: n/a
      X11 Layout: n/a
```

Output of `locale`:

```
LANG=de_DE.UTF-8
LC_CTYPE=de_DE.UTF-8
LC_NUMERIC=de_DE.UTF-8
LC_TIME=de_DE.UTF-8
LC_COLLATE=de_DE.UTF-8
LC_MONETARY=de_DE.UTF-8
LC_MESSAGES=de_DE.UTF-8
LC_PAPER=de_DE.UTF-8
LC_NAME=de_DE.UTF-8
LC_ADDRESS=de_DE.UTF-8
LC_TELEPHONE=de_DE.UTF-8
LC_MEASUREMENT=de_DE.UTF-8
LC_IDENTIFICATION=de_DE.UTF-8
LC_ALL=
```

Commands I used to build the spell files:

```sh
# Building upon the example from above:
cd /tmp/vim-runtime/spell/
rm *.sug *.spl

# Download files from LibreOffice, as described in runtime/spell/README.txt.
wget https://github.com/LibreOffice/dictionaries/raw/master/de/de_DE_frami.aff
wget https://github.com/LibreOffice/dictionaries/raw/master/de/de_DE_frami.dic
mv de_DE_frami.aff de_DE.aff
mv de_DE_frami.dic de_DE.dic

# Download and apply latest patch.
wget https://github.com/vim/vim/raw/master/runtime/spell/de/de_DE.diff

patch < de_DE.diff

# Build .spl and .sug file.
vim --clean +'mkspell! de de_DE' +q
```

Now repeat these steps to reproduce the bug:

```vim
vim --clean
:set runtimepath+=/tmp/vim-runtime
:setlocal spell spelllang=de
iRasenmäher<esc>
z=
```

**Comment by chrisbra** [comment] 2019-04-28 15:20
I have recently re-created the german dictionaries. However I am not sure there is anything I can do here, since it seems you can re-produce the problem :(

**Comment by blueyed** [comment] 2019-05-22 01:56
Looks like somewhere encoding (and therefore offsets etc) get messed up, and might need to be adjusted/converted (e.g. due to changes to the input files).

**Comment by ghid** [comment] 2019-05-22 06:58
Is it possible, that the word "Rasenmäher" is simply missing in the dictionary?

![image](https://user-images.githubusercontent.com/7606219/58153444-4b6a9100-7c6f-11e9-80be-a0f705371034.png)
(left: de-dictionary; right: my text)

**Comment by ghid** [comment] 2019-05-23 06:16
I've added "Rasenmäher" to the word list and rebuilt the spell file. Now "Rasenmäher" isn't marked as misspelled any more.

The suggestion list now looks like this:
![image](https://user-images.githubusercontent.com/7606219/58229797-e4161500-7d32-11e9-8f11-e96ebfd0aeae.png)

**Comment by AlxHnr** [comment] 2019-05-23 19:48
The problem is not that this particular word is missing. The issue is that German words usually don't contain zeros:

```
Change "Rasenmäher" to:
1 "-rasenmäher"
2 "Rasen0mäher"
3 "-rassenmäher"
4 "Rassen0mäher"
...
```

@ghid Your screenshot still contains unneeded dashes and whitespaces:
```
 1 "-rasenmäher"
...
 5 "Rase -mäher"
...
```

This word was included in previous versions of the dictionary files. I doubt they removed it.

**Comment by brammool** [comment] 2019-05-23 20:27
> The problem is not that this particular word is missing. The problem
> is that German words usually don't contain zeros:
> 
> ```
> Change "Rasenmäher" to:
> 1 "-rasenmäher"
> 2 "Rasen0mäher"
> 3 "-rassenmäher"
> 4 "Rassen0mäher"
> ...
> ```
> 
> @ghid Your screenshots still seem to contain unneeded dashes and whitespaces:
> ```
>  1 "-rasenmäher"
> ...
>  5 "Rase -mäher"
> ...
> ```
> 
> which isn't correct either.

This points to misinterpreting the rules for compounding.
That's probably also whey Rasenmäher is missing, I susped it is to be
compounded from Rasen and Mäher.

-- 
Anyone who is capable of getting themselves made President should on no
account be allowed to do the job.
		-- Douglas Adams, "The Hitchhiker's Guide to the Galaxy"

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by ghid** [comment] 2019-05-24 06:42
FYI: I'm getting a similar effect if I use the english dictonary...

![image](https://user-images.githubusercontent.com/7606219/58307640-987d6d00-7dff-11e9-93b8-be0998d93174.png)

**Comment by brammool** [comment] 2019-05-24 11:32
> FYI: I'm getting a similar effect if I use the english dictonary...
> 
> ![image](https://user-images.githubusercontent.com/7606219/58307640-987d6d00-7dff-11e9-93b8-be0998d93174.png)

That looks OK, it doesn't have weird dashes or zeroes.

-- 
How To Keep A Healthy Level Of Insanity:
3. Every time someone asks you to do something, ask if they want fries
   with that.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by ghid** [comment] 2019-05-27 12:37
First of all - please don't joke about me, I'm not really knowing what I'm doing here... 🙈 

But..., first I downloaded fresh copies of [de_DE_frami.aff](https://github.com/LibreOffice/dictionaries/blob/master/de/de_DE_frami.aff) and [de_DE_frami.dic](https://github.com/LibreOffice/dictionaries/blob/master/de/de_DE_frami.dic) from [LibreOffice/dictionaries](https://github.com/LibreOffice/dictionaries).

Then I patched `de_DE_frami.aff` with this [diff](https://github.com/ghid/vimfiles/blob/master/vimfiles/spell/de/de_DE.diff) and made a new spellfile with `:mkspell ...` as usual.

Now "Rasenmäher" isn't marked as mispelled anymore and I'm getting this list with suggestions:
![image](https://user-images.githubusercontent.com/7606219/58418097-199a6580-8087-11e9-92ef-bc83c1e57be6.png)

I saw, that the dict file contains `Rasen/Sij` and `Mäher/NSm` for example, therefore I changed the `COMPOUNDRULE` in the `.aff`-file to 

```
COMPOUNDRULE S*N*P*
```
which seems responsible for the result; but it still contains some zeroes and dashes though.

Does anybody know, which is the correct writing for that rule and are there more rules necessary or what else should be changed to get an optimal result?

**Comment by mcepl** [comment] 2019-07-24 23:31
Just to note that this is just completely wrong, and vim developers shouldn’t deal with stuff like this at all. Please, fix #846 (for example, by completing #2500), and be done with it.

**Comment by chrisbra** [comment] 2019-07-25 05:50
That comment is totally irrelevant, since it does not help getting the german spell files correct. I am not sure why you keep insisting on #2500, when you were in fact abandoning it, since you had no more interest in getting this in shape.

**Comment by brammool** [comment] 2019-07-25 11:41
Last time I tried Hunspell the suggestions for correction were quite bad.

**Comment by mcepl** [comment] 2019-07-25 16:51
> That comment is totally irrelevant, since it does not help getting the german spell files correct.

Well, strictly speaking, it does: my LibreOffice Writer has no problems with the word “Rasenmäher”.

```sh
~$ echo Rasenmäher|hunspell -d de_DE
Hunspell 1.7.0
-

~$
```

> I am not sure why you keep insisting on #2500, when you were in fact abandoning it, since you had no more interest in getting this in shape.

I keep insisting on it, because it is the only effort to actually do something about the disaster which is vim’s own spellchecker. Yes, it is unfinished, because you are so persuaded the crap which is in vim is the best thing in the world since the sliced bread, and nobody bothered to help to finish it. Yes, I agree, I am not entitled to your help, so I am just out of luck. It doesn’t mean it doesn’t frustrate me.

> Last time I tried Hunspell the suggestions for correction were quite bad.

Well, last time I tried LibreOffice Writer it didn’t mark “shouldn’t” as a typo.

</rant>

Sorry, shutting up. vim just have crappy spellchecker, but NIH rules, so nobody will ever do anything about it, and I should just get over it.

**Comment by Yamagi** [comment] 2019-07-29 10:26
The problem with "Rasenmäher" and other compounds isn't a bug or limitation of the spellchecker engine itself, it's caused by a broken dictionary. Luckily several years ago someone did the work to make the *Frami* dictionaries compatible with Vim: https://github.com/ganwell/vim-hunspell-dicts That dictionaries were always **much** better than the ones distributed with Vim. I wonder why they were never upstreamed.

Merging that work with an up to date *Frami* dictionary (taken from Libreoffice) isn't that hard. I gave it a try, the code is here: https://github.com/Yamagi/vim-german-dictionaries And binaries can be found here: https://github.com/Yamagi/vim-german-dictionaries/releases/tag/v0.0.1

Vims dictionary:
![vim_de_broken](https://user-images.githubusercontent.com/1224576/62041428-ef3a6500-b1fb-11e9-85c6-920ff998100e.png)

My *Frami* dictionary:
![vim_de_working](https://user-images.githubusercontent.com/1224576/62041445-f8c3cd00-b1fb-11e9-8553-ce93e153c29e.png)

**Comment by brammool** [comment] 2019-07-29 18:57
Yamagi wrote:

> The problem with "Rasenmäher" and other compounds isn't a bug or
> limitation of the spellchecker engine itself, it's caused by a broken
> dictionary. Luckily several years ago someone did the work to make the
> *Frami* dictionaries compatible with Vim:
> https://github.com/ganwell/vim-hunspell-dicts That dictionaries were
> always **much** better than the ones distributed with Vim. I wonder
> why the were never upstreamed.
> 
> Merging that work with an up to date *Frami* dictionary (taken from
> Libreoffice) isn't that hard. I gave it a try, the code is here:
> https://github.com/Yamagi/vim-german-dictionaries And binaries can be
> found here:
> https://github.com/Yamagi/vim-german-dictionaries/releases/tag/v0.0.1
> 
> Vims dictionary:
> ![vim_de_broken](https://user-images.githubusercontent.com/1224576/62041428-ef3a6500-b1fb-11e9-85c6-920ff998100e.png)
> 
> My *Frami* dictionary:
> ![vim_de_working](https://user-images.githubusercontent.com/1224576/62041445-f8c3cd00-b1fb-11e9-8553-ce93e153c29e.png)

Thanks for looking into a fix.

I notice that the affix files are missing the Vim improvements.
Specifically the SAL and MAP lines are missing, they greatly improve the
suggestions.

The FOL/LOW/UPP lines are also missing, I'm not sure how much this
matters.

There are a few other differences, please check it out and merge what
doesn't cause problems.

-- 
Our job was to build a computer information system for the branch banks.  We
were the perfect people for the job: Dean had seen a computer once, and I had
heard Dean talk about it.
				(Scott Adams - The Dilbert principle)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by Yamagi** [comment] 2019-07-30 10:12
Okay, I just pushed some updates to my repository:

* Convert the files to UTF-8. Shouldn't have any impact, UTF-8 is much easier to handle than ISO8859-1 these days.
* Some general cleanup. Add comments were necessary, remove unnecessary and unsupported statements, make clearer what statements belong together.
* Merge improvements from Vim.
* Add MAP and SAL statements for soundfoldings.

Binaries are here: https://github.com/Yamagi/vim-german-dictionaries/releases/tag/v0.0.2

**Comment by brammool** [comment] 2019-07-30 19:03
> Okay, I just pushed some updates to my repository:
> 
> * Convert the files to UTF-8. Shouldn't have any impact, UTF-8 is much easier to handle than ISO8859-1 these days.
> * Some general cleanup. Add comments were necessary, remove unnecessary and unsupported statements, make clearer what statements belong together.
> * Merge improvements from Vim.
> * Add MAP and SAL statements for soundfoldings.
> 
> Binaries are here: https://github.com/Yamagi/vim-german-dictionaries/releases/tag/v0.0.2

Thanks!

Looks like I can build a Vim spell file from this.  I do get a warning:
Duplicate word "Äthyl". That's indeed a duplicate.  There might be more,
Vim reports only the first one.

I used some text from a news site, and all words were recognized.

-- 
Engineers are always delighted to share wisdom, even in areas in which they
have no experience whatsoever.  Their logic provides them with inherent
insight into any field of expertise.  This can be a problem when dealing with
the illogical people who believe that knowledge can only be derived through
experience.
				(Scott Adams - The Dilbert principle)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by Yamagi** [comment] 2019-07-30 20:12
The duplicates are the same word with different affixes. `Äthyl/EPSm` and `Äthyl/m`, for example. There're 7366 such cases in de_DE_frami.dict alone. If they're really a problem the only feasible way to remove them would be by script, keep either the first or the last one. Doing it by hand would likely bring the best results but take days, if not weeks and make future updates much harder.

**Comment by brammool** [comment] 2019-07-31 18:40
> The duplicates are the same word with different affixes. `Äthyl/EPSm`
> and `Äthyl/m`, for example.

Right, and since "m" is included in the first line, the second line can
be dropped.

> There're 7366 such cases in de_DE_frami.dict alone. If they're really
> a problem the only feasible way to remove them would be by script,
> keep either the first or the last one. Doing it by hand would likely
> bring the best results but take days, if not weeks and make future
> updates much harder.

It's not a problem as such, but it may indicate that the .dic file has
an error.

I'll update runtime files, so that the new version gets out.  Let's see
what users think of it.

-- 
Engineers understand that their appearance only bothers other people and
therefore it is not worth optimizing.
				(Scott Adams - The Dilbert principle)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by Yamagi** [comment] 2019-08-01 08:33
Nice. Thank you. I've added a note to my repositories README and to avoid confusion.

**Comment by brammool** [comment] 2019-08-01 10:28
> Nice. Thank you. I've added a note to my repositories README and to
> avoid confusion.

Note that the spell files themselves are not on github, but can be
downloaded from the ftp server:
http://ftp.vim.org/vim/runtime/spell/

You can delete the spell files from $VIMRUNTIME/spell and they will be
downloaded once you need them.

-- 
I used to be indecisive, now I'm not sure.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment] 2019-09-09 16:19
closing.

**Closed as completed by chrisbra** 2019-09-09 16:19 UTC
