### ISSUE TITLE
wrong syntax highlighting for $((...) ....)

### ISSUE THREAD

**Issue by toralf** [vim/vim#11225] opened 2022-09-25 18:42 UTC
### Steps to reproduce

$ cat << EOF > x.sh
x="$( (echo x; echo y) | grep x)"
x="$x z"    # expected

x="$((echo x; echo y) | grep x)"
x="$x z"    # wrong
EOF

vi x.sh

shows line 5 x=printed in purple

### Expected behaviour

line 5 is printed in blue

### Version of Vim

# vim --version VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Aug 15 2022 17:07:37) Included patches: 1-99 Modified by Gentoo-9.0.0099 Compiled by portage@localhost

### Environment

# vim --version
VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Aug 15 2022 17:07:37)
Included patches: 1-99
Modified by Gentoo-9.0.0099
Compiled by portage@localhost

**Comment by lacygoill** [comment] 2022-09-25 18:55
Duplicate of https://github.com/vim/vim/issues/3847

---

FWIW, [shellcheck](https://github.com/koalaman/shellcheck) considers `$((` as [an error](https://www.shellcheck.net/wiki/SC1102):

    $ shellcheck x.sh

    In x.sh line 6:
    x="$((echo x; echo y) | grep x)"
       ^-- SC1102 (error): Shells disambiguate $(( differently or not at all. For $(command substitution), add space after $( . For $((arithmetics)), fix parsing errors.

    For more information:
      <https://www.shellcheck.net/wiki/SC1102 -- Shells disambiguate $(( different...>

**Comment by cecamp** [comment] 2022-09-25 20:23
As lacygoill says, changing the "$((...  to "$( (... and the highlighting will be correct. Its a question of interpreting that double open parenthesis.

**Closed as completed by cecamp** 2022-09-25 20:23 UTC
Labels: bug
