### ISSUE TITLE
Redirection of STDOUT and STDERR not working

### ISSUE THREAD

**Issue by macgruber99** [vim/vim#2099] opened 2017-09-16 16:22 UTC
After executing the following, both files are empty:

`vim --version > /tmp/version.out 2> /tmp/version.err`

If I just redirect STDOUT, I get what I expect.

**Comment by lacygoill** [comment] 2020-06-17 22:33
I can't reproduce:

    vim -u NONE --version > /tmp/version.out 2> /tmp/version.err

It works as expected.  `version.out` correctly contains the output of `$ vim -u NONE --version`.

If you can still reproduce, you need to bisect your config to find a [minimal example](https://en.wikipedia.org/wiki/Minimal_working_example) that other people can reliably reproduce on their machine.  Read this [faq entry](https://github.com/chrisbra/vim_faq/blob/de424bd8e08bcf0e6b1e0563ee49514dfed926ae/vim_faq.txt#L1153-L1228) for more information.

**Comment by tonymec** [comment] 2020-06-18 03:40
> After executing the following, both files are empty:
> 
> `vim --version > /tmp/version.out 2> /tmp/version.err`
> 
> If I just redirect STDOUT, I get what I expect.

@macgruber99 : Which Vim version? Which OS? Which shell?

I can't reproduce either, in Vim 8.2.998 (Big version) in bash 4.4.23(1) on openSUSE Linux 15.2 RC: after
```bash
vim --version >version.out 2>version.err
```
version.out contains the :version text and version.err is empty. If I do the same with a capital V in Vim, then version.out is empty and version.err contains the single line
```
Vim: command not found
```
because filenames (and program-names) are case-sensitive on Linux. Both are as expected.

Best regards,
Tony.

**Comment by k-takata** [comment] 2020-06-18 04:26
It doesn't look like a vim issue. Closing.

**Closed as completed by k-takata** 2020-06-18 04:26 UTC

**Comment by macgruber99** [comment] 2020-06-19 00:03
Hey guys, I opened this issue almost three years ago.  ;-)

I barely remember and don't remember any of the details other than what I put in the ticket.
