### ISSUE TITLE
Vim won't build with Python 3.8 anymore.

### ISSUE THREAD

**Issue by dertuxmalwieder** [vim/vim#5069] opened 2019-10-16 20:34 UTC
**Environment.**
- Windows 10, Visual Studio 2017.

**What worked:**
- Compiling Vim with Python 3.7.

**What does not work anymore:**
- Compiling Vim with Python 3.8.

      if_python3.obj : error LNK2001: Nicht aufgelöstes externes Symbol "__imp___Py_Dealloc".
      gvim.exe : fatal error LNK1120: 1 nicht aufgelöste Externe

I would assume that `if_python3.c`  needs a patch.

**Comment by eirnym** [comment] 2019-10-22 14:05
Can't reproduce with (at least) version 8.1.2198 and above. Please, check your plugins if any of them use `imp` module.

**Comment by k-takata** [comment] 2019-10-22 16:41
I haven't tried this yet, but I think this only occurs when compiled with python3/dyn.

**Comment by eirnym** [comment] 2019-10-22 18:46
as far as I investigated the problem:

in `configure` script
`vi_cv_path_python3_plibs` is populated correctly
while
`PYTHON3_LIBS` are not

Could you explain this?

result files are [here](https://gist.github.com/eirnym/3dea4558a85ebfe2bf8793e313a60425)

**Comment by mcepl** [comment] 2019-10-22 19:33
Isn’t this a duplicate of #4080?

**Comment by eirnym** [comment] 2019-10-22 20:18
@mcepl it is

**Comment by dertuxmalwieder** [comment] 2019-10-22 21:51
Yes, I usually compile with /dyn ...

No plugin involved:

https://tuxproject.de/projects/vim/_compile.bat.php

**Comment by k-takata** [comment] 2019-10-23 08:45
Closing as duplicate of #4080.

I posted a patch there. Please try.

**Closed as completed by k-takata** 2019-10-23 08:45 UTC
Labels: duplicate, if_python
