### ISSUE TITLE
Enabling the mouse by default was a regression

### ISSUE THREAD

**Issue by bleetube** [vim/vim#12621] opened 2023-07-01 14:31 UTC
### Steps to reproduce

Vim mouse is [enabled by default](https://github.com/vim/vim/blame/e7d9ca2b3bf99b0b759be8952e02c77110a354c1/runtime/defaults.vim#L83) for all xterms in `defaults.vim`.

 
When mouse mode is active, vim takes control of the mouse. As a side effect, copying buffers in most GUI terminals ceases to work. (Konsole, anything xterm based really, and iirc urxvt too)

Of course, anyone who does use mouse mode and wants the clipboard to still work while using a mouse can just recompile vim with +clipboard, apply some configuration, and carry on.
Or press shift to toggle control back to the terminal before clicking their mouse. I only discovered this when I found the original regression commit: https://github.com/vim/vim/commit/8c08b5b569e2a9e9f63dea514591ecfa2d3bb392

Note that most of the comments are critical of the change, but it has remained all these years.

I think this is a mistake, and I'm voicing my concern here.  I'll get on by fixing vim with `set mouse-=a` in all my dotfiles. Fine. But I'd bet fewer people are adopting vim after this commit than would otherwise.

I recommend reading the full comment thread on the original commit.

The fact that it ships with configuration to enable the mouse without the clipboard feature feels like a bug.

### Expected behaviour

New users to vim should not discover that it degrades their terminal by preventing copy to buffer.

### Version of Vim

9.0.1506

### Environment

OS: Archlinux
Terminal: Konsole
xterm-256color
bash

**Comment by tonymec** [comment] 2023-07-01 17:29
_The fact that it ships with configuration to enable the mouse without the clipboard feature feels like a bug._

I disagree. In the Linux console (Ctrl-Alt-F2 etc.) there is no connection to X11 therefore no clipboard; but when the gpm package is installed the mouse is available and in that case I expect configure and make to produce a Vim with +mouse_gpm and Vim to use the mouse at runtime.

**Comment by chrisbra** [comment] 2023-07-02 07:34
I am afraid it's way too late to discuss this behaviour now. Also, this is a duplicate of #2841 which turned out to be endless discussion without a clear resolution. 

I am closing this as duplicate.

**Closed as not planned** 2023-07-02 07:34 UTC
Labels: duplicate
