### ISSUE TITLE
Showbreak bug when visible lines end exactly at the last character

### ISSUE THREAD

**Issue by 0matgal0** [vim/vim#1686] opened 2017-05-07 09:13 UTC
`set wrap`
`set showbreak=..`

I have two lines like so:
![image](https://cloud.githubusercontent.com/assets/18264503/25779334/c3a92dfc-3315-11e7-897f-acd2382b4815.png)

On the first line i press `A` and look where cursor shows:
![image](https://cloud.githubusercontent.com/assets/18264503/25779336/dc14a696-3315-11e7-9bf0-d55fcb9ec2e7.png)

Is this how it's supposed to be? Because cursor now shows on (over) the second line, even though I'm appending text to the first line.

This is what happens with `nowrap`:
![image](https://cloud.githubusercontent.com/assets/18264503/25779346/0c998f7a-3316-11e7-9980-ad249e811dfe.png)

**Comment by alexeymuranov** [comment] 2017-05-07 09:43
Can you reproduce this starting Vim with  `vim -N -u NONE`?

**Comment by 0matgal0** [comment] 2017-05-07 10:05
Yes.

**Comment by chrisbra** [comment] 2017-05-07 19:32
I see the problem. I think this happens, because Vim is expecting you to enter something and as soon as you enter something, it will add the 'showbreak' setting to the line, so that the cursor won't be off anymore. It is a particularity, not sure if this classifies as bug and should be fixed.

**Comment by inkarkat** [comment] 2017-07-01 08:12
> It is a particularity, not sure if this classifies as bug and should be fixed.

To me, this definitely is a bug. Have another look at the second screenshot. Based on the cursor position, it appears that the next typed character would be inserted between the second and third `b` in the second line. In reality, it is appended at the end of the _first_ line!

So, there's a clear discrepancy between where Vim hints text would be entered, and what actually happens. If you type blindly, and then quit the buffer or move away, there's a real potential for wrong data entry. I've learned to recognize and ignore this particular situation, but it still makes you stop and annoys. Unless the fix means a complete rewrite of the rendering engine, please correct this!

**Comment by brammool** [comment] 2017-07-01 15:03
This only happens when 'number' is on.  Otherwise the cursor shows at the very start of the second line, not two characters to the right.

**Comment by zeertzjq** [comment] 2024-02-09 04:41
Does this bug still exist? I think it has been fixed.

**Comment by zeertzjq** [comment] 2024-02-09 04:49
Oh, actually #9884 is the same as this one, and it has been fixed.

**Comment by chrisbra** [comment] 2024-02-09 17:31
closing then as resolved.

**Closed as completed by chrisbra** 2024-02-09 17:31 UTC
