### ISSUE TITLE
Relative numer and scrollbind: no synced scrolling

### ISSUE THREAD

**Issue by mlopezgva** [vim/vim#1514] opened 2017-02-26 01:36 UTC
Hello.
When `:set rnu nu` and open two files for synced scrolling with `:windo set scrollbind` and start wandering around (keyboard or mouse,terminal or gtk) the position of th two files are not synced. If I deactivate the relative numbers (`:set nornu nu`) and start over (<kbd>gg</kbd> at the two buffers), and scroll down and up, both file scrolling are fine.

```
$ vim -N -u NONE -O file1 file2

:windo set rnu nu scrollbind
```
The synced file (not focused) cursor only starts moving after the cursor on the focused window reached either boundary.

```
:windo set nornu nu scrollbind
```
Works OK.

```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Feb 18 2017 22:56:36)
Parches incluidos: 1-313, 315-339
Modificado por pkg-vim-maintainers@lists.alioth.debian.org
Compilado por pkg-vim-maintainers@lists.alioth.debian.org
Versión "enorme" with GTK3 GUI.  Aspectos incluidos (+) o no (-):
+acl             +file_in_path    +mouse_sgr       +tag_old_static
+arabic          +find_in_path    -mouse_sysmouse  -tag_any_white
+autocmd         +float           +mouse_urxvt     +tcl
+balloon_eval    +folding         +mouse_xterm     +termguicolors
+browse          -footer          +multi_byte      +terminfo
++builtin_terms  +fork()          +multi_lang      +termresponse
+byte_offset     +gettext         -mzscheme        +textobjects
+channel         -hangul_input    +netbeans_intg   +timers
+cindent         +iconv           +num64           +title
+clientserver    +insert_expand   +packages        +toolbar
+clipboard       +job             +path_extra      +user_commands
+cmdline_compl   +jumplist        +perl            +vertsplit
+cmdline_hist    +keymap          +persistent_undo +virtualedit
+cmdline_info    +lambda          +postscript      +visual
+comments        +langmap         +printer         +visualextra
+conceal         +libcall         +profile         +viminfo
+cryptv          +linebreak       -python          +vreplace
+cscope          +lispindent      +python3         +wildignore
+cursorbind      +listcmds        +quickfix        +wildmenu
+cursorshape     +localmap        +reltime         +windows
+dialog_con_gui  +lua             +rightleft       +writebackup
+diff            +menu            +ruby            +X11
+digraphs        +mksession       +scrollbind      -xfontset
+dnd             +modify_fname    +signs           +xim
-ebcdic          +mouse           +smartindent     +xpm
+emacs_tags      +mouseshape      +startuptime     +xsmp_interact
+eval            +mouse_dec       +statusline      +xterm_clipboard
+ex_extra        +mouse_gpm       -sun_workshop    -xterm_save
+extra_search    -mouse_jsbterm   +syntax          
+farsi           +mouse_netterm   +tag_binary      
     archivo "vimrc" del sistema: "$VIM/vimrc"
     archivo "vimrc" del usuario: "$HOME/.vimrc"
  2º archivo "vimrc" del usuario: "~/.vim/vimrc"
      archivo "exrc" del usuario: "$HOME/.exrc"
    archivo "gvimrc" del sistema: "$VIM/gvimrc"
    archivo "gvimrc" del usuario: "$HOME/.gvimrc"
 2º archivo "gvimrc" del usuario: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
     archivo de menú del sistema: "$VIMRUNTIME/menu.vim"
            predefinido para $VIM: "/usr/share/vim"
Compilación: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/i386-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/mirclient -I/usr/include/mircommon -I/usr/include/mircookie -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng12 -I/usr/include/glib-2.0 -I/usr/lib/i386-linux-gnu/glib-2.0/include -Wdate-time  -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Enlazado: gcc   -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E  -Wl,-Bsymbolic-functions -fPIE -pie -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim   -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl  -L/usr/lib -llua5.2 -Wl,-E  -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/i386-linux-gnu/perl/5.22/CORE -lperl -ldl -lm -lpthread -lcrypt  -L/usr/lib/python3.5/config-3.5m-i386-linux-gnu -lpython3.5m -lpthread -ldl -lutil -lm -L/usr/lib/i386-linux-gnu -ltcl8.6 -ldl -lz -lpthread -lieee -lm -lruby-2.3 -lpthread -lgmp -ldl -lcrypt -lm     
```

Linux Mint 18 _Sarah_ XFCE 32bit Edition

**Comment by chrisbra** [comment] 2017-02-26 09:13
Are you sure? I cannot reproduce this issue. When you move down with the cursor and the second window actually starts to scroll, the first one does as well. However, since `'cursorbind'` is not set (and therefore the cursor stays at a different line), the relativenumbers are off, but that is expected. Both windows scroll fine however.

**Comment by mlopezgva** [comment] 2017-02-27 01:43
Yes, I noticed that issue at home and at job's station.

If relative numbers are on, although both windows move, cursors are at very different positions, also the displayed lines:: scrolling is done, but range shown are not the same (it's not a diff). I'll try the "cursorbind". However, this is not necessary when relative numbers are OFF, so this shouldn''t be an issue.

`--- 2 min. to test ---`

Well, with  `rnu cursorbind` I can get at least the "other" window cursor position synced after the current one scrolls up or down (not at cursor movement), which is an improvement.
With `cursorbind nornu nu` works like charm: both carets moving in sync, which is what I expected.

**Comment by chrisbra** [comment] 2017-02-27 14:59
I am not sure I understand. Just to make clear, where the cursor is, I used this command: `:windo set nornu nu scrollbind cursorline`.

Now regardless if I use nornu or rnu the scolling behaviour is always the same. (I used two identical files to test the behaviour). I don't see a problem here.

**Comment by mlopezgva** [comment] 2017-03-01 01:36
Sorry for the delay...

It seems like there's some kind of ackward behavior here... Today I've tried to reproduce the error and is working fine. I upgraded vim from the repository (see dump at first post) and now I can't do vim "go wrong".
~~Seems the issue has been solved, at least (or concealed... you know how bugs are like ;-)).~~

`$ vim -N -u NONE -O timm_tr_en.php en_v1.php -c 'windo set rnu nu'`

![imagen](https://cloud.githubusercontent.com/assets/996070/23442564/0e772e8a-fe08-11e6-9867-6dc5bae98907.png)

Then:

![imagen](https://cloud.githubusercontent.com/assets/996070/23442632/79f7f946-fe08-11e6-8a9c-efa0a7a4ffba.png)

As you can see, even with `crb` cursor lines are not synced.

Then, if I deactivate `:windo set nornu cursorline` relative numbers, I got the desired behavior:

![imagen](https://cloud.githubusercontent.com/assets/996070/23442716/fe87a198-fe08-11e6-9493-87292fdca851.png)

**Comment by chrisbra** [comment] 2017-03-01 07:09
how did you scroll?

**Comment by mlopezgva** [comment] 2017-03-01 17:13
I tried <kbd>CTRL-E</kbd> / <kbd>CTRL-Y</kbd>, <kbd>j</kbd> / <kbd>k</kbd>, <kbd>↑</kbd> / <kbd>↓</kbd>, <kbd>PgUp</kbd> / <kbd>PgDown</kbd> and `MouseScroll`.

**Comment by chrisbra** [comment] 2017-03-01 18:49
can you make a step by step reproducible example please?

**Comment by mlopezgva** [comment] 2017-03-01 20:26
Sure.

It is worth to note that, after the lass step, if I reactivate the relative numbers, it seems to work fine.

1. `vim -N -u NONE -O .vimrc .vimrc`
    ![captura de pantalla de 2017-03-01 16 31 50](https://cloud.githubusercontent.com/assets/996070/23477602/452f3bbc-fe9d-11e6-82b0-e37dea86828e.png)
2. set relative numering and scrollbind. That's OK as per your explanation: even if scroll is bound, cursor movement is not
    ![captura de pantalla de 2017-03-01 16 32 00](https://cloud.githubusercontent.com/assets/996070/23477599/452c3232-fe9d-11e6-876c-4d28aabbf8d9.png)
    ![captura de pantalla de 2017-03-01 16 32 38](https://cloud.githubusercontent.com/assets/996070/23477601/452ea206-fe9d-11e6-9527-6e29da6a6e94.png)
3. However, if I setup `cursorbind`, it still doesn't syncs the cursor positions:
![captura de pantalla de 2017-03-01 16 32 51](https://cloud.githubusercontent.com/assets/996070/23477600/452e6df4-fe9d-11e6-81cf-990bd6265269.png)
![captura de pantalla de 2017-03-01 16 33 15](https://cloud.githubusercontent.com/assets/996070/23477603/4538c84e-fe9d-11e6-9d3e-e34be5a71a1c.png)
![captura de pantalla de 2017-03-01 16 33 21](https://cloud.githubusercontent.com/assets/996070/23477598/452be8e0-fe9d-11e6-8212-5637a098f3a0.png)
4. But, if I deactivate relative numbering, it starts working fine!
![captura de pantalla de 2017-03-01 16 33 45](https://cloud.githubusercontent.com/assets/996070/23477605/455661e2-fe9d-11e6-9c6d-8a9645eb0a66.png)
4.a. I have also set cursorline on to mark the current line:
![captura de pantalla de 2017-03-01 16 34 29](https://cloud.githubusercontent.com/assets/996070/23477608/455ced32-fe9d-11e6-8cb2-6a553a569e25.png)
![captura de pantalla de 2017-03-01 16 34 39](https://cloud.githubusercontent.com/assets/996070/23477606/455712a4-fe9d-11e6-9b4f-7a09e34bc33d.png)
![captura de pantalla de 2017-03-01 16 34 52](https://cloud.githubusercontent.com/assets/996070/23477607/4558261c-fe9d-11e6-83ae-678e842e10fe.png)
![captura de pantalla de 2017-03-01 16 34 59](https://cloud.githubusercontent.com/assets/996070/23477609/455d5088-fe9d-11e6-8559-6c5f8cf613e0.png)
![captura de pantalla de 2017-03-01 16 35 12](https://cloud.githubusercontent.com/assets/996070/23477610/456ae612-fe9d-11e6-9621-daad4722438a.png)
![captura de pantalla de 2017-03-01 16 35 17](https://cloud.githubusercontent.com/assets/996070/23477611/457271a2-fe9d-11e6-8e9e-2ef38d482670.png)

**Comment by lacygoill** [comment] 2020-06-16 11:49
According to `git-bisect(1)`, this was fixed by https://github.com/vim/vim/commit/bd9a53c06c8869ad811cb3dd01a309c9be7d7a63.

**Comment by chrisbra** [comment] 2020-06-16 12:04
closing then.

**Closed as completed by chrisbra** 2020-06-16 12:04 UTC
