### ISSUE TITLE
'foldenable' is tuned off after diff mode

### ISSUE THREAD

**Issue by rickhowe** [vim/vim#11733] opened 2022-12-20 08:58 UTC
### Steps to reproduce

By default, `foldenable` is on on both windows:

![aaa](https://user-images.githubusercontent.com/3096934/208621500-e780329a-7155-48da-bb14-a2547e7263aa.png)

After doing `:diffthis` on both. `foldenable` is still on on both:

![bbb](https://user-images.githubusercontent.com/3096934/208621545-b8f1450a-9b23-4e62-a398-dcc4784f5937.png)

Then, do `:diffoff!`, `foldenable` is turned off:

![ccc](https://user-images.githubusercontent.com/3096934/208621578-4d27b079-e576-41f8-af0a-a31aa51f164a.png)

If `foldenable'`is turned to be on, the fold lines in diff mode is resumed and displayed:

![ddd](https://user-images.githubusercontent.com/3096934/208621609-47f32833-d4fc-4b68-bdc6-32ff8828b1d7.png)

### Expected behaviour

'foldenable' is not turned off after diff mode.

### Version of Vim

9.0.1082 (looks like it also happens in 8.0)

### Environment

Windows 10

**Comment by chrisbra** [comment] 2022-12-20 13:41
Hm, there is a comment here, to only restore the `foldenable` setting, if it wasn't set before:

https://github.com/vim/vim/blob/418b54788106efd94bbc71a4b100afae1080cbfc/src/diff.c#L1583-L1596

And indeed, if you set your foldmethod to something other than `manual` before entering diff mode, the `foldenable` option won't be reset after switching off diff mode. So it is intentionally, but not sure this should be changed back.

**Comment by brammool** [comment] 2022-12-20 15:02
> ### Steps to reproduce
> 
> By default, `foldenable` is on on both windows:
> 
> ![aaa](https://user-images.githubusercontent.com/3096934/208621500-e780329a-7155-48da-bb14-a2547e7263aa.png)
> 
> After doing `:diffthis` on both. `foldenable` is still on on both:
> 
> ![bbb](https://user-images.githubusercontent.com/3096934/208621545-b8f1450a-9b23-4e62-a398-dcc4784f5937.png)
> 
> Then, do `:diffoff!`, `foldenable` is turned off:
> 
> ![ccc](https://user-images.githubusercontent.com/3096934/208621578-4d27b079-e576-41f8-af0a-a31aa51f164a.png)
> 
> If `foldenable'`is turned to be on, the fold lines in diff mode is resumed and displayed:
> 
> ![ddd](https://user-images.githubusercontent.com/3096934/208621609-47f32833-d4fc-4b68-bdc6-32ff8828b1d7.png)
> 
> ### Expected behaviour
> 
> 'foldenable' is not turned off after diff mode.

The problem is that then folds would show up, the ones created in diff
mode.  That is very unlikely what you want.  As Christian mentioned,
this is related to 'foldmethod' being manual.

I'm actually not sure why you would expect 'foldenable' to be on.  It's
not like "diffoff" promises to completely restore the situation before
diff mode was entered.

-- 
ARTHUR:  I am your king!
WOMAN:   Well, I didn't vote for you.
ARTHUR:  You don't vote for kings.
WOMAN:   Well, 'ow did you become king then?
                                  The Quest for the Holy Grail (Monty Python)

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by rickhowe** [comment] 2022-12-21 09:15
`:h diffoff` says:
The `:diffoff` command resets the relevant options to the values they had when using `:diffsplit`, `:diffpatch` , `:diffthis`. or starting Vim in diff mode.

So, I thought `foldenable` has been left unchanged. But after diff mode, it is unknowingly changed to no, it looks an unnatural behavior. However, if it is a kind of long-time original behavior, I have no strong reason to change it now. It might be better to describe in help though.

**Comment by chrisbra** [comment] 2022-12-23 14:43
So how about the following doc-patch:
```diff
diff --git a/runtime/doc/diff.txt b/runtime/doc/diff.txt
index 1c93de4d7..cd6f30cfb 100644
--- a/runtime/doc/diff.txt
+++ b/runtime/doc/diff.txt
@@ -148,6 +148,10 @@ Otherwise they are set to their default value:
        'foldmethod'    "manual"
        'foldcolumn'    0

+Note: 'foldenable' will most-likely be reset to off (more accurate: it depends
+on the whether 'foldmethod' is set to "manual"  before starting diff mode)
+Rationale: otherwise even after finishing the diff mode, buffers would still
+display the diff mode folding.
 ==============================================================================
 2. Viewing diffs                                               *view-diffs*

```

**Comment by brammool** [comment] 2022-12-24 22:34
I'll include something like that in the help.  Is that sufficient to close this issue?

**Comment by chrisbra** [comment] 2022-12-25 10:18
let's close it then :)

**Closed as completed by chrisbra** 2022-12-25 10:18 UTC
Labels: documentation, bug
