### ISSUE TITLE
git mergetool use vimdiff, vimrc &diff is 0

### ISSUE THREAD

**Issue by aohan237** [vim/vim#10934] opened 2022-08-17 10:28 UTC
### Steps to reproduce

set git merge tool using vimdiff

using git mergetool

vimrc :
echo &diff

### Expected behaviour

echo 1 but echo 0

using standalone vimdiff echo 1

### Version of Vim

9.0.200

### Environment

mac

**Comment by chrisbra** [comment] 2022-08-17 10:43
most likely, diff mode is enabled after the vim has completely started up (and after `.vimrc`) is read. Run it interactively using `:echo &diff` or in a `VimEnter` autocommand. I don't think this is a bug here.

**Comment by vim-ml** [comment] 2022-08-17 16:08
On 2022-08-17, Christian Brabandt wrote:
> most likely, diff mode is enabled after the vim has completely started up (and
> after .vimrc) is read. Run it interactively using :echo &diff or in a VimEnter
> autocommand. I don't think this is a bug here.

Something funny is going on, though.  When I try that experiment on
my Ubuntu 20.04 system with Vim 9.0, &diff is 1.

I've had one or more tests of "if &diff" in my vimrc for years and
they have always worked as expected.

Here is the mergetool section of my ~/.gitconfig, for what it's
worth.

    [merge]
        tool = vimdiff
        trustExitCode = true
        conflictStyle = diff3

    [mergetool "vimdiff"]
        cmd = "vim -d -c '4wincmd w | wincmd J | wincmd =' $LOCAL $BASE $REMOTE $MERGED"

Maybe there's something different about some of this on a Mac.

Regards,
Gary

**Comment by aohan237** [comment] 2022-08-18 02:11
> 

i just only use tool as vimdiff ,but has no startup cmd
```
[mergetool "vimdiff"]
cmd = "vim -d -c '4wincmd w | wincmd J | wincmd =' $LOCAL $BASE $REMOTE $MERGED"
```
this section makes it right.

but is there any explanation on this, git or vimdiff seems no doc on this, and cant google it out

**Comment by aohan237** [comment] 2022-08-18 02:13
@chrisbra  maybe the way git mergetool use vimdiff cause this.

@vim-ml 's cmd solution goes right. maybe i should ask git for an answer, there is no doc on this feature

**Comment by vim-ml** [comment] 2022-08-18 05:05
On 2022-08-17, aohan237 wrote:
> @chrisbra maybe the way git mergetool use vimdiff cause this.
> 
> @vim-ml 's cmd solution goes right. maybe i should ask git for an answer, there
> is no doc on this feature

I don't know whether you saw my earlier, lengthy reply to Chris, but
that answered the question of _what_ changed in git.  The URL that
Chris posted explains a little of the _why_, but not all.  It just
said that they made the mergetool better, but it didn't explain how
the new way was better.

What the git developers did was to change the mergetool command that
diffs the various versions of the file being merged.  They used to
start the command with "vim -f -d ...", which started vim in diff
mode so that &diff was 1 when vimrc was sourced.  They changed the
command to start with "vim -f -c 'echo | ..." and somewhere in that
command they execute diffthis in a loop.  Consequently, that command
does not put vim into diff mode when it starts and vimrc is sourced
when &diff is 0.

It is not clear at all to me why someone thought the new mergetool
command was in some way better than the old one.

The problem is solely due to the change made in git.

I thought that the mergetool command was documented somewhere in the
git documentation, but I haven't looked for it in a long while.  You
_might_ find some explanation for the change in the git mailing list
archives or in the git log of the git repository, but not all
developers explain their reasoning very well.  The git mailing list
would be the place to ask about this.

Regards,
Gary

**Comment by aohan237** [comment] 2022-08-18 06:33
@vim-ml  
>I don't know whether you saw my earlier, lengthy reply to Chris, but
that answered the question of _what_ changed in git.  The URL that
Chris posted explains a little of the _why_, but not all.  It just
said that they made the mergetool better, but it didn't explain how
the new way was better.

i did not see your lengthy reply to Chris and what he posted, perhaps in other issues or somewhere else.

i read the git-scm doc [git-scm](https://git-scm.com/docs/git-mergetool) and the git man page,  there is no explanations on this.

maybe the git mailing list is the right place to ask.

thanks, best regards

**Closed as completed** 2022-08-18 06:34 UTC
Labels: bug

**Comment by chrisbra** [comment] 2022-08-18 06:42
I think the change by git was done to make the layout for vim more flexible, so that you do not need to specify `vimdiff1`, `vimdiff2`, `vimdiff3` etc. It's explained by the author here: https://u92.eu/blog/git-vimdiff/

If you think there is a bug with this, I'd recommend to take this to the git developers mailinglist.

**Comment by aohan237** [comment] 2022-08-18 06:46
@chrisbra  thanks, i will read it
