### ISSUE TITLE
Empty parts of the window are not updated while scrolling or changing tabs

### ISSUE THREAD

**Issue by serhatcevikel** [vim/vim#2284] opened 2017-11-04 11:29 UTC
After the 8.0.1159 or 8.0.1176 release, when vim is invoked inside tmux, the empty parts of the window is not updated on page down/up or change tab actions. So the window messes up current view with previous views.

Other editors such as nano do not have similar issues when invoked inside tmux. So the problem is with vim. And vim does not have the issue when invoked outside tmux.

I am using archlinux. In order to see whether the problem is with the binary packages, I compiled both vim and tmux from source and the issue persists.

In order to recreate the situation, you should start vim inside tmux and create a document longer than the current view and with lines of different length and either go pg up or down or open a new tab and switch betwen.

**Comment by chrisbra** [comment] 2017-11-04 16:44
can you bisect, which commit causes it?

**Comment by brammool** [comment] 2017-11-04 20:02
Serhat Cevikel wrote:

> After the 8.0.1159 or 8.0.1176 release, when vim is invoked inside
> tmux, the empty parts of the window is not updated on page down/up or
> change tab actions. So the window messes up current view with previous
> views.
> 
> Other editor such as nano do not have similar issues when invoked
> inside tmux. So the problem is with vim. And vim does not have the
> issue when invoked outside tmux.
> 
> I am using archlinux. In order to see whether the problem is with the
> binary packages, I compiled both vim and tmux from source and the
> issue persists.
> 
> In order to recreate the situation, you should start vim inside tmux
> and create a document longer than the current view and with lines of
> different length and either go pg up or down or open a new tab and
> switch betwen.

I cannot reproduce this problem.

-- 
It is illegal to take more than three sips of beer at a time while standing.
		[real standing law in Texas, United States of America]

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment] 2021-04-06 07:16
I cannot reproduce either, and I'm always inside tmux.

**Comment by chrisbra** [comment] 2021-04-06 08:26
so let's close it for now.

**Closed as completed by chrisbra** 2021-04-06 08:26 UTC
