### ISSUE TITLE
sh.vim incorrectly highlighting if/fi

### ISSUE THREAD

**Issue by jmreicha** [vim/vim#636] opened 2016-02-15 23:45 UTC
OS: `OS X 10.11.3`
vim version: `7.4 (2013 Aug 10, compiled Feb 11 2016 11:34:55)`
Info for filetype: `sh`

To reproduce:

```
#!/usr/bin/env bash
if ! which "xcode-select" > /dev/null; then
    echo "No xcode"
else
    xcode-select --install
fi
```

The select in xcode-select seems to be causing the problem? If I remove the --install flag the highlight error goes away.

**Comment by mattn** [comment] 2016-02-23 07:04
try following on cursor at `--install`.

```
:echo synIDattr(synID(line("."), col("."), 1), "name")
```

what do you get?

**Comment by jmreicha** [comment] 2016-02-26 22:34
@mattn I get `shCaseEsac` when I run the command you mentioned, just after the `--install` flag.  I get `shConditional` if I run the above before the `--install` flag.

Does that sound right?

**Comment by mattn** [comment] 2016-02-27 01:40
I get `shOption` instead. Do you use something plugin for sh?

**Comment by jmreicha** [comment] 2016-02-29 18:26
I am using a few custom plugins but I still see the same behavior with all of my plugins uninstalled/off.

**Comment by chrisbra** [comment] 2016-02-29 18:55
okay, closing then.

**Comment by jmreicha** [comment] 2016-02-29 19:02
@chrisbra I still see the behavior with plugins turned off, I still haven't found a workaround.  Can we keep this open until a resolution is found?

**Comment by chrisbra** [comment] 2016-02-29 19:05
Well, what is the output of the synID command given above? It does not seem reproducible.

**Comment by jmreicha** [comment] 2016-02-29 19:10
With no plugins installed:

With the cursor before the `--install` flag I get `shConditional`.  With the cursor after the `--install` flag I get `shCaseEsac`.

**Comment by mattn** [comment] 2016-03-01 01:30
Could you please try below?

```
$ vim -u NONE -N your.sh
:syntax on
  ... move cursor into `--install` above ...
:echo synIDattr(synID(line("."), col("."), 1), "name")
```

I get shOption.

**Comment by jmreicha** [comment] 2016-03-01 18:41
@mattn I followed your suggestion, with the same result.  Inside of the `--install` flag I get `shCaseEsac`, with the cursor positioned before the `--install` flag I get `shConditional`.

![image](https://cloud.githubusercontent.com/assets/1039098/13437620/16a651d6-df9a-11e5-8509-ca31a5ee23b6.png)

![image](https://cloud.githubusercontent.com/assets/1039098/13437613/0866bcfa-df9a-11e5-8072-5671102a0d8a.png)

![image](https://cloud.githubusercontent.com/assets/1039098/13437640/29575a14-df9a-11e5-910a-dd0fa072de00.png)

![image](https://cloud.githubusercontent.com/assets/1039098/13437646/30207ccc-df9a-11e5-89a0-caa97caa15a5.png)

**Comment by chrisbra** [comment] 2016-03-01 18:52
I think, the problem is this line from sh.vim (distributed with vim):

```
syn region shCaseEsac matchgroup=shConditional start="\<select\s" matchgroup=shConditional end="\<in\>" end="\<do\>" contains=@shLoopList
```

which matches the xcode-select command. Something like this might work:

``` patch
diff --git a/runtime/syntax/sh.vim b/runtime/syntax/sh.vim
index 15a00eb..cbf10fb 100644
--- a/runtime/syntax/sh.vim
+++ b/runtime/syntax/sh.vim
@@ -240,7 +240,7 @@ if exists("b:is_kornshell") || exists("b:is_bash")
  syn cluster shFunctionList    add=shRepeat
  syn region shRepeat   matchgroup=shLoop   start="\<while\_s" end="\<in\_s" end="\<do\>"me=e-2 contains=@shLoopList,shDblParen,shDblBrace
  syn region shRepeat   matchgroup=shLoop   start="\<until\_s" end="\<in\_s" end="\<do\>"me=e-2 contains=@shLoopList,shDblParen,shDblBrace
- syn region shCaseEsac matchgroup=shConditional start="\<select\s" matchgroup=shConditional end="\<in\>" end="\<do\>" contains=@shLoopList
+ syn region shCaseEsac matchgroup=shConditional start="-\@<!\<select\s" matchgroup=shConditional end="\<in\>" end="\<do\>" contains=@shLoopList
 else
  syn region shRepeat   matchgroup=shLoop   start="\<while\_s" end="\<do\>"me=e-2               contains=@shLoopList
  syn region shRepeat   matchgroup=shLoop   start="\<until\_s" end="\<do\>"me=e-2               contains=@shLoopList
```

**Comment by jmreicha** [comment] 2016-03-01 18:57
@chrisbra That looks promising.  Can I just drop that line in to my sh.vim or will it need to be recompiled?

**Comment by chrisbra** [comment] 2016-03-01 20:20
See the [vim-dev ml](https://groups.google.com/d/msg/vim_dev/gyDDzbeAQKA/48X1DZkZFAAJ) for the solution.

**Closed as completed by chrisbra** 2016-03-01 20:20 UTC

**Comment by jmreicha** [comment] 2016-03-01 20:30
Thanks.  I was unaware there was a thread going in parallel to this.
