### ISSUE TITLE
Search opens wrong fold

### ISSUE THREAD

**Issue by kurkale6ka** [vim/vim#794] opened 2016-05-10 10:09 UTC
When I open a file with folds and search for `world`, I get the second match instead of the first one, that second match being located in the second fold.

Steps to reproduce:
`\vim -nNX -u NONE -c'se fdm=marker' /tmp/test_file`

```
--- {{{1
hello world
--- {{{1
hello world
--- {{{1
hello world
```

`/world`

Version:

```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Mar 30 2016 14:46:23)
Included patches: 1-1689                                          
```

**Comment by brammool** [comment] 2016-05-10 16:19
> When I open a file with folds and search for `world`, I get the second match instead of the first one, that second match being located in the second fold.
> 
> Steps to reproduce:
> `\vim -nNX -u NONE -c'se fdm=marker' /tmp/test_file`
> 
> ```
> --- {{{1
> hello world
> --- {{{1
> hello world
> --- {{{1
> hello world
> ```
> 
> `/world`

I think this works as intended. If your search starts inside a closed
fold, it's like it starts at the end of the fold, thus finds only a
match in a line below it.
If you add a line above the first fold the match is in the first fold.

## 

Clothes make the man.  Naked people have little or no influence on society.
                               -- Mark Twain (Samuel Clemens) (1835-1910)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment] 2016-05-10 17:24
I also don't think this is a bug and it is documented at :h fold-behaviour I am closing this therefore.

**Closed as completed by chrisbra** 2016-05-10 17:24 UTC
