### ISSUE TITLE
--clean flag does not enable nocompatible mode

### ISSUE THREAD

**Issue by sheerun** [vim/vim#7002] opened 2020-09-23 13:49 UTC
_Instructions: Replace the template text and remove irrelevant text (including this line)_

**Describe the bug**

The `vim --help` says:

```
--clean		'nocompatible', Vim defaults, no plugins, no viminfo
```

But is seems to not be the case for nocompatible, as shown below:

**To Reproduce**

First, here's output for -N flag that actually works:

```
$ vim -N -u /dev/null -c 'set t_te= | echo &cpo | q'
aABceFs
```

Here the output if --clean flag is used:

```
$ vim --clean -u /dev/null -c 'set t_te= | echo &cpo | q'
aAbBcCdDeEfFgHiIjJkKlLmMnoOpPqrRsStuvwWxXyZ$!%*-+<>;
```

**Expected behavior**

--clean flag should set nocompiable mode, just like -N flag

**Environment (please complete the following information):**

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Sep 16 2020 23:47:44)
macOS version
Included patches: 1-1700
Compiled by Homebrew

 - OS: MacOS 10.15
 - Terminal: iTerm2

**Comment by chrisbra** [comment] 2020-09-23 14:04
I have seen this issue, if vim has been unable to find the defaults.vim scriptfile. You can check by issuing the `:scriptnames` command. 

I suppose this is a self-compiled version. Did you install it correctly or is vim looking for defaults.vim in the wrong directory? Check the `:version` output. Also check, if you have defined $VIMRUNTIME environment variable.

**Comment by tonymec** [comment] 2020-09-23 15:04
@sheerun : IOW, when inside Vim, the $VIMRUNTIME environment variable should point to the directory where the present Vim installed its `defaults.vim`, `filetype.vim`, `optwin.vim` and a number of other files, most of which are implicitly sourced by some built-in ex-commands.

In most cases $VIMRUNTIME is set correctly by Vim at startup if it is not set outside of Vim, especially if $VIM (which Vim also sets at startup) is also not set outside of Vim.

**Comment by sheerun** [comment] 2020-09-23 15:33
This vim version is version installed from homebrew:

```
ls -la $(which vim)
lrwxr-xr-x 1 sheerun admin 30 Sep 23 15:44 /usr/local/bin/vim -> ../Cellar/vim/8.2.1700/bin/vim
```

`$VIMRUNTIME` is empty. 

Here's full `:version`:

```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Sep 16 2020 23:47:44)
macOS version
Included patches: 1-1700
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl               +cmdline_info      -farsi             +langmap           +mouse_sgr         +profile           +tag_binary        +virtualedit
+arabic            +comments          +file_in_path      +libcall           -mouse_sysmouse    -python            -tag_old_static    +visual
+autocmd           +conceal           +find_in_path      +linebreak         +mouse_urxvt       +python3           -tag_any_white     +visualextra
+autochdir         +cryptv            +float             +lispindent        +mouse_xterm       +quickfix          -tcl               +viminfo
-autoservername    +cscope            +folding           +listcmds          +multi_byte        +reltime           +termguicolors     +vreplace
-balloon_eval      +cursorbind        -footer            +localmap          +multi_lang        +rightleft         +terminal          +wildignore
+balloon_eval_term +cursorshape       +fork()            +lua               -mzscheme          +ruby              +terminfo          +wildmenu
-browse            +dialog_con        +gettext           +menu              +netbeans_intg     +scrollbind        +termresponse      +windows
++builtin_terms    +diff              -hangul_input      +mksession         +num64             +signs             +textobjects       +writebackup
+byte_offset       +digraphs          +iconv             +modify_fname      +packages          +smartindent       +textprop          -X11
+channel           -dnd               +insert_expand     +mouse             +path_extra        -sound             +timers            -xfontset
+cindent           -ebcdic            +ipv6              -mouseshape        +perl              +spell             +title             -xim
-clientserver      +emacs_tags        +job               +mouse_dec         +persistent_undo   +startuptime       -toolbar           -xpm
+clipboard         +eval              +jumplist          -mouse_gpm         +popupwin          +statusline        +user_commands     -xsmp
+cmdline_compl     +ex_extra          +keymap            -mouse_jsbterm     +postscript        -sun_workshop      +vartabs           -xterm_clipboard
+cmdline_hist      +extra_search      +lambda            +mouse_netterm     +printer           +syntax            +vertsplit         -xterm_save
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: clang   -L. -fstack-protector-strong -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl@1.1/lib -L/usr/local/opt/readline/lib
-L/usr/local/lib -o vim        -lncurses -liconv -lintl -framework AppKit  -L/usr/local/opt/lua/lib -llua5.3 -mmacosx-version-min=10.15 -fstack-protector-st
rong -L/usr/local/lib  -L/usr/local/Cellar/perl/5.32.0/lib/perl5/5.32.0/darwin-thread-multi-2level/CORE -lperl -lm -lutil -lc  -L/usr/local/opt/python@3.8/F
rameworks/Python.framework/Versions/3.8/lib/python3.8/config-3.8-darwin -lpython3.8 -framework CoreFoundation  -lruby.2.
```

Even if Homebrew for some reason is compiling vim wrong, the `-N` flag doesn't care what's the runtime directory. I think it would be good if `--clean` wouldn't care as well.

**Comment by chrisbra** [comment] 2020-09-23 15:43
> $VIMRUNTIME is empty.

Is this from within Vim or from your terminal?

> defaults file: "$VIMRUNTIME/defaults.vim"

So does it exist? Try `:e $VIMRUNTIME/defaults.vim`. 

>  I think it would be good if --clean wouldn't care as well.

`--clean` means vim will set `nocompatible` because of defaults.vim. If that file is not found, Vim will stay in compatible mode. 

I actually wondered before if it should complain, if it is not found, but since I have never heard of complaints before, I did not bother further :/

**Comment by brammool** [comment] 2020-09-23 15:49
Well, you do "vim --clean -u /dev/null"  which, besides using "clean" also says not to use any startup script.
And then defaults.vim isn't loaded, not what you want.  So drop the "-u /dev/null" part and it should work.

**Comment by tonymec** [comment] 2020-09-23 15:54
I *think* that `vim --V1 --clean` will complain if `$VIMRUNTIME/defaults.vim` is not found. However, `:scriptnames`, **from inside Vim**, would tell you more surely: `defaults.vim`, if found, would be near the top (probably the very first one if Vim is invoked with `--clean`).

Best regards,
Tony.

**Comment by sheerun** [comment] 2020-09-23 15:59
From terminal. In vim it's /usr/local/share/vim/vim82 which contains all runtime files, including defaults.vim

```
$ vim --clean -u /dev/null -c 'set t_te= | echo $VIMRUNTIME | q'
/usr/local/share/vim/vim82
```

> So does it exist? Try :e $VIMRUNTIME/defaults.vim.

It does

> Well, you do "vim --clean -u /dev/null" which, besides using "clean" also says not to use any startup script.
And then defaults.vim isn't loaded, not what you want. So drop the "-u /dev/null" part and it should work.

It indeed "fixes" this issue, but it's not what `--clean` and `-u` is documented to do in `--help`

In particular:

- `-u <vimrc>` is said to `Use <vimrc> instead of any .vimrc`, but when I create empty .vimrc and run `vim --clean -c 'set t_te= | echo &cpo | q'` it happily sets nocompatible mode correctly. Shoudn't empty .vimrc work the same as `-u /dev/null`?
- `--clean` says just `'nocompatible', Vim defaults, no plugins, no viminfo`, it doesn't mention it won't work if you use `-u /dev/null` (but you can use empty .vimrc)
- In my case I'm not setting `-u /dev/null` (this is just for reproduction) but actually there's `-u somefile.vim` where there are commands to instantiate and test my plugin (i.e. what user would have in their .vimrc). In such case `--clean` flag doesn't work as well.

All I'm saying that I'd expect `--clean` to unconditionally set nocompatible mode :)

**Comment by sheerun** [comment] 2020-09-23 16:06
Hmm another note, the order of arguments matters:

```
vim -u /dev/null --clean -c 'set t_te= | echo &cpo | q'
```

works, while:

```
vim --clean -u /dev/null -c 'set t_te= | echo &cpo | q'
```

doesn't work

I think this is the source of this bug. `--clean` should always be considered last, even if it's before -u /dev/null

**Comment by chrisbra** [comment] 2020-09-23 16:22
> --clean says just 'nocompatible', Vim defaults, no plugins, no viminfo, it doesn't mention it won't work if you use -u /dev/null (but you can use empty .vimrc) 

I don't see this:

https://github.com/vim/vim/blob/6bf1b52ba2816dffdbd0d994320abfb1586bf666/runtime/doc/starting.txt#L506-L515

it clearly states, that the defaults.vim file will be loaded which will cause the `compatible` setting to be disabled.

> there's -u somefile.vim where there are commands to instantiate and test my plugin (i.e. what user would have in their .vimrc). 

BTW: For such a case, I always have the `set nocp` in that init file.

**Comment by sheerun** [comment] 2020-09-23 16:32
> I think this is the source of this bug. --clean should always be considered last, even if it's before -u /dev/null

Never mind, it "works" because --clean after -u resets -u

> I don't see this:

I mean the output of `vim --help`: 

```
-u <vimrc>		Use <vimrc> instead of any .vimrc
--clean		'nocompatible', Vim defaults, no plugins, no viminfo
```

I think at least documentation for both `-u` and `--clean` could be fixed in `--help`. The first one clearly doesn't just change .vimrc to be loaded, and second one doesn't always enable nocompatible mode

**Comment by chrisbra** [comment] 2020-09-23 18:12
> I mean the output of vim --help:

Can you suggest a better wording?

**Comment by sheerun** [comment] 2020-09-23 18:47
```
   -u <file>            Initialize Vim with <file> (see ":help -u" for details)
   --clean              Works similarly to "-u DEFAULTS -U NONE -i NONE"
```

**Comment by sheerun** [comment] 2020-09-23 18:56
btw. I'm cheering for default nocompatible mode for Vim 9 (at least for interactive terminals), because it's soo annoying to deal with it as plugin author. Nobody uses compatible mode, especially in interactive mode

**Comment by tonymec** [comment] 2020-09-23 20:08
Me too I always use 'nocompatible' mode, which I've been doing since forever (since I became a serious user, which IIRC was with Vim 6.0) by sourcing the vimrc_example.vim in my vimrc. Nowadays the result hasn't changed, even though the code has moved from vimrc_example.vim to defaults.vim.

However, time and again I've met people, even developers, who said (not only about Vim) "Nobody uses feature XXX", which sounds like a statement of fact of universal scope, when actually all they meant was "I don't use feature XXX, I don't care about it, and neither should anyone", which is only a statement of opinion.

AFAIK the set of Vim users who prefer 'compatible' mode is dwindling, but I don't think it is empty: even on one of these lists I've recently met someone who swore by these 'compatible' features, because, he said, they were the common denominator between vi and all his clones including Vim, so no matter on which Unix-like installation he landed, he could quickly start using some editor which behaved like vi without all that "nocompatible stuff".

**Comment by brammool** [comment] 2020-09-23 20:36
So, you have asked every single Vim users?  I don't think so.  The problem is that in places like github we only hear from users who are looking for improvements, not from the users who just use Vim as-is.  I know there are at least a few that want Vim to work like the good old Vi and nothing else.  Every time the startup defaults change there are users who complain.

**Comment by sheerun** [comment] 2020-09-23 21:03
I understand, I don't really want to argue on this topic. This issue is about my issues with `--clean` flag and even if it won't be fixed or improved, the discussion is enough by itself, so someone can debug this issue easier than me in the future, by googling it. Thank you for maintaining vim and discussing reported issues :)

**Comment by tonymec** [comment] 2020-09-24 11:48
As said above, `--clean` and `-u` work at cross-purpose.

About finding help for Vim, Google usually gives poor results. The best source is Vim's own help. Everything is in it, including (at `:help helphelp`) tips on searching the help.

Best regards,
Tony.

**Closed as completed** 2020-09-24 13:17 UTC
