### ISSUE TITLE
Syntax Style for Whole Line

### ISSUE THREAD

**Issue by laktak** [vim/vim#1349] opened 2017-01-03 17:43 UTC
Markdown uses 

```
---
```

to indicate a ruler like this:

---

It would be nice if the syntax style could be rendered over the whole line instead of just over the three `---` characters.

**Comment by grochmal** [comment] 2017-01-03 18:11
Ewww... no.  That's completely opinion based.

Markdown use **any** number of dashes **or stars** up from three, to determine a horizontal bar.  This is already present in `markdown.vim` anyway:

    syn match markdownRule "\* *\* *\*[ *]*$" contained
    syn match markdownRule "- *- *-[ -]*$" contained

Having a full line would disallow you from counting the number of bytes in the line with your eyes.

And you should contact the maintainer of that file in any case.  Which is Tim Pope, who is well known in the Vim community.  Contact info is in the file itself.

I would suggest not contacting Tim with that, since it isn't a change that will not be well seen by at least 50% of the Vim community.

**Comment by laktak** [comment] 2017-01-03 20:03
@grochmal you misunderstood/I guess I could have explained it better. I'm not asking for the default Markdown style to be changed (it was just my use case). 

I am asking for Vim to support this as a feature for the syntax/theme definitions. At the moment Vim can only style `---` but not the rest of the line (AFAIK without awful workarounds).

**Comment by chrisbra** [comment] 2017-01-03 21:39
that is not syntax anymore. I don't think this fits into an editor. Closing

**Closed as completed by chrisbra** 2017-01-03 21:39 UTC

**Comment by laktak** [comment] 2017-01-04 10:35
@chrisbra  OK but this is not an uncommon request:

http://stackoverflow.com/questions/2150220/how-do-i-make-vim-syntax-highlight-a-whole-line
http://vi.stackexchange.com/questions/3755/syntax-highlight-for-whole-line

Vim already has a `conceal` option so I don't see how this is that different.

**Comment by chrisbra** [comment] 2017-01-04 10:41
I thought you wanted to draw something different a complete line and not just some highlighting.
Yes, that is a known limitation. You can use signs to workaround it, as I wrote in one of those answers. Also this is a duplicate of #675
