### ISSUE TITLE
Vim background incompatible with Windows Powershell.

### ISSUE THREAD

**Issue by hungpham3112** [vim/vim#9810] opened 2022-02-18 12:26 UTC
![image](https://user-images.githubusercontent.com/75968004/154682477-378a7734-e97d-46c5-8981-6fcbf4d8ff0b.png)

Version:

```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled May  2 2021 18:02:30)
MS-Windows 32-bit console version
Included patches: 1-2824
Compiled by mool@tororo
Huge version without GUI.  Features included (+) or not (-):
+acl                +comments           +find_in_path       +listcmds           +popupwin           -sun_workshop       +vertsplit
+arabic             +conceal            +float              +localmap           -postscript         +syntax             +virtualedit
+autocmd            +cryptv             +folding            -lua                +printer            +tag_binary         +visual
+autochdir          +cscope             -footer             +menu               +profile            -tag_old_static     +visualextra
+autoservername     +cursorbind         +gettext/dyn        +mksession          -python             -tag_any_white      +viminfo
-balloon_eval       +cursorshape        -hangul_input       +modify_fname       -python3            -tcl                +vreplace
+balloon_eval_term  +dialog_con         +iconv/dyn          +mouse              +quickfix           +termguicolors      +vtp
-browse             +diff               +insert_expand      -mouseshape         +reltime            +terminal           +wildignore
++builtin_terms     +digraphs           +ipv6               +multi_byte_ime/dyn +rightleft          -termresponse       +wildmenu
+byte_offset        -dnd                +job                +multi_lang         -ruby               +textobjects        +windows
+channel            -ebcdic             +jumplist           -mzscheme           +scrollbind         +textprop           +writebackup
+cindent            +emacs_tags         +keymap             -netbeans_intg      +signs              -tgetent            -xfontset
+clientserver       +eval               +lambda             +num64              +smartindent        +timers             -xim
+clipboard          +ex_extra           +langmap            +packages           +sound              +title              -xpm_w32
+cmdline_compl      +extra_search       +libcall            +path_extra         +spell              -toolbar            -xterm_save
+cmdline_hist       -farsi              +linebreak          -perl               +startuptime        +user_commands      
+cmdline_info       +file_in_path       +lispindent         +persistent_undo    +statusline         +vartabs            
   system vimrc file: "$VIM\vimrc"
     user vimrc file: "$HOME\_vimrc"
 2nd user vimrc file: "$HOME\vimfiles\vimrc"
 3rd user vimrc file: "$VIM\_vimrc"
      user exrc file: "$HOME\_exrc"
  2nd user exrc file: "$VIM\_exrc"
       defaults file: "$VIMRUNTIME\defaults.vim"
Compilation: cl -c /W3 /GF /nologo  -I. -Iproto -DHAVE_PATHDEF -DWIN32  -DFEAT_CSCOPE -DFEAT_TERMINAL -DFEAT_SOUND  -DFEAT_JOB_CHANNEL -DFEAT_IPV6      -DWINVER=0x0501 -D_WIN32_WINNT=0x0501 /source-charset:utf-8 /MP -DHAVE_STDINT_H /Ox /GL -DNDEBUG /arch:IA32 /Zl /MT /D_CRT_SECURE_NO_DEPRECATE /D_CRT_NONSTDC_NO_DEPRECATE -DFEAT_MBYTE_IME -DDYNAMIC_IME -DDYNAMIC_ICONV -DDYNAMIC_GETTEXT -DFEAT_HUGE /Fd.\ObjCi386/ /Zi
Linking: link  /nologo /opt:ref /LTCG:STATUS oldnames.lib kernel32.lib advapi32.lib shell32.lib gdi32.lib  comdlg32.lib ole32.lib netapi32.lib uuid.lib /machine:i386   libcmt.lib  user32.lib          winmm.lib WSock32.lib Ws2_32.lib  /PDB:vim.pdb -debug
```
I suppose that this issue caused by almost versions of vim, not just this one.

**Comment by hungpham3112** [comment] 2022-02-22 05:10
> I think this issue rather belongs to vim/vim. I am a bit confused by your screenshot, why are there so many transparent background layers? Can you please explain? There are already some issues with powershell and windows, so this may be a duplicate.
> 
> Also, please clarify:
> 
> * Are you starting vim in a terminal?
> * What happens if you use `vim --clean`?

1. I opened it by Windows Powershell. with `everforest` theme and `startify` first screen.
2. vim --clean shows nothing.

step to reproduce:
1. use `everforest` theme and `startify` with vim-plug
2. colorscheme everforest
3.  open vim with window powershell

Here is the picture show different between `cmd.exe`, window `powershell` and `window terminal run pwsh.exe`:

![image](https://user-images.githubusercontent.com/75968004/155067015-eaa29a53-48ba-4acf-9876-5b868f0da75e.png)

**Comment by chrisbra** [comment] 2022-02-22 07:26
Please always use `vim --clean` or use a minimal reproducible example and always clearly explain what problem you are facing (e.g. what you expect, what you see, what exact error messages appear), so that we do not have to guess here. 

I guess the problem is, that for windows powershell the background color does not go until the end of the line? I think this is a duplicate, but don't find it currently (possibly #7162 but this is for windows terminal). 

Please check: 
- does it happen with other colorschemes, what about a default one?
- does it happen without startify?
- does it happen with or without `termguicolors` being set? 
- does `:set t_ut=` or `:set t_ut=y` make any difference?

**Comment by hungpham3112** [comment] 2022-02-22 11:24
1. It happens with all colorschemes except `blue `default colorscheme in vim. Colorscheme gruvbox:
![image](https://user-images.githubusercontent.com/75968004/155122442-630b3be1-5ff7-47b8-bd4a-34fade264e6f.png)

2. Without startify:
![image](https://user-images.githubusercontent.com/75968004/155122631-0efb4893-4ed4-4a3c-ba7e-1dc597269f05.png)

3. termguicolors in my vimrc
4. `:set t_ut=` `:set t_ut=y` make no difference

**Comment by habamax** [comment] 2022-02-22 13:48
I can confirm vim in powershell has that issue with legacy colorschemes.

Remakes, on the other hand, work:
![vim-colors-pwsh](https://user-images.githubusercontent.com/234774/155145047-ab51bf92-fb1f-4ffe-bc44-dc12472c1827.gif)

**Comment by habamax** [comment] 2022-02-22 14:06
I take it back...

With `vim -Nu NONE` all built-in colorschemes are fine (apart of some of them unreadable due to matching blue background with blue syntax elements).

If you `set t_Co=256` though then there are issues with background of syntax highlighted text:

## `t_Co=256`
![image](https://user-images.githubusercontent.com/234774/155148149-6a3dbd53-6430-4539-a720-d7c13b1e5dbb.png)

## `t_Co=16`
![image](https://user-images.githubusercontent.com/234774/155148347-9c9b2d0d-c0e6-4b28-8898-946f359087bf.png)

**Comment by chrisbra** [comment] 2022-05-28 08:12
I am closing this, since the new colorschemes have been merged in

**Closed as completed by chrisbra** 2022-05-28 08:12 UTC
Labels: platform-windows
