### ISSUE TITLE
text-properties return wrong information

### ISSUE THREAD

**Issue by hy172574895** [vim/vim#5840] opened 2020-03-24 21:28 UTC
**Describe the bug**
I am writing a plugin using **text-properties** (very helpful to impove my plugin)
And when I am testing or, in other words, learning how it works, I got some wrong cases.

**To Reproduce**
# 1. A simple vim script:
 ```
let g:extend = []
func Listener(bufnr, start, end, added, changes)
  for item in a:changes
    call add(g:extend, item)
  endfor
endfunc
call listener_add('Listener')
```
# 2. A sample buffer:
```
1
2

3
4
```
we run the above vim script here now.
And after i pressed `u` (undo), i got the following in my buffer which is my expectation to delete 3th line, a blank line:
```
1
2
3
4
```
# 3. But i got wrong text-properties callback.
`:echo g:extend`  ===> `[{'lnum': **2**, 'col': 1, 'added': -1, 'end': 4}]`

In vim's doc, saying:
```
		When lines are deleted the values are:
	 ???      lnum	the first deleted line 
		    end		the line below the first deleted line, before
				the deletion was done
		    added	negative, number of lines deleted
		    col		1

```
**Expected behavior**
`:echo g:extend`  ===> `[{'lnum': **3**, 'col': 1, 'added': -1, 'end': 4}]`
# 4. By contrast,
i press `dd` (delete one line) on the 3th line in the following buffer.
```
1
2

3
4
```
I got: 
`:echo g:extend`  ===> `[{'lnum': 3, 'col': 1, 'added': -1, 'end': 4}]`
it matched.

**Environment (please complete the following information):**
 - Vim 8.2.0439
 - OS: Windows 10
 - GUI

谢谢 means to thank you for reply and your great work.

**Comment by hy172574895** [comment] 2020-03-25 15:06
# Another case
vim script same as the above.
asuming we have current buffer and cursor is at 1th line:
```
1
2
3
4
```
To press `VGd`, we delete all text.
To press `u`, undo.

I got the following:

`:echo g:extend` ===> [{'lnum': 1, 'col': 1, 'added': -4, 'end': 5}, {'lnum': 1, 'col': 1,** 'added': 3 **, 'end': 2}]

In fact, we did added 3 line, but the first line had changed, and vim did not notify to user.

**Comment by hy172574895** [comment] 2020-03-25 15:07
# Another case
vim script same as the above.
asuming we have current buffer and cursor is at 1th line:
```
1
2
3
4
```
To press `VGd`, we delete all text.
To press `u`, undo.

I got the following:

`:echo g:extend` ===> [{'lnum': 1, 'col': 1, 'added': -4, 'end': 5}, {'lnum': 1, 'col': 1,** 'added': 3 **, 'end': 2}]

In fact, we did added 3 line, but the first line had changed, and vim did not notify to user.

**Comment by brammool** [comment] 2020-03-25 20:14
Jimmy Huang wrote:

> # Another case
> vim script same as the above.
> asuming we have current buffer and cursor is at 1th line:
> ```
> 1
> 2
> 3
> 4
> ```
> To press `VGd`, we delete all text.
> To press `u`, undo.
> 
> I got the following:
> 
> `:echo g:extend` ===> [{'lnum': 1, 'col': 1, 'added': -4, 'end': 5}, {'lnum': 1, 'col': 1,** 'added': 3 **, 'end': 2}]
> 
> In fact, we did added 3 line, but the first line had changed, and vim
> did not notify to user.

It did, since the first line is 1, thus the first line is changed.  It
reports both the changed first line and adding three lines at once.

The "lnum" item is the first affected line, "end" is the first line
below the affected lines, before the change.

-- 
Witches prefer brooms: vacuum-cleaners need extension cords!

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment] 2020-03-25 20:14
Jimmy Huang wrote:

> **Describe the bug**
> I am writing a plugin using **text-properties** (very helpful to impove my plugin)
> And when I am testing or, in other words, learning how it works, I got some wrong cases.
> 
> **To Reproduce**
> # 1. A simple vim script:
>  ```
> let g:extend = []
> func Listener(bufnr, start, end, added, changes)
>   for item in a:changes
>     call add(g:extend, item)
>   endfor
> endfunc
> call listener_add('Listener')
> ```
> # 2. A sample buffer:
> ```
> 1
> 2
> 
> 3
> 4
> ```

How did you create this?  Since you use undo this matters.

> we run the above vim script here now.
> And after i pressed `u` (undo), i got the following in my buffer which is my expectation to delete 3th line, a blank line:
> ```
> 1
> 2
> 3
> 4
> ```
> # 3. But i got wrong text-properties callback.
> `:echo g:extend`  ===> `[{'lnum': **2**, 'col': 1, 'added': -1, 'end': 4}]`
> In vim's doc, saying:
> ```
> 		When lines are deleted the values are:
> 	 ???      lnum	the first deleted line 
> 		    end		the line below the first deleted line, before
> 				the deletion was done
> 		    added	negative, number of lines deleted
> 		    col		1
> 
> ```
> **Expected behavior**
> `:echo g:extend`  ===> `[{'lnum': **3**, 'col': 1, 'added': -1, 'end': 4}]`
> # 4. By contrast,
> i press `dd` (delete one line) on the 3th line in the following buffer.
> ```
> 1
> 2
> 
> 3
> 4
> ```
> I got: 
> `:echo g:extend`  ===> `[{'lnum': 3, 'col': 1, 'added': -1, 'end': 4}]`
> it matched.

If I add the line with "o" on the second or "O" on the third line and
then undo, I get the same.

-- 
The question is:  What do you do with your life?
The wrong answer is: Become the richest guy in the graveyard.
				(billionaire and Oracle founder Larry Ellison)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by hy172574895** [comment] 2020-03-25 21:26
> How did you create this?  Since you use undo this matters.
> If I add the line with "o" on the second or "O" on the third line and then undo, I get the same.

Just same as you do. It seems to work well when i  `p` a new line then undo it.

--------------------

> It did, since the first line is 1, thus the first line is changed.  It
>reports both the changed first line and adding three lines at once.
>The "lnum" item is the first affected line, "end" is the first line
>below the affected lines, before the change.

I think i get it now.  At the first time, i thought it's "one operation one report", and it is very nice for users.

**Comment by lacygoill** [comment] 2021-02-06 01:43
> 3. But i got wrong text-properties callback.
> 
> :echo g:extend ===> [{'lnum': **2**, 'col': 1, 'added': -1, 'end': 4}]
> 
> In vim's doc, saying:
> 
> 		When lines are deleted the values are:
> 	 ???      lnum	the first deleted line 
> 		    end		the line below the first deleted line, before
> 				the deletion was done
> 		    added	negative, number of lines deleted
> 		    col		1
> 
> Expected behavior
> :echo g:extend ===> [{'lnum': **3**, 'col': 1, 'added': -1, 'end': 4}]

That's not what I get:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9
        range(1, 4)->setline(1)
        feedkeys('2Go', 'nxt')
        g:extend = []
        def Listener(bufnr: number, start: number, end: number, added: number, changes: any)
            for item in changes
                add(g:extend, item)
            endfor
            echom g:extend
        enddef
        listener_add(Listener)
        feedkeys('u', 'nxt')
        redraw
        mess
    EOF
    )

This outputs:

    [{'lnum': 3, 'col': 1, 'added': -1, 'end': 4}]
              ^

---

> I think i get it now.

So, is there still an issue?

**Comment by brammool** [comment] 2021-02-06 14:37
I think this is either fixed or working as intended.  I'll tentatively close this issue.  If you do see a problem, please re-open and give a full reproduction.

**Closed as completed by brammool** 2021-02-06 14:37 UTC
