### ISSUE TITLE
Netrw does a lot of things, and yet doesn't do enough

### ISSUE THREAD

**Issue by SRGOM** [vim/vim#4123] opened 2019-03-18 05:10 UTC
I wish to list some shortcomings of netrw and propose it's removal as a 'de-facto' plugin. 

The plugin is a 12K line file and while my vim flies on everything, just opening all the folds as an exercise as vim literally hanging, not just lagging, on the file. I am writing this from a 4-gen mobile core-i5. 

Netrw tries to do a lot of things that I fear a lot of people in the 'modern' userbase don't do. ssh/ftp/rsync are not something most people do.  On the other hand- I wish it had a  Ctrl-P (fuzzy matching) functionality so I wouldn't have to install an external plugin. And sine netrw does everything, one would expect it to do something that literally anyone editing a file, over ssh/ftp/rsync or locally, should use- a version control interface. 

Eminent vim programmers (@tpope comes to mind) have also talked about netrw being buggy. 

I would urge you to take away the "default plugin" status of netrw so that the community is encouraged to build a replacement

**Comment by vim-ml** [comment] 2019-03-18 07:09
On 2019-03-17, SRGOM wrote:
> I wish to list some shortcomings of netrw and propose it's removal as a
> 'de-facto' plugin.
> 
> The plugin is a 12K line file and while my vim flies on everything, just
> opening all the folds as an exercise as vim literally hanging, not just
> lagging, on the file. I am writing this from a 4-gen mobile core-i5.
> 
> Netrw tries to do a lot of things that I fear a lot of people in the 'modern'
> userbase don't do. ssh/ftp/rsync are not something most people do. On the other
> hand- I wish it had a Ctrl-P or NerdTree like functionality so I wouldn't have
> to install multiple plugins or some very basic functionality.
> 
> Eminent vim programmers (@tpope comes to mind) have talked about netrw being
> buggy.
> 
> I would urge you to take away the "default plugin" status of netrw so that the
> community is encouraged to build a replacement

The community is free to build a replacement at any time.  No one
has done so.

I use ssh daily to connect from my desktop to the various servers on
which I do most of my work.

If you find a bug in netrw, report it, with enough detail for Chip
to reproduce it.  Or send a patch.  In my experience, he has been
quite willing to fix defects in netrw.

Regards,
Gary

**Comment by SRGOM** [comment] 2019-03-18 07:30
You're not too smart, Gary. One person using it doesn't make it worthy of being default. Also, maybe it's your unwelcoming attitude (who the fuck is chip, maybe he has an email address?) that dissuades the community from doing much in this regard?

**Comment by SRGOM** [comment] 2019-03-18 07:32
Some may take objection to my strong reply but here's my reasoning- I made a good faith suggestion as a user which I felt would be useful in general. And I'm met with a platitude of a reply which can be as unwelcoming as it gets, rather than engaging with me on specific points. I hope your toxic generation of contributors stays on your backward ass email lists off github.

**Comment by chrisbra** [comment] 2019-03-18 08:21
Well, removing netrw will hurt everybody that currently relies on using it. And Gary is right, nothing hinders the community to come up with a better replacement, if netrw is really that bad.

Please also watch your tone. Closing, as this is not a bug of Vim. If you want to discuss alternatives of netrw, please use the mailinglist. This is not a bug of Vim.

**Closed as completed by chrisbra** 2019-03-18 08:21 UTC
Labels: plugin-netrw
