### ISSUE TITLE
Add a highlighting group for the bottom command/status bar.

### ISSUE THREAD

**Issue by Qualphey** [vim/vim#9177] opened 2021-11-21 14:15 UTC
Bassically it should be the equivalent of the [MsgArea](https://neovim.io/doc/user/syntax.html#hl-MsgArea) highlighting group.

**Comment by lacygoill** [comment] 2021-11-21 14:31
Duplicate of https://github.com/vim/vim/issues/4849

**Closed as completed** 2021-11-21 14:56 UTC
Labels: duplicate, enhancement
