### ISSUE TITLE
Vim shows empty window when terminal window is resized

### ISSUE THREAD

**Issue by pvonmoradi** [vim/vim#7118] opened 2020-10-11 17:51 UTC
When I change window size of the terminal vim is running from, and a bottom pop-up window is opened through a plugin, it completely messes up vim rendering. Vim shows an empty window. 

**To Reproduce**
1. Use a plugin which spawns the bottom pop-up window (like vim-which-key or CoC.nvim)
2. Spawn the bottom window. 
3. Change terminal size.
4. Vim shows an empty window filled with theme's background color.  
5. The issue would be fixed on hitting ESC or Enter but closes the bottom window. Also `Ctrl+l` fixes the issue but bottom window location would not get corrected.

Also tested on vim-gtk (gvim). Same problem. Floating popups are not affected.

**Expected behavior**
I expected the window to be rendered correctly at the new screen size

**Screenshots**
[https://imgur.com/a/fetYzr2](https://imgur.com/a/fetYzr2)

**Environment:**
 - VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Oct 11 2020 01:18:01)
Included patches: 1-1830
[https://termbin.com/ah2b2](https://termbin.com/ah2b2)
 - OS: Xubuntu 18.04 + i3gaps wm
 - Terminal: tested on both Alacritty and Xfce4-terminal

**Comment by brammool** [comment] 2020-10-11 20:10
This is not reproducible with these steps.
E.g. "spawn the bottom window" - I have no idea what this does.  some popup_create() call? With what arguments?

**Comment by pvonmoradi** [comment] 2020-10-11 20:29
@brammool Thanks for your quick reply and also thanks for your awesome work throughout the years, really appreciated :D  

Yeah I don't know how exactly those plugins internally spawn that bottom window.   
It seems for the vim-which-key plugin, the relevant parts are [here](https://github.com/liuchengxu/vim-which-key/blob/30c0810b012a7acdccc6b72f0e99c0388986844f/plugin/which_key.vim#L24) and [here](https://github.com/liuchengxu/vim-which-key/blob/30c0810b012a7acdccc6b72f0e99c0388986844f/autoload/which_key/window.vim#L58) 

Most straightforward way to reproduce the bug as a user could be to install the [vim-which-key](https://github.com/liuchengxu/vim-which-key) plugin, add `nnoremap <silent> <leader> :WhichKey '<leader>'<CR>` in the vimrc, hit the leader key in normal mode, the popup window shows up after a second, then make terminal window fullscreen and restore.

**Comment by lacygoill** [comment] 2020-12-14 09:49
> To Reproduce
>
> 1. Use a plugin which spawns the bottom pop-up window (like vim-which-key or CoC.nvim)
> 2. Spawn the bottom window.
> 3. Change terminal size.
> 4. Vim shows an empty window filled with theme's background color.
> 5. The issue would be fixed on hitting ESC or Enter but closes the bottom window. Also Ctrl+l fixes the issue but bottom window location would not get corrected.

That's not a [minimal working example](https://en.wikipedia.org/wiki/Minimal_working_example).  For how to get one, [see here](https://github.com/chrisbra/vim_faq/blob/7f9c65c91d01e289a92b9e43a70ee2becadd66ce/vim_faq.txt#L1153-L1228).

Anyway here is one:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        popup_create(['aaa', 'bbb', 'ccc'], {highlight: 'Pmenu'})
        redraw
        getchar()
    EOF
    )

Then, resize the terminal.  The popup is not redrawn.

The issue is similar to #7404, which is why a `:redraw` is needed for the popup to be drawn immediately.
But contrary to the latter, a simple `:redraw` is not enough to fix the issue when the terminal is resized.
I tried to install an autocmd listening to `VimResized`:

    au VimResized * redraw

Like this:
```vim
vim9script
popup_create(['aaa', 'bbb', 'ccc'], {highlight: 'Pmenu'})
redraw
au VimResized * redraw
getchar()
```
But it doesn't work.  I guess `VimResized` is not fired while `getchar()` waits for input.

**Comment by lacygoill** [comment] 2020-12-14 09:54
> The issue is similar to #7404

Well, actually, the cause is not similar; it's the exact same one.

**Comment by brammool** [comment] 2020-12-14 19:50
Well, if you call getchar() then Vim will block until a key is typed.  If you don't want that, well, then don't do it.

**Comment by lacygoill** [comment] 2020-12-15 02:50
I don't use the OP's plugins, but their authors probably have a good reason to invoke `getchar()` while a popup is visible, and I'm not sure it would be possible for them to work around this pitfall.

As mentioned earlier, the easiest workaround I can think of would be to fire `VimResized` even while `getchar()` waits for input; so that plugin's authors can `:redraw` when the terminal is resized.  But I don't know whether that's possible.

I also found this todo item which might be relevant:

https://github.com/vim/vim/blob/025cb1ca8605055383c53bf2c823d7093cf29b82/runtime/doc/todo.txt#L2758-L2759

In any case, if it's working as intended, then both issues can be closed; at least #7404, for which a workaround was given that doesn't require any Vim patch.

**Comment by lacygoill** [comment] 2020-12-15 03:19
> and I'm not sure it would be possible for them to work around this pitfall.

Actually, it should be possible for them to use a popup filter, which doesn't suffer from this issue.  In fact, it would probably be even better.  Popup filters were implemented for what these plugins seem to do.

So, I tend to think that it's not really a bug.  It's just that `getchar()` blocks Vim, which doesn't redraw the screen.  Although, maybe `:h getchar()` should say something about the fact that the screen is not redrawn while Vim waits for input, and that a `:redraw` might be needed, or a popup filter.  As a suggestion, here is a patch:
```diff
diff --git a/runtime/doc/eval.txt b/runtime/doc/eval.txt
index 9e81832a0..83a5e6cb8 100644
--- a/runtime/doc/eval.txt
+++ b/runtime/doc/eval.txt
@@ -5173,6 +5173,12 @@ getchar([expr])						*getchar()*
 			:  return c
 			:endfunction
 
+		NOTE: Vim blocks while waiting for input, which prevents the
+		screen from being redrawn.  This matters when invoking
+		`getchar()` while a popup window is visible.  Instead, try to
+		use a |popup-filter|.  Otherwise, a `:redraw` may be necessary,
+		which is not possible while the terminal window is resized.
+
 getcharmod()						*getcharmod()*
 		The result is a Number which is the state of the modifiers for
 		the last obtained character with getchar() or in another way.
```

**Comment by lacygoill** [comment] 2020-12-15 03:25
> It's just that getchar() blocks Vim, which doesn't redraw the screen.

And some plugins authors might not be aware of popup filters, so they try to re-invent them with `getchar()`.  If so, that's one more reason to add a `NOTE` at `:h getchar()` about popup filters.

**Comment by brammool** [comment] 2020-12-22 10:41
> > and I'm not sure it would be possible for them to work around this pitfall.
> 
> Actually, it should be possible for them to use a popup filter, which
> doesn't suffer from this issue.  In fact, it would probably be even
> better.  Popup filters were implemented for what these plugins seem to
> do.
> 
> So, I tend to think that it's not really a bug.  It's just that
> `getchar()` blocks Vim, which doesn't redraw the screen.  Although,
> maybe `:h getchar()` should say something about the fact that the
> screen is not redrawn while Vim waits for input, and that a `:redraw`
> might be needed, or a popup filter.  As a suggestion, here is a patch:

Thanks for the suggestion.  It fits in with the "There is no prompt"
remark, let's put it there.


-- 
A consultant is a person who takes your money and annoys your employees while
tirelessly searching for the best way to extend the consulting contract.
				(Scott Adams - The Dilbert principle)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment] 2020-12-22 10:56
in that case, let's close it here.

**Closed as completed by chrisbra** 2020-12-22 10:56 UTC
