### ISSUE TITLE
Netrw vs guioptions-=m

### ISSUE THREAD

**Issue by habamax** [vim/vim#8833] opened 2021-09-03 09:50 UTC
**Describe the bug**
`:Ex` toggles on/off/on/off/... menu

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run `gvim --clean`
2. `set guioptions-=m`
3. `so $VIMRUNTIME/plugin/netrwPlugin.vim`
3. `:Ex`
4. Menu appears and disappears

**Expected behavior**
Menu should not be toggled

**Screenshots**
with `clean`:
![vim-menu-flips](https://user-images.githubusercontent.com/234774/131986093-f149ec4b-c958-4583-82ad-12c78e1b61a8.gif)

More visible with my regular config:
![vim-menu-flips2](https://user-images.githubusercontent.com/234774/131986289-3e6d2d84-59c1-43e3-b10e-a3615b0255a0.gif)

**Environment:**
 - Vim version: 8.2.3397
 - OS: windows 10
 - Terminal: GUI

**Comment by chrisbra** [comment] 2021-09-03 09:58
I think this is a duplicate of #8820

**Comment by habamax** [comment] 2021-09-03 09:59
> I think this is a duplicate of #8820

Oh my issue search is bad :). I did search but overlooked that issue. Thank you!

**Closed as completed** 2021-09-14 06:20 UTC
Labels: duplicate, plugin-netrw
