### ISSUE TITLE
`vimtutor` failed to find `gvim.exe` when called in Windows Command Prompt

### ISSUE THREAD

**Issue by mengfan1102** [vim/vim#10535] opened 2022-06-07 19:59 UTC
### Steps to reproduce

run `vimtutor` in Windows Command Prompt, or in Windows Terminal

the following error dialog appears:

![vimtutor-error](https://user-images.githubusercontent.com/14812308/172469342-2ca26efc-376a-4e41-958d-2e0dc5f84a9d.png)

then it opens the `vim` with the tutor instead

### Expected behaviour

correctly open `gvim.exe` with the tutor, as running `vimtutor` from the start menu

### Version of Vim

8.2.5056

### Environment

OS: Windows 10.0.19044.1741
terminal: Windows Terminal 1.12.10982.0
shell: Command Prompt

another thing may be relevant: 
I installed the `vim` using `Chocolatey v1.1.0`, and during installation I can see it downloaded the `gvim_8.2.5056_x64.zip`

**Comment by chrisbra** [comment] 2022-06-07 20:34
is that a duplicate of #10460 ?

**Comment by mengfan1102** [comment] 2022-06-08 18:35
the issue #10460 do looks similar to me, 
while the problem persists even after I uninstalled the `vim` and redo the fresh install via `Chocolatey`, so I assume the problem may either in Chocolatey installation or in the vim installation package, specially: `gvim_8.2.5056_x64.zip`

**Comment by chrisbra** [comment] 2022-06-08 20:31
Cannot reproduce. I downloaded `gvim_8.2.5056_x64.zip` from https://github.com/vim/vim-win32-installer/releases/tag/v8.2.5056 and extracted it into a new directory. I then run `cmd.exe` and did clean $PATH so that current gvim installation does not interfer and then did run vimtutor.bat. Since it is in the same directory as (g)vim.exe the tutor started successfully. 

So how did you install it, since it is only a zip file? Do you have another vimtutor somewhere in your path? Check `where vimtutor` Check your PATH settings.

**Comment by mengfan1102** [comment] 2022-06-08 21:30
I installed the vim via Chocolatey:
`choco install vim`

Once installed, I can run program like `vim`, `gvim` or `vimtutor` from anywhere (not just inside the install folder),
as several batch files are automatically created inside the system folder:
- C:\Windows\vim.bat
- C:\Windows\gvim.bat
- C:\Windows\vimtutor.bat
- etc.

I can see the problem now: since `vimtutor.bat` only works inside the install folder, it wouldn't work when I actually run `C:\Windows\vimtutor.bat`

The default install folder is `C:\tools\vim`

**Comment by k-takata** [comment] 2022-06-09 00:19
Choco just copies vimtutor.bat from the install folder to `C:\Windows`, but vimtutor.bat works only when it is in the same folder as gvim.exe.
I think it is a choco issue.

**Comment by chrisbra** [comment] 2022-06-09 05:55
Please report then at https://github.com/chocolatey-community/chocolatey-packages/issues

Closing this then.

**Closed as completed by chrisbra** 2022-06-09 05:55 UTC
Labels: platform-windows
