### ISSUE TITLE
Wrong linewrap with linebreak and listchars

### ISSUE THREAD

**Issue by VladYagl** [vim/vim#12182] opened 2023-03-19 18:45 UTC
### Steps to reproduce

1. Here is a minimum set of settings to reproduce. Removing any of these fixes the issue:
```
set wrap
set tabstop=4
set linebreak
set list
set listchars=tab:.>
```

2. Open a text file:
```
Short line

LONG LINE  aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa	a         	aaaa      	aa,aaaaaaaa	END
Next line
```

My terminal fits between 81 and 82 characters in Vim with this settings (without `set linebreak` the cutoff is at character `D` of `END`)

3. The `END` part of the line is not visible:
![image](https://user-images.githubusercontent.com/18006816/226199516-37ee4f0b-944e-4cd5-9446-0eb60ac36470.png)

4. This error also causes other glitches (mostly random empty strings) further into the file.

### Expected behaviour

Full file should be visible.

### Version of Vim

9.0.1337

### Environment

OS: Arch linux
Terminal: Alacritty, ST
$TERM: alacritty, st-256color

**Comment by chrisbra** [comment] 2023-03-20 06:28
and what is the window width?

**Comment by chrisbra** [comment] 2023-03-20 09:51
So in case you have a single window, `:echo &columns` returns 86? Also the same for `:echo winwidth(0)` with your cursor in the window where the strange wrapping occurs?

**Comment by VladYagl** [comment] 2023-03-20 10:03
Yes, both output 86.

**Comment by chrisbra** [comment] 2023-03-20 10:29
For me it shows like this in putty, with 86 columns (similar in gvim):
![image](https://user-images.githubusercontent.com/244927/226312437-ef711b73-218f-4094-b3b6-09d27a89617f.png)
(assuming no wrap) and this seems to be reasonable. 

Not sure why it doesn't do it in your terminal. It looks like you don't really have 86 characters on the screen to fit?

If you do `:set et` and then `:retab!`, does it show any diffferent?
If you then start visual character mode from the first character in the line back to the last visible char on the line, what does Vim show?  It should also show `86`, like here:
![image](https://user-images.githubusercontent.com/244927/226313625-2ca24bc8-e0ef-437a-88c3-31d210de13d8.png)

**Comment by VladYagl** [comment] 2023-03-20 10:35
No, it happens only with wrap. With `nowrap` it shows exactly the same for me.

P.S. I replaced `set nocompatible` with `set wrap` in my sample config. I think `nocompatible` was enabling `wrap`.

**Comment by VladYagl** [comment] 2023-03-20 10:42
Didn't think to check in gvim before. Also happens in gvim (same version).
![image](https://user-images.githubusercontent.com/18006816/226316684-343453e6-8fb9-4e91-b910-72c4508b26d8.png)

Also, if I move my cursor to the end of the line, it appears on the next line (shown in the screenshot).

**Comment by chrisbra** [comment] 2023-03-20 10:55
ah, so it is with wrapping enabled? I can only check later, but that surprises me. Does it show differently with `:set et| %retab!`?

**Comment by VladYagl** [comment] 2023-03-20 10:58
Yes after this command, Vim shows the line correctly wrapped.

**Comment by chrisbra** [comment] 2023-03-20 12:34
Hm:
Gvim: 9.0.1392 (windows):
![image](https://user-images.githubusercontent.com/244927/226339774-51821b30-0097-4e6a-aad7-249b27b41fe6.png)
Vim 9.0.1386 (Debian with putty term):
![image](https://user-images.githubusercontent.com/244927/226339930-052ca135-d3bf-4958-b0f6-e4ba67808b39.png)

The only thing I notice is the version (even so I do not remember any changes to the drawing logic). Can you still reproduce with the latest Vim release?

**Comment by VladYagl** [comment] 2023-03-20 13:09
You are right. It is a version problem. The issue is gone in the latest release (9.0.1417).

Thanks for your help!

**Comment by chrisbra** [comment] 2023-03-20 13:12
closing then

**Closed as not planned by chrisbra** 2023-03-20 13:12 UTC
Labels: bug
