### ISSUE TITLE
Can't map ctrl slash in nightly gVIM build on Windows

### ISSUE THREAD

**Issue by hexhexD** [vim/vim#9895] opened 2022-03-05 21:36 UTC
### Steps to reproduce

I tried both `noremap <C-/>` and `noremap <C-_>' to map ctrl slash but neither worked. Press Ctrl+V followed by Ctrl+/ in insert mode does nothing.

### Expected behaviour

Map ctrl slash

### Version of Vim

v8.2.4501 64 bit windows installer from https://github.com/vim/vim-win32-installer/releases

### Environment

Windows

**Comment by lacygoill** [comment] 2022-03-06 06:19
> Press Ctrl+V followed by Ctrl+/ in insert mode does nothing.

- Which terminal are you using?
- Do you get the same result in the terminal?  Execute a [`cat(1)`](https://man7.org/linux/man-pages/man1/cat.1.html) command then press `Ctrl+/`.
- Can you reproduce without config (`vim -Nu NONE`)?

**Comment by lacygoill** [comment] 2022-03-06 06:22
> Which terminal are you using?

Ah my bad, your issue is in the GUI.

**Comment by lacygoill** [comment] 2022-03-06 06:31
FWIW, on Ubuntu, I can map `<C-/>` like this:

    nnoremap <C-S-/> <Cmd>echomsg "Ctrl-/ was hit"<CR>

Test:

    $ vim -Nu NONE -g +'nnoremap <C-S-/> <Cmd>echomsg "Ctrl-/ was hit"<CR>'

Note that I need to specify the shift modifier in the lhs of the mapping because I need to press it to produce a slash with my keyboard layout.  But your keyboard layout might be different and not require shift.

---

Did it work in the past, and broke at some point?  If so bisecting the regression might help.

---

Also, make sure to do a test without any config.  If you can still reproduce, and nothing is inserted when you press `Ctrl-V` followed by `Ctrl-/`, then it might be that the keypress is intercepted before reaching Vim, by some other program (window manager, OS, ...).

**Comment by lacygoill** [comment] 2022-03-06 06:34
> Did it work in the past, and broke at some point?  If so bisecting the regression might help.

If it's a regression, it might have been caused by the patch [8.2.4502](https://github.com/vim/vim/releases/tag/v8.2.4502).

**Comment by lacygoill** [comment] 2022-03-06 07:07
> If it's a regression, it might have been caused by the patch 8.2.4502.

Never mind, that patch can't be the issue, because your Vim version is 8.2.4501.

**Comment by hexhexd** [comment] 2022-03-06 14:09
Thank you for the prompt reply. I launched gVIM using `gvim --clean' and still didn't see anything after pressing Ctrl+V followed by Ctrl+/. I presume my keyboard is working fine since Ctrl+/ works in Visual Studio, I could be wrong though.

**Comment by brammool** [comment] 2022-03-06 14:37
This must be a Windows specific issue, on Linux it works fine.  Without mapping CTRL-/ inserts a slash.

**Comment by lacygoill** [comment] 2022-03-06 14:50
> still didn't see anything after pressing Ctrl+V followed by Ctrl+/

If Vim doesn't receive any keycode, then it can't do anything.  The only explanation I can see is that something else intercepts the keypress.

Can you reproduce the issue in a terminal?

If so, try to get a log file:

    $ vim --clean -g +'call ch_logfile("/tmp/logfile", "w")'

**Comment by hexhexd** [comment] 2022-03-06 16:05
I can map Ctrl+/ using vim launched through cmd.exe. I think it's a gVIM specific issue.

**Comment by chrisbra** [comment] 2022-03-12 16:04
I cannot use ctrl+/ in either cmd vim nor in gvim. Could that be a windows specific issue? perhaps you need to configure windows keyboard language?

**Comment by chrisbra** [comment] 2022-03-12 16:28
also please see the following: https://vimhelp.org/vim_faq.txt.html#faq-20.5

**Comment by mattn** [comment] 2022-04-10 07:40
As far as I looked this, <c-/> is not possible to handle with WM_CHAR or WM_SYSCHAR. Only WM_KEYUP can handle this.

```diff
diff --git a/src/gui_w32.c b/src/gui_w32.c
index 584e4ef3e..d088cf7a9 100644
--- a/src/gui_w32.c
+++ b/src/gui_w32.c
@@ -4635,6 +4635,18 @@ _WndProc(
 	}
 	break;
 
+    case WM_KEYUP:
+	// handle CTRL-/
+	if ((GetKeyState(VK_CONTROL) & 0x8000) != 0 && (wParam == 0xBF)) {
+	    char_u string[4];
+	    string[0] = CSI;
+	    string[1] = KS_MODIFIER;
+	    string[2] = 4;
+	    string[3] = 0x2F;
+	    add_to_input_buf(string, 4);
+	}
+	return 0L;
+
     case WM_CHAR:
 	// Don't use HANDLE_MSG() for WM_CHAR, it truncates wParam to a single
 	// byte while we want the UTF-16 character value.
```

**Comment by mattn** [comment] 2022-04-10 08:13
At the least, `<c-_>` insert some thing characters (`^_`), it is different issue from `<c-/>`.

Issue of `<c-/>` fixes with https://github.com/vim/vim/pull/10141

**Comment by chrisbra** [comment] 2022-05-28 07:41
fixed by https://github.com/vim/vim/commit/e08fde007308fffec818b4ad6eccf573f54bed5b

**Closed as completed by chrisbra** 2022-05-28 07:41 UTC
Labels: needs feedback

**Comment by hexhexd** [comment] 2022-05-29 06:44
Thank you @mattn and @chrisbra for fixing it, I confirm it works. You guys are real champs.

**Comment by zhyzky** [comment] 2024-10-14 06:56
With current version 9.1.0781, seems brocken again

**Comment by chrisbra** [comment] 2024-10-14 08:25
https://github.com/vim/vim/blob/7d755d8ef328a3eced18c57ea1b569898cc448a2/runtime/doc/version9.txt#L41658-L41659

**Comment by zhyzky** [comment] 2024-10-14 09:01
> https://github.com/vim/vim/blob/7d755d8ef328a3eced18c57ea1b569898cc448a2/runtime/doc/version9.txt#L41658-L41659

Thanks. I've find this.
