### ISSUE TITLE
settabvar() in tabline function causes redraw!

### ISSUE THREAD

**Issue by blueyed** [vim/vim#1317] opened 2016-12-10 23:40 UTC
TEST CASE:

Given `t-settabvar-in-tabline-causes-redraw.vim`:

```vim
set updatetime=1000
au CursorHold * echom 1
let loaded_matchparen = 1

fun! AltTabline()
  let r = 'tabline: '
  for i in range(tabpagenr('$'))
    let tab = i + 1
    call settabvar(tab, '_my_tablabel_cache_2', 1)
    let r .= ' '.tab
  endfor
  return r
endfun
set tabline=%!AltTabline()

" au CursorHold

edit /etc/passwd
tabedit /etc/group
```

```vim -u t-settabvar-in-tabline-causes-redraw.vim```

This forces a redraw (`redraw!`), so that you do not see the 1 being echoed:
1. when switching tabs (`gt`), but then only if there is a `CursorHold` autoevent being triggered
2. when moving around in general

I have noticed this since I use a `t:` var to store a cache in the `tabline` function, but apparently only for the non-current tab(s), so I noticed the flicker only when switching tabs (after the `updatetime` timeout, in case there is a `CursorHold` autoevent).

**Comment by chrisbra** [comment] 2016-12-16 22:19
Hm, this happens, because `settabvar()` internally switches tabpages which forces a redraw. I think we can avoid that. Also `enter_tabpage()` does set `must_redraw` and at the end also calls `redraw_all_later(CLEAR);`. I think we can remove that `redraw_all_later(CLEAR)` command, since this will force an additional redraw.

So something like this perhaps:
```patch
diff --git a/src/evalfunc.c b/src/evalfunc.c
index 08be12b..8b0df43 100644
--- a/src/evalfunc.c
+++ b/src/evalfunc.c
@@ -10295,6 +10295,7 @@ f_settabvar(typval_T *argvars, typval_T *rettv)
 #endif
     char_u     *varname, *tabvarname;
     typval_T   *varp;
+    int                redraw_save = must_redraw;

     rettv->vval.v_number = 0;

@@ -10332,6 +10333,7 @@ f_settabvar(typval_T *argvars, typval_T *rettv)
        if (valid_tabpage(save_curtab))
            goto_tabpage_tp(save_curtab, FALSE, FALSE);
 #endif
+       must_redraw = redraw_save;
     }
 }

diff --git a/src/window.c b/src/window.c
index ee5f7aa..d2a3cb9 100644
--- a/src/window.c
+++ b/src/window.c
@@ -3896,8 +3896,6 @@ enter_tabpage(
            apply_autocmds(EVENT_BUFENTER, NULL, NULL, FALSE, curbuf);
     }
 #endif
-
-    redraw_all_later(CLEAR);
 }

 /*
```

**Comment by brammool** [comment] 2016-12-17 10:42
Christian Brabandt wrote:

> Hm, this happens, because `settabvar()` internally switches tabpages
> which forces a redraw. I think we can avoid that. Also
> `enter_tabpage()` does set `must_redraw` and at the end also calls
> `redraw_all_later(CLEAR);`. I think we can remove that
> `redraw_all_later(CLEAR)` command, since this will force an additional
> redraw.
> 
> So something like this perhaps:
> ```patch
> diff --git a/src/evalfunc.c b/src/evalfunc.c
> index 08be12b..8b0df43 100644
> --- a/src/evalfunc.c
> +++ b/src/evalfunc.c
> @@ -10295,6 +10295,7 @@ f_settabvar(typval_T *argvars, typval_T *rettv)
>  #endif
>      char_u     *varname, *tabvarname;
>      typval_T   *varp;
> +    int                redraw_save = must_redraw;
> 
>      rettv->vval.v_number = 0;
> 
> @@ -10332,6 +10333,7 @@ f_settabvar(typval_T *argvars, typval_T *rettv)
>         if (valid_tabpage(save_curtab))
>             goto_tabpage_tp(save_curtab, FALSE, FALSE);
>  #endif
> +       must_redraw = redraw_save;
>      }
>  }
> 
> diff --git a/src/window.c b/src/window.c
> index ee5f7aa..d2a3cb9 100644
> --- a/src/window.c
> +++ b/src/window.c
> @@ -3896,8 +3896,6 @@ enter_tabpage(
>             apply_autocmds(EVENT_BUFENTER, NULL, NULL, FALSE, curbuf);
>      }
>  #endif
> -
> -    redraw_all_later(CLEAR);
>  }
> 
>  /*
> ```

But what if a setting is changed that does require a redraw?

-- 
All true wisdom is found on T-shirts.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment] 2016-12-17 10:57
settabvar does not allow to change settings, since all variables are explicitly prefixed with 't:'. And even if it did, since we are moving back to the old tabpage, why would we need a redraw for a tabpage we are going to leave again? We could postpone the redraw until we actually enter that tabpage in which case a redraw is going to happen anyhow.

**Comment by lacygoill** [comment] 2020-06-15 11:54
I can't reproduce.  I think this is fixed by https://github.com/vim/vim/commit/ba2929b6afd2fc20479912a8dec789be26a38244.

**Comment by chrisbra** [comment] 2020-06-15 12:10
closing then.

**Closed as completed by chrisbra** 2020-06-15 12:10 UTC
