### ISSUE TITLE
isfname+=32 breaks escaping for space in options

### ISSUE THREAD

**Issue by andrey-starodubtsev** [vim/vim#447] opened 2015-10-14 18:58 UTC
vim -u NUL -c"set isfname+=32 | filetype plugin on | e 1.pl"

causes following error

Error detected while processing C:\Program Files (x86)\Vim\vim74\ftplugin\perl.vim:
line   18:
E518: Unknown option: -f

Failing config string is

setlocal keywordprg=perldoc\ -f

**Comment by vim-ml** [comment] 2015-10-14 19:48
On Wed, Oct 14, 2015 at 8:59 PM, andrey-starodubtsev <
vim-dev-github@256bit.org> wrote:

vim -u NUL -c"set isfname+=32 | filetype plugin on | e 1.pl"

> causes following error
> 
> Error detected while processing C:\Program Files
> (x86)\Vim\vim74\ftplugin\perl.vim:
> line 18:
> E518: Unknown option: -f
> 
> Failing config string is
> 
> setlocal keywordprg=perldoc\ -f
> 
> Apparently your perldoc executable is different than the maintainer's — or
> mine.

When I run "man perldoc" in my bash shell (on openSUSE Linux) it tells me:

[...]
       Examples:

```
       perldoc -f BuiltinFunction
```

[...]
OPTIONS
[...]
       -f perlfunc
            The -f option followed by the name of a perl built-in function
will extract the documentation of this function from perlfunc.

```
        Example:

              perldoc -f sprintf
```

[...]

You should report the problem to http://github.com/vim-perl/vim-perl/issues
(the bug reporting URL for that plugin), telling your problem to the
maintainer (i.e. the owners of that group) in as much detail as you can,
including as a minimum
- which operating system you are on (including version and any service
  packs)
- which version of perl and of perldoc you are using (and from where you
  downloaded them).
- the details of the Vim error you described above.

Best regards,
Tony.

**Comment by vim-ml** [comment] 2015-10-14 20:40
Hi andrey-starodubtsev!

On Mi, 14 Okt 2015, andrey-starodubtsev wrote:

> vim -u NUL -c"set isfname+=32 | filetype plugin on | e 1.pl"
> 
> causes following error
> 
> Error detected while processing C:\Program Files (x86)\Vim\vim74\ftplugin\perl.vim:
> line   18:
> E518: Unknown option: -f
> 
> Failing config string is
> 
> setlocal keywordprg=perldoc\ -f

I can reproduce it:
diff --git a/src/option.c b/src/option.c
--- a/src/option.c
+++ b/src/option.c
@@ -4768,7 +4768,8 @@ do_set(arg, opt_flags)
 #ifdef BACKSLASH_IN_FILENAME
                                        && !((flags & P_EXPAND)
                                                && vim_isfilec(arg[1])
-                                               && (arg[1] != '\'
-                                               && ((arg[1] != '\' &&
-                                                    arg[1] != ' ')
                                                  || (s == newval
                                                      && arg[2] != '\')))
  #endif

Best,

## Christian

Die Ziele der Menschen sind Reichtum an Materiellem.
Reichtum an Glück sollte das Ziel sein.
        -- Benjamin Stramke

**Comment by lacygoill** [comment] 2021-03-28 13:14
Has this issue been fixed?  I can't reproduce:

    $ vim -u NONE -c"set isfname+=32 | filetype plugin on | e 1.pl"
    no error

but maybe that's because it's specific to Windows?

**Comment by chrisbra** [comment] 2021-04-01 15:02
seems to be fixed also on windows. Let's close it down.

**Closed as completed by chrisbra** 2021-04-01 15:02 UTC
