### ISSUE TITLE
Some text in filetype.vim is incorrectly highlighted

### ISSUE THREAD

**Issue by lkintact** [vim/vim#14765] opened 2024-05-13 15:21 UTC
### Steps to reproduce

In $VIMRUNTIME\filetype.vim the text `augroup END` in lines 2738 and 3008 is highlighted in `vimAugroupError`, which seems to be incorrect.

### Expected behaviour

.

### Version of Vim

9.1.296

### Environment

.

**Comment by chrisbra** [comment] 2024-05-13 17:02
That is probably because the list of autocommands is so huge. I think a `:syn sync fromstart` fixes it.

**Comment by chrisbra** [comment] 2024-05-25 19:08
I am closing this as not a bug.

**Closed as not planned by chrisbra** 2024-05-25 19:08 UTC
