### ISSUE TITLE
syntax/2html.vim, Undefined variable: g:loaded_2html_plugin

### ISSUE THREAD

**Issue by ambasta** [vim/vim#2135] opened 2017-09-21 12:33 UTC
Hi,

Loading vim w/o a vimrc and then executing 2html.vim throws the following error:

```
Error detected while processing /usr/share/vim/vim80/syntax/2html.vim:
line  725:
E121: Undefined variable: g:loaded_2html_plugin
E116: Invalid arguments for function extend
<?xml version="1.0" encoding="UTF-8"?>

<html>

<head>

<meta name="syntax" content="c" />

<meta name="settings" content="use_xhtml,use_css,pre_wrap,no_foldcolumn,prevent_copy=" />

<meta name="colorscheme" content="none" />

<style type="text/css">

 
/<html/e
/<html/e

finished sourcing /usr/share/vim/vim80/syntax/2html.vim
```

Steps to reproduce

```
vim -u NONE somefile
run! syntax/2html.vim
```

**Comment by fritzophrenic** [comment] 2017-09-22 04:10
Oops. Also with "vim --noplugin". The problem is that 2html.vim isn't really meant to source on its own anymore but it's allowed for backwards compatibility.

I'll probably fix it by sourcing the plugin file if that variable's not defined. As a workaround you can first do "run! plugin/tohtml.vim"

I'll track it here: https://bitbucket.org/fritzophrenic/vim-tohtml/issues/13/e121-when-2htmlvim-is-sourced-and-plugins

**Comment by chrisbra** [comment] 2017-09-25 12:56
closing then.

**Closed as completed by chrisbra** 2017-09-25 12:56 UTC
