### ISSUE TITLE
conceal movement

### ISSUE THREAD

**Issue by lesorubshayan** [vim/vim#14711] opened 2024-05-03 06:03 UTC
### Steps to reproduce

if you have something like
 syntax keyword int int conceal cchar=ℤ
in your vimrc
then you will create file with int in it
it will show as ℤ
the problem is if you will move through it (by arrow keys for example) you will have to do it 3 times because cursor is actually moving through int(not ℤ)

### Expected behaviour

move through concealed as regular

### Version of Vim

master

### Environment

arch

**Comment by zeertzjq** [comment] 2024-05-03 06:05
Duplicate of #12375

**Comment by ronin49** [comment] 2024-05-03 06:33
where is moving function defined to check for conceal?

**Comment by chrisbra** [comment] 2024-05-03 07:06
moving happens on the physical text on a line, not on the visual representation. Thus you get this behaviour. 

Note, this is very tricky to get right. There are many "monving functions" and concealing is only done on the drawing code. So the moving functions are not aware of this "feature".

**Comment by chrisbra** [comment] 2024-05-03 07:06
closing for being a duplicate

**Closed as not planned by chrisbra** 2024-05-03 07:06 UTC
Labels: duplicate, bug
