### ISSUE TITLE
GB18030-2022 is coming. Test it in Debian 11. Use VIM to open tested file will display non-character as '?'. 

### ISSUE THREAD

**Issue by utt54321** [vim/vim#12170] opened 2023-03-17 13:20 UTC
### Steps to reproduce

1.the test file is [CJK-4.txt](https://github.com/vim/vim/files/11001284/CJK-4.txt)
it includes some words in below picture:
<img width="544" alt="image" src="https://user-images.githubusercontent.com/20319237/225905537-bfa30e03-7a4b-4f27-8661-fe45f9c4c3b8.png">

2. use vim to open this test file: `vim CJK-4.txt -c "e ++enc=GB18030"`
3. and the result will be like:
![image](https://user-images.githubusercontent.com/20319237/225910124-80c02326-dc69-4774-9bb5-edac1a23c75f.png)

### Expected behaviour

we can see that  in the result
![image](https://user-images.githubusercontent.com/20319237/225911051-7b091166-bdba-4151-802e-f79a92f12a6e.png)
is not good.
And I try to find the mapping in GB18030-2022 standard:
![image](https://user-images.githubusercontent.com/20319237/225911873-b3ae736d-4f2f-4cdf-aef7-e24cb8df7cb2.png)

The GB18030 code and unicode of '龳' is:
`0x82359036  U+9FB3 龳`
The '龳' displays well.
And the 0x82359037 shows '?5', in vim, I think vim treats 0x8235 as '?5' because it cannot deal with it.
then I try to find out the charmap in  /usr/share/i18n/charmaps/GB18030.gz, I use "gzip -d" to unzip it finding that it has no charmap mapping to 0x82359037.
 1. Is /usr/share/i18n/charmaps/GB18030.gz what the VIM use to encode text based on?
 2. If it does use /usr/share/i18n/charmaps/GB18030.gz, where the updated charmap one can find?

### Version of Vim

8.2.2434

### Environment

Debian 11

**Comment by ychin** [comment] 2023-03-18 03:12
This conversion is done by iconv. On Debian, that should come with the standard glibc implementation I believe. You would need glibc to add support for this.

The actual file that does the conversion should be under a gconv folder (https://man7.org/linux/man-pages/man1/iconv.1.html), so something like `/usr/lib/gconv/GB18030.so`. On my VM, it's `/usr/lib/aarch64-linux-gnu/gconv` instead, so it depends.

**Comment by chrisbra** [comment] 2023-03-19 14:40
Hm,
when I try to load the  file using `++enc=gb18030` I also get:

```
 [noeol][converted][CONVERSION ERROR in line 2][dos]
```

which I believe is caused by ` U+9FB4` in line 2. 

You mention that GB18030 changed/will be changed by GB18030-2022, so perhaps this should then taken to the glibc developers? You can reach them here: https://www.gnu.org/software/libc/bugs.html

I checked, what I believe is the source [here](https://sourceware.org/git/?p=glibc.git;a=blob_plain;f=iconvdata/gb18030.c;hb=HEAD) and it doesn't seem to have seen a relevant changes in the past years. So might not correspond to GB18030-2022.

**Comment by utt54321** [comment] 2023-03-19 15:52
I have file a bug to glibc. The bug report is https://sourceware.org/bugzilla/show_bug.cgi?id=30243#
This issue can be closed or maybe wait for the release version of glibc holding the GB18030-2022 standard in the future.

**Comment by ychin** [comment] 2023-03-19 23:04
FWIW it works fine on macOS 13:

<img width="249" alt="image" src="https://user-images.githubusercontent.com/1217449/226215140-3451bb3f-5624-41b7-9d2d-48281781d117.png">

On macOS 12 some texts are missing:

<img width="125" alt="image" src="https://user-images.githubusercontent.com/1217449/226215222-8a9c3637-c4ce-429c-83c8-ce79229c0264.png">

But this is really an OS / system library bug.

**Comment by utt54321** [comment] 2023-03-20 01:28
Hi, ychin,
I think what you show in macOS 13 is also not right. Because in GB18030-2022, for example, '\x82\x35\x90\x37' is mapping to unicode '\uE8E1' which is a Reserved Character. It means  '\uE8E1' will show nothing or show a '\uE8E1' block. And here in your macOS 13, it '\x82\x35\x90\x37' mapping to '\u9FB4' according to GB18030-2005 will show '龴'.
And another difference between macOS 13 and macOS 12 is that the macOS 13 has a font supporting more charraters of GB18030, I think the font may support parts of Standard Level 1 in GB18030-2022. And macOS 12 dose not have this font then shows '?' block.

**Comment by ychin** [comment] 2023-03-20 02:26
Right. 

> And here in your macOS 13, it '\x82\x35\x90\x37' mapping to '\u9FB4' according to GB18030-2005 will show '龴'.

Hmm, is GB18030-2022 considered a different encoding then? I think usually they are just lumped together as "GB18030" when we specify an encoding. How would we know which version to use?

**Comment by utt54321** [comment] 2023-03-20 02:37
It is hard to tell.
Maybe expert like Doctor Ken Lunde haveideas.
By the way, my bug report to glibc has been focused by nobody.  https://sourceware.org/bugzilla/show_bug.cgi?id=30243#
Emm...
I can only hide in the corner and cry，QAQ.

**Comment by chrisbra** [comment] 2023-03-20 06:27
I'll close this for now, since this is not directly a bug of vim.

**Closed as not planned by chrisbra** 2023-03-20 06:27 UTC
Labels: bug
