### ISSUE TITLE
Remapping arrow keys breaks IM INSERT mode

### ISSUE THREAD

**Issue by graywolf** [vim/vim#1471] opened 2017-02-13 03:31 UTC
When arrow keys are remapped to `<NOP>`, the `IM INSERT` mode starts acting
weird. I'm using `ibus-anthy` for my insertion. When I type

	inu

following is correctly inserted into the buffer

	いぬ

then I press spacebar to cycle between options and I get following first

	犬

since I'm happy with that, I press enter to confirm my selection and here is
the problem, the kanji is inserted once more and I end up with this:

	犬犬

Following is minimal `.vimrc` I managed to reproduce this problem with:

	set nocompatible

	inoremap  <Up>     <NOP>
	inoremap  <Down>   <NOP>
	inoremap  <Left>   <NOP>
	inoremap  <Right>  <NOP>
	noremap   <Up>     <NOP>
	noremap   <Down>   <NOP>
	noremap   <Left>   <NOP>
	noremap   <Right>  <NOP>

Here is my vim version:

	VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Feb  6 2017 16:10:01)
	Included patches: 1-314
	Compiled by Arch Linux
	Huge version with GTK2 GUI.  Features included (+) or not (-):
	+acl             +file_in_path    +mouse_sgr       +tag_old_static
	+arabic          +find_in_path    -mouse_sysmouse  -tag_any_white
	+autocmd         +float           +mouse_urxvt     +tcl/dyn
	+balloon_eval    +folding         +mouse_xterm     +termguicolors
	+browse          -footer          +multi_byte      +terminfo
	++builtin_terms  +fork()          +multi_lang      +termresponse
	+byte_offset     +gettext         -mzscheme        +textobjects
	+channel         -hangul_input    +netbeans_intg   +timers
	+cindent         +iconv           +num64           +title
	+clientserver    +insert_expand   +packages        +toolbar
	+clipboard       +job             +path_extra      +user_commands
	+cmdline_compl   +jumplist        +perl/dyn        +vertsplit
	+cmdline_hist    +keymap          +persistent_undo +virtualedit
	+cmdline_info    +lambda          +postscript      +visual
	+comments        +langmap         +printer         +visualextra
	+conceal         +libcall         +profile         +viminfo
	+cryptv          +linebreak       +python/dyn      +vreplace
	+cscope          +lispindent      +python3/dyn     +wildignore
	+cursorbind      +listcmds        +quickfix        +wildmenu
	+cursorshape     +localmap        +reltime         +windows
	+dialog_con_gui  +lua/dyn         +rightleft       +writebackup
	+diff            +menu            +ruby/dyn        +X11
	+digraphs        +mksession       +scrollbind      -xfontset
	+dnd             +modify_fname    +signs           +xim
	-ebcdic          +mouse           +smartindent     -xpm
	+emacs_tags      +mouseshape      +startuptime     +xsmp_interact
	+eval            +mouse_dec       +statusline      +xterm_clipboard
	+ex_extra        +mouse_gpm       -sun_workshop    -xterm_save
	+extra_search    -mouse_jsbterm   +syntax          
	+farsi           +mouse_netterm   +tag_binary      
	   system vimrc file: "/etc/vimrc"
		 user vimrc file: "$HOME/.vimrc"
	 2nd user vimrc file: "~/.vim/vimrc"
		  user exrc file: "$HOME/.exrc"
	  system gvimrc file: "/etc/gvimrc"
		user gvimrc file: "$HOME/.gvimrc"
	2nd user gvimrc file: "~/.vim/gvimrc"
		   defaults file: "$VIMRUNTIME/defaults.vim"
		system menu file: "$VIMRUNTIME/menu.vim"
	  fall-back for $VIM: "/usr/share/vim"
	Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/gtk-2.0/include -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libdrm -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/pango-1.0 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -D_FORTIFY_SOURCE=2  -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
	Linking: gcc   -L. -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E -Wl,-rpath,/usr/lib/perl5/core_perl/CORE  -Wl,-O1,--sort-common,--as-needed,-z,relro -L/usr/local/lib -Wl,--as-needed -o vim   -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfontconfig -lfreetype -lSM -lICE -lXt -lX11 -lXdmcp -lSM -lICE  -lm -lncurses -lelf -lnsl    -lacl -lattr -lgpm -ldl   -Wl,-E -Wl,-rpath,/usr/lib/perl5/core_perl/CORE -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/perl5/core_perl/CORE -lperl -lpthread -lnsl -ldl -lm -lcrypt -lutil -lc   -L/usr/lib -ltclstub8.6 -ldl -lz -lpthread -lieee -lm

**Comment by nuko8** [comment] 2017-02-13 07:33
I'm afraid this is neither an issue nor a bug of Vim.

When いぬ (2 characters, 4 cells) was converted into 犬 (1 character, 2 cells), the input method notified Vim that the current cursor position had to go back 2 cells.

But the notification couldn't reach the internal of Vim because the following single mapping, which I think is the minimal `.vimrc` to reproduce the issue exactly, blocked it:
```
inoremap  <Left>   <NOP>
```
This prevented the input method and Vim from cooperatively interacting with one another.

An input method is an external process to Vim.  To some extent, we can compare it to a temporary user to Vim while it is being activated.  Any editor user has to know how to move the cursor, and he usually expects that the cursor keys will do.  Vim failed his expectation due to the mapping, which resulted in a disagreement over the cursor position between the user and Vim, thus giving 犬犬 on the editor screen as reported.

**Comment by chrisbra** [comment] 2017-02-13 07:50
closing then.

**Closed as completed by chrisbra** 2017-02-13 07:50 UTC

**Comment by k-takata** [comment] 2017-02-13 08:35
I think this is an issue of Vim, and it has the same cause as #1215.
It might be solved if Vim supports over-the-spot input style.
This is also discussed in vim-jp/issues#874 (in Japanese), but unfortunately no one updates the patch.

**Comment by chrisbra** [comment] 2017-02-13 08:49
so let's keep it then closed as duplicate of #1215
