### ISSUE TITLE
vim9: map() used in a function does not know the function's argument

### ISSUE THREAD

**Issue by alexaschee** [vim/vim#6475] opened 2020-07-18 04:34 UTC
_Instructions: Replace the template text and remove irrelevant text (including this line)_

**To Reproduce**

    vim9script
    def Addpos(a_index: number): list<string>
        let lst = ['a', 'b', 'c']
        lst->map('a_index .. ":" .. v:key .. v:val')
        # lst->map({ind, val -> '' .. a_index .. ':' .. ind .. val})
        return lst
    enddef

    echo Addpos(3)

The `map` on commented line works. 

The first `map` says `E121: undefined variable: a_index`

**Comment by lacygoill** [comment] 2020-07-18 12:07
eval strings can't access variables in the outer function scope:

>    The local variables are on the stack  and cannot be accessed outside of the
>    compiled function.

[Source](https://github.com/vim/vim/issues/6401#issuecomment-655071515).

Solution: use a lambda.

---

Lambdas are faster than eval strings in a `:def` function anyway:

    $ vim -es -Nu NONE -S <(cat <<'EOF'
        vim9script

        def Lambda()
            let time = reltime()
            map(range(999999), {_, v-> v + 1})
            setline(1, reltime(time)->reltimestr()->matchstr('.*\..\{,3}') .. ' seconds to run lambdas')
        enddef
        Lambda()

        def EvalString()
            let time = reltime()
            map(range(999999), 'v:val+1')
            setline(2, reltime(time)->reltimestr()->matchstr('.*\..\{,3}') .. ' seconds to run eval strings')
        enddef
        EvalString()

        :%p
        qa!
    EOF
    )

    0.393 seconds to run lambdas
    0.596 seconds to run eval strings

OTOH, they are slower at the script level:

    $ vim -es -Nu NONE -S <(cat <<'EOF'
        vim9script

        let time = reltime()
        map(range(999999), {_, v-> v + 1})
        setline(1, reltime(time)->reltimestr()->matchstr('.*\..\{,3}') .. ' seconds to run lambdas')

        let _time = reltime()
        map(range(999999), 'v:val+1')
        setline(2, reltime(_time)->reltimestr()->matchstr('.*\..\{,3}') .. ' seconds to run eval strings')

        :%p
        qa!
    EOF
    )

    1.225 seconds to run lambdas
    0.566 seconds to run eval strings

Conclusion: always use lambdas, but make sure to write them inside `:def` functions.

For more info, see [my notes](https://github.com/lacygoill/wiki/blob/master/vim/vim9.md#my-eval-string-cant-access-variables-in-the-outer-function-scope).

**Comment by lacygoill** [comment] 2020-07-18 21:31
I forgot: this is a duplicate of #6401, and documented at [`:h fast-functions`](https://vimhelp.org/vim9.txt.html#fast-functions()).

https://github.com/vim/vim/blob/6434fc574dfbde11461e70e5a62712370edf38e6/runtime/doc/vim9.txt#L521-L534

**Comment by k-takata** [comment] 2020-07-19 06:19
Closing, then.

**Closed as completed by k-takata** 2020-07-19 06:19 UTC
Labels: duplicate
