### ISSUE TITLE
support grep line number notation when opening a file in vim

### ISSUE THREAD

**Issue by ghost** [vim/vim#1672] opened 2017-05-02 09:59 UTC
When searching through grep you get the line number like: 

`aaa.c:888 foo bar foo bar foo bar`

Now if you want to open aaa.c directly at line 888 you have to: 

`vim aaa.c +888`

Is it possible to directly copy the `aaa.c:888` and open vim like:

`vim aaa.c:888`

**Comment by chrisbra** [comment] 2017-05-02 10:02
duplicate of #1473

**Closed as completed by chrisbra** 2017-05-02 10:02 UTC
