### ISSUE TITLE
prop_find: documented but not available

### ISSUE THREAD

**Issue by blueyed** [vim/vim#4970] opened 2019-09-23 21:13 UTC
The function `prop_find` is documented, but not included.

I wanted to use it as a quick way to list all text properties.

I've then noticed that it said "{not implemented yet}" in the help - but that wasn't obvious at first, and given that it is there for longer already: was it forgotten about?

**Comment by brammool** [comment] 2019-09-24 17:00
Daniel Hahler wrote:

> The function `prop_find` is documented, but not included.
> 
> I wanted to use it as a quick way to list all text properties.
> 
> I've then noticed that it said "{not implemented yet}" in the help -
> but that wasn't obvious at first, and given that it is there for
> longer already: was it forgotten about?

Well, so far nobody asked for it, so it had a low priority.
I'll see when I get to it (or until someone makes a PR).

-- 
LAUNCELOT: At last!   A call!  A cry of distress ...
           (he draws his sword, and turns to CONCORDE)
           Concorde!  Brave, Concorde ... you shall not have died in vain!
CONCORDE:  I'm not quite dead, sir ...
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by nikkistewart807** [comment] 2020-01-04 12:46
![BEC3C81A-C4D4-4DDB-8615-41FD76F1ED6B](https://user-images.githubusercontent.com/59505121/71765741-239e0580-2ead-11ea-9f70-f64039d2bdfd.png)
![28E02BF6-64BB-4142-B6F1-D951D6B59328](https://user-images.githubusercontent.com/59505121/71765742-239e0580-2ead-11ea-8f20-7abbb8243290.png)
![F8D099FB-C8AC-4532-82E1-DAB681B8B171](https://user-images.githubusercontent.com/59505121/71765743-239e0580-2ead-11ea-9457-e5f212cccb4c.png)
![Uploading 7AAA92D4-1D2A-4053-96B2-00F3C3B6EDDC.png…]()
![Uploading B0C0706C-CA78-4E87-901E-44AE9AFC6D40.png…]()
![Uploading 34C6566E-1A1F-4098-93DA-40EB712021B3.png…]()
![Uploading ABE59155-477D-4A1B-99E0-5866A543B805.png…]()
![Uploading 81F8963D-86F3-4BC3-A74C-23BE37F3E445.png…]()
![Uploading 49AAD0BB-6D5F-4441-9268-462C975055DE.png…]()
![Uploading CBB0FCA2-0A7A-4957-B738-9E059A6DD3BB.png…]()
![Uploading D7C0F4D3-A857-45D9-AC55-90C46D2AD6BC.png…]()
![Uploading 76F97295-AB80-4094-A640-F9B6ED87267E.png…]()
![Uploading 898C0F23-1E8C-453A-9F2D-934D1B75F947.png…]()
![Uploading 87582109-3C10-4095-B4FD-D28A90375B75.png…]()
![Uploading 5D8E43B3-119C-49E1-BD58-6A7ABEA04E46.jpeg…]()
![Uploading 0837CDA1-3A41-4BC5-B954-1D1908C347DD.jpeg…]()
![Uploading 27577753-D1FF-400D-8D8A-82D9CC05ED69.jpeg…]()
![Uploading 42D492E3-3D23-4A34-A8EC-67E8BF47BC74.jpeg…]()
![Uploading F049EA6A-69B5-4319-91AB-873820227C78.jpeg…]()
![Uploading 9CDE643E-6667-48F4-8937-8AA3083D7FC6.png…]()
![Uploading D8E9F118-7395-4CF7-901D-97F34F109A52.jpeg…]()
![Uploading 72743AC0-A607-4C78-B89F-D07D97DD0658.png…]()
![Uploading 3E8F10C5-01F1-466E-930D-1464EA06BBFF.png…]()
![Uploading 4CA4BC34-B60D-4637-9A09-7912C406A8BB.png…]()

**Comment by chrisbra** [comment] 2020-01-04 12:47
deleted comment for spam

**Comment by nikkistewart807** [comment] 2020-01-04 12:49
Duplicate of #4566 @k-takata 

>  ### 

- _**@`

1. 

- [ ] 

1. 

`**_

**Comment by nikkistewart807** [comment] 2020-01-04 12:50
- [ ] 

- `[Hey whatever you want to do you ](apple.com) `

**Comment by klojop** [comment] 2020-01-05 09:01
We will help you with your 

> When we cam

**Comment by klojop** [comment] 2020-01-05 09:09
### bye hi hello good bye

> The function `prop_find` is documented, but not included.
> 
> I wanted to use it as a quick way to list all text properties.
> 
> I've then noticed that it said "{not implemented yet}" in the help - but that wasn't obvious at first, and given that it is there for longer already: was it forgotten about?

I'm not sure. I will have to look into for you. Sorry about tha

**Comment by klojop** [comment] 2020-01-05 09:09
I'm sorry you issue wasn't corrected

**Comment by blueyed** [comment] 2020-01-05 16:03
@chrisbra also delete (and report) the comments above, please.

**Comment by k-takata** [comment] 2020-01-05 16:07
Deleted and reported.

**Comment by chrisbra** [comment] 2020-01-05 16:42
strange that suddenly spam appears here. I already reported it, but did not delete it (partly because I wasn't entirely sure whether this is spam or not and partly)

**Closed as completed** 2020-01-10 18:56 UTC
