### ISSUE TITLE
vim starts in REPLACE mode

### ISSUE THREAD

**Issue by habamax** [vim/vim#6951] opened 2020-09-14 10:56 UTC
**Describe the bug**

Vim on WSL debian starts in `REPLACE` mode. 

* There is no `~/.vimrc` and no `.vim/` folder.
* Terminals: alacritty and windows terminal (no issue with wsltty).
* `vim -u NONE` doesn't have the issue
* `vim --clean` has the issue

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run `vim --clean`
2. REPLACE mode is in vim window

**Screenshots**

![vim-replace-issue](https://user-images.githubusercontent.com/234774/93077782-018e9100-f692-11ea-80fa-71dd776cae8d.gif)

**Environment (please complete the following information):**
 - Vim version: 8.2.1678] (Or paste the result of `vim --version`.)
 - OS: Windows 10 with WSL1
 - Terminal: Alacritty, windows terminal, wsl.exe

**Comment by k-takata** [comment] 2020-09-14 11:00
Duplicate of  #6365. You can work around this with `set t_u7=` for now. Closing.

**Closed as completed by k-takata** 2020-09-14 11:00 UTC
Labels: duplicate, platform-wsl

**Comment by chrisbra** [comment] 2020-09-14 11:01
Note, that this looks like an actual terminal bug (and has been acknowledged by the terminal maintainer).
