### ISSUE TITLE
Vim core dumps when resizing past window boundaries

### ISSUE THREAD

**Issue by variadico** [vim/vim#6464] opened 2020-07-16 22:26 UTC
**Describe the bug**
Vim core dumps when resizing past window boundaries.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run `vim --clean`
2. Create a terminal buffer with `:terminal`
3. Shrink the terminal buffer with `ctrl-w 10-` and again `ctrl-w 10-` and again... until core dump

**Expected behavior**
I expected the window to stop shrinking once it got to the edge.

**Environment (please complete the following information):**
 - VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jun 21 2020 16:11:23) Included patches: 1-814
 - Arch Linux
 - GNOME Terminal 3.36.2 using VTE 0.60.3 +BIDI +GNUTLS +ICU +SYSTEMD

**Additional context**
This happens 100% of the time. Also, the core dump breaks mouse usage in the terminal afterwards. Also, Vim has been crashing on me for months whenever I executed window related commands.

**coredumpctl info**

```
           PID: 3825 (vim)
           UID: 1000 (variadico)
           GID: 1000 (variadico)
        Signal: 11 (SEGV)
     Timestamp: Thu 2020-07-16 15:14:58 PDT (7min ago)
  Command Line: /usr/bin/vim --clean
    Executable: /usr/bin/vim
 Control Group: /user.slice/user-1000.slice/user@1000.service/apps.slice/apps-org.gnome.Terminal.slice/vte-spawn-a5500963-99bb-45a8-9995-be327f00ef1b.scope
          Unit: user@1000.service
     User Unit: vte-spawn-a5500963-99bb-45a8-9995-be327f00ef1b.scope
         Slice: user-1000.slice
     Owner UID: 1000 (variadico)
       Boot ID: d4931cc800534b66a191536c07be2a87
    Machine ID: d96b874d6bf445e1a3c52c01a6f86be9
      Hostname: foo
       Storage: /var/lib/systemd/coredump/core.vim.1000.d4931cc800534b66a191536c07be2a87.3825.1594937698000000000000.lz4
       Message: Process 3825 (vim) of user 1000 dumped core.

                Stack trace of thread 3825:
                #0  0x00007f6d9877472b kill (libc.so.6 + 0x3c72b)
                #1  0x00005606dc06d061 mch_exit (vim + 0x178061)
                #2  0x00007f6d98913960 __restore_rt (libpthread.so.0 + 0x14960)
                #3  0x00005606dc14e96e n/a (vim + 0x25996e)
                #4  0x00005606dc14fda3 n/a (vim + 0x25ada3)
                #5  0x00005606dc153885 n/a (vim + 0x25e885)
                #6  0x00005606dc14cade vterm_input_write (vim + 0x257ade)
                #7  0x00005606dc10308e write_to_term (vim + 0x20e08e)
                #8  0x00005606dc1899ec n/a (vim + 0x2949ec)
                #9  0x00005606dc18c4d3 channel_parse_messages (vim + 0x2974d3)
                #10 0x00005606dbffb0eb parse_queued_messages (vim + 0x1060eb)
                #11 0x00005606dc113e06 inchar_loop (vim + 0x21ee06)
                #12 0x00005606dc113367 ui_inchar (vim + 0x21e367)
                #13 0x00005606dbffb468 n/a (vim + 0x106468)
                #14 0x00005606dbffc04e n/a (vim + 0x10704e)
                #15 0x00005606dbffd888 vgetc (vim + 0x108888)
                #16 0x00005606dc0fe296 n/a (vim + 0x209296)
                #17 0x00005606dc1048e0 terminal_loop (vim + 0x20f8e0)
                #18 0x00005606dc19b68b main_loop (vim + 0x2a668b)
                #19 0x00005606dc19c304 vim_main2 (vim + 0x2a7304)
                #20 0x00007f6d9875f002 __libc_start_main (libc.so.6 + 0x27002)
                #21 0x00005606dbf5dc4e _start (vim + 0x68c4e)
```

**Comment by lacygoill** [comment] 2020-07-16 23:28
Try to reproduce on master, because it may have been fixed by one of these:

   - [8.2.0989](https://github.com/vim/vim/releases/tag/v8.2.0989)  crash after resizing a terminal window
   - [8.2.1030](https://github.com/vim/vim/releases/tag/v8.2.1030)  reducing size of a terminal window may cause a crash

**Comment by brammool** [comment] 2020-07-17 20:13
Most likely 8.2.1030 fixes this.  Please reopen with more info when it doesn't.

**Closed as completed by brammool** 2020-07-17 20:13 UTC
