### ISSUE TITLE
Gvim stable version 8.2.2824 colorscheme is broken.

### ISSUE THREAD

**Issue by hungpham3112** [vim/vim#9678] opened 2022-02-01 05:50 UTC
### Steps to reproduce

1. On Windows, download vim stable using scoop: 

`scoop install vim `

2. Using this minimal vimrc:

```
call plug#begin('~/vimfiles/plugged')
Plug 'https://github.com/sainnhe/edge.git', {'as': 'edge'}
call plug#end()
set termguicolors
colorscheme edge
```
3. Open Gvim and see the result

### Expected behaviour

Display right `colorscheme,` not white background

### Version of Vim

8.2.2824

### Environment

OS:  Windows 11
Term: Windows Powershell

### Logs and stack traces

I thought this is a bug cause by this `colorscheme` but it's not. Here is the link to [my question](https://github.com/sainnhe/edge/issues/49)

**Comment by chrisbra** [comment] 2022-02-01 09:16
okay, can you please minimize this: Does it work without scoop? Can you simply download the colorscheme so we can test without installing Plug? Is that in the terminal or in the gui? Not clear from your description.

**Comment by hungpham3112** [comment] 2022-02-01 10:00
> okay, can you please minimize this: Does it work without scoop? Can you simply download the colorscheme so we can test without installing Plug? Is that in the terminal or in the gui? Not clear from your description.

No, it didn't work with version 8.2.2824. I tried to download .exe file from vim-win32. It was broken both terminal and gui vim in window but you can see it easier with GUI

**Comment by chrisbra** [comment] 2022-02-01 11:46
can you please provide a screenshot and mark what exactly is wrong?

**Comment by chrisbra** [comment] 2022-02-01 11:53
I checked it out locally:
- with `:set bg=dark`
![image](https://user-images.githubusercontent.com/244927/151963818-df2a2acf-43a7-4e5a-b43d-cf39315ae396.png)
- with `:set bg=light`
![image](https://user-images.githubusercontent.com/244927/151963884-f56effcd-1370-4f91-86b7-c86a26ac0e0a.png)


Apart from the fact that the light is very light and hard to read, what exactly is wrong?

**Comment by hungpham3112** [comment] 2022-02-01 13:33
I opened GVim and run` :e $myvimrc` to show you minimal vimrc, and also version of vim. It's should be dark edge default theme not the light screen.

![bandicam 2022-02-01 20-26-56-935](https://user-images.githubusercontent.com/75968004/151977178-0d1611e7-7e47-485d-99d3-cea4b8f1770c.gif)

**Comment by lacygoill** [comment] 2022-02-01 13:47
Possible duplicate of https://github.com/vim/vim/issues/8150

**Comment by k-takata** [comment] 2022-02-01 13:49
Then, closing.

**Closed as completed by k-takata** 2022-02-01 13:49 UTC
Labels: duplicate

**Comment by chrisbra** [comment] 2022-02-01 14:08
default background for `gvim --clean` is light, so please use `:set bg=dark`

**Comment by hungpham3112** [comment] 2022-02-01 15:57
Here is your `:set bg=dark`. This is the error with this version, not duplicate or something like that. 

![bandicam 2022-02-01 22-51-38-388](https://user-images.githubusercontent.com/75968004/152002965-03eddb89-a1ec-4800-8873-07355b37cf05.gif)

**Comment by hungpham3112** [comment] 2022-02-07 11:47
I found exactly what happening in here. It caused by `scoop install vim`. It went wrong in all version with scoop install vim or vim-nightly. `.exe` file still working. It seems problem with scoop.
