### ISSUE TITLE
TerminalOpen event

### ISSUE THREAD

**Issue by mattn** [vim/vim#2422] opened 2017-12-07 03:29 UTC
Current implementation provide way to set options to the `:terminal` buffer using BufWinEnter.

```
au BufWinEnter * if &buftype == 'terminal' | setlocal bufhidden=hide | endif
```
But this is bits bothersome. How about add TerminalOpen event which raise only when open `:terminal`?

**Comment by Shougo** [comment] 2017-12-07 03:47
I think `TermOpen` name is better.
Because, `TermChanged` and `TermResponse` events are already exists.

**Comment by brammool** [comment] 2017-12-07 21:48
Shougo wrote:

> I think `TermOpen` name is better.
> Because, `TermChanged` and `TermResponse` events are already exists.

Those events relate to 'term', so it's actualy better to avoid prefixing
with "Term" and use "Terminal".

-- 
From "know your smileys":
 :-)-O	Smiling doctor with stethoscope

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by jamessan** [comment] 2017-12-07 21:58
Neovim also uses `TermOpen` for this event, so consistency would be nice.

**Comment by brammool** [comment] 2017-12-08 12:44
James McCoy wrote:

> Neovim also uses `TermOpen` for this event, so consistency would be nice.

All terminal window stuff is new, it's best to make it as clear now, we
can't change it later.  We already have confusion between "term",
"terminal" and "terminal window".  Since the option is called 'term', we
can associate things with that option name.  But the new terminal window
feature is clearly called "terminal" and not "term", so let's use that
name.  The shortening can only cause confusion.

-- 
In order for something to become clean, something else must become dirty;
but you can get everything dirty without getting anything clean.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by wsdjeg** [comment] 2017-12-23 03:54
Still prefer TermOpen，as it is already exist in neovim.

**Comment by ZyX-I** [comment] 2017-12-24 11:39
“Term” is a recognized shortcut for “terminal”, no matter whether you spell it short or long if something like TermFocusLost (i.e. FocusLost controlled by terminal escape sequences; only the example) is implemented to fire on events caused by outside terminal that will cause confusion. If it is not, no confusion in TermOpen. Confusion could only be avoided by adding adjective, not by avoiding shortening.

And do not forget that `:terminal` can be shortened to `:term`, and you did exactly that in documentation as well (under `:h terminal-use`, in tag names: `:h term++close`), in `&termkey` and `&termsize` option names, in all associated function names, in plugin name (termdebug). If you want to stay consistent on that, do rename everything I mentioned.

**Comment by wsdjeg** [comment] 2017-12-24 11:43
yeah, the first time I know the key word `term` is in vim8, before this, the terminal is `:terminal` and `:te` in neovim, then vim8 add a new command `:term` instead of using `:te`.

**Comment by ZyX-I** [comment] 2017-12-24 11:50
@wsdjeg Both Vim and Neovim added command `:terminal` and nothing else. But Neovim removed `:tearoff` as well, so minimal shortcut in Neovim is `:te` and minimal shortcut in Vim is `:ter`.

**Comment by wsdjeg** [comment] 2017-12-24 11:57
oh, I got it, sorry for my previous comment

**Comment by chrisbra** [comment] 2018-01-02 14:25
closing for #2487

**Closed as completed by chrisbra** 2018-01-02 14:25 UTC
Labels: discuss, feature-terminal
