### ISSUE TITLE
matchparen delays

### ISSUE THREAD

**Issue by vilnar** [vim/vim#11644] opened 2022-12-01 07:33 UTC
### Steps to reproduce

here is the test file `test.log`

```
{Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum {Lorem}}
{Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum {Lorem}}
{Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum {Lorem}}
{Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum {Lorem}}
{Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum {Lorem}}
{Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum {Lorem}}
{Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum {Lorem}}
{Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum {Lorem}}
{Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum {Lorem}}
{Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum {Lorem}}
{Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum {Lorem}}
```

```sh
vim --clean -c "set nowrap" test.log
```

running `:source $VIMRUNTIME/plugin/matchparen.vim`

Try to move down or up, holding down the keys, just on the first column, there is a delay.

There is also a delay in visual line mode if you start from the first column.

https://user-images.githubusercontent.com/7551398/204994156-d3f7b2cd-2905-4cb7-bb42-8c146072be1a.mp4

### Expected behaviour

This behavior wasn't there before, for example I didn't notice this delay in v9.0.0933

### Version of Vim

9.0 Included patches: 1-978

### Environment

Operating system: Ubuntu 20.04.5 LTS
Terminal: GNOME Terminal 3.36.2
Value of $TERM: xterm-256color
Shell: GNU bash, version 5.0.17(1)-release

**Comment by chrisbra** [comment] 2022-12-01 07:54
Hm,
I cannot really reproduce on linux (putty, 9.0.978) and Windows with 9.0.975. I assume it works okay again, if you use `:NoMatchParen`?

I have some suggestions however
- can you please bisect the offending commit? I noticed the matchparen plugin was touched in 28a896f54d4b2f2b4bef8ef4144dde1673c9d6e7 just a couple of days ago, but the changes should not affect this issue here.
- Have you tried to adjust the search timeout? By default it uses 60 ms in insert mode and in other modes 300 ms. Use the global variables `g:matchparen_timeout` and `g:matchparen_insert_timeout` to adjust those.

**Comment by vilnar** [comment] 2022-12-01 08:55
Thanks for the answer!

Yes, if running `:NoMatchParen` is no delay.


https://user-images.githubusercontent.com/7551398/205008839-b3457841-0251-4329-943c-5f917834840e.mp4



I tried the previous patch you mentioned c13e998d4a82e2c90efb4bbc1dd4ea2d6c424592 (v9.0.0968)
The delay is reproduced.

Tried to set `g:matchparen_timeout = 50` the delay is reproduced.

**Comment by brammool** [comment] 2022-12-01 10:54
I can see it's a bit slow.  Finding the match takes about 80 msec.  That's not bad, but slow enough to be noticed.

The matchparen plugin hasn't changed, there might be some code change that affects this.  That might be a challenge to find.  Best would be to make a script to reproduce it and then run it with profiling, so the code can be located.  Hopefully that reveals something.  Anyone up for doing that?

**Comment by dpelle** [comment] 2022-12-01 13:12
I cannot reproduce on xubuntu-18.05.6. Or at least it's fast enough that I don't notice this issue.
If someone can clearly reproduce it, I suggest to bissect to find which commit slows it down.
From the ticket description, we know that:
* v9.0.0978 is slow
* v9.0.0933 is fast

So it's a small range of versions to narrow down.

**Comment by vilnar** [comment] 2022-12-01 16:42
Thanks @dpelle  for the tip about finding the commit.

Found that I'm starting to reproduce from a commit c96311b5be307f5a1d1b20a0ec930d63964e7335 (v9.0.0950)


https://user-images.githubusercontent.com/7551398/205109453-944da951-5cf4-4c6d-b551-489ecaaea8f4.mp4



The previous commit works without delay ef2c325f5e3c437b722bb96bf369ba2a5c541163 (v9.0.0949)


https://user-images.githubusercontent.com/7551398/205109500-5a512ad8-6e87-4764-9d4f-7c507afaa92a.mp4



Sorry, I don't know how to profile.
Unfortunately, I have no experience with C language development.

**Comment by vilnar** [comment] 2022-12-01 16:54
Looks like I missed this when describing the problem:
the delay is reproduce only if keys (up or down) are pressed and held.

**Comment by brammool** [comment] 2022-12-01 22:14
> Thanks @dpelle  for the tip about finding the commit.
> 
> Found that I'm starting to reproduce from a commit
> c96311b5be307f5a1d1b20a0ec930d63964e7335 (v9.0.0950)

This patch indeed makes searching slower, it tries many positions for a
match.  However, that should have been fixed by the next patch,
9.0.0951, which was missing a part that is in 9.0.0953.
Thus please compare with 9.0.0953 or later.

-- 
hundred-and-one symptoms of being an internet addict:
196. Your computer costs more than your car.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by vilnar** [comment] 2022-12-02 07:50
Tried patches:
v9.0.0951
v9.0.0952
v9.0.0953
v9.0.0954
v9.0.0955
A delay is reproduce in each patch.

**Comment by vilnar** [comment] 2022-12-03 16:09
Tried reverting the change from the patch v9.0.0950 c96311b5be307f5a1d1b20a0ec930d63964e7335
https://github.com/vim/vim/blob/c0370529c027abc5b1698d53fcfb8c02a0c515da/src/search.c#L844
replaced
```
matchcol = regmatch.rmm_matchcol;
```
to
```
matchcol = matchpos.col;
```
There is no delay. I don't understand why so.
Checked it with the latest current commit c0370529c027abc5b1698d53fcfb8c02a0c515da

**Comment by vilnar** [comment] 2022-12-06 20:34
Hello. It seems that it was possible to write a script to reproduce the bug

File `issue-11644.vim`:
```
set nowrap
source $VIMRUNTIME/plugin/matchparen.vim

edit test.log

call feedkeys('jjjjjjjjjj')
call feedkeys('kkkkkkkkkk')
call feedkeys('jjjjjjjjjj')
call feedkeys('kkkkkkkkkk')
call feedkeys('jjjjjjjjjj')
call feedkeys('kkkkkkkkkk')
call feedkeys('jjjjjjjjjj')
call feedkeys('kkkkkkkkkk')
call feedkeys(":q\<CR>")
```

`test.log` the same file that was in the first message


Run
```sh
time vim --clean -S issue-11644.vim
```


Result with latest current commit 86b4816766d976a7ecd4403eca1f8bf6b4105800
```
real	0m3,755s
user	0m3,350s
sys	0m0,401s
```

Result with commit ef2c325f5e3c437b722bb96bf369ba2a5c541163 tag: v9.0.0949
```
real	0m0,185s
user	0m0,057s
sys	0m0,023s
```

**Comment by brammool** [comment] 2022-12-10 22:38
> Hello. It seems that it was possible to write a script to reproduce the bug
> 
> File `issue-11644.vim`:
> ```
> set nowrap
> source $VIMRUNTIME/plugin/matchparen.vim
> 
> edit test.log
> 
> call feedkeys('jjjjjjjjjj')
> call feedkeys('kkkkkkkkkk')
> call feedkeys('jjjjjjjjjj')
> call feedkeys('kkkkkkkkkk')
> call feedkeys('jjjjjjjjjj')
> call feedkeys('kkkkkkkkkk')
> call feedkeys('jjjjjjjjjj')
> call feedkeys('kkkkkkkkkk')
> call feedkeys(":q\<CR>")
> ```
> 
> `test.log` the same file that was in the first message
> 
> 
> Run
> ```sh
> time vim --clean -S issue-11644.vim
> ```
> 
> 
> Result with latest current commit 86b4816766d976a7ecd4403eca1f8bf6b4105800
> ```
> real	0m3,755s
> user	0m3,350s
> sys	0m0,401s
> ```
> 
> Result with commit ef2c325f5e3c437b722bb96bf369ba2a5c541163 tag: v9.0.0949
> ```
> real	0m0,185s
> user	0m0,057s
> sys	0m0,023s
> ```

I played around with this a bit, which is quite tricky.  This uses
feedkeys() without a second argument, which means that everything goes
in the typeahead buffer.  And nothing should be done otherwise, the
sequence of commands would change.

I used reltime(), which is much more accurate than the time command.
This excludes the time to get Vim up and running.

I also added this to the script to check that CursorMoved is actually
triggered (when something in the script is wrong the count will be zero
or another number smaller than 81):
	let g:cursor_moved_count = 0
	au CursorMoved  * let g:cursor_moved_count += 1

Then I could reproduce the difference between using "matchpos.col"
and "rmm_matchcol".  I added log calls, and noticed that rmm_matchcol
isn't set to the right column.  I'll see if that can be fixed.

-- 
       He was not in the least bit scared to be mashed into a pulp
       Or to have his eyes gouged out and his elbows broken;
       To have his kneecaps split and his body burned away
       And his limbs all hacked and mangled, brave Sir Robin.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Closed as completed** 2022-12-11 14:18 UTC
Labels: bug

**Comment by vilnar** [comment] 2022-12-11 14:54
Thanks! Checked patch 9.0.1047 - it works!
