### ISSUE TITLE
esckeys and c_CTRL-V don't play nicely

### ISSUE THREAD

**Issue by taralx** [vim/vim#5254] opened 2019-11-20 18:26 UTC
Version: 8.1.2269 (debian)

Steps to reproduce in xterm:

1. :set esckeys
2. i^V^K
(github doesn't like angle brackets, those are control+V and control+K)

Expected result:

^K

Actual result:

^[[27;5;107~

**Comment by brammool** [comment] 2019-11-20 22:04
This is not related to 'esckeys' but modifyOtherKeys (see the help for that).

I had been wondering whether we should translate the escape sequence back to the character it encodes, but decided (so far) that it's more consistent to keep the escape code.  Thus this is working as intended, I'll close it.

Why would you want ^K to show?

**Closed as completed by brammool** 2019-11-20 22:04 UTC

**Comment by taralx** [comment] 2019-11-20 23:00
Mostly because I use it to type :help ^K instead of having to type :help c_CTRL-K.

**Comment by taralx** [comment] 2019-11-20 23:01
I referenced esckeys because :set noek makes the problem go away (at the cost of losing the very nice esckeys functionality).

**Comment by k-takata** [comment] 2019-11-26 06:49
I'm also wondering whether the current behavior is actually useful.
modifyOtherKeys might be very useful for mapping some special key combinations. However, I don't think it's so useful for `i_CTRL-V` or `c_CTRL-V`. E.g. when editing shell scripts, batch files, Vim scripts or some other scripts, I sometimes want to emit actual control code like escape, CTRL-V, etc. (E.g. `echo ^[[31mred^[[m` to show a red message.)
Now `i_CTRL-V_CTRL-[` inserts an escape sequence (`^[[91;5u`) instead of `^[`. Is it really useful?

**Comment by brammool** [comment] 2019-11-26 13:35
Ken Takata wrote:

> I'm also wondering whether the current behavior is actually useful.
> modifyOtherKeys might be very useful for mapping some special key
> combinations. However, I don't think it's so useful for `i_CTRL-V` or
> `c_CTRL-V`. E.g. when editing shell scripts, batch files, Vim scripts
> or some other scripts, I sometimes want to emit actual control code
> like escape, CTRL-V, etc. (E.g. `echo ^[[31mred^[[m` to show a red
> message.)
> Now `i_CTRL-V_CTRL-[` inserts an escape sequence (`^[[91;5u`) instead
> of `^[`. Is it really useful?

I've been wondering if when using CTRL-V should insert the actual Esc
sequence or the character it encodes.  So far using the Esc sequence has
helped find out what the terminal actually sends, thus I kept that.

We could add an option, but that makes it unpredictable and complicated.

Since in this mode we can distinguish variants of CTRL-V, perhaps we can
make CTRL-V and CTRL-SHIFT-V do either of the two?

-- 
hundred-and-one symptoms of being an internet addict:
125. You begin to wonder how often it REALLY is necessary to get up
     and shower or bathe.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by k-takata** [comment] 2019-11-26 14:43
> So far using the Esc sequence has helped find out what the terminal actually sends, thus I kept that.

That might be useful for debugging.


> Since in this mode we can distinguish variants of CTRL-V, perhaps we can make CTRL-V and CTRL-SHIFT-V do either of the two?

Ah, that's a good idea.
I prefer CTRL-V to insert encoded character to keep backward compatibility, and CTRL-SHIFT-V to insert Esc sequence.
