### ISSUE TITLE
vim 8.2 --version plays hide and seek

### ISSUE THREAD

**Issue by gregrwm** [vim/vim#7815] opened 2021-02-11 00:23 UTC
vim --version finicky about when it gives any output:
```
  $  vim=./.GVim-v8.2.2488.glibc2.15-x86_64.AppImage
  0$  $vim --clean --version >/tmp/v82 2>&1              #this command captures nothing!
  0$  $vim --clean --version >/tmp/v82o 2>/tmp/v82e      #also nothing!
  0$  $vim --clean --version 2>&1 >/tmp/v82y             #this finally coaxes --version from 8.2
  0$  ls -ld /tmp/v82*
-rw-rw-r-- 1 g greg    0 Feb 10 16:04 /tmp/v82       #nothing!
-rw-rw-r-- 1 g greg    0 Feb 10 16:04 /tmp/v82e
-rw-rw-r-- 1 g greg    0 Feb 10 16:04 /tmp/v82o
-rw-rw-r-- 1 g greg 4081 Feb 10 16:04 /tmp/v82y     #got it here finally
```
By contrast the 8.1 behavior exhibited below is the behavior i expect.
```
  $  dpkg-query -W vim
vim     2:8.1.2269-1ubuntu5                              #(8.1 as shipped with ubuntu focal)
  0$  vim --clean --version >/tmp/v81 2>&1
  0$  vim --clean --version >/tmp/v81o 2>/tmp/v81e           
  0$  vim --clean --version 2>&1 >/tmp/v81y                  
  0$  ls -ld /tmp/v81*
-rw-rw-r-- 1 g greg 3106 Feb 10 17:57 /tmp/v81     #8.1 plays fair
-rw-rw-r-- 1 g greg    0 Feb 10 17:57 /tmp/v81e
-rw-rw-r-- 1 g greg 3106 Feb 10 17:57 /tmp/v81o
-rw-rw-r-- 1 g greg 3106 Feb 10 17:57 /tmp/v81y
```
```
  $  vim81ver=$(vim --version 2>&1)                                                    #8.1 plays fair
  $  vim82ver=$($vim --version 2>&1)                                                   #8.2 plays hide&seek
  $  declare -p vim82ver vim81ver
declare -- vim82ver=""                                                                    #8.2: nothing here!
declare -- vim81ver="VIM - Vi IMproved 8.1 (2018 May 18, compiled Apr 15 2020 06:40:31)   #8.1 is fine
Included patches: 1-2269
Modified by team+vim@tracker.debian.org
Compiled by team+vim@tracker.debian.org
Huge version without GUI.  Features included (+) or not (-):
+acl               -farsi             -mouse_sysmouse    -tag_any_white
+arabic            +file_in_path      +mouse_urxvt       -tcl
+autocmd           +find_in_path      +mouse_xterm       +termguicolors
+autochdir         +float             +multi_byte        +terminal
-autoservername    +folding           +multi_lang        +terminfo
-balloon_eval      -footer            -mzscheme          +termresponse
+balloon_eval_term +fork()            +netbeans_intg     +textobjects
-browse            +gettext           +num64             +textprop
++builtin_terms    -hangul_input      +packages          +timers
+byte_offset       +iconv             +path_extra        +title
+channel           +insert_expand     -perl              -toolbar
+cindent           +job               +persistent_undo   +user_commands
-clientserver      +jumplist          +postscript        +vartabs
-clipboard         +keymap            +printer           +vertsplit
+cmdline_compl     +lambda            +profile           +virtualedit
+cmdline_hist      +langmap           -python            +visual
+cmdline_info      +libcall           +python3           +visualextra
+comments          +linebreak         +quickfix          +viminfo
+conceal           +lispindent        +reltime           +vreplace
+cryptv            +listcmds          +rightleft         +wildignore
+cscope            +localmap          -ruby              +wildmenu
+cursorbind        -lua               +scrollbind        +windows
+cursorshape       +menu              +signs             +writebackup
+dialog_con        +mksession         +smartindent       -X11
+diff              +modify_fname      +sound             -xfontset
+digraphs          +mouse             +spell             -xim
-dnd               -mouseshape        +startuptime       -xpm
-ebcdic            +mouse_dec         +statusline        -xsmp
+emacs_tags        +mouse_gpm         -sun_workshop      -xterm_clipboard
+eval              -mouse_jsbterm     +syntax            -xterm_save
+ex_extra          +mouse_netterm     +tag_binary
+extra_search      +mouse_sgr         -tag_old_static
   system vimrc file: \"\$VIM/vimrc\"
     user vimrc file: \"\$HOME/.vimrc\"
 2nd user vimrc file: \"~/.vim/vimrc\"
      user exrc file: \"\$HOME/.exrc\"
       defaults file: \"\$VIMRUNTIME/defaults.vim\"
  fall-back for \$VIM: \"/usr/share/vim\"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -Wdate-time  -g -O2 -fdebug-prefix-map=/build/vim-iU6mZD/vim-8.1.2269=. -fstack-protector-strong -Wformat -Werror=format-security -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim        -lm -ltinfo -lnsl  -lselinux  -lcanberra -lacl -lattr -lgpm -ldl     -L/usr/lib/python3.8/config-3.8-x86_64-linux-gnu -lpython3.8 -lcrypt -lpthread -ldl -lutil -lm -lm      "
  $
  $  cat /tmp/v82.
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Feb  9 2021 08:24:52)
Included patches: 1-2488
Compiled by travis@travis-job-4e22b497-0cc0-4353-bd05-c5bdb4eb329c
Huge version with GTK2 GUI.  Features included (+) or not (-):
+acl               -farsi             +mouse_sgr         +tag_binary
+arabic            +file_in_path      -mouse_sysmouse    -tag_old_static
+autocmd           +find_in_path      +mouse_urxvt       -tag_any_white
+autochdir         +float             +mouse_xterm       +tcl
-autoservername    +folding           +multi_byte        +termguicolors
+balloon_eval      -footer            +multi_lang        +terminal
+balloon_eval_term +fork()            -mzscheme          +terminfo
+browse            +gettext           +netbeans_intg     +termresponse
++builtin_terms    -hangul_input      +num64             +textobjects
+byte_offset       +iconv             +packages          +textprop
+channel           +insert_expand     +path_extra        +timers
+cindent           +ipv6              +perl              +title
+clientserver      +job               +persistent_undo   +toolbar
+clipboard         +jumplist          +popupwin          +user_commands
+cmdline_compl     +keymap            +postscript        +vartabs
+cmdline_hist      +lambda            +printer           +vertsplit
+cmdline_info      +langmap           +profile           +virtualedit
+comments          +libcall           +python/dyn        +visual
+conceal           +linebreak         +python3/dyn       +visualextra
+cryptv            +lispindent        +quickfix          +viminfo
+cscope            +listcmds          +reltime           +vreplace
+cursorbind        +localmap          +rightleft         +wildignore
+cursorshape       +lua               +ruby              +wildmenu
+dialog_con_gui    +menu              +scrollbind        +windows
+diff              +mksession         +signs             +writebackup
+digraphs          +modify_fname      +smartindent       +X11
+dnd               +mouse             +sound             -xfontset
-ebcdic            +mouseshape        +spell             +xim
+emacs_tags        +mouse_dec         +startuptime       -xpm
+eval              -mouse_gpm         +statusline        +xsmp_interact
+ex_extra          -mouse_jsbterm     -sun_workshop      +xterm_clipboard
+extra_search      +mouse_netterm     +syntax            -xterm_save
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "././/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK -pthread -I/usr/include/gtk-2.0 -I././/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I././/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/libpng16 -g -O2 -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 
Linking: gcc -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E -L/usr/local/lib -Wl,--as-needed -o vim -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfontconfig -lfreetype -lSM -lICE -lXt -lX11 -lXdmcp -lSM -lICE -lm -ltinfo -lelf -lcanberra -ldl -L/usr/lib -llua5.3 -Wl,-E -fstack-protector-strong -L/usr/local/lib -L././/lib/x86_64-linux-gnu/perl/5.26/CORE -lperl -ldl -lm -lpthread -lcrypt -L././/lib/x86_64-linux-gnu -ltcl8.6 -ldl -lz -lpthread -lm -lruby-2.5 -lpthread -lgmp -ldl -lcrypt -lm -L/usr/lib
  $
  $  echo $TERM
screen
  $  tmux -V
tmux 3.1b
  $  uname -a
Linux e540 5.4.0-60-generic #67-Ubuntu SMP Tue Jan 5 18:31:36 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
  $  cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"
  $
```

**Comment by tonymec** [comment] 2021-02-11 00:45
I can't reproduce the described behaviour with my own-built Vim 8.2.2496 (Big) on openSUSE Linux 5.2

linux-tuxedo:~ # vim --version >v8.2 2>&1
linux-tuxedo:~ # vim --version >v8.2o 2>v8.2e
linux-tuxedo:~ # vim --version >v8.2y
linux-tuxedo:~ # ll v8.2*
-rw-r--r-- 1 root root 3842 Feb 11 01:32 v8.2
-rw-r--r-- 1 root root    0 Feb 11 01:33 v8.2e
-rw-r--r-- 1 root root 3842 Feb 11 01:33 v8.2o
-rw-r--r-- 1 root root 3842 Feb 11 01:33 v8.2y

This is how I configure Vim:

export CONF_OPT_GUI='--enable-gui=gtk3'
export CONF_OPT_MULTIBYTE='--enable-multibyte'
export CONF_OPT_AUTOSERVE='--enable-autoservername'
export CONF_OPT_FEAT='--with-features=big'
#export CONF_ARGS2='--with-vim-name=vim-big'
export CONF_OPT_COMPBY='"--with-compiledby=antoine.mechelynck@gmail.com"'

and the resulting --version output is as follows:

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Feb 10 2021 21:49:04)
Included patches: 1-2496
Compiled by antoine.mechelynck@gmail.com
Big version with GTK3 GUI.  Features included (+) or not (-):
+acl               -farsi             +mouse_sgr         +tag_binary
+arabic            +file_in_path      -mouse_sysmouse    -tag_old_static
+autocmd           +find_in_path      +mouse_urxvt       -tag_any_white
+autochdir         +float             +mouse_xterm       -tcl
+autoservername    +folding           +multi_byte        +termguicolors
+balloon_eval      -footer            +multi_lang        -terminal
-balloon_eval_term +fork()            -mzscheme          +terminfo
+browse            +gettext           +netbeans_intg     +termresponse
++builtin_terms    -hangul_input      +num64             +textobjects
+byte_offset       +iconv             +packages          +textprop
+channel           +insert_expand     +path_extra        +timers
+cindent           +ipv6              -perl              +title
+clientserver      +job               +persistent_undo   +toolbar
+clipboard         +jumplist          +popupwin          +user_commands
+cmdline_compl     +keymap            +postscript        +vartabs
+cmdline_hist      +lambda            +printer           +vertsplit
+cmdline_info      +langmap           -profile           +virtualedit
+comments          +libcall           -python            +visual
+conceal           +linebreak         -python3           +visualextra
+cryptv            +lispindent        +quickfix          +viminfo
+cscope            +listcmds          +reltime           +vreplace
+cursorbind        +localmap          +rightleft         +wildignore
+cursorshape       -lua               -ruby              +wildmenu
+dialog_con_gui    +menu              +scrollbind        +windows
+diff              +mksession         +signs             +writebackup
+digraphs          +modify_fname      +smartindent       +X11
+dnd               +mouse             +sound             -xfontset
-ebcdic            +mouseshape        +spell             +xim
+emacs_tags        +mouse_dec         +startuptime       +xpm
+eval              +mouse_gpm         +statusline        +xsmp_interact
+ex_extra          -mouse_jsbterm     -sun_workshop      +xterm_clipboard
+extra_search      +mouse_netterm     +syntax            +xterm_save
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0 -I/usr/include/libxkbcommon -I/usr/include/wayland -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/uuid -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -O2 -fno-strength-reduce -Wall -D_REENTRANT -D_REENTRANT -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 
Linking: gcc -L/usr/local/lib -Wl,--as-needed -o vim -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE -lm -ltinfo -lelf -lselinux -lcanberra -lacl -lattr -lgpm -ldl 

I did the experiment in a "true" xterm, version 330.


Best regards,
Tony.

**Comment by tonymec** [comment] 2021-02-11 00:47
P.S. My shell is bash version 4.4.23(1)-release (x86_64-suse-linux-gnu)

**Comment by tonymec** [comment] 2021-02-11 00:56
P.P.S. No change if I add --clean on the command line (i.e. still behaves as expected, v8.2e is empty and the other three are still the same length as before).

Best regards,
Tony.

**Comment by dpelle** [comment] 2021-02-11 07:20
This is what I see:
```
$ vim --clean --version >/tmp/v82 2>&1
$ vim --clean --version >/tmp/v82o 2>/tmp/v82
$ vim --clean --version 2>&1 >/tmp/v82y
$ ls -l /tmp/v82*
-rw-rw-r-- 1 pel pel    0 feb 11 08:13 /tmp/v82
-rw-rw-r-- 1 pel pel 4289 feb 11 08:13 /tmp/v82o
-rw-rw-r-- 1 pel pel 4289 feb 11 08:13 /tmp/v82y

$ gvim -f -g --clean --version >/tmp/gv82 2>&1
$ gvim -f -g --clean --version >/tmp/gv82o 2>/tmp/gv82
$ gvim -f -g --clean --version 2>&1 >/tmp/gv82y
$ ls -l /tmp/gv82*
-rw-rw-r-- 1 pel pel    0 feb 11 08:17 /tmp/gv82
-rw-rw-r-- 1 pel pel    0 feb 11 08:17 /tmp/gv82o
-rw-rw-r-- 1 pel pel 4289 feb 11 08:17 /tmp/gv82y
```
I use vim-8.2.2497 (huge), GTK2 GUI on Linux x86_64 xubuntu-18.04.5, using bash-4.4.20 shell.

**Comment by drmikehenry** [comment] 2021-02-11 14:43
I think this is long-standing expected behavior.  The `mch_msg()` function shown below is responsible for `vim --version` output:
https://github.com/vim/vim/blob/v8.2.2488/src/message.c#L3184-L3211
```c
    void
mch_msg(char *str)
{
#if (defined(UNIX) || defined(FEAT_GUI)) && !defined(ALWAYS_USE_GUI) && !defined(VIMDLL)
    // On Unix use stdout if we have a tty.  This allows "vim -h | more" and
    // uses mch_errmsg() when started from the desktop.
    // When not going to start the GUI also use stdout.
    // On Mac, when started from Finder, stderr is the console.
    if (
# ifdef UNIX
#  ifdef MACOS_X
	    (isatty(2) && strcmp("/dev/console", ttyname(2)) != 0)
#  else
	    isatty(2)
#  endif
#  ifdef FEAT_GUI
	    ||
#  endif
# endif
# ifdef FEAT_GUI
	    !(gui.in_use || gui.starting)
# endif
	    )
    {
	printf("%s", str);
	return;
    }
#endif
```

The output will be written if at least one of these two conditions is met:
1. `stderr` is a tty
2. No GUI is in use (or will be in use)

Note that though the version output is destined for `stdout`, the decision is based on whether `stderr` is a tty.

When `stderr` is redirected to a file or a pipe, the first condition above fails; but the version information will still be written if Vim is started without a GUI.  In the event that Vim intends to start a GUI and `stderr` is not a tty, then the output will be suppressed.

Vim starts a GUI when the `-g` argument is passed, or when the name of the executable file starts with `g`; that's why `gvim` invokes the GUI by default whereas `vim` does not:
https://github.com/vim/vim/blob/v8.2.2488/src/main.c#L1805-L1816
```c
/*
 * Check for: [r][e][g][vi|vim|view][diff][ex[im]]  (sort of)
 * If the executable name starts with "r" we disable shell commands.
 * If the next character is "e" we run in Easy mode.
 * If the next character is "g" we run the GUI version.
 * If the next characters are "view" we start in readonly mode.
 * If the next characters are "diff" or "vimdiff" we start in diff mode.
 * If the next characters are "ex" we start in Ex mode.  If it's followed
 * by "im" use improved Ex mode.
 */
    static void
parse_command_name(mparm_T *parmp)
```

For some Vim ports, the GUI may always be started.

I suspect this new build of Vim starts the GUI, unlike the previous builds.  Since `stderr` is also being redirected, no version output is generated.

Note that the inconsistent-seeming behavior in the original examples is explained by the various ways `stderr` is being redirected:

```
  $  vim=./.GVim-v8.2.2488.glibc2.15-x86_64.AppImage
  0$  $vim --clean --version >/tmp/v82 2>&1              #this command captures nothing!
  0$  $vim --clean --version >/tmp/v82o 2>/tmp/v82e      #also nothing!
  0$  $vim --clean --version 2>&1 >/tmp/v82y             #this finally coaxes --version from 8.2
```

Shell redirections are performed left-to-right.  In the first example, `stdout` is redirected to `/tmp/v82`, and then `stderr` is redirected to be the same as the current (already redirected) `stdout`, making both point to `/tmp/v82`.  The second example uses independent files for `stdout` and `stderr`, so the order doesn't matter.  But the third case first redirects `stderr` to the original location for `stdout` (the terminal), and then redirects `stdout` to `/tmp/v82y`, leaving `stderr` still pointing to a tty; this triggers the "`stderr` is a tty" condition for the `mch_msg()` function, causing the version output to be displayed.

As far as I can tell, there are only two ways to force Vim to display the version output on `stdout`: either ensure `stderr` is a terminal, or ensure the GUI will not be started.  Looking through the source, there is this section of the `command_line_scan()` function for parsing command-line arguments:

https://github.com/vim/vim/blob/v8.2.2488/src/main.c#L2278-L2282
```c
	    case 'v':		// "-v"  Vi-mode (as if called "vi")
		exmode_active = 0;
#if defined(FEAT_GUI) && !defined(VIMDLL)
		gui.starting = FALSE;	// don't start GUI
#endif
```

The switch `-v` is intended to force Vi-compatible mode; but it has the side effect of setting `gui-starting` to `FALSE`, e.g.:
```sh
$ vim --version 2>/dev/null | wc -c
4100

$ gvim --version 2>/dev/null | wc -c
0

$ gvim -v --version 2>/dev/null | wc -c
4100
```

So perhaps adding a `-v` switch will make the version check work as expected.

Michael Henry

**Closed as completed** 2021-02-11 18:08 UTC

**Comment by gregrwm** [comment] 2021-02-11 18:12
my 2¢:
either the manual should clarify that if you want to capture --version into a bash variable you need 'vim -vV'
or vim -V should understand it won't be starting any gui and behave accordingly.

**Comment by gregrwm** [comment] 2021-02-11 18:50
hopefully the manual will clarify that if you want to capture --version into stdout, eg a bash variable, you need '[g]vim -v --version'.  (the gvim appimage is the only appimage available.)

**Comment by gregrwm** [comment] 2021-02-11 19:00
`gvim --help|&less` is also mute!  This is terrible behavior in my opinion.
`gvim --help|less` leaves standard error hidden outside of less and thus invisible to the user.  Not good.
yes `gvim -v --help|&less` works but it's certainly not intuitive.
