### ISSUE TITLE
Error detected while processing function <SNR>39_Highlight_Matching_Pair:    in bash file

### ISSUE THREAD

**Issue by vikkitharan** [vim/vim#3280] opened 2018-08-04 23:31 UTC
The title error message appears when the cursor moves between curly brackets in a bash file. The file contains  ' { } '.  ( There are four characters)

it seems the error is not logical and it is reported after patch 8.1.0112.

==========================
steps to duplicate:
1. echo " ' {} ' " > /tmp/2.sh
2. vim((v8.1.0112)|BISECTING)$ src/vim /tmp/2.sh
3. cross the cursor '{' and '}' by moving left to right. error appears

===========================
details error:
Error detected while processing function <SNR>39_Highlight_Matching_Pair:                                              
line   78:
E475: Invalid argument: 0

===========================
vim((v8.1.0111)|BISECTING)$ git bisect good
3dddb09c98825acefa6f2d94bb369b8e00d7b3e5 is the first bad commit
commit 3dddb09c98825acefa6f2d94bb369b8e00d7b3e5
Author: Bram Moolenaar <Bram@vim.org>
Date:   Sun Jun 24 19:01:59 2018 +0200

    patch 8.1.0112: no error when using bad arguments with searchpair()
    
    Problem:    No error when using bad arguments with searchpair().
    Solution:   Add error messages.

**Comment by k-takata** [comment] 2018-08-04 23:58
Please update the runtime files to 8.1.0143 (or later).
It includes a fix for this.

**Comment by k-takata** [comment] 2018-08-05 00:44
Duplicate of  #3225.

**Closed as completed by k-takata** 2018-08-05 00:44 UTC
Labels: duplicate

**Comment by vikkitharan** [comment] 2018-08-05 01:48
**Neither 8.1.0143 nor v8.1.0239** fixes the issue.

**Comment by k-takata** [comment] 2018-08-05 04:53
Please make sure that the updated `matchparen.vim` script is loaded.
If you execute vim without installing, old version of the script might be loaded.

To check which file is loaded, you can use the `:scriptnames` command.

> `Error detected while processing function <SNR>39_Highlight_Matching_Pair:`

The message says `<SNR>39`, so you should check the 39th scripts in the result of `:scriptnames`.
If the `Last Change` date of the script is not `2018 Jul 3`, your script is old.

**Comment by k-takata** [comment] 2018-08-05 05:12
> line 78:
> E475: Invalid argument: 0

This means that the error is occurred at the 78th line of the `s:Highlight_Matching_Pair()` function.
The 78th line of the function in the old version is:
https://github.com/vim/vim/blob/01164a6546b4c635daf96a1f17d1cb2d07f32a66/runtime/plugin/matchparen.vim#L117

And the 78th line of the function in the latest version is:
https://github.com/vim/vim/blob/218beb3e96bcb7b20395be3bec6076c767be71a1/runtime/plugin/matchparen.vim#L117

Obviously, the line in the latest version is a comment. So the error won't happen at the line with the latest version.

**Comment by vikkitharan** [comment] 2018-08-05 09:08
You are right. Old script was used. with new script issue is closed
