### ISSUE TITLE
Possibly inconsistent behavior

### ISSUE THREAD

**Issue by pierreganty** [vim/vim#13649] opened 2023-12-07 13:05 UTC
### Steps to reproduce

Contrast 
`1<C-v>`
which ends up in VISUAL BLOCK with
`vrl1<C-v>`
which ends up in VISUAL.

### Expected behaviour

I would expect the second sequence to also end up in VISUAL BLOCK because this is what I understood from the documentation.

### Version of Vim

9.0.2153

### Environment

MacOS 13.6
Terminal.app
xterm-256color
zsh

**Comment by zeertzjq** [comment] 2023-12-07 13:11
Exchanging `<C-V>` and `v` in the keys above also leads to Visual in the first case and Visual Block in the second case.

This seems to be describe by the following paragraph, which is a bit confusing.
```
			With [count] select the same number of characters or
			lines as used for the last Visual operation, but at
			the current cursor position, multiplied by [count].
			When the previous Visual operation was on a block both
			the width and height of the block are multiplied by
			[count].
```

**Comment by pierreganty** [comment] 2023-12-07 13:34
Thank you. Also changing `1` for `0` for the `[count]` ends up in different modes. The paragraph is indeed confusing.

**Comment by chrisbra** [comment] 2023-12-08 21:12
the problem is, this only ever applies, if you have entered visual mode before. So you can indeed end in different modes using the same key bindings. I was confused about it already 15 years ago or so. But it's been like this forever. If anybody has any clear doc improvements, please create a PR

**Comment by chrisbra** [comment] 2023-12-14 21:01
Let me close this. It's been like this for years. If anybody can think of a better description, please create a doc-PR. Thanks.

**Closed as completed by chrisbra** 2023-12-14 21:01 UTC
Labels: bug
