### ISSUE TITLE
Params inlay hints for vim 

### ISSUE THREAD

**Issue by hungpham3112** [vim/vim#9155] opened 2021-11-18 07:13 UTC
I hope in the future vim will support this feature like VSCode, it really helpful.
![image](https://user-images.githubusercontent.com/75968004/142369082-35e16562-e327-4f0f-bddc-a85e5c342f3e.png)

**Comment by chrisbra** [comment] 2021-11-18 08:27
Just to be clear here: You are talking about `Skip<Args>` in the picture? And that is not really in that line? That sounds like the virtual-text feature from neovim? Or are you talking about something different? Please provide a bit more detail here.

**Comment by bfrg** [comment] 2021-11-18 12:08
Duplicate of #7553.

**Closed as completed** 2021-11-18 12:25 UTC
Labels: duplicate, enhancement
