### ISSUE TITLE
visual block mode yank to clipboard adds newline

### ISSUE THREAD

**Issue by kinghrothgar** [vim/vim#2622] opened 2018-02-07 16:08 UTC
- `vim --version`:
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jan 28 2018 20:34:57)
Included patches: 1-1436
Compiled by Arch Linux
Huge version with GTK3 GUI.  Features included (+) or not (-):
+acl               +farsi             +mouse_sgr         -tag_any_white
+arabic            +file_in_path      -mouse_sysmouse    +tcl/dyn
+autocmd           +find_in_path      +mouse_urxvt       +termguicolors
-autoservername    +float             +mouse_xterm       +terminal
+balloon_eval      +folding           +multi_byte        +terminfo
+balloon_eval_term -footer            +multi_lang        +termresponse
+browse            +fork()            -mzscheme          +textobjects
++builtin_terms    +gettext           +netbeans_intg     +timers
+byte_offset       -hangul_input      +num64             +title
+channel           +iconv             +packages          +toolbar
+cindent           +insert_expand     +path_extra        +user_commands
+clientserver      +job               +perl/dyn          +vertsplit
+clipboard         +jumplist          +persistent_undo   +virtualedit
+cmdline_compl     +keymap            +postscript        +visual
+cmdline_hist      +lambda            +printer           +visualextra
+cmdline_info      +langmap           +profile           +viminfo
+comments          +libcall           +python/dyn        +vreplace
+conceal           +linebreak         +python3/dyn       +wildignore
+cryptv            +lispindent        +quickfix          +wildmenu
+cscope            +listcmds          +reltime           +windows
+cursorbind        +localmap          +rightleft         +writebackup
+cursorshape       +lua/dyn           +ruby/dyn          +X11
+dialog_con_gui    +menu              +scrollbind        -xfontset
+diff              +mksession         +signs             +xim
+digraphs          +modify_fname      +smartindent       -xpm
+dnd               +mouse             +startuptime       +xsmp_interact
-ebcdic            +mouseshape        +statusline        +xterm_clipboard
+emacs_tags        +mouse_dec         -sun_workshop      -xterm_save
+eval              +mouse_gpm         +syntax            
+ex_extra          -mouse_jsbterm     +tag_binary        
+extra_search      +mouse_netterm     +tag_old_static    
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "/etc/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -D_FORTIFY_SOURCE=2  -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -L. -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.26/core_perl/CORE  -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -L/usr/local/lib -Wl,--as-needed -o vim   -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lSM -lICE -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lelf -lnsl    -lacl -lattr -lgpm -ldl   -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.26/core_perl/CORE -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/perl5/5.26/core_perl/CORE -lperl -lpthread -lnsl -ldl -lm -lcrypt -lutil -lc   -L/usr/lib -ltclstub8.6 -ldl -lz -lpthread -lieee -lm
```

- Operating system/version:
Arch Linux with everything up-to-date as of 2018-02-06 21:00 UTC
If it matters, I am using i3-gaps as my WM.
- Terminal name/version:
termite v13
- `$TERM`:
Problem is in both xterm-termite and in tmux (screen-256color)

### Steps to reproduce using `vim -u NORC`

```
vim -u NORC
:set clipboard=unnamedplus
```
1. Now type `asdf asdf asdf`
2. Enter visual block mode
3. Select the middle `asdf` to assure no newline is contained in the selection
4. Press `y` to yank the text which also copies it into the Xorg CLIPBOARD buffer

### Actual behavior
The text copied into the X-Org clipboard has a newline added to it. This can be seen by using xsel or Ctrl+V anywhere else.
```
$ xsel -b -o
asdf
$
```

### Expected behavior
The clipboard to contain only the text I yanked. I expected xsel to print out the following (It adds the no newline warn):

```
$ xsel -b -o
asdf
\ No newline at end of selection
$
```

**Comment by tonymec** [comment] 2018-02-08 15:04
I believe that this behaviour is intended. Let me explain.

If you had selected the middle asdf characterwise, no newline would have been included and you would have been able to "put" it in the middle of a line.

Now let's imagine a different example. In an empty buffer, enter the following:
```
asdf asdf asdf asdf
asdf asdf asdf asdf
asdf asdf asdf asdf
asdf asdf asdf asdf
```
Now select the middle block of four "asdf" and yank it. The yanked block must include line breaks, otherwise the put operation would not be able to put it as a block — it would write both lines of the block as one, which is not the desired result.

Since Vim, like Unix, and IMHO with good reason (but whether or not it is indeed a good reason is a quite different can of worms and has occasionally in the past led to flamewars which I dont want to rekindle), regards line breaks as line **terminators** and not line **separators**, this means that every line of a blockwise yank (including the last one even if it is the only one) will have a proper end-of-line.

Best regards,
Tony.

**Comment by kinghrothgar** [comment] 2018-02-08 15:49
https://levenlabs.atlassian.net/wiki/spaces/PROD/pages/243892237/RFC+World-wide+Sessions

**Comment by chrisbra** [comment] 2018-03-06 11:27
That fact that pasting in Vim works and does not add a new line, makes clear, that the linebreak isn't actually there. So I am closing this. You can check, what is actually in the register by using the `:reg +` command.

If you enter `:reg +` it will show something like this:

    --- Register ---
    "+   asdf

While when a newline is present, Vim will show it like this:

    --- Register ---
    "+   asdf^J

(with the ^J one highlighted actual char).

So I am closing this.

**Closed as completed by chrisbra** 2018-03-06 11:27 UTC

**Comment by kinghrothgar** [comment] 2018-03-09 21:35
Thank you @tonymec and @chrisbra for the help! I agree it is not a vim bug and something else, I still haven't been able to hunt it down though.

**Comment by nuko8** [comment] 2018-03-10 02:15
To handle a selected region as a **visual block**, Vim uses a unique protocol dedicated to that.  Thanks to that, you can copy and paste between two different Vim instances **"block-wise"**.  The protocol is unique to Vim.  

That said, it would be better for Vim to do something when a user still want copy a block-wise selected region for those applications which don't understand it, .   The compromise is to add newlines. So, don't expect that **visual block** works nicely for every application including `xsel`.

**Comment by mikerobe** [comment] 2023-04-12 17:23
I have exactly this issue and it's a regular nuisance on the Mac. You select some text without newlines in it, and then paste that text in any application other than vim and there's a newline on the end.

It's clear from the register and pasting behavior within vim that the newline isn't there in vim, so something is happening between vim and the system clipboard that's adding this newline.

**Comment by chrisbra** [comment] 2023-04-12 20:56
Does it only happen when copying to/from the system clipboard? Do you possible :set clipboard option? or the 'guioptions'? 

You can possibly work-around this by striping the LF from the clipboard register and store the result in another register and use this for pasting.

**Comment by mikerobe** [comment] 2023-04-12 22:17
With a plain installation of vim (no vimrc), the clipboard is just internal, so on the Mac you have to call `:set clipboard=unnamed` for it to copy to the system for some reason (I don't know the behind the scenes reasons for that).

I think the right solution here is to find out why this is propagating a newline into the system clipboard in the first place and fix that. My guess is there's some typo somewhere in whatever code is bringing the vim registers into the system clipboard 🤔

**Comment by chrisbra** [comment] 2023-04-13 06:42
So it only happens when copy/pasting between the system-clipboard or not? It's not clear from your description. Please provide clear reproduction steps.

I think the reason for that is explained already [above](https://github.com/vim/vim/issues/2622#issuecomment-371994501).
