### ISSUE TITLE
Problematic ConTeXt Formatting

### ISSUE THREAD

**Issue by orbisvicis** [vim/vim#3650] opened 2018-12-01 01:39 UTC
```LaTeX
\starttext
    Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's
    standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it
    to make a type specimen book. It has survived not only five centuries, but also the leap into electronic
    typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset
    sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker
    including versions of Lorem Ipsum.
\stoptext
```

Reformat the paragraph above, by selecting it in visual-line mode and typing `gq`. Do so in the latest vim. I used 8.1.553, 07dc18ffa4e7ed202f219fe2fd3d6f58246f71f9 from Fri Nov 30 2018. This is what you get, and it isn't correct:

```LaTeX
\starttext
    Lorem Ipsum is simply dummy text of the printing and typesetting industry.
Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
when an unknown printer took a galley of type and scrambled it to make a type
specimen book. It has survived not only five centuries, but also the leap into
electronic typesetting, remaining essentially unchanged. It was popularised in
the 1960s with the release of Letraset sheets containing Lorem Ipsum passages,
and more recently with desktop publishing software like Aldus PageMaker
including versions of Lorem Ipsum.
\stoptext
```

This works fine in neovim, and neovim and vim share the exact same ConTeXt plugin files:

* `autoload/context.vim`
* `autoload/contextcomplete.vim`
* `compiler/context.vim`
* `ftplugin/context.vim`
* `indent/context.vim`
* `syntax/context.vim`

Also shared between neovim and vim:

* `formatoptions=tjcroql2, Last set from <INSTALLDIR>/share/vim/vim81/ftplugin/context.vim line 22` (technically the exact path differs)
* `formatexpr=`
* `formatlistpat=^\s*\d\+[\]:.)}\t ]\s*`
* `formatprg=`

As far as I know, if `formatexpr` and `formatprg` are unset then the responsibility lies solely with vim and `formatoptions`, and not with any plugin files.

**Comment by orbisvicis** [comment] 2018-12-01 01:41
Despite this vim still formats comments correctly:

```LaTeX
\starttext
    % Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's
    % standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it
    % to make a type specimen book. It has survived not only five centuries, but also the leap into electronic
    % typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset
    % sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker
    % including versions of Lorem Ipsum.
\stoptext
```

**Comment by lifepillar** [comment] 2018-12-01 20:54
Is`autoindent` set?

I have tried with Vim 8.1.0556, 8.1.0500 and MacVim 8.1.0280, and I cannot reproduce your issue. The value of the settings you show is correct.

**Comment by lifepillar** [comment] 2018-12-01 21:01
Btw, the ConTeXt plugin defines a `tp` text object (for “TeX Paragraph”), so you may reformat paragraphs in Normal mode with `gwtp`.

**Comment by orbisvicis** [comment] 2018-12-02 07:32
Yes, `autoindent` was not set! To be fair, its effect on `gq` is only mentioned in the help for `autoindent`, so the documentation could use enhancement. Technically the format options `2` and `n` in the help for `fo-table` mention `autoindent` but not as a top-level requirement. With, I guess, so many indentation plugins I'm just used to format indentation working out-of-the-box and didn't think to check `autoindent`.

Anyway `autoindent` is by default enabled in neovim, that's why I wasn't experience this issue there.

**Comment by chrisbra** [comment] 2018-12-07 09:50
I am not sure I follow correctly. Is there anything to do here for us or can this issue be closed?

**Comment by lifepillar** [comment] 2018-12-07 21:44
IMO, this can be closed. It is true that the help for `gq` does not mention `autoindent` directly, but it links to `fo-table`, which describes which options are affected by `autoindent`.

As to whether the ConTeXt plugin should set `autoindent` in ConTeXt buffers, this can be discussed in the plugin-specific repository at https://github.com/lifepillar/vim-context-metapost.

**Comment by k-takata** [comment] 2018-12-08 01:15
Closing.

**Closed as completed by k-takata** 2018-12-08 01:15 UTC
Labels: question
