### ISSUE TITLE
Deadlock in indent/html.vim or indent/javascript.vim

### ISSUE THREAD

**Issue by Rob--W** [vim/vim#2404] opened 2017-12-03 15:33 UTC
Steps to reproduce:

```
vim -u NONE  # reproduces with and without -N

:source /usr/share/vim/vim80/indent.vim
:source /usr/share/vim/vim80/indent/html.vim
(the last will also load /usr/share/vim/vim80/indent/javascript.vim as seen via :scrip)

:tabnew
:set ft=html

i (insert mode) and type
<script>
a={b:{<ENTER>
```

Upon pressing <kbd>Enter</kbd> at the specified location, vim uses a full CPU core and is in a deadlock. When I kill `vim` and use the Recover option, I see that the line break by Enter is present, so this bug is happening after the Enter is registered in the swap file, but before it is rendered on the screen.

The above is the minimum to reproduce the bug. The same effect can be achieved without explicitly specifying the .vim files by using the following steps instead of `:source` (compared to above, the following will load a few more non-relevant .vim files):

```
:filetype plugin indent on
:set ft=html
:tabnew whatever.html
```

Version information:

```
$ vim --version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Nov  5 2017 23:25:13)
Included patches: 1-1272
Compiled by Arch Linux
Huge version with GTK3 GUI.  Features included (+) or not (-):
+acl             +file_in_path    +mouse_sgr       +tag_old_static
+arabic          +find_in_path    -mouse_sysmouse  -tag_any_white
+autocmd         +float           +mouse_urxvt     +tcl/dyn
+balloon_eval    +folding         +mouse_xterm     +termguicolors
+browse          -footer          +multi_byte      +terminal
++builtin_terms  +fork()          +multi_lang      +terminfo
+byte_offset     +gettext         -mzscheme        +termresponse
+channel         -hangul_input    +netbeans_intg   +textobjects
+cindent         +iconv           +num64           +timers
+clientserver    +insert_expand   +packages        +title
+clipboard       +job             +path_extra      +toolbar
+cmdline_compl   +jumplist        +perl/dyn        +user_commands
+cmdline_hist    +keymap          +persistent_undo +vertsplit
+cmdline_info    +lambda          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python/dyn      +viminfo
+cscope          +lispindent      +python3/dyn     +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con_gui  +lua/dyn         +rightleft       +windows
+diff            +menu            +ruby/dyn        +writebackup
+digraphs        +mksession       +scrollbind      +X11
+dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     +xim
+emacs_tags      +mouseshape      +startuptime     -xpm
+eval            +mouse_dec       +statusline      +xsmp_interact
+ex_extra        +mouse_gpm       -sun_workshop    +xterm_clipboard
+extra_search    -mouse_jsbterm   +syntax          -xterm_save
+farsi           +mouse_netterm   +tag_binary      
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "/etc/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -D_FORTIFY_SOURCE=2  -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -L. -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.26/core_perl/CORE  -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -L/usr/local/lib -Wl,--as-needed -o vim   -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lSM -lICE -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lelf -lnsl    -lacl -lattr -lgpm -ldl   -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.26/core_perl/CORE -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/perl5/5.26/core_perl/CORE -lperl -lpthread -lnsl -ldl -lm -lcrypt -lutil -lc   -L/usr/lib -ltclstub8.6 -ldl -lz -lpthread -lieee -lm     
```

**Comment by brammool** [comment] 2017-12-03 16:49
Rob Wu wrote:

> Steps to reproduce:
> 
> ```
> vim -u NONE  # reproduces with and without -N
> 
> :source /usr/share/vim/vim80/indent.vim
> :source /usr/share/vim/vim80/indent/html.vim
> (the last will also load /usr/share/vim/vim80/indent/javascript.vim as seen via :scrip)
> 
> :tabnew
> :set ft=html
> 
> i (insert mode) and type
> <script>
> a={b:{<ENTER>
> ```
> 
> Upon pressing <kbd>Enter</kbd> at the specified location, vim uses a full CPU core and is in a deadlock. When I kill `vim` and use the Recover option, I see that the line break by Enter is present, so this bug is happening after the Enter is registered in the swap file, but before it is rendered on the screen.
> 
> The above is the minimum to reproduce the bug. The same effect can be achieved without explicitly specifying the .vim files by using the following steps instead of `:source` (compared to above, the following will load a few more non-relevant .vim files):
> 
> ```
> :filetype plugin indent on
> :set ft=html
> :tabnew whatever.html
> ```

I can reproduce it.  Looks like it's stuck in the Javascript indent
script.  CC'ing the maintainer.


-- 
hundred-and-one symptoms of being an internet addict:
74. Your most erotic dreams are about cybersex

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by Rob--W** [comment] 2017-12-03 22:44
I encountered other ways to trigger this bug, including using `==` and inserting text.

<kbd>Ctrl</kbd>+<kbd>C</kbd> breaks the deadlock, as a work-around.

**Comment by chrisbra** [comment] 2017-12-04 07:36
CC @bounceme (indent script maintainer for javascript).

**Comment by bounceme** [comment] 2017-12-04 16:13
Think i fixed this, at the dev repo:  https://github.com/pangloss/vim-javascript

**Comment by bounceme** [comment] 2017-12-04 16:18
If so, please update the runtime indent file with https://raw.githubusercontent.com/pangloss/vim-javascript/master/indent/javascript.vim

**Comment by bounceme** [comment] 2017-12-06 02:16
can't reproduce using ^^

**Comment by chrisbra** [comment] 2018-01-02 14:29
indent/javascript.vim has been last updated in https://github.com/vim/vim/commit/f0b03c4e98f8a7184d8b4a5d702cbcd602426923
I suppose it is fixed now.

**Closed as completed by chrisbra** 2018-01-02 14:29 UTC
Labels: runtime
