### ISSUE TITLE
the hide terminal is not closed actually

### ISSUE THREAD

**Issue by giceli** [vim/vim#12726] opened 2023-08-04 12:34 UTC
### Steps to reproduce

```vim
:let termbuf = term_start("NONE", {"term_name":"test", "hidden":1, "out_cb": function("g:Xxxxx")})
:let tty = job_info(term_getjob(g:commbuf))['tty_out']
:ls!
:execute("bw " .. termbuf)
:ls!
```

for line 1: we start a term, and hide them
for line2 : we can see the terminal is in directory "/dev/pts/???"
for line 3: we can see the termbuf in buffers
for line4: we close this buffer
for line5: we can see that the termbuf is closed

buf actually, we can see that the tty of this terminal is still exists. this terminal is not stopped actually. "out_cb" is import for this problem, if there is no "out_cb", the terminal can closed correctly.

### Expected behaviour

i hope that ,when the buffer is wiped, ther terminal of this buffer is closed, and the tty is alos disappear.
but it is not, for Plug  "termdebug", when i start for many times, i will get many ttys in  directory "/dev/pts/"

### Version of Vim

VIM - Vi IMproved 9.0

### Environment

ubuntu 22.04.2
gnome-terminal: # GNOME Terminal 3.44.0 using VTE 0.68.0 +BIDI +GNUTLS +ICU +SYSTEMD
$TERM : xterm-256color

**Comment by matveyt** [comment] 2023-08-06 16:06
This is not a bug. This is the default behaviour different from one you expect.

If you want terminal process to be killed after Vim's window closed you have to pass an argument to do so. See help for `terminal` command or `term_start()` function.

**Comment by chrisbra** [comment] 2023-08-08 18:20
closing then.

**Closed as not planned by chrisbra** 2023-08-08 18:20 UTC
Labels: bug
