### ISSUE TITLE
vim clipboard handling is incorrect

### ISSUE THREAD

**Issue by kallisti5** [vim/vim#11701] opened 2022-12-13 22:27 UTC
### Steps to reproduce

This is a continuation of the bug reported in #2841 

* Middle click in vim without holding shift pastes the VIM clipboard buffer
* Middle click while hosting shift in VIM pastes the "PRIMARY" from the OS or the "CLIPBAORD" buffer from the OS. (it seems to be whichever was populated last?)

Vim's mouse mode incorrectly manages clipboards.  The behaviour of needing to hold shift to paste the OS clipboard is in direct conflict with the freedesktop clipboard management specification:

https://specifications.freedesktop.org/clipboards-spec/clipboards-0.1.txt

> Application authors should follow the following guidelines to get correct behavior:
>
> - selecting but with no explicit copy should only set PRIMARY,
>   never CLIPBOARD
>
> - middle mouse button should paste PRIMARY, never CLIPBOARD

Reversing the <SHIFT> modifier would move vim to be more compatible with the freedesktop clipboard specifications

### Expected behaviour

* Middle click in vim without holding shift *SHOULD* paste the OS clipboard
* Middle clip in vim while holding shift *SHOULD* paste the vim clipboard.

Any behaviour beyond the above would be breaking the specification + best practices accepted by pretty much every X11 and Wayland application and desktop.

### Version of Vim

8.0, 9.0

### Environment

Any linux running X11 or Wayland

**Comment by chrisbra** [comment] 2022-12-14 08:08
I cannot seem to reproduce this behaviour. Can you please clarify, whether you are using terminal vim (whith or without clipboard feature?) or gvim? Also, are you by any chance using a clipboard manager?

For me, in a terminal Vim, whether I hold Shift or not, middle click will always paste the primary selection

Also, can you please clarify, what you mean with the Vim clipboard? We have several registers in Vim, including the `*` and `+` primary/clipboard registers. So it is not clear what you mean here. And finally, there are some options that influence that behaviour like 'clipboard' and the 'guioptions'.

So please provide exact reproduction steps (start with vim --clean). And you can check the register content using the `:reg` command.

**Comment by kallisti5** [comment] 2022-12-14 13:43
```vim --clean test-test```

1) highlight text in the os in another non-terminal window
2) middle click in vim.   "Nothing in register ''"
3) shift + middle click in vim.  os PRIMARY clipboard buffer is pasted into vim.
4) ```yy``` a line in vim
5) middle click in vim.  vim's clipboard buffer is pasted.

Essentially, vim only gets the contents of the os clipboard buffer when shift is held and you middle click.  This is anti-pattern to the freedesktop.org clipboard spec listed above.

**Comment by brammool** [comment] 2022-12-14 14:19
> ```vim --clean test-test```
> 
> 1) highlight text in the os in another non-terminal window

An essential part of reproduction steps is that they can be reproduced.
You don't mention here what you are actually doing.  Also, your text "in
the os" doesn't make sense.  Thus I have no clue what to do here.

> 2) middle click in vim.   "Nothing in register ''"
> 3) shift + middle click in vim.  os PRIMARY clipboard buffer is pasted
> into vim.

How do you know?  Quite often the same text is in multiple
selection/clipboard buffers.  Oh, and PRIMARY is a selection, not a
clipboard buffer.  There also is the CLIPBOARD selection, which mostly
works like a clipboard.

> 4) ```yy``` a line in vim
> 5) middle click in vim.  vim's clipboard buffer is pasted.

As I mentioned before, Vim does not have a "clipboard buffer".

> Essentially, vim only gets the contents of the os clipboard buffer
> when shift is held and you middle click.  This is anti-pattern to the
> freedesktop.org clipboard spec listed above.

When I select text in Chrome, without pressing CTRL-C (for copy), I can
paste it in Vim with a middle click just fine.  I suspect your setup
somehow prevents this from working. (in case it matters, I'm using
Ubuntu 22.04, it has worked the same way for years)

Since this issue now has mainly false information and claims, and
nothing useful, I'll probably close it soon.


-- 
   An extraordinary TALL KNIGHT in all black (possibly John with Mike on his
   shoulders) walks out from the dark trees.  He is extremely fierce and
   gruesome countenance.  He walks towards KING ARTHUR and PATSY, who are
   wazzing like mad.  (Salopian slang, meaning very scared.  almost to the
   point of wetting oneself, e.g. before an important football match or
   prior to a postering.  Salopian slang meaning a beating by the school
   praeposters.  Sorry about the Salopian slant to this stage direction - Ed.)
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by kallisti5** [comment] 2022-12-14 14:58
>> ```vim --clean test-test```
>> 1) highlight text in the os in another non-terminal window

> An essential part of reproduction steps is that they can be reproduced.
> You don't mention here what you are actually doing.  Also, your text "in
> the os" doesn't make sense.  Thus I have no clue what to do here.

I'm unsure on how this is unclear.
"Highlight any text within your currently running wayland session."

>> 2) middle click in vim.   "Nothing in register ''"
>> 3) shift + middle click in vim.  os PRIMARY clipboard buffer is pasted into vim.

> How do you know?  Quite often the same text is in multiple selection/clipboard buffers.  Oh, and PRIMARY is a selection, not a clipboard buffer.  There also is the CLIPBOARD selection, which mostly works like a clipboard.

* PRIMARY is a buffer... which stores the selected text within the wayland (or X11) desktop
  * It can be "placed" into other locations via the middle mouse button.
* CLIPBOARD is another buffer... which stores text you copy within the wayland (or X11) desktop
  * It can be "placed" into other locations by selecting paste

These are two different buffers within X11 and Wayland. They each can hold their own data.
Try it yourself:

* Open a text editor.
* Place some text into your CLIPBOARD buffer by selecting it and choosing copy.
* Place some text into your PRIMARY buffer by highlighting it.
* In your text editor. press the middle mouse button to "place" the PRIMARY buffer
* In your text editor choose paste to paste your CLIPBOARD buffer.

>> 4) ```yy``` a line in vim
>> 5) middle click in vim.  vim's clipboard buffer is pasted.

> As I mentioned before, Vim does not have a "clipboard buffer".


>> Essentially, vim only gets the contents of the os clipboard buffer
>> when shift is held and you middle click.  This is anti-pattern to the
>> freedesktop.org clipboard spec listed above.

> When I select text in Chrome, without pressing CTRL-C (for copy), I can
> paste it in Vim with a middle click just fine.
> I suspect your setup somehow prevents this from working.
> (in case it matters, I'm using Ubuntu 22.04, it has worked the same way for years)

> Since this issue now has mainly false information and claims, and
> nothing useful, I'll probably close it soon.

Ok.  Lets pause here.  Several people are raising the issue I raised where
vim isn't getting the wayland clipboard. See the issue I referenced opening this ticket.

"it works for me on Ubuntu" doesn't mean it will work everywhere. It also isn't enough
to say it's "false information and claims". 

Multiple people have mentioned holding shift "allows vim to access the wayland clipboard/primary buffers"
So what does "holding shift" do to make it work for these users?

**Comment by chrisbra** [comment] 2022-12-14 15:25
do you have perhaps not clipboard enabled in your vim build? please show the output of `:version`

**Comment by brammool** [comment] 2022-12-14 15:28
> >> ```vim --clean test-test```
> >> 1) highlight text in the os in another non-terminal window
> 
> > An essential part of reproduction steps is that they can be reproduced.
> > You don't mention here what you are actually doing.  Also, your text "in
> > the os" doesn't make sense.  Thus I have no clue what to do here.
> 
> I'm unsure on how this is unclear.
> "Highlight any text within your currently running wayland session."

Wayland?  You did not mention this before.  Wayland isn't really
supported by Vim yet.  There is a patch somewhere that is being worked
on.  There are also many known problems with Wayland, especially about
how it differs from the X server.  Whether that is intentional or not
remains to be seen.  Generally Wayland isn't ready for the big audience
yet.  Some early adaptors can play around with it, but expect to run
into some trouble.

You appaarently have no clue how to explain what you are doing.  I'm
going to close this issue.  Some info:
- "highlight any text" - How?  With the mouse, keyboard?  Do you use a
  marker?
- What text?  In a menu?  Some GUI application?  Gimp?

It is so easy to just say "use Chrome and select some text on a web page
with the mouse".  Or even more specific: "navigate to www.vim.org, move
the mouse pointer to the first header "Vim - the ubiquitous text editor"
and select it by keeping the left mouse button pressed while moving to
the end of the text".

> >> 2) middle click in vim.   "Nothing in register ''"
> >> 3) shift + middle click in vim.  os PRIMARY clipboard buffer is pasted into vim.
> 
> > How do you know?  Quite often the same text is in multiple selection/clipboard buffers.  Oh, and PRIMARY is a selection, not a clipboard buffer.  There also is the CLIPBOARD selection, which mostly works like a clipboard.
> 
> * PRIMARY is a buffer... which stores the selected text within the wayland (or X11) desktop

Nope, PRIMARY does not store anything with the X server.  If someone
wants to get the PRIMARY selection it has to ask for it, using the X
protocol, and the application currently owning the PRIMARY selection
will provide the text.  There can be some back and forth about what
format to use for the text, what encoding, etc.  Vim provides its own
format, thus copy/past between two Vim sessions works differently than
between other applications.

>   * It can be "placed" into other locations via the middle mouse button.
> * CLIPBOARD is another buffer... which stores text you copy within the wayland (or X11) desktop

CLIPBOARD works exactly the same as PRIMARY, it is commonly used when
specifically asked for (usually with the CTRL-C and CTRL-V keys).
And like PRIMARY the server doesn't store the text.

>   * It can be "placed" into other locations by selecting paste
> 
> These are two different buffers within X11 and Wayland. They each can hold their own data.
> Try it yourself:
> 
> * Open a text editor.
> * Place some text into your CLIPBOARD buffer by selecting it and choosing copy.
> * Place some text into your PRIMARY buffer by highlighting it.
> * In your text editor. press the middle mouse button to "place" the PRIMARY buffer
> * In your text editor choose paste to paste your CLIPBOARD buffer.
> 
> >> 4) ```yy``` a line in vim
> >> 5) middle click in vim.  vim's clipboard buffer is pasted.

How many times to I have to say that Vim does not have a "clipboard
buffer"?

> > As I mentioned before, Vim does not have a "clipboard buffer".
> 
> 
> >> Essentially, vim only gets the contents of the os clipboard buffer
> >> when shift is held and you middle click.  This is anti-pattern to the
> >> freedesktop.org clipboard spec listed above.
> 
> > When I select text in Chrome, without pressing CTRL-C (for copy), I can
> > paste it in Vim with a middle click just fine.
> > I suspect your setup somehow prevents this from working.
> > (in case it matters, I'm using Ubuntu 22.04, it has worked the same way for years)
> 
> > Since this issue now has mainly false information and claims, and
> > nothing useful, I'll probably close it soon.
> 
> Ok.  Lets pause here.  Several people are raising the issue I raised
> where vim isn't getting the wayland clipboard. See the issue I
> referenced opening this ticket.

Now you are just plain lying.  That issue is about the 'mouse' option
and has nothing to do with Wayland support.

> "it works for me on Ubuntu" doesn't mean it will work everywhere. It also isn't enough
> to say it's "false information and claims". 

> Multiple people have mentioned holding shift "allows vim to access the wayland clipboard/primary buffers"
> So what does "holding shift" do to make it work for these users?

Again you are lying.  I'm closing this.

-- 
ARTHUR:      Who are you?
TALL KNIGHT: We are the Knights Who Say "Ni"!
BEDEVERE:    No!  Not the Knights Who Say "Ni"!
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by kallisti5** [comment] 2022-12-14 15:29
> do you have perhaps not clipboard enabled in your vim build? please show the output of `:version`

```
:version
VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Nov 19 2022 14:37:14)
Included patches: 1-910
Compiled by Arch Linux
Huge version without GUI.  Features included (+) or not (-):
+acl               +cryptv            +fork()            +modify_fname      +persistent_undo   -sun_workshop      +viminfo
+arabic            +cscope            +gettext           +mouse             +popupwin          +syntax            +virtualedit
+autocmd           +cursorbind        -hangul_input      -mouseshape        +postscript        +tag_binary        +visual
+autochdir         +cursorshape       +iconv             +mouse_dec         +printer           -tag_old_static    +visualextra
-autoservername    +dialog_con        +insert_expand     +mouse_gpm         +profile           -tag_any_white     +vreplace
-balloon_eval      +diff              +ipv6              -mouse_jsbterm     -python            +tcl/dyn           +wildignore
+balloon_eval_term +digraphs          +job               +mouse_netterm     +python3/dyn       +termguicolors     +wildmenu
-browse            -dnd               +jumplist          +mouse_sgr         +quickfix          +terminal          +windows
++builtin_terms    -ebcdic            +keymap            -mouse_sysmouse    +reltime           +terminfo          +writebackup
+byte_offset       +emacs_tags        +lambda            +mouse_urxvt       +rightleft         +termresponse      -X11
+channel           +eval              +langmap           +mouse_xterm       +ruby/dyn          +textobjects       -xfontset
+cindent           +ex_extra          +libcall           +multi_byte        +scrollbind        +textprop          -xim
-clientserver      +extra_search      +linebreak         +multi_lang        +signs             +timers            -xpm
-clipboard         -farsi             +lispindent        -mzscheme          +smartindent       +title             -xsmp
+cmdline_compl     +file_in_path      +listcmds          +netbeans_intg     -sodium            -toolbar           -xterm_clipboard
+cmdline_hist      +find_in_path      +localmap          +num64             -sound             +user_commands     -xterm_save
+cmdline_info      +float             +lua/dyn           +packages          +spell             +vartabs
+comments          +folding           +menu              +path_extra        +startuptime       +vertsplit
+conceal           -footer            +mksession         +perl/dyn          +statusline        +vim9script
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wformat -Werror=format-security -
fstack-clash-protection -fcf-protection -g -ffile-prefix-map=/build/vim/src=/usr/src/debug/vim -flto=auto -D_REENTRANT -U_FORTIFY_SOURCE -D_FOR
TIFY_SOURCE=1
Linking: gcc -L. -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fstack-protector-strong -rdynamic -Wl,-export-dynamic -Wl,--no-as-needed -W
l,-E -Wl,-rpath,/usr/lib/perl5/5.36/core_perl/CORE -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -flto=auto -L/usr/local/lib -o vim -lm -lt
info -lelf -lacl -lattr -lgpm -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.36/core_perl/CORE -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -flto -fst
ack-protector-strong -L/usr/local/lib -L/usr/lib/perl5/5.36/core_perl/CORE -lperl -lpthread -ldl -lm -lcrypt -lutil -lc -L/usr/lib -ltclstub8.6
 -ldl -lz -lpthread -lm
```

**Closed as not planned** 2022-12-14 15:29 UTC
Labels: bug

**Comment by kallisti5** [comment] 2022-12-14 15:31
> Wayland?  You did not mention this before.  Wayland isn't really
supported by Vim yet.

I mentioned it while opening the issue. It's listed in the environment section.  All Linux desktops (Ubuntu included) are wayland now.

>>  "it works for me on Ubuntu" doesn't mean it will work everywhere. It also isn't enough
>>  to say it's "false information and claims".
>>  Multiple people have mentioned holding shift "allows vim to access the wayland clipboard/primary buffers"
>>  So what does "holding shift" do to make it work for these users?

> Again you are lying.  I'm closing this.


Could someone re-open this please?   This isn't really a reasonable way to work bugs.  I've been friendly and providing as much information as possible to assist in determining what is going on.

**Comment by kallisti5** [comment] 2022-12-14 15:37
:disappointed:  This has been an eye-opening experience about vim after all these decades using it.  Thanks for all the fish.

**Comment by brammool** [comment] 2022-12-14 15:46
> > Wayland?  You did not mention this before.  Wayland isn't really
> > supported by Vim yet.
> 
> I mentioned it while opening the issue. It's listed in the environment
> section.  All Linux desktops (Ubuntu included) are wayland now.

Again wrong information.  Many people prefer using X11 or have to
because of the hardware (some Nvidia drivers don't support Wayland).  On
my system:

$ echo $XDG_SESSION_TYPE
x11

> >>  "it works for me on Ubuntu" doesn't mean it will work everywhere. It also isn't enough
> >>  to say it's "false information and claims".
> >>  Multiple people have mentioned holding shift "allows vim to access the wayland clipboard/primary buffers"
> >>  So what does "holding shift" do to make it work for these users?
> 
> > Again you are lying.  I'm closing this.
> 
> Could someone re-open this please?   This isn't really a reasonable
> way to work bugs.  I've been friendly and providing as much
> information as possible to assist in determining what is going on.

You have not been giving reproducible examples, providing wrong
and confusing information, etc.  And when you finally provided :version
output it became clear that your Vim has "-clipboard", which means
clipboard support is not built in.  Thus everything else is irrelevant.
This issue is just a waste of time.

-- 
TALL KNIGHT: We shall say Ni! again to you if you do not appease us.
ARTHUR:      All right!  What do you want?
TALL KNIGHT: We want ... a shrubbery!
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by kallisti5** [comment] 2022-12-14 15:55
So. The neovim people figured out what was going on (by you know, actually troubleshooting, using their brains, and not flying off the handle in a manic panic in every bug report)

without xclip/xsel installed, you have to hold shift to make the clipboard work when pasting into vim.   vim silently fails with a broken mouse behavior when the cli  xclip/xsel tools aren't installed.

**Comment by zeertzjq** [comment] 2022-12-14 15:57
Vim doesn't use xsel/xclip. Whether Vim supports X11/Wayland clipboard depends on when Vim is built with +clipboard feature.

**Comment by kallisti5** [comment] 2022-12-14 16:00
ah ok.   @zeertzjq I found references to it here: https://github.com/vim/vim/issues/4596#issue-461126529   , but that seems like just someone's vimrc mentioned it (maybe they ported it from neovim)

Indeed the vim codebase doesn't show xclip.

**Comment by chrisbra** [comment] 2022-12-14 17:08
you are not using a vim without clipboard. Check for `+clipboard` in your version output.

**Comment by kallisti5** [comment] 2022-12-14 17:14
@chrisbra I think the tldr of this one is:

* vim is unable to access wayland's clipboard / primary buffer today (unsupported per @brammool above) and that feature is unsupported
* holding shift in this case when pasting into vim with the middle mouse button seems to work around the bug (nobody has highlighted why or what shift does as a modifier when pasting... but whatever)
* neovim moved to using xclip/xsel which works around the issue entirely.  neovim without xclip/xsel installed is just as broken as vim on wayland desktops.

**Comment by chrisbra** [comment] 2022-12-14 17:21
@kallisti5 I can understand your frustration. However the thing is:

1) Vim without `+clipboard` cannot handle (interact with)  X11 requests (Because the X11 Spec is basically some interprocess communication, that needs to link in additional X11 libraries in order to interact with those). That is mainly there, so you can install vim on a server without having to pull in all X11-Dependencies (which you do not want on a server). What that means is, whatever your mouse does comes basically from your terminal. You are only interacting with your mouse with the terminal. Vim does not see anything from your mouse.

2) I am not sure what your mouse + shift handling does in that case, since Vim does not connect to X11 in your case

3) Personally, I regret the decision of Neovim to rip of all the X11 libraries, because now you have to configure and install an additional 3rd-party library that needs to interact with your X11/Wayland desktop environment. That can lead to strange errors (think of encoding problems, visual block mode, etc). And again, without xclip/xsel it cannot handle any X11 requests as you noticed.

**Comment by chrisbra** [comment] 2022-12-14 17:23
>  right that in the above -clipboard is listed. That's the default archlinux vim package.

Does Archlinux not have a gui-package that you can install? Even so you may not need the gvim included there, it should also include a console vim with `+clipboard`

**Comment by kallisti5** [comment] 2022-12-14 17:33
ha, @chrisbra that all gets back to the meat of it.

The only reason i'm having this conversation is the new (well.. now old circa 2018) default ```mouse=a``` breaks pasting into vim terminals running under wayland.  I don't actually want or use mouse mode... and generally spam ```set mouse-=a``` across the vimrc files on the 100's of linux machines I manage.

Personally, Historically:

* since the early 2000's, I don't use gvim since I don't want mouse mode
* 2018 vim introduced ```mouse=a``` as default.  Distro's started getting new vim packages with it circa 2019-2020.
* 2019 I began a constant ```:set mouse=``` cycle every time I pulled up vim (until I add ```set mouse-=a``` to vimrc's) to "make pasting from wayland desktops to vim to work"

Now i'm just trying to figure out why mouse mode is so frustrating to use lol.  This ticket highlights the reasons why myself and several other long-time vim users have complained of similar issues (https://github.com/vim/vim/issues/2841)

The why of archlinux defaulting to ```-clipboard``` is a good question... however as I understand it, wayland support in general is broken (and unsupported) per @brammool

**Comment by chrisbra** [comment] 2022-12-14 17:44
I am not sure why you keep seeing the `mouse=a` issue. That should go away if you are not using `defaults.vim`. I know it's been a pain for some people, especially if they do not use a vimrc (especially when jumping between various systems), but I have personally never experienced it (even so I have to jump on customer environments and use a plain vim over there) quite a lot. I guess the default server vim does not have X11 support enabled, so in reality this was never a problem. Also if you really do not like `defaults.vim` you can either use an alias `alias vim=vim -c 'let skip_defaults.vim=1'` or use TERM=linux vim or just point $VIMRUNTIME to a directory without `defaults.vim`  or something similar. There should be ways around it I believe.

Yes, wayland support is not there yet. Support for it is here: https://github.com/vim/vim/pull/9639 but apparently needs a bit more work (documentation etc).

**Comment by habamax** [comment] 2022-12-15 06:33
>     * holding shift in this case when pasting into vim with the middle mouse button seems to work around the bug (nobody has highlighted why or what shift does as a modifier when pasting... but whatever)

Depends on a terminal emulator, some terminals use alt+click instead of shift+click. Terminal emulator intercepts mouse events and vim has nothing to do with it. This means if you are in normal mode and try to paste text `start` using shift+click, only `tart` would be pasted and the char your cursor is on would be deleted (`s` is a normal mode command to delete current character and start insert mode).
Think of it as the pasted text was manually typed into vim.

**Comment by Shane-XB-Qian** [comment] 2022-12-15 08:34
every some years later, someone would jump into to argue the clipboard :rofl:

check here: https://github.com/vim/vim/issues/4965#issuecomment-557538098 
and vim and neovim and others general editors impl different way to play clipboard, 

IMO: perhaps you should just get used to the official vim way since you chose vim.
// to me, i more preferred there is no mouse feature in vim totally which interrupt my editing always. :-)

**Comment by kallisti5** [comment] 2022-12-15 14:18
> Think of it as the pasted text was manually typed into vim.

The irony of all this is this is exactly how it used to work before the unholy mouse mode was made default.  It worked well without all these issues.

Eh. It's fine.  I'm replacing vim with neovim on all my machines, putting it into default linux images, and aliasing vim to nvim everywhere I can. (if vim packages can alias vi to vim, I can alias vim to nvim :laughing:)

Thanks y'all

**Comment by Shane-XB-Qian** [comment] 2022-12-16 02:14
@kallisti5 you may mis-understood something, unless it was a incompatible case (it do happened before e.g the `set clipboard-=autoselect` perhaps required to keep the used way) or mistake bug (e.g i mentioned #4965), then it just a used way in different impl and perhaps was the best practice one in its background.
// mouse is not functional well in TUI it is a knew issue, but sometime it depends on terminal.
// e.g some terminal can paste by shift + insert, some were ctrl+shift+v, i do not think it is vim control it.
// neovim enhanced some area of official vim to be like a modern edittor, but official vim more wide-supported than nvim.
// for example i wish bram can invest more time on vim with gnu-screen (mostly is user at server side), specially UTF issue.
// though perhaps was gnu-screen itself bug.. ohh, BTW: you can use gnu-screen to copy / paste as well, then you will forget `*mouse*` !!
