### ISSUE TITLE
All <C-x> map not work in newest gvim(v8.2.5157)

### ISSUE THREAD

**Issue by zoumi** [vim/vim#10618] opened 2022-06-25 09:36 UTC
### Steps to reproduce

1. modify a file
2. press \<C-s>

### Expected behaviour

The key map 
```
noremap <C-s> :w!<CR>
```
should be triggered, but it didn't.

### Version of Vim

8.2.5157

### Environment

Windows 10 64bit
gvim_8.2.5157_x64

minimal vimrc:
```
"Start (neo)vim with command: `vim -u min.vim`

set pyx=3
set langmenu=none
let $LANG = 'en'
syntax on
set nocompatible              " be iMproved, required
filetype off                  " required

" CTRL-X and SHIFT-Del are Cut
vnoremap <C-X> "+x
" CTRL-C and CTRL-Insert are Copy
vnoremap <C-C> "+y
" CTRL-V and SHIFT-Insert are Paste
noremap <C-V> "+gp
" CTRL-S are Save
noremap <C-s> :w!<CR>
vnoremap<C-r> :<C-U><C-R>=printf("%%s/%s/", expand("<cword>"))<CR>

```

**Comment by brammool** [comment] 2022-06-25 11:21
Duplicate of #10615

**Closed as not planned** 2022-06-25 11:22 UTC
Labels: bug
