### ISSUE TITLE
Have colorcolumn at the true position when linebreak is active

### ISSUE THREAD

**Issue by simonmandlik** [vim/vim#12743] opened 2023-08-07 16:25 UTC
### Steps to reproduce

When I start plain `vim` and run `:set ruler linebreak cc=50`, I get

<img width="718" alt="image" src="https://github.com/vim/vim/assets/16707112/2df1b58c-f2c1-494b-8b13-76b95d39a40c">

This is as expected, colorcolumn is occupying the col number 50.

When I resize the terminal so that the `linebreak` option because active and `cc` overflows to the next line, I get

<img width="310" alt="image" src="https://github.com/vim/vim/assets/16707112/46104a7f-85dd-4866-9fbc-61ea20717ecd">

The colorcolumn is now two characters earlier, and the "s" where it was originally has coordinate `1,50-52`. "r" has coordinate `1,48-50` and that's I guess why it was selected as colorcolumn.

I didn't find anything in the docs about this behavior. Would it be possible to instead use the smallest number of the column coordinate interval such that colorcolumn is consistent w.r.t resizing? Is this a bug or a feature?

Similar problem arrises with e.g. `:set breakindent cc=50` as well as `:set showbreak=> cc=50`

### Expected behaviour

I would expect the colorcolumn to be at the original location

### Version of Vim

9.0.1424

### Environment

MacOS 13.4.1
iterm2
xterm-256color
zsh

**Comment by bew** [comment] 2023-08-07 17:43
This seems to be the same underlying issue as #12238, where column counting uses the virtcol, not the logical column in the line

**Comment by Konfekt** [comment] 2023-08-08 16:46
Since it did not use to be this way, it must be due to a relatively recent commit

**Comment by chrisbra** [comment] 2023-08-08 18:21
can you please bisect to find it if this indeed regressed?

**Comment by sukima** [comment] 2023-08-11 23:37
I was unable to reproduce this on the latest master commit f1cc4d55b9ed3335985512fb9fedf31cc4bb65a0

https://github.com/vim/vim/assets/70075/61604f46-f9fd-4e40-a74c-c88b08ef6028

**Comment by chrisbra** [comment] 2023-08-12 07:58
closing then.

**Closed as not planned by chrisbra** 2023-08-12 07:58 UTC
Labels: bug

**Comment by simonmandlik** [comment] 2023-08-24 07:17
@sukima could you try resizing the window such that its smaller than 50 and cc overflows to the next line? This is when the bug manifests for me

**Comment by sukima** [comment] 2023-10-07 00:40
@simonmandlik Like this?

https://github.com/vim/vim/assets/70075/a3934cb9-2297-40d5-b0df-5b6d1663821d

**Comment by simonmandlik** [comment] 2023-10-07 04:29
@sukima yes, that's what I meant. It indeed looks fixed! 👍
