### ISSUE TITLE
Cannot use class type of itself in the method

### ISSUE THREAD

**Issue by thinca** [vim/vim#12369] opened 2023-05-10 01:17 UTC
### Steps to reproduce

```vim
vim9script

class Foo
  this.num: number
  def Equals(other: Foo): bool
    return this.num == other.num
  enddef
endclass
```

The following error occurs when this file is `:source`

```
E1010: Type not recognized: Foo
```

### Expected behaviour

The class can be defined without errors.

### Version of Vim

9.0.1536

### Environment

OS: Arch Linux
terminal: mintty (ssh from Windows)
value of $TERM: screen-256color

**Comment by lifepillar** [comment] 2023-10-22 19:11
A workaround is to set the type to `any` and be satisfied with runtime checks. To avoid the generic `E715: Dictionary required` error if the type at runtime is incorrect, you may assign to a `Foo`-typed variable inside the method. Like this:

```vim
vim9script

class Foo
  this.num: number
  def Equals(other: any): bool
    const other_: Foo = other
    return this.num == other_.num
  enddef
endclass

var f1 = Foo.new(1)
var f2 = Foo.new(2)

def F()
  echo f1.Equals(f2)  # OK
  echo f1.Equals([])  # E1012: type mismatch
enddef

F()
```

You get at least an informative message when the script is run.

The issue is also for methods that *return* the object itself. For instance:

```vim
class Foo
  this.num: number
  def Clone(): any  # <== Cannot be Foo
    return Foo.new(this.num)
  enddef
endclass

var f1 = Foo.new(1)

def F()
  var f2: Foo = f1.Clone()  # Without the explicit type, raises E715
  echo f2 is f1             # OK, false
  echo f2.num == f1.num     # OK, true
enddef

F()
```

**Closed as completed** 2024-03-09 14:46 UTC
Labels: bug, vim9class
