### ISSUE TITLE
vim 7.4.52 : output of python3 "input" built-in function does not display during :! execution

### ISSUE THREAD

**Issue by psychogears** [vim/vim#537] opened 2015-12-23 20:25 UTC
Hey.  Not sure if this is a vim issue or user error, but I figure I'd report it anyway because I don't know what's causing it.

Issue: When editing a file "test.py" then executing it via :!./test.py, python3's built-in function "input" does not seem to produce a prompt.  print() statements seem to work just fine.

Reproduce:
1.  From bash:

```
echo <<EOF
#!/usr/bin/env python3
if __name__ == '__main__':
 input("prompt")
EOF >test.py && chmod u+x test.py
```
1. Open test.py with vim
2.  From vim normal mode:  `:!./test.py`
3.  Observe that "prompt" does not display but the terminal is waiting for user input.
4.  Observe that after providing input, the program terminates like normal.

Not sure what's causing it, but executing the file from the shell itself produces the expected behavior, i.e. displaying "prompt" while waiting for some input and an "Enter" key press.

Thank you for your time.

**Comment by lacygoill** [comment] 2020-06-11 14:26
I can't reproduce, neither on master nor on 7.4.052.

Writing this in `test.py`:

    #!/usr/bin/env python3
    if __name__ == '__main__':
     input("prompt")

Then making the script executable, and running `:!./test.py` in Vim, makes the python script asks for the user input, as well as display the text `prompt`.

![gif](https://user-images.githubusercontent.com/8505073/84398308-145f7880-ac00-11ea-913d-ebcfd7e0e167.gif)

I checked on 2 different terminals: xterm and gnome-terminal.

Maybe something in your config triggers the issue.  Try to reproduce without config:

    vim -Nu NONE
    :!./test.py

Read this [faq entry](https://github.com/chrisbra/vim_faq/blob/de424bd8e08bcf0e6b1e0563ee49514dfed926ae/vim_faq.txt#L1153-L1228) to find a [minimal working example](https://en.wikipedia.org/wiki/Minimal_working_example).

**Comment by chrisbra** [comment] 2020-06-11 16:46
thanks closing then.

**Closed as completed by chrisbra** 2020-06-11 16:46 UTC
