### ISSUE TITLE
PHP Autocomplete source file reading + caching broken

### ISSUE THREAD

**Issue by Roy-Orbison** [vim/vim#7783] opened 2021-02-05 03:29 UTC
@complex857 I know the listed URL in the file is https://github.com/shawncplus/phpcomplete.vim but that looks abandoned, it also appears that the core version is way out of sync. In any case, the problem exists in both versions.

Attempting a simple class method completion fails with the error below, even though a thorough universal ctags file is loaded:
> -- Omni completion (^O^N^P) Pattern not found

I tried to debug the error using `:debug normal A^X^O` and found an error occurring here:
https://github.com/vim/vim/blob/ab65fc77c5389f7d3f788bbdc3d931561feab131/runtime/autoload/phpcomplete.vim#L2097

Removing the `!` from the `silent!` prefixes halted completion and produced:
> E578: Not allowed to change text here

Firstly, the class, method, and their containing file are all correctly determined. With the `!` retained, the error is skipped over, the new buffer is never switched to and filled with the class' source file, so when `let content = join(getline(cfline, endline), "\n")` is executed, it instead reads the current buffer (a completely different PHP script), ultimately filling `s:cache_classstructures` with bogus data. The completion then fails because no candidates are found in the bogus data.

I thought it might be #6017 again. This script seems to use buffers rather than windows (though I think windows were tried in https://github.com/shawncplus/phpcomplete.vim/issues/57).

**Comment by complex857** [comment] 2021-02-05 10:47
Thank you for taking the time for looking into this! 
I've managed to reproduce the issue (as you said it's quite a basic case) and your analysis is spot on.

It seems that switching windows has been forbidden since this commit https://github.com/vim/vim/commit/6adb9ea0a6ca01414f4b591f379b0f829a8273c0

Sadly the plugin itself relies extensively on this to be allowed, i'll have to think of some other solution (manipulating files somehow without having them in buffers is my first guess, but then we loose all the niceties like `searchpairpos` and syntax based comment / string ignores).

I don't see an easy fix for it right now, suggestions are welcomed!

**Comment by Roy-Orbison** [comment] 2021-02-05 15:16
Good to have the theory vindicated. It does look very active with the buffer use.

Is the reasoning for so much live reading of files to keep up with code changes ahead of updates to tags files? Or is it gleaning more into than tags files can hold?

I use [joonty/vim-taggatron](https://github.com/joonty/vim-taggatron) which updates the relevant tags files on every save. From what I can make out, this script reads only the on-disk copies then parses their contents to look for all the info that I thought was already in my tags file (variables, constants, functions, classes, methods, inheritance, namespaces), which would be double-handling the source files. Correct me if I'm wrong.

If sufficient info already is (or can be) put into tags files, then wouldn't this be an acceptable level of dependency, given some level of ctags is already required?

**Comment by complex857** [comment] 2021-02-05 21:59
I'm not 100% sure since this was there already when I started contributing to the project. 

I think it's mostly because ctag's PHP support back then (even with exuberant-ctags and some custom regexes) was very poor. You would not get any class related attributes in the generated files ("what class this method belongs to" and so on).
When the first ctag versions (universal-ctags, b4n patches for namespaces) appeared and I was adding extra features relying on these "better ctags", I've always tried to keep the code as functional as possible with the old ctags (I was thinking "who knows what you've on your system").

I did try to convert these extended ctags into some in-memory structure we can just query (reading files is super slow), but that didn't pan out, because lots of interesting information is in docblocks (back then there was no return-type type hints syntax, most projects never type-hinted their function arguments).

So I couldn't re-create the structured information I'd need. From what I can tell this is still the case (even if we'd accept that you'll need some newer ctags versions for anything to work).

What you'd need is something that's as powerful as [felixfbecker/php-language-server](https://github.com/felixfbecker/php-language-server), I remember some forks of the plugin that included similar (external process you send your buffer over and get completions), but the my idea was that I keep the plugin with minimum (preferably no) external dependency.

**Comment by lacygoill** [comment] 2021-02-06 01:03
> It seems that switching windows has been forbidden since this commit 6adb9ea

> I don't see an easy fix for it right now, suggestions are welcomed!

Have a look at [`:h win_execute()`](https://vimhelp.org/eval.txt.html#win_execute()).  It lets you execute Ex commands in arbitrary windows with few or no side-effects.  It should not raise `E565`.

**Comment by lacygoill** [comment] 2021-02-06 01:04
You could wrap the problematic code in a function, and call it with `win_execute()`:

    call win_execute(window ID, 'call Func()')

**Comment by brammool** [comment] 2021-02-06 13:10
If you want to manipulate text without opening a buffer or window, using readfile() might be a good solution.  You can't run Vim commands on it, but if you only want to search for something it should work fine.

**Comment by complex857** [comment] 2021-02-06 17:58
I've done a quick test like this:
```viml
function! phpcomplete#CompletePHP(findstart, base) 
  let ret = win_execute(win_getid(), 'call s:test()')
endf

function! s:test()
  below 1new
endf
```
The error persists, but the window itself opens. That's why we had a `silent!` in there. I've tried executing the whole completion function indirectly with `win_execute()`, but it doesn't seem to solve the problem (completing a just a class name which is from only tags works still, so generally it runs it fine).

On further investigation I found something else wrong: It seems that when the new window is opened, the current window is not switched over in newer vim versions. In the same section I've added this:
```viml
echom 'before: '.winnr()
silent! below 1new
echom 'after: '.winnr()
```
On an older vim (osx catalina default)
`VIM - Vi IMproved 8.1 Included patches: 1-503, 505-680, 682-2292`
I get this in `:messages`
```
"t2.php" 4L, 26C
before 1
after 2
```
On a newer vim (last homebrew install) `VIM - Vi IMproved 8.2 Included patches: 1-2400`:
```
"t2.php" 4L, 26C
before 1
after 1
```

What's weird that the line right after the `below 1new` is adding content to that window and that seems to be adding it to the correct buffer. Other commands like `getline()` or `search()` are all executing on the original buffer which breaks the code.

**Comment by lacygoill** [comment] 2021-02-07 01:37
> The error persists, but the window itself opens.

Yes, because now it's no longer allowed to switch windows while a completion function is being processed.  This is caused by these 2 patches:

   - [8.2.2426](https://github.com/vim/vim/releases/tag/v8.2.2426)  allowing 'completefunc' to switch windows causes trouble
   - [8.2.2427](https://github.com/vim/vim/releases/tag/v8.2.2427)  can still switch windows for 'completefunc'

`win_execute()` doesn't change that.  But it seems that your `below 1new` works with `silent!`, so I guess your issue is later with some other commands which fail because you're no longer in the right window.  That's when `win_execute()` can help.  With it, you don't need to be in the right window; it can run your commands anywhere, without switching the currently focused window which is now disallowed.

---

Also, instead of creating a temporary window with `:1new`, which maybe can break the general windows layout, or trigger some undesirable autocmds, I wonder whether you could use a temporary hidden popup.  Again, you can run arbitrary commands in a popup with `win_execute()`.  Unfortunately, the script is quite long, and I don't know anything about php, so I'm not sure what the right fix is here.

FWIW, this patch seems to fix the error, but I have no idea whether the suggestions are still correct or completely off:
```diff
diff --git a/runtime/autoload/phpcomplete.vim b/runtime/autoload/phpcomplete.vim
index 377baa843..838320aa6 100644
--- a/runtime/autoload/phpcomplete.vim
+++ b/runtime/autoload/phpcomplete.vim
@@ -2536,36 +2536,30 @@ endfunction!
 " }}}
 
 function! phpcomplete#GetCurrentNameSpace(file_lines) " {{{
-	let original_window = winnr()
-
-	silent! below 1new
-	silent! 0put =a:file_lines
-	normal! G
+	let popup_id = popup_create(a:file_lines, {'hidden': v:true})
+	call win_execute(popup_id, 'normal! G')
 
 	" clear out classes, functions and other blocks
 	while 1
-		let block_start_pos = searchpos('\c\(class\|trait\|function\|interface\)\s\+\_.\{-}\zs{', 'Web')
+		let block_start_pos = win_execute(popup_id, 'echo searchpos(''\c\(class\|trait\|function\|interface\)\s\+\_.\{-}\zs{'', "Web")')->trim("\<NL>")->eval()
 		if block_start_pos == [0, 0]
 			break
 		endif
-		let block_end_pos = searchpairpos('{', '', '}\|\%$', 'W', 'synIDattr(synID(line("."), col("."), 0), "name") =~? "string\\|comment"')
+		let block_end_pos = win_execute(popup_id, 'echo searchpairpos("{", "", ''}\|\%$'', "W", ''synIDattr(synID(line("."), col("."), 0), "name") =~? "string\\|comment"'')')->trim("\<NL>")->eval()
 
 		if block_end_pos != [0, 0]
 			" end of the block found, just delete it
-			silent! exec block_start_pos[0].','.block_end_pos[0].'d _'
+			call win_execute(popup_id, block_start_pos[0].','.block_end_pos[0].'d _', 'silent!')
 		else
 			" block pair not found, use block start as beginning and the end
 			" of the buffer instead
-			silent! exec block_start_pos[0].',$d _'
+			call win_execute(popup_id, block_start_pos[0].',$d _', 'silent!')
 		endif
 	endwhile
-	normal! G
+	call win_execute(popup_id, 'normal! G')
 
 	" grab the remains
-	let file_lines = reverse(getline(1, line('.') - 1))
-
-	silent! bw! %
-	exe original_window.'wincmd w'
+	let file_lines = win_execute(popup_id, "echo reverse(getline(1, line('.') - 1))")->trim("\<NL>")
 
 	let namespace_name_pattern = '[a-zA-Z_\x7f-\xff\\][a-zA-Z_0-9\x7f-\xff\\]*'
 	let i = 0
```
When I say "fixes the error", I mean this: no error is raised when I press `C-x C-o` in this test php file:
```php
<?php

$a = "hello";

$b = 'hello';

$c = "hello \"buddy\"";

$d = 'hello \'buddy\'';

$e = <<<EOS
hello buddy
EOS;

$f = <<<'EOS'
hello buddy
EOS;

$g = <<<"EOS"
hello buddy
EOS;

# just to check we're correctly out of a string here
$zzz_end = 42;
```
There is still another `silent! below 1new` in the script; I don't know when it's executed, but it would probably need to be refactored in a similar way.

**Comment by lacygoill** [comment] 2021-02-07 01:49
I think I forgot an `eval()`:
```diff
diff --git a/runtime/autoload/phpcomplete.vim b/runtime/autoload/phpcomplete.vim
index 377baa843..838320aa6 100644
--- a/runtime/autoload/phpcomplete.vim
+++ b/runtime/autoload/phpcomplete.vim
@@ -2536,36 +2536,30 @@ endfunction!
 " }}}
 
 function! phpcomplete#GetCurrentNameSpace(file_lines) " {{{
-	let original_window = winnr()
-
-	silent! below 1new
-	silent! 0put =a:file_lines
-	normal! G
+	let popup_id = popup_create(a:file_lines, {'hidden': v:true})
+	call win_execute(popup_id, 'normal! G')
 
 	" clear out classes, functions and other blocks
 	while 1
-		let block_start_pos = searchpos('\c\(class\|trait\|function\|interface\)\s\+\_.\{-}\zs{', 'Web')
+		let block_start_pos = win_execute(popup_id, 'echo searchpos(''\c\(class\|trait\|function\|interface\)\s\+\_.\{-}\zs{'', "Web")')->trim("\<NL>")->eval()
 		if block_start_pos == [0, 0]
 			break
 		endif
-		let block_end_pos = searchpairpos('{', '', '}\|\%$', 'W', 'synIDattr(synID(line("."), col("."), 0), "name") =~? "string\\|comment"')
+		let block_end_pos = win_execute(popup_id, 'echo searchpairpos("{", "", ''}\|\%$'', "W", ''synIDattr(synID(line("."), col("."), 0), "name") =~? "string\\|comment"'')')->trim("\<NL>")->eval()
 
 		if block_end_pos != [0, 0]
 			" end of the block found, just delete it
-			silent! exec block_start_pos[0].','.block_end_pos[0].'d _'
+			call win_execute(popup_id, block_start_pos[0].','.block_end_pos[0].'d _', 'silent!')
 		else
 			" block pair not found, use block start as beginning and the end
 			" of the buffer instead
-			silent! exec block_start_pos[0].',$d _'
+			call win_execute(popup_id, block_start_pos[0].',$d _', 'silent!')
 		endif
 	endwhile
-	normal! G
+	call win_execute(popup_id, 'normal! G')
 
 	" grab the remains
-	let file_lines = reverse(getline(1, line('.') - 1))
-
-	silent! bw! %
-	exe original_window.'wincmd w'
+	let file_lines = win_execute(popup_id, "echo reverse(getline(1, line('.') - 1))")->trim("\<NL>")->eval()
 
 	let namespace_name_pattern = '[a-zA-Z_\x7f-\xff\\][a-zA-Z_0-9\x7f-\xff\\]*'
 	let i = 0
```

**Comment by lacygoill** [comment] 2021-02-07 01:52
By moving these variables in the script-local namespace, you could get rid of the ugly `->trim("\<NL>")->eval()`

   - `block_start_pos`
   - `block_end_pos`
   - `file_lines`

For example, instead of writing this:

    let block_start_pos = win_execute(popup_id, 'echo searchpos(''\c\(class\|trait\|function\|interface\)\s\+\_.\{-}\zs{'', "Web")')->trim("\<NL>")->eval()

You could write this:

    call win_execute(popup_id, 'let s:block_start_pos = searchpos(''\c\(class\|trait\|function\|interface\)\s\+\_.\{-}\zs{'', "Web")')

**Comment by lacygoill** [comment] 2021-02-07 02:28
I forgot to close the hidden popup at the end.  Also, what I said about moving the variables in the script-local namespace was wrong.  You don't need to.  `let name = value` creates a function-local variable.  I was confused because that's not the case in Vim9.  I'll try to post a better patch later.

**Comment by lacygoill** [comment] 2021-02-07 02:35
This one is better:
```diff
diff --git a/runtime/autoload/phpcomplete.vim b/runtime/autoload/phpcomplete.vim
index 377baa843..1a8e8aaf9 100644
--- a/runtime/autoload/phpcomplete.vim
+++ b/runtime/autoload/phpcomplete.vim
@@ -2536,36 +2536,31 @@ endfunction!
 " }}}
 
 function! phpcomplete#GetCurrentNameSpace(file_lines) " {{{
-	let original_window = winnr()
-
-	silent! below 1new
-	silent! 0put =a:file_lines
-	normal! G
+	let popup_id = popup_create(a:file_lines, {'hidden': v:true})
+	call win_execute(popup_id, 'normal! G')
 
 	" clear out classes, functions and other blocks
 	while 1
-		let block_start_pos = searchpos('\c\(class\|trait\|function\|interface\)\s\+\_.\{-}\zs{', 'Web')
+		call win_execute(popup_id, 'let block_start_pos = searchpos(''\c\(class\|trait\|function\|interface\)\s\+\_.\{-}\zs{'', "Web")')
 		if block_start_pos == [0, 0]
 			break
 		endif
-		let block_end_pos = searchpairpos('{', '', '}\|\%$', 'W', 'synIDattr(synID(line("."), col("."), 0), "name") =~? "string\\|comment"')
+		call win_execute(popup_id, 'let block_end_pos = searchpairpos("{", "", ''}\|\%$'', "W", ''synIDattr(synID(line("."), col("."), 0), "name") =~? "string\\|comment"'')')
 
 		if block_end_pos != [0, 0]
 			" end of the block found, just delete it
-			silent! exec block_start_pos[0].','.block_end_pos[0].'d _'
+			call win_execute(popup_id, block_start_pos[0].','.block_end_pos[0].'d _', 'silent!')
 		else
 			" block pair not found, use block start as beginning and the end
 			" of the buffer instead
-			silent! exec block_start_pos[0].',$d _'
+			call win_execute(popup_id, block_start_pos[0].',$d _', 'silent!')
 		endif
 	endwhile
-	normal! G
+	call win_execute(popup_id, 'normal! G')
 
 	" grab the remains
-	let file_lines = reverse(getline(1, line('.') - 1))
-
-	silent! bw! %
-	exe original_window.'wincmd w'
+	call win_execute(popup_id, "let file_lines = reverse(getline(1, line('.') - 1))")
+	call popup_close(popup_id)
 
 	let namespace_name_pattern = '[a-zA-Z_\x7f-\xff\\][a-zA-Z_0-9\x7f-\xff\\]*'
 	let i = 0
```
But there is still another `:1new` to refactor.

**Comment by complex857** [comment] 2021-02-07 10:56
I tried to figure out the winid for the newly created window after the `new`, but it seems that only the buffer is created, not a window. Tried something like this:
```viml
silent! 1new phpcomplete_tempbuf
let bufid = bufnr('phpcomplete_tempbuf')
echom 'bufid: '.bufid
let winids = win_findbuf(bufid)
echom 'winids:'
echom winids
```
messages:
```
bufid: 17
winids:
[]   
```

Thank you for the suggestion for hidden popup windows (I suck at vimscript 😓). I'll give it a try.

**Comment by complex857** [comment] 2021-02-08 00:08
I've create a pull-request with the migrated code. All the previous tests are passing locally (old travis-ci integration seems to be broken).

Thank you @Roy-Orbison once again, for reporting it and @lacygoill for the popup window suggestion!

I'm a bit unfamiliar with github in this regard: I can't seem to add labels on the MR to mark it as "runtime" (I can see other MRs with that label). If there's some specific naming scheme or anything I can do that helps the process let me know.

**Comment by Roy-Orbison** [comment] 2021-02-08 00:35
Thanks to you all for jumping on this so quickly!

**Comment by lacygoill** [comment] 2021-02-13 17:24
Fixed by https://github.com/vim/vim/commit/942db23c9cb7532d68048530d749eb84ca94d0cd

**Closed as completed** 2021-02-13 20:31 UTC
Labels: runtime
