### ISSUE TITLE
Windows Drive Letter prepended when using gvim in cygwin / bash

### ISSUE THREAD

**Issue by pkirkaas** [vim/vim#10768] opened 2022-07-23 03:25 UTC
I use cygwin & bash as my only shell on my Windows PC.

`gvim [path/filename] `works perfectly to launch gvim from the bash shell.

`echo $HOME` from the bash shell returns `/cygdrive/c/home`

`cat $HOME/.bashrc `works fine

But` gvim $HOME/.bashrc` prepends "C:" and tries to open: `"C:\cygdrive\c\home\.bashrc"`

... so I guess gvim is trying to do something clever by automatically prepending the current drive letter to the path when it runs in a Windows environment? 

Does anyone know if there is any setting or way to prevent that?

**Comment by brammool** [comment] 2022-07-23 04:05
> I use cygwin & bash as my only shell on my Windows PC.
> 
> `gvim [path/filename] `works perfectly to launch gvim from the bash shell.
> 
> `echo $HOME` from the bash shell returns `/cygdrive/c/home`
> 
> `cat $HOME/.bashrc `works fine
> 
> But` gvim $HOME/.bashrc` prepends "C:" and tries to open: `"C:\cygdrive\c\home\.bashrc"`
> 
> ... so I guess gvim is trying to do something clever by prepending the current drive letter to the path? 
> 
> Is there any setting or way to prevent that?

What is 'shellslash' set to?  You could try changing it.

The problem is that normally on windows a patch starting with a slash
(or backslash) is not an absolute path, it is relative to the current
drive.  Cygwin causes terrible confusion by using /cygdrive/c instead of
c:/.  Trying to use Unix paths on an MS-Windows system will always cause
trouble.

It can't really be fixed in Vim, since we cannot predict what the path
is used for.  Given to a Cygwin tool it would work, given to any other
Windows command it will fail.

-- 
hundred-and-one symptoms of being an internet addict:
96. On Super Bowl Sunday, you followed the score by going to the
    Yahoo main page instead of turning on the TV.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by k-takata** [comment] 2022-07-23 04:06
I assume you are using the Windows native version of Vim (not the Cygwin version).
Then, you need to convert the Cygwin-style path to the Windows-style path by using the cygpath command.
E.g. `gvim "$(cygpath -w $HOME/.bashrc)"`

**Comment by chrisbra** [comment] 2022-07-28 17:38
I think we can close this one as a user configuration issue.

**Closed as completed by chrisbra** 2022-07-28 17:38 UTC
Labels: question, platform-windows, platform-cygwin
