### ISSUE TITLE
filename-modifier ':~:.' bug when getcwd()==$HOME

### ISSUE THREAD

**Issue by HarmtH** [vim/vim#6204] opened 2020-06-04 20:29 UTC
**Describe the bug**
filename-modifier ```:.``` is ignored after ```:~``` when getcwd()==$HOME

According to https://github.com/vim/vim/blob/v8.2.0903/runtime/doc/cmdline.txt#L943 ```':~:.'``` should result in maximum shortness. But it doesn't strip ```~/``` (become a relative path) when your cwd is your home directory. When your cwd is a subdirectory of your home directory it does work correctly.

**To Reproduce**
```
cd $HOME
vim --clean foo
:echo expand('%:~:.')
```

**Expected behavior**
```foo```

**Current behavior**
```~/foo```

**Environment**
 - Vim version: 8.2.862

**Comment by chrisbra** [comment] 2020-06-04 20:32
duplicate of #5979

**Closed as completed by chrisbra** 2020-06-04 20:32 UTC
Labels: duplicate
