### ISSUE TITLE
Cannot mouse scroll unfocused windows when mapping <ScrollWheelUp> and <ScrollWheelDown>

### ISSUE THREAD

**Issue by noscript** [vim/vim#6898] opened 2020-09-07 13:36 UTC
**Describe the bug**
Scrolling non-focused window (under mouse pointer) is no longer working after mapping `<ScrollWheelUp>` and `<ScrollWheelDown>`. Removing the mapping makes non-focused windows scrollable again.

**To Reproduce**
1. Create `~/scroll.vim`:
```vim
set mouse=a
set nocompatible
map <ScrollWheelUp> <C-Y>
map <ScrollWheelDown> <C-E>
```
2. Run VIM, `source  ~/scroll.vim` and make two horizontal splits:
```sh
vim -g -u NONE +'source ~/scroll.vim | edit ~/scroll.vim | help scroll'
```
3. Try scrolling top and bottom windows with mouse wheel without focusing (clicking) the window.

**Expected behavior**
Both windows are scrollable.

**Actual behavior**
Wheel scrolling only works for currently focused window.

**Environment:**
- Vim 8.2.1632
- OS: Ubuntu 18.04
- Terminal: GUI

**Comment by brammool** [comment] 2020-09-07 16:24
I'm afraid that this is to be expected.  For Vim to know where the mouse is requires some processing of the mouse events.  If you map the events then that code isn't reached.
Maybe it can be made to work by detecting the mouse pointer location, what window it's over, and executing the command in that window.  Quite complicated, but you could make it work.  Key is using getmousepos().
Since this is not a bug, closing this issue.

**Closed as completed by brammool** 2020-09-07 16:24 UTC
