### ISSUE TITLE
was there a way to make ':term' 's output respect the 'nowrap' option ?

### ISSUE THREAD

**Issue by Shane-XB-Qian** [vim/vim#7055] opened 2020-09-30 20:26 UTC
**Describe the bug**
wish :term output would not wrap the line, since such term output was not editable, kept it nowrap would be useful in some cases.
but looks it did not respect 'nowrap' option.
// btw: looks ':term' did not recoginize '~/' too ..

**To Reproduce**
Detailed steps to reproduce the behavior:
```
vim --clean x
set nowrap
vsp
vert term ls ~/a-very-long-nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnname.txt
vert term ls /home/shane/a-very-long-nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnname.txt
```

**Expected behavior**
not wrap the :term's output (when :term is not running or in normal mode), respected the nowrap option.

**Screenshots**
![image](https://user-images.githubusercontent.com/13550529/94735658-af41b580-039d-11eb-9c04-d6763604430d.png)

**Environment (please complete the following information):**
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Sep 30 2020 13:00:02)
Included patches: 1-1775

**Additional context**
n/a

**Comment by lacygoill** [comment] 2020-09-30 20:53
Possible duplicate of #5769.  See [here](https://vi.stackexchange.com/a/25072/17449) for a possible workaround.

**Comment by bfrg** [comment] 2020-09-30 21:06
Another alternative is to run everything inside tmux :smile: So for example `:term tmux`, then run `ls` etc.

IIRC it is a limitation of libvterm. See also the following discussion https://github.com/neovim/neovim/issues/2514. It seems there's a new WIP version that supports rewrapping: https://github.com/neovim/neovim/issues/2514#issuecomment-580333386
But maybe the author @leonerd can say a few words.

**Comment by Shane-XB-Qian** [comment] 2020-09-30 21:08
@lacygoill  thanks your info.
not sure if it was same situation, i understand we probably should not make ':term' not wrap when it is running, but why it kept wrapped status when it's done or in normal mode...

**Comment by Shane-XB-Qian** [comment] 2020-09-30 21:19
> Another alternative is to run everything inside tmux smile So for example `:term tmux`, then run `ls` etc.

um, really? have no chance to try 'tmux', but looks no help if using 'screen', same, nothing diff.
// and looks it's meaningless, even it worked, since looks nobody would embed such one by one .. :)
![image](https://user-images.githubusercontent.com/13550529/94740380-29296d00-03a5-11eb-907e-d6ce07999c4c.png)

**Comment by lacygoill** [comment] 2020-09-30 21:21
> Another alternative is to run everything inside tmux

FWIW, I'm always inside tmux and rarely use the Vim terminal.  I have a key binding on `M-c` to capture the contents of the current tmux pane in a Vim buffer.  Even if a line is hard wrapped in the terminal's scrollback buffer, I can get it back in one line in a Vim buffer.  It relies on the [`-J` option of the tmux command `capture-pane`](https://man.openbsd.org/OpenBSD-current/man1/tmux.1#capture-pane).  Here is the code:

    is_vim_or_man='#{||:#{m:*vim,#{pane_current_command}},#{==:#{pane_current_command},man}}'
    bind -T root M-c if -F \
        "#{||:#{==:#{window_name},[capture]},${is_vim_or_man}}" \
        '' \
        { capture-pane -b my-capture -J -S -
          neww -n "[capture]" \
          "stty -ixon; \
           vim +\"call tmux#capture_pane#main()\" <(tmux showb -b my-capture); \
           tmux deleteb -b my-capture" }
    setenv -gu is_vim_or_man

And here is [a link with some comments](https://github.com/lacygoill/config/blob/009ca7882d5d611f7fc229a3627e9afaac16a088/.config/tmux/tmux.conf#L995-L1076) explaining how it works.

**Comment by Shane-XB-Qian** [comment] 2020-09-30 21:30
um.. probably by a alternative way a small code snip can make it work, or even yank/paste/tidy-up from one buf to another manually can make it work too, but my question/advice was : it's better just it's native supported such (respected nowrap option when its not running and in normal mode) ..
or as you referred that ticket said, perhaps it's difficult to make it natively supported, if so, then let it be ... :(

**Comment by chrisbra** [comment] 2020-10-01 06:11
closing as duplicate of #5769

**Closed as completed by chrisbra** 2020-10-01 06:11 UTC
Labels: duplicate, feature-terminal

**Comment by lacygoill** [comment] 2020-10-01 12:29
I forgot that [tmux supports popup windows](https://man.openbsd.org/OpenBSD-current/man1/tmux.1#display-popup) since a somewhat recent version.  Instead of capturing the terminal scrollback buffer in a new window which might disturb the current layout, or just be distracting, we can now run Vim in a tmux popup:

    bind -T root M-c if -F \
        '#{||:#{m:*vim,#{pane_current_command}},#{==:#{pane_current_command},man}}' \
        '' \
        { capture-pane -b my-capture -J -S -
          popup -EK -xC -yC -w75% -h75% -d '#{pane_current_path}' -R \
              'tmux showb -b my-capture | vim --not-a-term - ; \
               tmux deleteb -b my-capture' }

**Comment by Shane-XB-Qian** [comment] 2020-10-01 14:11
> for example :term tmux, then run ls etc.

nevermind, i use 'gnu screen' very less at local, so to use 'tmux' embeded into vim's ':term' looks too complex ..

----------
anyway, this 'nowrap' issue is a problem, but other than native supported, there were some alternative workaround existed ..
so just waiting this would be fixed later.
