### ISSUE TITLE
Pressing Ctrl+s causes all buffers to freeze

### ISSUE THREAD

**Issue by Corallus-Caninus** [vim/vim#8089] opened 2021-04-08 23:19 UTC
**Describe the bug**
Pressing ctrl+s causes the buffers to freeze. It should not.

**To Reproduce**
Detailed steps to reproduce the behavior:
Press Ctrl+s in Vim with an open buffer

**Expected behavior**
anything else.

**Screenshots**
If applicable, copy/paste the text or add screenshots to help explain your problem.

**Environment (please complete the following information):**
 - Vim version Release 
 - OS: Ubuntu
 - Terminal: Kitty

**Additional context**
Vim is awesome!! :D

**Comment by vim-ml** [comment] 2021-04-08 23:50
On 2021-04-08, Corallus Caninus wrote:
> Describe the bug
> Pressing ctrl+s causes the buffers to freeze. It should not.
> 
> To Reproduce
> Press Ctrl+s in Vim with an open buffer
> 
> Expected behavior
> anything else.

> Environment (please complete the following information):
> 
>   • Vim version Release
>   • OS: Ubuntu
>   • Terminal: Kitty

This is expected behavior.  It is not caused by Vim but rather by
your terminal.

This is mentioned in a few places in the Vim help, but it's not easy
to find.  Execute

    :helpgrep CTRL-S\>

and you'll find a number of places that say,

    not used or used for terminal control flow

or

    NOTE: CTRL-S suspends display in many Unix terminals.  Use 's'
    instead.  Type CTRL-Q to resume displaying.

To keep your terminal from doing that, execute the following from
the shell prompt or put it in your shell's rc file, e.g., ~/.bashrc.

    stty stop undef

Regards,
Gary

**Comment by chrisbra** [comment] 2021-04-09 05:53
closing.

**Closed as completed by chrisbra** 2021-04-09 05:53 UTC

**Comment by mgedmin** [comment] 2021-04-09 08:06
BTW Vim 8.2.0852 fixed this.  If you have this or a newer version, you can use Ctrl-S in mappings without freezing terminal output, even if you don't tweak stty settings in your .bashrc.
