### ISSUE TITLE
prolog filetype detection

### ISSUE THREAD

**Issue by ignamartinoli** [vim/vim#10835] opened 2022-08-02 01:59 UTC
### Steps to reproduce

1. `vim example.pro`
2. `:set ft?`

### Expected behaviour

The file to be recognized as a **Prolog** file

### Version of Vim

latest

### Environment

Operating system: Gentoo
Terminal: kitty
Value of $TERM: xterm-kitty
Shell: zsh

**Comment by chrisbra** [comment] 2022-08-02 06:51
Hm,
currently, this is detect as IDL:

https://github.com/vim/vim/blob/e175dc6911948bcd0c854876b534fee62fb95b9f/runtime/filetype.vim#L887-L888

Is there a way to determine prolog files from the content?

**Comment by brammool** [comment] 2022-08-02 11:51
> ### Steps to reproduce
> 
> 1. `vim example.pro`
> 2. `:set ft?`
> 
> ### Expected behaviour
> 
> The file to be recognized as a **Prolog** file

Does Prolog uses the .pro file name extension?  I see .pl and .pdb.
Unfortunately .pl is also used for Perl.  Oh, it appears GNU Prolog
suggests using .pro.  But it is also used for idlang and C/C++ header
files.  Inspecting the file contents is required.

We can copy the check for Prolog from the .pl rule to also use for .pro
files:

  if getline(2) =~ '.;$'
    setf cpp
  else
    # recognize Prolog by specific text in the first non-empty line
    # require a blank after the '%' because Perl uses "%list" and "%translate"
    var l = getline(nextnonblank(1))
    if l =~ '\<prolog\>' || l =~ '^\s*\(%\+\(\s\|$\)\|/\*\)' || l =~ ':-'
      setf prolog
    else
      exe 'setf ' .. default
    endif
  endif


-- 
Get a life?  What is the URL where it can be downloaded?

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by ignamartinoli** [comment] 2022-08-02 19:07
Normally a prolog file can commence with a """function""" like syntax with a dot at the end as

```prolog
something(somethigs).
```

An edge case is that the dot can be on another line for intentation as

```pro
something(too_much_things,
  to_be_on,
  the_same_line).
```

**Comment by benknoble** [comment] 2022-08-03 12:53
> At least in some way or another, in the first few line, you're expected to encounter a dot closing a sentence, just as the semi-colon with **C**

This is somewhat true, though there are also comments (line `%` and multiline `/* */`) and directives (`:- clause(…).`, can be more than one line as indicated) or hash-bang lines.

Because of the Perl issue, I am in the habit of writing `% prolog` or `%vim: ft=prolog` at the top of my .pl Prolog files.

**Comment by ignamartinoli** [comment] 2022-08-04 09:09
To recap:
We need to differentiate **Prolog** from **C**/**C++** and `idlang` (I guess we are talking about [this](https://en.wikipedia.org/wiki/IDL_(programming_language)) language, correct me if I'm wrong).

Now the options are:

1. If a line commences with `%` we can be sure is **Prolog** since it doesn't clash with the others options

2. On clauses we have one advantage. Even in the worst case of multiline clause, if we were in the presence of a **C**/**C++** header, we would need to specify the type for each parameter as
```c
add(
	int a, 
	int b
)
```
which is illegal **Prolog**, since we can't have two symbols separated by a space. The same thing would be written as
```prolog
add(
	A,
	B
).
```
so on the second line we could already have a clue of the programming language, by following the rule "if there is more than two words separated by space it's a **C**/**C++** file".

3. On the case of multiline comments it would be trickier. They would need to be ignored until reaching a line of real code, still I guess **Prolog**, by usage of the `.pro` extension, would be a lot better guess than **IDL** or **C**/**C++**, so it should be the default

**Comment by brammool** [comment] 2022-08-05 11:37
> To recap:
> We need to differentiate **Prolog** from **C**/**C++** and `idlang` (I guess we are talking about [this](https://en.wikipedia.org/wiki/IDL_(programming_language)) language, correct me if I'm wrong).
> 
> Now the options are:
> 
> 1. If a line commences with `%` we can be sure is **Prolog** since it doesn't clash with the others options
> 
> 2. On clauses we have one advantage. Even in the worst case of multiline clause, if we were in the presence of a **C**/**C++** header, we would need to specify the type for each parameter as
> ```c
> add(
> 	int a, 
> 	int b
> )
> ```

Normally .pro files use one line per function.  Theoretically it is
possible that someone hand-edits a file or writes their own tool, but
the commonly used cproto produces output like:

	int add_to_showcmd(int c);

> which is illegal **Prolog**, since we can't have two symbols separated by a space. The same thing would be written as
> ```prolog
> add(
> 	A,
> 	B
> ).
> ```
> so on the second line we could already have a clue of the programming language, by following the rule "if there is more than two words separated by space it's a **C**/**C++** file".
> 
> 3. On the case of multiline comments it would be trickier. They would
> need to be ignored until reaching a line of real code, still I guess
> **Prolog**, by usage of the `.pro` extension, would be a lot better
> guess than **IDL** or **C**/**C++**, so it should be the default

The ProtoCheck() function mentions:

  # recognize Prolog by specific text in the first non-empty line
  # require a blank after the '%' because Perl uses "%list" and "%translate"



-- 
"Marriage is the process of finding out what kind of man your wife
would have preferred"

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by ignamartinoli** [comment] 2022-08-05 19:27
@brammool so if I understand correctly. Differentiating between **Cproto** and **Prolog** wouldn't be much of an issue since **Cproto** files are generated with a specific format much different from **Prolog**?

**Comment by brammool** [comment] 2022-08-05 20:40
> @brammool so if I understand correctly. Differentiating between
> **Cproto** and **Prolog** wouldn't be much of an issue since
> **Cproto** files are generated with a specific format much different
> from **Prolog**?

Yes, no need to worry about C++ syntax.

-- 
hundred-and-one symptoms of being an internet addict:
247. You use www.switchboard.com instead of dialing 411 and 555-12-12
     for directory assistance.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by ignamartinoli** [comment] 2022-08-06 05:52
Awesome, then we only need to differentiate between **IDL** and **Prolog**.
**IDL** syntax looks a lot more like **Matlab**'s, closing statements with newlines or semicolons, instead of a dot.
If we check for that we would be set, right?

**Comment by benknoble** [comment] 2022-08-06 14:00
> Awesome, then we only need to differentiate between **IDL** and **Prolog**.
> 
> **IDL** syntax looks a lot more like **Matlab**'s, closing statements with newlines or semicolons, instead of a dot.
> 
> If we check for that we would be set, right?

Note that Prolog also has semicolons (for disjunction) that are conventionally placed at end-of-line.

**Comment by chrisbra** [comment] 2022-08-09 08:07
should be fixed by 48c3f4e0bff7efd289a7001b68c777b6f89a7057

**Comment by ignamartinoli** [comment] 2022-10-30 18:01
@chrisbra hi, I forgot to test the changes and found out the issue is still present.

I tested with **Vim** version

```
VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Oct 30 2022 14:58:05)
Included patches: 1-655
Modified by Gentoo-9.0.0655-r1
Compiled by sicro@localhost
```

the file `test.pro` with content

```prolog
partition([], _, [], []).
partition([X|Xs], Pivot, Smalls, Bigs) :-
  ( X @< Pivot ->
    Smalls = [X|Rest],
    partition(Xs, Pivot, Rest, Bigs)
  ; Bigs = [X|Rest],
    partition(Xs, Pivot, Smalls, Rest)
  ).
 
quicksort([])     --> [].
quicksort([X|Xs]) -->
  { partition(Xs, X, Smaller, Bigger) },
  quicksort(Smaller), [X], quicksort(Bigger).
```

and the filetype returned is `idlang`

**Comment by chrisbra** [comment] 2022-11-02 18:03
re-opening. Can you suggest some changes to fix it please?

**Comment by ignamartinoli** [comment] 2022-11-02 18:49
At the moment this fix works only if the first line begins with `%` (**Prolog**'s comment). It's a bit hackey of a solution and I doubt it would work out-of-the-box on most cases.

Our objective is to differentiate **IDL**, from **Prolog**.
**Prolog** has a really nice characteristic, most rules (**Prolog**'s functions) won't span more than 10 lines at most, since the language strategy is to divide the problem domain into smaller pieces. This is more notable in the first lines were normally startup functions and facts (**Prolog**'s constants) are placed.

My proposed solution is based on this key point: **IDL** uses the dot symbol (`.`) only to write floating point numbers (i.e. `42.0`), while **Prolog** uses it to end rules also (i.e. `height(dad, 1.75).`).

Hence if we identify, say the first _n_ dots on a `.pro` file, if _at least one_ of them is trailing (`/.$/`) we can be _sure it is a **Prolog** file_.

This wouldn't exclude that if all the dots are of the form `\d.\d` then it surely is a **IDL** file, but the probability would be significantly lower (it's a logic _if_, not an _if and only if_).

In pseudo-code:

```
ft = "idlang"

for i in range 10:
  line = readline(i)
  if regex.match(line, "/.$/"):
    ft = "prolog"
    break
```

I have an important exam on Friday, but after that I have a couple of free days.
If you're low on work-force to fix this I can try to step in. I saw how a preliminary solution was implemented in [`48c3f4e`](https://github.com/vim/vim/commit/48c3f4e0bff7efd289a7001b68c777b6f89a7057) and I have a bit of experience in **VimL** scripting.

**Comment by benknoble** [comment] 2022-11-02 19:02
As a counter point, a [`module` declaration in Prolog](https://www.swi-prolog.org/pldoc/man?section=defmodule) might reasonably [get long](https://github.com/benknoble/zelda-mosaic/blob/b3e3360ed09994a928a7c0fa798ba5f4e47b17c5/zelda-scrape.pl#L4), so in certain cases you wouldn't find the first trailing `.` until later in the file.

**Comment by ignamartinoli** [comment] 2022-11-03 04:17
@benknoble Your point is completely right.

I mainly use **Prolog** on small University projects, so I didn't had the chance to see bigger and more professionals code-bases.

Luckily (as far as I've seen from looking it up, and correct me if I'm wrong), all this kind of directives like `module` begin with `:-`, which is illegal in **IDL**.

So adding another check in the first lines to see if it appears would also confirm that the file is a **Prolog** one, in the form:

```
ft = "idlang"

for i in range 10:
  line = readline(i)
  # HACK: for performance, equal to regex: /(^:-|\.$)/
  if (line[0] == ":" and line[1] == "-") or line[-1] == ".":
    ft = "prolog"
    break
```

[These](https://regexr.com/71hak) are a couple of tests to show the behavior.
I'm not sure if it would be better to use `if`s or a _regex_ in this situation.

**Comment by brammool** [comment] 2022-11-05 22:49
There are some ideas, I hope someone can take those to create a PR with proper tests.
We really need tests (in src/testdir/test_filetype.vim) to make sure we don't get regressions later
and to illustrate what the code intends to differentiate.  And what wasn't checked for yet....

**Comment by dkearns** [comment] 2022-11-06 02:35
>  I'm not sure if it would be better to use ifs or a regex in this situation.

It's probably more idiomatic to use the regex here and profiling (you made me look) suggests it's actually a little faster.

**Comment by ignamartinoli** [comment] 2024-07-09 20:16
Hi. Life (mainly university) swallowed me, and I forgot about this Issue. Now I have enough spare time to fix/improve this.

I cloned the repo and I changed the file at `runtime/autoload/dist/ft.vim`, on line 467 (that checks for the Prolog file) like this:

```viml
    var lnum = getline(nextnonblank(1))
    if lnum =~ '\<prolog\>' || lnum =~ '^\s*(:-|%|\/)|\.\s*$'
      setf prolog
    else
      exe 'setf ' .. default
    endif
```

Now the RegEx is faster than the one I proposed before and is also more flexible.

How can I test it before pushing?

**Comment by benknoble** [comment] 2024-07-09 21:44
> Hi. I'm sorry I wasn't able to work on this again, life (mainly university) swallowed me, and I forgot about this Issue. Now I have enough spare time to fix/improve this.

Life happens, no worries.

> I cloned the repo and I changed the file at `runtime/autoload/dist/ft.vim`, on line 467 (that checks for the Prolog file) like this:
> 
> ```viml
>     var lnum = getline(nextnonblank(1))
>     if lnum =~ '\<prolog\>' || lnum =~ '^\s*(:-|%|\/)|\.\s*$'
>       setf prolog
>     else
>       exe 'setf ' .. default
>     endif
> ```
> 
> Now the RegEx is faster than the one I proposed before and is also more flexible (https://regexr.com/83527).

The pattern `^\s*(:-|%|\/)|\.\s*$` doesn't look right to me; did you mean `^\s*(:-\|%\|\/)\|\.\s*$`?

> How can I test it before pushing?

Probably the best thing to do is write a test in `src/test/test_filetype.vim`, then build and test Vim (`./configure … && make all test`).

**Comment by ignamartinoli** [comment] 2024-07-10 17:57
@benknoble yes, you're right, I forgot to correctly format the Regex in VimL.

This is now the updated fix:

```viml
var lnum = getline(nextnonblank(1))
if lnum =~ '\<prolog\>' || lnum =~ '^\s*(:-\|%\|\/\*)\|\.\s*$'
  setf prolog
else
  exe 'setf ' .. default
endif
```

I wrote 4 tests in `src/testdir/test_filetype.vim` by looking at other similars:

```viml
func Test_pro_file()
  filetype on

  " Prolog
  call writefile(['rule(test, 1.7).'], 'Xfile.pro', 'D')
  split Xfile.pro
  call assert_equal('prolog', &filetype)
  bwipe!

  " FIX: always fails
  call writefile([':-module(test/1,'], 'Xfile.pro', 'D')
  split Xfile.pro
  call assert_equal('prolog', &filetype)
  bwipe!

  call writefile(['% comment'], 'Xfile.pro', 'D')
  split Xfile.pro
  call assert_equal('prolog', &filetype)
  bwipe!

  " FIX: always fails
  call writefile(['/* MULTILINE COMMENT'], 'Xfile.pro', 'D')
  split Xfile.pro
  call assert_equal('prolog', &filetype)
  bwipe!

  filetype off
endfunc
```

The second and fourth test failed.

The first and third test passed, but only if they were the other tests were commented (so the third test passed if the first, second and fourth test were commented).

I'm looking into fixing the failing tests. Do you happen to know why the other two tests only work if they are alone? (I'm probably writing the tests wrong)

**Comment by ignamartinoli** [comment] 2024-07-10 18:40
Fixed it. Now all tests passed.

I'm pushing now

**Closed as completed** 2024-07-10 19:30 UTC
Labels: runtime, bug

**Comment by clason** [comment] 2024-07-13 17:30
There is a very similar check for Perl files (`FTpl()`) -- should this be adapted analogously (as in the fixup commit, of course)?

**Comment by ignamartinoli** [comment] 2024-07-13 21:45
@clason in what file? (also, thanks for crediting me on Neovim)

**Comment by clason** [comment] 2024-07-13 21:46
In the same file (and it's your PR, so obviously the credit is yours).

**Comment by ignamartinoli** [comment] 2024-07-13 21:55
@clason yes, you're right. It looks like that file function should be updated as well. I will do that and commit
