### ISSUE TITLE
vim9class can't use this keyword in lambda function

### ISSUE THREAD

**Issue by heavenshell** [vim/vim#12336] opened 2023-05-03 12:43 UTC
### Steps to reproduce

```vim
vim9script

class Counter
  this.counter = 10
  def new()
  enddef

  def Up()
    timer_start(1000, (_time) => {
      echomsg this.counter
      this.counter = this.counter + 1
    }, { repeat: -1 })
  enddef
endclass

const counter = Counter.new()
counter.Up()
```
1. open Vim and `:so %`
2. Error shows
```
Error detected while compiling /tmp/a.vim[17]..function Up[1]..<lambda>68:
line    2:
E1034: Cannot use reserved name this
```

If I remove `this.counter = this.counter + 1` line, no error raised.

### Expected behaviour

It would be great if this keyword can use in lambda function like JavaScript's arrow function `this`.

Notes:

I know I can use like followings
```vim
vim9script

class Counter
  this.counter = 10
  def new()
  enddef

  def Up()
    const self = this
    timer_start(1000, (_time) => {
      echomsg self.counter
      self.counter = self.counter + 1
    }, { repeat: -1 })
  enddef
endclass

const counter = Counter.new()
counter.Up()
```

### Version of Vim

Vim9.1474

### Environment

OS: macOS
Terminal: Terminal.app
value of $TERM: xterm-256color
shell: zsh

**Comment by rodgersxy** [comment] 2023-05-05 17:33
Vimscript "this" is a reserved  keyword referring to the current object same to "self" in other programming language. to fix it rename "this" to something else eg self or obj

**Comment by brammool** [comment] 2023-05-13 14:37
Looks like a duplicate of #12076.  If you agree you can close this issue.

**Closed as completed** 2023-05-19 18:01 UTC
Labels: bug
