### ISSUE TITLE
It shows garbled characters when I open a  "*.tar.gz" file

### ISSUE THREAD

**Issue by RisingooSun** [vim/vim#6425] opened 2020-07-09 13:51 UTC
Hi guys，
    It shows garbled characters when I open a  "*.tar.gz" file, which  is compressed from the file with “error”  in the name.

    For example:
        [root@192-168-100-100 ~]# touch error_test.log
        [root@192-168-100-100 ~]# tar -zcvf test.tar.gz error_test.log 
         error_test.log
        [root@192-168-100-100 ~]# vim test.tar.gz
        
![image](https://user-images.githubusercontent.com/52234597/87048273-1c75fc80-c22e-11ea-96af-b7d4c3f60799.png)

        My os version:  CentOS Linux release 7.5.1804 (Core)
        My vim version:   vim-enhanced-7.4.160-4.el7.x86_64
    
    Waiting for your help

Thank you

**Comment by chrisbra** [comment] 2020-07-09 14:35
You have a very old version of Vim installed. Nevertheless, I can reproduce the problem in tar.vim.

The problem is, the tar.vim plugin checks if the last line matches `warning` or `error` or a few other keywords and if it does, it aborts.

If we make the regex a bit more strict and also require to have it match a `space` (after all an error message should contain some spaces to be more readable and unix files are very unlikely to contain spaces) we can work around this:

```patch
diff --git a/runtime/autoload/tar.vim b/runtime/autoload/tar.vim
index 9f9609434..56d125cf6 100644
--- a/runtime/autoload/tar.vim
+++ b/runtime/autoload/tar.vim
@@ -204,7 +204,12 @@ fun! tar#Browse(tarfile)
 "   call Dret("tar#Browse : a:tarfile<".a:tarfile.">")
    return
   endif
-  if line("$") == curlast || ( line("$") == (curlast + 1) && getline("$") =~# '\c\%(warning\|error\|inappropriate\|unrecognized\)')
+  " If there was an error message, the last line probably matches some keywords but
+  " should also contain whitespace for readability. Make sure not to match a
+  " filename that contains the keyword (error/warning/unrecognized/inappropriate, etc)
+  if line("$") == curlast || ( line("$") == (curlast + 1) &&
+        \ getline("$") =~# '\c\<\%(warning\|error\|inappropriate\|unrecognized\)\>' &&
+        \ getline("$") =~  '\s' )
    redraw!
    echohl WarningMsg | echo "***warning*** (tar#Browse) ".a:tarfile." doesn't appear to be a tar file" | echohl None
    keepj sil! %d
```


cc Charles, the maintainer: @cecamp

**Comment by RisingooSun** [comment] 2020-07-09 16:29
> You have a very old version of Vim installed. Nevertheless, I can reproduce the problem in tar.vim.
> 
> The problem is, the tar.vim plugin checks if the last line matches `warning` or `error` or a few other keywords and if it does, it aborts.
> 
> If we make the regex a bit more strict and also require to have it match a `space` (after all an error message should contain some spaces to be more readable and unix files are very unlikely to contain spaces) we can work around this:
> 
> ```diff
> diff --git a/runtime/autoload/tar.vim b/runtime/autoload/tar.vim
> index 9f9609434..56d125cf6 100644
> --- a/runtime/autoload/tar.vim
> +++ b/runtime/autoload/tar.vim
> @@ -204,7 +204,12 @@ fun! tar#Browse(tarfile)
>  "   call Dret("tar#Browse : a:tarfile<".a:tarfile.">")
>     return
>    endif
> -  if line("$") == curlast || ( line("$") == (curlast + 1) && getline("$") =~# '\c\%(warning\|error\|inappropriate\|unrecognized\)')
> +  " If there was an error message, the last line probably matches some keywords but
> +  " should also contain whitespace for readability. Make sure not to match a
> +  " filename that contains the keyword (error/warning/unrecognized/inappropriate, etc)
> +  if line("$") == curlast || ( line("$") == (curlast + 1) &&
> +        \ getline("$") =~# '\c\<\%(warning\|error\|inappropriate\|unrecognized\)\>' &&
> +        \ getline("$") =~  '\s' )
>     redraw!
>     echohl WarningMsg | echo "***warning*** (tar#Browse) ".a:tarfile." doesn't appear to be a tar file" | echohl None
>     keepj sil! %d
> ```
> 
> cc Charles, the maintainer: @cecamp

Nice work, my buddy! I modified  tar.vim according to your patch and it worked. Now It displays normally. Thank you for your help. 

![image](https://user-images.githubusercontent.com/52234597/87065331-7df49600-c243-11ea-99e8-5d964b4aa1e3.png)

Will the patch be incorporated into the next version?

**Comment by buweilv** [comment] 2020-07-13 06:18
> You have a very old version of Vim installed. Nevertheless, I can reproduce the problem in tar.vim.
> 
> The problem is, the tar.vim plugin checks if the last line matches `warning` or `error` or a few other keywords and if it does, it aborts.
> 
> If we make the regex a bit more strict and also require to have it match a `space` (after all an error message should contain some spaces to be more readable and unix files are very unlikely to contain spaces) we can work around this:
> 
> ```diff
> diff --git a/runtime/autoload/tar.vim b/runtime/autoload/tar.vim
> index 9f9609434..56d125cf6 100644
> --- a/runtime/autoload/tar.vim
> +++ b/runtime/autoload/tar.vim
> @@ -204,7 +204,12 @@ fun! tar#Browse(tarfile)
>  "   call Dret("tar#Browse : a:tarfile<".a:tarfile.">")
>     return
>    endif
> -  if line("$") == curlast || ( line("$") == (curlast + 1) && getline("$") =~# '\c\%(warning\|error\|inappropriate\|unrecognized\)')
> +  " If there was an error message, the last line probably matches some keywords but
> +  " should also contain whitespace for readability. Make sure not to match a
> +  " filename that contains the keyword (error/warning/unrecognized/inappropriate, etc)
> +  if line("$") == curlast || ( line("$") == (curlast + 1) &&
> +        \ getline("$") =~# '\c\<\%(warning\|error\|inappropriate\|unrecognized\)\>' &&
> +        \ getline("$") =~  '\s' )
>     redraw!
>     echohl WarningMsg | echo "***warning*** (tar#Browse) ".a:tarfile." doesn't appear to be a tar file" | echohl None
>     keepj sil! %d
> ```
> 
> cc Charles, the maintainer: @cecamp

@cecamp 
Hi cecmap, is this issue a problem, would chrisbra's patch be merged into mainline?

**Comment by cecamp** [comment] 2020-07-13 18:52
Thank you, Christian -- I'll include it.  Eventually it will get to Bram...

**Closed as completed by cecamp** 2020-07-13 18:52 UTC
Labels: patch, runtime

**Comment by AnHeBridgeNorth** [comment] 2022-01-30 09:09
When will this be resolved? thanks！

**Comment by brammool** [comment] 2023-01-06 12:49
It looks like version 33 of the tar plugin wasn't finished.  You can find the unfinished version on Charles website.
@cecamp can you send me the version to included?

**Comment by code-Oct** [comment] 2023-01-09 01:32
> It looks like version 33 of the tar plugin wasn't finished. You can find the unfinished version on Charles website. 

Thank you for your response!
