### ISSUE TITLE
kPageUp/kPageDown doesn't work in gvim like in vim?

### ISSUE THREAD

**Issue by hasufell** [vim/vim#7174] opened 2020-10-20 10:21 UTC
**Describe the bug**

When adding `kPageUp`/`kPageDown` key bindings in vim-clap, they don't work in the clap popup windows in **gvim**, but in *vim*. This suggests it's not an issue with vim-clap, but with gvim. Why does it work in vim?

See https://github.com/liuchengxu/vim-clap/issues/552

**To Reproduce**

1. Add [vim-clap](https://github.com/liuchengxu/vim-clap#installation) to your rtp
2. Add the following config to your vimrc:
```vim
autocmd Filetype clap_input inoremap <silent> <buffer> <kPageDown> <C-R>=clap#navigation#scroll('down')<CR>
autocmd Filetype clap_input inoremap <silent> <buffer> <kPageUp> <C-R>=clap#navigation#scroll('up')<CR>
autocmd Filetype clap_input nnoremap <silent> <buffer> <kPageDown> <C-R>=clap#navigation#scroll('down')<CR>
autocmd Filetype clap_input nnoremap <silent> <buffer> <kPageUp> <C-R>=clap#navigation#scroll('up')<CR>
```
3. Open a folder with multiple files via gvim
4. Run `Clap files`
5. try to use `kPageUp`/`kPageDown` to navigate

**Expected behavior**

Navigation works via the new keys.

**Environment (please complete the following information):**
 - Vim version: https://gist.github.com/hasufell/0e61d233c0ca963b26b3d54ba7442758
 - OS: Exherbo Linux
 - Terminal: alacritty

**Comment by brammool** [comment] 2020-10-20 10:41
What GUI is this with?  GTK?
I can map <kPageDown> in GTK without proglems.

**Comment by lacygoill** [comment] 2020-10-20 10:43
> Vim version: https://gist.github.com/hasufell/0e61d233c0ca963b26b3d54ba7442758

You're using 8.2.1058, can you reproduce on master?

A few bugs have been fixed in the last few months; they were related to mappings which didn't work as expected in the GUI.  For example, https://github.com/vim/vim/issues/6457 and https://github.com/vim/vim/issues/6243.

**Comment by hasufell** [comment] 2020-10-20 10:56
> What GUI is this with? GTK?

yep

> I can map in GTK without proglems.

I can too, but the binding for the plugin doesn't work in gvim. Now you could say that's a plugin issue... but why does it work in vim? The author believes it's a gvim issue.

> You're using 8.2.1058, can you reproduce on master?

I tried with a2c026d0fd470d68d679616fddfc285cb4834412 it's the same.

**Comment by lacygoill** [comment] 2020-10-20 11:36
I can map and use `<kPageDown>` as well as `<kPageUp>` in the terminal and in the GUI.  I've tried to use the mappings you provided, and indeed they don't work.  I've replaced the rhs with simple sequences of characters (`down` and `up`), and your mappings still don't work.  This suggests that they are not installed, which in turn suggests that the filetype event is not fired with the pattern `clap_input`.  I can't make your mappings work in the terminal either (st inside tmux).  I've [logged all the events](https://0x0.st/iDWx.txt) which were fired and although I can see `FileType` being fired once, I can't find the pattern `clap_input`.

To me this suggests that the issue is in the plugin.  Although, I haven't read its documentation, so maybe I'm missing some simple configuration.  If it's not a simple configuration issue, then you'll need to find a minimal working example, because the plugin is quite complex (almost 14K lines of code):

    $ cloc .
         200 text files.
         199 unique files.
          15 files ignored.

    github.com/AlDanial/cloc v 1.86  T=0.11 s (1712.9 files/s, 163535.5 lines/s)
    -------------------------------------------------------------------------------
    Language                     files          blank        comment           code
    -------------------------------------------------------------------------------
    vim script                      99           1591            624           7829
    Rust                            42            594            453           4027
    Markdown                         7            416              0            886
    Python                           6            112             46            331
    Bourne Shell                     9             71             12            281
    TOML                            13             32             11            197
    JSON                             3              0              0            183
    YAML                             5             33              4            135
    make                             2             12              0             32
    PowerShell                       1              8              1             18
    Dockerfile                       1              3              4              3
    -------------------------------------------------------------------------------
    SUM:                           188           2872           1155          13922
    -------------------------------------------------------------------------------

**Comment by hasufell** [comment] 2020-10-20 11:47
@lacygoill 

1. `git clone https://github.com/hasufell/vim-clap-minimal-example.git` 
2. `cd vim-clap-minimal-example`
3. `make -C vim-clap`
4. `gvim -u min.vim` and `vim -u min.vim`
5. `:Clap files`
6. try to navigate with kPageUp/Down

**Comment by lacygoill** [comment] 2020-10-20 11:47
> This suggests that they are not installed

Actually, they are ignored, because even a simple global mapping like this one doesn't work in the plugin's popup:

    ino a b

I don't know how the plugin handles the keypresses, and in which mode it is when the popup is active.

**Comment by lacygoill** [comment] 2020-10-20 11:50
> @lacygoill

>     git clone https://github.com/hasufell/vim-clap-minimal-example.git
>     cd vim-clap-minimal-example
>     make -C vim-clap
>     gvim -u min.vim and vim -u min.vim
>     :Clap files
>     try to navigate with kPageUp/Down

That doesn't look like [a minimal example](https://en.wikipedia.org/wiki/Minimal_working_example).  It looks like we still need to install a plugin which adds several thousands lines of code.

**Comment by hasufell** [comment] 2020-10-20 11:51
> That doesn't look like a minimal example. It looks like we still need to install a plugin which adds several thousands lines of code.

The plugin is part of the repo. I don't know how to reproduce that minimally without coding another plugin.

**Comment by lacygoill** [comment] 2020-10-20 11:55
> The plugin is part of the repo. I don't know how to reproduce that minimally without coding another plugin.

Removing code is not coding another plugin, but indeed, the bigger the plugin, the more time-consuming the task is.

**Comment by hasufell** [comment] 2020-10-20 11:58
Did you confirm the problem with my steps above?

**Comment by lacygoill** [comment] 2020-10-20 12:17
> Did you confirm the problem with my steps above?

I already confirmed that – on my machine – the mappings didn't work, neither in the terminal nor in the GUI.
I tried to follow your last instructions; after several minutes of compilation, I was stopped by [an error](https://0x0.st/iD4P.txt), probably due to a lack of space on my machine.

In any case, maybe the mappings don't work because of a bug in Vim, or maybe they don't because of a bug in the plugin.

**Comment by lacygoill** [comment] 2020-10-20 13:38
Does it help if you apply this patch to the vim-clap plugin?
```diff
diff --git a/autoload/clap/popup/move_manager.vim b/autoload/clap/popup/move_manager.vim
index b682b8e..288252d 100644
--- a/autoload/clap/popup/move_manager.vim
+++ b/autoload/clap/popup/move_manager.vim
@@ -127,6 +127,8 @@ let s:move_manager["\<C-K>"] = { winid -> win_execute(winid, 'noautocmd call cla
 let s:move_manager["\<Up>"] = s:move_manager["\<C-K>"]
 let s:move_manager["\<PageUp>"] = { winid -> win_execute(winid, 'noautocmd call clap#navigation#scroll("up")') }
 let s:move_manager["\<PageDown>"] = { winid -> win_execute(winid, 'noautocmd call clap#navigation#scroll("down")') }
+let s:move_manager["\<kPageUp>"] = { winid -> win_execute(winid, 'noautocmd call clap#navigation#scroll("up")') }
+let s:move_manager["\<kPageDown>"] = { winid -> win_execute(winid, 'noautocmd call clap#navigation#scroll("down")') }
 let s:move_manager["\<Tab>"] = { winid -> win_execute(winid, 'noautocmd call clap#handler#tab_action()') }
 let s:move_manager["\<CR>"] = { _winid -> clap#handler#cr_action() }
 let s:move_manager["\<Esc>"] = { _winid -> clap#handler#exit() }
```

**Comment by lacygoill** [comment] 2020-10-21 08:49
I can confirm that applying the previously mentioned patch fixes the issue:

![gif](https://user-images.githubusercontent.com/8505073/96696253-d848db00-138a-11eb-83b1-b768b01a2334.gif)

On this gif, pressing `<kPageUp>` and `<kPageDown>` makes [screenkey](https://gitlab.com/screenkey/screenkey) display resp. `(9)` and `(3)` because that's where the keys are located on my keypad, as shown on [this picture](https://en.wikipedia.org/wiki/Numeric_keypad#/media/File:Numpad.svg).

The issue has nothing to do with Vim, but with the plugin whose [popup filter doesn't handle `<kPageUp>` and `<kPageDown>`](https://github.com/liuchengxu/vim-clap/blob/d3955eb7800e1c81e9c95ee141762005fe2d889b/autoload/clap/popup/move_manager.vim#L124-L149).

**Comment by hasufell** [comment] 2020-10-21 09:24
> I can confirm that applying the previously mentioned patch fixes the issue:

Nice find. I can confirm too. But then I wonder why it works without the patch in vim terminal?

**Closed as completed** 2020-10-21 10:02 UTC
