### ISSUE TITLE
Bug in C syntax (cComment leaks into parentheses)

### ISSUE THREAD

**Issue by Galicarnax** [vim/vim#6426] opened 2020-07-09 18:59 UTC
Following `:h containedin`, I put the following snippet into /after/syntax/c.vim:
```
syn keyword myword HELP containedin=cComment.* contained
hi myword ctermfg=red
```
All nice, now I have `HELP` highlighted in red within comments in C source code.
But if I have a C variable called HELP and if it occurs within parentheses (e.g., passed to a function), it also gets colored in red. Seems like somehow cComment.* leaks into the regions between normal parentheses.

Using Vim version 8.2, C syntax file last changed on 29 Nov 2019, so I guess [this](https://github.com/vim/vim/issues/3551) (probably related) bug was fixed there.

**Comment by bfrg** [comment] 2020-07-09 19:37
Add the following to `after/syntax/c.vim`:
```vim
" Highlight additional keywords in comments
syntax keyword cMywords contained HELP
syntax cluster cCommentGroup add=cMywords
highlight default link cMywords Special
```
See `:help syn-cluster` for more details.

**Comment by Galicarnax** [comment] 2020-07-10 04:27
> Add the following to `after/syntax/c.vim`:
> 
> ```viml
> " Highlight additional keywords in comments
> syntax keyword cMywords contained HELP
> syntax cluster cCommentGroup add=cMywords
> highlight default link cMywords Special
> ```
> 
> See `:help syn-cluster` for more details.

Works, thanks. Still, I believe the solution using `containedin=` is not supposed to behave the way I described?

**Comment by bfrg** [comment] 2020-07-10 09:59
This is the same issue as #1265.

The following line in `c.vim` causes this unexpected highlighting you described:
https://github.com/vim/vim/blob/67fbdfefd26a237831c3838f799d3e6198c8a34a/runtime/syntax/c.vim#L162

The problem is the `ALLBUT` option. If your syntax group isn't listed after `ALLBUT`, it will always be highlighted when inside parentheses, even if you add `containedin=xyz`. 

My code snippet above on the other hand works because `cMywords` is added to the syntax cluster `cCommentGroup`, which itself is contained in `cParenGroup`:
https://github.com/vim/vim/blob/67fbdfefd26a237831c3838f799d3e6198c8a34a/runtime/syntax/c.vim#L131
And `cParenGroup` is the first group listed after `ALLBUT`.

**Comment by chrisbra** [comment] 2020-07-10 10:04
okay, closing as duplicate of #1265

**Closed as completed by chrisbra** 2020-07-10 10:04 UTC
Labels: duplicate, runtime
