### ISSUE TITLE
Regression in vim 8.0: undo in ex mode

### ISSUE THREAD

**Issue by johnwcowan** [vim/vim#1662] opened 2017-04-27 19:36 UTC
In pre-7.0 versions of vim, the "undo" command in ex mode (not colon mode, but ex mode proper) undid everything back to the last time you were in vi mode.  If you had never been in vi mode, as when starting the editor as "ex", this undid everything in the current editing session irrevocably.  This was fixed in vim 7.0.  It has now returned in vim 8.0.

—John Cowan, "ex" troglodyte

**Comment by chrisbra** [comment] 2017-04-28 04:50
I am not sure I understand. Please give an example, with what you entered, what you expected and what you saw. Also show what you buffer looks like before and after. Thanks.

**Comment by johnwcowan** [comment] 2017-04-28 14:56
I tried to replicate this in a small case, but without success: apparently the regression is only partial.  I'll try to capture it in the wild.  In pre-7.0 versions it was quite consistent:  adding lines to an empty file with successive a commands, followed by a u command, would leave one with an empty buffer again.

**Comment by lacygoill** [comment] 2020-06-17 09:09
I can't reproduce:

    ex -Nu NONE
    :a
    aaa
    .
    :a
    bbb
    .
    :c
    ccc
    .
    :undo
    :%p


![gif](https://user-images.githubusercontent.com/8505073/84878966-e27c6500-b08a-11ea-8d45-8eb1a84d57be.gif)

The last `%p` correctly prints 2 lines `aaa` and `bbb`, meaning that `:undo` did not undo all the changes, but only the last one.

**Comment by lacygoill** [comment] 2020-06-17 09:11
If there is a bug, it may need some settings to be triggered; in that case, you need to bisect your config.  See this [faq entry](https://github.com/chrisbra/vim_faq/blob/de424bd8e08bcf0e6b1e0563ee49514dfed926ae/vim_faq.txt#L1153-L1228) for how to do this.

**Comment by chrisbra** [comment] 2020-06-17 09:18
closing then.

**Closed as completed by chrisbra** 2020-06-17 09:18 UTC

**Comment by johnwcowan** [comment] 2020-06-17 20:58
I don't in fact have any config files (no edits to viminfo, no vimrc, no exrc either in my home directory or in /etc) and just use `ex` as-is.  The exact version is 8.1.2292.

I understand not putting dev resources into an intermittent error, but I'm leaving this for the record in case the problem pops up again.
