### ISSUE TITLE
Proposal: change 't<char>' to position afTer the <char> instead before it

### ISSUE THREAD

**Issue by homofortis** [vim/vim#1759] opened 2017-06-09 16:16 UTC
The 'f' and 't' commands are great to quickly position the cursor. The 'f' command is ok but I find the 't' command slightly useless. I never need to position to the character before, even if i need to insert something before I would rather use 'f{char}i'. On the contrary, it frequently happens to change the word after a key character as  '=' or ":", e.g. "color=0xff1212" or "easymove:true". In the last example I would like to quick-position at the first character of the word that has to be changed. The 't' command could do just like that - jump to the character afTer. For example, in the expression "use_phonetic true" the 't{space}' would go to the character 't' of the word "true" and then it will be easy 'cw' to replace "true" with "false".

**Comment by chdiza** [comment] 2017-06-09 16:25
`t` is not useless for everyone else.   If *you* find it useless, then map it to do whatever it is you want it to do instead of breaking it for the rest of us.

**Comment by homofortis** [comment] 2017-06-09 16:40
No need to be negative, it's just a proposal. Instead of lecturing me you could just write "Oh, no it's a great command, I use it all the time for..." and give a specific example, or bring up any other reason.

**Comment by fritzophrenic** [comment] 2017-06-09 16:48
Vim has a very strong history of backwards compatibility. This would be one of the biggest changes possible to the feature that would break EVERY past use of it. It's never going to happen.

"t" placing the cursor *before* something is actually extremely useful. One of the most useful features of Vim, in fact, in my opinion. I use it probably every few minutes while I'm editing code. Perhaps you don't see the use of it because you're stuck on it being used only to move the cursor?

The power of this command is using it as a "combo" with other commands. I'm not sure if you knew, but you can use things like "d" (delete) or "c" (change) in combination with the t movement command. For example, "ct=" will change everything from the cursor to an equal sign or dt< will delete from the cursor to the first '<'.

If you want to go to the character AFTER something, you could also navigate from the end of the line, and use T instead of t.

**Comment by chrisbra** [comment] 2017-06-09 17:50
That is definitely not something that a vi user would expect and would certainly be a controversial change. For your own customization however you can map it to a function or perhaps start getting used to `t/char/e` or similar.
Closing.

**Closed as completed by chrisbra** 2017-06-09 17:50 UTC

**Comment by vim-ml** [comment] 2017-06-10 12:36
On Fri, Jun 9, 2017 at 6:40 PM, reTouche <vim-dev-github@256bit.org> wrote:
> No need to be negative, it's just a proposal. Instead of lecturing me you
> could just write "Oh, no it's a great command, I use it all the time for..."
> and give a specific example, or bring up any other reason.

Chdiza wasn't lecturing. Like Fritzophrenic said, Vim has a very
strong tradition of backwards compatibility, and the t and T commands
have a long tradition of moving the cursor just "one short" of the
corresponding f or F command. For instance, dt. deletes everything up
to, but not including, the next full stop. Similarly vt, (set
character-visual mode up to but not including the next comma) etc. I
use it less often, maybe, than Fritzophrenic, but still quite often;
changing it to mean "one more than the corresponding f or F" would
leave me quite distressed: I would go as far as calling it a
regression bug of major severity in category "unusable-ui, dogfood"
and an off-by-two error.

Best regards,
Tony.

**Comment by vim-ml** [comment] 2017-06-10 13:19
I am happy with the current function of f and t.
But I would like to know how to re-map t (or another char) such that it would it would essentially do f(char)l.  How to do f wait for (char) then do l?

**Comment by vim-ml** [comment] 2017-06-10 13:45
On Sat, Jun 10, 2017 at 3:19 PM, vim-dev ML <vim-dev-github@256bit.org> wrote:
> I am happy with the current function of f and t.
> But I would like to know how to re-map t (or another char) such that it
> would it would essentially do f(char)l. How to do f wait for (char) then do
> l?

I think an <expr> mapping using the getchar() function would do the trick.

See

        :help :map-<expr>
        :help getchar()

"The actual implementation is left as an exercise to the student."

Best regards,
Tony.

**Comment by vim-ml** [comment] 2017-06-10 18:23
On Saturday, June 10, 2017 at 6:45:55 AM UTC-7, Tony Mechelynck wrote:
> On Sat, Jun 10, 2017 at 3:19 PM, vim-dev ML <vim-dev-github@256bit.org> wrote:
> > I am happy with the current function of f and t.
> > But I would like to know how to re-map t (or another char) such that it
> > would it would essentially do f(char)l. How to do f wait for (char) then do
> > l?
> 
> I think an <expr> mapping using the getchar() function would do the trick.
> 
> See
> 
>         :help :map-<expr>
>         :help getchar()
> 
> "The actual implementation is left as an exercise to the student."
> 
> Best regards,
> Tony.

Thank you Tony for the :help

This works for the first instance, but ; only repeats the f part as per documentation.  Is there a way to repeat this version of t?

nnoremap <expr> t "f" . nr2char(getchar()) . "l"

Why are posts repeated by "vim-dev ML"?
I have not made a "Reply" is a looong time, something has changed.

**Comment by horse-latitudes** [comment] 2017-06-10 19:21
I also get the ML repeats. I'm not subscribed to any Vim issue on GitHub so I'm at a loss to explain it...

**Comment by ZyX-I** [comment] 2017-06-10 21:13
“Vim-dev ML” is a bot which

1. Reposts new issues and comments from github to vim-dev mailing list.
2. Reposts answers to the reposted issues which come from the mailing list to the github issue.

If you post answers via the mailing list then comment made when reposting answer from the mailing list gets reposted back to the mailing list as a comment.
