### ISSUE TITLE
Configured mapping for key `§` no longer detected (French keyboard)

### ISSUE THREAD

**Issue by Melandel** [vim/vim#13468] opened 2023-11-01 10:43 UTC
### Steps to reproduce

1. open `gvim.exe` (x64)
2. type `:inoremap § hello`
3. type `:nnoremap § :echomsg 'hello'<CR>`
4. type `:cnoremap § <C-U>echomsg 'hello'`
5. try these mappings in insert, normal & command mode

### Expected behaviour

* In insert mode, typing the `§` key should display `hello`
* In normal mode, typing the `§` key should echo `hello`
* In command mode, typing the `§` key should change the command to `echomsg 'hello'`

### Actual behaviour

* In insert mode, typing the `§` key actually writes `§`
* In normal mode, typing the `§` key actually rings the bell sound
* In command mode, typing the `§` key actually writes `§`

### Version of Vim

9.0.2081

### Environment

gvim_x64 on Windows 10

### Additional Information
`i/n/cnoremap §` commands had the expected behaviour up until [gvim_8.2.4803_x64](https://github.com/vim/vim-win32-installer/releases/tag/v8.2.4803) included, and their behaviour changed starting with [gvim_8.2.4807_x64](https://github.com/vim/vim-win32-installer/releases/tag/v8.2.4807)

**Comment by k-takata** [comment] 2023-11-01 10:53
I think this is a duplicate of #12595.
This is addressed in #12752.

**Comment by chrisbra** [comment] 2023-11-01 10:59
yes, closing as duplicate #12595

**Closed as not planned by chrisbra** 2023-11-01 10:59 UTC
Labels: duplicate, platform-windows, bug
