### ISSUE TITLE
add lua output to xxd

### ISSUE THREAD

**Issue by yuvalif** [vim/vim#15685] opened 2024-09-15 13:40 UTC
Problem: currently xxd can only output C code
Soution: would like to add an option to output Lua code. other parameters: variable name, capitalization, number of columns etc. should be used in a similar way.

**Comment by chrisbra** [comment] 2024-09-16 13:21
If you are planning to do a PR, there is no need to create an issue first. So let me close this one here as duplicate of #15686

**Closed as not planned by chrisbra** 2024-09-16 13:21 UTC
Labels: enhancement
