### ISSUE TITLE
There is not easy way to close popup after bd in terminal popup

### ISSUE THREAD

**Issue by wsdjeg** [vim/vim#6516] opened 2020-07-22 23:48 UTC
1. run terminal in popup
2. switch to normal mode
3. run `bd!`

what happened? the popup is still focued, But the buffer is normal buffer. and we can not use `:q` or `:close`. but why we can use them in popup terminal?

**Comment by bfrg** [comment] 2020-07-23 07:45
You can run `call popup_close(win_getid())` to close the popup window.

**Comment by brammool** [comment] 2020-07-23 12:51
Wang Shidong wrote:

> 1. run terminal in popup
> 2. switch to normal mode
> 3. run `bd!`
> 
> 
> what happened? the popup is still focued, But the buffer is normal
> buffer. and we can not use `:q` or `:close`. but why we can use them
> in popup terminal?

I get a "not allowed in popup" error.
Please give the exact steps you use to reproduce this.

-- 
hundred-and-one symptoms of being an internet addict:
66. You create a homepage with the impression to cure the afflicted...but
    your hidden agenda is to receive more e-mail.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by wsdjeg** [comment] 2020-07-23 15:38
1. open terminal in popup windows
2. press `<c-\><c-n>` to switch to normal mode
3. press `:close` or `:q` is ok

but:

1. open terminal in popup windows
2. press `<c-\><c-n>` to switch to normal mode
3. press `:bd!`, then the popup buffer will be changed to previews buffer
4. then press `:close` or `:q` is not allowed.

**Comment by bfrg** [comment] 2020-07-23 15:42
Which Vim version?

**Comment by lacygoill** [comment] 2020-07-24 17:40
> press :bd!, then the popup buffer will be changed to previews buffer

It looks like a bug; `:bd` should raise `E994`:

    E994: Not allowed in a popup window

I can't reproduce on Linux, neither in a terminal nor in the GUI, but it may be a bug specific to Windows (and maybe to the GUI), because according to the report #6474, you use gVim on Windows 7.  If such a bug exists, I doubt it has been fixed, since you said you were using 8.2.1266 in the report #6511, which is probably recent enough (although you could try to make sure and check whether you can reproduce on master).

In any case, to close the popup window, try one of these two commands:

    :call win_getid()->popup_close()

    :call popup_clear(1)

**Comment by lacygoill** [comment] 2020-12-14 06:23
> Please give the exact steps you use to reproduce this.

> Which Vim version?

@wsdjeg Any update?

**Comment by chrisbra** [comment] 2020-12-14 07:49
no update, so closing.

**Closed as completed by chrisbra** 2020-12-14 07:49 UTC
Labels: enhancement
