### ISSUE TITLE
maximize window using keyboard on Win 10

### ISSUE THREAD

**Issue by alan-isaac** [vim/vim#2761] opened 2018-03-27 16:20 UTC
The standard Win 10 keystroke combination to maximize a window (Win key + up arrow) is not recognized by Vim 8.  (The Win key + down arrow to shrink a window is however recognized.)

**Comment by chrisbra** [comment] 2018-03-27 19:55
Cannot reproduce. Works perfectly with vim 8.0.1451

**Comment by alan-isaac** [comment] 2018-03-28 20:39
Confirm that today I cannot reproduce it either.  I will report back if I can find the conditions under which the problem occurs.  (This is not a hardware issue (e.g., sticky key); all other apps were responding normally.)

**Comment by chrisbra** [comment] 2018-03-31 14:41
closing then.

**Closed as completed by chrisbra** 2018-03-31 14:41 UTC
