### ISSUE TITLE
E730 when evaluating within loop within function

### ISSUE THREAD

**Issue by igbanam** [vim/vim#13635] opened 2023-12-05 18:17 UTC
### Steps to reproduce

1. Have the "reason.vim" file in your directory
2. Run `vim --clean +'so ./reason.vim'
3. Notice '12' echoed
4. Now uncomment the commented out lines
5. Run (2) again

**reason.vim**
```vim
vim9script

# def Trebuchet(the_input: string): void
  var calibrations: list<number> = []

  for line in ['1this2\n']
    var digits = []
    line->substitute('\d', '\=digits->add(submatch(0))', 'g')
    calibrations->add((digits[0] .. digits[-1])->str2nr())
  endfor

  echo calibrations->reduce((sum, num) => sum + num, 0)
# enddef

# Trebuchet('/input/example.txt')

defcompile
```

### Expected behaviour

Expected nothing to change since the logic is not affected. But for some reason, I get E730

### Version of Vim

9.0 with patch 1-2100

### Environment

Operating System: Mac OS
Terminal: iTerm
Value of $TERM: xterm-256color-italic
Shell: ZSH

**Comment by chrisbra** [comment] 2023-12-11 17:28
it seems correct however. I suppose in script-context, the function is not compiled and therefore the error is not noticed, but the `digits->add()` function returns a list, which will then be fed to the `\=` expression of the  `substitute()` function.

I think you should either add an explicit `string()` or `join()` around the `digits->add()` expression to make sure you are handling strings properly.

**Comment by vaisx05** [comment] 2023-12-29 04:36
## code:

let calibrations = []
for line in ['1this2\n']
    call add(calibrations, join(map(split(line, '\zs'), 'string(v:val)'), ''))
endfor
echo calibrations

try to use the above code instead of previous one to get the expected output.

**Comment by vaisx05** [comment] 2023-12-29 04:37
> ### Steps to reproduce
> 1. Have the "reason.vim" file in your directory
> 2. Run `vim --clean +'so ./reason.vim'
> 3. Notice '12' echoed
> 4. Now uncomment the commented out lines
> 5. Run (2) again
> 
> **reason.vim**
> 
> ```viml
> vim9script
> 
> # def Trebuchet(the_input: string): void
>   var calibrations: list<number> = []
> 
>   for line in ['1this2\n']
>     var digits = []
>     line->substitute('\d', '\=digits->add(submatch(0))', 'g')
>     calibrations->add((digits[0] .. digits[-1])->str2nr())
>   endfor
> 
>   echo calibrations->reduce((sum, num) => sum + num, 0)
> # enddef
> 
> # Trebuchet('/input/example.txt')
> 
> defcompile
> ```
> 
> ### Expected behaviour
> Expected nothing to change since the logic is not affected. But for some reason, I get E730
> 
> ### Version of Vim
> 9.0 with patch 1-2100
> 
> ### Environment
> Operating System: Mac OS Terminal: iTerm Value of $TERM: xterm-256color-italic Shell: ZSH
> 
> ### Logs and stack traces
> _No response_

### code:
let calibrations = []
for line in ['1this2\n']
call add(calibrations, join(map(split(line, '\zs'), 'string(v:val)'), ''))
endfor
echo calibrations

try to use the above code instead of previous one to get the expected output.

**Comment by chrisbra** [comment] 2023-12-29 09:30
let me close this as not a bug

**Closed as not planned by chrisbra** 2023-12-29 09:30 UTC
Labels: bug
