### ISSUE TITLE
End and Home keys not usage after :set ttymouse=urxvt

### ISSUE THREAD

**Issue by GoogleCodeExporter** [vim/vim#316] opened 2015-08-18 21:09 UTC
```
What steps will reproduce the problem?
1. Use urxvt terminal
2. open vim and :set ttymouse=urxvt
3. type Home or End button

What is the expected output? What do you see instead?
Cursor should go at the end of line or beginning of line

What version of the product are you using? On what operating system?
2:7.3.429-2ubuntu2.1
on ubuntu 12.04

Please provide any additional information below.
* If I :set ttymouse=xterm2 the Home and End buttons work fine but I have the 
mouse issue after the 223rd column.
* It seems there is only Home and End button not working with ttymouse=urxvt
* "End" binding on ttymouse=xterm2:"[8~"
* "End" binding on ttymouse=urxvt :"^[[8~"
* Workaround:
map ^[[8~ <End>                                                                 

map ^[[7~ <Home>                                                                





```

Original issue reported on code.google.com by `mich...@gmail.com` on 14 Jan 2015 at 4:51

**Comment by lacygoill** [comment] 2020-06-11 13:27
*I don't think the author of an issue automatically created by GoogleCodeExporter is notified but just in case...*

I can't reproduce; neither on master, nor on 7.3.429; with or without any extra config.

Pressing `<Home>` correctly moves the cursor at the start of the line, while pressing `<End>` moves the cursor at the end of the line.

Could it be an issue in the terminfo description of your terminal?

On Ubuntu, you can try to update the latter by installing the `ncurses-base` and `ncurses-term` packages:

    $ sudo aptitude install ncurses-base ncurses-term

If that doesn't help; you may need to update right from the ncurses developer website:

    $ curl -LO http://invisible-island.net/datafiles/current/terminfo.src.gz
    $ gunzip terminfo.src.gz
    $ tic -sx -e $TERM terminfo.src

Also, make sure that the terminal does not lie to Vim about its identity.
`$TERM` should contain `rxvt`; well, maybe it's not really necessary, but it may help.

    :echo $TERM

On my machine, this command outputs `rxvt-unicode-256color`.  That's because I set the `URxvt.termName` resource in `~/.Xresources` like this:

    URxvt.termName: rxvt-unicode-256color

FWIW, here are [my notes](https://github.com/lacygoill/wiki/blob/master/terminal/database.md) on the subject.

---

If that doesn't help, you may need to update urxvt.  My version is 9.22.
I compiled it from source, and applied some patches.  Here are [my notes](https://github.com/lacygoill/wiki/blob/master/urxvt.md#by-compiling) on the subject.

**Comment by lacygoill** [comment] 2020-06-11 13:29
Also, try without any extra config:

    vim -Nu NONE +'set ttymouse=urxvt' /path/to/some/file

**Comment by chrisbra** [comment] 2020-06-11 13:37
so let's close it then.

**Closed as completed by chrisbra** 2020-06-11 13:37 UTC
Labels: Priority-Medium, defect, auto-migrated
