### ISSUE TITLE
Problems with indenting comments in ``rst`` document

### ISSUE THREAD

**Issue by mcepl** [vim/vim#5142] opened 2019-10-29 23:13 UTC
**Describe the bug**
With ``formatoptions=1jtroqlaw`` and ``comments=fb:..`` for ``rst`` text (which seems to be correct ``comments`` settings IMHO) both vim and neovim doesn’t indent the comments, so instead of

```rst
.. FIXME Start working on wards, suddenly Petunia with Dudley 
   arrives
```

I get

```rst
.. FIXME Start working on wards, suddenly Petunia with Dudley 
arrives
```

Moreover, vim is rather weird state, where I cannot insert space before the arrives word (just nothing happens), and even when I force there space with ``Ctrl-V<space>`` it gets removed on next ``gqap``.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run `vim --clean filename.rst`
2. Set configuration:
```vim
set listchars=tab:▸\ ,trail:·,precedes:←,extends:→,eol:↲,nbsp:␣
set formatoptions=1jtroqlaw
set comments=fb:..
set tw=65
```
3. Write the above shown comment (longer than ``textwidth``)

**Expected behavior**
Second line should be indented, but it isn’t.

**Screenshots**

![Snímek z 2019-10-29 23-15-18](https://user-images.githubusercontent.com/198999/67816175-70c6bb00-faa9-11e9-8c92-4fd0354363ad.png)

(the first comment is wrong, the second (multiparagraph one) is right (fixed with temporary ``set paste``))

**Environment (please complete the following information):**
 - Vim version: both Bram’s vim 8.1 (2018 May 18), 1-2148, and neovim built from the master branch commit https://github.com/neovim/neovim/commit/5a212a96a6d784c9d62eee2bbca525ff0f815061 (post 0.4.2)
 - OS: openSUSE/Tumbleweed
 - Terminal: GNOME Terminal, 3.34.2 (but was able to reproduce it a long time ago)

Probably of interest to @marshallward

**Comment by nickspoons** [comment] 2019-10-29 23:16
This appears to be caused by the 'indentexpr' in `$VIMRUNTIME/indent/rst.vim`. Running `:set indentexpr=` restores the comment indentation.

**Comment by mcepl** [comment] 2019-10-29 23:19
> This appears to be caused by the 'indentexpr' in `$VIMRUNTIME/indent/rst.vim`. Running `:set indentexpr=` restores the comment indentation.

Except it probably breaks indentation elsewhere (there is a reason, why there is ``rst``-specific indenting function, right?). Hmm, why is ``indentexpr`` set to function for *folding*?

**Comment by nickspoons** [comment] 2019-10-29 23:25
> Except it probably breaks indentation elsewhere

Probably, I was just tracking down where the error lies.

> Hmm, why is indentexpr set to function for folding?

? `$VIMRUNTIME/indent/rst.vim` contains `setlocal indentexpr=GetRSTIndent()` and also defines `function GetRSTIndent()`, there's no folding there.

**Comment by mcepl** [comment] 2019-10-29 23:28
> ? `$VIMRUNTIME/indent/rst.vim` contains `setlocal indentexpr=GetRSTIndent()` and also defines `function GetRSTIndent()`, there's no folding there.

Right, my mistake. Sorry. But hopefully not important for this ticket.

**Comment by chrisbra** [comment] 2019-10-30 07:20
can you please contact the maintainer of the indent script?

**Comment by mcepl** [comment] 2019-10-30 07:21
@chrisbra That’s what I did (see above link to vim-restructuredtext repo ticket).

**Comment by chrisbra** [comment] 2019-10-30 07:28
ah missed that. Closing here then.

**Closed as completed by chrisbra** 2019-10-30 07:28 UTC
Labels: runtime

**Comment by mcepl** [comment] 2019-10-30 07:38
@chrisbra Well, this should be really closed only when the fix transfers from that repository to this one.

**Comment by chrisbra** [comment] 2019-10-30 07:48
Let's talk about this, when the open issue count is below 200. It's already way too much effort for the few of us to handle the issues here and try to have resolved issues closed. And after all, it is an upstream issue and we won't see anything happen here.

**Comment by mcepl** [comment] 2019-10-30 07:49
Couldn’t you have some label like "Upstreamed" or something?

**Comment by marshallward** [comment] 2019-10-30 18:03
@mcepl has opened https://github.com/marshallward/vim-restructuredtext/issues/43 to continue this discussion.  We will try to address the problem over there and push any potential fixes back to vim.

I've never looked at any of the indent script code before, so I hope that others with more experience will have a look if possible.

**Comment by chrisbra** [comment] 2019-10-30 19:22
sure, if you have problems, feel free to ask

**Comment by mcepl** [comment] 2019-12-18 10:15
@chrisbra OK, I tried
```diff
diff --git a/indent/rst.vim b/indent/rst.vim
index c1ef8c9..940c869 100644
--- a/indent/rst.vim
+++ b/indent/rst.vim
@@ -18,6 +18,16 @@ endif
 
 let s:itemization_pattern = '^\s*[-*+]\s'
 let s:enumeration_pattern = '^\s*\%(\d\+\|#\)\.\s\+'
+let s:note_pattern = '^\.\. '
+
+function parastart()
+    let l:blnum = search('^\s*$', 'bcnW')
+    if l:blnum == 0
+        return 0
+    else
+        return l:blnum + 1
+    endif
+endfunction
 
 function GetRSTIndent()
   let lnum = prevnonblank(v:lnum - 1)
@@ -28,6 +38,13 @@ function GetRSTIndent()
   let ind = indent(lnum)
   let line = getline(lnum)
 
+  let psnum = parastart()
+  if psnum != 0
+      if getline(psnum) =~ s:note_pattern
+          return 3
+      endif
+  endif
+
   if line =~ s:itemization_pattern
     let ind += 2
   elseif line =~ s:enumeration_pattern
```
But I don’t see any difference. What I am doing wrong?

**Comment by chrisbra** [comment] 2019-12-18 14:39
You don't give very much details. How did you test? What did you expect?
I don't have any rst files lying around to test, so I basically have to guess:

- The parastart() function needs to be `s:parastart()` (or start with an upper case)?
- That parastart() function returns 0 for the beginning of the file

So does this make any difference:

```patch
diff --git a/runtime/indent/rst.vim b/runtime/indent/rst.vim
index c1ef8c995..115af5681 100644
--- a/runtime/indent/rst.vim
+++ b/runtime/indent/rst.vim
@@ -18,6 +18,22 @@ endif

 let s:itemization_pattern = '^\s*[-*+]\s'
 let s:enumeration_pattern = '^\s*\%(\d\+\|#\)\.\s\+'
+let s:note_pattern = '^\.\. '
+
+function s:parastart()
+    let blnum = search('^\s*$\|\%^', 'bcnW')
+    if blnum == 0
+        return 0
+    else
+        let line = getline(blnum)
+        if line =~ '^\s*$'
+          return blum + 1
+        else
+          " start of file
+          return blnum
+        endif
+    endif
+endfunction

 function GetRSTIndent()
   let lnum = prevnonblank(v:lnum - 1)
@@ -27,6 +43,11 @@ function GetRSTIndent()

   let ind = indent(lnum)
   let line = getline(lnum)
+  let psnum = s:parastart()
+  if psnum != 0 && getline(psnum) =~ s:note_pattern
+      return 3
+  endif
+

   if line =~ s:itemization_pattern
     let ind += 2
```

**Comment by mcepl** [comment] 2019-12-18 14:47
Sorry, I have found other way (https://github.com/marshallward/vim-restructuredtext/pull/49), thank you for your effort.
