### ISSUE TITLE
`:w` causes &fdm to change from 'diff' to 'manual'

### ISSUE THREAD

**Issue by chdiza** [vim/vim#11869] opened 2023-01-22 16:58 UTC
### Steps to reproduce

At the commandline start Vim in diff mode: vim -d foo bar.  I did this with two files that had a lot of folding shown because they are mostly identical.  Do `:se fdm?` to verify that it's "diff".

In the buffer on the left, do `:w`.  Suddenly all the folds in that buffer become open, and `&fdm` becomes "manual". 

### Expected behaviour

I expected `&fdm` to remain at "diff" and for no folds to open.

I have no time to git bisect at the moment, so hopefully someone has an idea of which patch might've broken it.

### Version of Vim

9.0.1227

### Environment

Ubuntu 20.04; The terminal is kitty.

**Comment by chrisbra** [comment] 2023-01-23 08:13
I cannot seem to reproduce this:
```bash
~/code-vim/src$ ./vim --clean  -c ':w!' -c ':set fdm?' -d  ~/temp/seq_1_20*
"~/temp/seq_1_20.txt" 20L, 51B written
  foldmethod=diff
~/code-vim/src$ ./vim --version
:version
VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Jan 23 2023 09:09:43)
Included patches: 1-1234
Compiled by Christian Brabandt <cb@256bit.org>
[...]
~/code-vim/src$ 
```

Can you verify this using `--clean`?

**Comment by brammool** [comment] 2023-01-23 21:41
> ### Steps to reproduce
> 
> At the commandline start Vim in diff mode: vim -d foo bar.  I did this
> with two files that had a lot of folding shown because they are mostly
> identical.  Do `:se fdm?` to verify that it's "diff".
> 
> In the buffer on the left, do `:w`.  Suddenly all the folds in that buffer become open, and `&fdm` becomes "manual". 
> 
> ### Expected behaviour
> 
> I expected `&fdm` to remain at "diff" and for no folds to open.
> 
> I have no time to git bisect at the moment, so hopefully someone has an idea of which patch might've broken it.
> 
> ### Version of Vim
> 
> 9.0.1227

I also cannot reproduce this.  I suspect some mapping or plugin
interferes.  As Christian suggested use "vim --clean -d foo bar".
You could also do this, it might give a hint about where 'foldmethod'
was changed:
	:verbose set fdm?

-- 
Never overestimate a man's ability to underestimate a woman.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment] 2023-02-03 12:32
I am closing this as not reproducible.

**Closed as completed by chrisbra** 2023-02-03 12:32 UTC
Labels: bug

**Comment by chdiza** [comment] 2023-02-03 18:17
Sorry, I'll reopen if I can repro it reliably.
