### ISSUE TITLE
Makefile:3174: recipe for target 'objects/crypt.o' failed

### ISSUE THREAD

**Issue by coeoo** [vim/vim#10883] opened 2022-08-10 06:40 UTC
### Steps to reproduce

I installed the latest vim-debian-2%9.0.0135-1 version on the debian8 system.

 First, I tried "make" to compile the source code, and then generated the vim executable in the "src" directory. Can successfully run vim 9.0.0135-1

Next I tried to do dpkg-buildpackages, but got an error 

gcc -std=gnu99 -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libpng12 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng12 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/freetype2    -O2 -fno-strength-reduce -Wall -Wno-deprecated-declarations  -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        -o objects/crypt.o crypt.c
crypt.c:138:2: error: ‘crypto_pwhash_argon2id_SALTBYTES’ undeclared here (not in a function)
  crypto_pwhash_argon2id_SALTBYTES, // 16
  ^
crypt.c:163:5: error: unknown type name ‘crypto_secretstream_xchacha20poly1305_state’
     crypto_secretstream_xchacha20poly1305_state
     ^
crypt.c: In function ‘crypt_sodium_init’:
crypt.c:879:5: warning: implicit declaration of function ‘crypto_pwhash’ [-Wimplicit-function-declaration]
     if (crypto_pwhash(dkey, sizeof(dkey), (const char *)key, STRLEN(key), salt,
     ^
crypt.c:880:2: error: ‘crypto_pwhash_OPSLIMIT_INTERACTIVE’ undeclared (first use in this function)
  crypto_pwhash_OPSLIMIT_INTERACTIVE, crypto_pwhash_MEMLIMIT_INTERACTIVE,
  ^
crypt.c:880:2: note: each undeclared identifier is reported only once for each function it appears in
crypt.c:880:38: error: ‘crypto_pwhash_MEMLIMIT_INTERACTIVE’ undeclared (first use in this function)
  crypto_pwhash_OPSLIMIT_INTERACTIVE, crypto_pwhash_MEMLIMIT_INTERACTIVE,
                                      ^
crypt.c:881:2: error: ‘crypto_pwhash_ALG_DEFAULT’ undeclared (first use in this function)
  crypto_pwhash_ALG_DEFAULT) != 0)
  ^
crypt.c: In function ‘crypt_sodium_buffer_encode’:
crypt.c:1050:6: error: ‘crypto_secretstream_xchacha20poly1305_TAG_FINAL’ undeclared (first use in this function)
    ? crypto_secretstream_xchacha20poly1305_TAG_FINAL  : 0;
      ^
crypt.c:1055:25: error: ‘crypto_secretstream_xchacha20poly1305_ABYTES’ undeclared (first use in this function)
     length = (int)len + crypto_secretstream_xchacha20poly1305_ABYTES
                         ^
crypt.c:1056:18: error: ‘crypto_secretstream_xchacha20poly1305_HEADERBYTES’ undeclared (first use in this function)
       + (first ? crypto_secretstream_xchacha20poly1305_HEADERBYTES : 0);
                  ^
crypt.c:1067:2: warning: implicit declaration of function ‘crypto_secretstream_xchacha20poly1305_init_push’ [-Wimplicit-function-declaration]
  crypto_secretstream_xchacha20poly1305_init_push(&sod_st->state,
  ^
crypt.c:1072:5: warning: implicit declaration of function ‘crypto_secretstream_xchacha20poly1305_push’ [-Wimplicit-function-declaration]
     crypto_secretstream_xchacha20poly1305_push(&sod_st->state, ptr,
     ^
crypt.c: In function ‘crypt_sodium_buffer_decode’:
crypt.c:1109:2: warning: implicit declaration of function ‘crypto_secretstream_xchacha20poly1305_init_pull’ [-Wimplicit-function-declaration]
  if (crypto_secretstream_xchacha20poly1305_init_pull(&sod_st->state,
  ^
crypt.c:1115:10: error: ‘crypto_secretstream_xchacha20poly1305_HEADERBYTES’ undeclared (first use in this function)
  from += crypto_secretstream_xchacha20poly1305_HEADERBYTES;
          ^
crypt.c:1119:5: warning: implicit declaration of function ‘crypto_secretstream_xchacha20poly1305_pull’ [-Wimplicit-function-declaration]
     if (crypto_secretstream_xchacha20poly1305_pull(&sod_st->state,
     ^
crypt.c:1126:16: error: ‘crypto_secretstream_xchacha20poly1305_TAG_FINAL’ undeclared (first use in this function)
     if (tag == crypto_secretstream_xchacha20poly1305_TAG_FINAL && !last)
                ^
Makefile:3174: recipe for target 'objects/crypt.o' failed
make[1]: *** [objects/crypt.o] Error 1
make[1]: Leaving directory '/tmp/vim-debian-2%9.0.0135-1/src'
Makefile:2050: recipe for target 'reconfig' failed
make: *** [reconfig] Error 2

I did not get an error when I executed make
![image](https://user-images.githubusercontent.com/68361024/183832187-3d105145-795c-4a7b-98d5-e7d7ab4326e4.png)

### Expected behaviour

The deb package was successfully generated

### Version of Vim

vim-debian-2%9.0.0135-1

### Environment

debian 8

**Comment by chrisbra** [comment] 2022-08-10 06:44
I think your linker flags did not include `sodium`.  Not sure how this happens. You should check configure and either enable libsodium feature if you want it (and make sure to have it installed) or disable libsodium

**Comment by Collins-Leo** [comment] 2022-08-10 07:26
> I think your linker flags did not include `sodium`. Not sure how this happens. You should check configure and either enable libsodium feature if you want it (and make sure to have it installed) or disable libsodium

sorry i don't understand libnaid

**Comment by jamessan** [comment] 2022-08-11 02:14
> Next I tried to do dpkg-buildpackages, but got an error

This isn't really the right place to debug problems you're having using distribution tools.  The [debian-mentors](https://lists.debian.org/debian-mentors/) or [debian-user](https://lists.debian.org/debian-user/) mailing lists may be better.  There's also the [new maintainer's guide](https://www.debian.org/doc/manuals/maint-guide/) which gives a general overview of packages and how to build them.

As far as the error you're seeing, it's likely due to not having the required dependencies installed, as Christian mentioned.  You can use `sudo apt-get build-dep vim` to install them.

**Comment by Collins-Leo** [comment] 2022-08-11 05:21
> 
Thanks for your answer, I am a new developer and will try to use debian-mentors or debian-user to ask questions later.

I used sudo apt-get build-dep vim and installed some dependencies. Finally, there is no prompt dependency problem.

But when I continue to execute dpkg-buildpackages, there is still a problem with the file crypy.c.

![image](https://user-images.githubusercontent.com/68361024/184069119-b8bb26bb-f3e3-46c9-b329-4a6c1d1d7fcf.png)

**Comment by chrisbra** [comment] 2022-08-11 06:11
You need to check the configure log. There is a check for libsodium and that should actually fail so that make does not try to include the libsodium feature. Also you may want to run make distclean, just to start from a clean state.

**Comment by Collins-Leo** [comment] 2022-08-11 06:31
> 
When using dpkg-buildpackages there is a dh_clean command which cleans up previous installations.

I found. The make at the beginning can be successfully compiled. When I execute dpkg-buildpackages, I will get the same error as executing dpkg-buildpackages when I execute make.

Then I redownloaded the source package and recompiled. It is still found to be wrong.

I suspect that a downloaded dependency package broke my system dependencies.

After I restore through the virtual machine snapshot function, re-execution of make can be successful again. So the problem is the dependency problem I installed, because the dependency problem will be prompted when dpkg-buildpackages is packaged. So I just installed it.

**Comment by chrisbra** [comment] 2022-08-11 06:54
There is either a dependency problem of the Debian package (which I doubt), or some problem with your system. I don't think this is a vim issue here. So let's close it. If you suspect there is something wrong with the debian dependencies, please check James' mentioned resources and try to validate your steps over there. 

Thanks

**Comment by Collins-Leo** [comment] 2022-08-11 07:07
> There is either a dependency problem of the Debian package (which I doubt), or some problem with your system. I don't think this is a vim issue here. So let's close it. If you suspect there is something wrong with the debian dependencies, please check James' mentioned resources and try to validate your steps over there.
> 
> Thanks

![image](https://user-images.githubusercontent.com/68361024/184081133-d9bcce66-cdc5-46c6-889e-fb28646fa088.png)

**Comment by chrisbra** [comment] 2022-08-11 07:20
so try installing libsodium-dev then :)

**Comment by Collins-Leo** [comment] 2022-08-11 07:29
> so try installing libsodium-dev then :)

Yes. You're right. When I installed libsodium-dev, the above error popped up.

This is the dependency that I need to install when I execute dpkg-buildpackages, including libsodium-dev. It seems that it is the problem of this dependency. I tried removing it in debian/control.

![image](https://user-images.githubusercontent.com/68361024/184084437-bdece664-079b-40af-91df-d10f10c64380.png)

**Comment by chrisbra** [comment] 2022-08-11 07:31
okay, can we please reduce this to plain configure and make without all the debian magic?

**Comment by chrisbra** [comment] 2022-08-11 07:34
I am not sure if there is an actual bug lying here. 
When configure fails to find `libsodium-dev`, `src/auto/config.h` should contain a line

```
/* #define HAVE_SODIUM 1 */
```
so it should be undefined. Then in `src/feature.h` the following test is there:
```
  /*
   * libsodium - add cryptography support
   */
  #if defined(HAVE_SODIUM) && defined(FEAT_BIG)
  # define FEAT_SODIUM
  #endif
```

so `FEAT_SODIUM` should be undefined, which would mean, that in crypt.c the references to the libsodium features should not be included. 

I don't know where this breaks for you.

**Comment by Collins-Leo** [comment] 2022-08-11 09:06
> I am not sure if there is an actual bug lying here. When configure fails to find `libsodium-dev`, `src/auto/config.h` should contain a line
> 
> ```
> /* #define HAVE_SODIUM 1 */
> ```
> 
> so it should be undefined. Then in `src/feature.h` the following test is there:
> 
> ```
>   /*
>    * libsodium - add cryptography support
>    */
>   #if defined(HAVE_SODIUM) && defined(FEAT_BIG)
>   # define FEAT_SODIUM
>   #endif
> ```
> 
> so `FEAT_SODIUM` should be undefined, which would mean, that in crypt.c the references to the libsodium features should not be included.
> 
> I don't know where this breaks for you.

thanks for your help. I chose not to rely on dpkg-buildpackage with libsodium-dev so far to avoid problems with crypt.c.

But I ran into a new problem. I will try to solve it. Thanks for the guidance up front!

**Comment by jamessan** [comment] 2022-08-11 12:35
I just noticed you're trying to build Vim on a Debian 8 system. That release of Debian has been out of support for 4 years now, and doesn't have a new enough version of libsodium to build Vim.

If there's anything actionable from the Vim side here, it's to have configure check for the minimum required libsodium version.

**Closed as completed** 2022-08-15 06:22 UTC
Labels: bug
