### ISSUE TITLE
vim always resets alternate screen

### ISSUE THREAD

**Issue by kovidgoyal** [vim/vim#11717] opened 2022-12-17 11:02 UTC
### Steps to reproduce

1. echo main
2. tput smcup; vim --clean; cat
3. tput rmcup; vim --clean; cat
4. See that we are back at the main screen regardless of whether we start in main screen or alternate screen, that is after both steps 2 and 3 we are in the main screen.

### Expected behaviour

I expect to return to the screen I started in. At least that's what Bram says should be vim's behavior. Personally, I think that is not possible to do robustly and efficiently, but what do I know.

Reference: https://github.com/vim/vim/issues/11705#issuecomment-1354730945

### Version of Vim

9.0.1046

### Environment

Operating system: Arch Linux
Terminal: xterm 377 with TERM=xterm
Shell: zsh 5.9

### Logs and stack traces

```shell
This presumably happens because vim uses the smcup and rmcup capabilities from terminfo to populate t_TI and t_TE. Most (all?) terminals that support smcup and rmcup define them to toggle alternate screen.
```

**Comment by brammool** [comment] 2022-12-17 12:15
I cannot reproduce.  Well, the reproduction steps are unclear, "cat" is not a Vim command.
So what exactly happens after "vim --clean"?
And what is "cat" supposed to do?  Without interaction it just hangs.

If after "vim --clean" I exit Vim I'm back where I started.

**Comment by kovidgoyal** [comment] 2022-12-17 12:55
On Sat, Dec 17, 2022 at 04:15:54AM -0800, Bram Moolenaar wrote:
> I cannot reproduce.  Well, the reproduction steps are unclear, "cat" is not a Vim command.
> So what exactly happens after "vim --clean"?
> And what is "cat" supposed to do?  Without interaction it just hangs.

vim --clean; then exit vim. cat will prevent the shell from running and
interfering with anything.

tput smcup

puts the terminal in alternate screen. Then vim --clean is started. Then vim is
quit and cat is run. At this point you see that you are in main screen,
not alternate screen, as evidenced by the fact that you can see the
commands you typed on the main screen. But when vim was started the
terminal was in alternate screen.

And anyway you dont need a reproducer, inside vim do

:set t_te?

you will see that it contains ^[[1049l now go lookup this escape code in
https://invisible-island.net/xterm/ctlseqs/ctlseqs.html 

You will see that it unconditionally changes from alternate screen back
to main screen. Thus on exit vim will always reset the terminal to main
screen regardless of what screen the terminal started at in xterm (and
every other terminal, but lets use xterm here since you like it).

**Comment by brammool** [comment] 2022-12-17 16:17
> On Sat, Dec 17, 2022 at 04:15:54AM -0800, Bram Moolenaar wrote:
> > I cannot reproduce.  Well, the reproduction steps are unclear, "cat" is not a Vim command.
> > So what exactly happens after "vim --clean"?
> > And what is "cat" supposed to do?  Without interaction it just hangs.
> 
> vim --clean; then exit vim. cat will prevent the shell from running and
> interfering with anything.
> 
> tput smcup
> 
> puts the terminal in alternate screen. Then vim --clean is started.
> Then vim is quit and cat is run. At this point you see that you are in
> main screen, not alternate screen, as evidenced by the fact that you
> can see the commands you typed on the main screen. But when vim was
> started the terminal was in alternate screen.

I still don't see what "cat" is needed for.  Assuming starting in the
main screen, that shows the "tput smcup" command, the alternate screen
doesn't.

> And anyway you dont need a reproducer, inside vim do
> 
> :set t_te?
> 
> you will see that it contains ^[[1049l now go lookup this escape code in
> https://invisible-island.net/xterm/ctlseqs/ctlseqs.html 

No, it doesn't contain this code.  For me the value is:

	t_te=^[[2J^[[?47l^[8

Now you might think this is the value from the builtin xterm termcap,
but it isn't, because FEAT_XTERM_SAVE is not defined.  You can check
that with the version output, which contains "+xterm_save" if it would
be defined, but for me it is "-xterm_save".  And unless you build Vim
yourself and explicitly enabled this feature, you should have
"-xterm_save".

I'm not quite sure where this t_te value comes from...  The value of
$TERM is "xterm-color".  Ah, it's just the terminfo entry "rmcup" for
this terminal.

> You will see that it unconditionally changes from alternate screen back
> to main screen. Thus on exit vim will always reset the terminal to main
> screen regardless of what screen the terminal started at in xterm (and
> every other terminal, but lets use xterm here since you like it).

Well, Vim just does what it has been told to.  The t_te termcap entry is
exactly to allow for the user to control this behavior.  In my .vimrc I
make t_te empty, what other users do is up to them.

-- 
Nothing is impossible for the man who doesn't have to do it.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by kovidgoyal** [comment] 2022-12-18 00:39
On Sat, Dec 17, 2022 at 08:17:28AM -0800, Bram Moolenaar wrote:
> 
> > On Sat, Dec 17, 2022 at 04:15:54AM -0800, Bram Moolenaar wrote:
> > > I cannot reproduce.  Well, the reproduction steps are unclear, "cat" is not a Vim command.
> > > So what exactly happens after "vim --clean"?
> > > And what is "cat" supposed to do?  Without interaction it just hangs.
> > 
> > vim --clean; then exit vim. cat will prevent the shell from running and
> > interfering with anything.
> > 
> > tput smcup
> > 
> > puts the terminal in alternate screen. Then vim --clean is started.
> > Then vim is quit and cat is run. At this point you see that you are in
> > main screen, not alternate screen, as evidenced by the fact that you
> > can see the commands you typed on the main screen. But when vim was
> > started the terminal was in alternate screen.
> 
> I still don't see what "cat" is needed for.  Assuming starting in the
> main screen, that shows the "tput smcup" command, the alternate screen
> doesn't.

The shell could potentially reset the screen. Running cat after vim 
ensures that cannot happen thereby making the reproducer robust.

> 
> > And anyway you dont need a reproducer, inside vim do
> > 
> > :set t_te?
> > 
> > you will see that it contains ^[[1049l now go lookup this escape code in
> > https://invisible-island.net/xterm/ctlseqs/ctlseqs.html 
> 
> No, it doesn't contain this code.  For me the value is:
> 
> 	t_te=^[[2J^[[?47l^[8

And go to https://invisible-island.net/xterm/ctlseqs/ctlseqs.html 
and you will see the ^[[47l also uncoditionally transitions to the main
screen just like ^[[1049l

> Now you might think this is the value from the builtin xterm termcap,
> but it isn't, because FEAT_XTERM_SAVE is not defined.  You can check
> that with the version output, which contains "+xterm_save" if it would
> be defined, but for me it is "-xterm_save".  And unless you build Vim
> yourself and explicitly enabled this feature, you should have
> "-xterm_save".
> 
> I'm not quite sure where this t_te value comes from...  The value of
> $TERM is "xterm-color".  Ah, it's just the terminfo entry "rmcup" for
> this terminal.

And this terminfo causes a transition to the main screen.

> 
> > You will see that it unconditionally changes from alternate screen back
> > to main screen. Thus on exit vim will always reset the terminal to main
> > screen regardless of what screen the terminal started at in xterm (and
> > every other terminal, but lets use xterm here since you like it).
> 
> Well, Vim just does what it has been told to.  The t_te termcap entry is
> exactly to allow for the user to control this behavior.  In my .vimrc I
> make t_te empty, what other users do is up to them.

No one is telling vim what to do. vim is reading t_te from terminfo
rmcup capability. All terminfo's that have this capability reset the
alternate screen in it. Therefore, vim always resets to the main screen
on exit, unless a user goes out of his way to configure it not to, in
contravention of your statement that vim always runs in whatever screen
it was started in. I am simply pointing out that vim is not behaving how
you say it should. What you want to do about it is up to you.

**Comment by zewpo** [comment] 2022-12-18 01:03
I don't think there is any way for Vim to query which screen buffer it was started in, it may be either the main screen buffer or an alternate screen buffer.  Vim typically returns to the 'main' screen buffer on exit, even if it was started in an alternate screen buffer.    

Whatever!  I don't see anyway around this being the default behavior, and users can configure this differently if they wish.

@kovidgoyal   This really feels like a petty point scoring exercise on your part.  What are you actually expecting Vim to do here?  Why does this matter to the keyboard issue?

**Comment by kovidgoyal** [comment] 2022-12-18 01:23
There is a way to query it, use the DECRQM escape code to query to query the 47 and 1049 modes. 

```sh
printf '\x1b[?1049$p\x1b[?47$p'; cat -v;
```

I am expecting vim to do what Bram says it should do, aka respect the screen it was started in. It's technically possible to do that via DECRQM. I dont think its a good idea to do it, but, again, what do I know.

Or Bram needs to retract that statement, which will allow him to realize that vim always resets the screen mode. Therefore there is no problem in also resetting the keyboard mode before resetting the screen mode. Which in turn makes the fix for the keyboard issue trivial.

**Comment by zewpo** [comment] 2022-12-18 01:53
Maybe not trivial, because Vim doesn't always return to the main screen mode on exit for all configurations.  Consider when Vim is nesting a terminal session, hosting another instance of vim running inside that.   It gets complicated.

**Comment by kovidgoyal** [comment] 2022-12-18 02:06
On Sat, Dec 17, 2022 at 05:53:40PM -0800, Christopher Plewright wrote:
> Maybe not trivial, because Vim doesn't always return to the main screen mode on exit for all configurations.  Consider when Vim is nesting a terminal session, hosting another instance of vim running inside that.   It gets complicated.

I dont follow the complication there. If vim is nesting a terminal it
presumably is using a dedicated PTY device to do so, what does that have
to do with the issue? The state of that PTY device has to be managed
completely independently.

**Comment by zewpo** [comment] 2022-12-18 02:25
> Or Bram needs to retract that statement, which will allow him to realize that vim always resets the screen mode.

Yeah, well, it looks like a petty way to go about it.  Expecting someone to retract a statement feels like an ego thing.   Anyway, I find rudeness unhelpful in most situations.  Maybe it's a cultural thing.  I hope it works out the way you want it to in the end.

Keep in mind, @brammool  wrote what he did shortly after you were rudely condescending toward him.   

And, then there's the delicious irony of my ego even suggesting this stuff to you.  You gotta love internet etiquette.

Oh, you are right, PTY provides another layer.  I just did some testing, the nested Vim didn't affect the host Vim.

My example was unhelpful.   But, there are situations where users have set up different configurations where Vim does not return to the main screen buffer.

Thanks for the reference to DECRQM.   My intro to the screen restore issues was on the Windows Terminal side - only about a month ago.    And that does not have any way to query which buffer it started from, at least not that I can find as of yet.   Although, I do see that someone has submitted a PR to Windows Terminal to utilize DECRQM, so that might be doable too sometime in the future.    Anyway, unrelated to the keyboard issue.

Sorry if this is a naive question, but why is the keyboard protocol data tied to which screen-buffer is in use?

**Comment by kovidgoyal** [comment] 2022-12-18 02:40
On Sat, Dec 17, 2022 at 06:25:22PM -0800, Christopher Plewright wrote:
> > Or Bram needs to retract that statement, which will allow him to realize that vim always resets the screen mode.
> 
> Yeah, well, it looks like a petty way to go about it.  Expecting someone to retract a statement feels like an ego thing.   Anyway, I find rudeness unhelpful in most situations.  Maybe it's a cultural thing.  I hope it works out the way you want it to in the end.

So I should just let incorrect reasons to not do something stand? If that's
the way this repo is run that's fine by me. I will simply bow out at
this point. Good luck.

> 
> Keep in mind, @brammool  wrote what he did shortly after you were rudely condescending toward him.   

What?? Point out what I said before the reply I quoted was rudely
condescending?

Here is what I wrote:

Dont randomnly transition screens. There is no usecase for that. At startup always switch to alternate screen. Then enable the keyboard protocol. Whenever vim relinquishes control of the tty, whether that is to run a shell command, suspend itself, or quit, it is incumbent on it to restore the tty to the state it found it in, or if it is not capable of doing that, then to a known good state. Which means you turn off the keyboard protocol and preferably transition back to the main screen before relinquishing control of the tty.

Oh and as far as I can tell for this particular issue, all you need to do is emit the restore keyboard protocol bytes before you emit the switch to main screen bytes when doing :!


> And, then there's the delicious irony of my ego even suggesting this stuff to you.  You gotta love internet etiquette.

Its the internet what do you expect :)

> 
> My example was unhelpful.   But, there are situations where users have set up different configurations where Vim does not return to the main screen buffer.

So in that case emitting the bytes to reset the keyboard protocol
*before* the rest of t_te wont affect anything. And if a user completely
changes t_ti and t_te then the keyboar dprotcol will not have been
enabled at all in the first place.

> Sorry if this is a naive question, but why is the keyboard protocol data tied to which screen-buffer is in use?

Because the keyboard protocol is mostly going to be used by full screen
apps which use the alternate screen. So the alternate screen becomes a
shorthand for setting up various properties. You dont need to reset
individual things every time you transition, unless you want to.

Regardless, that is how the
spec is designed, and by now implemented in multiple places.
vim should support it correctly.

**Comment by zewpo** [comment] 2022-12-18 03:27
No, I enjoy reading your thoughts.   Please don't bow out because of me!   I'm relatively new to this open development stuff, only been involved in this Vim community a couple of months.   It's none of my business how you discuss the issue.   Just adding my 2c for a different perspective.    I hope you feel free to disagree or disregard anything I say, and please don't feel that I am in anyway representative of the tone of this community.  That would be me doing an injustice to this community.  I'm just a noob trying to get involved and contribute.

The thing that I found condescending;
https://github.com/vim/vim/issues/11705#issuecomment-1354978853
> If you insist on using termcap/terminfo in vim maybe you should
> educate yourself about them a little.

But, touchet.   Another mistake of mine.   @brammool  did write his comment before yours.   Don't know why I tried to defend what he said that way.  I guess I was reacting to the tone of your comment.

Also, I appreciate your answer to my question about keyboard state;
> You dont need to reset individual things every time you transition, unless you want to.

To the actual issue, users can configure some screen restore behavior; 

```
			 *'restorescreen'* *'rs'* *'norestorescreen'* *'nors'*
'restorescreen' 'rs'	boolean	(default on)
			global
			{only in MS-Windows console version}
	When set, the screen contents is restored when exiting Vim.  This also
	happens when executing external commands.

	For non-Windows Vim: You can set or reset the 't_ti' and 't_te'
	options in your .vimrc.  To disable restoring:
		set t_ti= t_te=
	To enable restoring (for an xterm):
		set t_ti=^[7^[[r^[[?47h t_te=^[[?47l^[8
	(Where ^[ is an <Esc>, type CTRL-V <Esc> to insert it)
```


You suggest the meat of the issue is in here;

> So in that case emitting the bytes to reset the keyboard protocol
> *before* the rest of t_te wont affect anything. And if a user completely
> changes t_ti and t_te then the keyboar dprotcol will not have been
> enabled at all in the first place.

I wonder if you can really assume that is safe, without knowing what users enter into t_ti and t_te.  Are there zero scenarios where it could be a problem to emit the bytes to reset the keyboard protocol before emitting t_te?   Again, I'm just asking as an interested noob.   I'm not suggesting anything is right or wrong here.

**Comment by kovidgoyal** [comment] 2022-12-18 04:25
On Sat, Dec 17, 2022 at 07:27:51PM -0800, Christopher Plewright wrote:
> No, I enjoy reading your thoughts.   Please don't bow out because of me!   I'm relatively new to this open development stuff, only been involved in this Vim community a couple of months.   It's none of my business how you discuss the issue.   Just adding my 2c for a different perspective.    I hope you feel free to disagree or disregard anything I say, and please don't feel that I am in anyway representative of the tone of this community.  That would be me doing an injustice to this community.  I'm just a noob trying to get involved and contribute.

No worries, it's up to Bram, it's his project. If he doesn't want my
input I am happy to leave. I got involved because Bram asked me to help
test his implementation and I am a vim user myself.

> 
> The thing that I found condescending;
> https://github.com/vim/vim/issues/11705#issuecomment-1354978853
> > If you insist on using termcap/terminfo in vim maybe you should
> > educate yourself about them a little.
> 
> But, touchet.   Another mistake of mine.   @brammool  did write his comment before yours.   Don't know why I tried to defend what he said that way.  I guess I was reacting to the tone of your comment.

My comment was a direct response to this from Bram:

"
 You do know about the relation between terminfo and termcap names,
 right?  They are 1:1, so either can be used to identify an entry.
"

 
> To the actual issue, users can configure some screen restore behavior; 
> 
> ```
> 			 *'restorescreen'* *'rs'* *'norestorescreen'* *'nors'*
> 'restorescreen' 'rs'	boolean	(default on)
> 			global
> 			{only in MS-Windows console version}
> 	When set, the screen contents is restored when exiting Vim.  This also
> 	happens when executing external commands.
> 
> 	For non-Windows Vim: You can set or reset the 't_ti' and 't_te'
> 	options in your .vimrc.  To disable restoring:
> 		set t_ti= t_te=
> 	To enable restoring (for an xterm):
> 		set t_ti=^[7^[[r^[[?47h t_te=^[[?47l^[8
> 	(Where ^[ is an <Esc>, type CTRL-V <Esc> to insert it)
> ```
> 
> 
> You suggest the meat of the issue is in here;
> 
> > So in that case emitting the bytes to reset the keyboard protocol
> > *before* the rest of t_te wont affect anything. And if a user completely
> > changes t_ti and t_te then the keyboar dprotcol will not have been
> > enabled at all in the first place.
> 
> I wonder if you can really assume that is safe, without knowing what users enter into t_ti and t_te.  Are there zero scenarios where it could be a problem to emit the bytes to reset the keyboard protocol before emitting t_te?   Again, I'm just asking as an interested noob.   I'm not suggesting anything is right or wrong here.

I cant think of a scenario where it is an issue. If you can I am all
ears.

Also, beyond a certain point if a user changes low level things like this,
they need to take responsibility for not breaking things. Personally, if
I was designing this, I would remove t_ti and t_te and restorescreen.
There is no use case I know of where it ever makes sense for a full
screen application like vim to not use the alternate screen. At best you
can have an option to dump the contents of the alternate screen to the
main screen on exit. But that's Bram's choice and I dont want to dictate
his design. 

I will however insist that emitting the keyboard state escape codes in
the correct order is both possible, desirable and safe.

What vim is doing here is setting up terminal emulator state by means of
escape codes. The t_ti sequence is

switch to alt screen -> change keyboard mode

the corresponding unwind t_te sequence should be

change keyboard mode -> switch to main screen

In general when doing state transitions A->B->C
the correct way to unwind it is C->B->A. That is because subsequent
states can depend on previous ones.

**Comment by Shane-XB-Qian** [comment] 2022-12-18 04:40
me too, i am just the another noob. :laughing: 
i may think the problem is just the different angle or level or scope, for example @kovidgoyal mentioned `BSU` and `ESU` #11718 such tech actually was a common and used way to reduce flick, but just terminal raw esc level i donot know how it play, and there some exceptions like the case here https://github.com/yegappan/lsp/issues/66#issuecomment-1288450404  such flick looks cannot be solved by such tech.
again, i think there should be some historical reason we cannot change it totally as/per the modern spec, wish to be fixed but not sure which is right or wrong not sure...
// at least this (vim) and that (kitty) is keeping update freq and fast, vs (i would say or blame? :rofl:) gnu-screen 2 years would update a release...

**Comment by zewpo** [comment] 2022-12-18 04:57
@kovidgoyal   thanks for taking the time to explain it for me.   

I'm also following along because I am also trying to deal with issues of Vim working with Windows Terminal using "\033[?1049h"  and  "\033[?1049l".  When using these, it solves a number of issues related to restoring the windows buffer properly when Vim exits.   BUT, these consistently cause some other existing CI Test scripts to fail in the CI test environment.    As of yet, I am still unable to reproduce those failures in any version of Windows,    8, 10, 11 & Server 22.    So, I'm still trying to solve that properly.   

Anyway, I know these details are irrelevant for Kitty, but whatever Bram decides is the correct behavior, I want to make sure we follow that on Windows if we can too.

@Shane-XB-Qian   Thanks :)

**Comment by brammool** [comment] 2022-12-18 11:26
This discussion is drifting off in various directions, therefore I'm going to close it.

For the original problem: If you don't want switching between the alternate and main screen you have to make sure that the t_te and t_ti termcap entries are empty.

Any change in Vim to try and make this work better will cause havoc among users who rely on the current behavior.  And I don't see a real problem with the current behavior anyway.  It may go against what some people expect, sure, but sticking with how it has worked for 20 years is more important.

**Closed as not planned by brammool** 2022-12-18 11:26 UTC
Labels: bug
