### ISSUE TITLE
check_external_diff called too often

### ISSUE THREAD

**Issue by blueyed** [vim/vim#4800] opened 2019-08-12 07:00 UTC
`check_external_diff` is used with `diffexpr` or when `internal` is not in `diffopt`, via  https://github.com/vim/vim/blob/0b5dc644465c549ac54fe3c4ad232dd692000d26/src/diff.c#L816-L818

This is meant to check if the "diff" command is working (in general, and with different options).

However:

1. it does not really make sense for `diffexpr`, which might not use the `diff`
   command in the first place, and then should probably do it's own checking
   anyway.  (only the basic "diff" is checked in that case already, but I think
   even that could be skipped maybe - although it checks if temporary files
   can be created also)

2. there is `diff_a_works` and `diff_bin_works` already, which does those
   specific checks only once.
   Maybe `diff_works` should be added to do the basic check also only once.
   That might not be necessary after all though (see 3).

3. the doc mentions that the exit code cannot be used, but at least GNU diff
   exits with 1 for differences, and 2 when in trouble.

  > Do a quick test if "diff" really works.  Otherwise it looks like there
  > are no differences.  Can't use the return value, it's non-zero when
  > there are differences.

btw: when diffing 3 files with `vim -d` `check_external_diff` is called twice even already,
which can be seen with:

    gdb -ex 'break check_external_diff' -ex 'break diff_file' -ex run --args ./src/vim -Nu NONE --cmd 'set diffopt-=internal' -d 1 2 3

**Comment by chrisbra** [comment] 2019-08-14 08:25
1) Well, the diffexpr might as well use a diff, like in the documentation (search for the `MyDiff` function), so it does make sense to check for a working diff when using a custom diffexpr. (I believe this or something similar was also shipped with windows vim before the internal diff algorithm was available).

2) the check_external_diff does not depend on the return value, but rather on the result of the diff of a predefined input. 

It is true, that the check for a working diff for more than 2 buffers will be executed several times. But is this actual a problem?

**Comment by chrisbra** [comment] 2019-08-16 06:49
In fact, the check for a working diff is always performed before the external command diff is called. I have a feeling this has been discussed before and works as intended. So closing.

**Closed as completed by chrisbra** 2019-08-16 06:49 UTC
