### ISSUE TITLE
ml_get: invalid lnum: 2

### ISSUE THREAD

**Issue by skanehira** [vim/vim#4997] opened 2019-09-29 12:47 UTC
_Instructions: Replace the template text and remove irrelevant text (including this line)_

**Describe the bug**
When I using plugin `https://github.com/liuchengxu/vim-clap` and execute `:Clap files` then happend.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Install vim-clap
2. `:Clap files`

**Expected behavior**
Command can be executed normally without error.

**Screenshots**
![image](https://user-images.githubusercontent.com/7888591/65832713-91f98780-e302-11e9-8937-a0e864d89658.png)

**Environment (please complete the following information):**
 - Vim version 8.1.2100
 - OS: MacOS Mojave
 - Terminal: iTerm2

**Additional context**

**Comment by brammool** [comment] 2019-09-29 15:18
Is there a simpler way to reproduce?  Ideally in the form of a test.

**Comment by chrisbra** [comment] 2019-09-29 17:48
I tried using `vim --clean` and I get a popup with the message `zsh:1: command not found fd`. Interestingly, the popup is not closed after pressing `C-C` or `ESC`. 

@skanehira can you provide a backtrace from gdb? That might give a hint where this is called.

**Comment by liuchengxu** [comment] 2019-09-30 13:13
I did see this before, not only in [vim-clap](https://github.com/liuchengxu/vim-clap), but also in [vista.vim](https://github.com/liuchengxu/vista.vim), especially for some old version of vista.vim in which this error occurs more often. 

For [vista.vim](https://github.com/liuchengxu/vista.vim), please see my previous notes: https://github.com/liuchengxu/vista.vim/blob/d22e847e20/autoload/vista/util.vim#L56-L58 . Basically the symptom is that I want to set the buffer line of some other window, using `s:SetBufline` would cause E315 error more often, the wordaround afterwords is to jump to that window to use `silent 1,$delete _` and `call setline(1, lines)`, and jump back the previous window.

For [vim-clap](https://github.com/liuchengxu/vista.vim), I only seen E315 once or twice, I can't recall it clearly and then I have never seen it again until now.

Unfortunately, I can't reproduce it stably whether in vista.vim or in vim-clap, and I failed to reproduce it with a minimal vimrc :). I'll try to dive into this next time I see it.

Edit: In order to avoid that error in my previous use case, it's better for vim to offer two native apis like `setbuflines(bufnr, lines)` to replace the whole buffer content given the lines, `appendbuflines(bufnr, lines)`, then I don't have to do https://github.com/liuchengxu/vim-clap/blob/f92d951564/autoload/clap/init.vim#L99-L109 and https://github.com/liuchengxu/vim-clap/blob/f92d951564/autoload/clap/init.vim#L121-L129.

**Comment by chrisbra** [comment] 2019-10-02 12:05
I am closing this, since it is not reproducible and vim-clap already changes much.

Please reopen, if you can easily reproduce this. 

@liuchengxu if you come across this error again, please try to reproduce it to a minimal working example and open a new issue, so we can fix this here.

**Closed as completed by chrisbra** 2019-10-02 12:05 UTC
