### ISSUE TITLE
Syntax highlighting doesn't work for Javascript in HTML after jump

### ISSUE THREAD

**Issue by Glench** [vim/vim#5440] opened 2020-01-05 19:29 UTC
**Describe the bug**
Syntax highlighting doesn't work for JavaScript that appears in HTML <script> tags, but only when jumping through the file. 

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run `vim --clean` and open this file: https://github.com/Glench/wiki-category-search/blob/master/test.html
2. press G to scroll to last line
3. Observe the javascript visible on the screen doesn't have any highlighting.
4. now press gg to go back to top of file and scroll down with j until you get javascript 
5. Observe that the javascript now has syntax highlighting, even when scrolling or jumping to bottom of file.

**Expected behavior**
JS in <script> tag should have syntax highlighting.

**Screenshots**
![Screen Shot 2020-01-05 at 2 22 42 PM](https://user-images.githubusercontent.com/451461/71784896-e168e700-2fc6-11ea-8abd-d933837e2f5a.png)
What it should look like:
![Screen Shot 2020-01-05 at 2 28 15 PM](https://user-images.githubusercontent.com/451461/71784947-b4690400-2fc7-11ea-9ad6-08749c91217a.png)

**Environment (please complete the following information):**
OS: Mac OSX Version 10.12.6 (16G1815)
Terminal: Iterm 2 Build 3.3.7
Vim version:
 ```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Dec 17 2019 22:00:16)
macOS version
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl               -farsi             -mouse_sysmouse    -tag_old_static
+arabic            +file_in_path      +mouse_urxvt       -tag_any_white
+autocmd           +find_in_path      +mouse_xterm       -tcl
+autochdir         +float             +multi_byte        +termguicolors
-autoservername    +folding           +multi_lang        +terminal
-balloon_eval      -footer            -mzscheme          +terminfo
+balloon_eval_term +fork()            +netbeans_intg     +termresponse
-browse            +gettext           +num64             +textobjects
++builtin_terms    -hangul_input      +packages          +textprop
+byte_offset       +iconv             +path_extra        +timers
+channel           +insert_expand     +perl              +title
+cindent           +job               +persistent_undo   -toolbar
-clientserver      +jumplist          +popupwin          +user_commands
+clipboard         +keymap            +postscript        +vartabs
+cmdline_compl     +lambda            +printer           +vertsplit
+cmdline_hist      +langmap           +profile           +virtualedit
+cmdline_info      +libcall           -python            +visual
+comments          +linebreak         +python3           +visualextra
+conceal           +lispindent        +quickfix          +viminfo
+cryptv            +listcmds          +reltime           +vreplace
+cscope            +localmap          +rightleft         +wildignore
+cursorbind        +lua               +ruby              +wildmenu
+cursorshape       +menu              +scrollbind        +windows
+dialog_con        +mksession         +signs             +writebackup
+diff              +modify_fname      +smartindent       -X11
+digraphs          +mouse             -sound             -xfontset
-dnd               -mouseshape        +spell             -xim
-ebcdic            +mouse_dec         +startuptime       -xpm
+emacs_tags        -mouse_gpm         +statusline        -xsmp
+eval              -mouse_jsbterm     -sun_workshop      -xterm_clipboard
+ex_extra          +mouse_netterm     +syntax            -xterm_save
+extra_search      +mouse_sgr         +tag_binary
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: clang   -L. -fstack-protector-strong -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl@1.1/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -o vim        -lncurses -liconv -lintl -framework AppKit  -L/usr/local/opt/lua/lib -llua5.3 -mmacosx-version-min=10.12 -fstack-protector-strong -L/usr/local/lib  -L/usr/local/Cellar/perl/5.30.0/lib/perl5/5.30.0/darwin-thread-multi-2level/CORE -lperl -lm -lutil -lc  -L/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/config-3.7m-darwin -lpython3.7m -framework CoreFoundation  -lruby.2.6
```

**Comment by tonymec** [comment] 2020-01-05 19:45
Syntax highlighting usually looks back only a certain number of lines in the file. This is customizable in several ways, see `:help syn-sync` and `:help 'synmaxcol'`.

The only way to make sure that the current file will always be highlighted correctly, no matter how big the embedded conditional clauses, loops and functions and how long the lines, is also the slowest:
```vim
        :syn sync fromstart
        :setlocal synmaxcol=0
```

Best regards,
Tony.

**Comment by Glench** [comment] 2020-01-05 23:04
Hey, thanks for your response. I don't know much about these things, but don't other text editors have syntax strategies that don't make a tradeoff between slowness and highlighting? Even though there's a "fix" you mentioned this still seems like a bug to me that sometimes a feature of the editor doesn't work at all for no explained reason.

**Comment by chrisbra** [comment] 2020-01-06 08:31
not sure what other text editors do. However that's not relevant here. The problem is documented and can be worked around. Closing.

**Closed as completed by chrisbra** 2020-01-06 08:31 UTC

**Comment by Glench** [comment] 2020-01-06 11:42
I’m very grateful to have vim and appreciate your commenting on my bug report, but I’ll also say that just because a bug is documented and there’s a workaround (that significantly impacts the performance) doesn’t mean there isn’t still a bug.

**Comment by chrisbra** [comment] 2020-01-06 18:50
I am not saying this is a bug, it looks like some misconfiguration. Note, that depending on syntax rules (which can get quite complex), it is expected that coloring might get lost in order to be responsive (think of expansive regex rules). Also you might want to check your `redrawtime` setting. 
That file is quite small and I cannot reproduce this. Have you tried a different terminal or perhaps the gui version? Also check your terminal configuration. Is $TERM correctly set? 

Also I am wondering about this:

```
macOS version
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
```

Did you edit this? What exact version is this? Please try with an uptodate version.

**Comment by Glench** [comment] 2020-01-11 22:41
Whoops, forgot the first line of the vim version (which I didn't change from the homebrew installed version): `VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Dec 17 2019 22:00:16)`

More info:
`$ echo $TERM
xterm-256color`

redrawtime=2000

I don't have a gui version of vim. It also happens in the Apple Terminal.app (Version 2.7.5 (388.1.3)). I had to change the source file structure because the highlight bug was so annoying. You can now test with this: https://github.com/Glench/wiki-category-search/blob/master/test.html
