### ISSUE TITLE
Substitution for visual selection (both block and character) should embrace only selected text

### ISSUE THREAD

**Issue by ethouris** [vim/vim#9264] opened 2021-12-03 14:15 UTC
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**

The problem: Imagine you have a text that is intended to be column-oriented, like tables in md:

```
Header  |  Content | Rest
:------ | :------- | :-------
first   |   old    | gold
second  |   old    | folded
```
Now you want to replace in the second column "old" with "new".

If you now mark the contents of the second column with VISUAL BLOCK and do `:substitute` with automatically pasted the range of the block, it will do substitute, but the result will be:

```
Header  |  Content | Rest
:------ | :------- | :-------
first   |   new    | gnew
second  |   new    | fnewed
```
while expected is:

```
Header  |  Content | Rest
:------ | :------- | :-------
first   |   new    | gold
second  |   new    | folded
```

BTW. looxlike the same thing happens if you have just the characterwise visual:
```
The gnew statue '<was very new,
and it remained new after'> being fnewed.
```
(if you know what I mean)

**Describe the solution you'd like**

Vim would have to somehow distinguish between the marker of the whole line, character in the line, blockwise or linear range. I understand that this is a general functionality working the same way for all commands that accept range parameters, but there could be at least some extra information available for such a command, and definitely used by the `:substitute` command. Not sure if extending syntax elements would be so easy to add, but this could be as well done by having extra functions that can extract appropriate information from the markers ('< and '>), while the default translation would be to the line number to maintain backward compatibility.

**Describe alternatives you've considered**

I saw there exist also some vim extensions that can do proper search-replace inside the block. Not sure how it's done, but if this is possible as an extension, could be as well out-of-the-box in the mainline - I'm certain that no one is currently using in-block-replacement in vim at all just because it doesn't work as expected.

**Additional context**

{}

**Comment by chrisbra** [comment] 2021-12-03 14:25
This is a duplicate of https://github.com/vim/vim/issues/1448 (and I am pretty sure several others, which I do not find). There is also a todo item, about allowing ex commands to apply to columns instead of lines.

Please use `\%V` regex atom to only replace within a certain visual selection.

Ah, found some of them:

https://github.com/vim/vim/issues/1448
https://github.com/vim/vim/issues/4272
https://github.com/vim/vim/issues/3292

Note: #3292 is still open and it also covers this case here, so closing this one here.

**Closed as completed by chrisbra** 2021-12-03 14:25 UTC
Labels: enhancement
