### ISSUE TITLE
Failures, test_startup.vim, errors in Test_geometry()

### ISSUE THREAD

**Issue by amosnier** [vim/vim#12167] opened 2023-03-16 19:55 UTC
### Steps to reproduce

1. Use Xubuntu 22.04 or 22.10 or equivalent.

2. Clone vim repository.

3. Run:

```
cd vim
```

```
./configure --with-features=huge --enable-multibyte --enable-rubyinterp=yes \
--enable-python3interp=yes --with-python3-config-dir=$(python3-config --configdir) \
--enable-perlinterp=yes --enable-luainterp=yes --enable-gui=gtk3 --enable-cscope \
--enable-tclinterp=yes --prefix=/usr/local
```

```
make -j
```

```
make test
```

4. Result:

> Executed:  5753 Tests
>  Skipped:    46 Tests
>   FAILED:     1 Tests
> 
> 
> Failures:
>     From test_startup.vim:
>     Found errors in Test_geometry():
>     command line..script /path/vim/src/testdir/runtest.vim[569]..function RunTheTest[52]..Test_geometry line 30: Expected '13' but got '9'

Note: non-blocking issue. Vim still seems to work perfectly.

### Expected behaviour

No "FAILED" test.

### Version of Vim

https://github.com/vim/vim/commit/e638acc9274112ca5ac6b610b01e44ab2a1e19ce

### Environment

Xubuntu 22.04 and 22.10
xterm-256color
GNU bash, version 5.2.2(1)-release (x86_64-pc-linux-gnu)
gcc (Ubuntu 12.2.0-3ubuntu1) 12.2.0

### Logs and stack traces

Not sure. Does `make test` produce some logs? I can rerun it and provide any helpful output if needed.

**Comment by chrisbra** [comment] 2023-03-17 09:03
Looks like it fails here: https://github.com/vim/vim/blob/076de79ad832558267b3ff903c048df2f4c1a5d6/src/testdir/test_startup.vim#L523-L532

You didn't mention what WM you are running, but you should be able to reproduce the issue by running your self-compiled vim with `../vim -f  -u unix.vim -U NONE --noplugin  -g -geometry 31x13+41+150 `  and then check the output of `:echo &lines` which should be `13` according to the command line argument `-geometry` 

Or you can try to re-run the test using: 
```
VIMRUNTIME=../../runtime  ../vim -f  -u unix.vim --gui-dialog-file guidialog -U NONE --noplugin --not-a-term -S runtest.vim test_startup.vim
```

Your WM may influence this (especially if you have customized it), so you may want to tell us what you are using.

**Comment by amosnier** [comment] 2023-03-17 11:30
@chrisbra: don't have much time right now (I'll get back to you later), but for now, if by WM you mean window manager, as mentioned I'm using Xubuntu 22.04 and 22.10, no particular customization so that's the XFCE window manager. The former is a VMware virtual machine and the latter a desktop PC running native Xubuntu.

**Comment by chrisbra** [comment] 2023-03-19 14:45
I think you can ignore that GTK error. The important question is
And how many lines do you have in that vim window?

You should have `13` (and that's what the text expects) but Vim only seems to have gotten 9

check the output of `:echo &lines` from within Vim

**Comment by amosnier** [comment] 2023-03-19 17:07
> I think you can ignore that GTK error. The important question is And how many lines do you have in that vim window?
> 
> You should have `13` (and that's what the text expects) but Vim only seems to have gotten 9
> 
> check the output of `:echo &lines` from within Vim

`:echo &lines` from within the Vim window that pops up gives me 9, not 13. Indeed that's one line with a blinking cursor, 7 with `~`, and one empty line at the bottom that becomes the command line when I press `:`.

**Comment by amosnier** [comment] 2023-03-19 17:12
If I replace 13 with 9 in `31x13+41+150`, I "consistently" get 5, not 9. If I replace 13 with 4, I get 2 (indeed, one with the blinking cursor, and one for the command), which I guess is a reached minimum, then.

**Comment by amosnier** [comment] 2023-03-19 17:20
A quick googling lands at https://bugs.eclipse.org/bugs/show_bug.cgi?id=538000. Just tried `sudo`ing it, and indeed, I then get the correct result, and the GTK error is gone! So somehow this seems to be related to permissions. I'm not sure how. I did a regular `git clone` to clone the repo, and my user owns the directory and everything in it, as far as I can see.

**Comment by amosnier** [comment] 2023-03-19 17:21
https://gitlab.gnome.org/GNOME/gtk/-/issues/210 seems relevant too.

**Comment by amosnier** [comment] 2023-03-19 17:42
Now I'm a little confused. After running it once with `sudo`, if I then run it without `sudo`, the GTK error is gone, but the number of lines is still incorrect (9 instead of 13). Basically, regardless of whether the GTK error is there or not, the number of lines seems to always be incorrect without `sudo`, and always correct with `sudo`.

**Comment by amosnier** [comment] 2023-03-19 17:49
I've tried it a few more times, and seem to be getting different results, quite randomly. I've seen it work correctly without `sudo` and incorrectly with `sudo`. Unstable, basically.

For the record, I have libgtk-3-0:amd64 3.24.34-3ubuntu2, amd64, on the machine I am on right now (Xubuntu 22.10), although the Xubuntu 22.04 machine I have seen the same issue on is likely to have a different version of GTK-3

**Comment by chrisbra** [comment] 2023-03-20 06:38
we don't particular care about the GTK error messages, gtk is notoriously bad at spitting out such errors and nobody knows what this means :/ 

FWIW: I am running XFCE in Debian bullseye and cannot reproduce the problem about the wrong geometry (libgtk-3 `3.24.24-4`). BTW: how does the Ubuntu distributed gvim behave?

**Comment by amosnier** [comment] 2023-03-20 18:26
> we don't particular care about the GTK error messages, gtk is notoriously bad at spitting out such errors and nobody knows what this means :/
> 

In this case, maybe the GTK error message is telling us something about the geometry issue.

> FWIW: I am running XFCE in Debian bullseye and cannot reproduce the problem about the wrong geometry (libgtk-3 `3.24.24-4`). BTW: how does the Ubuntu distributed gvim behave?

I did start gvim from the same window I was running the test in, and I did not notice anything special. Working as "usual" (again, I'm not a gvim user) and no GTK error.

I'll try to understand more by digging further. Thanks for clearly pointing out the actual test case. I'll report whatever I find, if anything, here.

**Comment by amosnier** [comment] 2023-03-20 18:48
@chrisbra, by the way, how exactly are you configuring and building? My procedure is pretty much 100% specified at https://github.com/amosnier/vim-config. Anything obvious I am missing?

**Comment by amosnier** [comment] 2023-03-20 21:56
I have been attempting some debugging with GDB, which landed in a crash, so I'm falling back to `printf` which seems to give some start of a clue. I am adding the following `printf`:

```
int gui_get_shellsize(void) {
  printf("%d, %d\n", gui.num_rows, gui.num_cols);
  Rows = gui.num_rows;
  Columns = gui.num_cols;
  return OK;
}
```

That's in gui.c starting line 1506 (latest master tonight). When it fails, I  seem to be consistently getting:

```
$ ../vim -f  -u unix.vim -U NONE --noplugin  -g -geometry 31x13+41+150
9, 33
9, 33
9, 40
```

Sometimes with a GTK error, sometimes not.

When it works, which happens quite seldom, I seem to be systematically getting:

```
$ ../vim -f  -u unix.vim -U NONE --noplugin  -g -geometry 31x13+41+150
9, 33
9, 33
13, 33
13, 40
```

It seems like the function is invoked 4 times instead of 3 when it works. I will now try to get information on where these invocations come from.

**Comment by amosnier** [comment] 2023-03-20 22:27
Getting closer, I guess.

Not working:

```
$ ../vim -f  -u unix.vim -U NONE --noplugin  -g -geometry 31x13+41+150
gui.c, 1579, gui_resize_shell: gui.num_rows = 9, gui.num_cols = 33
gui.c, 1579, gui_resize_shell: gui.num_rows = 9, gui.num_cols = 33
gui.c, 1579, gui_resize_shell: gui.num_rows = 9, gui.num_cols = 40
```

Working:

```
$ ../vim -f  -u unix.vim -U NONE --noplugin  -g -geometry 31x13+41+150
gui.c, 1579, gui_resize_shell: gui.num_rows = 9, gui.num_cols = 33
gui.c, 1579, gui_resize_shell: gui.num_rows = 13, gui.num_cols = 33
gui.c, 1579, gui_resize_shell: gui.num_rows = 13, gui.num_cols = 40
```

**Comment by amosnier** [comment] 2023-03-20 22:53
Not working

```
$ ../vim -f  -u unix.vim -U NONE --noplugin  -g -geometry 31x13+41+150
gui.c, 1579, gui_resize_shell: gui.num_rows = 9, gui.num_cols = 33
pixel_width = 284, gui_get_base_width() = 20, gui.char_width = 8
pixel_height = 163, gui_get_base_height() = 4, gui.char_height = 17
gui.c, 1579, gui_resize_shell: gui.num_rows = 9, gui.num_cols = 33
pixel_width = 284, gui_get_base_width() = 20, gui.char_width = 8
pixel_height = 158, gui_get_base_height() = 4, gui.char_height = 17
gui.c, 1579, gui_resize_shell: gui.num_rows = 9, gui.num_cols = 40
pixel_width = 343, gui_get_base_width() = 20, gui.char_width = 8
pixel_height = 158, gui_get_base_height() = 4, gui.char_height = 17
```

Working

```
$ ../vim -f  -u unix.vim -U NONE --noplugin  -g -geometry 31x13+41+150
gui.c, 1579, gui_resize_shell: gui.num_rows = 9, gui.num_cols = 33
pixel_width = 284, gui_get_base_width() = 20, gui.char_width = 8
pixel_height = 163, gui_get_base_height() = 4, gui.char_height = 17
gui.c, 1579, gui_resize_shell: gui.num_rows = 13, gui.num_cols = 33
pixel_width = 284, gui_get_base_width() = 20, gui.char_width = 8
pixel_height = 226, gui_get_base_height() = 4, gui.char_height = 17
gui.c, 1579, gui_resize_shell: gui.num_rows = 13, gui.num_cols = 40
pixel_width = 343, gui_get_base_width() = 20, gui.char_width = 8
pixel_height = 226, gui_get_base_height() = 4, gui.char_height = 17
```

**Comment by amosnier** [comment] 2023-03-20 22:56
So 9 is the result of `pixel_height` being 158 instead of 226 as it is when the number of lines is 13.

(158 - 4)  / 17 ~ 9
(226 - 4) / 17 ~ 13

**Comment by amosnier** [comment] 2023-03-20 23:07
Getting closer still. Not working:

```
$ ../vim -f  -u unix.vim -U NONE --noplugin  -g -geometry 31x13+41+150
gui_gtk_x11.c, 4233, form_configure_event: usable_height = 163
gui_gtk_x11.c, 4233, form_configure_event: usable_height = 158
gui_gtk_x11.c, 4233, form_configure_event: usable_height = 158
```

```
$ ../vim -f  -u unix.vim -U NONE --noplugin  -g -geometry 31x13+41+150
gui_gtk_x11.c, 4233, form_configure_event: usable_height = 163
gui_gtk_x11.c, 4233, form_configure_event: usable_height = 226
gui_gtk_x11.c, 4233, form_configure_event: usable_height = 226
```

**Comment by amosnier** [comment] 2023-03-21 18:27
A slight but I'm guessing crucial difference by moving up the `gui_mch_set_shellsize` to the start of the function. Not working:

```
$ ../vim -f  -u unix.vim -U NONE --noplugin  -g -geometry 31x13+41+150
gui_gtk_x11.c, 4171, form_configure_event: usable_height = 163
gui_gtk_x11.c, 4701, gui_mch_set_shellsize: height = 157
gui_gtk_x11.c, 4171, form_configure_event: usable_height = 158
gui_gtk_x11.c, 4171, form_configure_event: usable_height = 158
```

Working:

```
$ ../vim -f  -u unix.vim -U NONE --noplugin  -g -geometry 31x13+41+150
gui_gtk_x11.c, 4701, gui_mch_set_shellsize: height = 225
gui_gtk_x11.c, 4171, form_configure_event: usable_height = 163
gui_gtk_x11.c, 4171, form_configure_event: usable_height = 226
gui_gtk_x11.c, 4171, form_configure_event: usable_height = 226
```

It would look like if `form_configure_event` occurs before `gui_mch_set_shellsize`. we get the incorrect size. If it comes afterwards, we get the correct one. Probably a race condition, then.

**Comment by amosnier** [comment] 2023-03-21 20:04
A final printout before I give this up to people who know the code base better than me. Not working:

```
$ ../vim -f  -u unix.vim -U NONE --noplugin  -g -geometry 31x13+41+150
gui_gtk_x11.c, 3595, gui_mch_init
gui_gtk_x11.c, 4573, gui_mch_open
gui_gtk_x11.c, 4175, form_configure_event: usable_height = 163
gui.c, 764, gui_init
gui_gtk_x11.c, 4707, gui_mch_set_shellsize: height = 157
gui_gtk_x11.c, 4175, form_configure_event: usable_height = 158
gui_gtk_x11.c, 4175, form_configure_event: usable_height = 158
```

```
$ ../vim -f  -u unix.vim -U NONE --noplugin  -g -geometry 31x13+41+150
gui_gtk_x11.c, 3595, gui_mch_init
gui_gtk_x11.c, 4573, gui_mch_open
gui.c, 764, gui_init
gui_gtk_x11.c, 4707, gui_mch_set_shellsize: height = 225
gui_gtk_x11.c, 4175, form_configure_event: usable_height = 224
gui_gtk_x11.c, 4175, form_configure_event: usable_height = 224
```

My guess is that `gui_mch_open` triggers `form_configure_event`. And then it's a race between the latter and `gui_mch_set_shellsize`. If `form_configure_event` wins, it resets the window's height to some kind of (for us) bad default. If it looses and we manage to run `gui_mch_set_shellsize` with the right height, everything is fine. Maybe we somehow need to ignore the event when `gui_mch_set_shellsize` has not yet run, but I'm not sure about the best way to achieve that. When reading the code, I feel like this is not the first time Vim has had such issues, so the risk that a fix would create some other issue seems high.

Over and out...

**Comment by amosnier** [comment] 2023-03-25 23:44
For information, I happen to just have reinstalled one of my machines. On it, I am now running a preview of Xubuntu 23.04. In that setup, I seem to not be able to reproduce the issue described here. It's running libgtk-3-0:amd64 3.24.37-1ubuntu1. Interestingly I then do not either see a single GTK issue (and the Vim tests all pass successfully, which feels great :-)). Please feel free to close the issue.

**Comment by chrisbra** [comment] 2023-03-27 06:26
closing then

**Closed as not planned by chrisbra** 2023-03-27 06:26 UTC
Labels: bug

**Comment by brammool** [comment] 2023-03-27 20:34
> A final printout before I give this up to people who know the code base better than me. Not working:
> 
> ```
> $ ../vim -f  -u unix.vim -U NONE --noplugin  -g -geometry 31x13+41+150
> gui_gtk_x11.c, 3595, gui_mch_init
> gui_gtk_x11.c, 4573, gui_mch_open
> gui_gtk_x11.c, 4175, form_configure_event: usable_height = 163
> gui.c, 764, gui_init
> gui_gtk_x11.c, 4707, gui_mch_set_shellsize: height = 157
> gui_gtk_x11.c, 4175, form_configure_event: usable_height = 158
> gui_gtk_x11.c, 4175, form_configure_event: usable_height = 158
> ```
> 
> ```
> $ ../vim -f  -u unix.vim -U NONE --noplugin  -g -geometry 31x13+41+150
> gui_gtk_x11.c, 3595, gui_mch_init
> gui_gtk_x11.c, 4573, gui_mch_open
> gui.c, 764, gui_init
> gui_gtk_x11.c, 4707, gui_mch_set_shellsize: height = 225
> gui_gtk_x11.c, 4175, form_configure_event: usable_height = 224
> gui_gtk_x11.c, 4175, form_configure_event: usable_height = 224
> ```
> 
> My guess is that `gui_mch_open` triggers `form_configure_event`. And
> then it's a race between the latter and `gui_mch_set_shellsize`. If
> `form_configure_event` wins, it resets the window's height to some kind
> of (for us) bad default. If it looses and we manage to run
> `gui_mch_set_shellsize` with the right height, everything is fine. Maybe
> we somehow need to ignore the event when `gui_mch_set_shellsize` has not
> yet run, but I'm not sure about the best way to achieve that. When
> reading the code, I feel like this is not the first time Vim has had
> such issues, so the risk that a fix would create some other issue seems
> high.

Indeed, this is tricky stuff.  The sequence of events is largely
unpredictable.  See the comment for force_shell_resize_idle() for
another problem.

Besides changes in the GTK library it can also depend on the X server
and the window manager.  We can make it work form some combination, but
we can't possibly reproduce all combinations and make sure they work.
Since you only report a problem with a test and I haven't heard of
real-world problems, I think we better not make changes that we don't
know what the effect will be.

-- 
Have you heard about the new Barbie doll?  It's called Divorce
Barbie.  It comes with most of Ken's stuff.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
