### ISSUE TITLE
Wrong value when using synIDattr(id, 'fg#', 'gui')

### ISSUE THREAD

**Issue by wsdjeg** [vim/vim#6801] opened 2020-08-27 15:03 UTC
**Describe the bug**

`synIDattr(id, 'fg#', 'gui')` return a wrong value.

**To Reproduce**

1. `highlight TestAPIVimHighlight ctermfg=11 guifg=#89DDFF guibg=#212121`
2. `let id = hlID(a:name)`
3. `:echo  tolower(synIDattr(id, 'fg#', 'gui'))`

you will see `#ffdd89`, but I think it should be `#89ddff`

**Expected behavior**

**Screenshots**
If applicable, copy/paste the text or add screenshots to help explain your problem.

**Environment (please complete the following information):**
 - Vim version: 8.0.0027
 - OS: Windows,

It is appveyor evn, and the job is https://ci.appveyor.com/project/wsdjeg/spacevim/builds/34887383/job/g8b54msslufnv5kx

**Additional context**

**Comment by chrisbra** [comment] 2020-08-27 15:42
I cannot reproduce on 8.2.1114. Does this happen every time on your appveyor CI test run or could there be some other conditions interfering? If so, can you see, if an updated vim fixes it perhaps?

**Comment by wsdjeg** [comment] 2020-08-27 15:50
@chrisbra Thanks for your replay, here is the list of ci, everytime only `v8.0.0027` failed

https://ci.appveyor.com/project/wsdjeg/spacevim/builds/34888077

**Comment by k-takata** [comment] 2020-08-27 22:56
So, it has been already fixed. Closing.

**Closed as completed by k-takata** 2020-08-27 22:56 UTC

**Comment by wsdjeg** [comment] 2020-08-27 23:29
@k-takata thanks But I can not find which patch fix this issue. and whyvit works well in old vim. which patch brings this bug. please reopen it, thanks.

**Comment by k-takata** [comment] 2020-08-28 01:42
Your reproduce steps look incorrect.
I changed the second step to `let id = hlID("TestAPIVimHighlight")`, and executed on 8.0.0027, then the result was `#89ddff`.

**Comment by wsdjeg** [comment] 2020-08-28 10:23
this  is in a function, and a:name is just the higroup name. It is wrong in https://ci.appveyor.com/project/wsdjeg/spacevim/builds/34887383/job/g8b54msslufnv5kx

**Comment by k-takata** [comment] 2020-08-28 10:38
No need to reopen this except it is reproduced on the latest code.
If you want to know which patch fixed it, please bisect by yourself.
If you need a help to bisect it, please show the complete steps (including the function) to reproduce.

**Comment by wsdjeg** [comment] 2020-08-28 13:16
Hello, Thanks @k-takata , here is the full reproduce step:

```
highlight TestAPIVimHighlight ctermfg=11 guifg=#89DDFF guibg=#212121
let id = hlID('TestAPIVimHighlight')
:echo tolower(synIDattr(id, 'fg#', 'gui'))
```

I test it in https://ci.appveyor.com/ with vim8.0.0027, It prints `#ffdd89`, but I think it should be `#89ddff`

**Comment by chrisbra** [comment] 2020-08-28 13:18
if this works in current vim, than what exactly do you expect us here to do?

**Comment by k-takata** [comment] 2020-08-28 13:28
Ah, reproduced only on vim.exe with `set tgc`.
I remember that some versions of vim.exe incorrectly swapped RGB and BGR.

**Comment by wsdjeg** [comment] 2020-08-28 13:37
I want to know which version of vim has this issue, I need to fix it in plugin, my plugin use this synIDattr function.

the full log is here: https://ci.appveyor.com/project/wsdjeg/spacevim/builds/34906909/job/lktg86p99p1g04jj

vim version:

```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Oct  9 2016 22:09:09)
MS-Windows 32-bit console version
Included patches: 1-27
Compiled by appveyor@APPVYR-WIN
```

vader script:

```
Execute ( SpaceVim api: vim#highlight ):
  highlight TestAPIVimHighlight ctermfg=11 guifg=#89DDFF guibg=#212121
    let id = hlID('TestAPIVimHighlight')
    Log 'guifg is: ' . synIDattr(id, 'fg#', 'gui')
    Log 'guibg is: ' . synIDattr(id, 'bg#', 'gui')
    Log cmp.execute('hi TestAPIVimHighlight')
```
vader log:

```
    (1/1) [EXECUTE]  SpaceVim api: vim#highlight
      > guifg is: #ffdd89
      > guibg is: #212121
  Success/Total: 0/1
```

**Comment by chrisbra** [comment] 2020-08-28 13:43
I had a brief look at the git log, but did not find an obvious commit message. Can't you simply skip the test for version 8.0.27? If you really need to know which patch fixed it, you may need to bisect to find the fix.

**Comment by k-takata** [comment] 2020-08-28 13:43
`set tgc` doesn't work on that version of vim.exe. Colors are not shown correctly.
Trying to fix it in a plugin is totally meaningless.

**Comment by wsdjeg** [comment] 2020-08-28 13:46
@k-takata @chrisbra Thank you, ok, I will not `set tgc` in that version. the tgc works on which version of vim.exe?

**Comment by k-takata** [comment] 2020-08-28 13:50
Maybe 8.0.0146.

**Comment by wsdjeg** [comment] 2020-08-28 13:52
Ok, thanks, :+1:

**Comment by chrisbra** [comment] 2020-08-28 13:52
I would simply skip that test for 8.0.027, it is almost 4 years ago.

**Comment by chrisbra** [comment] 2020-08-28 13:55
> Maybe 8.0.0146.

Very likely this patch fixed it. https://github.com/vim/vim/commit/287266527abc163e191a06dd70518bbbdab4468f

**Comment by wsdjeg** [comment] 2020-08-29 08:27
@chrisbra Thanks for your info.
