### ISSUE TITLE
Vim clipboard won't work on OS X when compiled with GTK

### ISSUE THREAD

**Issue by GoogleCodeExporter** [vim/vim#264] opened 2015-08-18 21:08 UTC
```
What steps will reproduce the problem?
1. Compile Vim with GTK+ (brew install vim --client-server)
2. Open Vim
3. Try to paste from the clipboard (Using "+p or "*p)

What is the expected output? What do you see instead?
Expected: Pasting whatever is in the clipboard
Actual result: Nothing in register * (or +, both are empty)

Tested with version(s):
Vim: 7.4.253 and 7.4.430
OS: OS X 10.8.5

It should be noted that everything works fine as long as I don't compile in 
GTK+. I see how this causes problems for "+ but I don't understand why it 
affects "* as well.

Some extra info can be found in a downstream bug report: 
https://github.com/Homebrew/homebrew/issues/32875#issuecomment-57911462
```

Original issue reported on code.google.com by `Wolphie` on 8 Oct 2014 at 2:11

**Comment by nuko8** [comment] 2017-03-17 00:33
By design, the X11 clipboard and the OS X pasteboard cannot be available simultaneously from Vim at run time.  You must make a decision as to which to use at configuration.

If you want the `clientserver` feature, pass `--dsiable-darwin` to `configure` to kill the OS X pasteboard feature; otherwise, the `clientserver` won't be enabled because it requires the X11 clipboard.

**Comment by brammool** [comment] 2017-03-18 20:47
Closing, as this appears to be infeasible.

**Closed as completed by brammool** 2017-03-18 20:47 UTC
Labels: Priority-Medium, defect, auto-migrated
