### ISSUE TITLE
NerdFont symbols clipped

### ISSUE THREAD

**Issue by Djedouas** [vim/vim#8175] opened 2021-05-03 17:09 UTC
**Describe the bug**

On gvim GUI, the nerdfont symbols are clipped, but on terminal vim they are not clipped.

**Screenshots**

On GUI gvim
![image](https://user-images.githubusercontent.com/34267385/116907999-ad491900-ac42-11eb-848d-3f8fc275478f.png)

On terminal vim
![image](https://user-images.githubusercontent.com/34267385/116908287-fef1a380-ac42-11eb-8bca-566a238c03c2.png)

**Environment (please complete the following information):**

SpaceVim

```
 ~ vim --version
NVIM v0.4.4
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-u4YhjF/neovim-0.4.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim-u4YhjF/neovim-0.4.4/build/config -I/build/neovim-u4YhjF/neovim-0.4.4/src -I/usr/include -I/usr/include/lua5.1 -I/build/neovim-u4YhjF/neovim-0.4.4/build/src/nvim/auto -I/build/neovim-u4YhjF/neovim-0.4.4/build/include
Compilé par team+vim@tracker.debian.org

Features: +acl +iconv +tui
See ":help feature-compile"

         fichier vimrc système : "$VIM/sysinit.vim"
               $VIM par défaut : "/usr/share/nvim"
```
OS: Ubuntu 21.04
Terminal: GUI and terminal same problem

**Comment by dpelle** [comment] 2021-05-03 17:31
* What are the Unicode characters that appear truncated?
* How do you reproduce it? Ideally provide an automated way to reproduce it with with `vim --clean`.
* You use neovim, not vim.  Does the same issue affect vim?

**Comment by chrisbra** [comment] 2021-05-04 06:05
closing, since this is not vim

**Comment by Djedouas** [comment] 2021-05-04 07:50
Same problem with this vim:

```
 ~ gvim --version
VIM - Vi IMproved 8.2 (2019 Dec 12, compilé Feb 15 2021 12:29:39)
Rustines incluses : 1-2434
Modifié par team+vim@tracker.debian.org
Compilé par team+vim@tracker.debian.org
Énorme version avec interface graphique GTK3.
  Fonctionnalités incluses (+) ou non (-) :
+acl               -farsi             +mouse_sgr         +tag_binary
+arabic            +file_in_path      -mouse_sysmouse    -tag_old_static
+autocmd           +find_in_path      +mouse_urxvt       -tag_any_white
+autochdir         +float             +mouse_xterm       +tcl
-autoservername    +folding           +multi_byte        +termguicolors
+balloon_eval      -footer            +multi_lang        +terminal
+balloon_eval_term +fork()            -mzscheme          +terminfo
+browse            +gettext           +netbeans_intg     +termresponse
++builtin_terms    -hangul_input      +num64             +textobjects
+byte_offset       +iconv             +packages          +textprop
+channel           +insert_expand     +path_extra        +timers
+cindent           +ipv6              +perl              +title
+clientserver      +job               +persistent_undo   +toolbar
+clipboard         +jumplist          +popupwin          +user_commands
+cmdline_compl     +keymap            +postscript        +vartabs
+cmdline_hist      +lambda            +printer           +vertsplit
+cmdline_info      +langmap           +profile           +virtualedit
+comments          +libcall           -python            +visual
+conceal           +linebreak         +python3           +visualextra
+cryptv            +lispindent        +quickfix          +viminfo
+cscope            +listcmds          +reltime           +vreplace
+cursorbind        +localmap          +rightleft         +wildignore
+cursorshape       +lua               -ruby              +wildmenu
+dialog_con_gui    +menu              +scrollbind        +windows
+diff              +mksession         +signs             +writebackup
+digraphs          +modify_fname      +smartindent       +X11
+dnd               +mouse             +sound             -xfontset
-ebcdic            +mouseshape        +spell             +xim
+emacs_tags        +mouse_dec         +startuptime       +xpm
+eval              +mouse_gpm         +statusline        +xsmp_interact
+ex_extra          -mouse_jsbterm     -sun_workshop      +xterm_clipboard
+extra_search      +mouse_netterm     +syntax            -xterm_save
         fichier vimrc système : "$VIM/vimrc"
     fichier vimrc utilisateur : "$HOME/.vimrc"
  2e fichier vimrc utilisateur : "~/.vim/vimrc"
      fichier exrc utilisateur : "$HOME/.exrc"
        fichier gvimrc système : "$VIM/gvimrc"
    fichier gvimrc utilisateur : "$HOME/.gvimrc"
 2e fichier gvimrc utilisateur : "~/.vim/gvimrc"
 fichier de valeurs par défaut : "$VIMRUNTIME/defaults.vim"
          fichier menu système : "$VIMRUNTIME/menu.vim"
               $VIM par défaut : "/usr/share/vim"
Compilation : gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -Wdate-time -g -O2 -ffile-prefix-map=/build/vim-ZRU0XK/vim-8.2.2434=. -fstack-protector-strong -Wformat -Werror=format-security -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 
Édition de liens : gcc -Wl,-E -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE -lm -ltinfo -lselinux -lcanberra -lacl -lattr -lgpm -ldl -L/usr/lib -llua5.2 -Wl,-E -fstack-protector-strong -L/usr/local/lib -L/usr/lib/x86_64-linux-gnu/perl/5.32/CORE -lperl -ldl -lm -lpthread -lcrypt -L/usr/lib/python3.9/config-3.9-x86_64-linux-gnu -lpython3.9 -lcrypt -lpthread -ldl -lutil -lm -lm -L/usr/lib/x86_64-linux-gnu -ltcl8.6 -ldl -lz -lpthread -lm 
```

**Comment by brammool** [comment] 2021-05-04 08:05
It might be a GTK 3 issue then.  There was an option to use some extra space but the name escapes me right now.

**Comment by chrisbra** [comment] 2021-05-04 08:06
is this with the gui or with the terminal? If so what terminal? Please also answer the questions from @dpelle

**Comment by chrisbra** [comment] 2021-05-04 08:09
This might depend on the unicode version of your terminal and all related libraries. You might be able to fix this by setting the width of certain characters using the `setcellwidth()` function.

**Comment by Djedouas** [comment] 2021-05-04 08:15
While looking for the unicode code, I found that the issue only appears in the status line of SpaceVim, and not in the main text area.

But what is strange is that using the terminal (Terminator or gnome-terminal) the status line icons are not clipped.

I suspect that the icons are not taken from the same source (same font) for the statusline by gvim and by the terminal.

**Closed as completed** 2021-05-04 10:17 UTC
