### ISSUE TITLE
setfiletype does not work in packages

### ISSUE THREAD

**Issue by airblade** [vim/vim#1679] opened 2017-05-04 15:55 UTC
Hello!

I have a plugin containing a file `ftdetect/foo.vim`:

```viml
autocmd BufNewFile,BufRead foo setfiletype foo
```

The plugin is installed in `~/.vim/pack/stuff/start/`.

When I edit a file named `foo`, I expect the filetype to be set to `foo`.  Actually it is set to `conf`.

I believe this is because vim's [filetype detection](https://github.com/vim/vim/blob/4475b623960671898dac6a72b13a8d140402afa6/runtime/filetype.vim#L2770) uses:

```viml
runtime! ftdetect/*.vim
```

I think that when that line is executed, the plugins in `~/.vim/pack/stuff/start/` are not on the `runtimepath`.  So Vim falls back to its [generic configuration file](https://github.com/vim/vim/blob/4475b623960671898dac6a72b13a8d140402afa6/runtime/filetype.vim#L2778-L2783).

When I change that line to:

```viml
runtime! ALL ftdetect/*.vim
```

– the filetype is set as expected.

Vim 8.0.586.

**Comment by vim-ml** [comment] 2017-05-04 16:08
On Thursday, May 4, 2017 at 10:56:21 AM UTC-5, Andy Stewart wrote:
> 
> I believe this is because vim's filetype detection uses:
> 
> runtime! ftdetect/*.vim
> 
> I think that when that line is executed, the plugins in ~/.vim/pack/stuff/start/ are not on the runtimepath.  So Vim falls back to its generic configuration file.
> 
> When I change that line to:
> 
> runtime! ALL ftdetect/*.vim
> 
> – the filetype is set as expected.
> 
> Vim 8.0.586.
> 


Hmm, that will also search in "opt" packages. I don't think that's wanted unless the user has used packadd already in which case it will be in the runtimepath. Probably it should just search the "start" packages and then the runtime. How is this done? Does it need two runtime commands, first "runtime! START ftdetect/*.vim" followed by "runtime! ftdetect/*.vim" to pick up the runtimepath files?

**Comment by k-takata** [comment] 2017-05-05 03:54
How about adding following lines to your `.vimrc`? (not tested)

```vim
filetype plugin indent off
packloadall
filetype plugin indent on
```

**Comment by airblade** [comment] 2017-05-05 08:41
> Does it need two runtime commands, first "runtime! START ftdetect/*.vim" followed by "runtime! ftdetect/*.vim" to pick up the runtimepath files?

According to the `:runtime` docs, that would do it.  And indeed it works for me.

```
When [where] is omitted only 'runtimepath' is used.
Other values:
	START	search under "start" in 'packpath'
	OPT 	search under "opt" in 'packpath'
	PACK	search under "start" and "opt" in
		'packpath'
	ALL	first use 'runtimepath', then search
		under "start" and "opt" in 'packpath'
```

Alternatively the `:runtime` command could be updated to accept two "where" arguments, e.g. `:runtime! RUNTIME START ftdetect/*.vim`.  But that's more complicated than just calling `:runtime!` twice.

@k-takata That doesn't solve the problem, at least for me.  And I feel this should be addressed by vim rather than worked around in users' vimrc configs.

**Comment by inkarkat** [comment] 2017-05-08 17:05
I cannot reproduce this (in Vim 8.0.559); I believe [this code](https://github.com/vim/vim/blob/master/src/ex_cmds2.c#L3614-L3624) ensures that ftdetect scripts from pack directories are sourced.

**Comment by k-takata** [comment] 2017-05-09 11:01
I tried with Vim 8.0.0596 and couldn't reproduce.

@airblade Could you show your (minimal) .vimrc to reproduce?

**Comment by airblade** [comment] 2017-05-09 13:07
~/.vim/vimrc:

```viml
filetype plugin on
```

~/.vim/pack/stuff/start/foo/ftdetect/foo.vim:

```viml
autocmd BufNewFile,BufRead foo setfiletype foo
```

```
$ vim foo
:verbose set ft?
```

Expected: `foo`
Actual: `foo`

`filetype plugin on` executes $VIMRUNTIME/filetype.vim, but filetype.vim doesn't set the file type to anything (proved by echoing the file type at the end of $VIMRUNTIME/filetype.vim).  This means that pack/stuff/start/foo/ftdetect/foo.vim is not on the [runtime path](https://github.com/vim/vim/blob/4475b623960671898dac6a72b13a8d140402afa6/runtime/filetype.vim#L2770) then.

Therefore something else (I don't know the mechanism) must subsequently execute pack/stuff/start/foo/ftdetect/foo.vim (which sets the file type to the expected value).

Furthermore:

```sh
$ echo "#" > foo
$ vim foo
:verbose set ft?
```

Expected: `foo`
Actual: `conf`

$VIMRUNTIME/filetype.vim sets the file type to the [generic `conf`](https://github.com/vim/vim/blob/4475b623960671898dac6a72b13a8d140402afa6/runtime/filetype.vim#L2778-L2783).  This means that pack/stuff/start/foo/ftdetect/foo.vim is not on the runtime path then.

Therefore when the something-else subsequently executes pack/stuff/start/foo/ftdetect/foo.vim, the `setfiletype foo` has no effect.

Admittedly I don't understand the "something-else" mechanism which detects the foo file type after $VIMRUNTIME/filetype.vim has already run.  But it seems to me that $VIMRUNTIME/filetype.vim should be aware of packages in ~/.vim/pack/start when it executes.  Currently it isn't.

**Comment by inkarkat** [comment] 2017-05-09 14:40
Ah, I can reproduce this now. And moving `~/.vim/pack/stuff/start/foo/ftdetect/foo.vim` to `~/.vim/ftdetect/foo.vim` fixes the problem, so it's clearly related to the detection script being in a _pack_ directory.

The problem appears to be the ordering of the `:autocmd filetypedetect`; the [code I mentioned](https://github.com/vim/vim/blob/master/src/ex_cmds2.c#L3614-L3624) sources the additional pack ftdetect scripts, so their autocmds get appended. However, `$VIMRUNTIME/filetype.vim` already finished execution, so the fallback detection for generic `conf`iguration is now evaluated _before_ the detections from the pack plugins!

    :autocmd filetypedetect
    [...]
    *         if !did_filetype() && expand("<amatch>") !~ g:ft_ignore_pat    && (getline(1) =~ '^#' || getline(2) =~ '^#' || getline(3) =~ '^#'^I|| getline(4) =~ '^#' || getline(5) =~ '^#') |   setf conf | endif
    [...]
    foo       setf foo

That also explains why your first command (`vim foo`) gives the correct filetype: This is an empty file, so the fallbacks do not apply.


So, the current implementation only works when the ordering of the detection doesn't matter. That's not what the user expects; the plugin location (pack vs. default) should not matter. It's a bug, similar to #1680 which I've reported.

**Closed as completed** 2017-06-04 17:00 UTC
