### ISSUE TITLE
Termdebug K keybinding messes up existing K keybinding

### ISSUE THREAD

**Issue by Kazhuu** [vim/vim#6108] opened 2020-05-19 13:58 UTC
**Describe the bug**
When termdebug session is started K key is bind to :Evaluate command: https://github.com/vim/vim/blob/master/runtime/pack/dist/opt/termdebug/plugin/termdebug.vim#L661 and there is no way to remap this key or the original binding is not restored.

**To Reproduce**
1. `vim --clean`
2. `:packadd  termdebug`
3. `:Termdebug`
4. In gdb window type q and hit enter (this will end debug session)
5. Press shift + k
Now the K binding from termdebug is still there even debug session is not open anymore and I see error message saying `E349: No identifier under cursor`.

**Expected behavior**
Original K keybinding is restored or K binding for debug session can be remapped in my .vimrc file.

**Environment (please complete the following information):**
 - OS: Manjaro 20.1
 - Terminal: kitty
 - Vim: VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Feb  2 2020 19:11:59)

**Comment by jamessan** [comment] 2020-05-19 14:13
Shouldn't all of those commands and mappings be made buffer-local?

**Comment by chrisbra** [comment] 2020-05-19 14:24
I suppose it is useful to use the K mapping in several buffers. However I cannot reproduce this. Once the gdb session terminates, the function `EndTermDebug` will be called, which does call `EndDebugCommon()` and `EndDebugCommon()` will finally call `DeleteCommands()` which does `unmap K`.

**Comment by Kazhuu** [comment] 2020-05-19 17:00
I updated the steps to reproduce and tried them myself. Should now be simple as possible to reproduce the issue.

**Comment by chrisbra** [comment] 2020-05-19 17:13
are you sure? Have you verified, that `:nmap K` shows the mapping? 

If I perform your steps, I do see `E349: No identifier under cursor.`, but that also happens after a `vim --clean` and hitting `K` on the empty buffer.

**Comment by brammool** [comment] 2020-05-19 21:31
Mauri Mustonen wrote:

> **Describe the bug**
> When termdebug session is started K key is bind to :Evaluate command: https://github.com/vim/vim/blob/master/runtime/pack/dist/opt/termdebug/plugin/termdebug.vim#L661 and there is no way to remap this key or the original binding is not restored.
> 
> **To Reproduce**
> 1. Run `vim`
> 2. Run `:packadd  termdebug`
> 3. Run `:Termdebug`
> 4. In gdb window type q and hit enter (this will end debug session)
> Now the K binding from termdebug is still there even debug session is not open anymore.
> 
> **Expected behavior**
> Original K keybinding is restored or K binding for debug session can be remapped in my .vimrc file.

It's marked as TODO:

  " TODO: can the K mapping be restored?
  nnoremap K :Evaluate<CR>

As Christian mentioned, currently the mapping is cleared when the debugger
ends.

We can disable the mapping if you don't want it:

  if !exists('g:termdebug_map_K') || g:termdebug_map_K
    " TODO: can the K mapping be restored?
    nnoremap K :Evaluate<CR>
  endif


-- 
hundred-and-one symptoms of being an internet addict:
141. You'd rather go to http://www.weather.com/ than look out your window.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by Kazhuu** [comment] 2020-05-20 06:42
Okay sorry my bad it seems that `E349: No identifier under cursor` comes up even when debug mode is not entered. It seems I overlooked this. So the real problem is that my old K keybinding gets unmapped like you guys said. Yeah if this keybinding could be restored or even better changed in my .vimrc that would be the best solution I think :)

Thank you for you time!

**Comment by chrisbra** [comment] 2020-05-20 10:01
How about the following patch than:

```patch
diff --git a/runtime/pack/dist/opt/termdebug/plugin/termdebug.vim b/runtime/pack/dist/opt/termdebug/plugin/termdebug.vim
index 3ba1f7e1d..ac3c2f21f 100644
--- a/runtime/pack/dist/opt/termdebug/plugin/termdebug.vim
+++ b/runtime/pack/dist/opt/termdebug/plugin/termdebug.vim
@@ -657,7 +657,7 @@ func s:InstallCommands()
   command Source call s:GotoSourcewinOrCreateIt()
   command Winbar call s:InstallWinbar()

-  " TODO: can the K mapping be restored?
+  let s:save_k_map = maparg('K', 'n', 0, 1)
   nnoremap K :Evaluate<CR>

   if has('menu') && &mouse != ''
@@ -708,7 +708,7 @@ func s:DeleteCommands()
   delcommand Source
   delcommand Winbar

-  nunmap K
+  call s:RestoreMap()

   if has('menu')
     " Remove the WinBar entries from all windows where it was added.
@@ -1066,5 +1066,17 @@ func s:BufUnloaded()
   endfor
 endfunc

+func s:RestoreMap()
+  " Restore K mapping
+  if !empty(s:save_k_map)
+    exe (s:save_k_map.noremap ? 'nnoremap ' : 'nmap ') .
+      \ join(map(['buffer', 'expr', 'nowait', 'silent'], {i,val -> s:save_k_map[val] ? "<" . val . ">": ""})) .
+      \ s:save_k_map.lhs . ' ' .
+      \ substitute(s:save_k_map.rhs, '<SID>', '<SNR>' . s:save_k_map.sid . '_', 'g')
+  else
+    nunmap K
+  endif
+endfunc
+
 let &cpo = s:keepcpo
 unlet s:keepcpo
```

**Comment by Kazhuu** [comment] 2020-05-21 06:26
Thank you for fast answer! I'm not very fluent in vim script but both global mapping `g:termdebug_map_K` and above diff are good and solve the issue. I'm just wondering what Vim community prefer and which one should be implemented? Based on that original TODO comment restoring the original keybinding what original author wanted?

**Comment by brammool** [comment] 2020-05-21 13:28
Christian wrote:

> How about the following patch than:
> 
> ```patch
> diff --git a/runtime/pack/dist/opt/termdebug/plugin/termdebug.vim b/runtime/pack/dist/opt/termdebug/plugin/termdebug.vim
> index 3ba1f7e1d..ac3c2f21f 100644
> --- a/runtime/pack/dist/opt/termdebug/plugin/termdebug.vim
> +++ b/runtime/pack/dist/opt/termdebug/plugin/termdebug.vim
> @@ -657,7 +657,7 @@ func s:InstallCommands()
>    command Source call s:GotoSourcewinOrCreateIt()
>    command Winbar call s:InstallWinbar()
> 
> -  " TODO: can the K mapping be restored?
> +  let s:save_k_map = maparg('K', 'n', 0, 1)
>    nnoremap K :Evaluate<CR>
> 
>    if has('menu') && &mouse != ''
> @@ -708,7 +708,7 @@ func s:DeleteCommands()
>    delcommand Source
>    delcommand Winbar
> 
> -  nunmap K
> +  call s:RestoreMap()
> 
>    if has('menu')
>      " Remove the WinBar entries from all windows where it was added.
> @@ -1066,5 +1066,17 @@ func s:BufUnloaded()
>    endfor
>  endfunc
> 
> +func s:RestoreMap()
> +  " Restore K mapping
> +  if !empty(s:save_k_map)
> +    exe (s:save_k_map.noremap ? 'nnoremap ' : 'nmap ') .
> +      \ join(map(['buffer', 'expr', 'nowait', 'silent'], {i,val -> s:save_k_map[val] ? "<" . val . ">": ""})) .
> +      \ s:save_k_map.lhs . ' ' .
> +      \ substitute(s:save_k_map.rhs, '<SID>', '<SNR>' . s:save_k_map.sid . '_', 'g')
> +  else
> +    nunmap K
> +  endif
> +endfunc
> +
>  let &cpo = s:keepcpo
>  unlet s:keepcpo
> ```

Makes me wonder why it's so complicated to restore a mapping.
I suppose we would need a mapset() function that uses the result of
maparg().

-- 
hundred-and-one symptoms of being an internet addict:
147. You finally give up smoking...because it made the monitor dirty.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment] 2020-05-22 12:05
I'll implement this with maparg() and  mapset()

**Closed as completed by brammool** 2020-05-22 12:05 UTC
