### ISSUE TITLE
Request: Use full version numbers on vim-win32-installer

### ISSUE THREAD

**Issue by idbrii** [vim/vim#827] opened 2016-05-21 20:20 UTC
On Windows with a version of python installed that doesn't match the micro version vim was built, once you executes `:python` code, vim will crash without notice (no error). Example: editorconfig/editorconfig-vim#58

So it would be great to have the [vim-win32-installer/releases](https://github.com/vim/vim-win32-installer/releases) include the micro version number. Currently, it says Python 2.7, but we need to know it's Python 2.7.11.

It looks like this [appveyor](https://github.com/vim/vim-win32-installer/blob/master/appveyor.bat) script generates the packages. And [this yml contains the release notes template](https://github.com/vim/vim-win32-installer/blob/master/appveyor.yml), but I can't tell what generates the release notes. Could that script generate some text to insert into the release notes? If it could output version numbers (`%PYTHON_DIR%\python.exe --version`) that we could insert into the release notes, that would be awesome! I'm not really sure how the template gets filled in.

BTW, thanks for these releases! They're fantastic!

**Comment by k-takata** [comment] 2016-05-21 23:07
I didn't add micro versions to the release notes because I assumed the APIs are not changed when only the micro version is changed.
I confirmed that the files from vim-win32-installer work fine with Python 2.7.10.

> Example: editorconfig/editorconfig-vim#58

As I commented in that issue, this is caused by the combination of two bugs:
1. A bug already fixed with Vim 7.4.380
2. Python 2.7.11's bug

So I don't think the micro version number is needed.
Ah, maybe it's better to mention about the (serious) Python 2.7.11's bug. I don't understand why python.org don't release the fix soon.

**Comment by chrisbra** [comment] 2016-05-22 18:58
Hm, it might be a good idea, to document the minor version, or perhaps have the compile script run python --version, so that at least the logfile contains the output of the interpreter. This could also help, if appveyor updates python and this breaks vim.

**Comment by idbrii** [comment] 2016-05-22 19:27
> Ah, maybe it's better to mention about the (serious) Python 2.7.11's bug.

Also good to mention that [it only affects the x32 Python installer](https://github.com/vim/vim/issues/526#issuecomment-164885089). That bug threw me off since I didn't encounter problems with Py2.7.11 x64.
(I setup [vim 7.4.1832 x64](https://github.com/vim/vim-win32-installer/releases/tag/v7.4.1832) and [Python 2.7.11 x64](https://www.python.org/downloads/) without registry changes and of the four keys mentioned in [your workaround](https://github.com/k-takata/vim/commit/435be6dc61347d92029768f1678fdfdb9a543005) only `...PythonCore\2.7 /reg:64` exists.)

**Comment by k-takata** [comment] 2016-05-22 21:16
> This could also help, if appveyor updates python and this breaks vim.

Agree.

> Also good to mention that it only affects the x32 Python installer. That bug threw me off since I didn't encounter problems with Py2.7.11 x64.

No, x64 also has the same problem:
https://github.com/vim/vim/issues/526#issuecomment-164949732
http://bugs.python.org/issue25824#msg257698

X64 fails without the workaround:
https://ci.appveyor.com/project/k-takata/vim-win32-installer/build/30/job/1tp9jn6cgdyy6265
(I don't know why this doesn't happen on your environment.)

**Comment by chrisbra** [comment] 2016-06-02 10:22
I am closing, as all issues should be resolved with the integration of vim/vim-win32-installer#8

**Closed as completed by chrisbra** 2016-06-02 10:22 UTC
