### ISSUE TITLE
Vim's future development system

### ISSUE THREAD

**Issue by 0Delta** [vim/vim#12733] opened 2023-08-06 01:21 UTC
I feel that maintaining and leveraging his Vim legacy is my greatest contribution to Bram.

Discussing the new regime, whether it's transitioning to a new admin or maintaining the community, he thinks the README needs to be updated first.

**Comment by peacock0803sz** [comment] 2023-08-06 01:39
For the time being, it seems appropriate to proceed by agreement among those who have commit permission; @k-takata @chrisbra and Dr. Chip.

Grieving will not help, so I hope that we can overcome our grief and move forward with constructive discussions.

**Comment by k-takata** [comment] 2023-08-06 06:23
I think this is a duplicate of #12728. Closing.

**Closed as completed by k-takata** 2023-08-06 06:23 UTC
Labels: duplicate, discuss
