### ISSUE TITLE
Typing left square bracket '[' in Insert Mode on large markdown files with syntax on

### ISSUE THREAD

**Issue by poiurewq** [vim/vim#11355] opened 2022-10-12 23:27 UTC
### Steps to reproduce

1. Have "syntax on" in .vimrc
2. Have a very long `.markdown` or `.md` file with lots of text in it
3. Enter Insert Mode by typing `i`
4. Type `[` and observe that the cursor has not moved to the right of the newly typed `[`, but stays on top of the `[` character. 
5. If I typed `[` at the end of a line, there is also no way to use right arrows in Insert mode or `A` or `k` in Normal mode to get to the other side of this character to type after it.
6. Additionally, I see several errors (not always all of them, sometimes only Error 1 and 2): 
    Error 1: `E363: Pattern uses more memory than 'maxmempattern'`
    Error 2: `'redrawtime' exceeded, syntax highlighting disabled`
    Error 3: ```Error detected while processing CursorMovedI Autocommands for "*"..function <SNR>18_Highlight_Matching_Pair[135]..CursorMovedI Autocommands
 for "*"..function <SNR>18_Highlight_Matching_Pair:```
    I dug into it a little and saw number 18 script is `18: /usr/share/vim/vim90/plugin/matchparen.vim`
7. After the errors show up, they no longer show up for future `[` typed during the vim session.

### Expected behaviour

I expect to be able to simply type `[` without any errors. Additionally, I expect that, after typing `[`, the cursor moves to the right instead of still covering the `[` character. I expect to be able to use right arrows in insert mode as well as A or k to get to the other side of this character. If I get Error 2, then syntax highlighting is disabled and I am then able to type `[` without a problem.

### Version of Vim

9.0

### Environment

macOS version - x86_64
Terminal: iTerm
$TERM: xterm-256color
Shell: bash

**Comment by poiurewq** [comment] 2022-10-12 23:29
See also relevant StackExchange:
https://stackoverflow.com/questions/74035507/error-when-typing-left-square-bracket-in-vim-insert-mode-on-large-markdown-f

**Comment by arp242** [comment] 2022-10-13 00:29
How long is a "very long" Markdown file?

**Comment by poiurewq** [comment] 2022-10-13 02:06
Mine is a README.md that is 1357 lines long. I cannot verify this for other lengths, but have tried it on shorter .md files of 20 lines long and this could not be replicated. I cannot provide the exactly .md file here for IP reasons, but any .md file of similar length would cause this issue on my computer.

**Comment by arp242** [comment] 2022-10-13 02:12
That's fine; just to have an idea so it can be reproduced; "very long" could mean 100,000 lines or something.

I can reproduce easily with a markdown file that's 3,240 lines long; with 1,311 lines it's a bit slow/awkward but no error.

**Comment by arp242** [comment] 2022-10-13 02:42
The problem is `markdownLinkText` from syntax/markdown.vim; it doesn't really seem related to matchparen.  Running `/!\=\[\%(\%(\_[^][]\|\[\_[^][]*\]\)*]\%( \=[[(]\)\)\@=` from Vim also fails with that error.

Running `:syn clear markdownLinkText` should "fix" it for you so you can continue working; or at least, it does for me.

FYI @tpope

**Comment by tpope** [comment] 2022-10-13 03:27
#6777

**Comment by arp242** [comment] 2022-10-13 03:31
Can confirm that fixes it @tpope; can you send your changes to Bram? The current Vim runtime still has the old version, and it's been a few years since it was fixed.

**Comment by chrisbra** [comment] 2022-10-13 07:08
closing in favor of #11358 then

**Closed as completed by chrisbra** 2022-10-13 07:08 UTC
Labels: bug
