### ISSUE TITLE
Soft wrapping at given column

### ISSUE THREAD

**Issue by Jorenar** [vim/vim#10825] opened 2022-07-31 15:29 UTC
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**
Currently, soft wrapping is possible only at the end of window. For the code (or prose) with long lines, it would be helpful to have an option to soft wrap it at given column _N_.

**Describe the solution you'd like**
An option to set column to wrap at; something à la:
```help
                                             *'softwrapcol'* *'swc'*
'softwrapcol' 'swc'    number  (default 0)
                       local to window
    A column to soft wrap text at if it's smaller than window width.
    Requires 'wrap' option to be set and respects 'linebreak' feature.
	When 'swc' is zero, this feature is off.
	When 'swc' is negative, the value of 'textwidth' is used.
```
So when `set wrap linebreak softwrapcolumn=80` the code will be wrapped around column 80 even if window is wider.

**Describe alternatives you've considered**
The workarounds include `set column=N` or `vnew | wincmd p | vert resize N`.  
The limit of such approaches is that you essentially limit yourself to one vertical window.

**Additional context**
I've had a quick look and tried a dirty implementation: https://github.com/Jorengarenar/vim/tree/softwrapcol  
Surprisingly, it somewhat works, but I'm sure there is a lot of problems (I don't think `win_lbr_chartabsize()` from `charset.c` is the right place for it; one problem I've found right away: it also affects hard wrap).

**Comment by brammool** [comment] 2022-07-31 17:36
Why not reduce the window width?

**Comment by Jorengarenar** [comment] 2022-07-31 18:47
> Why not reduce the window width?

It's impossible without vertical window next to it?

**Comment by brammool** [comment] 2022-07-31 21:11
> > Why not reduce the window width?
> 
> It's impossible without vertical window next to it?

Yes, if you can't change the Vim window width, then splitting vertically
does that.  You can leave the window on the right empty, then you simply
have the vertical separator as the boundary.  That's not really a
problem, is it?

-- 
hundred-and-one symptoms of being an internet addict:
214. Your MCI "Circle of Friends" are all Hayes-compatible.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by arp242** [comment] 2022-07-31 22:03
Duplicate of #1847

Using `set columns=80` works reasonably well btw, although it will be reset on a window resize. Can probably use an autocmd for it.

**Comment by Jorengarenar** [comment] 2022-08-01 15:55
@brammool @arp242 
Since this is a duplicate, I will close the issue and answer over at #1847

**Closed as not planned by Jorengarenar** 2022-08-01 15:55 UTC
Labels: enhancement
