### ISSUE TITLE
menu.vim failed  line 122 for non-English locale

### ISSUE THREAD

**Issue by GoogleCodeExporter** [vim/vim#269] opened 2015-08-18 21:08 UTC
```
What steps will reproduce the problem?
1. LANG=zh_TW.UTF-8 gvim -u NONE

What is the expected output? 
No error

What do you see instead?
處理 /usr/share/vim/vim74/menu.vim 時發生錯誤:  (Error on processing 
/usr/share/vim/vim74/menu.vim)
行  122:
E329: No menu "&Print"

What version of the product are you using? On what operating system?
vim-7.4.160 in RHEL7

Actual package is vim-X11-7.4.160-1.el7.x86_64

Please provide any additional information below.
Other locales have same problem:

Japanses:
LANG=ja_JP.UTF-8 gvim -u /tmp/vimrc
/usr/share/vim/vim74/menu.vim の処理中にエラーが検出されました:
行  122:
E329: "&Print" というメニューはありません

Spanish:
LANG=es_ES.UTF-8 gvim -u /tmp/vimrc
Se ha detectado un error al procesar /usr/share/vim/vim74/menu.vim:
línea  122
E329: No existe el menú "&Print"

French:
LANG=fr_FR.UTF-8 gvim -u /tmp/vimrc
Erreur détectée en traitant /usr/share/vim/vim74/menu.vim :
ligne  122 :
E329: Aucun menu "&Print"



```

Original issue reported on code.google.com by `dingyichen` on 15 Oct 2014 at 12:49

**Comment by lacygoill** [comment] 2021-01-28 10:49
I cannot reproduce this on master.  I've generated the chinese, japanese, spanish and french locales on my machine (`$ sudo dpkg-reconfigure locales`), then set all the locale environment variables:

    LANG=zh_TW.UTF-8
    LANGUAGE=zh_TW
    LC_CTYPE="zh_TW.UTF-8"
    LC_NUMERIC=zh_TW.UTF-8
    LC_TIME=zh_TW.UTF-8
    LC_COLLATE="zh_TW.UTF-8"
    LC_MONETARY=zh_TW.UTF-8
    LC_MESSAGES="zh_TW.UTF-8"
    LC_PAPER=zh_TW.UTF-8
    LC_NAME=zh_TW.UTF-8
    LC_ADDRESS=zh_TW.UTF-8
    LC_TELEPHONE=zh_TW.UTF-8
    LC_MEASUREMENT=zh_TW.UTF-8
    LC_IDENTIFICATION=zh_TW.UTF-8
    LC_ALL=

After starting Vim with no config, the menu items are correctly displayed in chinese characters, including the one to print.  Same thing for the japanese, spanish and french locales.

One thing I've noticed though, is that I couldn't reproduce the issue on 7.4.160 either, even though I made sure to use the old runtime files:

    set rtp-=~/.vim
    set rtp-=~/.vim/after
    set rtp^=~/Vcs/vim/runtime
    let $VIMRUNTIME = $HOME . '/Vcs/vim/runtime'
    let $VIM = $VIMRUNTIME
    set hf=~/Vcs/vim/runtime/doc/help.txt

**Comment by chrisbra** [comment] 2021-01-28 11:00
closing then.

**Closed as completed by chrisbra** 2021-01-28 11:00 UTC
Labels: Priority-Medium, defect, auto-migrated, runtime
