### ISSUE TITLE
Indentation in HTML scripts goes wrong

### ISSUE THREAD

**Issue by eight04** [vim/vim#9333] opened 2021-12-12 00:18 UTC
### Steps to reproduce

1. Start vim: `vim --clean`
2. Edit a new HTML file: `:e test.html`
3. Paste following code in insert mode:
    ```html
    <script>
    foo({
    a,
    b,
    c
    });
    </script>
    ```
    
Result:
```html
<script>
	foo({
			a,
			b,
			c
		});
</script>
```

### Expected behaviour

It seems that it works fine by running the following command before step 2:
```vim
:let g:html_indent_script1 = "zero"
```
Result:
```html
<script>
foo({
	a,
	b,
	c
});
</script>
```
Should `zero` be the default?

### Operating system

Windows 10 x64

### Version of Vim

8.2.3582

**Comment by matveyt** [comment] 2021-12-12 16:26
>Should zero be the default?

`:h ft-html-indent` states so. But it is set to `inc` on purpose here: [`$VIMRUNTIME/indent/javascript.vim:35`](https://github.com/vim/vim/blob/6e371ecb27227ff8fedd8561d0f3880a17576848/runtime/indent/javascript.vim#L35)

No idea which is "the right one".

**Comment by chrisbra** [comment] 2022-03-12 17:02
related or possibly a duplicate of 8997

please report at the upstream repository: https://github.com/pangloss/vim-javascript

**Closed as completed by chrisbra** 2022-03-12 17:02 UTC
