### ISSUE TITLE
:Vex and :Sex have unexpected save behaviour

### ISSUE THREAD

**Issue by guillefix** [vim/vim#5178] opened 2019-11-05 12:33 UTC
I have found that when using :Vex and :Sex to split the window the second file you open doesn't save its changes.

**To Reproduce**
Detailed steps to reproduce the behavior:

Assume three files: `a`, `b`, and `c`
You open a (`vim a`), split vertically (`:Vex`), then open b, split horizontally (`:Sex`), and open c.
You then edit the three files, and save by `ZZ` the three files, in any order.
Then, file `b` doesn't save its changes.

I have tried this a few times, and it seems to always happen. It also happens if you split horizontally and then vertically. It is always the second file you open.

**Expected behavior**
Obviously the expected behaviour is for all the files to be saved. This is indeed what happens if you do as above, but using `ctrl+w+s` and `ctrl+w+v` for horizontal and vertical splits, and then open the files using `:e [file]`

**Environment (please complete the following information):**

`vim --version`:

```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jun 06 2019 17:31:41)
Included patches: 1-1453
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by pkg-vim-maintainers@lists.alioth.debian.org
Huge version without GUI.  Features included (+) or not (-):
+acl               +farsi             +mouse_sgr         -tag_any_white
+arabic            +file_in_path      -mouse_sysmouse    -tcl
+autocmd           +find_in_path      +mouse_urxvt       +termguicolors
-autoservername    +float             +mouse_xterm       +terminal
-balloon_eval      +folding           +multi_byte        +terminfo
+balloon_eval_term -footer            +multi_lang        +termresponse
-browse            +fork()            -mzscheme          +textobjects
++builtin_terms    +gettext           +netbeans_intg     +timers
+byte_offset       -hangul_input      +num64             +title
+channel           +iconv             +packages          -toolbar
+cindent           +insert_expand     +path_extra        +user_commands
-clientserver      +job               -perl              +vertsplit
-clipboard         +jumplist          +persistent_undo   +virtualedit
+cmdline_compl     +keymap            +postscript        +visual
+cmdline_hist      +lambda            +printer           +visualextra
+cmdline_info      +langmap           +profile           +viminfo
+comments          +libcall           -python            +vreplace
+conceal           +linebreak         +python3           +wildignore
+cryptv            +lispindent        +quickfix          +wildmenu
+cscope            +listcmds          +reltime           +windows
+cursorbind        +localmap          +rightleft         +writebackup
+cursorshape       -lua               -ruby              -X11
+dialog_con        +menu              +scrollbind        -xfontset
+diff              +mksession         +signs             -xim
+digraphs          +modify_fname      +smartindent       -xpm
-dnd               +mouse             +startuptime       -xsmp
-ebcdic            -mouseshape        +statusline        -xterm_clipboard
+emacs_tags        +mouse_dec         -sun_workshop      -xterm_save
+eval              +mouse_gpm         +syntax            
+ex_extra          -mouse_jsbterm     +tag_binary        
+extra_search      +mouse_netterm     +tag_old_static    
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -Wdate-time  -g -O2 -fdebug-prefix-map=/build/vim-8l5tlu/vim-8.0.1453=. -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim        -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl     -L/usr/lib/python3.6/config-3.6m-x86_64-linux-gnu -lpython3.6m -lpthread -ldl -lutil -lm      
```

 - OS: Ubuntu 18.04.2
 - Terminal: bash

**Comment by chrisbra** [comment] 2019-11-05 12:40
I cannot reproduce this. Please try with an updated Vim (and possibly also an updated netrw: http://www.drchip.org/astronaut/vim/#NETRW)

**Comment by guillefix** [comment] 2019-11-05 12:49
Hmm, yeah this doesn't seem to happen in another installation with vim with "Included patches: 1-1766". I guess one of those patches fixed it?

**Comment by chrisbra** [comment] 2019-11-05 12:59
I don't remember a patch regarding that `ZZ` did not work, but as this seems to be netrw related, a runtime file updated might have also fixed it. Closing then.

**Closed as completed by chrisbra** 2019-11-05 12:59 UTC
Labels: plugin-netrw
