### ISSUE TITLE
jump to end of line is not working in a script

### ISSUE THREAD

**Issue by cridemichel** [vim/vim#13993] opened 2024-02-08 13:09 UTC
### Steps to reproduce

1. create the file "vim_minrc" with the following content
```viml
set nocompatible
set encoding=utf-8
set langmenu=en_US.UTF-8
language messages en_US.UTF-8
filetype on
function! ToLastCol()
  exe 'normal! $'
  return
endfunction
au FileType text inoremap <silent> <Tab> <Cmd>call ToLastCol()<CR>
```
2. create a file called "check.txt"
3. open file "check.txt" with the command
```
> vim -u vim_minrc check.txt
```
4. Enter "insert mode" by pressin 'i'
5. Press <Tab>
6. cursor move to column before last column, while it should be placed at the last column. 
    Indeed, if one type "<C-O>$" cursor correctly jump to last column

Note that if one replaces "vim_minrc" with the following one
```viml
set nocompatible
set encoding=utf-8
set langmenu=en_US.UTF-8
language messages en_US.UTF-8
filetype on
function! ToLastCol()
  exe 'normal! $'
  return
endfunction
au FileType text inoremap <silent> <Tab> <C-O>:call ToLastCol()<CR>
```
 vim works as expected, i.e. cursor jump to last column.

### Expected behaviour

in both cases cursor should jump to last column

### Version of Vim

9.1.50

### Environment

OS: mac osx sonoma 14.3
TERMINAL: iterm2 3.4.23
$TERM: xterm-256color
SHELL: zsh 5.9 (x86_64-apple-darwin21.3.0)

### Logs and stack traces

```shell
full output of ":version"

VIM - Vi IMproved 9.1 (2024 Jan 02, compiled Jan 23 2024 22:19:02)
macOS version - x86_64
Included patches: 1-50
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl               +cryptv            +fork()            +modify_fname      +persistent_undo   -sun_workshop      +viminfo
+arabic            +cscope            +gettext           +mouse             +popupwin          +syntax            +virtualedit
+autocmd           +cursorbind        -hangul_input      -mouseshape        +postscript        +tag_binary        +visual
+autochdir         +cursorshape       +iconv             +mouse_dec         +printer           -tag_old_static    +visualextra
-autoservername    +dialog_con        +insert_expand     -mouse_gpm         +profile           -tag_any_white     +vreplace
-balloon_eval      +diff              +ipv6              -mouse_jsbterm     -python            -tcl               +wildignore
+balloon_eval_term +digraphs          +job               +mouse_netterm     +python3           +termguicolors     +wildmenu
-browse            -dnd               +jumplist          +mouse_sgr         +quickfix          +terminal          +windows
++builtin_terms    -ebcdic            +keymap            -mouse_sysmouse    +reltime           +terminfo          +writebackup
+byte_offset       +emacs_tags        +lambda            +mouse_urxvt       +rightleft         +termresponse      -X11
+channel           +eval              +langmap           +mouse_xterm       +ruby              +textobjects       -xattr
+cindent           +ex_extra          +libcall           +multi_byte        +scrollbind        +textprop          -xfontset
-clientserver      +extra_search      +linebreak         +multi_lang        +signs             +timers            -xim
+clipboard         -farsi             +lispindent        -mzscheme          +smartindent       +title             -xpm
+cmdline_compl     +file_in_path      +listcmds          +netbeans_intg     +sodium            -toolbar           -xsmp
+cmdline_hist      +find_in_path      +localmap          +num64             +sound             +user_commands     -xterm_clipboard
+cmdline_info      +float             +lua               +packages          +spell             +vartabs           -xterm_save
+comments          +folding           +menu              +path_extra        +startuptime       +vertsplit
+conceal           -footer            +mksession         +perl              +statusline        +vim9script
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H -DMACOS_X -DMACOS_X_DARWIN -g -O2 -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: clang -L/usr/local/lib -o vim -lm -lncurses -lsodium -liconv -lintl -framework AppKit -L/usr/local/opt/lua/lib -llua5.4 -mmacosx-vers
ion-min=14.2 -fstack-protector-strong -L/usr/local/lib -L/usr/local/opt/perl/lib/perl5/5.38/darwin-thread-multi-2level/CORE -lperl -L/usr/loca
l/opt/python@3.12/Frameworks/Python.framework/Versions/3.12/lib/python3.12/config-3.12-darwin -lpython3.12 -framework CoreFoundation -lruby.3.
3 -L/usr/local/Cellar/ruby/3.3.0/lib

```
```

**Comment by zeertzjq** [comment] 2024-02-08 13:29
I think you have a misunderstand of what "last column" means. In the `<Cmd>` case the cursor is "at the last column", and in the `<C-O>` case the cursor is "after the last column", which is a special case of Ctrl-O.

**Comment by cridemichel** [comment] 2024-02-08 13:38
I agree that I meant “after the last column", but effect of “$” shouldn’t be the same in both cases?

Cristiano De Michele
***@***.***

**Comment by zeertzjq** [comment] 2024-02-08 13:42
The effect of `$` is the same. If you add a command that gets cursor position after the `:normal! $` in `ToLastCol()` you will se that. The difference is caused by the return from i_CTRL-O.

**Comment by cridemichel** [comment] 2024-02-08 14:30
assume that contento of file "check.txt" is: 
```text
hallo
```
open it with minimal rc files above, where exec instruction is replaced with
```
exe 'normal! 2|'
```
in this case by pressing <Tab> cursor jumps to letter "a".
Anyway, if I replace '2' with '6', I have cursor at "o" (<Cmd>) or at position after last cursor (<C-O>).
Even I do not like this behavior, is it what is expected?

**Comment by chrisbra** [comment] 2024-02-08 16:37
What you call last column in insert mode, is really not there yet. Technically, the column does not yet exists yet *until* you press a key so that something will be inserted at that specific column. So what you want is to place the cursor *after* the last available column, which usually is only possible  in insert mode. This is more apparent, if you use a block cursor, while Vim in insert mode often uses a thin line and makes it look like the cursor is between 2 columns (however, there is no room between 2 adjacent columns, so this not possible). If you use a block cursor, you will see, that your `<cmd>` mapping is correctly placing the cursor on the last available column.

Hoewver, for `i_Ctrl-O`, Vim contains some special logic, to allow the cursor being placed one column to the right of the last available cursor. So I would say, if you want to place the cursor after the last existing column in insert mode, please use `i_CTRL-O`.

**Comment by cridemichel** [comment] 2024-02-08 17:06
> What you call last column in insert mode, is really not there yet. Technically, the column does not yet exists yet _until_ you press a key so that something will be inserted at that specific column. So what you want is to place the cursor _after_ the last available column, which usually is only possible in insert mode. This is more apparent, if you use a block cursor, while Vim in insert mode often uses a thin line and makes it look like the cursor is between 2 columns (however, there is no room between 2 adjacent columns, so this not possible). If you use a block cursor, you will see, that your `<cmd>` mapping is correctly placing the cursor on the last available column.
> 
> Hoewver, for `i_Ctrl-O`, Vim contains some special logic, to allow the cursor being placed one column to the right of the last available cursor. So I would say, if you want to place the cursor after the last existing column in insert mode, please use `i_CTRL-O`.

thank you for the clear explanation, the real motivation for what I asked is that I added this to my .vimrc:
```viml

" this function mimick behavior of emacs <Tab> and actual behavior of <Tab> for C, C++ in vim
function! IndentLikeC()
  " get current column of cursor 
  let curposbef = virtcol('.')

  " get current column of last char in current line before indentation
  let lastcolbef = virtcol('$')
  
  "autoindent
  exe 'normal! =='

  " get current column of last char in current line after indentation
  let lastcolaft = virtcol('$')

  " calculate shift due to indentation
  let sw = lastcolaft - lastcolbef

  " set cursor position accounting for shift (sw) due to indentation

  exe 'normal!'.(curposbef+sw).'|'
  "call feedkeys("\<C-O>".(curposbef+sw).'|')

  "echom 'cp '.curposbef.' bef '.lastcolbef.' aft '.lastcolaft.' newpos='.virtcol('.') 
  "using <Cmd> in autocmd places cursor on the last column
  if curposbef == lastcolbef && virtcol('.') == lastcolaft - 1
     call feedkeys("\<Right>",'n')
  endif 
  return
endfunction

"emulate emacs before (in C, C++ is already like this thanks to cindent autoindentation)
" autoindent and go back to initial position (`^ is the position of cursor last inser mode was stopped)

"<cmd> allows to map a key to a command 
au FileType vim,python,tex,sh,fortran inoremap <silent> <Tab> <Cmd>call IndentLikeC()<CR>
```
which emulates the behavior of Emacs \<Tab\> for languages other than C/C++ (for which I can do the same by using "cinkeys").  I do not want to use \<C-O\>  in the "autocmd", since it changes cursor shape to block one and I do not like the resulting "flickering".
Hence, to avoid using \<C-O\>, as you can see, the workaround is to move left the cursors if it was on column-after-last-one.

**Comment by chrisbra** [comment] 2024-02-09 17:08
I have no idea what `<Tab>` is doing in Emacs. Note you can probably change the cursor style either using ansi terminal escape sequences or using the 'guicursor' setting for the GUI (if that bothers you).

You can also try to use: `:set ve=onemore` and then make your function do:
```
norm! $l
```
which would jump to the last existing column, and then one more to the left. It seems that is what your are after.

**Comment by chrisbra** [comment] 2024-02-09 17:33
you of course need `:set ve=onemore` as suggested.

**Comment by cridemichel** [comment] 2024-02-09 17:58
> you of course need `:set ve=onemore` as suggested.

you are right, I overlooked the `:set ve=onemore`, now it works as expected!

best C.

**Closed as not planned** 2024-02-09 19:10 UTC
Labels: bug
