### ISSUE TITLE
Vim clone left "dirty" after make. src/po/ru.cp1251.po is modified.

### ISSUE THREAD

**Issue by errael** [vim/vim#14490] opened 2024-04-10 17:24 UTC
### Steps to reproduce

I occasionally see this, and I think I've seen mention of this on the dev list; it might always be the same file; this morning I happened to catch it just after it happened. I also built yesterday morning. It doesn't happen too often (the revert file I see is from January), I haven't looked at makefiles, I don't know what dependency is triggering.

If anyone knows something specific to check...

After pull, make reconfig, the console shows the make ending as:
```
...
OLD_PO_FILE_INPUT=yes msgfmt -v -o vi.mo vi.po
1410 translated messages.
OLD_PO_FILE_INPUT=yes msgfmt -v -o zh_CN.UTF-8.mo zh_CN.UTF-8.po
2800 translated messages.
OLD_PO_FILE_INPUT=yes msgfmt -v -o zh_TW.UTF-8.mo zh_TW.UTF-8.po
1410 translated messages.
make[2]: Leaving directory '/ref/vim/src/po'
make[2]: Entering directory '/ref/vim/src/po'
OLD_PO_FILE_INPUT=yes msgfmt -v -o cs.cp1250.mo cs.cp1250.po
1272 translated messages.
...
OLD_PO_FILE_INPUT=yes msgfmt -v -o pl.cp1250.mo pl.cp1250.po
1858 translated messages.
rm -f ru.cp1251.po
iconv -f UTF-8 -t CP1251 ru.po | \
	LANG=C sed -e 's/charset=[uU][tT][fF]-8/charset=CP1251/' \
		-e 's/# Original translations/# Generated from ru.po, DO NOT EDIT/' \
		> ru.cp1251.po
OLD_PO_FILE_INPUT=yes msgfmt -v -o ru.cp1251.mo ru.cp1251.po
2979 translated messages.
...
make[2]: Leaving directory '/ref/vim/src/po'
make[1]: Leaving directory '/ref/vim/src'
err@harmony:/ref/vim/src
$ hg st
M src/po/ru.cp1251.po
```

The diff seems to be a lot of formatting. Here's an excerpt, as seen in vim.
```
-"W17: Äëÿ ðàáîòû ñ àðàáñêîé ïèñüìåííîñòüþ ââåäèòå êîìàíäó `:set "
-"encoding=utf-8`"
+"W17: Äëÿ ðàáîòû ñ àðàáñêîé ïèñüìåííîñòüþ ââåäèòå êîìàíäó `:set encoding=utf-8`"
```
It interesting that the wrap, as shown in vim above, is happening right around column 80. With all these formatting changes it's hard to see if there are any real changes.

Using `gvim -d` to look at the checked in file and the it looks like the only changes are around the linebreak and that the translation itself has no changes.

![vdiff-translation](https://github.com/vim/vim/assets/20450427/291949c1-8dc4-4e84-9256-ed019efd4193)

### Expected behaviour

No modified checked-in file.

### Version of Vim

9.1.0299

### Environment

ubuntu/gtk

**Comment by RestorerZ** [comment] 2024-04-10 18:50
Hmm, interesting! Do you have this happen sometimes, and always on this file?
I'm going to try building in MS Windows now - it's fine. 
I'll check what's wrong with this file. If there is something wrong with it.

**Comment by errael** [comment] 2024-04-10 19:30
> Hmm, interesting! Do you have this happen sometimes, 

I see it every month or two

> and always on this file? 

Not sure, maybe.

For reference, take a look at https://groups.google.com/g/vim_dev/c/Gyqie6FQM4s/m/W2yZLzsuAwAJ from December, other people see this once and a while.

> I'm going to try building in MS Windows now - it's fine. I'll check what's wrong with this file. If there is something wrong with it.
> 
> Can you please tell me what your gettext is? Version and so on...

I built with current source this morning.

**Comment by RestorerZ** [comment] 2024-04-10 20:00
Okay, thank you!
I have a rough idea of what it could be related to.
From the dates you gave, it seems to happen when translations are updated periodically.
Okay, let's try to figure it out.

**Comment by RestorerZ** [comment] 2024-04-10 20:06
Based on this line `OLD_PO_FILE_INPUT=yes msgfmt -v -o vi.mo vi.po`, you are using the "gettext" version before 0.22.

**Comment by julio-b** [comment] 2024-04-10 20:10
I have also been bothered by this and i ended up just compiling with `--disable-nls`.
But here is what is happening and how to trigger this bug reliably.

I will take as an example commit 8fcc12977 because it is the more recent one, but it could be any commit that updates the translation files.

To reproduce:
1. run this one-liner until you see that src/po/ru.po is newer than src/po/ru.cp1251.po
  `$ git checkout 8fcc12977~ && ls -la --time-style=full-iso src/po/ru*po && git checkout master && ls -la --time-style=full-iso src/po/ru*po`
Example output on my fourth run:
```
HEAD is now at c9ec20d94 runtime(doc): Update documentation
-rw-r--r-- 1 ju ju 410K 2024-04-10 22:43:04.013415053 +0300 src/po/ru.cp1251.po
-rw-r--r-- 1 ju ju 539K 2024-04-10 22:43:04.016748378 +0300 src/po/ru.po
Previous HEAD position was c9ec20d94 runtime(doc): Update documentation
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
-rw-r--r-- 1 ju ju 413K 2024-04-10 22:43:04.050081632 +0300 src/po/ru.cp1251.po
-rw-r--r-- 1 ju ju 543K 2024-04-10 22:43:04.053414958 +0300 src/po/ru.po
```
notice how ru.po timestamp is newer by a few MS

2. run `$ make`

Explanation:
- You pull a commit that updates some translation files e.g src/po/ru.po and src/po/ru.cp1251.po
- when this commit is applied, the timestamp of ru.po could end up by a few milliseconds newer than ru.cp1251.po. This can happen randomly and it's unpredictable. It's more noticeable when the cpu is under heavy load.
- now make detects that ru.cp1251.po file is older and triggers the iconv rule [here](https://github.com/vim/vim/blob/1817ccdb107ceeaf5c48fe193da5146682c15ca6/src/po/Makefile#L218-L223)
- iconv is not really consistent between systems, so the results you get may be different. I think it's behavior depends on LC_ environmental variables  and there are different implementations for windows.

This possible for any translation file that uses iconv, listed in [here](https://github.com/vim/vim/blob/1817ccdb107ceeaf5c48fe193da5146682c15ca6/src/po/Makefile#L104-L232).

**Comment by errael** [comment] 2024-04-10 20:37
> Based on this line `OLD_PO_FILE_INPUT=yes msgfmt -v -o vi.mo vi.po`, you are using the "gettext" version before 0.22.

I didn't know what you meant by `gettext`, now I see. And you are correct; I guess a lot of people are still using that version.

```
$ gettext --version
gettext (GNU gettext-runtime) 0.21
```

**Comment by errael** [comment] 2024-04-10 20:40
BTW, I use popOS, I update regularly. So I guess their distribution hasn't incorporated the 0.22 version.

**Comment by RestorerZ** [comment] 2024-04-10 20:55
I switched to version 0.22 and use it when preparing translations. Anyway, I'll try to figure out what's going on.

**Comment by benknoble** [comment] 2024-04-10 23:25
> 1. run this one-liner until you see that src/po/ru.po is newer than src/po/ru.cp1251.po
>    `$ git checkout 8fcc12977~ && ls -la --time-style=full-iso src/po/ru*po && git checkout master && ls -la --time-style=full-iso src/po/ru*po`

Probably it would have been simpler to
```
git checkout <REF>
touch src/po/ru.po
```
to force the “newer” timestamp (for reproduction; your method is nice to explain how Git might leave the timestamps in an unexpected state).

**Comment by julio-b** [comment] 2024-04-11 03:28
> Probably it would have been simpler to
> 
> ```
> git checkout <REF>
> touch src/po/ru.po
> ```
> 
> to force the “newer” timestamp (for reproduction; your method is nice to explain how Git might leave the timestamps in an unexpected state).

Right, I wanted to show how this could be triggered just by using a simple git pull, without any special modification on the .po file itself. But for a fast reproduction a simple `touch ru.po` is all you need!

I debugged this a bit more and now i think know for sure what is happening:
- At some point, one of those faulty .po files was generated with msgconv (instead of iconv)
- msgconv, by default, will hard wrap lines at column 80
- So now every time that the iconv rule above is triggered (because of the different timestamp that i explained) the output is not wrapped at column 80

You can verify that by using `$ msgconv -t CP1251 -o /tmp/ru.c1251.po ru.po` and compare it with the current version of this file `$ diff /tmp/ru.c1251.po src/po/ru.c1251.po`. Almost identical, minus a single line that is changed by a simple sed script.

Right now `msgconv` is used only on windows, eg. by [`src/po/Make_mvc.mak`](https://github.com/vim/vim/blob/1817ccdb107ceeaf5c48fe193da5146682c15ca6/src/po/Make_mvc.mak#L425-L450).

Thus there are three fixes required:
1. Make the output of `iconv` and `msconv` equal. Probably by using `msgconv --no-wrap`
2. Fix the files that were generated with `msgconv`
3. And finally find a way for `make` to not trigger the iconv rule randomly. For gnu version of `make` this is done with `.LOW_RESOLUTION_TIME`, but i don't know if it is portable for other versions.

(3) is technically not required if (1,2) are fixed because the output will always be the same, but still worth fixing it so we don't waste time regenerating those files.

I hope this helps!

**Comment by k-takata** [comment] 2024-04-11 03:45
If `make ru` is executed in `src/po/` and `cleanup.vim` is applied, `ru.po` will be wrapped in 80 columns.
Then, `make ru.cp1251.po` is executed, `ru.cp1251.po` will be also wrapped in 80 columns.

All of (or most of) the other po files are wrapped in 80 columns. So, I think `ru*.po` should be also wrapped in 80 columns.

**Comment by RestorerZ** [comment] 2024-04-18 19:49
> I have also been bothered by this and i ended up just compiling with `--disable-nls`.

By default, when Vim is built, PO files in the "src/po" directory are processed.

https://github.com/vim/vim/blob/133ed2a592e4d7998a8f6afa3de9f057feb23f0a/src/configure.ac#L4497C4-L4500C23

https://github.com/vim/vim/blob/1433ac93eb3acf28c55f0c4d775716ebee543160/src/Makefile#L2068C1-L2078C4

If you don't need this, you can use this command:
```
[./configure [switch] &&] make "MAKEMO="
```
This will cut through the PO file processing and does not require you to change
the "./configure" preset.

> now make detects that ru.cp1251.po file is older and triggers the iconv rule here
> So now every time that the iconv rule above is triggered (because of the different timestamp that i explained)

When checking on the host and stand systems, no big differences in time stamps
exceeding 2-second intervals were noticed. However, when the time difference was
close to 1-second in tenths of seconds, some files were converted on the stand
system. The situation was similar on the host system when the "/B" switch for
"nmake.exe" was used. Unfortunately, the exact relationship could not be
established. We can conclude that "make" uses a 1-second time interval to check
timestamps and when transferring from one system (host) to another (stand),
there is a rounding error.
To minimize these differences, the `$(PS) $(PSFLAGS) Set-ItemProperty -Path '.\$@' -Name LastWriteTime -Value (Get-Date)`
command was added to the "Make_mvc.mak" file, which is executed after the
PO-files conversion is completed.

> If `make ru` is executed in `src/po/` and `cleanup.vim` is applied, `ru.po` will be wrapped in 80 columns.

Unfortunately, that doesn't always happen.

The illustration below shows the file created by `msgmerge --no-wrap` before
`cleanup.vim` (bottom) and after (top).

![cleanup](https://github.com/vim/vim/assets/69863286/d72ae46d-5258-49c7-9ced-b3846d961fc6)

> The diff seems to be a lot of formatting.

The difference in formatting between "ru.po" and "ru.cp1251.po" is probably
because I used "Make_mvc.mak" to prepare "ru.po" and my own makefile for
"ru.cp1251.po", where "msgconv" and "msgmerge" are set to text width.

> All of (or most of) the other po files are wrapped in 80 columns.  

Also, the check revealed that almost all PO files have different text
formatting. This also applies to the files "ru.po" and "ru.cp1251.po".

The illustrations below show the difference in formatting between the original
file (bottom) and the file (top) produced by "msgmerge" with `--width=79`,
`--width=80` and without text width.

msgmerge --width=79
![width79](https://github.com/vim/vim/assets/69863286/961625b7-3769-40c5-b2f2-363a5450dadd)
msgmerge --witdth=80
![width80](https://github.com/vim/vim/assets/69863286/375f3b86-2c3f-4bd6-bf5c-abb257c8c491)
msgmerge
![noswitch](https://github.com/vim/vim/assets/69863286/c3ea8dfb-9549-48ff-8036-21290918e75f)

The following was done to utilize uniform text formatting:
- All existing PO files were reformatted to text width 79.
- The modeline `vim:tw=79:ts=8:ft=po:` was added to the PO files
- In Makefile and Make_mvc.mak, the switch `--width=79` is set for "msgmerge"
  and "xgettex". And the same switch is set for "msgconv" in Make_mvc.mak.

> iconv is not really consistent between systems, so the results you get may be different. I think it's behavior depends on LC_ environmental variables and there are different implementations for windows.

No influence on text formatting from the "iconv" program and its analog from
"powershell" commands was detected. The output text is in the same format as the
input.

Hopefully, these steps will help eliminate unplanned processing of PO files.

> Right now `msgconv` is used only on windows

It might be worth using the "msgconv" tool in the Makefile too.

Pros:
- "Native" tool for the gettext package;
- Automatic setting of the correct encoding name in the "charset" field and
  avoiding additional processing with the "sed" tool;
- Additional check of the correctness of the processed PO file;
- Unified tool for all systems.

Cons:
- Everyone is used to "iconv";
- ???.

What do you think about it, @k-takata , @chrisbra ?

**Comment by julio-b** [comment] 2024-04-19 02:47
> > iconv is not really consistent between systems, so the results you get may be different. I think it's behavior depends on LC_ environmental variables and there are different implementations for windows.
> 
> No influence on text formatting from the "iconv" program and its analog from "powershell" commands was detected. The output text is in the same format as the input.
> 

Yeah sorry, i was wrong here. This was simply a wild guess I made because had no idea that windows makefiles may use `msgconv`.


> We can conclude that "make" uses a 1-second time interval to check timestamps

This 1-second timestamp interval must specific to your system and not how `make` implementations work generally. Maybe either nmake.exe or windows is doing something weird? I don't know. Usually `make` uses high precession timestamps to determine if a target is up to date and every millisecond matters.

**Comment by RestorerZ** [comment] 2024-04-20 11:36
@julio-b 

> This was simply a wild guess I made because had no idea that windows makefiles may use `msgconv`.

It needed to be verified one way or another and it's good that you brought it to
your attention.

> This excellent explanation by the maintainer of GNU make may clear up some confusion: https://lists.gnu.org/archive/html/help-make/2001-04/msg00047.html
> Also this manual from autoconf might be useful: https://www.gnu.org/software/autoconf/manual/autoconf-2.63/html_node/Timestamps-and-Make.html

Thanks for the links to useful descriptions of how the make program works.

**Comment by k-takata** [comment] 2024-08-10 06:15
@RestorerZ 
The issue happens only in ru.cp1251.po. 
Adding the `--width=79` option to msgmerge only in Make_mvc.mak looks good to minimize the effect only in the ru files.
Each translation file should be maintained by each maintainer. I don't want to apply `--with=79` without the agreements from the maintainers.

BTW, which version of gettext tools are you using?
I always use gettext from Cygwin or MSYS2, but they don't work with Make_mvc.mak.

**Comment by k-takata** [comment] 2024-08-10 06:52
Ahh, no, I misunderstood the cause of the ru.cp1251.po issue.

`Makefile` uses icov to convert ru.po to ru.cp1251.po. So, it will not change the width of the file.
However, `Make_mvc.mak` uses msgconv to convert it and msgconv changes the width. The file that was converted by msgconv is committed to the repository. So, it is different from the result of iconv.

So, the solution might be:
1. Don't use msgconv in Make_mvc.mak. Or,
2. Add `--width=79` option to msgconv when converting to ru.cp1251.po.

**Comment by k-takata** [comment] 2024-08-10 08:13
msgconv may also remove unused messages and it causes additional differences even if `--width=79` is specified.
Stop using msgconv seems the best way to solve this: #15469

BTW, I found that changing `copy /a` to `copy /b` makes Make_mvc.mak work with Cygwin/MSYS2's gettext. (`copy /a` appends ^Z at the end of the file and it cannot be handled by Cygwin/MSYS2's gettext.)

```diff
--- a/src/po/Make_mvc.mak
+++ b/src/po/Make_mvc.mak
@@ -500,7 +500,7 @@ files: $(PO_INPUTLIST)
 first_time: files
 	"$(VIMPROG)" -u NONE --not-a-term -S tojavascript.vim $(LANGUAGE).po \
 		$(PO_VIM_INPUTLIST)
-	@ copy /a .\files+.\vim_to_js .\allfiles
+	@ copy /b .\files+.\vim_to_js .\allfiles
 	set OLD_PO_FILE_INPUT=yes
 	set OLD_PO_FILE_OUTPUT=yes
 	$(XGETTEXT) --default-domain=$(LANGUAGE) --add-comments $(XGETTEXT_KEYWORDS) \
@@ -512,7 +512,7 @@ first_time: files
 $(PACKAGE).pot: files
 	"$(VIMPROG)" -u NONE --not-a-term -S tojavascript.vim $(PACKAGE).pot \
 		$(PO_VIM_INPUTLIST)
-	@ copy /a .\files+.\vim_to_js .\allfiles
+	@ copy /b .\files+.\vim_to_js .\allfiles
 	set OLD_PO_FILE_INPUT=yes
 	set OLD_PO_FILE_OUTPUT=yes
 	$(XGETTEXT) --default-domain=$(PACKAGE) --output=$(PACKAGE).pot \
```

**Comment by RestorerZ** [comment] 2024-08-10 08:15
@k-takata , the reasons for this behavior and not only for "ru-cp1251.po" but
for all other PO files were pointed out by @julio-b  in [this comment](https://github.com/vim/vim/pull/14601#issuecomment-2073353765).
I, for my part, can confirm this for Windows on versions 0.21 [from here](https://git.savannah.gnu.org/gitweb/?p=gettext.git;a=blob;f=gettext-tools/src/write-po.c;h=eeb190a0ed0b7b908f797fb5343b8c5849629055;hb=HEAD#l653) and
0.22.3 [from here](https://github.com/vslavik/gettext-tools-windows/releases), and for Ubuntu 22 and FreeBSD 14.

Using the `--width=79` switch does not solve the problem. This is evident from
this [pull request](https://github.com/vim/vim/pull/14601).

To solve this problem, I planned the following:
1. Create a Vim script and implement in it the string wrapping algorithm from
[this](https://git.savannah.gnu.org/gitweb/?p=gettext.git;a=blob;f=gettext-tools/src/write-po.c;h=eeb190a0ed0b7b908f797fb5343b8c5849629055;hb=HEAD#l653) gettext function.
2. In make-files, when creating PO files, use the `--no-wrap` key and then apply
the string wrap script to the created files.
3. When converting PO files, avoid using "msgconv" and use "iconv" or, in
Windows, the powershell command.

Only in this case you can guarantee a uniform content of PO files, independent
of the version of "gettext" used.

Unfortunately, I don't have much free time right now to write such a Vim script.
Also, I don't know VimL well enough to do it quickly.
If you, Takata-san, or anyone else has the ability to write such a script, it
would solve our problem.

**Comment by RestorerZ** [comment] 2024-08-10 08:21
> BTW, I found that changing copy /a to copy /b makes Make_mvc.mak work with Cygwin/MSYS2's gettext. (copy /a appends ^Z at the end of the file and it cannot be handled by Cygwin/MSYS2's gettext.)

Yeah, thanks! Didn't know about such a feature (bug?) Cygwin. I will fix it now.

**Comment by k-takata** [comment] 2024-08-10 08:41
> I, for my part, can confirm this for Windows on versions 0.21 [from here](https://git.savannah.gnu.org/gitweb/?p=gettext.git;a=blob;f=gettext-tools/src/write-po.c;h=eeb190a0ed0b7b908f797fb5343b8c5849629055;hb=HEAD#l653) and
> 0.22.3 [from here](https://github.com/vslavik/gettext-tools-windows/releases), and for Ubuntu 22 and FreeBSD 14.

Thanks. I've just confirmed #15469 with https://github.com/vslavik/gettext-tools-windows/releases .
It also works with `copy /b`, so I merged the above patch into #15469.

Conclusions:
`ru.po` is updated manually (mainly by you) and it is not so important if the width is 79 or not.
`ru.cp1251.po` is automatically updated within the build process on Unix-like systems by using iconv.
However, the file in the repository was converted by using msgconv. msgconv can generate the different file from iconv.
So, stop using msgconv completely solves the issue. (and #14601 is not needed anymore.)

**Comment by RestorerZ** [comment] 2024-08-10 08:57
Yes, "msgconv" contributes to string wrapping, I agree with you.
But otherwise, unfortunately, the problem remains.
If the versions of "gettext" (or rather the library) are different on different machines, the problem will persist.

**Comment by k-takata** [comment] 2024-08-10 09:31
How does it happen?
Original translation files (e.g. ru.po) are updated manually. So, if the maintainer updated the original file and the converted one in the same commit, the mismatch between them won't happen.
The problem is that the converted files are different depending on the environment.

**Comment by RestorerZ** [comment] 2024-08-10 17:02
Yes, Takata-san, I agree with you. I have now checked on Windows gettext versions 21 and 22, Ubuntu gettext ver. 21 and FreeBSD gettext 22. The "msgconv" formatting of the text is different from the original file generated by "xgettext". And there is a difference between the versions of "msgconv". And there are differences in formatting of "xgettext" text in version 21 and in version 22.
(By the way, file conversion does not work on FreeBSD. Need to change the `$<` variable to `$?`).

**Closed as completed** 2024-08-11 17:08 UTC
Labels: translation, bug
