### ISSUE TITLE
zero width non-joiner (ZWNJ) renders as its Unicode codepoint <200c>

### ISSUE THREAD

**Issue by faridcher** [vim/vim#7932] opened 2021-03-04 20:09 UTC
This problem is already reported [here](https://vi.stackexchange.com/questions/17900/how-to-make-vim-display-zwnj-characters-correctly) but the `conceal` solution has side effects and is not desired. The [Gnome terminal with BiDi](https://terminal-wg.pages.freedesktop.org/bidi/) support renders ZWNJ correctly but when I run Vim inside Gnome terminal, it shows ZWNJ as <200c> using the same font; I use [Vazir](https://github.com/rastikerdar/vazir-font) font in the screenshots but the same happens with the ubiquitous  Liberation Mono font.

The word فارس‌ی in Gnome Terminal:

![image](https://user-images.githubusercontent.com/9982519/110022866-b8b2bd80-7d41-11eb-9f0b-bdc3d13e4f01.png)

The same word in Vim run inside Gnome Terminal:
![image](https://user-images.githubusercontent.com/9982519/110022948-cbc58d80-7d41-11eb-92cc-3fcc5c58987b.png)

To reproduce type or copy/paste the word س‌ی  in both the Gnome terminal and Vim to see the differences. A ZWNJ resides between the letters س and ی.

**Comment by mskf1383** [comment] 2022-04-13 11:36
I can reproduce that.

**Comment by chrisbra** [comment] 2024-06-10 18:38
duplicate of #204

**Closed as not planned by chrisbra** 2024-06-10 18:38 UTC
Labels: duplicate

**Comment by avidseeker** [comment] 2024-07-16 13:41
I don't think it's a duplicate. Support for special Unicode character is a different issue from Bidi rendering, despite some overlap (It's better to divide a big topic like bidi into smaller problems anyways). I'd prefer to keep the discussion here to avoid hijacking the original issue.

**Comment by avidseeker** [comment] 2024-07-16 13:43
I think there is a solution that is a middle ground. Not *complete* conceal and not conceal that replaces with whitespace either.

I just noticed this behavior while editing a Vim help file (syntax.txt): Lines such as:

```
TEX				*tex.vim* *ft-tex-syntax* *latex-syntax*
```

have conceal for asterisks `*` that are not shown *unless* in Visual or Insert mode.

**Comment by chrisbra** [comment] 2024-07-16 13:58
That is concealing

**Comment by avidseeker** [comment] 2024-07-16 14:16
It is a stronger type of concealing I just realized is possible in Vim. The conceal I'm used to, at least in LaTeX and Markdown, is that characters are unconcealed as soon as the cursor is in the same line with them. This is not the case with `help` filetype. They are unconcealed only in Visual and Insert modes, and they're not replaced with whitespace characters.

Would it be possible to ship a solution like the one you provided: https://vi.stackexchange.com/questions/17900 to be the default with Vim? Perhaps toggle-able behind a command similar to `:list`. ZWNJ is not the only Unicode control character. There are dozens more: https://en.wikipedia.org/wiki/Category:Control_characters

**Comment by avidseeker** [comment] 2024-07-16 15:38
@faridcher you mentioned that "`conceal` solution has side effects and is not desired". Can you clarify what these unintended side effects are?

**Comment by faridcher** [comment] 2024-07-18 19:21
@avidseeker it hides certain markups. This is of paramount importance while editing plain text dominant files like TeX (as opposed to a programming language). Imagine you had to toggle conceal mode to properly see character "a" in English. The ZWNJ in plain text (conceal=0) is great both for editing as well as reading.

**Comment by avidseeker** [comment] 2024-07-19 01:06
Conceal hides markup? Can you give an example .tex document? 

I think Vim should already have a selective conceal where <ZWNJ> is hidden but markup is not.
