### ISSUE TITLE
Arrow keys cause spurious A, B, C, D characters in classic vi

### ISSUE THREAD

**Issue by alexninja** [vim/vim#10871] opened 2022-08-09 09:16 UTC
### Steps to reproduce

Found on Ubuntu 20.0.4, where vi is a link to /usr/bin/vim.tiny.

1. Uninstall vim `sudo apt purge vim`, leaving only vi
2. Start vi. NB the file/link **must** be called "vi"
3. Enter insert mode
4. Press arrow keys

Observed:
Spurious 'A', 'B', 'C', 'D' characters appear in the buffer.

![image](https://user-images.githubusercontent.com/13776207/183614318-f73a008c-0ac8-4e6d-b482-8175c6065fc6.png)

### Expected behaviour

No spurious characters in the buffer.

### Version of Vim

8.1.3741

### Environment

Ubuntu 20.0.4
Ubuntu terminal, xterm, xfce4-terminal (also PuTTY/MobaXTerm on win10)
$TERM=xterm
$SHELL=/bin/bash

**Comment by chrisbra** [comment] 2022-08-09 09:25
I believe this is what happens, because the terminal send those keys and that's what vi then receives.  Try e.g. in your terminal:

```
cat -A <<EOF
<CTRL-V><type cursor here>
EOF
```
you need to press `CTRL-V` before pressing cursor key, so that the terminal receives those keys literally.

Can you please show the full output of `:vim --version`. I think this works also as expected, if you are not using `vi-compatible` mode.

**Comment by alexninja** [comment] 2022-08-09 09:50
Thank you for your reply.

> Can you please show the full output of `:vim --version`. 

With vim uninstalled, `:vim --version` in vi gives `E319: Sorry, the command is not available in this version`.

> I think this works also as expected, if you are not using `vi-compatible` mode.

Not that I know of, this is just a bone stock Ubuntu install :)

**Comment by chrisbra** [comment] 2022-08-09 10:07
please run `vi --version`

**Comment by chrisbra** [comment] 2022-08-09 10:10
oh sorry, I did not mean to use `:vim` but just `vim --version` (so from a command line terminal, not from vi inside).

Also please see this faq entry here: [When I use my arrow keys, Vim changes modes, inserts weird characters in my document but doesn't move the cursor properly. What's going on?](https://vimhelp.org/vim_faq.txt.html#faq-10.9)

**Comment by alexninja** [comment] 2022-08-09 10:48
```
~$ vi --version
VIM - Vi IMproved 8.1 (2018 May 18, compiled Feb 01 2022 09:16:32)
Included patches: 1-2269, 3612, 3625, 3669, 3741
Modified by team+vim@tracker.debian.org
Compiled by team+vim@tracker.debian.org
Small version without GUI.  Features included (+) or not (-):
+acl               -farsi             -mouse_sysmouse    -tcl
-arabic            -file_in_path      -mouse_urxvt       -termguicolors
+autocmd           -find_in_path      +mouse_xterm       -terminal
-autochdir         -float             +multi_byte        +terminfo
-autoservername    -folding           -multi_lang        +termresponse
-balloon_eval      -footer            -mzscheme          -textobjects
-balloon_eval_term +fork()            -netbeans_intg     -textprop
-browse            -gettext           -num64             -timers
+builtin_terms     -hangul_input      -packages          -title
-byte_offset       +iconv             -path_extra        -toolbar
-channel           +insert_expand     -perl              +user_commands
-cindent           -job               -persistent_undo   -vartabs
-clientserver      +jumplist          -printer           +vertsplit
-clipboard         -keymap            -profile           +virtualedit
+cmdline_compl     -lambda            -python            +visual
+cmdline_hist      -langmap           -python3           +visualextra
-cmdline_info      -libcall           -quickfix          -viminfo
+comments          -linebreak         -reltime           +vreplace
-conceal           -lispindent        -rightleft         +wildignore
-cryptv            +listcmds          -ruby              -wildmenu
-cscope            +localmap          +scrollbind        +windows
+cursorbind        -lua               -signs             +writebackup
-cursorshape       -menu              -smartindent       -X11
-dialog            -mksession         -sound             +xfontset
-diff              +modify_fname      -spell             -xim
-digraphs          +mouse             -startuptime       -xpm
-dnd               -mouseshape        -statusline        -xsmp
-ebcdic            -mouse_dec         -sun_workshop      -xterm_clipboard
-emacs_tags        -mouse_gpm         -syntax            -xterm_save
-eval              -mouse_jsbterm     +tag_binary        
+ex_extra          -mouse_netterm     -tag_old_static    
-extra_search      +mouse_sgr         -tag_any_white     
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -Wdate-time  -g -O2 -fdebug-prefix-map=/build/vim-9EpYYi/vim-8.1.2269=. -fstack-protector-strong -Wformat -Werror=format-security -DTINY_VIMRC -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim    -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo  -lselinux -lacl -lattr -ldl
```

Also, thank you for the link.

**Comment by chrisbra** [comment] 2022-08-09 11:03
so do you have a vimrc? Does it work if you run in non-compatible way? (e.g. `vi -N`)?

**Comment by brammool** [comment] 2022-08-09 11:08
Most likely the cursor keys send codes like <Esc>OA and the termcap isn't matching.
Try ":set termcap" and compare to when using a Vim version that doesn't have this problem.
Check the value of $TERM.

**Comment by alexninja** [comment] 2022-08-09 14:19
@chrisbra 
>so do you have a vimrc? Does it work if you run in non-compatible way? (e.g. vi -N)?
I don't have a .vimrc. `vi -N` exhibits the same behavior.

@brammool 
This happens when vim is uninstalled, leaving only vi (on Ubuntu, it's a link to vim.tiny).
Since 5 different terminals exhibit this issue, I thought it may be caused by vim. Or rather, are the terminals mishandling this rare corner case?

FWIW vi on FreeBSD doesn't have this behavior.

`:set termcap` between {vi without vim installed} and {vi with vim installed} has some minor differences:
Removed:
```
        t_8f=
        t_8b=
```
Added:
```
  t_8f=^[[38;2;%lu;%lu;%lum
  t_8b=^[[48;2;%lu;%lu;%lum
```

$TERM=xterm

**Comment by jamessan** [comment] 2022-08-11 02:01
> 1. Uninstall vim `sudo apt purge vim`, leaving only vi
> 
>     2. Start vi. NB the file/link **must** be called "vi"

This is intentional.  vim.tiny is provided solely so there's a "vi" command in a minimal Debian install.  Therefore, it is customized to behave in "compatible" mode when invoked as vi.  This is why the package doesn't install a /usr/bin/vim symlink.

If you want vim behavior, then install one of the other vim packages, as described in "apt-cache show vim-tiny", ":help", etc.

**Comment by chrisbra** [comment] 2022-08-11 06:11
so let's close this as intended behaviour.

**Closed as completed by chrisbra** 2022-08-11 06:11 UTC
Labels: bug
