### ISSUE TITLE
Concealed characters cause cursor to give wide jumps

### ISSUE THREAD

**Issue by GoogleCodeExporter** [vim/vim#206] opened 2015-08-18 21:07 UTC
```
What steps will reproduce the problem?
1. set virtualedit=all
2. set conceallevel=2
3. set concealcursor=vin
4. syn region placeHolder 
     \matchgroup=placeHolderMark start=+\$`+ 
     \matchgroup=placeHolderMark end=+`+ concealends
5. Paste: $`1`$`2`$`3`$`4`$`5`
6. When the cursor moves past the text, it'll give a wide jump.
7. This is annoying for completion plugins that make use of conceal feature
   when entering text.

What is the expected output? What do you see instead?

I expect concealed text doesn't make the cursor jump randomly.


What version of the product are you using? On what operating system?

Latest Vim built from sources under Ubuntu.


```

Original issue reported on code.google.com by `obl...@gmail.com` on 12 Mar 2014 at 5:09

**Comment by chrisbra** [comment] 2018-12-20 13:50
I think this is a duplicate of #260 
closing therefore.

**Closed as completed by chrisbra** 2018-12-20 13:50 UTC
Labels: Priority-Medium, defect, auto-migrated
