### ISSUE TITLE
[Linux] `$LANG` fallback encoding.

### ISSUE THREAD

**Issue by bartoszek** [vim/vim#8361] opened 2021-06-11 07:12 UTC
**Describe the bug**
`vim` falls back to `latin1` encoding when `$LANG` is set to a locale which isn't generated.

**To Reproduce**
0. generate locale for your system `cat /etc/locale-gen <<<"en_US.UTF-8 UTF-8"; locale-gen`
1. set locale: `export LANG=en_US.UTF-8`
2. run vim and check `set encodeing` you get `utf-8`
3. set locale to a not generated one `export LANG=en_GB.UTF-8`
4. run vim and check `set encodeing` you get `latin1`

**Expected behavior**
`vim` could warn the user that fallback encoding is used for given `$LANG` env var.

**Environment (please complete the following information):**
 - Vim: 8.2
 - OS: Arch, glibc:2.33, gcc:11.1.0
 - Terminal: na

**Comment by brammool** [comment] 2021-06-11 17:26
A warning is only useful if the user has an easy way to avoid it.  Otherwise the warning always shows, which is just annoying.
I am not sure why the user would have an invalid $LANG value.  Could be using a startup script shared with other systems where the locale is installed.
I do not see a clear argument for or against giving a warning,  considering this has not come up before, I prefer to leave it as it is.

**Comment by tonymec** [comment] 2021-06-11 19:07
On my system, en_GB.UTF8 and en_US.UTF8 are undefined but en_GB.utf8 and en_US.utf8 (with utf8 in lowercase) are defined. Getting a warning might point the user toward the existence of a possible parameter error, even a trivial one like defining $LANG (or $LC_CTYPE or whatever) with .UTF8 at the end instead of .utf8, as in this case.

Best regards,
Tony.

**Comment by tonymec** [comment] 2021-06-11 19:32
er, sorry, maybe these strings are case-insensitive.

**Comment by chrisbra** [comment] 2021-07-01 20:52
I suppose, if the user is setting a locale, that is not available on his system, he will get annoyed by other error messages soon enough. Not saying, Vim shouldn't also error, but as mentioned before, this can be really annoying. 
I remember having seen such error messages several 100 times on every invocation of `apt-get install` (I think this was caused by some perl script that was called in turn). And certainly back then I felt overwhelmed and did not know what was expected from me :( 

So let's close it for now.

**Closed as completed by chrisbra** 2021-07-01 20:52 UTC
