### ISSUE TITLE
'incsearch': "\n" highlights the first char in the line below

### ISSUE THREAD

**Issue by lkintact** [vim/vim#6693] opened 2020-08-12 13:15 UTC
**To Reproduce**
1. Run `gvim --clean`
2. Execute `:set incsearch`
3. Put this text to the buffer
```
test
abc
```
4. Type `/test\n`. You should see something like this:
![slash-n](https://user-images.githubusercontent.com/24726299/90018832-35068600-dcb6-11ea-9a31-9d240bc7da18.png)
Notice that `a` in `abc` is highlighted.

**Expected behavior**
`a` shouldn't be highlighted.

**Environment**
 - Vim [8.2.1424](https://github.com/vim/vim-win32-installer/releases/download/v8.2.1424/gvim_8.2.1424_x86_signed.zip)
 - OS: Windows 10 Home 1803
 - Terminal: GUI.

**Comment by chrisbra** [comment] 2020-08-12 13:26
I suppose highlighting the `a` is the only way to make sure that there is actually a line break. Without highlighting the first character on the line, it wouldn't be clear, that the search item spans more than a single line.

**Comment by lkintact** [comment] 2020-08-12 14:06
> I suppose highlighting the `a` is the only way to make sure that there is actually a line break.

Doesn't highlighting the space after `test` serve that purpose?
![slash-en-space](https://user-images.githubusercontent.com/24726299/90024663-caf1df00-dcbd-11ea-91a2-8f90a614b4f7.png).

**Comment by vim-ml** [comment] 2020-08-12 14:11
On 2020-08-12, Christian Brabandt wrote:
> I suppose highlighting the a is the only way to make sure that there is
> actually a line break. Without highlighting the first character on the line, it
> wouldn't be clear, that the search item spans more than a single line.

But with this highlighting, it's not clear that the first character
is not included in the search pattern.

Not being able to highlight the newline is an inconvenience;
highlighting that first character is wrong.

Regards,
Gary

**Comment by chrisbra** [comment] 2020-08-12 14:17
> Doesn't highlighting the space after test serve that purpose?

How do you know, that this is actually the linefeed and not a trailing whitespace?

> Not being able to highlight the newline is an inconvenience;
> highlighting that first character is wrong.

Yeah, I suppose that is right. I am probably too used to the current behaviour.

**Comment by lkintact** [comment] 2020-08-12 14:29
> How do you know, that this is actually the linefeed and not a trailing whitespace?

Thanks for specifying the ambiguity.

**Comment by lkintact** [comment] 2020-11-21 18:19
>>Not being able to highlight the newline is an inconvenience;
>>highlighting that first character is wrong.

>Yeah, I suppose that is right. I am probably too used to the current behaviour.

@chrisbra Sorry for specifically drawing your attention to this, but I just had another situation with gVim highlighting a char that's not part of a search pattern. So will the issue be fixed? If not, perhaps the current behaviour should be considered a feature and somehow described in the docs?

**Comment by chrisbra** [comment] 2020-11-23 11:17
I suppose this is an implementation default, that might be noticeable by users for this specific edge case. It might be better to document this behaviour. Can you suggest a doc patch (or where to document this peculiarity)?

**Comment by brammool** [comment] 2020-11-23 17:21
There is something wrong here.  The character after the line is highlighted to indicate including the line break, but the first character on the next line is also highlighted.  Typing that character doesn't change the highlighted match, so that looks wrong.

**Comment by chrisbra** [comment] 2020-11-23 19:37
> There is something wrong here. The character after the line is highlighted to indicate including the line break, but the first character on the next line is also highlighted. Typing that character doesn't change the highlighted match, so that looks wrong.

Are you sure? The behaviour on the screenshot is the `incsearch` behaviour, e.g. what is shown, while typing the search pattern. 'hlsearch' option is showing fine. I thought this behaviour has been like this for as long as I can remember and as a quick test I downloaded the oldest release from the github.com/vim/vim-win32-installer repository, which is gvim 7.4.1185.  It shows exactly this behaviour.

I believe this is caused by the fact that when searching the cursor is put on the first character of the next line after the `\n`, so the window is highlighted including the first column of the following line.

**Comment by brammool** [comment] 2020-11-23 19:52
Have a line end in "the word" and the next line start with "xxx".
Put the cursor on "the", start a search command with "/word" (don't hit Enter).
Now "word" is highlighted.  Adding the two characters "\n" adds both highlighting to just after "word"
and also the first "x".  That "x" should not have highlighted.
Now add "x" - nothing changes.  This is where the "x" would also have been highlighed.
When adding another "x" we get the first two "x" highlighted, back to being OK.

**Comment by chrisbra** [comment] 2020-11-23 20:03
Yes, understood what you are saying (and what is wrong).
what I was trying to say was, that this must have been broken a long time ago, because I remember vim behaving this way for very long (and didn't even think this is a bug). Anyway, will have a look

**Comment by chrisbra** [comment] 2020-11-25 12:54
fixed by https://github.com/vim/vim/commit/448465e6872905967c97a56cd45307530795653c

**Closed as completed by chrisbra** 2020-11-25 12:54 UTC
