### ISSUE TITLE
:unlockvar can't be applied to non-existent variables in compiled functions

### ISSUE THREAD

**Issue by dkearns** [vim/vim#11433] opened 2022-10-23 14:23 UTC
### Steps to reproduce

Source the following script.

```vim
vim9script

function FreeFoo()
  unlockvar g:foo
  echomsg "Foo"
endfunction

def FreeBar()
  unlockvar g:bar
  echomsg "Bar"
enddef

FreeFoo()
FreeBar()
```

Output:
```
Foo 
Error detected while processing /tmp/l2.vim[14]..function <SNR>71_FreeBar:
line    1:
E1246: Cannot find variable to (un)lock: g:bar
```

### Expected behaviour

Output:

```
Foo
Bar
```

### Version of Vim

9.0.0815

### Environment

Ubuntu: 18.04

**Comment by brammool** [comment] 2022-11-12 22:24
In my opinion this is correct.  In the legacy function the error was somehow not reported, that was fixed in Vim9 script.
Unless you can explain why you think the error should be silently ignored, I think this should be closed "working as intended".

**Comment by dkearns** [comment] 2022-11-13 08:11
No, I'd prefer that it didn't fail silently as well.  Perhaps it could be expected to behave like `:unlet!` but the bang is already taken.

This behaviour is relied upon, somewhat idiomatically, in legacy scripts that use functions to create and modify locked global variables.  They unconditionally call `:unlock` on entry and `:lockvar` on exit.

How about adding something like this to the docs?

```diff
diff --git a/runtime/doc/eval.txt b/runtime/doc/eval.txt
index ba95f3291..f4874d878 100644
--- a/runtime/doc/eval.txt
+++ b/runtime/doc/eval.txt
@@ -3073,6 +3073,9 @@ text...
                        Unlock the internal variable {name}.  Does the
                        opposite of |:lockvar|.
 
+                       If {name} does not exist an error is given in Vim9
+                       script, in legacy script this is silently ignored.
+
 :if {expr1}                    *:if* *:end* *:endif* *:en* *E171* *E579* *E580*
 :en[dif]               Execute the commands until the next matching `:else`
                        or `:endif` if {expr1} evaluates to non-zero.
```

**Comment by brammool** [comment] 2022-11-13 12:30
> No, I'd prefer that it didn't fail silently as well.  Perhaps it could
> be expected to behave like `:unlet!` but the bang is already taken.
> 
> This behaviour is relied upon, somewhat idiomatically, in legacy
> scripts that use functions to create and modify locked global
> variables.  They unconditionally call `:unlock` on entry and
> `:lockvar` on exit.
> 
> How about adding something like this to the docs?

I'll add that.  We forgot to add that remark when changing the behavior.

If the error is undesired then the usual ":silent!" prefix can be used.
I don't think we need to do anything else here.


-- 
hundred-and-one symptoms of being an internet addict:
53. To find out what time it is, you send yourself an e-mail and check the
    "Date:" field.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment] 2022-11-25 17:56
Closing, since the help has been updated.

**Closed as completed by brammool** 2022-11-25 17:56 UTC
Labels: bug
