### ISSUE TITLE
:terminal <command> indents multiline output on FreeBSD 12

### ISSUE THREAD

**Issue by ov2k** [vim/vim#4289] opened 2019-04-21 20:41 UTC
This occurs on a fresh install of FreeBSD 12, installed with default settings wherever possible.  It affects the vim-console package (8.1.985) and a source build (8.1.1198).

Terminal commands that output multiple lines indent unexpectedly.
Input: `:terminal printf \%s\\n a bc def g`
Output
```
a
 bc
   def
      g
```
Expected
```
a
bc
def
g
```

**Comment by brammool** [comment] 2019-04-23 17:05
I cannot reproduce this.  Please provide more information.

**Comment by chrisbra** [comment] 2019-04-24 06:34
looks like you have not enabled `LF` to `CRLF` conversion for your terminal. Try `stty onlcr` first. See [this excellent answer](https://unix.stackexchange.com/a/151963/303213) from stackoverflow.

Since this looks like a configuration issue, closing.

**Comment by ov2k** [comment] 2019-04-25 02:06
@chrisbra I tried `stty onlcr` before opening vim, and it didn't change anything.  I also tried calling `:terminal stty onlcr`, which gave the error message `stty: stdin isn't a terminal`.  This occurs both directly on the console and from an ssh session.

I won't pretend to know what `:terminal` is doing internally, but I think the same fundamental pty problem results in this and #4290.  I'm pretty sure this is specific to FreeBSD, because this all works fine on the various linux platforms I have.  However, I do think this might be worth some attention, because I haven't configured anything (so the default configuration seems to be at issue) and this affects the version of vim installed through the package manager and the version compiled from source.

### Reproduction summary

I'm able to reproduce this bug from the VirtualBox [VM image](https://download.freebsd.org/ftp/releases/VM-IMAGES/12.0-RELEASE/amd64/Latest/FreeBSD-12.0-RELEASE-amd64.vmdk.xz) provided by FreeBSD.  This occurs as root on the console.

#### Prepackaged
```
pkg install vim-console
vim
```
Then in vim: 
```
:terminal stty onlcr
:terminal printf \%s\\n a bc def g
```

#### Source
```
pkg install git
git clone https://github.com/vim/vim
cd vim
./configure
make install
vim
```
Then in vim: 
```
:terminal stty onlcr
:terminal printf \%s\\n a bc def g
```

**Comment by lifepillar** [comment] 2019-04-25 06:45
@ov2k I can reproduce both this and https://github.com/vim/vim/issues/4290 with Vim compiled from ports, but as @brammool and you have acknowledged, the terminal feature is working everywhere, so this is a FreeBSD-only issue and as such it should be reported to the FreeBSD's project. There they will likely figure out what the issue is and possibly propose a fix for Vim if required.

**Comment by dpelle** [comment] 2019-04-25 07:21
What does this outputs on FreeBSD (with the added \\r)?
```
:terminal printf \%s\\r\\n a bc def
```

**Comment by ichizok** [comment] 2019-04-25 07:36
Have you loaded pty module?

```
kldload pty
```

**Comment by ov2k** [comment] 2019-04-26 00:31
@deplle Things look okay with the extra `\r`, but that's masking an underlying issue.

@ichizok That works.  It's a useful workaround for now.

@brammool I think there are two issues here, both of which are worth considering.

Before going futher, I want to mention that I'm working with command line vim, and haven't tested the GUI.

The first issue is pts support.  FreeBSD uses [pts](https://www.freebsd.org/cgi/man.cgi?query=pts&sektion=4&manpath=FreeBSD+12.0-RELEASE) by default, which is why it doesn't normally enable [pty](https://www.freebsd.org/cgi/man.cgi?query=pty&sektion=4&manpath=FreeBSD+12.0-RELEASE).  Access is through `posix_openpt()`([FreeBSD](https://www.freebsd.org/cgi/man.cgi?query=posix_openpt&sektion=2&manpath=FreeBSD+12.0-RELEASE), [POSIX](http://pubs.opengroup.org/onlinepubs/9699919799/functions/posix_openpt.html)).  Supporting `posix_openpt()` means FreeBSD doesn't require an extra kernel module and supporting the standardized function will hopefully prevent similar issues in the future.

Second, the problems with FreeBSD 12 and pty support reveal an underlying issue with the pipe-based channels vim uses when `mch_openpty()` returns -1.  I've been able to replicate the bug on a Ubuntu system by replacing the call to `mch_openpty()` in `open_pty()` with `*pty_master_fd = -1;`.

### Summary

1. Add a version of `mch_openpty()` that uses `posix_openpt()` and add corresponding `configure` checks.
2. Either fix the pipe-based fallback for `:terminal` or disable it.

**Comment by brammool** [comment] 2019-04-26 22:34
> @ichizok That works.  It's a useful workaround for now.

Have you tried out the patch in pull request #4306?

> @brammool I think there are two issues here, both of which are worth considering.
> 
> Before going futher, I want to mention that I'm working with command line vim, and haven't tested the GUI.
> 
> The first issue is pts support.  FreeBSD uses [pts](https://www.freebsd.org/cgi/man.cgi?query=pts&sektion=4&manpath=FreeBSD+12.0-RELEASE) by default, which is why it doesn't normally enable [pty](https://www.freebsd.org/cgi/man.cgi?query=pty&sektion=4&manpath=FreeBSD+12.0-RELEASE).  Access is through `posix_openpt()`([FreeBSD](https://www.freebsd.org/cgi/man.cgi?query=posix_openpt&sektion=2&manpath=FreeBSD+12.0-RELEASE), [POSIX](http://pubs.opengroup.org/onlinepubs/9699919799/functions/posix_openpt.html)).  Supporting `posix_openpt()` means FreeBSD doesn't require an extra kernel module and supporting the standardized function will hopefully prevent similar issues in the future.
> 
> Second, the problems with FreeBSD 12 and pty support reveal an underlying issue with the pipe-based channels vim uses when `mch_openpty()` returns -1.  I've been able to replicate the bug on a Ubuntu system by replacing the call to `mch_openpty()` in `open_pty()` with `*pty_master_fd = -1;`.
> 
> ### Summary
> 
> 1. Add a version of `mch_openpty()` that uses `posix_openpt()` and add corresponding `configure` checks.
> 2. Either fix the pipe-based fallback for `:terminal` or disable it.

I don't quite see how to make :terminal fall back to pipes.

-- 
GUARD #2:  Wait a minute -- supposing two swallows carried it together?
GUARD #1:  No, they'd have to have it on a line.
GUARD #2:  Well, simple!  They'd just use a standard creeper!
GUARD #1:  What, held under the dorsal guiding feathers?
GUARD #2:  Well, why not?
                                  The Quest for the Holy Grail (Monty Python)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by ov2k** [comment] 2019-04-27 20:39
> 
> Have you tried out the patch in pull request #4306?

I just tried, and it seems to work.  I haven't tried anything too fancy, but I think it covers the basic issue.

>
> I don't quite see how to make :terminal fall back to pipes.

I guess that answers the question of whether it was supposed to do that.  When `mch_openpty()` returns -1, the error passes through `open_pty()` to `mch_job_start()`, which falls back to setting up a pipes-based channel.  For non-interactive use, this doesn't work because the pipes are treated as a raw channel by `may_invoke_callback()` in `vim/channel.c`, so there's no LF->CRLF conversion.  In general, I'm not sure how to make `:terminal` work properly with pipes, and I suspect there are other issues beyond the LF->CRLF conversion (e.g., #4290).  

I do think something needs to be done about the pipe-based fallback.  It's still an issue even with #4306, because it triggers anytime `mch_openpty()` returns -1.  For example, it should show up if a user runs out of pty devices.  In that case, `:terminal` will suddenly stop working properly, and I doubt most users would know why.  It affects at least FreeBSD and Ubuntu, and I don't really think it's platform-specific.  It sounds like the pipe-based fallback wasn't intended for `:terminal`, in which case it's probably simplest to just have `:terminal` give an error message when it fails to allocate a pty.

**Comment by brammool** [comment] 2019-04-28 12:03
> > Have you tried out the patch in pull request #4306?
> 
> I just tried, and it seems to work.  I haven't tried anything too
> fancy, but I think covers the basic issue.

I'll include that then.

> > I don't quite see how to make :terminal fall back to pipes.
> 
> I guess that answers the question of whether it was supposed to do
> that.  When `mch_openpty()` returns -1, the error passes through
> `open_pty()` to `mch_job_start()`, which falls back to setting up a
> pipes-based channel.  For non-interactive use, this doesn't work
> because the pipes are treated as a raw channel by
> `may_invoke_callback()` in `vim/channel.c`, so there's no LF->CRLF
> conversion.  In general, I'm not sure how to make `:terminal` work
> properly with pipes, and I suspect there are other issues beyond the
> LF->CRLF conversion (e.g., #4290).  
> 
> I do think something needs to be done about the pipe-based fallback.
> It's still an issue even with #4306, because it triggers anytime
> `mch_openpty()` returns -1.  For example, it should show up if a user
> runs out of pty devices.  In that case, `:terminal` will suddenly stop
> working properly, and I doubt most users would know why.  It affects
> at least FreeBSD and Ubuntu, and I don't really think it's
> platform-specific.  It sounds like the pipe-based fallback wasn't
> intended for `:terminal`, in which case it's probably simplest to just
> have `:terminal` give an error message when it fails to allocate a
> pty.

On systems without pty support it should at least make some things work.
If one runs out of pty's (I never ever encountered that) it should just
fail with a useful error message.  But should never happen.

-- 
Individualists unite!

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Closed as completed** 2019-04-28 13:00 UTC

**Comment by ov2k** [comment] 2019-04-28 14:43
>
> If one runs out of pty's (I never ever encountered that) it should just 
fail with a useful error message.

I didn't see any code that would generate an error message and didn't see an error message when I deliberately crippled `open_pty()`, but falling back to pipes seems to be uncommon enough for the associated issues to not have been reported before.

@ichizok Thanks for the patch.

@brammool Sorry for the mess and thanks for taking the time to address this.

**Comment by ov2k** [comment] 2019-05-01 16:50
> 
> 
> Have you loaded pty module?

> 
> 
> That works. It's a useful workaround for now.

#4306 and https://github.com/vim/vim/commit/1e44968780bb6ddb48bf22dc629a579c4035d5b3 are working as expected.

This is just to document that the workaround of loading the pty module on FreeBSD isn't as robust as it seemed.  Only a single `:terminal` command can be running at a time.  For example, if an interactive `:terminal` command is running, additional `:terminal` commands will exhibit this and #4290.
