### ISSUE TITLE
Errors when trying to use vim as a MANPAGER with the fish shell

### ISSUE THREAD

**Issue by svmhdvn** [vim/vim#1956] opened 2017-08-09 20:37 UTC
I followed the help documentation's instructions on how to use vim as a syntax-highlighting manpager. However, I'm getting inconsistent results and sometimes errors when running `$ man <manpage>` afterwards. These results differ on different systems:

* FreeBSD 12 CURRENT, xfce4-terminal, tmux, and latest vim from Ports
* macOS High Sierra beta 3, alacritty, tmux, and latest vim from Homebrew

To reproduce:
1. `$ echo 'set -x MANPAGER "env MAN_PN=1 vim -M +MANPAGER -"' >> ~/.config/fish/config.fish` as recommended by the vim help docs
2. Spawn a new shell session and run `man <manpage>`. At this stage on both systems, I get the following results:
```
# First get a blank screen, which I terminate with CTRL-C, then the following output appears inside vim:
Vim: Warning: Output is not to a terminal
Vim: Warning: Input is not from a terminal
?1000h?2004h?1h?2004h27mm38;2;131;148;150m48;2;0;43;54mH2J?25l24;1H"-stdin-" 277L, 22708C?2004h1;24r?12;25h?12l?25h27mm38;2;131;148;150m48;2;0;43;54mH2J?1000l?2004lVim: Reading from stdin...
?1000h?2004h?1000l?2004lVim: Reading from stdin...
?1000h?2004h?1000l?2004lVim: Reading from stdin...
?1000h?2004h24;1H?12l?25h?1000l?2004l?1000h?2004h?1000l?2004lm38;2;131;148;150m48;2;0;43;54m39;49m?2004l?1lVim: Error reading input, exiting...
Vim: Finished.
24;1H27mm38;2;131;148;150m48;2;0;43;54m39;49mVim: Reading from stdin...
```
3. Comment out the newly added line in `~/.config/fish/config.fish` in the same shell session, then re-run the `man` command

On FreeBSD, (3) will cause it to work with no errors (the manpage correctly displays within VIM).
On macOS, (3) will output the following within vim:
```
sh: -c: line 0: syntax error near unexpected token `||'
sh: -c: line 0: `(cd '/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/share/man' && (echo ".ll 16.1i"; echo ".nr LL 16.1i"; /bin/cat '/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/share/man/man1/patch.1') | /usr/bin/tbl | /usr/bin/groff -Wall -mtty-char -Tascii -mandoc -c | ( || true))'
Error executing formatting or display command.
System command (cd '/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/share/man' && (echo ".ll 16.1i"; echo ".nr LL 16.1i"; /bin/cat '/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/share/man/man1/patch.1') | /usr/bin/tbl | /usr/bin/groff -Wall -mtty-char -Tascii -mandoc -c | ( || true)) exited with status 512.
Man page /usr/share/man/man1/patch.1 is identical to /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/share/man/man1/patch.1
No entry for patch in section 1 of the manual
```
(This makes me think it might not be a vim issue, but rather an issue with man or fish since `||` is being called (which is `or` on fish), but I'm not sure.)

However, running `$ man <manpage> | env MAN_PN=1 vim -M +MANPAGER -` on macOS causes it to work with no errors.

Do the vim help docs state the correct MANPAGER value? Or is it an issue outside of vim?

**Comment by rlue** [comment] 2017-11-09 04:21
I can confirm this issue. It's definitely not an issue with fish, though (I'm using bash).

The `MANPAGER` setting described in `:h manpager` works 100% fine on Debian, and results in the quoted error on macOS (10.11 El Capitan).

```
$ man dd
sh: -c: line 0: syntax error near unexpected token `||'
sh: -c: line 0: `(cd '/usr/share/man' && (echo ".ll 7.6i"; echo ".nr LL 7.6i"; /bin/cat '/usr/share/man/man1/dd.1') | /usr/bin/tbl | /usr/bin/groff -Wall -mtty-char -Tascii -mandoc -c | ( || true))'
Error executing formatting or display command.
System command (cd '/usr/share/man' && (echo ".ll 7.6i"; echo ".nr LL 7.6i"; /bin/cat '/usr/share/man/man1/dd.1') | /usr/bin/tbl | /usr/bin/groff -Wall -mtty-char -Tascii -mandoc -c | ( || true)) exited with status 512.
No manual entry for dd
```

Notably, if I _don't_ set the `MANPAGER` environment variable, and I manually source `$VIMRUNTIME/ftplugin/man.vim`, then I can use `:Man` to look up manpages just fine. But if it is set, then both `:Man` and `$ man` return the error message above.

@svmhdvn's shell-piping workaround works just fine; on my system, the following alias works as well:

```
function man ()
{
  vim -c 'set ft=man' -c "Man $1" -c 'silent! only'
}
```

---

I emailed the author of `plugins/manpager.vim` (Enno Nagel) about this; he said that the author of `ftplugin/man.vim` (SungHyun Nam) would be the one to ask. Then I emailed SungHyun, but I think I must have explained the issue poorly because he referred me back to Enno. 

(I'm pretty sure the error isn't in Enno's `manpager.vim` plugin — all that does is find the file corresponding to the manpage and call `:Man` internally, without ever invoking any shell commands. OTOH, SungHyun's `man.vim` ftplugin seems to not to call many system commands either, but I won't profess to understand the whole thing.)

**Comment by nuko8** [comment] 2017-11-09 06:50
On macOS, when `MANPAGER` is undefined, `$ man dd` gives
```
sh -c (cd '/usr/share/man' && /usr/bin/tbl '/usr/share/man/man1/dd.1' | /usr/bin/groff -Wall -mtty-char -Tascii -mandoc -c | (/usr/bin/less -is || true))
```
On the other hand, when `MANPAGER` is defined, it tries to run
```
sh -c (cd '/usr/share/man' && /usr/bin/tbl '/usr/share/man/man1/dd.1' | /usr/bin/groff -Wall -mtty-char -Tascii -mandoc -c | ($MANPAGER || true))
```
Note that `less -is` is now replaced with `$MANPAGER`.  (Also, for the sake of brevity, `PAGER` is not taken into account here.)

Keeping that in mind, if you have a look at

https://github.com/vim/vim/blob/master/runtime/ftplugin/man.vim#L20-L22

you see that `ftplugin/man.vim` sets $MANPAGER to an empty string when it is defined.

That explains the reason of the error `sh: -c: line 0: syntax error near unexpected token '||'` that appears on macOS when `plugin/manpager.vim` is used with `MANPAGER` defined: The pager is set to that empty `MANPAGER` when `man(1)` is invoked.

To fix it, that empty `MANPAGER` needs to be `unset` or undefined explicitly, so that the shell in use will correctly recognize it as an undefined variable, and then `man(1)` will select the default pager `less -is` accordingly.

One of the ways to accomplish that might be to replace

https://github.com/vim/vim/blob/master/runtime/ftplugin/man.vim#L100 

with
```viml
silent exec "r !unset MANPAGER; man ".s:GetCmdArg(sect, page)." | col -b"
```
But I'm not sure if that works well for platforms/shells other than macOS/bash or zsh.

@goweol  This is by no means a bug of `ftplugin/man.vim` at all; however, in order to make `plugin/manpager.vim` work well for Mac, it seems that we need your help unless another solution which doesn't require modification in `man.vim` is given.

**Comment by chrisbra** [comment] 2017-11-09 07:41
> silent exec "r !unset MANPAGER; man ".s:GetCmdArg(sect, page)." | col -b"

unset is a shell builtin, I think better would be to use `env` which should work always: 

` silent exec "r ! env -u MANPAGER man ".s:GetCmdArg(sec,page)." |col -b"`

**Comment by goweol** [comment] 2017-11-09 07:53
2017-11-09 오후 4:41에 Christian Brabandt 이(가) 쓴 글:
>     silent exec "r !unset MANPAGER; man ".s:GetCmdArg(sect, page)." |
>     col -b"
> 
> unset is a shell builtin, I think better would be to use |env| which 
> should work always:
> 
> ` silent exec "r ! env -u MANPAGER man ".s:GetCmdArg(sec,page)." |col -b"

'sec' should be 'sect'.

And I'm fine with this change.
Does this patch works for Mac?


diff --git a/runtime/ftplugin/man.vim b/runtime/ftplugin/man.vim
index c7fc3bbdf..4b7cb4f44 100644
--- a/runtime/ftplugin/man.vim
+++ b/runtime/ftplugin/man.vim
@@ -15,12 +15,6 @@ if &filetype == "man"
    endif
    let b:did_ftplugin = 1

-  " Ensure Vim is not recursively invoked (man-db does this)
-  " when doing ctrl-[ on a man page reference.
-  if exists("$MANPAGER")
-    let $MANPAGER = ""
-  endif
-
    " allow dot and dash in manual page name.
    setlocal iskeyword+=\.,-

@@ -176,7 +170,7 @@ func <SID>GetPage(...)
      let $MANWIDTH = winwidth(0)
      let unsetwidth = 1
    endif
-  silent exec "r !man ".s:GetCmdArg(sect, page)." | col -b"
+  silent exec "r ! env -u MANPAGER man ".s:GetCmdArg(sect,page)." |col -b"
    if unsetwidth
      let $MANWIDTH = ''
    endif

**Comment by rlue** [comment] 2017-11-09 08:01
Works for me!

**Comment by goweol** [comment] 2017-11-09 08:19
I'm not sure you test various condition.  I guess you check the shell command 'man'.
Then, I hope you check below.  Could you please?
- Does ':Man' in the vim  work?
- Does browsing other manual pages work?  I mean &lt;Ctrl-]&gt; and &lt;Ctrl-t&gt;.

**Comment by rlue** [comment] 2017-11-09 08:34
@goweol, you were 100% correct — I did not check those other conditions. ;)

* `:Man` works A-OK. 
* `<C-]>` also works A-OK. 
* What is `<C-t>` supposed to do? Navigate to the previous man page? If so, then it's working, too.

Thanks a lot!

**Comment by goweol** [comment] 2017-11-10 00:53
Thanks!

**Comment by rlue** [comment] 2017-11-11 06:58
I didn't see a PR go up for this and I figured you all might be busy, so I thought I'd save you the trouble. Do let me know if this is against protocol or anything.

Thanks again!

**Comment by goweol** [comment] 2017-11-13 05:05
I did send a patch to Bram, and heard he already included the patch.
I'm sorry I'm not familiar with github.

**Comment by rlue** [comment] 2017-11-13 05:08
Great! I was just looking for a way to get this issue closed, but I suppose I should really leave that to the maintainers. :)

**Comment by k-takata** [comment] 2017-11-13 06:07
The change [above](https://github.com/vim/vim/issues/1956#issuecomment-343074314) was merged with the latest runtime file update: https://github.com/vim/vim/commit/7f2e9d7c9cdfc5201a899b7b610edf64bf80c45f#diff-8691c83194ea5f1342ecc9f17b4c51d8L4
Can we close this issue, or are there any remaining problems?

**Closed as completed** 2017-11-15 03:26 UTC
Labels: runtime

**Comment by pavoljuhas** [comment] 2017-12-13 18:19
> unset is a shell builtin, I think better would be to use env which should work always:
> `silent exec "r ! env -u MANPAGER man ".s:GetCmdArg(sec,page)." |col -b"`

@chrisbra, @goweol  - this broke the `:Man` command on Mac, because its `env` has no `-u` option.
I am getting the following output:
```
env: illegal option -- u
usage: env [-i] [name=value ...] [utility [argument ...]]
```

How about
```Vim
silent exec "r ! env MANPAGER=cat man ".s:GetCmdArg(sec,page)." |col -b"
```

**Comment by nuko8** [comment] 2017-12-13 23:02
@pavoljuhas 

> @chrisbra, @goweol - this broke the :Man command on Mac, because its env has no -u option.
I am getting the following output:
>
> env: illegal option -- u
> usage: env [-i] [name=value ...] [utility [argument ...]]


Strange.  On my Mac, `:Man env` actually works fine and gives
```
ENV(1)			  BSD General Commands Manual			ENV(1)

NAME
     env -- set environment and execute command, or print environment

SYNOPSIS
     env [-iv] [-P altpath] [-S string] [-u name] [name=value ...]
	 [utility [argument ...]]

DESCRIPTION
...
```
which clearly states that it has `-u` option.

Also, for this `env`,  the error message to an unknown option is
```
env -x
env: illegal option -- x
usage: env [-iv] [-P utilpath] [-S string] [-u name]
           [name=value ...] [utility [argument ...]]
```
which is apparently different from yours.

So, your `env` appears to be something different from `/usr/bin/env`.  Why?

**Comment by pavoljuhas** [comment] 2017-12-13 23:18
> So, your env appears to be something different from /usr/bin/env. Why?

I suppose it depends on the OS X version.  Mine is OS X Yosemite 10.10.5 (14F2511).

```sh
$ /usr/bin/env -u MANPAGER pwd
/usr/bin/env: illegal option -- u
usage: env [-i] [name=value ...] [utility [argument ...]]
$ ls -l /usr/bin/env
-rwxr-xr-x  1 root  wheel  14224 Sep  9  2014 /usr/bin/env
$ md5sum /usr/bin/env
e96793df622bbb444c5ed3976f4b169c  /usr/bin/env
```

`man env` states the following BSD version:
```
BSD                             August 27, 1993                            BSD
```

**Comment by goweol** [comment] 2017-12-13 23:51
If MANPAGER is set again, I'm afraid that it will be a problem for others.
But, because 'env -u' is not portable, I think reverting that change would be better.

If someone cannot find a good solution, how about removing MANPAGER stuff from man.vim and recommends "do not use manpager plugin if you have a problem with it, and you can use such as, "
export MANPAGER="/bin/sh -c \"unset PAGER;col -b -x | \
    vim -R -c 'set ft=man nomod nolist' \
    -c 'map <SPACE> <C-D>' -c 'map b <C-U>' \
    -c 'nmap K :Man <C-R>=expand(\\\"<cword>\\\")<CR><CR>' -\""

(Above MANPAGER setting is example).

**Comment by nuko8** [comment] 2017-12-14 00:20
@pavoljuhas 

Indeed, mine is
```
BSD				April 17, 2008				   BSD
```
on 10.11.6 (El Capitan).   

Hmm, instead of `env`, I used to use `unset` to have gotten `:Man` to work for my Mac and gave an idea of making use of it in this thread, but couldn't remember why I had preferred such an unportable way when @chrisbra pointed it out.   Probably, that version difference I didn't notice explains why I did that.

An alternative solution to the Yosemite issue would be:  Copy `$VIMRUNTIME/ftplugin/man.vim` and put it in `$HOME/.vim/ftplugin/man.vim`, give it the modification so that `:Man` can work well with Yosemite or older OS X versions.  (This is what I had done until `man.vim` was fixed for _recent_ OS X versions.)

**Comment by pavoljuhas** [comment] 2017-12-14 03:40
> If MANPAGER is set again, I'm afraid that it will be a problem for others.
> But, because 'env -u' is not portable, I think reverting that change would be better.

How about using `env MANPAGER=cat` instead of `env -u MANPAGER`?

That syntax should be supported in all `env` versions.  In my case the output from `man` is the same with `MANPAGER` unset and with `MANPAGER=cat`.  Setting MANPAGER=cat avoids `env -u` and also the `unset` shell builtin which [does not work in the fish shell](https://stackoverflow.com/a/30703861).

```sh
$ (unset MANPAGER; man bash) | md5sum
e302543089e9b8f08d5b402f302aef11  -
$ env MANPAGER=cat man bash | md5sum
e302543089e9b8f08d5b402f302aef11  -
```

> An alternative solution to the Yosemite issue would be: Copy $VIMRUNTIME/ftplugin/man.vim and put it in $HOME/.vim/ftplugin/man.vim, ...

That is fine, but it leaves an out-of-box `:Man` broken on older Mac-s and on any other older BSD systems.

**Comment by chrisbra** [comment] 2017-12-14 08:52
Yes you are right, `env -u` is unportable according to [POSIX](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/env.html).

Would `env -i` work (this would run the following command with an empty environment, not sure, if the manpager plugin requires any other environment variables to be set)? The suggestion to use `cat` as `MANPAGER` also seems reasonable.

**Comment by nuko8** [comment] 2017-12-14 10:32
> The suggestion to use cat as MANPAGER also seems reasonable.

Before the fix which was already done in the wake of this thread was adopted, `man.vim` would set `MANPAGER` to an empty string in order to prevent the plugin from hanging due to recursive calls.  Meanwhile, this empty `MANPAGER` was the very reason that the plugin didn't work for Mac.  Thus, currently, `MANPGER` is explicitly set undefined using `env -u` when `man(1)` is invoked from the plugin.

Although I'm not 100% sure of the implication of @goweol 's comment:

> If MANPAGER is set again, I'm afraid that it will be a problem for others.

I think we need to make sure that `cat` causes no trouble (particularly, with page jumps via `<C-]>` and `<C-T>`) for every system on which the plugin has already been working well.

**Comment by pavoljuhas** [comment] 2017-12-14 15:43
> Would env -i work?

It would unset MANPATH and PATH which are both used to locate man pages.  It would also unset LANG which may select translated manuals.

> I think we need to make sure that cat causes no trouble (particularly, with page jumps via <C-]> and <C-T>) for every system on which the plugin has already been working well.

I don't see how cat could have any trouble with jumps.  Note that `MANPAGER=cat` would be in effect only for the system command that gets the manual text.  Otherwise MANPAGER would remain unset or at whatever value vim was started with.
