### ISSUE TITLE
Ctrl-[ don't escape from insert mode (like Esc) on Belgian keyboard

### ISSUE THREAD

**Issue by vds2212** [vim/vim#10454] opened 2022-05-20 08:06 UTC
### Steps to reproduce

On a computer with a Belgian keyboard using gVim

1. Start Vim
2. Enter in insert mode
3. Type: Ctrl-[

### Expected behaviour

You should be back in Normal mode but you stay in insert mode.

### Version of Vim

8.2.4943 on Windows 10 8.2.3995 on Ubuntu 22.04

### Environment

Operating System: Windows 10 or Ubuntu 22.04

I can only reproduce the problem on gVim (on Vim the problem do not occur)

**Comment by vds2212** [comment] 2022-05-20 09:29
I have compiled different tags of Vim on Windows 10.
I don't have the problem at version 8.2.4006
But I do have the problem at version 8.2.4007 and later

**Comment by chrisbra** [comment] 2022-05-20 09:31
I think this is a duplicate of https://github.com/vim/vim/issues/10324

**Comment by brammool** [comment] 2022-06-29 09:23
@LemonBoy was working on a solution, but it didn't get completed yet.

**Comment by vds2212** [comment] 2022-06-30 05:07
Thanks! Let me know if I can contribute in any ways.

**Comment by brammool** [comment] 2022-07-04 09:55
Patch 9.0.0033 fixes this for GTK, but it is still a problem for MS-Windows

**Comment by vds2212** [comment] 2022-07-04 11:58
Thanks for the update :-)

**Comment by tonymec** [comment] 2022-07-04 13:55
WFM on gvim (Big, GTK3) 9.0.32 i.e. without the patch. Don't forget, however, that on a Belgian keyboard, [ is AltGr+dead-circumflex, therefore Ctrl+[ is Ctrl+AltGr+dead-circumflex.

Best regards,
Tony.

**Comment by vds2212** [comment] 2022-07-06 11:03
Hi Tony,

I have tested version 9.0.35 and the problem is still present in gVim.

On gVim 8.2 I can escape using: Ctrl+DeadCircumflex
On gVim 9.0 I can't escape neither Ctrl+DeadCircumflex nor Ctrl+AltGr+DeadCircumflex

Remark: The problem is not present on Vim 9.0

Best regards,
Vivian

**Closed as completed** 2022-07-26 20:26 UTC
Labels: platform-windows
