### ISSUE TITLE
:highlight ignores bold if ctermfg is Black

### ISSUE THREAD

**Issue by rolf007** [vim/vim#1545] opened 2017-03-08 19:51 UTC
Create a new highlight with cterm having 'bold' and ctermfg=Black
    `:highlight Foo cterm=bold,reverse ctermfg=Black ctermbg=Yellow`
and then view the highlight
    `:highlight Foo`
Observe how cterm is now without 'bold'
    `Foo            xxx cterm=reverse ctermfg=0 ctermbg=3`
Expected to have 'bold'
    `Foo            xxx cterm=bold,reverse ctermfg=0 ctermbg=3`

If 'Black' is substituted with '0' or any other color, it works as expected.

Observed in vim 8.0.13

**Comment by lacygoill** [comment] 2020-06-16 08:46
I can't reproduce.  The output of `:highlight Foo` correctly includes the `bold` attribute:

    vim -es -Nu NORC +'highlight Foo cterm=bold,reverse ctermfg=Black ctermbg=Yellow' +"pu=execute('highlight Foo')" +'%p|qa!'
    Foo            xxx cterm=bold,reverse ctermfg=0 ctermbg=14
                             ^^^^

Tested with Vim master and with Vim 8.0.13, in xterm without any Vim config, shell config, terminal config.

**Comment by chrisbra** [comment] 2020-06-16 08:56
neither can I reproduce. I wonder if this could be some kind of termcap issue. Anyhow, closing, as this does not seem to be a vim bug

**Closed as completed by chrisbra** 2020-06-16 08:56 UTC
