### ISSUE TITLE
Replace command not working properly when there are special characters before at same line

### ISSUE THREAD

**Issue by Filipizaum** [vim/vim#8615] opened 2021-07-23 17:31 UTC
**Describe the bug**
Each special character before the replaced text make an offset on the replacement.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Create a plain text file (yourfile.txt)
2. Put this content in the file: " usuário 'usuario' ..."
2. Open the file with vim (vim youfile.txt)
3. Execute the replace command "%s/usuario/word"
4. Notice that the text becomes " usuário 'uword' ..."

**Expected behavior**
The final text would be " usuário 'word' ..."

**Environment (please complete the following information):**
 - VIM Version: - Vi IMproved 8.1 (2018 May 18, compiled Apr 15 2020 06:40:31)
 - OS: Ubuntu 20.04 LTS
 - Terminal: MobaXTerm v10.9

**Comment by lacygoill** [comment] 2021-07-23 17:58
I can't reproduce:

    vim -es -Nu NONE -i NONE +"call setline(1, \" usuário 'usuario' ...\") | %s/usuario/word" +'%p |qa!'

Correctly outputs:

    usuário 'word' ...

And not:

    usuário 'uword' ...

Either the issue has been fixed (your Vim is more than 3 years old), or you have some settings/plugins which are necessary to reproduce.

**Comment by chrisbra** [comment] 2021-07-23 18:03
Neither can I. Please test with an updated Vim first starting with `vim --clean`

**Comment by lacygoill** [comment] 2021-08-07 12:38
Any update?

**Comment by chrisbra** [comment] 2021-08-07 16:42
let's close it as unreproducible.

**Closed as completed by chrisbra** 2021-08-07 16:42 UTC
