### ISSUE TITLE
support rtl languages

### ISSUE THREAD

**Issue by motahharm** [vim/vim#9761] opened 2022-02-13 07:02 UTC
**Describe the solution you'd like**
hi everyone.
Right-to-left languages ​​are not properly supported by Vim
But Iranians, Arabs, etc. need to write Persian or Arabic.
like this:
![prob](https://user-images.githubusercontent.com/78138597/153742578-dd6360a5-2df6-438b-ac88-19c97f44a54a.png)
We would like the output to look like this:
```
hello
سلام
سلام العلیکم
ایران، عربستان، افغانستان، ترکمنستان
```

**Describe alternatives you've considered**
i not have spcial idea but i think `UTF-8` support rtl languages.

**Additional context**
vim now:
![prob](https://user-images.githubusercontent.com/78138597/153742578-dd6360a5-2df6-438b-ac88-19c97f44a54a.png)
we like to be:
![prob](https://user-images.githubusercontent.com/78138597/153742758-8077f12a-4653-4259-b8d7-d24b78d2b5db.png)

**Comment by dpelle** [comment] 2022-02-13 09:25
I do not speak Arabic. But try `:set arabic`
Consider also reading `:help arabic`
Does it solve your problem?
Consider also indicating your version of vim (output of `:version`) when reporting issues.

**Comment by motahharm** [comment] 2022-02-13 13:42
thanks @dpelle 
but it is reverse:
![prob](https://user-images.githubusercontent.com/78138597/153755811-f728d0a8-0635-4b55-a573-abe8fcb1c87a.png)
i need to be like this:
`چو ایران نباشد تن من مباد بدین بوم و بر زنده یک تن مباد`

**Comment by chrisbra** [comment] 2022-02-13 13:58
Then set `:set norightleft`. Please read `:h arabic.txt` for what is currently possible. Also please note, this quite heavily depends on whether you use a gui or use a terminal. For the terminal version, this requires a terminal that supports it correctly.

However, better arabic mode is quite complicated, as none of the developers know enough about the rules how to combine characters and therefore cannot really try it out. Also better bidi and right-left support has long been in the todo list. But for the reasons mentioned before, a patch from someone who knows and uses this natively is probably the best to hope.

**Comment by motahharm** [comment] 2022-02-15 05:46
hi @chrisbra 
thanks,
this is work only for arabic and my keyboard must be arabic.

but i and iranian developers need to write persion or farsi.

**Comment by brammool** [comment] 2022-02-15 14:00
> this is work only for arabic and my keyboard must be arabic.
> 
> but i and iranian developers need to write persion or farsi.

I'm afraid Persian/Farsi support was removed in patch 8.1.0932.
At that time it probably wasn't actually working, since nobody was
maintaining it.

It would be great to have better RTL support and also specific Farsi and
Arabic support.  This requires someone who knows the mechanisms
involved and can implement changes in Vim.

-- 
hundred-and-one symptoms of being an internet addict:
40. You tell the cab driver you live at
    http://123.elm.street/house/bluetrim.html
41. You actually try that 123.elm.street address.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by motahharm** [comment] 2022-02-16 05:33
thanks @brammool .

if i can help you.
i'll definitely help you so that we can do this.

persion/farsi is my first language But in some projects, Persian language does not work properly

**Comment by Konfekt** [comment] 2022-12-01 12:33
Out of curiosity: What did Farsi support achieve in addition to  

```vim
    setlocal arabic
    setlocal keymap=persian
```

@motahharm : Vim can write from right to left if the terminal (such as [urxvt](https://github.com/mkamensky/Text-Bidi/wiki/Installation-Instructions-for-urxvt)) supports it and enabling `&termbidi`.

**Comment by Konfekt** [comment] 2022-12-01 15:24
For what it's worth, attached a [phonetic persian vim keymap](https://github.com/vim/vim/files/10133662/persian-qwerty.vim.txt) similar to [that on Mac](https://github.com/gpuminingir/Farsi-Phonetic-Keyboard-Linux).

**Comment by Konfekt** [comment] 2022-12-02 19:41
To partially answer my above question, seemingly `&arabicshape`, the morphing of joint characters depending on their position in a word, misses some Persian ligatures such as  `ە` and `ا` becoming `ها`

**Comment by alikaramniya** [comment] 2023-11-11 04:40
Hi test blow command:

set termbidi

**Comment by avidseeker** [comment] 2024-02-17 23:36
For some reason, `:set rl` seems to re-shape letters assuming the terminal doesn't support letter shaping. While this might be the case in older terminals, most terminals currently do support letter shaping.

Here's a screenshot comparing Konsole (with shaping support) vs Alacritty (which doesn't support):
![image](https://github.com/vim/vim/assets/67508272/a2a82d46-cdd5-4fee-ade0-0e8f323ee977)

**Comment by avidseeker** [comment] 2024-02-29 09:03
This seems a duplicate of https://github.com/vim/vim/issues/204

**Comment by chrisbra** [comment] 2024-02-29 09:32
so closing then as duplicate

**Closed as not planned by chrisbra** 2024-02-29 09:32 UTC
Labels: duplicate, enhancement

**Comment by MasoudHeydari** [comment] 2025-07-30 07:58
> Hi test blow command:
> 
> set termbidi

Tnx, you saved my time.
