### ISSUE TITLE
'e' (e.g. 'de') does not work well when ft is 'vim'

### ISSUE THREAD

**Issue by Shane-XB-Qian** [vim/vim#4409] opened 2019-05-22 12:00 UTC
_Instructions: Replace the template text and remove irrelevant text (including this line)_

**Describe the bug**
'e' (e.g. 'de') does not work well when ft is 'vim'

**To Reproduce**
0, vim vimrc
1, type '#whatever#'
2, the 'cursor' on the letter 'w'
3, issue 'de'
4, it would cut 'whatever#' - including the end '#'

**Expected behavior**
normally it should just cut the 'whatever' - without the end '#'

**Screenshots**
- n/a

**Environment (please complete the following information):**
VIM - Vi IMproved 8.1 (2018 May 18, compiled May 22 2019 01:32:39)
Included patches: 1-1362

**Additional context**
should one of 'builtin' plugin caused the issue, but not sure which one ..
since if i removed all ext-plugins, the issue still there ..
and if i started the vim with '-u' : vim -u xxx, then it would work.
so far just found it happened when ft is vim.

**Comment by Shane-XB-Qian** [comment] 2019-05-22 12:02
vim -u NONE

**Comment by tonymec** [comment] 2019-05-22 12:25
This seems to be intentional: in `$VIMRUNTIME/ftplugin/vim.vim` there is the following at lines 44sqq:
```vim
" To allow tag lookup via CTRL-] for autoload functions, '#' must be a
" keyword character.  E.g., for netrw#Nread().
setlocal isk+=#
```

**Comment by chrisbra** [comment] 2019-05-22 12:36
if you do not want that behaviour, adjust your 'isk' setting. 
Please ask user questions on the vim_use mailinglist or use vi.stackexchange.com. This is not a bug. Closing.

**Closed as completed by chrisbra** 2019-05-22 12:36 UTC

**Comment by Shane-XB-Qian** [comment] 2019-05-22 12:43
oh, i see, thanks @tonymec
and yes, some vim-script func naming with '#' ..

but the side-effect is e.g. 'de' did not work proper ...
@chrisbra  ok, if it's acceptable to others .. i just did not notice that's a 'isk' ..

**Comment by brammool** [comment] 2019-05-22 21:13
> oh, i see, thanks @tonymec
> and yes, some vim-script func naming with '#' ..
> 
> but the side-effect is e.g. 'de' did not work proper ...
> @chrisbra  ok, if it's acceptable to others .. i just did not notice that's a 'isk' ..

You are not supposed to edit help files (only I'm allowed to do that :-).
Well, that's why sometimes a full stop goes missing...

-- 
hundred-and-one symptoms of being an internet addict:
15. Your heart races faster and beats irregularly each time you see a new WWW
    site address in print or on TV, even though you've never had heart
    problems before.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
