### ISSUE TITLE
'cursorline' local to window or local to buffer?

### ISSUE THREAD

**Issue by Yggdroot** [vim/vim#4945] opened 2019-09-17 09:00 UTC
**Describe the bug**

Is 'cursorline' local to window or local to buffer? 
We can conclude from the python api that 'cursorline' is local to window:
```python
py import vim
py vim.current.window.options["cursorline"]=True  # OK
py vim.current.buffer.options["cursorline"]=True  # KeyError: 'cursorline'
```
As per the doc, 
https://github.com/vim/vim/blob/0e57dd859ecb1e8a3b91509d2f4343e839340eb8/runtime/doc/options.txt#L2460-L2470
'cursorline' is local to window.

**BUT** the actual behavior is local to buffer.

**To Reproduce**

0. `set nocursorline` in vimrc
1. vim a.txt 
2. `:setlocal cursorline` ,  cursorline is displayed.
3.  `:e b.txt`, no cursorline
4. `:bp`, switched to a.txt, cursorline is displayed.
5. `:bn`, switched to b.txt, no cursorline

**Expected behavior**

There should not be such a paradox.
If it is local to window, the behavior should not be local to buffer.
If it is local to buffer, the doc should be updated and `py vim.current.buffer.options["cursorline"]=True` should be the correct usage, `py vim.current.window.options["cursorline"]=True` should not.

**Environment (please complete the following information):**
 - Vim version  8.1.1888
 - OS: All

**Comment by lacygoill** [comment] 2019-09-17 14:18
An option local to a window has two values: a global one and a local one.

The global value is not global to any window, but to the current window. That's why you can set two different global values in two different windows with `:setglobal`. It's used to initialize the local value when a new buffer is displayed in the window.

The local value is not local to any buffer displayed in the window, but to the current buffer displayed in the current window.

---

So, when you run `:setlocal cursorline`, you set the local value of `'cursorline'` in the current window for the current buffer `a.txt`; not for any buffer.

---

This is documented at `:h local-options`:

> It's possible to set a local window option specifically for a type of buffer.
> When you edit another buffer in the same window, you don't want to keep
> using these local window options.  Therefore Vim keeps a global value of the
> local window options, which is used when editing another buffer.  Each window
> has its own copy of these values.  Thus these are local to the window, but
> global to all buffers in the window.  With this you can do: >
>         :e one
>         :set list
>         :e two
> Now the 'list' option will also be set in "two", since with the ":set list"
> command you have also set the global value. >
>         :set nolist
>         :e one
>         :setlocal list
>         :e two
> Now the 'list' option is not set, because ":set nolist" resets the global
> value, ":setlocal list" only changes the local value and ":e two" gets the
> global value.  Note that if you do this next: >
>         :e one
> You will get back the 'list' value as it was the last time you edited "one".
> The options local to a window are remembered for each buffer.  This also
> happens when the buffer is not loaded, but they are lost when the buffer is
> wiped out |:bwipe|.

In particular this sentence:

> The options local to a window are remembered for each buffer.

**Comment by brammool** [comment] 2019-09-17 20:23
Thus working as intended?  Closing then.

**Closed as completed by brammool** 2019-09-17 20:23 UTC

**Comment by nickspoons** [comment] 2019-09-17 20:37
This doesn't seem right. @lacygoill is referring to buffer-local options, but there is a difference between buffer-local and window-local options, where window-local options should persist across buffers in that window. At least, that's always been my interpretation of `:h internal-variables`.

**Comment by nickspoons** [comment] 2019-09-17 20:43
Perhaps I (and @Yggdroot) have always misunderstood this feature. Tying window-local options to buffers doesn't seem so useful to me. It may explain the difficulty I've occasionally had tracking down the source of a window-local option setting though - I have been sure I've disables 'cursorline' in a window, then switched to previous buffer and there it was again. I had hoped this was a bug that might be addressed in this issue. But it's by design?

**Comment by lacygoill** [comment] 2019-09-17 21:06
> @lacygoill is referring to buffer-local options

No, the help tag `local-options` refers to both types of local options: buffer-local and window-local.

And the example given at the bottom uses `'list'` which is a window-local option, not a buffer-local option. From `:h 'list`:

    *'list'* *'nolist'*
    'list'			boolean	(default off)
    local to window

> At least, that's always been my interpretation of :h internal-variables.

I don't think that this help tag is relevant. It doesn't mention options, nor does it mention the `&`, `&l:`, `&g:` scopes. Besides, you can use `:unlet` to destroy an internal variable, but you can't do the same to destroy an option (e.g. `:unlet &cc` raises E488), so internal variables and options are different concepts.

> Tying window-local options to buffers doesn't seem so useful to me.

To be more accurate, the global value of a window-local option is tied to a window.
But the local value of a window-local option is tied to a buffer in a window; it's not tied to only a window, nor to only a buffer.

> But it's by design?

I think so. From `:h local-options`:

> When you edit another buffer in the same window, you don't want to keep using these local window options.

---

I'm not saying the current behavior is good nor bad. I'm just saying that it's consistent with the documentation.

**Comment by Yggdroot** [comment] 2019-09-18 03:17
@lacygoill So a local to window option is actually local to (window, buffer) pair, right?

I can not find a way to disable a window local option, 
For example,

0. `set nocursorline` in vimrc
1. vim a.txt 
2. `:setlocal cursorline` ,  cursorline is displayed.
3.  `:e b.txt`, no cursorline 

After step 3, how can I `setlocal nocursorline` for (current window, buffer a.txt) without switching to a.txt?

That is to say, if I write script in python, 'cursorline' should not be a key of vim.current.window.options, it should be a key of vim.current.**window_buffer_pair**.options(if there is such an object).

**Comment by chrisbra** [comment] 2019-09-18 06:57
A buffer does not have a cursor, only a window has, so I suppose you need to switch to the buffer first to disable the 'cursorline'  setting. You can probably use `bufdo`.

**Comment by Yggdroot** [comment] 2019-09-18 07:25
@chrisbra  `bufdo` may affect other buffers, moreover if run bufdo in another window but not in which `setlocal cursorline` is set, it does not take effect.

**Comment by chrisbra** [comment] 2019-09-18 07:28
Well, I believe there is no other possibility than to first load the buffer. And bufdo does the load all buffers in the current window, which I thought you want to achieve.

**Comment by lacygoill** [comment] 2019-09-18 13:02
> After step 3, how can I setlocal nocursorline for (current window, buffer a.txt) without switching to a.txt?

I would use `setbufvar()`. Assuming `a.txt` is the buffer 1, it would give:

    :call setbufvar(1, '&cursorline', 0)
                    │   │             │
                    │   │             └ new value assigned to option
                    │   └ option to modify
                    └ index of target buffer

![gif](https://user-images.githubusercontent.com/8505073/65148915-6680be00-da21-11e9-9fda-c05cd7507040.gif)

However, it doesn't work when the buffer is hidden:

![gif](https://user-images.githubusercontent.com/8505073/65149132-da22cb00-da21-11e9-9811-77728c017a1a.gif)

This is not because `setbufvar()` can't alter a window option. It can:

> This also works for a global or local window option, but it
> doesn't work for a global or local window variable.
> For a local window option the global value is unchanged.

I think that the effect of `setbufvar()` is undone when the buffer goes from hidden to displayed.
When that happens, Vim reapplies the value it remembers from the last time the buffer was displayed:

> The options local to a window are remembered for each buffer.

IMO, there should be a way for the user to alter the last remembered value of a window-local option, via `setbufvar()` or something else. At the moment, it seems there is none.
I find this unexpected; maybe it could be considered as a bug, I don't know.

I'm not sure it will help, but I also had an issue with window-local options in the past (values set from a filetype plugin were not always set). I fixed this issue by setting the options from an autocmd listening to `BufWinEnter`.

Maybe you could also try an autocmd:

    au BufWinEnter a.txt ++once setl nocul

![gif](https://user-images.githubusercontent.com/8505073/65150695-ee1bfc00-da24-11e9-8f05-5709eed6dcd5.gif)

The `++once` argument causes the autocmd to be fired only once. It was added in [8.1.1113](https://github.com/vim/vim/releases/tag/v8.1.1113).

Without it, you can get the same effect by making the autocmd remove itself:

    augroup setl_nocul
        au!
        au BufWinEnter a.txt setl nocul | au! setl_nocul
    augroup END

Edit: If `a.txt` is displayed in several windows, and `'cursorline'` is set in all of them, then `:call setbufvar(1, '&cul', 0)` only resets the option in one of the window; so `setbufvar()` is not the right tool, sorry.

**Comment by Yggdroot** [comment] 2019-09-18 13:42
@lacygoill Thanks for your pacient explanation.
