### ISSUE TITLE
vim-gtk caught SEGV signal when using amenu command

### ISSUE THREAD

**Issue by tracyone** [vim/vim#2670] opened 2018-02-24 13:07 UTC
reproduce step
===

```bash
./vim -g -u NONE
```

Then execute following command:

```vim
:tmenu ToolBar.Find find
:amenu ToolBar.-Sep- :
```

**version info**
===

**ubuntu 16.04 x64 unity**

```bash
./configure \
    --enable-fail-if-missing \
    --disable-darwin \
    --enable-gui=gtk3 \
    --enable-xim \
    --enable-fontset \
    --with-features=huge \
    --enable-perlinterp=dynamic \
    --enable-python3interp=dynamic \
    --enable-tclinterp=dynamic \
    --enable-cscope \
    --enable-terminal \
    --enable-autoservername \
    --enable-multibyte \
    CFLAGS="-g -DDEBUG -Wall -Wshadow -Wmissing-prototypes" \
    --enable-fontset \
```

```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Feb 24 2018 20:19:29)
Included patches: 1-1531
Compiled by tracyone@tracyone-pc
Huge version with GTK3 GUI.  Features included (+) or not (-):
+acl               +clientserver      +dialog_con_gui    +find_in_path      +keymap            +modify_fname      +multi_byte        +profile           +statusline        +textobjects       +wildignore
+arabic            +clipboard         +diff              +float             +lambda            +mouse             +multi_lang        -python            -sun_workshop      +timers            +wildmenu
+autocmd           +cmdline_compl     +digraphs          +folding           +langmap           +mouseshape        -mzscheme          +python3/dyn       +syntax            +title             +windows
+autoservername    +cmdline_hist      +dnd               -footer            +libcall           +mouse_dec         +netbeans_intg     +quickfix          +tag_binary        +toolbar           +writebackup
+balloon_eval      +cmdline_info      -ebcdic            +fork()            +linebreak         +mouse_gpm         +num64             +reltime           +tag_old_static    +user_commands     +X11
+balloon_eval_term +comments          +emacs_tags        +gettext           +lispindent        -mouse_jsbterm     +packages          +rightleft         -tag_any_white     +vertsplit         -xfontset
+browse            +conceal           +eval              -hangul_input      +listcmds          +mouse_netterm     +path_extra        -ruby              +tcl/dyn           +virtualedit       +xim
++builtin_terms    +cryptv            +ex_extra          +iconv             +localmap          +mouse_sgr         +perl/dyn          +scrollbind        +termguicolors     +visual            +xpm
+byte_offset       +cscope            +extra_search      +insert_expand     -lua               -mouse_sysmouse    +persistent_undo   +signs             +terminal          +visualextra       +xsmp_interact
+channel           +cursorbind        +farsi             +job               +menu              +mouse_urxvt       +postscript        +smartindent       +terminfo          +viminfo           +xterm_clipboard
+cindent           +cursorshape       +file_in_path      +jumplist          +mksession         +mouse_xterm       +printer           +startuptime       +termresponse      +vreplace          -xterm_save
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/mirclient -I/usr/include/mircore -I/usr/include/mircookie -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng12 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include   -g -DDEBUG -Wall -Wshadow -Wmissing-prototypes -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -Wl,-E   -L/usr/local/lib -Wl,--as-needed -o vim   -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl   -Wl,-E  -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/x86_64-linux-gnu/perl/5.22/CORE -lperl -ldl -lm -lpthread -lcrypt   -L/usr/lib/x86_64-linux-gnu -ltclstub8.6 -ldl -lz -lpthread -lieee -lm     
  DEBUG BUILD
```

bt
===

```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./vim -g -u NONE'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f892b6dd767 in kill () at ../sysdeps/unix/syscall-template.S:84
84      ../sysdeps/unix/syscall-template.S: 没有那个文件或目录.
[Current thread is 1 (Thread 0x7f892f38fa80 (LWP 6884))]
(gdb) bt
#0  0x00007f892b6dd767 in kill () at ../sysdeps/unix/syscall-template.S:84
#1  0x000000000056deca in may_core_dump () at os_unix.c:3381
#2  0x000000000056de6e in mch_exit (r=1) at os_unix.c:3347
#3  0x00000000006a186e in getout (exitval=1) at main.c:1552
#4  0x0000000000522096 in preserve_exit () at misc1.c:9642
#5  0x000000000056ba18 in deathtrap (sigarg=6) at os_unix.c:1162
#6  <signal handler called>
#7  0x00007f892b6dd428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#8  0x00007f892b6df02a in __GI_abort () at abort.c:89
#9  0x00007f892d42ad65 in g_assertion_message () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#10 0x00007f892d42adfa in g_assertion_message_expr () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#11 0x00007f892ec12876 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#12 0x00007f892ec14980 in gtk_toolbar_insert () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#13 0x000000000064d91b in gui_mch_add_menu_item (menu=0x2cfa9e0, idx=27) at gui_gtk.c:711
#14 0x000000000050ecbb in add_menu_path (menu_path=0x2a95806 "ToolBar.-Sep-", menuarg=0x7ffe0eb2f7d0, pri_tab=0x7ffe0eb2f7a0, call_data=0x2aaf9b0 ":") at menu.c:676
#15 0x000000000050e62e in ex_menu (eap=0x7ffe0eb2f980) at menu.c:388
#16 0x00000000004aaa9e in do_one_cmd (cmdlinep=0x7ffe0eb2fba0, sourcing=0, cstack=0x7ffe0eb2fc90, fgetline=0x4c3639 <getexline>, cookie=0x0) at ex_docmd.c:2920
#17 0x00000000004a742a in do_cmdline (cmdline=0x0, fgetline=0x4c3639 <getexline>, cookie=0x0, flags=0) at ex_docmd.c:1067
#18 0x0000000000541777 in nv_colon (cap=0x7ffe0eb30210) at normal.c:5408
#19 0x0000000000539bbd in normal_cmd (oap=0x7ffe0eb302a0, toplevel=1) at normal.c:1151
#20 0x00000000006a14ce in main_loop (cmdwin=0, noexmode=0) at main.c:1367
#21 0x00000000006a0bcd in vim_main2 () at main.c:912
#22 0x00000000006a02cd in main (argc=4, argv=0x7ffe0eb304a8) at main.c:436

```

**Comment by brammool** [comment] 2018-02-24 17:48
I can't reproduce this problem.

**Comment by chrisbra** [comment] 2018-05-23 20:02
no more info, closing as unreproducible

**Closed as completed by chrisbra** 2018-05-23 20:02 UTC
