### ISSUE TITLE
Executing :badd unexpectedly prevents window-local options from propagating into new windows

### ISSUE THREAD

**Issue by matveyt** [vim/vim#7195] opened 2020-10-24 13:08 UTC
**Describe the bug**
Normally when opening already existing buffer in a new window, Vim tries to copy window-local options (if any set) from existing window into this new window. However, previously executing `:badd` on a buffer has unexpected side-effect of disabling this functionality.

**To Reproduce**
1. Run `vim --clean`

2. Create second buffer/window (with an arbitrary name) and set a window-local option to non-default value:

        vnew cole
        setl cole=2

3. Switch back to the first (unnamed) window/buffer (so "cole" will become inactive)

        wincmd p

4. Now if we do just `:vnew cole` and `:setl cole?` then it shows `conceallevel=2`, as expected. However, if we issue `:badd` first, for some reason it sets window-local options to defaults:

        badd cole
        vnew cole
        setl cole?

And it shows that `conceallevel=0` in the third (last created) window.

**Expected behavior**
:badd should not impose such unforeseeable and undocumented side-effects. What makes it worse, `:mksession` thoughtlessly inserts a bunch of `badd`s into generated session files (this is how I ran into this issue) to restore current line number(s). But it leads to more than just that!

**Comment by lacygoill** [comment] 2020-10-24 13:26
Possible duplicate of https://github.com/vim/vim/issues/4994.

Relevant todo item:
https://github.com/vim/vim/blob/e1be11864d1f4383171e3af3eb77e61d41140c4e/runtime/doc/todo.txt#L458

**Comment by matveyt** [comment] 2020-10-24 14:08
So it's on the list for a long time already. Maybe I'll try to fix it myself then...

**Closed as completed** 2020-10-25 14:03 UTC

**Comment by matveyt** [comment] 2020-10-25 14:34
@brammool  Unfortunately, patch 1902 is not enough, as it only solves the problem with `badd SomeNewBuffer`, but not with `badd +1 SomeNewBuffer`.

**Comment by brammool** [comment] 2020-10-25 15:46
Hmm, that is quite tricky.  There will be an entry for the window then, but somehow we don't want to use it.  I'll figure out the condition when to use it....
