### ISSUE TITLE
Manpager incorrect width when signcolumn is set

### ISSUE THREAD

**Issue by balki** [vim/vim#15152] opened 2024-07-05 16:35 UTC
### Steps to reproduce

1. `export MANPAGER="vim +MANPAGER --not-a-term -"`
2. set `signcolumn=yes` in vimrc
3. Run `man man`

![image](https://github.com/vim/vim/assets/189196/c30abe62-d58a-4417-984c-c63194b35709)

---

I suspect this issue is here: https://github.com/vim/vim/blob/master/runtime/autoload/dist/man.vim#L191 . I tried to change `winwidth` to `getwininfo` and subtract `textoff`. But does not seem to work for me.

---

It was difficult to pinpoint the problem to signcolumn for me as `--clean` option did not load man plugin (i.e. `export MANPAGER="vim --clean +MANPAGER --not-a-term -"`). Is there a way to start vim cleanly but load just the default plugins?

### Workaround

Disable `signcolumn` for file type man

    autocmd Filetype man setlocal signcolumn=no

### Expected behaviour

width calculated correctly, so the last character does not wrap to next line

### Version of Vim

9.1.496

### Environment

linux bash

**Comment by chrisbra** [comment] 2024-07-05 18:54
> https://github.com/vim/vim/blob/master/runtime/autoload/dist/man.vim#L191

This doesn't seem to be involved, as can be seen by `:scriptnames`. We should probably rather disable signcolumn in [manpager.vim](https://github.com/vim/vim/blob/master/runtime/plugin/manpager.vim) 

@Konfekt please :)

**Comment by chrisbra** [comment] 2024-07-06 09:30
BTW: I cannot reproduce this specific issue. For me, the man page looks fine, even with signcolumn enabled.

**Comment by Konfekt** [comment] 2024-07-07 07:33
Neither can I reproduce with Vim 9.1.145 on Opensuse 15.5 and Urxvt on Bash or Zsh and

```sh
MANPAGER="/usr/bin/vim --clean -u ~/.vim/viminrc +MANPAGER --not-a-term -" man man
```

and `~/.vim/viminrc` reading

```vim
set nocompatible
let &rtp = '/usr/share/vim/vim91/plugin' . ',' . &rtp
set signcolumn=yes
filetype plugin indent on
syntax on
```

as shows

![immagine](https://github.com/vim/vim/assets/7195553/c914002a-86e8-4a52-b1b1-0c07950486d5)

Did a commit between 9.1.141 and 9.1.496 break &signcolumn  ? (I suppose that @chrisbra used a more recent version though).
I wonder if it could be related to the terminal? @balki, did you try with different terminals?

**Comment by chrisbra** [comment] 2024-07-13 16:07
let's close it as non-reproducible then.

**Closed as not planned by chrisbra** 2024-07-13 16:07 UTC
Labels: runtime, bug
