### ISSUE TITLE
Cannot set `spellfile` when `$HOME` contains an at sign (@)

### ISSUE THREAD

**Issue by rexkerr** [vim/vim#10798] opened 2022-07-26 17:43 UTC
My username, and thus my `$HOME` path, contains an ampersand, in the format of:

     /home/rkerr@domain.company.com

As painful as this has been, I cannot control it as this is happening on my IT configured work computer.

I have this in my `.vimrc`, which works fine in 8.0.1453, but no longer works as of vim 9.0:

     set spellfile=$HOME/.vim/spell/en.utf-8.add

This fails with `E474:  Invalid argument` (I have also tried using the `~` symbol as well as an absolute path, with the same outcome).  Pointing to the same file, but using a symlink to the file works fine, so it's not the file itself that is causing the failure.  

I can work around this using the aforementioned explicit path via symlink, but I'd like to use a relative path to share the same `.vimrc` between all of my systems.

**Comment by lacygoill** [comment] 2022-07-26 18:14
If it is a regression, then it was introduced in patch [8.1.1143](https://github.com/vim/vim/releases/tag/v8.1.1143).

**Comment by chrisbra** [comment] 2022-07-29 06:45
I think, you need to modify your ['isfname'](https://vimhelp.org/options.txt.html#%27isfname%27) to include the `@`. At least that is how I can fix this issue here I think. 

So please try:

`:set isfname+=@-@` and then setting the `'spellfile'` option.

**Comment by rexkerr** [comment] 2022-08-03 22:59
That works, thanks.

**Comment by rexkerr** [comment] 2022-08-03 23:03
What I don't understand is why that was necessary.  The `isfname` setting already had a @ in it:

```
isfname=@,48-57,/,.,-,_,+,,,#,$,%,~,=
```

Why does adding `@-@` to it help, and why was the old `isfname` value (which was the same in the 8.0 release) working?

**Comment by lacygoill** [comment] 2022-08-04 00:34
> What I don't understand is why that was necessary. The isfname setting already had a @ in it:

Inside the value of `'isfname'`, `@` does not stand for the `@` character but for a whole class of characters.  From [`:help 'isfname'`](https://vimhelp.org/options.txt.html#%27isfname%27):

   > If the character is '@', all characters where isalpha() returns TRUE
   > are included.  Normally these are the characters a to z and A to Z,
   > plus accented characters.

---

   > Why does adding @-@ to it help

Since the symbol `@` is already taken to mean something else, we need another way to represent the character `@` itself.  That's where `@-@` comes in.  It's documented right after the previous excerpt.

   > To include '@' itself use "@-@".

---

   > and why was the old isfname value (which was the same in the 8.0 release) working?

IMO, this is a regression introduced in 8.1.1143.

The commit message says this:

    Problem:    May pass weird strings to file name expansion.

The word "weird" is subjective, but the second line of the message gives more details:

    Solution:   Check for matching characters.  Disallow control characters.

This is confirmed in the comments of the patch:

    // Disallow line break characters.
    // Allow for escaping.
    // A { must be followed by a matching }.
    // A quote and backtick must be followed by another one.

The first one disallows line breaks (which is `LF` on Linux, aka `^J` a control character).
The second one allows a backslash used to quote/escape a special character.
The third one enforces the presence of a closing `}` after a `{`.
The fourth one enforces the presence of a closing quote/backtick after an opening one.

None of this disallows the `@` character.

For the moment, you can tweak `'isfname'`, but it can have undesirable side effects.  In particular, it's a global option; including `@` will affect all buffers.  Maybe we should allow `@` as we did before 8.1.1143.

**Comment by lacygoill** [comment] 2022-08-04 01:41
> Maybe we should allow @ as we did before 8.1.1143.

How about this patch:
```diff
diff --git a/src/spell.c b/src/spell.c
index 24abce462..b40ce02dd 100644
--- a/src/spell.c
+++ b/src/spell.c
@@ -4363,7 +4363,7 @@ valid_spellfile(char_u *val)
     char_u *s;
 
     for (s = val; *s != NUL; ++s)
-	if (!vim_isfilec(*s) && *s != ',' && *s != ' ')
+	if (!vim_isfilec(*s) && *s != ',' && *s != ' ' && *s != '@')
 	    return FALSE;
     return TRUE;
 }
diff --git a/src/testdir/test_spellfile.vim b/src/testdir/test_spellfile.vim
index 38d1ec083..3618d195f 100644
--- a/src/testdir/test_spellfile.vim
+++ b/src/testdir/test_spellfile.vim
@@ -1160,4 +1160,11 @@ func Test_mkspellmem_opt()
   call assert_fails('set mkspellmem=1000,50,0', 'E474:')
 endfunc
 
+def Test_spellfile_allow_at_character()
+  mkdir('Xtest/foo@bar', 'p')
+  &spellfile = './Xtest/foo@bar/Xspellfile.add'
+  &spellfile = ''
+  delete('Xtest', 'rf')
+enddef
+
 " vim: shiftwidth=2 sts=2 expandtab
```

**Comment by lacygoill** [comment] 2022-08-04 02:00
BTW, to avoid some confusion when reading the report, I suggest you replace "[ampersand](https://en.wikipedia.org/wiki/Ampersand)" with "[at sign](https://en.wikipedia.org/wiki/At_sign)" or "commercial at".

**Comment by lacygoill** [comment] 2022-08-04 02:41
OTOH, it does make sense to honor `'isfname'` when setting a filename.  Although, not sure why the at sign is not considered as a valid character in a filename by default (except for Win32).  I guess that's because it's often used as a delimiter between a login name and a host name.

But if that's the case, then why don't we also give an error when setting `'errorfile'` with a filename including an at sign:

    $ vim --clean +'set errorfile=foo@bar'
    # expected: an error is given
    # actual: no error is given

Anyway, if it's working as intended, then we might want to document this:
```diff
diff --git a/runtime/doc/options.txt b/runtime/doc/options.txt
index 55c2146b9..a3bd0b2f9 100644
--- a/runtime/doc/options.txt
+++ b/runtime/doc/options.txt
@@ -4677,8 +4677,9 @@ A jump table for the options with a short description can be found at |Q_op|.
 			    otherwise: "@,48-57,/,.,-,_,+,,,#,$,%,~,=")
 			global
 	The characters specified by this option are included in file names and
-	path names.  Filenames are used for commands like "gf", "[i" and in
-	the tags file.  It is also used for "\f" in a |pattern|.
+	path names.  Filenames are used for commands like "gf", "[i", options
+	like 'spellfile' and in the tags file.  It is also used for "\f" in a
+	|pattern|.
 	Multi-byte characters 256 and above are always included, only the
 	characters up to 255 are specified with this option.
 	For UTF-8 the characters 0xa0 to 0xff are included as well.
@@ -7327,6 +7328,7 @@ A jump table for the options with a short description can be found at |Q_op|.
 	Name of the word list file where words are added for the |zg| and |zw|
 	commands.  It must end in ".{encoding}.add".  You need to include the
 	path, otherwise the file is placed in the current directory.
+	The value of this option must only include characters from 'isfname'.
 								*E765*
 	It may also be a comma-separated list of names.  A count before the
 	|zg| and |zw| commands can be used to access each.  This allows using
```

**Comment by chrisbra** [comment] 2022-08-04 12:17
fixed by https://github.com/vim/vim/commit/bc49c5f48f89c2d6f4d88ee77f44a11d68293be3

**Closed as completed by chrisbra** 2022-08-04 12:17 UTC
