### ISSUE TITLE
popup not show immediately when following a getchar()

### ISSUE THREAD

**Issue by ZhiyuanLck** [vim/vim#7404] opened 2020-12-02 08:49 UTC
Below is the test script.
`test.vim`
```vim
function! Test()
  let winid = ['111', '222', '333']
        \ ->popup_create(#{
        \ maxwidth: 10,
        \ minwidth: 10,
        \ maxheight: 5,
        \ minheight: 5,
        \ pos: 'center',
        \ })
  echom winid
  let nr = getchar()
  echom nr
endfunction
```
1. run `vim -S test.vim --clean`
2. run `:call Test()`

Then you can see that winid is printed but there is no popup shown and vim wait for me to type keys. Then after the execution of `getchar()`, the popup is shown.

**Environment:**
 - Vim version: VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Oct 24 2020 16:26:37) contain patch 1-2020
 - OS: Ubuntu 18.04,
 - Terminal: GNOME Terminal

**Comment by lacygoill** [comment] 2020-12-02 09:41
As a workaround, you can add a `:redraw` right after invoking `popup_create()` to force Vim to redraw the screen, and display the popup:
```vim
function! Test()
  let winid = ['111', '222', '333']
        \ ->popup_create(#{
        \ maxwidth: 10,
        \ minwidth: 10,
        \ maxheight: 5,
        \ minheight: 5,
        \ pos: 'center',
        \ })
  redraw
  echom winid
  let nr = getchar()
  echom nr
endfunction
```

**Comment by chrisbra** [comment] 2020-12-21 07:36
closing as duplicate of #7118

**Closed as completed by chrisbra** 2020-12-21 07:36 UTC
Labels: duplicate
