### ISSUE TITLE
Display corruption after placing a sign in a nested autocmd

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#1238] opened 2016-11-07 18:18 UTC
I wanted to have some space between the beginning of a line inside a buffer and the left border of the screen. I found a way to do it [here](http://superuser.com/a/558885), by placing a sign on the first line of all buffers:
```
sign define dummy
augroup dummy_sign
    autocmd!
    autocmd BufEnter * exe 'sign place 9999 line=1 name=dummy buffer=' . bufnr('%')
augroup END
```

It seemed to work well until I tried a plugin which installed an autocmd triggered by the `ShellCmdPost` event. Among other things, the autocmd loaded a different buffer than the one where the shell command was executed. After the loading of this buffer, the display was corrupted.

Here is a way to reproduce:

```
colorscheme evening
sign define dummy
augroup dummy_sign
    autocmd!
    autocmd BufEnter     * exe 'sign place 9999 line=1 name=dummy buffer=' . bufnr('%')
    autocmd ShellCmdPost * nested buffer 2
augroup END
```

If I write the previous code in `/tmp/vimrc.vim`, then launch Vim from the shell like this:

`$ vim -Nu /tmp/vimrc.vim /tmp/foo /tmp/vimrc.vim`

Then, inside Vim type:

 `:!echo hello`

…to execute a shell command, after hitting `Enter` to get back to Vim, the display is corrupted (sorry, I don't know if it is the correct term, some part of the screen gets invisible).

The problem doesn't appear if the `nested` flag of the 2nd autocmd is removed.
With the `nested` flag, the shell command probably triggers a `BufEnter` event, which in turn places a sign on the first line, and then, for some reason, the display gets corrupted.

It can be fixed by hitting `<C-L>`, or typing `:redraw!`, or changing the event of the 1st autocmd from `BufEnter` to `BufRead`.

I don't know whether it's a bug, and even if it is, it's probably not very important, but I thought it would be a good idea to report it, just in case.

I'm using linux, guake or xfce4-terminal, and Vim version 7.4 (patches 1-2156 included).
Here's the [report ](http://pastebin.com/ykzALTfr) produced by `:so $VIMRUNTIME/bugreport.vim`.

**Comment by chrisbra** [comment] 2016-11-08 14:11
I see some redrawing artifacts that are cleared immediately after returning from the shell, but cannot reproduce this reliably. Was that gvim or in a terminal? If so, what terminal? BTW: with newer vims you can simply `:set signcolumn=yes` and do not need such hacks about placing a dummy sign. Closing therefore.

**Closed as completed by chrisbra** 2016-11-08 14:11 UTC
