### ISSUE TITLE
Script-scoped function arguments

### ISSUE THREAD

**Issue by igbanam** [vim/vim#12682] opened 2023-07-17 19:07 UTC
### Steps to reproduce

With

```vim
vim9script

def Padding(s: string)
  echom "  " .. s .. "  "
enddef

var s = "this" .. ":" .. "that"
s->Padding()
```

…as `./this.vim`, run Vim with 

```sh
vim --clean +'so ./this.vim'
```

### Expected behaviour

`  this:that  ` should be echoed as a message.

`s` as the function argument should be local to the function scope; i.e. equivalent to `l:s` in legacy Vimscript. Instead, seems the function argument is equivalent to `s:s`

### Version of Vim

VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Jun 23 2023 15:15:13)

### Environment

VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Jun 23 2023 15:15:13)
macOS version - arm64
Included patches: 1-1650

Mac OS X
iTerm
xterm-256color-italic
ZSH

**Comment by bfrg** [comment] 2023-07-18 00:17
That's not a bug. When you source the above script, Vim throws the following error:
```
E1168: Argument already declared in the script: s
```

Under `:h E1168` you can find the explanation.

**Comment by chrisbra** [comment] 2023-07-18 06:11
closing

**Closed as completed by chrisbra** 2023-07-18 06:11 UTC
Labels: bug

**Comment by igbanam** [comment] 2023-07-19 17:13
@bfrg what I was trying to point out is that these are two different scopes. As an argument to a function, the variable should be in `local` scope, but it's polluting the `script` scope.

Technically, we shouldn't be getting E1168 here

**Comment by bfrg** [comment] 2023-07-19 17:27
IIRC this has been discussed somewhere but I don't remember where and what the reasons were for the current behavior. Feel free to reopen and mark this issue as a feature request.

**Comment by chrisbra** [comment] 2023-07-19 18:43
This was an intentional choice. I don't remember any discussions on this and the relevant commit does not mention an issue number or similar: 9a015111a56d0011ced40d98f46a9841

**Comment by chrisbra** [comment] 2023-07-20 05:39
Actually there was a bit of discussion at the end of the commit: https://github.com/vim/vim/commit/9a015111a56d0011ced40d98f46a9841d1457b51

**Comment by lifepillar** [comment] 2023-07-20 10:55
Maybe, an example in `:h E1168` would help clarify this design choice? Currently, the help tells the what, but not the why.

In [the above mentioned discussion](https://github.com/vim/vim/commit/9a015111a56d0011ced40d98f46a9841d1457b51), the main motivation seems to be summarized by this sentence:

>It has bitten me several times, especially in a long function, that I thought I was using an object member, but it was
shadowed by a function argument. 

This sounds like a valid argument, but it took me a few minutes to come up with an example (and I am not sure that this is the best example):

```vim
class A
  this.x: number
endclass

const a = A.new()

def F(a: A)
  # Long body referring to a.x at some point
enddef

const a2 = A.new()
F(a2)
```

If I understand correctly, the problem E1168 avoids is that the user's intention may be to have a function using a script-level object `a`. For some reason (perhaps, after a refactoring that renames variables?), that function ends up having a parameter with the same name, at which point `a` in the body of the function does not refer to the script-level object any more.

I have encountered E1168 several times, and to me it was a mild annoyance, because the code did not have any unintentional shadowing. But the error forces you to use different names for different things within the same script, which one may argue is good for clarity or legibility. To me, this falls in the class of the “language features forcing some discipline on you” (similar to mandatory spacing).
