### ISSUE TITLE
Running gvim in foreground causes some toolbar icons to disappear

### ISSUE THREAD

**Issue by metasyntax** [vim/vim#567] opened 2016-01-18 19:38 UTC
The default gVim launcher in Arch uses the "`-f`" option to run in the foreground. When doing that, some of the toolbar icons disappear. This doesn't happen when forking to the background (i.e. without "`-f`"). I've attached two screenshots to show the behavior.

This is what I get with `gvim -N -u NONE -U NONE`:

![background](https://cloud.githubusercontent.com/assets/593731/12400849/861fe250-bdf0-11e5-8d48-23bde35579f8.png)

This is what I get with `gvim -N -u NONE -U NONE -f`:

![foreground](https://cloud.githubusercontent.com/assets/593731/12400850/8623b84e-bdf0-11e5-8cc1-0ca4b630ae13.png)

 Here's my `:version`

```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jan 13 2016 12:08:13)
Included patches: 1-1089
Compiled by Arch Linux
Huge version with GTK2 GUI.  Features included (+) or not (-):
+acl             +cscope          +folding         +menu            +netbeans_intg   -sniff           +virtualedit
+arabic          +cursorbind      -footer          +mksession       +path_extra      +startuptime     +visual
+autocmd         +cursorshape     +fork()          +modify_fname    +perl/dyn        +statusline      +visualextra
+balloon_eval    +dialog_con_gui  +gettext         +mouse           +persistent_undo -sun_workshop    +viminfo
+browse          +diff            -hangul_input    +mouseshape      +postscript      +syntax          +vreplace
++builtin_terms  +digraphs        +iconv           +mouse_dec       +printer         +tag_binary      +wildignore
+byte_offset     +dnd             +insert_expand   +mouse_gpm       +profile         +tag_old_static  +wildmenu
+cindent         -ebcdic          +jumplist        -mouse_jsbterm   +python/dyn      -tag_any_white   +windows
+clientserver    +emacs_tags      +keymap          +mouse_netterm   +python3/dyn     -tcl             +writebackup
+clipboard       +eval            +langmap         +mouse_sgr       +quickfix        +terminfo        +X11
+cmdline_compl   +ex_extra        +libcall         -mouse_sysmouse  +reltime         +termresponse    -xfontset
+cmdline_hist    +extra_search    +linebreak       +mouse_urxvt     +rightleft       +textobjects     +xim
+cmdline_info    +farsi           +lispindent      +mouse_xterm     +ruby/dyn        +title           +xsmp_interact
+comments        +file_in_path    +listcmds        +multi_byte      +scrollbind      +toolbar         +xterm_clipboard
+conceal         +find_in_path    +localmap        +multi_lang      +signs           +user_commands   -xterm_save
+cryptv          +float           +lua/dyn         -mzscheme        +smartindent     +vertsplit       -xpm
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "/etc/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/gtk-2.0/inclu
de -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libdrm -I
/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/pango-1.0 -I/usr/include/freetype2 -I/usr/include/lib
png16 -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/gl
ib-2.0 -I/usr/lib/glib-2.0/include -D_FORTIFY_SOURCE=2  -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong
-U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L. -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E -Wl
,-rpath,/usr/lib/perl5/core_perl/CORE  -Wl,-O1,--sort-common,--as-needed,-z,relro -L/usr/local/lib -Wl,--as-needed -o vi
m   -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0
 -lgobject-2.0 -lglib-2.0 -lfontconfig -lfreetype -lSM -lICE -lXt -lX11 -lXdmcp -lSM -lICE  -lm -lncurses -lelf -lnsl
 -lacl -lattr -lgpm -ldl   -Wl,-E -Wl,-rpath,/usr/lib/perl5/core_perl/CORE -Wl,-O1,--sort-common,--as-needed,-z,relro -f
stack-protector-strong -L/usr/local/lib  -L/usr/lib/perl5/core_perl/CORE -lperl -lpthread -lnsl -ldl -lm -lcrypt -lutil
-lc
```

This is the binary version currently distributed by Arch Linux. But since it changes depending on "`-f`" I thought it might be a bug in Vim. Thanks for looking.

**Comment by vim-ml** [comment] 2016-01-19 06:56
This issue is caused by calling gui_gtk_register_resource() at a wrong
place when gvim is invoked with the option -f.

Attached is a patch to fix it.

Thank you for reporting.

Best regards,
Kazunobu Kuriyama

2016-01-19 4:38 GMT+09:00 Taylor Venable vim-dev-github@256bit.org:

**Comment by nuko8** [comment] 2016-01-19 09:00
Patch updated.

Cleanup code is added in case the GUI initialization should fail.

Although the previous patch causes no problem, the updated one is more
sanitary than the previous one, I hope :-)

2016-01-19 15:56 GMT+09:00 vim-dev ML notifications@github.com:

**Comment by chrisbra** [comment] 2016-01-19 17:45
Fixed by https://github.com/vim/vim/releases/tag/v7.4.1138

**Closed as completed by chrisbra** 2016-01-19 17:45 UTC
