### ISSUE TITLE
Setting termguicolors in Vim causes Windows Terminal to become opaque

### ISSUE THREAD

**Issue by Chaoticsys101** [vim/vim#7162] opened 2020-10-17 21:37 UTC
**Describe the bug**
I use Vim in Windows Terminal. If termguicolors is set the acrylic transparency of WT stops working. 

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Open the new Windows Terminal and set acrylic transparency on
2. Run `vim --clean` 
3. Run the command `:set termguicolors`

**Expected behavior**
The WT background's opacity shouldn't be altered. 

**Screenshots**
![IMG_20201017_221853](https://user-images.githubusercontent.com/67800528/96353935-b4567280-10c8-11eb-95c1-ac0ec51f0565.jpg)
![IMG_20201017_221921](https://user-images.githubusercontent.com/67800528/96353946-cf28e700-10c8-11eb-8a9c-f3609015f3b3.jpg)

**Environment**
 - Vim: 8.2.1818
 - OS: Windows 10
 - Terminal: Windows Terminal 1.3.2651.0

**Comment by chrisbra** [comment] 2020-10-18 14:35
is this windows terminal specific? Do you set the Normal highlighting group?

**Comment by Chaoticsys101** [comment] 2020-10-18 14:44
Yes, it is Windows Terminal specific. I have tried cmd.exe and it works.
I have it set on my vimrc and the issue persists. I only said to try `vim --clean` to make sure the problem is not on my vimrc

**Comment by chrisbra** [comment] 2020-10-18 14:46
Don't you need to remove the background color for the Normal highlighting group, if you want a transparent terminal? So does that change anything?

**Comment by Chaoticsys101** [comment] 2020-10-18 14:52
Could you please list all commands you want me to try? 
Things about this issue:
- it only happens in vim, not nvim;
- one person told me it didn't happen in older versions;
- only happens in Windows Terminal (not in cmd.exe, alacritty.exe);

EDIT: If you mean `hi Normal ctermbg=NONE` command, I just tried it and the issue persists

**Comment by chrisbra** [comment] 2020-10-19 14:52
> EDIT: If you mean hi Normal ctermbg=NONE command, I just tried it and the issue persists

If you are using `termguicolors` you also need to reset the guibg attribute.

**Comment by Chaoticsys101** [comment] 2020-10-19 15:28
I know I forgot to write it. The issue persists.

**Comment by chrisbra** [comment] 2020-10-19 15:33
I think this is a duplicate of #2361 so closing.

**Comment by Chaoticsys101** [comment] 2020-10-19 19:13
@chrisbra yes they are rather similar. 
Alas it doesn't tell how to solve the bug, the author just then said it was working fine in his system. 
I tried all steps and it still doesn't work properly on my system so I think perhaps the issue shouldn't be closed.

**Comment by nickspoons** [comment] 2020-10-19 19:47
I don't think this is a duplicate of #2361. That issue is specifically about the `:terminal` buffer, where vim with `set termguicolors` cannot clear the `:terminal` background. It affects vim on all operating systems, I experience it in linux, where any _other_ window displays transparent backgrounds.

This issue is specific to the Windows OS, and affects ordinary buffers. I think it also affects cmd.exe, not just Windows Terminal. Here's a cmd.exe example:

```sh
"C:\Program Files\Vim\vim82\vim.exe" --clean -c "set tgc" -c "hi Normal guibg=white" -c "hi Normal guibg=NONE"
```

This opens vim to look like this:

![image](https://user-images.githubusercontent.com/5274565/96503844-55ebe880-12b0-11eb-892d-7bf6f2a75817.png)

**Comment by nickspoons** [comment] 2020-10-19 19:50
Note that in the above example, the `Normal` highlight group has its `guibg` set to `white`, then reset to `NONE`. The background of most of the window remains white, except the text and the first line of the buffer.

**Comment by Chaoticsys101** [comment] 2020-10-19 19:57
Actually in my system it doesn't affect cmd.exe with transparency, it only seems to effect Windows Terminal. Weird...

**Comment by Bakudankun** [comment] 2020-10-20 14:05
I bisected and discovered that the opaquely filled background came from [v8.1.2382](https://github.com/vim/vim/releases/tag/v8.1.2382) (commit a050b9471c66b383ed674bfd57ac78016199d972).
However, the behavior before that was not that good thing. Next image is the result of `vim.exe --clean "+set tgc"` at v8.1.2381, but you can see some part of its background is still blacked.

v8.1.2381
![v8.1.2381](https://user-images.githubusercontent.com/4504807/96591520-4a390a00-1322-11eb-8005-a35b19985595.png)

But if I went back to v8.1.0337, such black background disappeared. So I think the source of the problem slipped in at [v8.1.0338](https://github.com/vim/vim/releases/tag/v8.1.0338) (commit f6ceaf1e058c64775fd46cbdb8962f5c19ef83e0).

v8.1.0337
![v8.1.0337](https://user-images.githubusercontent.com/4504807/96595719-f250d200-1326-11eb-8560-21a9ff5fac36.png)

**Comment by Chaoticsys101** [comment] 2020-10-20 15:16
Oh nicely done! Hopefully there will be a way to fix it in the next releases!

**Comment by Hammster** [comment] 2021-03-29 01:08
If anyone want's a workaround, i created a shader to turn any wanted color transparent.

https://github.com/Hammster/windows-terminal-shaders#Transparent

![WindowsTerminal_p45yoy3gFc](https://user-images.githubusercontent.com/1093709/112775047-f4d4f780-903b-11eb-9788-94207249a1e9.png)

**Comment by dapovich** [comment] 2021-12-09 18:55
Try the command `autocmd vimenter * ++nested highlight normal ctermbg=none guibg=none` and move it after your `colorscheme` declaration

**Closed as completed** 2022-05-07 13:09 UTC
Labels: platform-windows
