### ISSUE TITLE
Cannot turn off autoindent/smartindent on xml or ant filetypes

### ISSUE THREAD

**Issue by byron-hawkins** [vim/vim#14693] opened 2024-05-01 12:55 UTC
### Steps to reproduce

In a buffer with filetype set to "ant" or "xml";

    :set noautoindent
    :set nosmartindent

Now type something with an open brace ('{'), and vim indents the line. Closing the braced expression does not cause vim to un-indent the line. Typing tags, both open and closed, causes strange indentation that is incoherent with the xml structcure. 

### Expected behaviour

No lines should ever be indented by vim while I am typing in the buffer.

### Version of Vim

VIM - Vi IMproved 9.0 (2022 Jun 28, compilé Nov 16 2023 00:00:00) Rustines incluses : 1-2105

### Environment

Fedora 38 on a plain gnome terminal.

**Comment by bfrg** [comment] 2024-05-01 14:03
That's because for `xml` files, `indentexpr` is set, see [indent/xml.vim](https://github.com/vim/vim/blob/b2e42b9be0ffa193ef32ad5a5846ef46f5cc4e8c/runtime/indent/xml.vim#L37). And `ant` filetypes [load](https://github.com/vim/vim/blob/master/runtime/indent/ant.vim) the `xml` indent script.

You need to `set indendexpr=` (i.e. to an empty string) in `~/.vim/after/ftplugin/xml.vim`.

**Comment by chrisbra** [comment] 2024-05-01 16:00
or remove `indent` from `filetype plugin indent on`

**Comment by chrisbra** [comment] 2024-05-01 16:00
not a bug, so closing

**Closed as not planned by chrisbra** 2024-05-01 16:00 UTC
