### ISSUE TITLE
Concealing a long string that spans multiple lines on a certain viewport will show line breaks.

### ISSUE THREAD

**Issue by freddieventura** [vim/vim#15681] opened 2024-09-13 12:57 UTC
### Steps to reproduce

1. Create a some conceal rules on your setup , for me for example
.vim/syntax/googleapidan.vim
```
  syn match danLinkFromParentName contained "@[-./[:alnum:]_~)]*@" conceal
  hi def link danLinkFromParentName Ignore
```

2. Create some text to reproduce the issue.
In my example main.googleapidan , I have got the following lines

```
										- & @admin-sdk-)alertcenter-)reference-)rest-)v1beta1-)AbuseDetectedVariationType@ AbuseDetectedVariationType &
```

Note is a long line , and all that string that comes in between the ats@ , it is a placeholder , a unique identifier I use in order to jump to other section in the same document , that is why is there , but I eventually want to conceal it from the user.
So the line should look like

```
										- & AbuseDetectedVariationType &
```

And it does look like that. It just add an additional line break when the viewport width is shorter than (at least) 153 characters wide.

Please check the video to see the explanation.

[bug-link](https://imgur.com/a/eT8i11m)
 

### Expected behaviour

To conceal the whole string and redraw the lines to fit in one.

### Version of Vim

VIM - Vi IMproved 9.0 (2022 Jun 28, compiled May 04 2023 10:24:44) Included patches: 1-1378, 1499

### Environment

OS : Debian Bookworm on WSL
Terminal : Windows Terminal
$TERM = tmux-256color
bash --version GNU bash, version 5.2.15(1)-release (x86_64-pc-linux-gnu)

**Comment by chrisbra** [comment] 2024-09-14 08:44
Well, I think this is a well-known limitation of concealing. It does not change how Vim wraps lines, as this always happens on the physical lines. I suppose Vim is simply wrapping the line because it is too long. You could try to use `:set nowrap`, but that has other implications of course.

**Comment by freddieventura** [comment] 2024-09-14 10:27
Appreciating the effort of the devs involved , would be nice to change the narrative from *this is a well-known limitation of concealing* to *we are adding this on our todo list for future updates* even though it may be complex and it may not suppose one of the priorities of the project.

**Comment by chrisbra** [comment] 2024-09-15 14:52
I beg to differ. Please check the list of open issues and pull requests and the todo list (`:h todo`). That is barely manageable for us here.  We need to cut down and set priorities. 
duplicate of #260

**Closed as not planned by chrisbra** 2024-09-15 14:52 UTC
Labels: bug
