### ISSUE TITLE
Larger UTF-8 characters are cut off in gvim and vim

### ISSUE THREAD

**Issue by Erotemic** [vim/vim#1438] opened 2017-02-02 22:52 UTC
I'm editing markdown file containing unicode symbols and I've noticed that certain larger unicode characters are cut off. Specifically the characters ⋃ (NARY-Union U+22C3) and ⋂ (NARY-Intersection U+22C2). 

The line that I noticed this on was:  `(⋃_i m_i ∩ (⋂_i (m_i ∩ n_i))`, but it has nothing to do with the makeup of the line, its just the larger NARY characters. 

I've tested rendering this line on gvim and vim, and what happens is the right side of the characters is slightly cut off by the underscore. I've also noticed that if I select the character with the cursor, the whole character appears but slightly cuts of the start of the next character. 

I wasn't originally sure that this was a gvim issue. I've tested this with several fonts Ubuntu Mono, Inconsolata, Free Mono, DejaVu Sans Mono, and Monospace. They all had the same result. I also tested this line in the terminal vim and got the same result. (I also checked pico and nano, which also had the same result).

However, I then tried gedit, and the line rendered nicely. It also renders nicely on my browser, so this makes me think that there is something vim could do to render these characters appropriately. 

I'm working on Ubuntu 14.04 with a version of vim that I compiled from source. My `vim --version` info is
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Feb  2 2017 17:50:35)
Included patches: 1-295
Compiled by joncrall@hyrule
Huge version with GTK2 GUI.  Features included (+) or not (-):
+acl             +file_in_path    +mouse_sgr       +tag_old_static
+arabic          +find_in_path    -mouse_sysmouse  -tag_any_white
+autocmd         +float           +mouse_urxvt     -tcl
+balloon_eval    +folding         +mouse_xterm     +termguicolors
+browse          -footer          +multi_byte      +terminfo
++builtin_terms  +fork()          +multi_lang      +termresponse
+byte_offset     +gettext         -mzscheme        +textobjects
+channel         -hangul_input    +netbeans_intg   +timers
+cindent         +iconv           +num64           +title
+clientserver    +insert_expand   +packages        +toolbar
+clipboard       +job             +path_extra      +user_commands
+cmdline_compl   +jumplist        -perl            +vertsplit
+cmdline_hist    +keymap          +persistent_undo +virtualedit
+cmdline_info    +lambda          +postscript      +visual
+comments        +langmap         +printer         +visualextra
+conceal         +libcall         +profile         +viminfo
+cryptv          +linebreak       +python          +vreplace
+cscope          +lispindent      -python3         +wildignore
+cursorbind      +listcmds        +quickfix        +wildmenu
+cursorshape     +localmap        +reltime         +windows
+dialog_con_gui  -lua             +rightleft       +writebackup
+diff            +menu            -ruby            +X11
+digraphs        +mksession       +scrollbind      -xfontset
+dnd             +modify_fname    +signs           +xim
-ebcdic          +mouse           +smartindent     -xpm
+emacs_tags      +mouseshape      +startuptime     +xsmp_interact
+eval            +mouse_dec       +statusline      +xterm_clipboard
+ex_extra        -mouse_gpm       -sun_workshop    -xterm_save
+extra_search    -mouse_jsbterm   +syntax          
+farsi           +mouse_netterm   +tag_binary      
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/pango-1.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/freetype2 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/libpng12 -I/usr/include/harfbuzz     -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -L/usr/local/lib -Wl,--as-needed -o vim-8   -lgtk-x11-2.0 -lgdk-x11-2.0 -latk-1.0 -lgio-2.0 -lpangoft2-1.0 -lpangocairo-1.0 -lgdk_pixbuf-2.0 -lcairo -lpango-1.0 -lfontconfig -lgobject-2.0 -lglib-2.0 -lfreetype   -lSM -lICE -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lnsl   -ldl    -L/usr/lib/python2.7/config-x86_64-linux-gnu -lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions        
```

**Comment by nuko8** [comment] 2017-02-03 01:56
I'm afraid this is more of an issue of "font substitution" than Vim's, as its implementation is left to rendering engines.

Also, whether such font substitutions give a satisfactory result or not depends on various parameters in addition to the quality of the rendering engine itself: fonts available for substitution, priority order among them in terms of size, style, spacing, locale...all of which are left to users, or OS/software of users' choice.

As for me, iTerm2 and Terminal have no problem at all and give the same good result.  Both `urxvt` and `st` don't have the problem, either, but there's a visible difference in substitution between them.  Sadly, `xterm` cannot display any of the n-ary math operators for me.

As such, I think a practical solution is to find and install a monospace font having both U+22C2 and U+22C3 glyphs which is also suitable for substitution, or compatible in size with Ubuntu Mono.

**Comment by nuko8** [comment] 2017-02-03 02:11
Oh, I forgot to talk about gvim.  GTK2 gvim also works fine for me with both `fontconfig` and `coretext` pango backends.

**Comment by Erotemic** [comment] 2017-02-03 14:22
Here are images of the 3 ways that the characters render with Ubuntu Mono for me: 

The first shows the highlighted union character which is overlapping with the underscore 
![screenshot from 2017-02-03 09 05 10](https://cloud.githubusercontent.com/assets/3186211/22594212/17c25752-e9f0-11e6-99e9-e3d6946e3aa7.png)
The second shows what happens if I move my cursor right, the union operator stays on top of the underscore
![screenshot from 2017-02-03 09 05 15](https://cloud.githubusercontent.com/assets/3186211/22594214/17c9ada4-e9f0-11e6-9d51-9e5cf4cd3e46.png)
The last image shows what happens by default: the underscore cuts off the left part of the union.
![screenshot from 2017-02-03 09 05 24](https://cloud.githubusercontent.com/assets/3186211/22594213/17c88442-e9f0-11e6-9e93-88085e59707b.png)

Weird that it works on GTK2 for you. As you said, there must be some configuration difference between our systems. If you were able to get a good result, I shouldn't I be able to change my system settings and get the same good result?

I'm not familiar with the details of how text editors render fonts.  How can I tell which rendering backend I'm using? I am using gnome3 as my desktop environment, is it possible that the core issue lies with that?

**Comment by nuko8** [comment] 2017-02-03 16:12
Hmm, it looks you are missing my point...

OK, let me explain the point in another way.

For that, I need you help.  Please follow the instruction below.

On the command line, open an xterm with
```
$ xterm -fa 'Ubuntu Mono'
```
and open vim there.

Copy and paste the example in the initial post into the vim you just opened:

(⋃_i m_i ∩ (⋂_i (m_i ∩ n_i))

Then, what do you have on the vim?

**Comment by Erotemic** [comment] 2017-02-03 20:26
I do understand the general point that this is not a vim issue. I ended searching for a font with the NARY characters and found that FreeMono seemed to work well. However, I'm still confused about where the problem lies.  If you are willing to explain, I'd be very gracious. 

Following your instructions I saw this: 
![screenshot from 2017-02-03 14 34 38](https://cloud.githubusercontent.com/assets/3186211/22605498/1722a314-ea1e-11e6-9603-575f525e8dd3.png)

-----
I've attempted to research the issues a bit on my own, but this seems to be a complex subject. Here is my best effort to explain what I currently do and don't understand. 

In the exercise you had me go through none of the Unicode glyphs are rendering. I would guess that its because the font does not define them, so it tries to fallback on another font. In this instance it seems to fail. I would further guess that most fonts don't define a glyph for most unicode characters, so when they were being rendered on my screen earlier the glyphs I saw were substituted in from a different font that had an incompatible spacing with my current font. I don't understand why xterm couldn't find any replacement for the character (maybe it just doesn't try, or is it that it doesn't know where to look?). 

I know that there are multiple compoments to rendering fonts, and today I've learned what some of those components are, but I still don't understand where each component lies and how they relate to each other. I've known about font files, and windows systems (gtk2/gnome/athena), and I vaguely know about FreeType, but today is the first I've heard about rendering backends (fontconfig, coretext, pango). Are they system-wide, or are they hard compiled directly into vim/chrome/geddit, or can I dynamically change backends within a vim instance? 

The other thing I don't understand is how you were able to get good results using the same font. Am I correct that your rending backend must be substituting in a different font than my rendering backend is? If so, how do I determine which rendering back I'm using? And how would I configure it to do something more sensible in this case? Or maybe, how would I get it to render similar to the way chrome is rendering the monospaced fonts on github? How would I get gvim to fallback in the same way that chrome or geddit does? Is that even possible?

**Comment by ericpruitt** [comment] 2017-02-03 20:37
I ran into a [similar issue](https://groups.google.com/forum/#!topic/vim_dev/QtTkbmkLJ7E) which was caused by differing opinions by certain parts of my graphical stack about the width of certain characters. What I ultimately ended up doing was creating a patch for Vim to use the Unicode 8 character property tables instead of the more recent Unicode 9 properties. This fixed the problem I observed with the lightning character, but I still have problems using the union & intersection symbols as you do here. You could try modifying src/mbyte.c and adding the offending codepoints to the definition of [`static struct interval doublewidth`](https://github.com/vim/vim/blob/master/src/mbyte.c#L1410). I'm not sure if there's a better / more elegant approach to resolving this.

**Comment by nuko8** [comment] 2017-02-04 05:52
@Erotemic 

> I do understand the general point that this is not a vim issue.

Thank you for the confirmation.

> However, I'm still confused about where the problem lies. If you are willing to explain, I'd be very gracious.

Since this is the issue tracker for Vim, people are not encouraged to use it for other purposes.  If your questions were short and simple, people might allow me to answer to them, but the number of the questions are too many and hence my possible answer will be too long to fit here. 

So, this is the best I can do for you: Don''t try to configure the renderer or modify Vim.  Read through`fonts-conf(5)`. Then, try to find and exclude the offending font file with `~/.config/fontconfig/fonts.conf`.  If you are lucky enough, the renderer will just pick up the font used with the browser for substitution.

**Comment by ericpruitt** [comment] 2017-02-04 06:25
@nuko8 

> So, this is the best I can do for you: Don''t try to configure the renderer or modify Vim. Read throughfonts-conf(5). Then, try to find and exclude the offending font file with ~/.config/fontconfig/fonts.conf. If you are lucky enough, the renderer will just pick up the font used with the browser for substitution.

I don't think _fonts-conf(5)_ is a viable solution for this problem at least with the terminal version of Vim. Please correct me if I'm wrong, but I think most terminal programs get their character dimension information from _wcwidth(3)_ or internal Unicode property tables, so if curses, the terminal emulator (or potentially emulators when using things like tmux or screen) and Vim do not agree about the width of characters, something will be misaligned.

On my system, I typically have the following components interacting with one another, and I compile them all from source which means programs that use internal tables may be out of sync with one another:

- [st](http://st.suckless.org/), which uses Xft (and in turn fonts.conf), for fallback fonts but [_wcwidth(3)_ to determine how many columns the character should span](http://git.suckless.org/st/tree/st.c?id=c63a87cd936c1eeef14c4c21572e5b782d3df4bc#n3012).
 - Vim has a [table in src/mbyte.c](https://github.com/vim/vim/blob/master/src/mbyte.c)
- tmux can use [wcwidth(3) or utf8proc](https://github.com/tmux/tmux/blob/044999ce6d852e91d172a45f671be357bd9057f7/utf8.c#L112). When using utf8proc, [you may be using yet another internal table of character properties](https://github.com/JuliaLang/utf8proc/blob/master/utf8proc_data.c).
- ncurses also has a [re-implementation wcwidth(3) with hard-coded data](https://github.com/ThomasDickey/ncurses-snapshots/blob/master/ncurses/wcwidth.h).

I've spent a lot of time messing with fonts.conf for other reasons, and I don't recall seeing anything that would resolve these issues. If you're aware of some feature in particular that could, I'm all ears.

**Comment by ericpruitt** [comment] 2017-02-04 06:29
I also forgot to add -- when I last looked into this, there was no simple way to ensure that fonts.conf always picks a certain font for a particular glyph, and depending on how the X11 programs you're using query fonts.conf, they may end up using different fallbacks despite sharing the same source of truth.

**Comment by nuko8** [comment] 2017-02-04 07:23
> there was no simple way to ensure that fonts.conf always picks a certain font for a particular glyph

I wrote:  try to find and **exclude the offending font file** with ~/.config/fontconfig/fonts.conf

Don't confuse.

**Closed as completed** 2017-02-06 17:30 UTC
