### ISSUE TITLE
[RFC] unset environment variable

### ISSUE THREAD

**Issue by mattn** [vim/vim#2854] opened 2018-05-01 05:48 UTC
In current implementation, vim doesn't have a way to unset environment variable. Most of programs works well with empty value as same as no-set variable. But for example, TZ variable

```
$ TZ=EST date
Tue May  1 00:45:54 EST 2018
$ TZ= date
Tue May  1 05:45:57 UTC 2018
$ date
Tue May  1 14:46:01 JST 2018
$
```

If vim doesn't have a way to unset environemnt variable, we can't reset `TZ`. Let's add a way to unset environment variables with `unlet $FOO`?

**Comment by mattn** [comment] 2018-05-01 05:54
One another example.
```
let $TZ='EST'
echo localtime() " This is EST
let $TZ=''
echo localtime() " This is UTC
```
Once we set TZ, we can not get result of localtime in default time zone since ever.

**Comment by mattn** [comment] 2018-05-01 06:07
This is dup of https://github.com/vim/vim/issues/1116 but no progresses.

**Comment by chrisbra** [comment] 2018-05-01 06:48
closing as duplicate of #1116

**Closed as completed by chrisbra** 2018-05-01 06:48 UTC
