### ISSUE TITLE
Calling filetype twice gives an error of already defined function TestFiletypeFuncs

### ISSUE THREAD

**Issue by Grueslayer** [vim/vim#9890] opened 2022-03-04 06:48 UTC
If you are calling `filetype` twice in your `.vimrc like

```vim
filetype off

filetype plugin indent on
```

you'll receive an error of

```
Error detected while processing C:\Users\userxxxx\_vimrc[659]..C:\Progr
am Files (x86)\Vim\vim82\filetype.vim:

line 2530:

E122: Function TestFiletypeFuncs already exists, add ! to replace it
```

using Patch 8.2.4500

```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Mar  3 2022 20:48:45)
MS-Windows 64-bit GUI/console version with OLE support
Included patches: 1-4500
Compiled by knurr@BITLOGIC
Huge version with GUI.  Features included (+) or not (-):
+acl                +clipboard          +directx            +gettext/dyn        +listcmds           +ole                +rightleft          -tag_old_static     +vartabs            -xfontset
+arabic             +cmdline_compl      -dnd                -hangul_input       +localmap           +packages           +ruby/dyn           -tag_any_white      +vertsplit          -xim
+autocmd            +cmdline_hist       -ebcdic             +iconv/dyn          +lua/dyn            +path_extra         +scrollbind         +tcl/dyn            +vim9script         +xpm_w32
+autochdir          +cmdline_info       +emacs_tags         +insert_expand      +menu               +perl/dyn           +signs              +termguicolors      +viminfo            -xterm_save
+autoservername     +comments           +eval               +ipv6               +mksession          +persistent_undo    +smartindent        +terminal           +virtualedit        
+balloon_eval       +conceal            +ex_extra           +job                +modify_fname       +popupwin           +sodium/dyn         -termresponse       +visual             
+balloon_eval_term  +cryptv             +extra_search       +jumplist           +mouse              -postscript         +sound              +textobjects        +visualextra        
+browse             +cscope             -farsi              +keymap             +mouseshape         +printer            +spell              +textprop           +vreplace           
++builtin_terms     +cursorbind         +file_in_path       +lambda             +multi_byte_ime/dyn +profile            +startuptime        -tgetent            +vtp                
+byte_offset        +cursorshape        +find_in_path       +langmap            +multi_lang         +python/dyn         +statusline         +timers             +wildignore         
+channel            +dialog_con_gui     +float              +libcall            +mzscheme/dyn       +python3/dyn        -sun_workshop       +title              +wildmenu           
+cindent            +diff               +folding            +linebreak          +netbeans_intg      +quickfix           +syntax             +toolbar            +windows            
+clientserver       +digraphs           -footer             +lispindent         +num64              +reltime            +tag_binary         +user_commands      +writebackup        
   system vimrc file: "$VIM\vimrc"
     user vimrc file: "$HOME\_vimrc"
 2nd user vimrc file: "$HOME\vimfiles\vimrc"
 3rd user vimrc file: "$VIM\_vimrc"
      user exrc file: "$HOME\_exrc"
  2nd user exrc file: "$VIM\_exrc"
  system gvimrc file: "$VIM\gvimrc"
    user gvimrc file: "$HOME\_gvimrc"
2nd user gvimrc file: "$HOME\vimfiles\gvimrc"
3rd user gvimrc file: "$VIM\_gvimrc"
       defaults file: "$VIMRUNTIME\defaults.vim"
    system menu file: "$VIMRUNTIME\menu.vim"
Compilation: cl -c /W3 /GF /nologo -I. -Iproto -DHAVE_PATHDEF -DWIN32  -DFEAT_CSCOPE -DFEAT_TERMINAL -DFEAT_SOUND -DFEAT_NETBEANS_INTG -DFEAT_JOB_CHANNEL -DFEAT_IPV6   -DFEAT_XPM_W32 -DHAVE_SODIUM -DDYNAMIC_SODIUM /I "..\..\libs\libsodium-1.0.18\include" -DWINVER=0x0501 -D_WIN32_WINNT=0x0501 /source-charset:utf-8 /MP -DHAVE_STDINT_H /Ox /GL -DNDEBUG /MD /D_CRT_SECURE_NO_DEPRECATE /D_CRT_NONSTDC_NO_DEPRECATE -DVIMDLL -DFEAT_OLE -DFEAT_MBYTE_IME -DDYNAMIC_IME -DFEAT_GUI_MSWIN -DFEAT_DIRECTX -DDYNAMIC_DIRECTX -DFEAT_DIRECTX_COLOR_EMOJI -DDYNAMIC_ICONV -DDYNAMIC_GETTEXT -DFEAT_TCL -DDYNAMIC_TCL -DDYNAMIC_TCL_DLL=\"tcl86t.dll\" -DDYNAMIC_TCL_VER=\"8.6\" -DFEAT_LUA -DDYNAMIC_LUA -DDYNAMIC_LUA_DLL=\"lua54.dll\" -DFEAT_PYTHON -DDYNAMIC_PYTHON -DDYNAMIC_PYTHON_DLL=\"python27.dll\" -DFEAT_PYTHON3 -DDYNAMIC_PYTHON3 -DDYNAMIC_PYTHON3_DLL=\"python310.dll\" -DFEAT_MZSCHEME -I "..\..\libs\racket-8.3\include" -DDYNAMIC_MZSCHEME -DDYNAMIC_MZSCH_DLL=\"libracketxxxxxxx.dll\" -DDYNAMIC_MZGC_DLL=\"libmzgcxxxxxxx.dll\" -DFEAT_PERL -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS -DDYNAMIC_PERL -DDYNAMIC_PERL_DLL=\"perl532.dll\" -DFEAT_RUBY -DDYNAMIC_RUBY -DDYNAMIC_RUBY_DLL=\"x64-ucrt-ruby310.dll\" -DRUBY_VERSION=31 -DFEAT_HUGE /Fd.\ObjDXOULYHTRZVAMD64/ /Zi
Linking: link /nologo /opt:ref /LTCG:STATUS /HIGHENTROPYVA:NO oldnames.lib kernel32.lib advapi32.lib shell32.lib gdi32.lib  comdlg32.lib ole32.lib netapi32.lib uuid.lib user32.lib  /machine:AMD64 version.lib  winspool.lib comctl32.lib  msvcrt.lib oleaut32.lib  /nodefaultlib:lua54.lib  /STACK:8388608  /nodefaultlib:python27.lib /nodefaultlib:python310.lib   "C:\tcl-64\lib\tclstub86.lib" winmm.lib WSock32.lib Ws2_32.lib .\xpm\x64\lib-vc14\libXpm.lib /PDB:vim64.pdb -debug
```

**Comment by brammool** [comment] 2022-03-04 13:00
> If you are calling `filetype` twice in your `.vimrc like
> 
> ```vim
> filetype off
> 
> filetype plugin indent on
> ```
> 
> you'll receive an error of
> 
> ```
> Error detected while processing C:\Users\userxxxx\_vimrc[659]..C:\Progr
> am Files (x86)\Vim\vim82\filetype.vim:
> 
> line 2530:
> 
> E122: Function TestFiletypeFuncs already exists, add ! to replace it
> ```
> 
> using Patch 8.2.4500

I cannot reproduce this.  Perhaps you have two "filetype.vim" files in
your 'runtimepath'?

To see where the function was defined:
	:verbose func TestFiletypeFuncs

-- 
hundred-and-one symptoms of being an internet addict:
159. You get excited whenever discussing your hard drive.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by Grueslayer** [comment] 2022-03-04 13:06
Hi Bram,

you are right:

```
   function TestFiletypeFuncs()
	Last set from ~\vimfiles\bundle\vim-polyglot\extras\filetype.vim line 2509
1    let output = ''↲
2    for f in a:testlist↲
3      try↲
4        exe f↲
5      catch↲
6        let output = output . "\n" . f . ": " . v:exception↲
7      endtry↲
8    endfor↲
9    return output↲
   endfunction
```

That's a very commonly used plugin.

**Comment by brammool** [comment] 2022-03-04 14:14
Looks like a copy.  That plugin should check if the function already exists, and skip it if it does exist.
Or use a different name.

I guess previously "function!" was used.  But the "!" is now not needed when loading a script file a second time.  And it covers up mistakes like you just noticed, that a function defined elsewhere is overwritten.

**Comment by chrisbra** [comment] 2022-03-06 14:11
cc @sheerun

Closing here.

**Closed as completed by chrisbra** 2022-03-06 14:11 UTC
