### ISSUE TITLE
Odd behavior with v:register, visual selection and macros

### ISSUE THREAD

**Issue by glacambre** [vim/vim#3021] opened 2018-06-16 17:58 UTC
I can reproduce this bug (perhaps not a bug?) on master (bc5020aa4d7ef4aea88395eff858f74fc881eab9 at the moment).
I'm having a hard time understanding what happens so here are the instructions to reproduce what I'm seeing:
Use this file
```ada
procedure Hello_World ()
```
Start vim like this:
```
vim -u NORC -c 'vnoremap <expr>y "my\"" . v:register . "y`y"' tmp.adb
```
Press the following keystrokes:
`qqwywO<Esc>pyyPv$hr-yyjpjq@q`
Basically what this does is:
- Start recording macro `q`
- Move to the beginning of Hello_World
- Yank Hello_World
- Open a new line over the current line
- Paste Hello_World
- Yank the whole line
- Paste it over the current line
- Select the whole line except for the last character
- Replace it with `-`
- Copy the whole line
- Go to the line below
- Paste the selected line below the current one
- Go the the line below
- Stop recording the macro
- Replay the macro

At the end of this sequence, I expect my file to look like this:
```adb
------------
Hello_World 
------------
------------
Hello_World 
------------
procedure Hello_World ()
```
But it looks like this:
```adb
------------
Hello_World 
------------
------------
------------
Hello_World 
Hello_World 
procedure Hello_World ()
```

At first I thought this was normal because of interactions between the macro register and the use of `v:register` in my remapping but I don't understand why my file ends up looking like it does, even if the yanking/pasting is indeed happening to/from my unnamed/q register.

**Comment by lacygoill** [comment] 2020-06-06 04:19
> Press the following keystrokes:
>
>     qqwywO<Esc>pyyPv$hr-yyjpjq@q

Press `Escape` right after replacing the visual selection with hyphens:

    qqwywO<Esc>pyyPv$hr-<Esc>yyjpjq@q
                        ^^^^^

Here's a shell command reproducing your issue:

    vim -Nu NONE -S <(cat <<'EOF'
        let @q = "^wywO\epyyPv$hr-yyjpj"
        xnoremap <expr> y 'my"' . v:register . 'y`y'
        pu!='procedure Hello_World ()'
        au VimEnter * call feedkeys('@q')
    EOF
    )

Expected result:

    ------------
    Hello_World
    ------------
    procedure Hello_World ()

Actual result:

    ------------
    ------------
    Hello_World
    Hello_World
    procedure Hello_World ()

Here's the same shell command, but with an extra escape right after replacing the visual selection:

    vim -Nu NONE -S <(cat <<'EOF'
        let @q = "^wywO\epyyPv$hr-\eyyjpj"
        "                         ^^
        xnoremap <expr> y 'my"' . v:register . 'y`y'
        pu!='procedure Hello_World ()'
        au VimEnter * call feedkeys('@q')
    EOF
    )

This time, you should get the expected result.

---


> At first I thought this was normal because of interactions between the macro register and the use of v:register in my remapping

No, `v:register` doesn't cause any issue.

> but I don't understand why my file ends up looking like it does, even if the yanking/pasting is indeed happening to/from my unnamed/q register.

The issue is that your mapping is used.

During the recording, after *you* execute `r-` in visual mode, when *you* press `y`, you're back into normal mode; so your visual `y` mapping is *not* triggered.

But during the replay, after *Vim* executes `r-` in visual mode, when *it* presses `y`, it's still in visual mode (presumably because it types much faster than you); this time, your visual mapping *is* triggered.

As a result, in your sequence, the `y` right after `r-`:

    wywO<Esc>pyyPv$hr-yyjpj
                      ^

is replaced with the rhs of your mapping, which is ``my""y`y``:

    wywO<Esc>pyyPv$hr-my""y`yyjpj
                      ^^^^^^^

This completely changes the meaning of the remaining commands.  During the recording, `yyj` yanks the current line and moves one line down.  During the replay, ``my""y`y`` does this:

   - `my` sets the mark `y` on the cursor position
   - `""y` yanks the selection in the unnamed register
   - `` `y`` jumps to the mark `y`

Then, `yj` yanks the current line and the next one.

You can prevent that by pressing `Escape` – during the recording – whenever you've replaced a visual selection, so that you're sure to be in normal mode before the remaining commands are processed.

---

I don't know whether this is a bug; I didn't find anything at `:h v_r` which explains that Vim is still in visual mode for a brief amount of time after a replace command has been executed.  But maybe I missed something.

Btw, here's a simpler MWE:

    vim -Nu NONE -S <(cat <<'EOF'
        let @q = 'Vr-x'
        xno <expr> x Func()
        fu Func()
            echom 'should not be triggered'
            return ''
        endfu
        pu!='some text'
        au VimEnter * call feedkeys('@q')
    EOF
    )

If you run `:mess`, you should see that the message `should not be triggered` has been logged, meaning that the visual `x` mapping was triggered.

One possible fix would be for Vim to insert a `<Nop>` whenever a replace command has been executed from visual mode during a recording.  Similar to what is already done since [8.1.1003](https://github.com/vim/vim/releases/tag/v8.1.1003) to avoid [this kind of other issue](https://github.com/vim/vim/issues/4068).

Although, it would not fix other cases where keys are typed non-interactively; e.g. via the rhs of a mapping, `feedkeys()`, or `:norm`.

**Comment by lacygoill** [comment] 2020-06-06 04:27
Assuming my analysis is correct (maybe it's not), I think the best fix would be for Vim to quit visual mode immediately after a replace command has been executed, and not shortly after; or, if that's not possible, then stop processing the input until visual mode has been quit.

**Comment by lacygoill** [comment] 2020-06-06 04:35
> One possible fix would be for Vim to insert a `<Nop>` whenever a replace command has been executed from visual mode during a recording.  Similar to what is already done since [8.1.1003](https://github.com/vim/vim/releases/tag/v8.1.1003) to avoid [this kind of other issue](https://github.com/vim/vim/issues/4068).

I meant `<C-\><C-n>`, not `<Nop>`.

**Comment by glacambre** [comment] 2020-06-06 04:55
Wow, thanks a lot for investigating this 2 years old bug! That's an interesting discovery. Do you know why vim stays in visual mode after `r-`?

**Comment by lacygoill** [comment] 2020-06-06 05:04
No, I don't know.  I suspect it's due to a detail of implementation, but maybe it's documented somewhere...

**Comment by lacygoill** [comment] 2020-06-06 06:27
#3678 is a similar issue; this one does not affect visual mode, but operator-pending mode.

---

> I meant `<C-\><C-n>`, not `<Nop>`.

Considering that a no-op (i.e. `C-r = "" CR`) fixes the issue there, maybe a `<Nop>` could work here too...

**Comment by andymass** [comment] 2020-06-06 11:54
Does https://github.com/vim/vim/issues/5294 / PR https://github.com/vim/vim/pull/5305 relate in any way?

Patch:
```diff
--- a/src/normal.c
+++ b/src/normal.c
@@ -1190,6 +1190,11 @@ normal_end:

     msg_nowait = FALSE;

+#ifdef FEAT_EVAL
+    if (finish_op)
+       set_reg_var(0);
+#endif
+
     // Reset finish_op, in case it was set
 #ifdef CURSOR_SHAPE
     c = finish_op;
```

**Comment by brammool** [comment] 2020-06-06 13:52
This should use adjust_clip_reg().  Is there a test for what this fixes?

**Comment by lacygoill** [comment] 2020-06-06 14:26
> Does #5294 / PR #5305 relate in any way?

Thank you for the patch; I've just applied it to test whether it would fix the current issue, but unfortunately it does not.

The issue here is that Vim remains in visual mode for a short time after a replace command has been executed from visual mode.  I guess this amount of time is too short to be noticed during a recording; but during a replay, since Vim can type much faster than the user, this delay can matter.  Here, it matters because the user has a visual mode mapping which is – unexpectedly – used after the replace command has been executed.

**Comment by chrisbra** [comment] 2023-08-12 08:00
closing for now, seems kind of duplicate to #3678 which I keep open for the other sub-problem.

**Closed as completed by chrisbra** 2023-08-12 08:00 UTC
