### ISSUE TITLE
:! no longer shows the shell output

### ISSUE THREAD

**Issue by andrewshadura** [vim/vim#11843] opened 2023-01-18 10:26 UTC
### Steps to reproduce

1. Run `:!`
2. Nothing happens, no visual changes

### Expected behaviour

1. Run `:!`
2. Shell output is shown, nothing else happens, upon a keypress the editor is shown again

### Workaround

Using `:!:` approximates the original behaviour.

### Version of Vim

9.0.813

### Environment

OS: Debian testing
Terminal: GNOME Terminal
`TERM`: `xterm-256color`

**Comment by chrisbra** [comment] 2023-01-18 10:31
Duplicate of #11409 should have been fixed by #11420 which was merged in as [patch 9.0.0815](https://github.com/vim/vim/commit/9c50eeb40117413bf59a9da904c8d0921ed0a6e6)  

So please upgrade

**Closed as completed by chrisbra** 2023-01-18 10:31 UTC
Labels: bug
