### ISSUE TITLE
'statusline': two "%{}" in a row result in consuming a space

### ISSUE THREAD

**Issue by lkintact** [vim/vim#6237] opened 2020-06-11 08:45 UTC
1. Run `gvim --clean --cmd "set encoding=utf-8" --cmd "set laststatus=2`
2. Execute `set statusline=%{&enc}%{'\ test'}`.

The statusline changes to `utf-8test`, while it should be `utf-8 test`, i.e. with a space before `test`. This only seems to happen when the expression in the first %{} (`&enc` in our case) evaluates to a string: for example `set statusline=%{&list}%{'\ test'}` gives `0 test` as expected.

Vim: 8.2.940 (https://github.com/vim/vim-win32-installer/releases/download/v8.2.0940/gvim_8.2.0940_x86_signed.zip)
OS: Windows 10 Home 1803
Terminal: GUI.

**Comment by chrisbra** [comment] 2020-06-11 08:50
I think this is a duplicate of #1431 and #3898

**Comment by chrisbra** [comment] 2020-06-14 17:00
closing this as a duplicate

**Closed as completed by chrisbra** 2020-06-14 17:00 UTC
Labels: duplicate
