### ISSUE TITLE
gVim Can't Show All Unicode Fonts!

### ISSUE THREAD

**Issue by in2Rafi** [vim/vim#5922] opened 2020-04-13 07:58 UTC
**Describe the bug**
Vim is not showing some Unicode characters while notepad, notepad++, firefox shows the character. You can see some rectangle boxes instead of symbols... https://imgur.com/a/Ni9b88W

let g:airline_symbols.linenr = '␊'
let g:airline_symbols.linenr = '␤'
let g:airline_symbols.branch = '⎇'
let g:airline_symbols.spell = 'Ꞩ'

But if you look at my notepad... https://imgur.com/zaJKoTM. All the characters are showing. 
Firefox... https://imgur.com/hkQ5BJL

I have used same font Iosevka_NF for Notepad, gVim & Firefox.

I have tried all powerline fonts. DejaVu Sans Mono for Powerline, Source Code Pro for Powerline, Jet brains mono blah blah blah almost 34 different fonts. But the result is same. When I see in Notepad or Notepad++ I see the symbols. But gVim can't show the symbols. So I think this problem is a bug of gVim.

**Screenshots**
https://imgur.com/a/Ni9b88W
https://imgur.com/zaJKoTM
https://imgur.com/hkQ5BJL

**Environment (please complete the following information):**
 - Vim version : 8.2
 - OS: Windows 10, Version 1909. OS build - 18363.418
 - Terminal: GUI. gVim
- .Vimrc file: https://pastebin.com/21Mvw2PG

**Comment by k-takata** [comment] 2020-04-13 08:15
If the selected font doesn't have glyphs for those symbols, they won't be shown.
And if you enable DirectWrite (see `:help 'rop'`), some symbols might be shown. (Because DirectWrite falls back to other fonts.)

**Comment by tonymec** [comment] 2020-04-13 08:43
`:set gfn=*` will give you a menu with all the fonts which declare themselves as monospaced. That menu should have a line with sample text, where you can type or paste some text of your choice (e.g. some text including the problematic characters, to see how this font displays them). Not every font has every character, if a character is missing in the chosen font it will probably be displayed as some placeholder glyph, often an empty rectangle.

ISTR that the Courier New font, though not very beautiful, has a good set of glyphs for many languages. Lucida Console is another possibility. Otherwise, trial and error is the way to go.

If you can find a font which is _almost_ what you want, but not quite, come back here and tell us to which value you set the `'guifont'` option.

Best regards,
Tony.

**Comment by in2Rafi** [comment] 2020-04-13 15:32
> 
> 
> If you can find a font which is _almost_ what you want, but not quite, come back here and tell us to which value you set the `'guifont'` option.
> 
> Best regards,
> Tony.

I have found Iosevka_NF is the best font amongh 34 Powerline fonts. It is best because only Iosevka_NF can show almost all glyphs. Only 4 glyphs are missing. But when I test Iosevka_NF using notepad I see it can show all the glyphs including the 4 missing glyphs in gVim.

Iosevka_NF on gVim - https://imgur.com/TtUklHp
Iosevka_NF on notepad - https://imgur.com/bsET8L6

This is my .vimrc file - https://pastebin.com/WtvrN4Cz

**Comment by in2Rafi** [comment] 2020-04-13 15:38
> 
> 
> If the selected font doesn't have glyphs for those symbols, they won't be shown.
> And if you enable DirectWrite (see `:help 'rop'`), some symbols might be shown. (Because DirectWrite falls back to other fonts.)

How can I enable direct write on gVim 8.2?

**Comment by chrisbra** [comment] 2020-04-13 16:05
> How can I enable direct write on gVim 8.2?

It was referenced in the paragraph you quoted: `:h 'rop'`

**Comment by in2Rafi** [comment] 2020-04-13 17:20
> 
> 
> > How can I enable direct write on gVim 8.2?
> 
> It was referenced in the paragraph you quoted: `:h 'rop'`

I am new gVim user. So a bit explanation needed.

**Comment by tonymec** [comment] 2020-04-13 22:14
> > > How can I enable direct write on gVim 8.2?
> > 
> > 
> > It was referenced in the paragraph you quoted: `:h 'rop'`
> 
> I am new gVim user. So a bit explanation needed.

Type `:h 'rop'` in Normal mode in Vim, followed by `<Enter>`. You'll see there not only how to enable DirectX fonts in gvim, but how to customize them. On my system, and with my choice of 'guifont', that detailed explanation takes about two screen heights. You may have to use trial and error to find the exact `'renderoptions'` setting which suits you best, so Christian and I cannot do it for you.

You say that losevka_NF is the best font you found, but what I asked was the exact 'guifont' setting used to set it: when you type
```vim
:set gfn?
```
followed by `<Enter>` in Normal mode, what exactly is the answer? I expect something like
```
  guifont=losevka_NF:h11:cANSI
```
but maybe not exactly that. I'm still interested in knowing the exact value. Now you have two things to try: First try setting and possibly customizing DirectX according to the detailed online help for the `'rop'` option. If it doesn't work, leave DirectX on but replace the :c parameter at the end of your `'guifont'` option by `:cDEFAULT`. You can do that once to try it by typing `:set gfn=<Tab>` where `<Tab>` means "hit the Tab key", then editing the command-line before hitting `<Enter>`, but for permanent use you should write it into your vimrc.

**Comment by chrisbra** [comment] 2020-04-14 07:03
Sorry, but I am going to close this issue. Please ask user questions on the vim_use mailing list or use vi.stackexchange.com. This here is a bug tracker for problems with Vim. We cannot provide individual help here. 

Once you have figured this out and can provide a reproducible example (start from `vim --clean`, mention all commands that you enter, what you expect and what happened), you can create a new issue (or comment here and I can re-open). Thanks for understanding.

**Closed as completed by chrisbra** 2020-04-14 07:03 UTC
Labels: platform-windows
