### ISSUE TITLE
Cannot paste PowerShell code correctly

### ISSUE THREAD

**Issue by Liturgist** [vim/vim#3567] opened 2018-10-26 21:55 UTC
The following lines of PowerShell source code will not paste correctly into Vim for Windows version 8.0.586. This has been reproduced using "vim -N -u NONE". The problem does not occur on Vim for Cygwin version 8.0.1567.
```
$year = $date.year
$date = GET-DATE
$datemonth=$date.month
$month = (Get-Culture).DateTimeFormat.GetMonthName($datemonth)
$url = 'https://health.mil/Reference-Center/Technical-Documents?query=DMIS'

$links = ((Invoke-WebRequest –Uri $url).Links |
    Where-Object {
        ($_.innerHTML -like "*DMIS ID Monthly*") -and
        ($_.innerHTML -notlike "*Change*") -and
        ($_.innerHTML -like "*$month*")
    }).href

$links
```

This is how it looks after pasted in.

```
  1 $year = $date.year
  2 $date = GET-DATE
  3 $datemonth=$date.month
  4 $month = (Get-Culture).DateTimeFormat.GetMonthName($datemonth)
  5 $url = 'https://health.mil/Reference-Center/Technical-Documents?query=DMIS'
  6
  7 nks |
  8     Where-Object {
  9         ($_.innerHTML -like "*DMIS ID Monthly*") -and
 10         ($_.innerHTML -notlike "*Change*") -and
 11         ($_.innerHTML -like "*$month*")
 12     }).href
 13
 14 $links$links = ((Invoke-WebRequest l
```

**Comment by k-takata** [comment] 2018-10-27 00:54
Cannot reproduce. How did you copy and paste it? `"+p`, `:0put *`, Shift+Insert, etc.
Are the line numbers also pasted? or you added just for explanation?
Does it occur with more recent version? The latest version is 8.1.0497 now.

**Comment by chrisbra** [comment] 2018-11-05 21:09
closing for no feedback

**Closed as completed by chrisbra** 2018-11-05 21:09 UTC
Labels: needs feedback
