### ISSUE TITLE
netrw: wrong filetype when using :Ex after opening a file

### ISSUE THREAD

**Issue by zeertzjq** [vim/vim#12353] opened 2023-05-07 00:11 UTC
### Steps to reproduce

1. In the Vim repository, run `vim .`
2. Put cursor on `README.md` and press Enter to go to that file
3. Run `:Ex`
4. The netrw buffer has wrong highlight because it's filetype is markdown instead of netrw

This seems to be a regression from the latest netrw update.

### Expected behaviour

The netrw buffer's filetype is netrw and has correct highlight.

### Version of Vim

9.0.1520

### Environment

Operating system: Arch Linux
Terminal: kitty
Value of $TERM: xterm-kitty
Shell: fish

**Comment by Shane-XB-Qian** [comment] 2023-05-07 04:57
cannot reproduce it.
// maybe last vim patch 9.0.1519 fixed it? :rofl:

**Comment by gdupras** [comment] 2023-05-07 17:53
I can reproduce it with both 9.0.1518 and 9.0.1521.

**Comment by brammool** [comment] 2023-05-07 17:54
> ### Steps to reproduce
> 
> 1. In the Vim repository, run `vim .`
> 2. Put cursor on `README.md` and press Enter to go to that file
> 3. Run `:Ex`
> 4. The netrw buffer has wrong highlight because it's filetype is markdown instead of netrw
> 
> This seems to be a regression from the latest netrw update.
> 
> ### Expected behaviour
> 
> The netrw buffer's filetype is netrw and has correct highlight.

I cannot reproduce it.  I did notice that sometimes a remote file opened
by netrw doesn't get the filetype set.  E.g. for a ".patch" file the
filetype doesn't get set to "diff".  Not sure if that is related, I
haven't had time to investigate.


-- 
10e12 microphone == 1 megaphone

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by gdupras** [comment] 2023-05-07 18:29
I cannot reproduce the bug with 9.0.1578 (80406c2) but I CAN reproduce it with the runtime files update that comes right after (71badf9).

**Comment by zeertzjq** [comment] 2023-05-07 23:56
I can still reproduce with a 'runtimepath' that only contains paths in the Vim repository:

In fish
```fish
VIMRUNTIME=./runtime ./src/vim --clean -u (echo 'set nocompatible | syntax on' | psub) .
```

In bash or zsh
```bash
VIMRUNTIME=./runtime ./src/vim --clean -u <(echo 'set nocompatible | syntax on') .
```

`:echo &rtp` prints `./vimfiles,./runtime,./vimfiles/after`, where only `./runtime` (the Vim runtime directory) is an existing directory.

**Comment by chrisbra** [comment] 2023-05-08 08:50
looks like this is a duplicate of #12304 and #12339 (e.g. the [mentioned patch](https://github.com/vim/vim/issues/12304#issuecomment-1532022142) fixes it)

**Comment by dcousens** [comment] 2023-05-11 04:50
Thanks @chrisbra, [applying your patch](https://github.com/vim/vim/issues/12304#issuecomment-1532022142) to `/usr/share/vim/vim90/autoload/netrw.vim` resolved my system `vim` installation, hopefully distribution packages update soon :yellow_heart:

**Comment by johnridesabike** [comment] 2023-05-13 16:14
I'm not sure if this is the same or a different issue, but ever since this bug started happening I've also noticed that the netrw key maps stay set after opening a file from netrw. For example, if I open a file and press `i` then it will call `48_NetrwListStyle(1)` instead of entering insert mode.

This happens about half of the time, so I'm not sure which exact steps are needed to reproduce it. I'm happy to provide more info though, or open a new issue if necessary.

**Closed as completed** 2023-05-14 23:55 UTC
Labels: plugin-netrw, bug
