### ISSUE TITLE
[vim9script] Internal error when initializing an instance variable from another instance variable

### ISSUE THREAD

**Issue by lifepillar** [vim/vim#16344] opened 2024-12-30 10:52 UTC
### Steps to reproduce

Source any of these scripts:

```vim
vim9script

class X 
  var x: string = ''
  var Y: func(): string = () => this.x
endclass

var x0 = X.new('ok')
```

Or this silly one:

```vim
vim9script

class X 
  var x: string = this.x
endclass

var x0 = X.new('ok')
```

In either case, the result is:

```
Error detected while processing foo.vim[8]..function <SNR>62_X.new:
line    1:                                                                                                                                                 
E340: Internal error; if you can reproduce please report a bug
E685: Internal error: copy_tv(UNKNOWN)
```

### Expected behaviour

The second example should definitely throw an error (but not an internal error).

As for the former example, ideally that should compile, considering that the following variant of the script works:

```vim
vim9script

class X 
  var x: string = 'foobar'
  var y: string = this.x
endclass

var x0 = X.new('ok')
echo x0.y # 'foobar'
```

Given the limited usefulness of such a feature, however, I think that throwing an error complaining about initializing an instance variable with another instance variable would be acceptable, too.

### Version of Vim

9.1.980

### Environment

macOS 15.1
Terminal.app
xterm-256color
ZSH 5.9

**Comment by zzzyxwvut** [comment] 2024-12-30 17:05
This subject is also explored in #14411.

**Comment by chrisbra** [comment] 2024-12-31 10:40
closing as duplicate of #14411

**Closed as not planned by chrisbra** 2024-12-31 10:40 UTC
Labels: bug, vim9class
