### ISSUE TITLE
'textwidth' but with soft wrapping

### ISSUE THREAD

**Issue by ghost** [vim/vim#10852] opened 2022-08-05 19:59 UTC
## Issue
When writing markdown or plaintext, I often use the 'textwidth' option. But 'textwidth' invokes a hard wrap, which is sometimes undesirable. I have not found a method to 'soft wrap' at a certain width.

## Proposed solution

A 'set softwrap' option that stops 'textwidth' from inserting line breaks. (And likewise, a default 'set nosoftwrap' option that does the opposite.)

## Considered alternatives

I have seen some solutions on the internet, but they are quite hackey. Resizing the window width also works, but I often have to make my terminal window fullscreen when working with code or in the terminal. If some kind of 'softwrap' option is added, resizing the terminal window won't be necessary. It would be a small feature, but still a valuable quality-of-life improvement for many Vim users.

**Comment by bfrg** [comment] 2022-08-05 20:36
Duplicate of #10825 and #1847.

**Closed as completed** 2022-08-08 08:56 UTC
Labels: enhancement
