### ISSUE TITLE
vi -u NONE replace key capitalizes text

### ISSUE THREAD

**Issue by sickingfj** [vim/vim#10084] opened 2022-04-04 19:07 UTC
### Steps to reproduce

$ vi -u NONE, insert some text, move cursor halfway inserted text, press r, press shift-d and the text is capitalized to end of line

### Expected behaviour

the replaced character is replaced by the typed uppercase letter (as it is with lowercase letters)

### Version of Vim

VIM - Vi IMproved 8.1 (2018 May 18, compiled Feb 01 2022 09:16:32) Included patches: 1-2269, 3612, 3625, 3669, 3741 Modified by team+vim@tracker.debian.org Compiled by team+vim@tracker.debian.org Huge version without GUI.  Features included (+) or not (-): +acl               -farsi             -mouse_sysmouse    -tag_any_white +arabic            +file_in_path      +mouse_urxvt       -tcl +autocmd           +find_in_path      +mouse_xterm       +termguicolors +autochdir         +float             +multi_byte        +terminal -autoservername    +folding           +multi_lang        +terminfo -balloon_eval      -footer            -mzscheme          +termresponse +balloon_eval_term +fork()            +netbeans_intg     +textobjects -browse            +gettext           +num64             +textprop ++builtin_terms    -hangul_input      +packages          +timers +byte_offset       +iconv             +path_extra        +title +channel           +insert_expand     -perl              -toolbar +cindent           +job               +persistent_undo   +user_commands -clientserver      +jumplist          +postscript        +vartabs -clipboard         +keymap            +printer           +vertsplit +cmdline_compl     +lambda            +profile           +virtualedit +cmdline_hist      +langmap           -python            +visual +cmdline_info      +libcall           +python3           +visualextra +comments          +linebreak         +quickfix          +viminfo +conceal           +lispindent        +reltime           +vreplace +cryptv            +listcmds          +rightleft         +wildignore +cscope            +localmap          -ruby              +wildmenu +cursorbind        -lua               +scrollbind        +windows +cursorshape       +menu              +signs             +writebackup +dialog_con        +mksession         +smartindent       -X11 +diff              +modify_fname      +sound             -xfontset +digraphs          +mouse             +spell             -xim -dnd               -mouseshape        +startuptime       -xpm -ebcdic            +mouse_dec         +statusline        -xsmp +emacs_tags        +mouse_gpm         -sun_workshop      -xterm_clipboard +eval              -mouse_jsbterm     +syntax            -xterm_save +ex_extra          +mouse_netterm     +tag_binary         +extra_search      +mouse_sgr         -tag_old_static        system vimrc file: "$VIM/vimrc"      user vimrc file: "$HOME/.vimrc"  2nd user vimrc file: "~/.vim/vimrc"       user exrc file: "$HOME/.exrc"        defaults file: "$VIMRUNTIME/defaults.vim"   fall-back for $VIM: "/usr/share/vim" Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -Wdate-time  -g -O2 -fdebug-prefix-map=/build/vim-9EpYYi/vim-8.1.2269=. -fstack-protector-strong -Wformat -Werror=format-security -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        Linking: gcc   -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim        -lm -ltinfo -lnsl  -lselinux  -lcanberra -lacl -lattr -lgpm -ldl     -L/usr/lib/python3.8/config-3.8-x86_64-linux-gnu -lpython3.8 -lcrypt -lpthread -ldl -lutil -lm -lm      

### Environment

Operating system: Ubuntu 20.04
Terminal: xterm
Shell: /bin/bash

**Comment by lacygoill** [comment] 2022-04-04 19:34
Duplicate of https://github.com/vim/vim/issues/6809

---

A fix is given in the patch [8.2.1549](https://github.com/vim/vim/releases/tag/v8.2.1549)

---

> VIM - Vi IMproved 8.1 (2018 May 18, compiled Feb 01 2022 09:16:32) Included patches: 1-2269, ...

[8.1.2269](https://github.com/vim/vim/releases/tag/v8.1.2269) is more than 2 years old.  Many bugs have been fixed in the meantime.  Try to update your Vim version.

**Comment by chrisbra** [comment] 2022-04-05 06:57
please update your vim and always reproduce with latest master.

**Closed as completed by chrisbra** 2022-04-05 06:57 UTC

**Comment by sickingfj** [comment] 2022-04-05 09:59
Thanks for your comments. However, this is the default version that comes with Ubuntu 20.04. Send the issue there?
