### ISSUE TITLE
PHP syntax broken for heredoc quotes

### ISSUE THREAD

**Issue by tlathm** [vim/vim#12952] opened 2023-08-29 13:45 UTC
### Steps to reproduce

Edit any PHP code that uses heardoc syntax with escaped dollar signs ($)

### Expected behaviour

The following PHP code:

    print <<<END
    \$somevar
    END;

...highlights the "$somevar" as a variable and not the literal text. I know this used to work correctly, and I'm unclear as to specifically which version broke it.

### Version of Vim

9.0.1503

### Environment

Gentoo Linux
TERM=rxvt
Shell: bash

**Comment by dkearns** [comment] 2023-08-29 14:06
If you haven't already done so you should try approaching the maintainer, listed in the header, first.

https://github.com/TysonAndre/php-vim-syntax

**Comment by stefanos82** [comment] 2023-08-29 14:19
This is an expected behavior; please, do not confused Heredoc and Nowdoc.

If you want to highlight it as literal text, just enclose your opened Nowdoc in single quotes:

![image](https://github.com/vim/vim/assets/1777466/c74ae78e-5072-4fa4-a84a-24bc88cf4b6b)

**Comment by chrisbra** [comment] 2023-08-29 14:26
closing then.

**Closed as not planned by chrisbra** 2023-08-29 14:26 UTC
Labels: bug

**Comment by tlathm** [comment] 2023-08-29 18:47
I get the difference between the two, but have to disagree on the assessment here when it comes to the specific case where the dollar sign is escaped. Even a simple double quoted string correctly shows that as text and not a highlighted variable:

    <?php
    print "This is \$somevar\n";

That gets handled correctly. How is the current behavior within a HEREDOC correct?

**Comment by stefanos82** [comment] 2023-08-29 19:11
Replace `END` with another word, for instance `EOD` and it should behave as expected; but please, read again very closely the whole https://www.php.net/manual/en/language.types.string.php because it contains valuable information in it, especially around string quotes versus double quotes and their parsing mechanism.

I like calling such information **_hidden pearls_**.

**Comment by stefanos82** [comment] 2023-08-30 11:47
> I don't understand why using that specific string is highlighted differently however(?), and I don't see anything in that documentation related specifically to the END quoting string. From a PHP standpoint it functions identically to any other.

I presume the word `end` (case insensitive) is being recognized from PHP syntax as part of SQL support (`BEGIN ... END`); it's enabled by default if I'm not mistaken.

You can find more in Vim via `:h ft-php-syntax`.

**Comment by tlathm** [comment] 2023-08-30 14:25
Ahhh...OK, that makes total sense. As you see above I've logged a bug with the maintainer. I'll add to that and we'll see what he says. I actually wasn't aware you could even call functions using names in upper case like END() which for me is sort of horrifying :D. Thanks a million for the clarification!
