### ISSUE TITLE
Tab size is weird if there is above virtual text

### ISSUE THREAD

**Issue by tcx4c70** [vim/vim#16161] opened 2024-12-03 12:50 UTC
### Steps to reproduce

1. Save the following script as a file (e.g. `repro.vim`):
```vim
" 4 is easier to count than 8 :)
set ts=4 sw=4 sts=4 noet

" just to make the tab size visible, no help to repro the issue
set listchars=tab:<->
set list

call setline(1, "    some text")
call prop_type_add( 'Normal', { 'highlight': 'Normal' } )
call prop_add(1, 0, { 'type': 'Normal', 'text_align': 'above', 'text': "some virtual text", 'text_padding_left': 4 })
```
2. Run `vim --clean`
3. `:source repro.vim`

### Expected behaviour

There should be 4 char width before `some text` and the 2 `s` should be aligned, like:
```
    some virtual text
<-->some text
```

### Version of Vim

9.1.895

### Environment

OS: Fedora 41
Terminal: iTerm2 (using ssh to connect to the Fedora)
Value of $TERM: xterm-256color
Shell: zsh 5.9

**Comment by tcx4c70** [comment] 2024-12-03 12:53
The content I get:
<img width="298" alt="图片" src="https://github.com/user-attachments/assets/b871daba-7994-4be4-8764-df45310dc3eb">

**Comment by zeertzjq** [comment] 2024-12-03 13:34
Duplicate of #12232

**Closed as completed by zeertzjq** 2024-12-03 13:34 UTC
Labels: duplicate, bug
