### ISSUE TITLE
there is no OSC 7 sequence when terminal is started in gvim

### ISSUE THREAD

**Issue by coiby** [vim/vim#10853] opened 2022-08-06 01:13 UTC
### Steps to reproduce

1. start gvim as GUI application (gtk-launch /usr/share/applications/gvim.desktop)
2. Enable autoshelldir i.e. `:set autoshelldir` which will automatically set terminal buffer's working directory to shell's pwd based on the OSC 7 sequence emitted by shell
3. start a terminal e.g `:terminal`
4. change working directory to /usr/bin
5. run `<C-w>:pwd`

### Expected behaviour

The terminal buffer's working directory is changed to "/usr/bin".

### Version of Vim

9.0 Included patches: 1-49

### Environment

Operating system: Fedora
shell: bash or zsh

### Notes
1. If I manually print OSC 7 sequence by `echo -ne $'\\e\]7;file:///usr/bin\\a' `, the terminal buffer's working directory is changed to "/usr/bin" as expected. So the problem is somehow OSC 7 sequence is not emitted. 
2. If I start gvim in a terminal emulator e.g. gnome-terminal or xfce4-terminal and create a terminal in gvim, autoshelldir works as expected. 
3. /usr/share/applications/gvim.desktop has specified `Terminal=false`. If I change it to `Terminal=true`, autoshelldir also works as expected. 
4. If I create a terminal buffer in vim instead of gvim, autoshelldir also works.

**Comment by brammool** [comment] 2022-08-06 10:34
> ### Steps to reproduce
> 
> 1. start gvim as GUI application (don't start gvim in terminal)
> 2. Enable autoshelldir i.e. `:set autoshelldir` which will automatically set terminal buffer's working directory to shell's pwd based on the OSC 7 sequence emitted by shell
> 3. start a terminal e.g `:terminal`
> 4. change working directory to /usr/bin
> 5. run `:pwd`
> 
> ### Expected behaviour
> 
> The terminal buffer's working directory is changed to "usr/bin".

You need more than setting 'autoshelldir', sending the escape sequence
also needs to be setup.  For me I didn't manage to make it work today.

Your reproduction steps are a bit vague.  E.g., you probably press
CTRL-W before ":pwd".

How do you start gvim exactly?


-- 
Vi is clearly superior to emacs, since "vi" has only two characters
(and two keystrokes), while "emacs" has five.  (Randy C. Ford)

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment] 2022-08-06 14:28
> You need more than setting 'autoshelldir', sending the escape sequence
> also needs to be setup.

In a Vim init file:
```vim
vim9script
def g:Tapi_exe(_, cmd: string)
    # Run an arbitrary Ex command.
    # `:silent` is useful to prevent `:lcd` from printing the new Vim CWD on the
    # command-line.
    execute 'silent ' .. cmd
enddef
```
In a bash init file:
```bash
if [[ -n "$VIM_TERMINAL" ]]; then
    PROMPT_COMMAND="__vte_prompt_command"
    function __vte_prompt_command() {
      local pwd='~'
      [ "$PWD" != "$HOME" ] && pwd=${PWD/#$HOME\//\~\/}
      printf '\033]51;["call", "Tapi_exe", "lcd %q"]\007' "$PWD"
    }
fi
```
In a zsh init file:
```zsh
if [[ -n "$VIM_TERMINAL" ]]; then
    autoload -Uz add-zsh-hook
    add-zsh-hook -Uz chpwd vim_sync_CWD
    function vim_sync_CWD() {
        printf '\033]51;["call", "Tapi_exe", "lcd %q"]\007' "$PWD"
    }
fi
```
---

The help at [`:help 'autoshelldir'`](https://vimhelp.org/options.txt.html#%27autoshelldir%27) could be improved:

   > You need proper setting-up, so whenever the shell's pwd changes an OSC 7
   > escape sequence will be emitted. For example, on Linux, you can source
   > /etc/profile.d/vte.sh in your shell profile if you use bash or zsh.

First, there is no `vte.sh` file on my Ubuntu 20.04 machine.
But there is a `vte-2.91.sh` file, which can be found with:

    $ locate --regex '/vte.*\.sh'

Second, sourcing this file doesn't seem to work.  The code that I posted earlier does work.

---

It doesn't work in the fish shell:
```fish
if test -n "$VIM_TERMINAL"
    function chpwd --on-variable PWD
        printf '\033]51;["call", "Tapi_exe", "lcd %q"]\007' "$PWD"
    end
end
```
Not sure why, nor how to debug this.

**Comment by lacygoill** [comment] 2022-08-06 14:36
> It doesn't work in the fish shell:

That's because the `printf` builtin from fish doesn't support the `%q` format specifier.  Fixed code:
```fish
if test -n "$VIM_TERMINAL"
    function vim_sync_PWD --on-variable PWD
        printf -- '\033]51;["call", "Tapi_exe", "lcd %s"]\007' "$PWD"
    end
end
```

**Comment by lacygoill** [comment] 2022-08-06 14:51
To the OP, see also [`:help terminal-api`](https://vimhelp.org/terminal.txt.html#terminal-api).

Might be worth adding a link to this help tag at [`:help 'autoshelldir'`](https://vimhelp.org/options.txt.html#%27autoshelldir%27).

**Comment by lacygoill** [comment] 2022-08-06 23:57
> Might be worth adding a link to this help tag at :help 'autoshelldir'.

How about this patch:
```diff
diff --git a/runtime/doc/options.txt b/runtime/doc/options.txt
index 55c2146b9..cdedd65de 100644
--- a/runtime/doc/options.txt
+++ b/runtime/doc/options.txt
@@ -808,9 +808,37 @@ A jump table for the options with a short description can be found at |Q_op|.
 	When on, Vim will change the current working directory whenever you
 	change the directory of the shell running in a terminal window. You
 	need proper setting-up, so whenever the shell's pwd changes an OSC 7
-	escape sequence will be emitted. For example, on Linux, you can source
-	/etc/profile.d/vte.sh in your shell profile if you use bash or zsh.
+	escape sequence will be emitted.  For example, in a Vim init file: >
+	def g:Tapi_exe(_, cmd: string)
+	    execute 'silent ' .. cmd
+	enddef
+<
+	And, in a bash init file: >
+        if [[ -n "$VIM_TERMINAL" ]]; then
+            PROMPT_COMMAND='_vim_sync_PWD'
+            function _vim_sync_PWD() {
+              printf '\033]51;["call", "Tapi_exe", "lcd %q"]\007' "$PWD"
+            }
+        fi
+<
+	Or, for zsh: >
+	if [[ -n "$VIM_TERMINAL" ]]; then
+	    autoload -Uz add-zsh-hook
+	    add-zsh-hook -Uz chpwd _vim_sync_PWD
+	    function _vim_sync_PWD() {
+		printf '\033]51;["call", "Tapi_exe", "lcd %q"]\007' "$PWD"
+	    }
+	fi
+<
+	Or, for fish: >
+	if test -n "$VIM_TERMINAL"
+	    function _vim_sync_PWD --on-variable=PWD
+		printf '\033]51;["call", "Tapi_exe", "lcd %s"]\007' "$PWD"
+	    end
+	end
+<
 	When the parsing of the OSC sequence fails you get *E1179* .
+	See |terminal-api| for how to build a valid one.
 
 				*'arabic'* *'arab'* *'noarabic'* *'noarab'*
 'arabic' 'arab'		boolean (default off)
```

**Comment by brammool** [comment] 2022-08-07 10:54
> > Might be worth adding a link to this help tag at :help 'autoshelldir'.
> 
> How about this patch:

Hmm, this is at 'autoshelldir', but it doesn't use that option, right?
Putting it at terminal-api makes more sense.

g:Tapi_exe() would execute any command the shell sends, that doesn't
seem safe.  Only sending the argument and executing "lcd" would be
better.  I'll include it like that.


-- 
hundred-and-one symptoms of being an internet addict:
266. You hear most of your jokes via e-mail instead of in person.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment] 2022-08-07 11:20
> Hmm, this is at 'autoshelldir', but it doesn't use that option, right?

Oh right.  It doesn't even use `'autoshelldir'`.  No idea how the latter works.  I guess setting the option lets us eliminate `:lcd dir` (run by `g:Tapi_exe()` or something similar).  But the help suggests that the shell needs to be configured for the OSC 7 sequence to be sent to the Vim job.  That's exactly what the suggested shell code does.

But yes, it would make more sense at [`:help terminal-api`](https://vimhelp.org/terminal.txt.html#terminal-api).  Provided we add a reference to this tag at [`:help 'autoshelldir'`](https://vimhelp.org/options.txt.html#%27autoshelldir%27) (unless I completely misunderstood the issue...).  So that the user knows what to do when reading this sentence:

   > You need proper setting-up, so whenever the shell's pwd changes an OSC 7
   > escape sequence will be emitted.

In particular if they can't find a `vte.sh` script on their machine; or they can but it doesn't work as expected.

**Comment by lacygoill** [comment] 2022-08-07 11:56
OK, this patch is simpler, does assume that `'autoshelldir'` is set, and explains how to set up the shell:
```diff
diff --git a/runtime/doc/options.txt b/runtime/doc/options.txt
index 55c2146b9..065073202 100644
--- a/runtime/doc/options.txt
+++ b/runtime/doc/options.txt
@@ -810,6 +810,30 @@ A jump table for the options with a short description can be found at |Q_op|.
 	need proper setting-up, so whenever the shell's pwd changes an OSC 7
 	escape sequence will be emitted. For example, on Linux, you can source
 	/etc/profile.d/vte.sh in your shell profile if you use bash or zsh.
+	Alternatively, in a bash init file: >
+	if [[ -n "$VIM_TERMINAL" ]]; then
+	    PROMPT_COMMAND='_vim_sync_PWD'
+	    function _vim_sync_PWD() {
+		printf "\033]7;file://%s\033\\" "$PWD"
+	    }
+	fi
+<
+	Or, in a zsh init file: >
+	if [[ -n "$VIM_TERMINAL" ]]; then
+	    autoload -Uz add-zsh-hook
+	    add-zsh-hook -Uz chpwd _vim_sync_PWD
+	    function _vim_sync_PWD() {
+		printf "\033]7;file://%s\033\\" "$PWD"
+	    }
+	fi
+<
+	In a fish init file: >
+	if test -n "$VIM_TERMINAL"
+	    function _vim_sync_PWD --on-variable=PWD
+		printf "\033]7;file://%s\033\\" "$PWD"
+	    end
+	end
+<
 	When the parsing of the OSC sequence fails you get *E1179* .
 
 				*'arabic'* *'arab'* *'noarabic'* *'noarab'*
```

**Comment by coiby** [comment] 2022-08-07 12:03
> You need more than setting 'autoshelldir', sending the escape sequence also needs to be setup. For me I didn't manage to make it work today. 

I think escape sequence has already been setup because if I start gvim in a terminal emulator, it works as expected.

> Your reproduction steps are a bit vague. E.g., you probably press CTRL-W before ":pwd". 

Yes, I should have said "press CTRL-W" before ":pwd".

> How do you start gvim exactly?

Fedora provides /usr/share/applications/gvim.desktop. I use dmenu to launch this .desktop. Btw, this .desktop file has `Terminal=false`. If I change it to `Terminal=true", the terminal buffer's working directory could be changed to "/usr/bin" if I "cd /usr/bin".

**Comment by lacygoill** [comment] 2022-08-07 12:14
> I think escape sequence has already been setup because if I start gvim in a terminal emulator, it works as expected.

Could you compare the difference in the output of `env(1)` in a terminal buffer when gVim is started from a terminal emulator, vs when it's started without?

    # start gVim from a terminal
    $ env >/tmp/from_terminal

    # start gVim from GUI
    $ env >/tmp/from_GUI

    $ vimdiff /tmp/from_{terminal,GUI}

**Comment by coiby** [comment] 2022-08-07 12:34
> > I think escape sequence has already been setup because if I start gvim in a terminal emulator, it works as expected.
> 
> Could you compare the difference in the output of `env(1)` in a terminal buffer when gVim is started from a terminal emulator vs when it's started from the GUI?

After reading your previous reply about vte.sh, I realize vte.sh hasn't instructed shell to emit OSC 7 sequence because it requires running under vte,
```sh
# Not bash or zsh?
[ -n "${BASH_VERSION:-}" -o -n "${ZSH_VERSION:-}" ] || return 0

# Not an interactive shell?
[[ $- == *i* ]] || return 0

# Not running under vte?
# [ "${VTE_VERSION:-0}" -ge 3405 ] || return 0

# TERM not supported?
case "$TERM" in
    xterm*|vte*|gnome*) :;;
    *) return 0 ;;
esac

__vte_osc7 () {
  printf "\033]7;file://%s%s\033\\" "${HOSTNAME}" "$(/usr/libexec/vte-urlencode-cwd)"
}
```

If I start gvim in gnome-terminal or xfce4-terminal, vte.sh works because gnome-terminal or xce4-terminal exactly uses VTE.

**Comment by brammool** [comment] 2022-08-07 12:41
> OK, this patch is simpler, does assume that `'autoshelldir'` is set,
> and explains how to set up the shell:

Thanks.  I can include this and the other one as well.


-- 
Two fish in a tank. One says to the other:
"Do you know how to drive this thing?"

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by Shane-XB-Qian** [comment] 2022-08-08 01:49
the original ticket is here: #6290 
and @coiby was the `asd` PR creator.

issues:
1. https://github.com/vim/vim/pull/6290#issuecomment-810158590
2.
```sh
# TERM not supported?
case "$TERM" in
    xterm*|vte*|gnome*) :;;
    *) return 0 ;;
esac
```
this probably was added in ubuntu 22.04, but seems no such in the previous version

the `asd` option as the doc already said : `need proper setting-up`, or dependences.
// that already said that was not a reliable option, or user manual doing sth to make it instead of it.

**Comment by lacygoill** [comment] 2022-09-04 23:47
Now that [`:help 'autoshelldir'`](https://vimhelp.org/options.txt.html#%27autoshelldir%27) has been updated to include 3 snippets to set up bash, zsh and fish, can the issue be closed?  I've just tested the instructions given in the OP:

   - start gVim as GUI application (from whisker menu in XFCE)
   - execute `:set autoshelldir`
   - start a `:terminal`
   - check that the current working directory is `/home/user` (C-W : pwd Enter)
   - in the shell, change the working directory to `/usr/bin` (`$ cd /usr/bin`)
   - in Vim, check that the current working directory has been automatically synchronized with the shell (C-W : pwd Enter)

The result is `/usr/bin`, as expected; provided that we use bash and make it source this code given in the help:
```bash
if [[ -n "$VIM_TERMINAL" ]]; then
    PROMPT_COMMAND='_vim_sync_PWD'
    function _vim_sync_PWD() {
        printf '\033]7;file://%s\033\\' "$PWD"
    }
fi
```

**Comment by chrisbra** [comment] 2022-09-05 07:13
closing then.

**Closed as completed by chrisbra** 2022-09-05 07:13 UTC
Labels: bug
