### ISSUE TITLE
Enter key not working inside tmux inside terminal buffer

### ISSUE THREAD

**Issue by bstaletic** [vim/vim#2161] opened 2017-09-26 18:11 UTC
Steps to reproduce:

- `vim`
- `:term`
- `tmux`
- `ls<CR>`

What I expected to happen:
The output of `ls` to be shown.

What happened:
`<CR>` got completely ignored.

Details about thte environment:

- Default shell: zsh
- Vim version: 8.0.1153
- $TERM inside tmux: `screen-256color`

**Comment by brammool** [comment] 2017-09-26 18:53
Boris Staletic wrote:

> Steps to reproduce:
> 
> - `vim`
> - `:term`
> - `tmux`
> - `ls<CR>`
> 
> What I expected to happen:
> The output of `ls` to be shown.
> 
> What happened:
> `<CR>` got completely ignored.
> 
> Details about thte environment:
> 
> - Default shell: zsh
> - Vim version: 8.0.1153
> - $TERM inside tmux: `screen-256color`

Works fine for me (Ubuntu).

-- 
hundred-and-one symptoms of being an internet addict:
206. You religiously respond immediately to e-mail, while ignoring
     your growing pile of snail mail.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by bstaletic** [comment] 2017-09-26 19:05
I'm on Gentoo, but that shouldn't cause any issues. How can I investigate this further?

**Comment by bstaletic** [comment] 2017-09-26 19:24
I've done some further testing.

If I run:
- `:term bash`
- `tmux` (inside the terminal buffer)
- Enter works.

But if I run:
- `:term zsh`
- `tmux`
- Enter is ignored.

Note: In both cases thte shell inside tmux is zsh.

**Comment by ZyX-I** [comment] 2017-09-26 19:27
Try using `:term zsh -f`, should make it sure that problem is (not) in your config.

**Comment by chrisbra** [comment] 2017-09-26 19:29
probably a duplicate of #1998 and #2031

**Comment by bstaletic** [comment] 2017-09-26 19:31
> Try using :term zsh -f, should make it sure that problem is (not) in your config.

On the plus side, I've learnt a new zsh flag.
On the minus side, it it is something in my config causing this.

I will try to find out what part of the config is causing this behaviour.

**Comment by bstaletic** [comment] 2017-09-26 19:38
Heh, it was the very last line causing the problem.

```zsh
[[ -z $SSH_CONNECTION && -z $TMUX && $(tty) != "/dev/tty1" ]] && (tmux attach || tmux new-session)
```

**Comment by bstaletic** [comment] 2017-09-26 20:43
I've rewritten my config and now it doesn't conflict vim's terminal.

If anyone is interested, here's how the config looks right now:
```zsh
if [[ $TERM == st* ]]; then
	tmux attach -t st || tmux new-session -t st
elif [[ -n $SSH_CONNECTION ]]; then
	tmux attach  -t ssh || tmux new-session -t ssh
fi
```

I'm not closing this issue as someone may want to look further into this.
If someone does, I'll gladly help. If not, feel free to close this.

**Closed as completed** 2017-09-29 20:40 UTC
